CMakeLists.txt

This is not yet complete as it doesn't perform the emscripten
build stage, nor does it attempt to run tests.
This is work in progress on issue #2.

Initial start on CMakeLists.txt.

---

CMakeLists.txt
src/pass.cpp
src/wasm.h

Deleting a Pass* wasn't doing the right thing.

Add missing virtual dtor

---

src/bits.h
src/wasm-interpreter.h

Make bits.h a bit more capable, make wasm-interpreter.h a bit more simple, use "a bit" a bit too much.
N.B.: Bit is the best character in the original Tron.

Simplify the bit functions... a bit!

---

test/s2wasm_known_gcc_test_failures.txt

Negative relocations fixed in 49bc6a370abf20ee2b2749ee3ca73373bfeceeb7, fixes #52.

Update expected GCC test failures

---

CMakeLists.txt
src/s2wasm-main.cpp
src/support/command-line.cpp
src/support/command-line.h

This only moves things, no functional change yet.

Start moving command-line processing to libsupport.a

---

src/s2wasm-main.cpp
src/support/command-line.cpp
src/support/command-line.h

This should allow other programs to use the same command-line support.

Generalize command-line parsing more.

---

update.py

@kripken asked if test/lkgr could be updated only if the downloaded content is different. This patch does just that.

update.py: update only if needed

---

src/s2wasm.h

Handle .skip

---

.travis.yml
check.py

Start to add testing in travis

---

.travis.yml
scripts/__init__.py
scripts/storage.py
scripts/support.py
update.py

Patches such as #112 could use them.

Factor out some support code

---

src/wasm-binary.h

Design document seems to have this backyards compared with the v8 implementation.

Function section has the flags before the signature index.

---

check.py

Only run WASM_BACKEND tests if it does.

Detect whether vanilla emcc works

---

src/asm2wasm.h
src/pass.h
src/passes/LowerIfElse.cpp
src/passes/LowerInt64.cpp
src/passes/MergeBlocks.cpp
src/passes/RemoveImports.cpp
src/passes/RemoveUnusedBrs.cpp
src/passes/RemoveUnusedNames.cpp
src/passes/SimplifyLocals.cpp
src/s2wasm.h
src/wasm-binary.h
src/wasm-interpreter.h
src/wasm-validator.h
src/wasm.h
src/wasm2asm.h
test/example/find_div0s.cpp

This is an updated version of https://github.com/WebAssembly/binaryen/pull/96 that addresses some of @jfbastien comments. I opened a new PR so that I wouldn't lose the review history from the previous PR (I rebased the commits and would have required to do a force push).
I still need to do some cleanup, so putting this up for review to make sure I'm on the right path.

Use LLVM style static polymorphism for AST Visitors

---

src/wasm.h

This makes other code less verbose

Name: support std::string ctor

---

src/parsing.h
src/support/utilities.h
src/wasm.h
test/llvm_autogenerated/immediates.wast

As discussed with @binji and @sunfish in https://github.com/WebAssembly/sexpr-wasm-prototype/issues/28

Output NaN payloads only

---

README.md

Small change, just to help new binaryen experimenters. I joined the W3C wasm group as PAustin. Hope its not to small.

Update README example for test name change.

---

src/wasm-interpreter.h

This makes it easier to debug, the message looks like:
```
[trap final > memory: 1 > 0]
```

Shell: improve memory trap

---

src/wasm-s-parser.h

Fix out-of-bounds read

---

src/binaryen-shell.cpp

Older tsan doesn't like longjmp. Use throw.

longjmp -> throw

---

src/s2wasm.h
src/wasm.h
test/dot_s/memops.wast
test/llvm_autogenerated/byval.wast
test/llvm_autogenerated/i32-load-store-alignment.wast
test/llvm_autogenerated/i64-load-store-alignment.wast
test/llvm_autogenerated/load-store-i1.wast
test/llvm_autogenerated/offset.wast
test/llvm_autogenerated/store-trunc.wast
test/s2wasm_known_binaryen_shell_test_failures.txt

It was broken.
We also didn't write stores properly either!

Store parsing fix

---

src/binaryen-shell.cpp
src/wasm-binary.h
src/wasm-interpreter.h
src/wasm-validator.h

Adds interpreter support etc., and makes the new spec test pass.
still wip

Fully support start in wasm modules

---

README.md

Tiny fix in readme file

---

CMakeLists.txt
auto_update_tests.py
check.py
src/asm2wasm-main.cpp
src/binaryen-shell.cpp
src/pass.cpp
src/pass.h
src/passes/Print.cpp
src/s2wasm-main.cpp
src/s2wasm.h
src/support/file.h
src/wasm-dis.cpp
src/wasm-printing.h
src/wasm.h
test/example/find_div0s.cpp

As suggested in #172.
This makes things more modular, and easier to add custom printing options (printing with name stripped, print sexpr vs. the final text format, etc.).

Move printing to a pass

---

CMakeLists.txt
src/passes/LowerCase.cpp
test/passes/lower-case.txt
test/passes/lower-case.wast

This is useful for comparing switches with and without cases. It also turns out to be simple to do, a nice example of the pass system I think.

Add a optional pass to lower cases

---

src/wasm-s-parser.h

This fixes the parsing of branch index targets in switches:
```
(func $nested (param i32) (result i32)
(block
(block
(block
(tableswitch (get_local 0)
(table (br 0) (br 1) (br 2))
(br 3)
)
(return (i32.const 1))
)
(return (i32.const 2))
)
(return (i32.const 3))
)
(return (i32.const 4))
)
```
This test case was added (https://github.com/WebAssembly/spec/commit/027f4453428bda7c4960caf6d6931b0b0849716b) 12 days ago and somehow didn't cause `check.py` to fail.

Fix switch offsets.

---

src/wasm-interpreter.h
src/wasm.h

And we can update the spec tests after doing that.

Grow memory returns a value now

---

check.py
src/wasm-s-parser.h

New spec changes

---

README.md
check.py

Matches the new argument and config in  https://github.com/kripken/emscripten/pull/4135/

Update check.py and documentation to match emscripen PR4135

---

src/js/wasm.js-post.js

Integrate wasm fixes

---

src/js/wasm.js-post.js

We need this to merge vanilla into emscripten incoming, after which we can just use incoming there, no more side branch.

Move to a cleaner way of emcc.py integrating with wasm.js-post.js

---

src/js/wasm.js-post.js
src/s2wasm.h
test/dot_s/asm_const.wast
test/dot_s/memops.wast

Fix up exports when arriving from wasm backend output

---

.travis.yml
scripts/spidermonkify.py

Re-enable flake8

---

README.md

Referencing https://github.com/WebAssembly/binaryen/pull/252#discussion-diff-56397106

switched HTML-link to Markdown-Link

---

src/asm2wasm.h
src/support/command-line.cpp
src/support/command-line.h

Make --debug a boolean

---

check.py
src/asm2wasm.h
test/memorygrowth.asm.js
test/memorygrowth.fromasm
test/memorygrowth.fromasm.imprecise
test/unit.asm.js
test/unit.fromasm
test/unit.fromasm.imprecise

Memory growth fixes

---

src/asm2wasm.h
test/emcc_O2_hello_world.fromasm
test/emcc_O2_hello_world.fromasm.imprecise
test/emcc_hello_world.fromasm
test/emcc_hello_world.fromasm.imprecise
test/memorygrowth.fromasm
test/memorygrowth.fromasm.imprecise
test/two_sides.fromasm
test/two_sides.fromasm.imprecise
test/unit.fromasm
test/unit.fromasm.imprecise

Noticed by @sunfishcode in https://bugzilla.mozilla.org/show_bug.cgi?id=1258458

Use eqz in asm2wasm

---

src/js/wasm.js-post.js
test/grow_memory.cpp
test/grow_memory.emcc
test/grow_memory.txt

This works at least in the interpreter. Not sure if browsers have native support yet. Fixes #270.

Fix and test memory growth

---

src/support/safe_integer.cpp

Remove bogus asserts from safe_integer casts

---

src/emscripten-optimizer/istring.h
src/emscripten-optimizer/simple_ast.h

Safety stuff

---

src/parsing.h
src/wasm-interpreter.h
src/wasm.h

Fix the build with GCC 5.3.1 and Clang 3.8.0.

---

src/asm2wasm-main.cpp
src/binaryen-shell.cpp
src/s2wasm-main.cpp
src/support/file.cpp
src/support/file.h
src/wasm-as.cpp
src/wasm-dis.cpp
src/wasm2asm-main.cpp

Followup for #303 
cc @jfbastien @binji

Refactor file flags into enums

---

src/asm2wasm.h
test/min.asm.js
test/min.fromasm
test/min.fromasm.imprecise
test/unit.asm.js
test/unit.fromasm
test/unit.fromasm.imprecise

Pattern-match bitcasts in asm.js to wasm unary ops.
Still need to benchmark.

asm2wasm opts

---

src/asm2wasm.h
src/ast_utils.h
src/binaryen-shell.cpp
src/passes/MergeBlocks.cpp
src/passes/OptimizeInstructions.cpp
src/passes/PostEmscripten.cpp
src/passes/Print.cpp
src/passes/RemoveUnusedBrs.cpp
src/passes/SimplifyLocals.cpp
src/s2wasm.h
src/wasm-s-parser.h
src/wasm-traversal.h
src/wasm.h
test/emcc_O2_hello_world.fromasm
test/emcc_O2_hello_world.fromasm.imprecise
test/emcc_hello_world.fromasm
test/emcc_hello_world.fromasm.imprecise
test/example/find_div0s.cpp
test/memorygrowth.fromasm
test/memorygrowth.fromasm.imprecise
test/min.fromasm
test/min.fromasm.imprecise
test/passes/simplify-locals.txt
test/passes/simplify-locals.wast
test/two_sides.fromasm
test/two_sides.fromasm.imprecise
test/unit.fromasm
test/unit.fromasm.imprecise

More optimizations

---

src/asm_v_wasm.h
src/s2wasm.h
src/wasm-builder.h

Currently it's not called anywhere.
The bulk of this change is refactoring to add makeFunction, makeCallIndirect, and makeReturn
to wasm::Builder, and make S2wasmBuilder call it.

Add a method to generate a dyncall thunk

---

.travis.yml

Don't allow tsan to fail

---

src/emscripten-optimizer/parser.h
test/unit.asm.js
test/unit.fromasm
test/unit.fromasm.imprecise
test/unit.wast
test/unit.wast.fromBinary

Fixes typo in hex number parsing in asm2wasm.

---

src/wasm-traversal.h

This is useful especially after global indexing, but also in general, many passes want to look at the current function.

Let traversals access the current function

---

src/passes/SimplifyLocals.cpp
test/emcc_hello_world.fromasm
test/emcc_hello_world.fromasm.imprecise
test/passes/simplify-locals.txt
test/unit.fromasm.imprecise

In particular, handle trivial dead stores.

Do some TODOs in SimplifyLocals

---

src/s2wasm-main.cpp
src/s2wasm.h
src/support/utilities.h
src/wasm-link.h
src/wasm-linker.h

This is the first of a couple of refactorings in for #370 
No functionality change, and minimal code change to make it work.

Factor linker-related functionality of S2WasmBuilder into its own class

---

src/support/utilities.h
src/wasm-linker.h

Still making things nicer for #370 
Follow-on from #372. Probably we should do even better for error
handling, and that might mean a cpp file in support, but for now this is
a small improvement.

Move Fatal into utilities.h

---

bin/wasm.js
src/wasm-binary.h

We had a few of them flipped.
With this in, spidermonkey can execute binaryen binaries.

Fix conversion opcodes

---

src/mixed_arena.h
src/wasm-binary.h

Not efficiently yet, maybe we'll never need them to be efficient, but at least allow them.

Allow allocations on side threads

---

src/passes/RemoveUnusedBrs.cpp
test/emcc_O2_hello_world.fromasm
test/emcc_O2_hello_world.fromasm.imprecise
test/emcc_hello_world.fromasm
test/emcc_hello_world.fromasm.imprecise
test/hello_world.fromasm
test/hello_world.fromasm.imprecise
test/memorygrowth.fromasm
test/memorygrowth.fromasm.imprecise
test/min.fromasm
test/min.fromasm.imprecise
test/passes/remove-unused-brs.txt
test/passes/remove-unused-brs.wast
test/two_sides.fromasm
test/two_sides.fromasm.imprecise
test/unit.fromasm
test/unit.fromasm.imprecise

Optimize out brs with value, and optimize out returns.

More control flow optimization

---

src/ast_utils.h
src/wasm-binary.h

We were emitting unnecessary blocks.

Improve emitting of ifs in binary format

---

src/ast_utils.h
src/passes/RemoveUnusedBrs.cpp
src/wasm-linker.cpp

Two improvements to ast_utils.h, to make things a little nicer.
Second commit is a followup for #395 as discussed with @dschuff.

ast_utils improvements

---

check.py
src/asm2wasm.h
src/asm_v_wasm.h
src/asmjs/asm_v_wasm.cpp
src/ast_utils.h
src/binaryen-shell.cpp
src/mixed_arena.h
src/passes/MergeBlocks.cpp
src/passes/Print.cpp
src/passes/RemoveUnusedBrs.cpp
src/s2wasm.h
src/wasm-binary.h
src/wasm-builder.h
src/wasm-linker.cpp
src/wasm-s-parser.h
src/wasm.h
src/wasm2asm.h

This allocates vectors of AST nodes in arenas, which removes most of our current leaks. It also makes things a bit faster.

Arena vectors

---

src/wasm-binary.h
src/wasm-s-parser.h

Avoid dynamic allocas

---

src/wasm-interpreter.h

f32.demote/f64 fix UB

---

src/wasm.h

Fix UB with FP divide by zero

---

src/s2wasm.h

There may be some other places which are broken, but they don't trigger ubsan right now. This is another fix for #404.

Fix alignment UB

---

src/support/archive.cpp

Followup for https://github.com/WebAssembly/binaryen/pull/435#discussion_r62246020

Make print flags in archive.cpp nicer

---

src/binaryen-c.cpp
src/binaryen-c.h
src/wasm-validator.h
src/wasm.h
test/example/c-api-kitchen-sink.c
test/example/c-api-kitchen-sink.txt

Now people can validate modules they create.
This also turned up some bugs in the tests.

Validation in C API

---

scripts/fuzz_relooper.py

Use C for source files, and improve logging.

Relooper fuzzing improvements

---

src/wasm.h

Fix block finalize(type)

---

src/mixed_arena.h

Seems to make it a little faster.
Passes helgrind locally and thread-sanitizer on the bots.

Use atomics in MixedArena

---

.gitignore
src/binaryen-c.cpp
src/binaryen-c.h

Adds C Shared Library to gitignore and added void to some empty parameter functions.

Minor fixes for C API

---

test/example/relooper-fuzz.c

This makes it stricter C, which some compilers are more picky about.

Fix relooper fuzz testcase

---

src/wasm-validator.h

Fix Visual Studio 2015 compiler warning about invalid conversion.

Fix Visual C++ warning

---

src/binaryen-c.cpp
src/binaryen-shell.cpp
src/parsing.h
src/shell-interface.h
src/wasm-as.cpp
src/wasm-binary.h
src/wasm-dis.cpp
src/wasm-s-parser.h
test/example/find_div0s.cpp

This uses exceptions more consistently, adds the option for line and column numbers (but not used much yet), and reports pretty parse errors from the shell.

Better error reporting

---

src/wasm-s-parser.h
src/wasm-validator.h
src/wasm.cpp

Adds line+col for s-expr parse errors, and avoids some invalid errors based on new spec changes.

Error improvements

---

src/cfg/cfg-traversal.h
src/passes/CoalesceLocals.cpp
src/support/timing.h

Various optimizations for local coloring. This makes it over 2x faster than before.

Optimize CoalesceLocals

---

src/wasm-js.cpp

Address following build error (when build.sh is used):
```
src/wasm-js.cpp:113:62: error: conditional expression is ambiguous; 'const Address::address_t'
(aka 'const unsigned int') can be converted to 'wasm::Address' and vice versa
...= module->checkExport(GROW_WASM_MEMORY) ? Memory::kMaxSize : module->memory.initial;
^ ~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~
src/wasm-js.cpp:132:32: error: no matching constructor for initialization of
'wasm::SExpressionWasmBuilder'
sExpressionWasmBuilder = new SExpressionWasmBuilder(*module, *root[0], [&]() {
^                      ~~~~~~~~~~~~~~~~~~~~~~~~~~
src/wasm-js.cpp:242:43: error: non-virtual member function marked 'override' hides virtual member
function
Literal load(Load* load, size_t addr) override {
....
```

Fixes wasm-js build after Address and SExpressionWasmBuilder refactoring

---

src/passes/CoalesceLocals.cpp

Doing it once at the end can be faster, 5% on unoptimized code and 20% on optimized.
This is rebased on #515, only the last commit is new.

Calculate interferences after liveness flow is done

---

src/passes/CoalesceLocals.cpp

Avoid deprecated random_shuffle

---

src/wasm-s-parser.h
src/wasm-validator.h
src/wasm.cpp
src/wasm.h

For the latest batch of new spec tests in the works.

Type checking fixes

---

src/passes/CMakeLists.txt
src/passes/DropReturnValues.cpp
test/passes/drop-return-values.txt
test/passes/drop-return-values.wast

For investigation regarding https://github.com/WebAssembly/design/pull/694

Add a pass to drop return values in set_local and store

---

src/wasm-s-parser.h
src/wasm.cpp

Some minor fixes for new spec tests.

Spec test fixes

---

.gitignore

Encountered these while rehearsing these steps: https://github.com/brakmic/brakmic/pull/3.

Updated .gitignore for VS meta noise

---

src/s2wasm.h
src/tools/s2wasm.cpp
src/wasm-builder.h
src/wasm-linker.cpp
test/s2wasm_known_gcc_test_failures.txt

Also fix validation error in import thunk generation.

s2wasm: Validate the result module

---

check.py
src/wasm-interpreter.h
src/wasm-s-parser.h

Spec fixes

---

check.py
src/tools/binaryen-shell.cpp

So one does not need to always do `--print > file`

 Support -o in binaryen-shell

---

src/passes/CoalesceLocals.cpp
src/passes/pass.cpp
src/support/archive.cpp
src/support/archive.h
src/support/file.cpp

Build fixes/workarounds to support Visual Studio 2013 build, which has trouble with some new C++11 constructs.

vs2013_fixes

---

src/binaryen-c.cpp
src/binaryen-c.h
test/example/c-api-kitchen-sink.c
test/example/c-api-kitchen-sink.txt

For easy debug printing of expressions while building them.

Add BinaryenExpressionPrint to c api

---

src/binaryen-c.cpp
src/binaryen-c.h
test/example/c-api-kitchen-sink.c
test/example/c-api-kitchen-sink.txt

Add c api method to interpret a module, calling its start method

---

src/binaryen-c.cpp
src/binaryen-c.h

It almost was, this finishes the job.

Make creating functions and types parallelizable in C API

---

src/wasm-builder.h

It has an allocator, and should never need to access a module.

Simplify wasm-builder

---

src/passes/Precompute.cpp

For simplicity it used exceptions, but that is silly (and around 100x slower).

Optimize Precompute

---

src/binaryen-c.cpp
src/binaryen-c.h
test/example/c-api-kitchen-sink.c
test/example/c-api-kitchen-sink.txt

Showing irreducible control flow and helper var use.

Add a relooper test for duff's device

---

auto_update_tests.py
check.py
scripts/clean_c_api_trace.py
src/binaryen-c.cpp
src/binaryen-c.h
src/cfg/Relooper.cpp
test/example/c-api-hello-world.c
test/example/c-api-kitchen-sink.c
test/example/c-api-kitchen-sink.txt
test/example/c-api-kitchen-sink.txt.txt

This  logs out c api calls, in the form of a runnable program, so it makes creating testcases easy.

Add a tracing option to the c api

---

src/binaryen-c.cpp
src/binaryen-c.h
test/example/c-api-kitchen-sink.txt

for https://github.com/WebAssembly/binaryen/pull/627#issuecomment-232392060

Don't emit empty array literals in trace output

---

check.py
src/passes/DeadCodeElimination.cpp
src/passes/pass.cpp
test/passes/dce.txt
test/passes/dce.wast

Also add testing for debug mode, and make code handling function-parallel passes more consistent.

Fix dce bug in non-parallel mode, which happens in debug mode

---

src/passes/Print.cpp
src/s2wasm.h
src/wasm-binary.h
src/wasm-s-parser.h
src/wasm.h

Fix checking element presence in map, eliminate explicit index counter
Use character instead of single-character string
Fix trailing whitespace

Miscellaneous cleanups

---

src/wasm-interpreter.h

Latest spec tests, including a fix for DemoteFloat64 (solving it using @binji's code).

Spec updates

---

src/wasm-interpreter.h

Interpreter debugging fixes

---

README.md

This tripped me up as a complete beginner, since I had copied out the example code from the README rather than the test file.

Update README.md with full hello_world.asm.js source

---

src/passes/Vacuum.cpp
test/passes/remove-unused-names_vacuum.txt
test/passes/remove-unused-names_vacuum.wast

Happens on weird things like an infinite loop. Found by fuzzing.

Fix vacuum big where we changed an unreachable node to a nop

---

src/asm2wasm.h
test/wasm-only.asm.js
test/wasm-only.fromasm
test/wasm-only.fromasm.imprecise
test/wasm-only.fromasm.imprecise.no-opts
test/wasm-only.fromasm.no-opts

Corresponds to https://github.com/kripken/emscripten-fastcomp/pull/154

wasm-only additions: i32.cttz, copysign, popcnt

---

src/wasm-binary.h

Write global mutability into wasm binary

---

src/js/wasm.js-post.js

This adds support for using Memory and Table in the wasm/js glue.
The emscripten memory already exists before this code, so the code handles what it receives.
The Table is currently generated when needed, in this glue code, and nothing much done with it, but in the future we can use it for dynamic linking.

Use 0xc Memory and Table

---

src/passes/pass.cpp

This new debugging code turned out to be [very slow in some cases](https://gist.github.com/rongjiecomputer/b56c780137ef53502a0c2cd78938d6c4#gistcomment-1892938), and it's only needed when debugging passes specifically, so put it behind an env var.

Put heavy pas debugging operations behind BINARYEN_PASS_DEBUG

---

check.py

Fix some relative paths to absolute to not depend on a fixed CWD.

absolute_paths

---

src/passes/pass.cpp
src/support/timing.h

Use steady_clock to measure code execution time #766

---

auto_update_tests.py
check.py
src/asm2wasm.h
src/wasm-module-building.h
src/wasm-traversal.h

Not actual bugs, just some odd limitations and annoyances worth doing right.

Some tiny pass cleanups

---

src/passes/OptimizeInstructions.cpp
test/emcc_O2_hello_world.fromasm
test/emcc_O2_hello_world.fromasm.imprecise
test/passes/optimize-instructions.txt
test/passes/optimize-instructions.wast

Catches cases where a value flows through an if or block into a boolean context.

Recurse in optimizeBoolean

---

src/ast/count.h
src/passes/SimplifyLocals.cpp

Refactor get_local counting out of SimplifyLocals

---

src/passes/PrintCallGraph.cpp
test/passes/print-call-graph.txt

Remove indirect call edges as they greatly increase the size of the graph.

Work around dot quirks related to updating node styles.

---

scripts/fuzz_passes.py
scripts/fuzz_passes_wast.py

For some reason travis didn't notice this before.

fix python spacing in some scripts

---

src/passes/RelooperJumpThreading.cpp
test/emcc_hello_world.fromasm
test/emcc_hello_world.fromasm.imprecise
test/unit.fromasm
test/unit.fromasm.imprecise

increase limit in RelooperJumpThreading

---

src/s2wasm.h
src/wasm-emscripten.cpp
src/wasm-emscripten.h
src/wasm-linker.cpp
src/wasm-linker.h
src/wasm-validator.h
src/wasm.h
test/dot_s/globals.s
test/dot_s/globals.wast

Depends on https://reviews.llvm.org/D26875

Handle importing globals in s2wasm

---

src/wasm-emscripten.cpp
src/wasm-emscripten.h
src/wasm-linker.cpp
src/wasm-linker.h

Generate global imports separately from emscripten glue

---

src/js/wasm.js-post.js

Depends on https://github.com/kripken/emscripten/pull/4767. Details there.

use exported static base and bump

---

src/cfg/Relooper.cpp
src/wasm-validator.h
src/wasm/wasm.cpp
test/example/c-api-relooper-unreachable-if.cpp

Add missing finalizes in relooper, fix finalize logic, and harden validation.

Fix if handling in rust testcase

---

src/passes/CMakeLists.txt
src/passes/LogExecution.cpp
src/passes/pass.cpp
src/passes/passes.h
test/passes/log-execution.txt
test/passes/log-execution.wast

It adds an ffi call to log at each function entry and loop header.

add a pass to log execution traces via instrumenting the code

---

src/wasm-linker.cpp

Don't iterate over removed-but-not-erased functions

---

check.py
src/asm2wasm.h
test/emcc_hello_world.fromasm.imprecise
test/emcc_hello_world.fromasm.imprecise.no-opts
test/unit.asm.js
test/unit.fromasm
test/unit.fromasm.clamp
test/unit.fromasm.clamp.no-opts
test/unit.fromasm.imprecise
test/unit.fromasm.imprecise.no-opts
test/unit.fromasm.no-opts

Fix asm2wasm unsigned float-to-int

---

src/tools/wasm-opt.cpp
src/wasm-binary.h
src/wasm-interpreter.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-s-parser.cpp

Found by afl. Nothing particularly interesting, just proper input error handling stuff.

Parsing fixes

---

src/wasm/wasm-binary.cpp

If just some functions are named in the names section, check them against the existing ones for duplicate names too.

afl binary fix

---

src/wasm/wasm-binary.cpp

Optimize duplication checks in binary format reading

---

src/wasm/wasm-s-parser.cpp

Text format parsing fixes

---

src/passes/RemoveUnusedBrs.cpp
src/passes/pass.cpp
test/emcc_hello_world.fromasm
test/emcc_hello_world.fromasm.clamp
test/emcc_hello_world.fromasm.imprecise
test/example/relooper-fuzz.txt
test/passes/O.bin.txt
test/passes/remove-unused-brs.txt
test/passes/remove-unused-brs.wast
test/unit.fromasm
test/unit.fromasm.clamp
test/unit.fromasm.imprecise
test/wasm-only.fromasm
test/wasm-only.fromasm.clamp
test/wasm-only.fromasm.imprecise

Noticed when working on re-relooping control flow.

Misc minor remove-unused-brs improvements

---

src/passes/DeadCodeElimination.cpp

Some cleanup I noticed was possible after the merge of #1014.

Streamline dceing of blocks and known-to-exist children

---

CMakeLists.txt
src/parsing.h
src/shell-interface.h
src/tools/wasm-opt.cpp
src/wasm-interpreter.h
src/wasm-s-parser.h
src/wasm-validator.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-s-parser.cpp
src/wasm/wasm.cpp

Almost the end of the fuzzing work. This is a bunch of tiny fixes fuzzing found. At this point, both binary and text parsers are hardened, and the fuzzer runs for days without finding new stuff.

More misc fuzz fixes

---

src/binaryen-c.cpp
test/binaryen.js/kitchen-sink.js.txt

Correct the mutex usage, clean up some surrounding code, and update a test output file.

C API fixes

---

src/wasm/wasm-binary.cpp

Change char to auto to avoid type-limits warn on some arches

---

CMakeLists.txt
src/wasm-validator.h
src/wasm/CMakeLists.txt
src/wasm/wasm-validator.cpp

Also small cleanup to CMake libraries

Factor wasm validator into a cpp file

---

src/passes/OptimizeInstructions.cpp
src/passes/RemoveUnusedBrs.cpp
src/passes/Vacuum.cpp
src/wasm-builder.h
test/passes/optimize-instructions.txt
test/passes/optimize-instructions.wast
test/passes/remove-unused-brs.txt
test/passes/remove-unused-brs.wast
test/passes/remove-unused-names_remove-unused-brs_vacuum.txt
test/passes/remove-unused-names_remove-unused-brs_vacuum.wast
test/passes/vacuum.txt
test/passes/vacuum.wast

Turns out the more you run fuzzers, the more stuff they find.

Yet more fuzz fixes

---

.travis.yml

Followup for #1064.
First time I use this stuff, hopefully I did it right...

Add api key for releases generation

---

src/passes/MergeBlocks.cpp
src/wasm/wasm.cpp
test/passes/merge-blocks.txt
test/passes/merge-blocks.wast
test/passes/remove-unused-brs.txt
test/passes/remove-unused-brs.wast

A few more from the new fuzzer.

Fuzz fixes

---

auto_update_tests.py
scripts/test/shared.py

Also, fix -l and -rpath lib directories so that it can be
run out-of-tree

Fix locaion of wasm-merge in auto_update_tests.py

---

src/literal.h
src/support/hash.h

Disambiguate hash usage

---

check.py
src/support/threads.cpp

Working on #1204, which adds more parallelism (in validation), I saw that the torture tests would hang on the bots. Turns out the issue is it's hitting a concurrency limit - the torture tests run in parallel, and if each also tries to create a bunch of threads, it's slow and starts to fail at some point (especially in thread-sanitizer mode) This PR fixes that, by (1) not using multiple threads in the already-parallel torture tests (faster anyhow), and (2) handle errors in thread creation, falling back to single-threaded mode.
easier to read without whitespace changes, https://github.com/WebAssembly/binaryen/pull/1205/files?w=1

Thread fixes

---

src/ast/type-updating.h
src/passes/DeadCodeElimination.cpp
test/passes/dce.txt
test/passes/dce.wast

If changed to unreachable but didn't propagate that effect up. Also add set_global support in dce.

fix a dce fuzz bug

---

check.py

Which were useful in bootstrapping but are now much better covered by the emscripten test suite anyhow. Basically it would be nice to not overlap the emscripten test suite, and to not depend on emcc in the binaryen test suite.
Still some other emcc tests left, but those are actually interesting and do not overlap with emscripten. I think we should move them to emscripten eventually.

remove unneeded and outdated emcc tests

---

src/cfg/Relooper.h
src/passes/ReReloop.cpp
test/passes/rereloop.txt
test/passes/rereloop.wast
test/passes/rereloop_dce_remove-unused-brs_remove-unused-names_coalesce-locals_simplify-locals_reorder-locals_remove-unused-brs_merge-blocks_vacuum.txt

We need to ensure a terminator in all relooper blocks.

Fix re-reloop fuzz bug

---

scripts/fuzz_passes.py
scripts/fuzz_passes_wast.py
scripts/fuzz_relooper.py
scripts/storage.py
scripts/test/shared.py
scripts/test/support.py

flake8 starts warning on bare "except:" in python scripts, and all CI job is failing for that.

Fix flake8 failures in scripts/

---

src/binaryen-c.cpp
src/binaryen-c.h

Not sure if these are a specified already, but since I just stumbled upon them, I thought I make a PR of it instead of asking a question.
May create an update for binaryen.js as well if it makes sense, otherwise feel free to close.

Added BinaryenAtomic* incl. ops to binaryen-c

---

src/binaryen-c.cpp
test/example/c-api-kitchen-sink.c
test/example/c-api-kitchen-sink.txt
test/example/c-api-kitchen-sink.txt.txt

Fix yet another BinaryenAddGlobal tracing issue

---

src/tools/fuzzing.h
test/passes/translate-to-fuzz.txt

After each function the fuzzer creates, it optionally creates a function calling that one multiple times with different arguments.

Add invocation functions for fuzz functions, so they are tested with many input values

---

README.md
src/asm2wasm.h
test/debugInfo.asm.js
test/debugInfo.fromasm
test/debugInfo.fromasm.clamp
test/debugInfo.fromasm.clamp.map
test/debugInfo.fromasm.clamp.no-opts
test/debugInfo.fromasm.clamp.no-opts.map
test/debugInfo.fromasm.imprecise
test/debugInfo.fromasm.imprecise.map
test/debugInfo.fromasm.imprecise.no-opts
test/debugInfo.fromasm.imprecise.no-opts.map
test/debugInfo.fromasm.map
test/debugInfo.fromasm.no-opts
test/debugInfo.fromasm.no-opts.map

Fixes https://github.com/kripken/emscripten/issues/5718

Handle debug info without a filename in asm2wasm

---

src/wasm/wasm-validator.cpp
test/export-import.wast
test/export-import.wast.from-wast
test/export-import.wast.fromBinary
test/export-import.wast.fromBinary.noDebugInfo

Allow exporting an import

---

src/asm2wasm.h
src/binaryen-c.cpp
src/pass.h
src/passes/ReReloop.cpp
src/passes/SSAify.cpp
src/passes/pass.cpp
src/wasm-module-building.h

runFunction => runOnFunction (we run on the function, not run the function)

---

src/support/timing.h
src/tools/wasm-reduce.cpp

Better error messages, better validation, better function removal, etc.

wasm-reduce tweaks and improvements

---

src/passes/OptimizeInstructions.cpp

Just a few small things noticed while reading.

fix some comment typos

---

src/wasm2asm.h

Adds support for (constant i32/f32/f64) global variable initializers, which were previously ignored though get_global/set_global are supported.
There isn't a test for these, yet, as outputs would possibly look a bit different once https://github.com/WebAssembly/binaryen/pull/1433 lands. Can add one then. Other than that this PR alone shouldn't change any existing test outputs.

Add global initializers to wasm2asm

---

src/emscripten-optimizer/istring.h
src/wasm-emscripten.cpp
test/dot_s/em_js.s
test/dot_s/em_js.wast

Companion to https://github.com/kripken/emscripten/pull/6220

EM_JS binaryen support

---

src/asm2wasm.h

In particular on non-float min/max etc. See #1455

Better asm2wasm error handling and reporting

---

src/wasm-binary.h
src/wasm/wasm-binary.cpp

Validate we are in a function context when adding a label in binary parsing

---

src/wasm/wasm-s-parser.cpp

Check for errors when parsing s-expression load/store immediates

---

CMakeLists.txt
src/support/path.h
src/tools/wasm-reduce.cpp

Also add option `--binaries` to specify the `bin` folder that has `wasm-opt`

Support wasm-reduce for Windows

---

src/passes/ExtractFunction.cpp

Remove more of the unwanted stuff, and leave just an export to the function we are extracting. Then optimizations can do an effective cleanup.

Improve --extract-function

---

src/passes/OptimizeInstructions.cpp
test/passes/optimize-instructions.txt
test/passes/optimize-instructions.wast

Optimize selects of constant conditions

---

src/tools/wasm-reduce.cpp

More simple reduction rules, for if, block, loop, etc.

Reducer improvements

---

.travis.yml

I mistakenly added to before_script.

travis: Move flake8 to script phase

---

.flake8
.gitmodules
.travis.yml
README.md
check.py
scripts/test/shared.py

The wasm waterfall is moving away from testing with s2wasm
and s2wasm hopefully going to be removed soon.
See https://github.com/WebAssembly/waterfall/pull/362/

Remove testing of s2wasm via the wasm waterfall scripts

---

check.py
scripts/test/shared.py
scripts/test/support.py

Fix some file reading & endline issues on windows platform.
Not tested on another platforms.

Fix check.py on windows platform

---

src/js/binaryen.js-post.js

Modify the internal out() method instead. see kripken/emscripten#6756

Emscripten no longer allows modifying Module['print'] at runtime

---

src/ir/LocalGraph.cpp

I have done my tests & small optimisation on LocalGraph #1338 .
So, to sum up :
- Replace seen unordered_set by a boolean check.
- Replace LocalGraphInternal::Info::lastSets vector by a unordered_map.
Benchmark process:
Firstly I gather xxx.temp.asm.js files from various sources. (Emscripten Tests, using EMCC_DEBUG=2)
Then process them to asm2wasm using -O3 parameter.
Run the application four times (for each case), keep the three best ones and compute the average.
The last column include remove seen set optimisation.
There are the results : 
| Test  | Base | Remove seen set | Replace vector -> umap |
| ------------- | ------------- | ------------- | ------------- |
| SQLite  | 12.969 s  | 7.789 s | 6.935 s | 
| Prolog | 81.139 s | 30.563 s | 28.505 s |
| Bullet | 1.458 s | 1.298 s | 1.286 …

Speedup localgraph

---

src/ir/LocalGraph.cpp

* Remove the Action class - we just need a pointer to a get or set. This simplifies the code and saves a little memory, but doesn't seem to have any impact on speed.
* Miscellaneous code style and comment changes.
cc @vloppin

Some minor LocalGraph improvements

---

src/ir/iteration.h

This avoids us needing to update it for new Expression types (SIMD, GC, etc.) in the future.

Greatly simplify iteration.h

---

src/emscripten-optimizer/optimizer-shared.cpp
test/unit.asm.js
test/unit.fromasm
test/unit.fromasm.clamp
test/unit.fromasm.clamp.no-opts
test/unit.fromasm.imprecise
test/unit.fromasm.imprecise.no-opts
test/unit.fromasm.no-opts

(No sign to detect there, but we need to handle that case and not error.)
Fixes kripken/emscripten#7123

Fix sign detection of a floating-point mod

---

src/wasm/wasm-emscripten.cpp

Fixes the 3 regressions mentioned here: https://github.com/WebAssembly/binaryen/pull/1678#issuecomment-423031735

Fix an iterator invalidation regression from #1678

---

src/js/binaryen.js-post.js
test/binaryen.js/stackir.js
test/binaryen.js/stackir.js.txt

Related to https://github.com/WebAssembly/binaryen/pull/1716#issuecomment-434476984
I also tested this with a custom build in AssemblyScript which seems to work.

Add Module#emitStackIR to the JS-API

---

src/passes/Print.cpp
test/binaryen.js/stackir.js.txt
test/passes/O2_print-stack-ir.txt
test/passes/O3_print-stack-ir.txt
test/passes/Os_print-stack-ir.txt
test/passes/generate-stack-ir_optimize-stack-ir_print-stack-ir_optimize-level=3.txt
test/passes/remove-unused-brs_generate-stack-ir_print-stack-ir.txt

Follow-up to https://github.com/WebAssembly/binaryen/pull/1717#issuecomment-434795632

Suppress the 'has StackIR' comment when printing StackIR

---

src/cfg/Relooper.cpp
src/cfg/Relooper.h

Use c++11 auto, iterators, etc.
Preparation for some optimizations I'm planning.

Modernize relooper code

---

src/wasm/wasm-validator.cpp

Without this wasm-opt can't operation on emscripten-produced
SIDE_MODULES's which have zero sized memory imports.
Technically is not a validation failure if you have segments that
are larger than your initial memory, regardless of whether you
import them.
For non-imported memories it can be helpful though, so leaving it
in to catch those errors.

Fix segment size validation for imported memories

---

src/ir/effects.h
test/emcc_hello_world.fromasm
test/emcc_hello_world.fromasm.clamp
test/emcc_hello_world.fromasm.imprecise
test/passes/remove-unused-names_merge-blocks.txt

Previously we assumed that we can't reorder a branching instruction and anything else. However, the only risk is when the other thing has side effects.
This is only tested indirectly in this PR - upcoming PRs will stress it more directly.

Branches only invalidate side effects

---

src/cfg/Relooper.cpp
test/binaryen.js/kitchen-sink.js.txt
test/example/c-api-kitchen-sink.txt
test/example/c-api-kitchen-sink.txt.txt
test/example/relooper-merge6.c
test/example/relooper-merge6.txt
test/passes/1.txt
test/passes/flatten_rereloop.txt
test/passes/rereloop.txt

That is, A -> B where no other branches go to B. In that case we are guaranteed to not increase code size.

Relooper: Merge consecutive blocks

---

scripts/fuzz_relooper.py
scripts/test/shared.py

This allows me to run tests on a system where the default
installed node is not recent enough.

Check $NODE environment variable when looking for node

---

src/wasm-binary.h
src/wasm/wasm-binary.cpp
src/wasm/wasm.cpp

Alternatively perhaps we should error, but I can imagine cases where that might be annoying.

Warn if linking section is present, as we cannot handle it yet

---

src/tools/wasm-emscripten-finalize.cpp
test/lld/duplicate_imports.wast.out
test/lld/em_asm.wast.out
test/lld/hello_world.wast.mem.out
test/lld/hello_world.wast.out
test/lld/init.wast.out
test/lld/recursive.wast.out
test/lld/reserved_func_ptr.wast.jscall.out
test/lld/reserved_func_ptr.wast.out

I broke this to be alwasy empty in #1795.

Fix initializerFunctions output by wasm-emscripten-finalize

---

auto_update_tests.py
src/tools/wasm-emscripten-finalize.cpp
src/wasm/wasm-emscripten.cpp
test/lld/duplicate_imports.wast.out
test/lld/em_asm.wast.out
test/lld/em_asm_table.wast.out
test/lld/hello_world.wast.mem.out
test/lld/hello_world.wast.out
test/lld/init.wast.out
test/lld/recursive.wast.out
test/lld/reserved_func_ptr.wast.jscall.out
test/lld/reserved_func_ptr.wast.out

Also, omit keys that don't have any value(s).

Format metadata json using mutliple lines for readability

---

src/ir/module-utils.h

Fix comment in src/ir/module-utils.h

---

src/wasm/wasm-binary.cpp
src/wasm/wasm-emscripten.cpp

Fix for https://github.com/kripken/emscripten/pull/7661

wasm-emscripten-finalize: Don't add a table max if none is present in the input

---

src/passes/I64ToI32Lowering.cpp
test/wasm2js/i64-select.2asm.js
test/wasm2js/i64-select.wast
test/wasm2js/left-to-right.2asm.js
test/wasm2js/select.2asm.js

Fix i64 select lowering.

---

src/ir/features.h
src/wasm.h
src/wasm/wasm-validator.cpp

Add `features.h` which centralizes all the feature detection code. (I'll need this in another place than the validator which is where it was til now.)

Refactor Features code

---

scripts/fuzz_opt.py
src/passes/SSAify.cpp
test/passes/ssa.txt
test/passes/ssa_fuzz-exec.txt

We iterated over a set. Instead, iterate over the relevant items in their order in the IR.

Determinism fix for SSA pass

---

.gitattributes
.travis.yml
README.md

following https://github.com/WebAssembly/binaryen/pull/1859

Remove wasm.js references

---

src/wasm/wasm-binary.cpp
src/wasm/wasm-s-parser.cpp

fixes #1863, #1864, #1865, #1866, #1867

Misc minor ASAN fixes

---

src/emscripten-optimizer/istring.h
src/emscripten-optimizer/simple_ast.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-s-parser.cpp

Fixes #1876, #1877, #1879 
cc @wcventure - thanks again!

More misc ASAN fixes

---

src/tools/feature-options.h
src/tools/optimization-options.h
src/tools/tool-options.h
src/tools/wasm-shell.cpp
src/tools/wasm2js.cpp
src/wasm/wasm-validator.cpp
test/passes/optimize-instructions.txt
test/passes/optimize-instructions.wast
test/wasm2js/grow-memory-tricky.wast
test/wasm2js/i64-select.wast

Also fixes some bugs in wasm2js tests that did not validate.

Validate unique local names, and use validation in wasm2js. Fixes #1885

---

src/wasm/wasm-binary.cpp

fixes bug reported in comment on e63c4a7 , https://github.com/WebAssembly/binaryen/issues/1885#issuecomment-457061114 , https://github.com/WebAssembly/binaryen/issues/1879#issuecomment-457059816

Validate all function indexes in binary reading

---

CMakeLists.txt
src/passes/LegalizeJSInterface.cpp
src/wasm.h
src/wasm/wasm.cpp

Fix memory leaks

---

src/ir/features.h
src/tools/tool-options.h
src/wasm.h

Add sign-ext feature

---

.travis.yml

🙅‍♂️ do not merge 🙅‍♂️ 
fixes #1695

feat(release): add OSX binary to CI GitHub releases

---

test/passes/O4.txt
test/passes/O4.wast

This will make it easier to track progress and prevent regressions.
cc @ MaxGraey

Add AssemblyScript n-body benchmark test

---

src/passes/Metrics.cpp
test/passes/O3_low-memory-unused_metrics.txt
test/passes/converge_O3_metrics.bin.txt
test/passes/func-metrics.txt
test/passes/metrics.txt
test/passes/metrics_strip-debug_metrics.bin.txt
test/passes/metrics_strip-producers_metrics.bin.txt

Also, alwasy output high level metrics even when zero.

Add export count to --metrics

---

check.py
scripts/test/shared.py
test/crash/test_features.py

unittest is Python's standard testing framework, so this change allows
arbitrary tests to be written without introducing any new dependencies
or code in check.py. A new test that was not possible to write before
is also included. It is the first of many.

Discover and run unit tests from check.py

---

.travis.yml

Accidentally introduced in #1698!

Fix OSX build error on master

---

scripts/test/generate_lld_tests.py
src/wasm/wasm-emscripten.cpp
test/lld/em_asm_shared.cpp
test/lld/em_asm_shared.wast
test/lld/em_asm_shared.wast.out
test/lld/hello_world.wast
test/lld/init.wast
test/lld/recursive.wast
test/lld/reserved_func_ptr.wast
test/lld/shared.c
test/lld/shared.wast
test/lld/shared.wast.out

In relocatable code the constant offset might be relative to
__memory_base.

Handle relocatable code in AsmConstWalker

---

src/wasm-interpreter.h

Should prevent surprises in the future.

OverriddenVisitor in ExpressionRunner

---

scripts/test/env.js
src/wasm2js.h
test/wasm2js/dynamicLibrary.2asm.js
test/wasm2js/dynamicLibrary.wast

Mostly what we need for dynamic linking, at least on the binaryen side.

wasm2js: support non-constant indexes for memory and table segments

---

src/tools/tool-options.h
src/wasm-binary.h
src/wasm-features.h
src/wasm/wasm-binary.cpp
test/unit/test_features.py

This only adds the feature and its flag and not the instructions yet.

Add exception handling feature

---

src/wasm-traversal.h
src/wasm-type.h

A few things that were missing in #2048.

Fix formatting of some comments (NFC)

---

CMakeLists.txt

Fix cmake install of binaryen.js

---

src/wasm/wasm-s-parser.cpp

These formats don't seem to be used now, right?

Remove old import/export parsing routines (NFC)

---

build-js.sh
src/binaryen-c.cpp
src/binaryen-c.h
src/js/binaryen.js-post.js
test/binaryen.js/kitchen-sink.js
test/binaryen.js/kitchen-sink.js.txt
test/example/c-api-kitchen-sink.c
test/example/c-api-kitchen-sink.txt

This adds `Features.MVP` and `Features.All` to binaryen.js and make test
cases use it.

Add Features.MVP and Features.All to binaryen.js

---

src/wasm/wasm-s-parser.cpp

Now `parseTypeUse` always returns `FunctionType*` and params/return pair
and makes sure the two are consistent, so the caller does not have to
populate params/results when only `(type)` is specified.

Refactor typeuse parsing more (NFC)

---

src/ir/module-utils.h
src/wasm-binary.h
src/wasm/wasm-binary.cpp

This was suggested in https://github.com/WebAssembly/binaryen/pull/2151#discussion_r289481693.

Use BinaryIndexes instead of copies in BinaryWriter (NFC)

---

src/wasm-interpreter.h
test/spec/bulk-memory.wast

As decided in the recent in-person CG meeting.

Relax bulk memory rules

---

src/passes/Bysyncify.cpp
test/passes/bysyncify.txt
test/passes/bysyncify_optimize-level=1.txt
test/passes/bysyncify_pass-arg=bysyncify-ignore-imports.txt
test/passes/bysyncify_pass-arg=bysyncify-ignore-indirect.txt
test/passes/bysyncify_pass-arg=bysyncify-imports@env.import,env.import2.txt
test/unit/input/bysyncify-stackOverflow.wast
test/unit/input/bysyncify.js
test/unit/test_bysyncify.py

Add assertions on stack overflow in all 4 Bysyncify API calls (previously only 2 did it).
Also add a check that those assertions are hit.

Bysyncify: Assertion improvements

---

scripts/fuzz_opt.py

That env var is the one piece of global state we use.

Fuzzing: Emit BINARYEN_PASS_DEBUG in the autoreducer scripts

---

src/ir/manipulation.h
src/passes/MemoryPacking.cpp
src/wasm/wasm-validator.cpp
test/passes/memory-packing.txt
test/passes/memory-packing.wast

Reverts WebAssembly/binaryen#2235

Revert "Remove bulk memory instructions refering to active segments"

---

scripts/fuzz_opt.py
src/tools/fuzzing.h

Fuzz all feature flags, and fix another SignExt issue in the fuzzer

---

src/wasm/wasm-emscripten.cpp
test/lld/em_asm_table.wast
test/lld/em_asm_table.wast.out

Reverts WebAssembly/binaryen#2271
See https://github.com/WebAssembly/binaryen/pull/2271#issuecomment-517446827

Revert "Fix EM_ASM not working with setjmp/longjmp"

---

src/wasm/wasm-emscripten.cpp
test/lld/em_asm_table.wast
test/lld/em_asm_table.wast.out

Refs https://github.com/emscripten-core/emscripten/issues/8894. This fix does not handle dynamic linking, which requires additional work.
This is a fixed version of #2271.

Fix EM_ASM not working with setjmp/longjmp

---

appveyor.yml

Also don't do duplicate builds.

Update AppVeyor to Visual Studio 2017

---

CMakeLists.txt

Temporarily build with -Wno-implicit-int-float-conversion

---

build-js.sh

See https://github.com/emscripten-core/emscripten/pull/9360

Workaround for current breakage on master, avoid ASSERTIONS. 

---

src/wasm/wasm-emscripten.cpp
test/lld/em_asm_main_thread.wast
test/lld/em_asm_main_thread.wast.out

Supports proxying EM_ASM calls to main thread. Fixes https://github.com/emscripten-core/emscripten/issues/9410

MAIN_THREAD_EM_ASM support

---

src/wasm-traversal.h
test/passes/dce_all-features.txt
test/passes/dce_all-features.wast

PostWalker traversal should visit its value.

Fix PostWalker traversal of push instruction

---

src/wasm-features.h

Cast to bool after bitwise operations, to avoid an MSVC warning

---

CMakeLists.txt
src/asmjs/CMakeLists.txt
src/cfg/CMakeLists.txt
src/emscripten-optimizer/CMakeLists.txt
src/ir/CMakeLists.txt
src/passes/CMakeLists.txt
src/support/CMakeLists.txt
src/wasm/CMakeLists.txt

Reverts WebAssembly/binaryen#2463

Revert "Build libbinaryen as a monolithic statically/shared library"

---

third_party/llvm-project/Path.cpp

This requires removing some more LLVM code, which
was only pulled in a debug build.

Fix debug build

---

third_party/llvm-project/DWARFExpression.cpp
third_party/llvm-project/include/llvm/BinaryFormat/Dwarf.def
third_party/llvm-project/include/llvm/BinaryFormat/Dwarf.h

From
https://github.com/llvm/llvm-project/commit/adf7a0a558a51f275bf8906b6a010c397560b7ff

Update LLVM to support WASM_location 

---

src/wasm/wasm-debug.cpp
test/passes/fannkuch3.bin.txt
test/passes/fannkuch3_manyopts.bin.txt
test/passes/fib2.bin.txt
test/passes/ignore_missing_func.bin.txt
test/passes/multi_line_table.bin.txt

Before this we just considered expressions there.

Update debug line info with function starts

---

src/ir/ReFinalize.cpp
src/ir/utils.h

This adds AutoDrop (+ ReFinalize) support for Try. We don't have
`--autodrop` option so I can't add a separate test for this, but this is
basically the same as what If does. I'll add the `--autodrop` option and
a test if reviewers feel necessary.

Add AutoDrop support for Try

---

CHANGELOG.md
CMakeLists.txt

Version 91

---

src/wasm/wasm-binary.cpp

Add 'warning:' to names section warning. Helps #2680

---

src/support/small_vector.h

Add a non-const iterator to SmallVector

---

travis-emcc-tests.sh

Switch to emcmake from emconfigure, which emscripten has made
a requirement meanwhile.

Fix emscripten CI

---

src/tools/wasm-reduce.cpp
src/wasm-builder.h

Also increases the usefulness of a couple wasm-builder methods that
are useful here.

Handle tuples in wasm-reduce

---

src/passes/Asyncify.cpp
src/wasm/wasm-type.cpp
test/passes/asyncify.txt
test/passes/asyncify.wast

Iterate over tuple locals and separately load or store each component.

Support tuple locals in Asyncify

---

src/binaryen-c.cpp
src/binaryen-c.h
src/js/binaryen.js-post.js
test/binaryen.js/kitchen-sink.js
test/binaryen.js/kitchen-sink.js.txt
test/example/c-api-kitchen-sink.c
test/example/c-api-kitchen-sink.txt
test/example/c-api-kitchen-sink.txt.txt

Adds functions for creating and inspecting tuple.make and
tuple.extract expressions in the C and JS APIs.

Tuple operations in C and JS APIs

---

src/passes/ReorderLocals.cpp

The original code here is quite old and I guess we assumed
that it was ok to use maps for this, but on really huge amounts
of locals it ends up mattering a lot. This makes the pass 3x
faster on poppler after `--flatten --flatten` (double flatten creates
lots of new locals, and is generally similar to what wasm2js
does).

Optimize ReorderLocals maps to vectors

---

auto_update_tests.py
check.py
scripts/test/binaryenjs.py
scripts/test/wasm_opt.py

Also, factor out auto-updating of binaryenjs testing so it lives
alongside the actual test code.

Factor out wasm_opt testing. NFC.

---

src/passes/LegalizeJSInterface.cpp

Fixes https://github.com/WebAssembly/binaryen/issues/2749

Legalize return_calls properly

---

src/wasm/wasm-binary.cpp

Fix invalid index checking in readImports

---

.github/workflows/build_release.yml

Also add upload of shasum file

CI: Fix windows asset upload

---

.github/workflows/ci.yml

CI: Avoid downloading cmake unnecessarily

---

src/wasm/wasm-binary.cpp

Reopening #2798 on a local branch to trigger CI.

Emit section IDs as bytes

---

.github/workflows/ci.yml

cc @dcodeIO as this may affect more bots
I will have a WIP PR up soon I hope.

Fix emscripten CI tests to 1.39.14, until we fix the lack of MODULARIZE_INSTANCE

---

scripts/fuzz_opt.py

* Use `--emit-target-features` and `--detect-features`.
* Rename Asyncify handler temp files (I happened to notice they overwrote other files, which was annoying.
Fixes #2831

fuzz_opt.py fixes

---

src/wasm/wasm-debug.cpp
test/passes/fannkuch3_manyopts.bin.txt

Turns out we had a testcase for this already, but were doing the
wrong thing on it.
Found and diagnosed by @paolosevMSFT

[dwarf] Handle a bad mapped base in debug_loc updating

---

CMakeLists.txt
src/asmjs/shared-constants.cpp
src/asmjs/shared-constants.h
src/tools/wasm2js.cpp
src/wasm2js.h

Reverts WebAssembly/binaryen#2864
The rpath on Linux isn't quite right.

Revert "Link binaryen tools against the dylib"

---

scripts/fuzz_opt.py

Fuzzer: Ignore V8 warnings on removed flags

---

src/support/safe_integer.cpp
test/spec/conversions.wast

I think this is the last of these...

Fix i32.trunc_f64_u of values that round down to UINT32_MAX (#2975)

---

src/passes/CMakeLists.txt
src/passes/ReplaceStackPointer.cpp
src/passes/pass.cpp
src/passes/passes.h
src/tools/wasm-emscripten-finalize.cpp
src/wasm-emscripten.h
src/wasm/wasm-emscripten.cpp

First step in making wasm-emscripten-finalize use more passes.

Move ReplaceStackPoint into a pass. NFC.

---

src/support/bits.cpp

This approach already mentioned in #2955

Fix build for win32

---

src/tools/fuzzing.h
test/passes/fuzz_metrics_noprint.bin.txt
test/passes/translate-to-fuzz_all-features.txt

Tweak floating-point numbers with not just a +-1 integer, but also a
float in `[-1, 1]`.
Apply a tweak to powers of 2 as well.

Better const fuzzing

---

.github/workflows/build_release.yml
.github/workflows/ci.yml

This means we will also include any headers or libraries that
are part of the `install` step.

Include full `install` in releases

---

src/passes/OptimizeInstructions.cpp
test/passes/optimize-instructions_all-features.txt
test/passes/optimize-instructions_all-features.wast

`x - 0.0` -> `x`
`x + (-0.0)` -> `x`
`x - (-0.0)` -> `x + 0.0`
where `x` is `f32` or `f64`.

Simplify subtraction zero from float expressions

---

src/wasm-builder.h
src/wasm2js.h

Removes even more uses of allocators.

Fix build after semantic merge conflict

---

src/literal.h
src/wasm-interpreter.h
src/wasm/literal.cpp
test/spec/bulk-memory.wast
test/spec/bulk-memory64.wast

details: https://github.com/WebAssembly/binaryen/issues/3149

Fix regression in memory.fill due to Memory64

---

src/passes/OptimizeInstructions.cpp
test/passes/optimize-instructions_all-features.txt
test/passes/optimize-instructions_all-features.wast

`i32.eqz(wrap_i64(x))` -> `i64.eqz(x)`, where `maxBits(x) <= 32`

Fold wrapped 64-bit ints with 32-bit eqz composition to i64.eqz

---

test/lld/em_asm.wat
test/lld/em_asm_O0.wat
test/lld/em_asm_shared.wat
test/lld/em_asm_shared.wat.out
test/lld/hello_world.wat
test/lld/init.wat
test/lld/longjmp.wat
test/lld/recursive.wat
test/lld/reserved_func_ptr.wat
test/lld/shared.wat
test/lld/shared.wat.out
test/lld/shared_longjmp.wat
test/lld/shared_longjmp.wat.out

This updates lld tests by running generate_lld_tests.py with the latest
toolchain.

Update lld tests

---

src/passes/OptimizeInstructions.cpp

Reason explanation for #2988
cc @kripken

Add comment about signed lowering pre-transform

---

src/emscripten-optimizer/optimizer-shared.cpp
src/emscripten-optimizer/simple_ast.h
src/support/bits.cpp
src/support/json.h

Basically all this changes is part of #2952. But I decided split it to separate PR.

Minor refactoring

---

test/lld/longjmp.wat
test/lld/longjmp.wat.out
test/lld/shared_longjmp.wat
test/lld/shared_longjmp.wat.out

Generated by running:
./scripts/test/generate_lld_tests.py
./auto_update_tests.py

Re-generate lld test inputs

---

src/passes/OptimizeInstructions.cpp
test/passes/optimize-instructions_all-features.txt
test/passes/optimize-instructions_all-features.wast

Also handle 64-bit and, or & xor operations
Fix #3224

Improve partial evaluation

---

src/binaryen-c.cpp
src/wasm.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-s-parser.cpp
test/example/c-api-unused-mem.txt
test/passes/func-metrics.txt

Only write explicit names to name section

---

scripts/fuzz_opt.py

We used to either apply all, or pick each at random. Also add a chance
to pick none at all.

Fuzzer: improve random selection of features

---

src/pass.h
src/tools/optimization-options.h

Rename unmodifiedImportedMemory => zeroFilledMemory

---

src/passes/OptimizeInstructions.cpp
src/support/bits.cpp
test/passes/optimize-instructions_all-features.txt
test/passes/optimize-instructions_all-features.wast

Fix issue found by fuzzed [here](https://github.com/WebAssembly/binaryen/pull/3015#issuecomment-718001620)
cc @kripken

Fix pow2 util and avoid pow2 for left shifting in ZeroRemover

---

src/tools/fuzzing.h
test/passes/translate-to-fuzz_all-features.txt

Followup to #3276 where this was suggested by @tlively

Use RAII in fuzzer for function context creation

---

src/passes/Memory64Lowering.cpp
src/wasm-binary.h
src/wasm/wasm-binary.cpp
test/passes/memory64-lowering_enable-memory64_enable-bulk-memory.txt
test/passes/memory64-lowering_enable-memory64_enable-bulk-memory.wast

Fixed bug in memory64-lowering pass for memory.size/grow

[Memory64]

---

src/asm_v_wasm.h
src/asmjs/asm_v_wasm.cpp
src/asmjs/shared-constants.cpp
src/asmjs/shared-constants.h
src/parsing.h
src/passes/Directize.cpp
src/passes/DuplicateImportElimination.cpp
src/passes/FuncCastEmulation.cpp
src/passes/I64ToI32Lowering.cpp
src/passes/InstrumentLocals.cpp
src/passes/InstrumentMemory.cpp
src/passes/LegalizeJSInterface.cpp
src/passes/LogExecution.cpp
src/passes/RemoveUnusedModuleElements.cpp
src/passes/SafeHeap.cpp
src/passes/TrapMode.cpp
src/shared-constants.h
src/shell-interface.h
src/tools/wasm-ctor-eval.cpp
src/wasm-binary.h
src/wasm/wasm-emscripten.cpp
src/wasm/wasm-s-parser.cpp
src/wasm/wasm-stack.cpp
src/wasm/wasm.cpp
test/spec/old_import.wast

Specifically try to cleanup use of asm_v_wasm.h and asmjs constants.

Remove dead code and unused includes. NFC.

---

src/binaryen-c.cpp
test/example/c-api-kitchen-sink.c
test/example/c-api-kitchen-sink.txt

We mistakenly tried to run all passes there, but should run only
the function ones.

Fix BinaryenFunctionOptimize. fixes #3333

---

src/ir/utils.h
src/wasm-delegations.h
src/wasm-traversal.h

Also avoid needing to #undef DELEGATE all the time.

Remove boilerplate in utils.h

---

src/wasm/wasm-type.cpp

[Types] Add type sorting for Signatures

---

src/passes/OptimizeInstructions.cpp
src/passes/Vacuum.cpp

Just things I noticed while writing other code.
The vacuum code can be deleted as it is handled by the default anyhow.

Minor code cleanups. NFC

---

src/ir/cost.h

Almost NFC, but adds a cost to `DataDrop` - just a number I made up, not sure
how much it makes sense.

[cost.h] Require all expressions to define a cost

---

test/lit/wasm-split/invalid-options.wast

Context:
https://github.com/WebAssembly/binaryen/pull/3359#discussion_r527484301

Fix comment in invalid-options.wast

---

src/wasm/wasm-type.cpp

Although there is only one "type store" right now, a subsequent PR will add a
new "TypeBuilder" class that manages its own universe of temporary types. Rather
than duplicate all the logic behind type creation and canonicalization, it makes
more sense to encapsulate that logic in a class that TypeBuilder will be able to
reuse.

[wasm-type][NFC] Encapsulate type canonicalization in a TypeStore

---

src/passes/Vacuum.cpp

This is shorter by using ChildIterator, so it's more general. The greater generality
should not be noticeable atm, but it will allow this pass to just work on GC
instructions once we have them (without this, in my testing the optimizer does not
do very well on GC).

[GC] Refactor Vacuum pass. NFC.

---

src/tools/wasm-reduce.cpp

Passing `--detect-features` there doesn't work (as there is no feature
section).
Maybe there's a simpler way though?

[wasm-reduce] Improve support for reducing on text files

---

src/ir/branch-utils.h
src/ir/type-updating.h
src/wasm.h
src/wasm/wasm-binary.cpp
src/wasm/wasm.cpp

More refactoring of branch utility code to remove boilerplate. NFC

---

src/tools/wasm-emscripten-finalize.cpp
src/wasm-emscripten.h
src/wasm/wasm-emscripten.cpp
test/lld/basic_safe_stack.wat.out
test/lld/duplicate_imports.wat.out
test/lld/em_asm.wat.mem.out
test/lld/em_asm.wat.out
test/lld/em_asm64.wat.out
test/lld/em_asm_O0.wat.out
test/lld/em_asm_main_thread.wat.out
test/lld/hello_world.passive.wat.out
test/lld/hello_world.wat.mem.out
test/lld/hello_world.wat.out
test/lld/init.wat.out
test/lld/longjmp.wat.out
test/lld/main_module.wat.out
test/lld/recursive.wat.out
test/lld/recursive_safe_stack.wat.out
test/lld/reserved_func_ptr.wat.out
test/lld/safe_stack_standalone-wasm.wat.out

See https://github.com/emscripten-core/emscripten/pull/13213

finalize: remove initializers from metadata output

---

src/wasm/wasm-type.cpp
test/passes/Oz_fuzz-exec_all-features.txt
test/passes/Oz_fuzz-exec_all-features.wast

See https://github.com/WebAssembly/gc/issues/175

[GC] rtt types are not defaultable

---

src/wasm/wasm-binary.cpp
src/wasm/wasm-stack.cpp

Some fields were removed, see 
https://docs.google.com/document/d/1yAWU3dbs8kUa_wcnnirDxUu9nEBsNfq0Xo90OWx6yuo/edit#

[GC] Update GC binary format for prototype v3

---

CMakeLists.txt

Followup on original conversion done in #2495.

Consistent lowercase keyword/methods in CMakeLists.txt

---

scripts/fuzz_opt.py
src/tools/fuzzing.h

* Fix label fixup code to use delegates-fields. This makes it support BrOn etc.
* Add an `isRtt()` in places RTTs are not supported.
* Implement `makeConst` for arbitrary RTTs.
This is not enough to get things working for more than a few iterations, but it's
a start...

[GC] Small fuzz fixes for GC

---

src/wasm/wasm-emscripten.cpp

This is a pure refactor in preparation for change that will
enable stripping or at least zeroing segments that only contain
EM_JS/EM_ASM strings.

finalize: Refactor C string extraction code. NFC.

---

src/passes/Memory64Lowering.cpp
src/passes/MemoryPacking.cpp
src/wasm-interpreter.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-emscripten.cpp
src/wasm/wasm-s-parser.cpp
src/wasm/wasm-validator.cpp
test/passes/memory64-lowering_enable-memory64_enable-bulk-memory.wast
test/spec/address64.wast
test/spec/bulk-memory64.wast
test/spec/memory64.wast
test/spec/memory_trap64.wast
test/spec/old_address64.wast

This as a consequence of https://reviews.llvm.org/D95651

Support 64-bit data segment init-exps in Memory64

---

CMakeLists.txt

* VS2017 15.9.12
* cl.exe 19.16.27031.1

Fix VS2017 builds with /std:c++17

---

src/wasm/wasm-s-parser.cpp
src/wasm/wasm-validator.cpp
test/example/c-api-kitchen-sink.c
test/spec/array.wast

This is the first of the GC spec tests that have recently been updated.

[Wasm GC] Add array.wast and validator fixes for it

---

src/wasm/wasm-binary.cpp

The same one appears 3 lines above...

Remove duplicate assertion. NFC

---

CHANGELOG.md
CMakeLists.txt

Release 100

---

src/tools/wasm-reduce.cpp

The old code tried to call `visitExpression` from outside of a walk on the
wasm, which works except that `replaceCurrent` does nothing as there is
no current node. Perhaps it should assert if called outside of a walk? Might
be an expensive check, but once we have no-assert builds maybe that's
worthwhile.
Replace that with a working check during the walk. Also limit the
frequency of it (do it 1000x more often than a normal reduction, but not
all the time like we used to).
Also optimize the starting factor for text reduction. Text files are much
larger for the same amount of IR, so the initial factor was far too high and
inefficient.

Reducer optimizations: Improve reduction of function bodies and text reduction

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-gc.wast
test/passes/Oz_fuzz-exec_all-features.txt

Same as we already do for struct.set.

[Wasm GC] Optimize array.set stored values

---

src/wasm/wasm-validator.cpp

This validation is almost never needed, but it starts to get interesting with
GC, where a global initializer can be an `rtt.sub` which must be valid.
No tests here as testing requires a further GC fix in a later PR.
Maybe it's not worth validating offsets? Those are even more constrained
as to what they can contain than even global initializers. But it seems best
to validate them just to be sure, so we don't miss something in some
future wasm feature.

Validate code in global data structures

---

CHANGELOG.md
src/binaryen-c.cpp
src/binaryen-c.h
test/example/c-api-kitchen-sink.c
test/example/c-api-relooper-unreachable-if.cpp
test/example/c-api-unused-mem.cpp

Use stdbool boolean instead of int to represent boolean values

---

src/wasm/wasm-validator.cpp

Without this we might segfault on the check right below.

[Wasm GC] Validate the number of arguments in struct.new

---

src/wasm/wasm-binary.cpp

See https://webassembly.github.io/spec/core/appendix/custom.html
"Each subsection may occur at most once, and in order of increasing id."

Write names subsections by increasing id

---

src/tools/wasm-reduce.cpp

Previously we just used unreachable. This also tries nop when it is possible,
and sometimes that is better (if the code is called, a nop may be less intrusive
of a change).

Reducer: Replace entire function bodies with either unreachable or nop

---

src/wasm/wasm-emscripten.cpp
test/lld/em_asm_shared.wat.out
test/lld/main_module.wat.out
test/lld/main_module_table.wat.out
test/lld/main_module_table_2.wat.out
test/lld/main_module_table_3.wat.out
test/lld/main_module_table_4.wat.out
test/lld/main_module_table_5.wat.out
test/lld/shared.wat.out
test/lld/shared_add_to_table.wasm.out
test/lld/shared_longjmp.wat.out

See https://github.com/emscripten-core/emscripten/pull/13847

Remove final remnants of name mangling from wasm-emscripten

---

test/example/module-splitting.txt

Elem printing changes raced with a new test with elems.

Update test expectations after colliding landings

---

check.py

Run lit tests with pass-debug as well, to check for more errors

---

src/binaryen-c.cpp
src/binaryen-c.h
test/example/c-api-multiple-tables.c

Becomes BinaryenElementSegmentIsPassive

Fix typo in function name: BinayenElementSegmentIsPassive

---

src/passes/ExtractFunction.cpp

Fix usage comment for ExtractFunction

---

.gitignore
src/binaryen-c.cpp
src/binaryen-c.h
src/js/binaryen.js-post.js
test/binaryen.js/expressions.js
test/binaryen.js/expressions.js.txt
test/binaryen.js/kitchen-sink.js
test/binaryen.js/kitchen-sink.js.txt

Adds the respective getters, setters and wrapper class for `SIMDLoadStoreLane`. With this, the C- and JS-APIs should be ready for SIMD :)

Add SIMDLoadStoreLane get/setters to C/JS API

---

scripts/gen-s-parser.py
src/gen-s-parser.inc
src/ir/ReFinalize.cpp
src/ir/cost.h
src/ir/effects.h
src/passes/OptimizeInstructions.cpp
src/passes/Precompute.cpp
src/passes/Print.cpp
src/wasm-binary.h
src/wasm-builder.h
src/wasm-delegations-fields.h
src/wasm-delegations.h
src/wasm-interpreter.h
src/wasm-s-parser.h
src/wasm.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-s-parser.cpp
src/wasm/wasm-stack.cpp
src/wasm/wasm-validator.cpp
src/wasm/wasm.cpp
src/wasm2js.h
test/heap-types.wast
test/heap-types.wast.from-wast
test/heap-types.wast.fromBinary
test/heap-types.wast.fromBinary.noDebugInfo
test/passes/Oz_fuzz-exec_all-features.txt
test/passes/Oz_fuzz-exec_all-features.wast

Spec for it is here:
https://docs.google.com/document/d/1DklC3qVuOdLHSXB5UXghM_syCh-4cMinQ50ICiXnK3Q/edit#
Also reorder some things in wasm.h that were not in the canonical order (that has
no effect, but it is confusing to read).

[Wasm GC] Add experimental array.copy

---

src/ir/bits.h
src/ir/properties.h
test/example/cpp-unit.cpp

[OptimizeInstructions] Handle post-MVP sign extended operations

---

src/ir/global-utils.h
test/heap-types.wast
test/heap-types.wast.from-wast
test/heap-types.wast.fromBinary
test/heap-types.wast.fromBinary.noDebugInfo

This is being experimented with and is supported in V8.

[Wasm GC] Support struct.new in global initializers

---

src/passes/Precompute.cpp
test/passes/precompute_all-features.txt
test/passes/precompute_all-features.wast

We had the logic in only one place.
Fixes https://github.com/emscripten-core/emscripten/issues/14629

Fix Precompute on SIMD

---

check.py

Add .DS_Store to non executable filter in check.py

---

src/tools/wasm-reduce.cpp

Practically NFC, but it does reorder some code a little. Previously we would
find a "zero", then shrink segments, then use that zero - which might no
longer be in the table. That seems weird, so this reorders that, but there
should be no significant difference in the output.
Also reduce the factor of 100 to 1, which in practice is important on one of
the Dart GC benchmarks that has a huge number of table segments.

Clean up and rewrite wasm-reduce element segment logic.

---

src/wasm/literal.cpp

Idea and motivation was described [here](https://github.com/WebAssembly/binaryen/pull/4016#issuecomment-885602111)

[SIMD] Refactor extend helper

---

src/literal.h
src/wasm-interpreter.h
src/wasm/literal.cpp
test/spec/simd.wast

```ts
i16x8.extadd_pairwise_i8x16_s
i16x8.extadd_pairwise_i8x16_u
i32x4.extadd_pairwise_i16x8_s
i32x4.extadd_pairwise_i16x8_u
```

[Simd] Add extending pairwise adds to interpreter

---

src/literal.h
src/wasm-interpreter.h
src/wasm/literal.cpp
test/spec/simd.wast

```ts
f64x2.convert_low_i32x4_s
f64x2.convert_low_i32x4_u
i32x4.trunc_sat_f64x2_s_zero
i32x4.trunc_sat_f64x2_u_zero
f32x4.demote_f64x2_zero
f64x2.promote_low_f32x4
```

[Simd] Implement extra convert, trunc, demote and promote ops for interpreter

---

src/passes/SimplifyGlobals.cpp

An optimization was added there without updating the comment.

Add a comment in SimplifyGlobals to document existing work

---

src/wasm/wasm-type.cpp
test/example/type-builder-nominal.cpp

The wrong variable was null checked, leading to segfaults.

Fix a bug in nominal LUB calculation

---

src/ir/cost.h

The cost type isn't an index in a wasm binary, it's just a number.
As suggested by @tlively

Costs: Index => ContType

---

test/unit/test_asyncify.py

Add a test for too many locals in Asyncify

---

src/passes/Asyncify.cpp
src/wasm-type.h
src/wasm/wasm-type.cpp

Show a clear error on asyncify+references. Helps #3739

---

CHANGELOG.md
CMakeLists.txt

This includes a fix for a segfault which has been a problem for
users, #4139

Version 102

---

src/wasm-interpreter.h
test/passes/Oz_fuzz-exec_all-features.txt
test/passes/Oz_fuzz-exec_all-features.wast

Fix interpreting of ref.as_func|data

---

src/ir/ExpressionManipulator.cpp
src/mixed_arena.h
src/wasm/wasm.cpp

also insert couple reserve heap spaces

[Refactoring] More code reusage

---

CMakeLists.txt
src/wasm-type.h
src/wasm/CMakeLists.txt

Remove use of std::iterator

---

src/ir/branch-utils.h
src/passes/Inlining.cpp
test/lit/passes/inlining_optimize-level=3.wast

Quite a corner case, but the fuzzer found it...

Fix inlining name collision

---

src/tools/CMakeLists.txt
src/tools/fuzzing.h
src/tools/fuzzing/fuzzing.cpp
src/tools/fuzzing/random.cpp
src/tools/fuzzing/random.h

In preparation for using it from a separate file specifically for generating
random HeapTypes that has no need to depend on all of fuzzing.h.

[NFC] Factor fuzzer randomness into a separate utility

---

scripts/fuzz_opt.py

(I hit this after recently renaming a lit test...)

Handle removed/renamed initial contents in fuzzer

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/inlining-optimizing_optimize-level=3.wast
test/lit/passes/optimize-instructions.wast

```rust
(i32(x) != 0) | (i32(y) != 0)   ==>   i32(x | y) != 0
(i64(x) != 0) | (i64(y) != 0)   ==>   i64(x | y) != 0
```

[OptimizeInstructions] Combine some relational ops joined Or/And (Part 2)

---

src/wasm/wasm-type.cpp

We have always cached nominal signature types keyed on their signatures to avoid
creating extra nominal types through the `HeapType::HeapType(Signature)`
constructor. However, that logic was previously built into the HeapTypeInfo
canonicalization system. To allow that system to be simplified in future PRs,
separate the caching into its own explicit layer.

[NFC] Add a separate cache for nominal signature types

---

src/wasm/wasm-type.cpp

Now that caching of "canonical" nominal signatures is handled at a separate
layer, we can remove the separate code paths for hashing and comparing
HeapTypeInfos based on their structure even in nominal mode. Now hashing and
comparing of HeapTypeInfos is uniformly handled by FiniteShapeHasher and
FiniteShapeEquator.

[NFC] Simplify HeapTypeInfo hashing and comparison

---

src/wasm/wasm-type.cpp

Hashing and comparison of nominal HeapTypeInfos previously observed their child
Types, so the Types had to be canonicalized before the HeapTypes. Unfortunately
equirecursive canonicalization requires that the HeapTypes be canonicalized
before the Types, so this was a point of divergence between the two systems.
However, #4394 updated hashing and comparison of nominal types to not depend on
child Types, so now we can harmonize the two systems by having them use the same
`globallyCanonicalize` function to canonicalize their HeapTypes followed by
their Types.

[NFC] Reuse `globallyCanonicalize` for nominal types

---

CHANGELOG.md
CMakeLists.txt

Version 104

---

src/binaryen-c.cpp
src/binaryen-c.h

fix BinaryenTypeCreate argument numTypes type, all other numXxxs argement

fix BinaryenTypeCreate argument numTypes type, all other numXxxs argement

---

src/tools/wasm-ctor-eval.cpp

A bit less explicit I think but definitely more idiomatic.

[ctor-eval] Use std::optional for EvalCtorOutcome

---

src/ir/CMakeLists.txt
src/ir/module-utils.cpp
src/ir/module-utils.h

In preparation for the refactoring in #4455.

[NFC] Move ModuleUtils::collectHeapTypes to a .cpp file

---

src/wasm/wasm-type.cpp

Since isorecursive canonicalization will happen incrementally in a bottom-up
manner, it will be more efficient if can more precisely control which types get
updated at each step. Refactor the `CanonicalizationState` interface to
separately expose shallow updating, which updates only the top-level state, and
deep updating of the use sites within HeapTypeInfos.

[NFC] Split shallow and deep updating of CanonicalizationState

---

README.md
src/tools/wasm-ctor-eval.cpp
test/lit/help/wasm-ctor-eval.test

I noticed we didn't really have docs for this tool, when someone asked
me what it does...

[Docs] Document wasm-ctor-eval

---

src/tools/wasm-fuzz-types.cpp

This makes it easier to get an overview of what methods exist by looking at the
shorter struct definition.
Conflicts with #4503, but that should be easy to resolve.

[NFC] Move type fuzzer method definitions out of line

---

src/emscripten-optimizer/parser.cpp
src/emscripten-optimizer/parser.h
src/emscripten-optimizer/simple_ast.h
src/wasm2js.h
test/wasm2js/export_global.2asm.js
test/wasm2js/export_global.2asm.js.opt
test/wasm2js/export_global.wast

feat(wasm2js): export global var

---

src/passes/MemoryPacking.cpp

The memory packing pass previously used vectors with a slot for each data
segment to easily map segment indices to lists of "referrers," i.e. bulk memory
expressions that referred to the segments. The parallel analysis pass to collect
these referrers allocated one of these vectors for each function in a module.
Unfortunately, for a particularly large module with over 200k functions and over
75k data segments, this resulted in hundreds of gigabytes of memory allocations.
The vast majority of functions contain no referrers, so using a
std::unordered_map makes much more sense than using a vector to perform this
mapping.

[NFC][MemoryPacking] Avoid unnecessarily enormous memory allocations

---

src/tools/wasm-shell.cpp
src/wasm-type.h
src/wasm/wasm-type.cpp
src/wasm/wasm-validator.cpp
test/lit/validation/nn-tuples.wast

[Wasm GC] Fix non-nullable tuples

---

scripts/gen-s-parser.py
src/gen-s-parser.inc
src/ir/cost.h
src/passes/Print.cpp
src/wasm-binary.h
src/wasm-interpreter.h
src/wasm.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-stack.cpp
src/wasm/wasm-validator.cpp
test/lit/relaxed-simd.wast

As proposed in https://github.com/WebAssembly/relaxed-simd/issues/40.

Implement i16x8.relaxed_q15mulr_s

---

src/tools/wasm-reduce.cpp

Previously we'd only try to remove functions from index 0, so we missed
some opportunities. With this change we still go through all the functions
if things go well, but we start from a deterministic random location in the
vector.

wasm-reduce: Try to remove functions from a random place

---

src/passes/DeadArgumentElimination.cpp

Reduce iterations required for dead argument elimination convergence
Crude measurements 
Before:
```
[PassRunner]   running pass: dae-optimizing...                     53.1484 seconds.
```
After:
```
[PassRunner]   running pass: dae-optimizing...                     39.9249 seconds.
```
<details>
<summary>More details</summary>
<details>
<summary>Before</summary>
```
[PassRunner] running passes
[PassRunner]   running pass: dae-optimizing...                     
Function Count: 132035
Iteration: 1
removedParams: 12961
returnValuesRemoved: 0
Iteration: 2
removedParams: 2343
returnValuesRemoved: 0
Iteration: 3
removedParams: 903
returnValuesRemoved: 0
Iteration: 4
removedParams: 553
returnValuesRemoved: 0
Iteration: 5
removedParams: 409
returnValuesRemoved: 0
Iteration: 6
removedParams: 303 …
```

Reduce iterations required for dead argument elimination convergence

---

src/passes/DeadArgumentElimination.cpp

Reverts WebAssembly/binaryen#4629

Revert "Reduce iterations required for dead argument elimination convergence"

---

src/passes/Directize.cpp
src/passes/OptimizeInstructions.cpp
src/passes/call-utils.h
test/lit/passes/directize_all-features.wast
test/lit/passes/optimize-instructions-call_ref.wast

Just a draft, uploading for experimentation.

OptimizeInstructions: Turn call_ref of a select into an if over two direct calls 

---

src/tools/fuzzing.h
src/tools/fuzzing/fuzzing.cpp

This just moves code around + adds assertions.

Fuzzer: Refactor makeConst into separate functions [NFC]

---

src/wasm/wasm-io.cpp
src/wasm/wat-lexer.cpp
src/wasm/wat-parser.cpp
src/wat-lexer.h
src/wat-parser.h
test/gtest/wat-lexer.cpp

Apply cleanups suggested by aheejin@ in post-merge code review of previous
parser PRs.

[Parser][NFC] Small code cleanups

---

scripts/fuzz_opt.py

Disable Wasm2C in fuzz_opt

---

src/cfg/cfg-traversal.h
src/tools/wasm-reduce.cpp
src/tools/wasm-shell.cpp

I tried another compiler and found more warnings...

Fix more no-assertions warnings

---

scripts/gen-s-parser.py
src/gen-s-parser.inc
src/ir/ReFinalize.cpp
src/ir/cost.h
src/ir/effects.h
src/ir/possible-contents.cpp
src/passes/Print.cpp
src/wasm-binary.h
src/wasm-builder.h
src/wasm-delegations-fields.def
src/wasm-delegations.def
src/wasm-interpreter.h
src/wasm-s-parser.h
src/wasm.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-s-parser.cpp
src/wasm/wasm-stack.cpp
src/wasm/wasm.cpp
src/wasm2js.h
test/lit/strings.wast

[Strings] string.measure

---

scripts/gen-s-parser.py
src/gen-s-parser.inc
src/passes/Print.cpp
src/wasm-binary.h
src/wasm.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-stack.cpp
test/lit/strings.wast

This measures the length of a view, so it seems simplest to make it a
sub-operation of the existing measure instruction.

[Strings] stringview_wtf16.length

---

src/binaryen-c.cpp
src/binaryen-c.h
src/js/binaryen.js-post.js
test/binaryen.js/kitchen-sink.js
test/binaryen.js/kitchen-sink.js.txt

[C/JS-Api] Expose string reference feature

---

src/ir/drop.cpp

Simplify early return if children are empty

Refactor getDroppedChildrenAndAppend

---

src/passes/SimplifyLocals.cpp
test/lit/passes/simplify-locals-gc.wast

SimplifyLocals: ReFinalize when needed

---

src/wasm/wasm-binary.cpp
src/wasm/wasm-s-parser.cpp
test/lit/strings.wast

Like the 8-bit array variants, it takes 3 parameters.

[Strings] Fix string.new_wtf16_array

---

README.md
scripts/auto_update_tests.py
scripts/test/wasm2js.py

So it lives alongside `update_lit_checks.py` and `update_help_checks.py`

Move `auto_update_tests.py` into scripts directory. NFC

---

src/passes/param-utils.cpp
test/lit/passes/dae_tnh.wast

Only look at the relevant parameter in param-utils:removeParameter

---

src/wasm/wasm-binary.cpp

Local name will be out of order when `funcMappedLocals` has a different order with function's local.
However webassembly spec require the order of local name in custom name section (see https://webassembly.github.io/spec/core/appendix/custom.html#binary-namemap).
So this PR move the mapping logic into loop and add sort logic between mapping and writing.

fix local name out of order

---

src/tools/tool-options.h
src/wasm-binary.h
src/wasm-features.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-validator.cpp
src/wasm/wasm.cpp
test/binaryen.js/kitchen-sink.js.txt
test/example/c-api-kitchen-sink.txt
test/lit/help/wasm-as.test
test/lit/help/wasm-ctor-eval.test
test/lit/help/wasm-dis.test
test/lit/help/wasm-emscripten-finalize.test
test/lit/help/wasm-metadce.test
test/lit/help/wasm-opt.test
test/lit/help/wasm-reduce.test
test/lit/help/wasm-split.test
test/lit/help/wasm2js.test
test/passes/strip-target-features_roundtrip_print-features_all-features.txt
test/unit/test_features.py

Adding multi-memories to the the list of wasm-features.

Adding Multi-Memories Wasm Feature

---

src/wasm-binary.h
src/wasm/wasm-binary.cpp
test/lit/wat-kitchen-sink.wast

Similar to #4969 but for globals.

[NFC] Simplify binary reading logic for globals

---

src/wasm-binary.h
src/wasm/wasm-binary.cpp

Similar to #4969 but for memories.

[NFC] Simplify binary reading logic for memories

---

src/wasm-binary.h
src/wasm/wasm-binary.cpp

Similar to #4969 but for element segments.

[NFC] Simplify binary reading logic for element segments

---

test/lit/passes/optimize-instructions.wast

See https://github.com/WebAssembly/binaryen/pull/4282#discussion_r957509149

[tests] Fix comments in optimize-instructions.wast

---

src/tools/fuzzing/heap-types.cpp

The only call to `generateSubBasic` was removed as part of a bug fix in #4346,
but the function itself was not removed. Remove it and other unused functions it
depends on now.

[NFC] Remove unused code in type fuzzer

---

.gitignore

This directory gets generated by emcc-tests.sh

Add emcc-build to .gitignore. NFC

---

src/passes/Vacuum.cpp
test/lit/passes/vacuum-eh.wast

A try whose body throws, and does nothing else, and the try catches that
exception, can be removed.

Vacuum trivial trys

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions.wast

See https://github.com/WebAssembly/binaryen/pull/5034#issuecomment-1253861584

[OptimizeInstruction] Prevent reordering for rule in #5034

---

src/ir/possible-contents.cpp
test/lit/passes/gufa-refs.wast

Similar to ref.cast slightly, but simpler.
Also update some TODO text as I go through them.

[GUFA] Optimize ref.test

---

.github/workflows/ci.yml

This should fix current binaryen.js breakage.

Pin the emsdk for now

---

CHANGELOG.md
src/binaryen-c.cpp
src/binaryen-c.h
src/ir/type-updating.cpp
src/wasm-type.h
src/wasm/wasm-type.cpp
test/example/c-api-kitchen-sink.c
test/gtest/type-builder.cpp

[C API] Make TypeBuilderSetSubType take a heap type

---

src/ir/possible-contents.cpp
src/ir/possible-contents.h
src/passes/GUFA.cpp
test/gtest/possible-contents.cpp
test/lit/passes/gufa-refs.wast

If the PossibleContents for the two sides have no possible intersection then the
result must be 0.

[GUFA] Infer a RefEq value of 0 when possible

---

src/ir/possible-contents.cpp
src/ir/possible-contents.h
src/passes/GUFA.cpp

See https://github.com/WebAssembly/binaryen/pull/5081#issuecomment-1256737179 - this is the same as that fix but for RefTest

[GUFA] Fix RefTest logic

---

src/ir/possible-contents.h
src/support/hash.h
test/gtest/possible-contents.cpp

Avoid manually doing bitshifts etc. - leave combining to the core hash
logic, which can do a better job.

[GUFA] Improve hashing

---

test/gtest/possible-contents.cpp

Just an automatic test that `A` has an intersection with `A + B` for the contents
in our unit test.

[GUFA] Test that combined things intersect with the combination.

---

src/ir/possible-contents.cpp

The last parameter is the function to call, and we treated it like a normal parameter.
This is mostly only an issue during debugging, but in theory sending this extra value
could cause us to optimize less later (since it gets added to what the local of that
index can contain).
Also add assertions which would have caught this before.

[GUFA] Fix call.without.effects's handling of the last parameter

---

scripts/wasm2js.js

Fixes `./scripts/fuzz_opt.py --auto-initial-contents 7044408155933374954`

Fix fuzzer after #5114

---

src/wasm/wat-parser.cpp
test/lit/wat-kitchen-sink.wast

Also add some missing error checking for the similar local instructions and make
some neighboring styling more consistent.

[Parser] Parse global.get and global.set

---

src/wasm/wat-parser.cpp
test/lit/wat-kitchen-sink.wast

Including all `SIMDExtract`, `SIMDReplace`, `SIMDShuffle` expressions.

[Parser] Parse SIMD lane manipulation instructions

---

src/wasm/wat-parser.cpp

ParseDefsCtx was the only client of the CRTP InstrParserCtx utility and the
separation between the two did not serve a real purpose. Simplify the code by
combining them.

[Parser][NFC] Combine InstrParserCtx into ParseDefsCtx

---

src/passes/Asyncify.cpp

I just noticed this trivial typo when working on this suggestion https://github.com/sagemathinc/cowasm/issues/39

Fix trivial typo in the docs.

---

src/wasm/wat-parser.cpp

Fix for building on gcc 10.2 (Debian 11) (#5188)

---

src/wasm/wat-parser.cpp

Work around some gcc 10.x issues

---

src/wasm/wasm-validator.cpp
test/lit/validation/shared-memory.wast
test/unit/test_features.py

E.g.
```
Atomic operation (atomics are disabled)
=>
Atomic operations require threads [--enable-threads]
```

[NFC] Mention relevant flags in validator errors

---

src/passes/SimplifyLocals.cpp
test/lit/passes/simplify-locals-gc.wast

We just checked if the new type we prefer (when switching a local to a more
refined one in #5194) is different than the old type. But that check at the end
must check it is a subtype as well.

SimplifyLocals: Fix handling of subtyping

---

src/support/small_set.h
test/example/small_set.cpp

We did not preserve the ordering of the fixed-size storage there.

Fix SmallSet ordering

---

CHANGELOG.md
CMakeLists.txt

Depends on https://github.com/emscripten-core/emscripten/pull/18219.

Release 111

---

src/ir/local-utils.h
test/lit/passes/simplify-locals-gc.wast

[Wasm GC] Refinalize in UnneededSetRemover when necessary

---

src/binaryen-c.cpp
src/ir/module-utils.h
src/passes/Print.cpp
src/passes/Strip.cpp
src/wasm-binary.h
src/wasm.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-debug.cpp
src/wasm/wasm.cpp

This reflects that naming used in the spec.

Rename UserSection -> CustomSection. NFC

---

src/passes/Print.cpp

This can help debugging sometimes.

[NFC] Print type names in BINARYEN_PRINT_FULL mode

---

src/wasm/wat-lexer.cpp

It turns out that this assumption does not necessarily hold on Windows with
Visual Studio 2019. Instead of using `NAN` and `-NAN`, explicitly construct
positive and negative NaN values with `std::copysign`, which should be portable.
Fixes #5291.

[Parser] Do not assume `NAN` is positive

---

CMakeLists.txt

This better reflects what it really means. Also I noticed that it wasn't declared.

Rename BYN_INSTALL_TOOLS_ONLY to INSTALL_LIBS (NFC)

---

src/passes/TypeSSA.cpp
test/lit/passes/type-ssa.wast

Previously it only handled structs.

[Wasm GC] Add array support to TypeSSA

---

src/support/istring.h

Make wasm::IString::operator bool() explicit

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-gc.wast

Also add some comments on related optimization opportunities.

[Wasm GC] Optimize impossible ref.casts better

---

src/ir/gc-type-utils.h
test/lit/passes/optimize-instructions-gc.wast

[Wasm GC] Add missing unreachable check in evaluateKindCheck

---

src/passes/GlobalStructInference.cpp

Fix iterator invalidation bug in GlobalStructInference

---

src/ir/gc-type-utils.h
src/passes/RemoveUnusedBrs.cpp

Since we refactored all the old kind-checking instructions to be represented as
general cast instructions, `GCTypeUtils::evaluateKindCheck` had become a
vestigial wrapper around `GCTypeUtils::evaluateCastCheck` that was only used in
RemoveUnusedBrs. Remove `evaluateKindCheck` and use `evaluateCastCheck` in
RemoveUnusedBrs without changing any functionality. A future PR may use the
extra information from `evaluateCastCheck` to further optimize branching casts.

[NFC] Remove GCTypeUtils::evaluateKindCheck

---

src/binaryen-c.cpp
src/wasm-s-parser.h
src/wasm/wasm-s-parser.cpp

Fix segment fault of API BinaryenModuleParse (#5440)

---

src/ir/drop.cpp
test/lit/passes/optimize-instructions-gc.wast

Fix OptimizeInstructions on null trap of struct.set

---

scripts/gen-s-parser.py
src/gen-s-parser.inc
src/passes/Print.cpp
src/wasm-binary.h
src/wasm.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-stack.cpp
test/lit/strings.wast

See https://github.com/WebAssembly/stringref/issues/60

[Strings] Add experimental string.hash instruction

---

src/literal.h
src/wasm/literal.cpp
test/lit/passes/rse-gc.wast

[Strings] Add hashing and equality support for strings

---

src/wasm/wasm-validator.cpp
test/lit/validation/bulk.wast

`shouldBeFalse` was misused in that place.
Fixes #5511

Fix validation of DataDrop

---

src/tools/fuzzing/fuzzing.cpp

This fixes an existing TODO, which is being hit as I start to fuzz more GC stuff.

Fuzzer: Create struct/array initial values when fields are nondefaultable

---

scripts/fuzz_opt.py

If this number ever gets high then we would need to look into
why we ignore so much. Right now we seem to end up ignoring
much less than 1%.

Fuzzer: Count the number of VM runs we ignore

---

src/passes/SignaturePruning.cpp

The order of iteration on `sigFuncs` there can matter, as each time we
prune we end up changing things that can affect other prunings (specifically,
`ParamUtils::removeParameter` can decide that it can't remove a parameter
based on the effects on arguments, and current limitations in how we handle
that; and pruning can affect effects).

[Wasm GC] Fix nondeterminism in SignaturePruning

---

src/passes/RemoveUnusedModuleElements.cpp
test/lit/passes/remove-unused-module-elements_all-features.wast

RemoveUnusedModuleElements: Add SIMD support for memory operations

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-gc-tnh.wast

This is the flip case of #5630

[Wasm GC] Handle another unreachability case in trapOnNull()

---

src/ir/possible-contents.cpp
test/lit/passes/gufa-refs.wast

Looks like it is fairly simple to do, but it requires some hacks...

[Wasm GC] Fix GUFA on ArrayInit 

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-gc.wast

The fuzzer found another case we were missing. I realized that we can just
check for this in `replaceCurrent`, at least for places that call that method,
which is the common case. So this simplifies the code while fixing a bug.

Fix and simplify refinalization in OptimizeInstructions

---

src/ir/struct-utils.h
src/passes/RemoveUnusedModuleElements.cpp
src/tools/fuzzing.h
src/tools/fuzzing/fuzzing.cpp
test/passes/translate-to-fuzz_all-features_metrics_noprint.txt

Fuzzing with this locally has led to many of the recent fixes.

[Wasm GC] Fuzz struct.get and array.get

---

CMakeLists.txt

Remove binaryen.js debug build changes to WASM_BIGINT flag

---

src/tools/wasm-reduce.cpp

I've seen some of these help in practice, and the others seem useful.

wasm-reduce: Add more passes

---

src/wasm/wasm-type.cpp

Remove an unused `isFinalized` field and slightly simplify other miscellaneous
code.

[NFC] Minor simplifications in wasm-type.cpp

---

src/passes/Inlining.cpp

This patch doesn't inline the methods to help with the review. I will follow up with another patch to inline them.

Split the maybeSplit into canSplit/doSplit

---

src/passes/Inlining.cpp

[NFC] Add some comments for split inlining crossing the normal limit

---

src/passes/OptimizeCasts.cpp

Improve TODO docs in OptimizeCasts

---

CHANGELOG.md
CMakeLists.txt

This contains the recent `-O3 -Oz` fix which users have asked a release for.

Release version 114

---

src/tools/wasm-metadce.cpp

[NFC] Add a helper to get function DCE names in wasm-metadce

---

test/lit/passes/heap2local.wast

This already worked (thanks to LocalGraph integration), but add an explicit test to
verify that just to be sure.

Heap2Local: Add a test for params

---

src/passes/hash-stringify-walker.cpp
src/passes/stringify-walker-impl.h
src/passes/stringify-walker.h

Added the license to recently added files per #5818

Adding license header to new files

---

src/passes/Print.cpp
src/wasm.h
test/gtest/CMakeLists.txt
test/gtest/printing.cpp

Add support for debug printing of functions

---

src/support/small_vector.h
test/example/small_vector.cpp

I needed these to experiment with replacing the vector in CFGWalker. However, I saw
no benefit to doing so, so I won't be landing that. But these iterator improvements
may help in the future (and I had to fight the C++ compiler quite a bit for them...).

SmallVector iteration improvements

---

src/wasm/wasm-binary.cpp
test/lit/binary/strings-nogc.test

I'm actually not sure this is right, but it fixes the fuzz bug. Thoughts?

Fix binary writing of strings without GC enabled

---

src/ir/possible-contents.cpp

In order of appearance in this diff:
* Use `heapType` rather than `otherHeapType` when either will do, for brevity.
* We checked `isNull` after checking for `isLiteral` (line 173), but every null is a literal.
* Calling `setNoneOrNull` simplifies some repetitive code.
* We checked `isLiteral` yet again lower down.

[NFC] Remove some unneeded cruft from PossibleContents::intersect()

---

src/passes/TypeSSA.cpp
test/lit/passes/type-ssa.wast

This has been a bug for a while but it became noticeable after #5881 #5882
which do more work in refinalization.

ReFinalize in TypeSSA

---

README.md

I thought it might be useful to document some things I learned about
source maps recently.

[NFC] Document source maps and other debug support

---

third_party/llvm-project/ConvertUTF.cpp
third_party/llvm-project/include/llvm/Support/ConvertUTF.h

Almost no actual change in the files except for a license update. The new license
is a proper FOSS one, it turns out, see #5947
Fixes #5947

Update two files from upstream LLVM, ConvertUTF.h,cpp

---

src/parser/contexts.h
src/parser/input-impl.h
src/parser/input.h
src/parser/parsers.h
src/wasm-ir-builder.h
src/wasm/wasm-ir-builder.cpp
test/lit/wat-kitchen-sink.wast

Parse loops in the new wat parser and add support for them to the IRBuilder.

[Parser] Support loops

---

src/passes/Directize.cpp
test/lit/passes/directize_all-features.wast

Like `table.set`, it can modify a table.

Handle table.fill in Directize

---

src/passes/StackIR.cpp

[NFC] Refactor StackIR code to clarify local variable meanings

---

test/lit/passes/asyncify_optimize-level=1.wast

This test is failing on main, perhaps because of a faulty rebase. Fixing with the result of running update_lit_test.py

Updating asyncify_optimize-level=1 test

---

src/tools/tool-options.h
src/wasm-binary.h
src/wasm-features.h
src/wasm/wasm-binary.cpp
src/wasm/wasm.cpp
test/binaryen.js/kitchen-sink.js.txt
test/example/c-api-kitchen-sink.txt
test/lit/help/wasm-as.test
test/lit/help/wasm-ctor-eval.test
test/lit/help/wasm-dis.test
test/lit/help/wasm-emscripten-finalize.test
test/lit/help/wasm-merge.test
test/lit/help/wasm-metadce.test
test/lit/help/wasm-opt.test
test/lit/help/wasm-reduce.test
test/lit/help/wasm-split.test
test/lit/help/wasm2js.test
test/passes/strip-target-features_roundtrip_print-features_all-features.txt
test/unit/test_features.py

This PR is part of a series that adds basic support for the [typed continuations proposal](https://github.com/wasmfx/specfx).
This particular PR simply extends `FeatureSet` with a corresponding entry for this proposal.

Typed Continuations: Add feature flag

---

.github/codecov.yml

Disable codecov GitHub comments and PR-specific coverage checks.

Configure codecov to be less intrusive

---

README.md

- Link building instructions.
- Add hint for building on macOS.
- Some syntax highlighting fixes.
- Minor formatting (code font, remove duplicate spaces, smart quotes,…).

Minor improvements for the `README`

---

test/gtest/stringify.cpp

Added type to fix template deduction failure

---

src/passes/hash-stringify-walker.cpp
src/passes/stringify-walker.h
test/gtest/stringify.cpp

Adds a function to filter branch and return instructions from being included in potential outlining candidates.

[Outlining] Filter branches & returns

---

src/analysis/lattices/stack.h
src/tools/wasm-fuzz-lattices.cpp
test/gtest/cfg.cpp

Also shorten various names in the implementation to improve readability.

[analysis][NFC] Move the stack lattice to analysis/lattices

---

check.py
scripts/test/shared.py
scripts/test/wasm2js.py
scripts/test/wasm_opt.py
test/unit/test_asyncify.py
test/unit/test_passes.py

Avoid some common warnings and stop printing various stdout/stderr stuff.
Helps #6104 - maybe fixes it, what do you think @sbc100 ?

Remove various testing spam

---

src/passes/Outlining.cpp
src/passes/hash-stringify-walker.cpp
test/gtest/stringify.cpp
test/lit/passes/outlining.wast

Checking a couple of testing TODOs off and adding more tests of the outlining pass for outlining:
- a sequence at the beginning of an existing function
- a sequence that is outlined into a function that takes no arguments
- multiple sequences from the same source function into different outlined functions

[Outlining] Adding more tests

---

src/ir/properties.cpp
test/lit/passes/local-cse_all-features.wast

[WasmGC] Add missing ArrayNew variants to Properties::isGenerative

---

CHANGELOG.md
CMakeLists.txt

There was a request for this (https://github.com/WebAssembly/binaryen/issues/6710#issuecomment-2211031853) and it's been a while, and I can't think of any blockers atm.

Version 118

---

scripts/test/shared.py

Add comments to the spec test skip list briefly explaining why each
skipped spec test must be skipped.

[NFC] Triage spec test problems

---

.github/workflows/ci.yml

We started to error on this, e.g.
https://github.com/WebAssembly/binaryen/actions/runs/10705658056/job/29681561108?pr=6899

Investigate GitHub deprecation of artifact uploading v1

---

src/passes/ReorderGlobals.cpp

We previously computed both forward and reverse dependence graphs, but
one of them was only used for a single topological sort that could just
as well be computed by reversing the topological sort on the other
graph.

[NFC] Compute only one dependence graph in ReorderGlobals

---

CHANGELOG.md
CMakeLists.txt

Motivation: https://github.com/WebAssembly/binaryen/issues/6907

Version 119

---

src/passes/Heap2Local.cpp
test/lit/passes/heap2local.wast

The fuzzer probably found it using the other recent testcase added to the test suite...

Fix Heap2Local on pops inside of newly-created blocks

---

src/passes/TypeRefining.cpp
test/lit/passes/type-refining.wast

Found from fuzzing a Kotlin testcase.

[GC] Fix handling of public types in TypeRefining

---

scripts/fuzz_opt.py

When fuzzing wasm-merge, we need to avoid the first module not having
an exported table but the second having one, as the way the table operation
imports work, they are sensitive to the existence of such an export, so just
merging in such an export can alter behavior.

Fuzzer: Handle exported table for wasm-merge

---

scripts/fuzz_opt.py

(hard to test these fuzzer things...)

Fix flipped condition on keep_defaults in fuzzer

---

src/abi/stack.h
src/binaryen-c.cpp
src/ir/child-typer.h
src/ir/memory-utils.cpp
src/ir/module-utils.cpp
src/parser/context-decls.cpp
src/parser/contexts.h
src/parser/parsers.h
src/passes/AlignmentLowering.cpp
src/passes/AvoidReinterprets.cpp
src/passes/GenerateDynCalls.cpp
src/passes/InstrumentMemory.cpp
src/passes/Memory64Lowering.cpp
src/passes/MemoryPacking.cpp
src/passes/MultiMemoryLowering.cpp
src/passes/SafeHeap.cpp
src/passes/SimplifyLocals.cpp
src/passes/SpillPointers.cpp
src/passes/StackCheck.cpp
src/passes/Table64Lowering.cpp
src/tools/fuzzing/fuzzing.cpp
src/tools/wasm-ctor-eval.cpp
src/tools/wasm-split/instrumenter.cpp
src/wasm-binary.h
src/wasm-builder.h
src/wasm-interpreter.h
src/wasm.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-validator.cpp

See https://github.com/WebAssembly/memory64/pull/92

Rename indexType -> addressType. NFC

---

scripts/fuzz_opt.py

It never used the parameter, so remove that (we always access the
features using a global anyhow).
But add a new parameter, the wasm file, which does need to be
passed in for a later PR (so in this PR it is just for future use).

[NFC] Refactor fuzzer's can_run_on_feature_opts()

---

scripts/fuzz_opt.py

I am told this is a good thing to fuzz with. It enables internal flags like new
JITS and such, that are worth fuzzing.

Fuzzer: Use V8's --future flag

---

scripts/clusterfuzz/run.py
test/unit/test_cluster_fuzz.py

This just moves code around. It will allow more code reuse in a later PR.
Also add a bit of test logging.

[NFC] Refactor ClusterFuzz run.py

---

scripts/fuzz_opt.py

This increases our testing of V8.
The downside is that it is a little slower, but that seems acceptable.

[Fuzzing] Maximize fuzzing of CompareVMs

---

src/passes/TypeMerging.cpp
test/lit/passes/type-merging.wast

The LUB of sibling types is their common supertype, but after the
sibling types are merged, their LUB is the merged type, which is a
strict subtype of the previous LUB. This means that merging sibling
types causes `selects` to have stale types when the two select arms
previously had the two merged sibling types. To fix any potential stale
types, ReFinalize after merging sibling types.

ReFinalize after merging siblings in TypeMerging

---

test/lit/node/fuzz_shell_second.wast
test/lit/node/fuzz_shell_second.wast.second

This feature is depended on by our ClusterFuzz integration.

[NFC] Add a node test for fuzz_shell.js running on two input wasms

---

CHANGELOG.md
src/wasm-binary.h

The PR was accidentally merged without these fixes included.

Address comments from #7149

---

src/passes/GlobalTypeOptimization.cpp
test/lit/passes/gto-removals.wast

GTO removes fields that are never read and also removes sets to those
fields. Update the pass to add a seqcst fence when removing a seqcst set
to preserve its effect on the global order of seqcst operations.

Handle atomics in GTO

---

src/passes/Outlining.cpp

During function reconstruction, a walker iterates thru each instruction of a function, incrementing a counter to find matching sequences. As a result, the sequences of a function must be sorted by smallest start index, otherwise reconstruction will miss outlining a repeat sequence.
I considered making a test for this commit, but the sort wasn't needed until the tests started running on GitHub infra. I'm not sure what specific architecture is causing the discrepancy in vector ordering, but let's introduce the sort to be safe.

[Outlining] Sort sequences by order appeared in function

---

test/unit/test_cluster_fuzz.py

[NFC] Ignore MemoryPacking warning in ClusterFuzz test

---

src/tools/fuzzing.h
src/tools/fuzzing/fuzzing.cpp

This adds more variety in some situations.

Fuzzer: Shuffle exports

---

src/passes/Monomorphize.cpp

This was done in #6760 ("monomorphize all the things").

Remove stale TODO in Monomorphize.cpp [NFC]

---

src/parser/parsers.h

This should have been removed in #7252.

[NFC] Remove redundant assertion

---

src/interpreter/interpreter.cpp
test/gtest/interpreter.cpp

Building on top of #7227, i32.mul is implemented and tested.

[Interpreter] i32.mul

---

src/interpreter/interpreter.cpp
test/gtest/interpreter.cpp

Reverts WebAssembly/binaryen#7260

Revert "[Interpreter] i32.mul"

---

test/lit/help/wasm-metadce.test
test/lit/help/wasm-opt.test
test/lit/help/wasm2js.test
test/lit/passes/gto-removals.wast

Some of the expected output lines had drifted from what the auto-update
script generates. Fix them so the changes don't inadvertently make their
way into some unrelated PR.

[NFC] Update lit test output

---

test/lit/passes/gufa-cast-all.wast

[NFC] Update test from old EH to new EH

---

src/ir/possible-contents.h

As proven in
https://github.com/WebAssembly/binaryen/pull/7331#discussion_r1979927844

[NFC] Document that PossibleContents is not a distributive lattice

---

src/wasm/wasm-binary.cpp

[Parsing] Emit better errors when binary parser encounters a bad code

---

test/lit/passes/string-lowering.wast

We tested isolated surrogates, but we did not test with a valid
surrogate pair.

Test StringLowering with a surrogate pair

---

scripts/test/binaryenjs.py
scripts/test/support.py

Also, move `js_test_wrap` into binaryenjs.py which is its only callsite.

[test] Extract function in scripts/test/binaryenjs.py. NFC

---

scripts/test/binaryenjs.py

Previously each test would take binaryen.js can modify a copy of it.  Now they import it, as is (hopefully) more common in practice.

Use ES6 import to run JS tests. NFC

---

src/parser/contexts.h
src/wasm-ir-builder.h
src/wasm/wasm-ir-builder.cpp
test/lit/wat-annotations.wast

With this, support for the feature should be complete (at least aside from
bugs like source maps not working).

[Branch Hinting] Support branch hints on If and BrOn

---

src/wasm-binary.h
src/wasm/wasm-binary.cpp

Similar to #7592 but for reading.

[NFC] Refactor a generic function for binary reading of a code annotations section

---

src/tools/wasm-opt.cpp
test/lit/help/wasm-opt.test

[NFC] Improve wasm-opt help text

---

src/tools/fuzzing/heap-types.cpp

The heap type fuzzer provides a utility for transforming a type
definition graph to ensure that all the defined types are inhabitable.
This requires finding and breaking cycles of non-nullable references. We
use a simple DFS to find the cycles, but this DFS previously assumed
that each type would be visited only once at a time because it would
always make the first backedge found nullable.
A follow-on PR will update this DFS to handle descriptor types, which
are like non-nullable references that cannot be made nullable. When the
DFS finds a backedge correspnding to a descriptor, it will not be able
to make that edge nullable. Instead, it will have to continue searching
for the next backedge. To make that follow-on PR simpler, refactor the
data structures used in the DFS to make it easier …

[NFC] Generalize DFS machinery in makeInhabitable

---

src/ir/module-splitting.cpp

While reading I thought that
```cpp
assert(table == tableManager.activeTable->name);
```
in that `forEachElement` loop would be helpful, but adding it made clang-format intendentation change.. So the change was only the one assertion line. "Hide whitespace" will make it clear. This also removes a unused header.

[wasm-split] Add an assert (NFC)

---

src/wasm/wasm-ir-builder.cpp

Move the code skipped over with the goto into a separate function. The
goto used to break out of multiple loops is now a return from that
function.

[NFC] Remove a goto

---

src/wasm-interpreter.h
test/spec/cont.wast

Upstreaming: https://github.com/WebAssembly/stack-switching/pull/124

[Stack Switching] Handle resuming a null
