.gitignore
They get generated when using cmake -G Ninja.
=> .gitignore ninja files

Contributing.md, LICENSE, README.md
=> License and contributing

src/command-line.h, src/s2wasm-main.cpp, src/s2wasm.h, src/wasm.h
Use some C++ in a few places. I'll propagate similar changes to the rest of the codebase later. I also need to turn off colors when outputting to a file (isatty on stdout doesn't do that with -o) but I'll do it in a separate PR because it'll touch more files.
=> s2wasm: add outfile

CMakeLists.txt, src/asm2wasm.h, src/binaryen-shell.cpp, src/command-line.h, src/compiler-support.h, src/emscripten-optimizer/simple_ast.h, src/s2wasm.h, src/wasm-interpreter.h, src/wasm.h, src/wasm2asm.h
My previous patch addressed all LLVM warnings, this one addresses all the GCC ones as well (mostly signed / unsigned mix).
The patch also turns on -Wall -Werror.
=> Fix warnings found by GCC

src/bits.h
As discussed here:
https://github.com/WebAssembly/binaryen/pull/34#discussion_r48379297
It's useful to have portable bit functions instead of relying on compiler builtins which aren't always portable.
=> Portable bit functions

test/s2wasm_known_gcc_test_failures.txt
These tests now pass. New ones are failing unexpectedly, though. Investigate separately.
=> Update expected s2wasm failures

test/s2wasm_known_gcc_test_failures.txt
Some new unexpected symbols, a lot fewer (Alon added a workaround), finds a new bug with negative relocations.
=> Update expected GCC test failures

src/s2wasm-main.cpp, src/support/colors.cpp, src/support/colors.h
This will allow other tools to consume the output.
Note that I didn't make colors_disabled atomic because it doesn't need to be at the moment. We may want to do so later, but atomic_bool isn't guaranteed to be lock free (realistically it is) whereas atomic_flag is but doesn't support load, so the choices are kind of sad.
=> Disable colors when outputting to a file

build.sh
`build.sh` failed to build `s2wasm` due to linker errors, this PR fixes that.
=> Fix build.sh script.

src/wasm.h, test/dot_s/global.wast, test/dot_s/legalize.wast, test/dot_s/offset.wast, test/dot_s/store-results.wast, test/dot_s/symbolic-offset.wast, test/dot_s/userstack.wast, test/dot_s/vtable.wast
These should probably be commutable so humans don't have to remember which order to read/write things in, but there's pushback and this really doesn't matter so fix it here, bikeshed on github.
This will require an associated fix in sexpr-wasm's GCC torture test failure list.
Ref: https://github.com/WebAssembly/sexpr-wasm-prototype/issues/17
Ref: https://github.com/WebAssembly/spec/pull/205
=> s2wasm: load/store swap offset/align params

test/dot_s/function-data-sections.s, test/dot_s/visibilities.s
This adds tests for the assembly constructs produced when clang is invoked with
-ffunction-sections, -fdata-sections, -fvisibility=hidden,
-fvisibility=protected, and -fvisibility=internal.
Visibilities only matter for dynamic library linking, so s2wasm can just ignore them for now.
=> Add tests for more assembler constructs that LLVM may use soon.

src/s2wasm-main.cpp
Previously the file was created but was empty when s2wasm failed. This caused sexpr-wasm to be sad because it tried to use an empty file.
=> s2wasm: only create output file when successful

.travis.yml, check.py
Initialize the git submodules to the index (I'm not sure what they're initialized to right now).
Move exports to before_script, and print out compiler version.
Invoke check directly (the shebang and x permissions should take care of it).
Remove the sleep on warnings, it slows down Travis.
=> A few Travis change

.travis.yml, CMakeLists.txt, check.py, src/asm2wasm.h, src/emscripten-optimizer/optimizer-shared.cpp, src/emscripten-optimizer/optimizer.h, src/emscripten-optimizer/parser.h, src/emscripten-optimizer/simple_ast.h, src/s2wasm.h, src/support/safe_integer.cpp, src/support/safe_integer.h, src/wasm.h, src/wasm2asm.h, test/emcc_hello_world.2asm.js, test/emcc_hello_world.fromasm, test/emcc_hello_world.wast, test/llvm_autogenerated/global.wast, test/passes/O.txt, ubsan.blacklist
This triggers 5 independent build / test runs:
- clang, no sanitizer;
- clang, UB sanitizer;
- clang, address sanitizer (disabled for now);
- clang, thread sanitizer (disabled for now);
- GCC.
Enabling UBSan led to these changes:
- Fix a bunch of undefined behavior throughout the code base.
- Fix some tests that relied on that undefined behavior.
- Make some of the tests easier to debug by printing their command line.
- Add ubsan blacklist to work around libstdc++ bug.
- Example testcase also needs sanitizer because libsupport.a uses it.
=> Add Travis builds with sanitizers

src/s2wasm.h, test/dot_s/asm_const.s, test/dot_s/basics.s, test/dot_s/exit.s, test/dot_s/memops.s, test/llvm_autogenerated/call.s, test/llvm_autogenerated/cfg-stackify.s, test/llvm_autogenerated/f32.s, test/llvm_autogenerated/f64.s, test/llvm_autogenerated/frem.s, test/llvm_autogenerated/global.s, test/llvm_autogenerated/legalize.s, test/llvm_autogenerated/offset-folding.s, test/llvm_autogenerated/signext-zeroext.s, test/llvm_autogenerated/store-results.s, test/llvm_autogenerated/switch.s, test/llvm_autogenerated/unreachable.s, test/llvm_autogenerated/unused-argument.s, test/llvm_autogenerated/userstack.s, test/llvm_autogenerated/userstack.wast, test/llvm_autogenerated/varargs.s
This does not update tests through the official mechanism, because the test updates need to be made in lock-step with an LLVM change, http://reviews.llvm.org/D16091 . Please advise me on the appropriate procedure for performing such changes.
Changes include:
- the @FUNCTION symbol kind
- .skip instead of .zero
- the allocarray_inbounds test
=> Update tests for upstream changes.

check.py, src/wasm-binary.h
`wasm-as` can now emit *something* for the wasts in `/test/`, without crashing.
* This is still not including the spec test suite.
* This output may be totally wrong, it isn't tested yet.
* I had to disable one test already, due to something missing in the binary format (noted [here](https://github.com/WebAssembly/design/issues/497#issuecomment-171036017)).
=> wasm-as testing

.travis.yml
See the flake8 docs: https://pypi.python.org/pypi/flake8
And pep8: http://pep8.readthedocs.org/en/latest/
Exclusions are specified in setup.cfg, currently we only ignore the 4-space convention and use 2-space.
=> Travis: check style of update.py

CMakeLists.txt, src/binaryen-shell.cpp
-Wextra adds checks for potential clobbers which triggered in binaryen-shell.cpp:
might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
The fix moves the setjmp/longjmp using code into another function, and passes in potentially-clobbered values from the parent frame so they can't be clobbered. We could also mark them as volatile but that's a big hammer.
=> Avoid potential setjmp clobber

test/llvm_autogenerated/llvm-to-s.py
The LLVM test its generated from has external global variables, which
isn't supported in s2wasm.
=> Disable importing of the offset-folding test.

test/llvm_autogenerated/global.s, test/llvm_autogenerated/global.wast, test/llvm_autogenerated/mem-intrinsics.s, test/llvm_autogenerated/mem-intrinsics.wast, test/llvm_autogenerated/offset.s, test/llvm_autogenerated/store-results.s
Changes:
- Call memset/memcpy/memmove with the correct signature
- Optimize memset/memcpy/memmove calls by using their return values
- Change .align to .p2align
=> Update llvm_autogenerated tests to LLVM r258792.

src/s2wasm.h, test/dot_s/macClangMetaData.s, test/dot_s/macClangMetaData.wast
Clang likes to add some meta data (in llvm::MCStreamer::EmitVersionMin):
.text
.macosx_version_min 10, 10
.file	"test.ll"
.globl	main
.type	main,@function
This patch lets the parser ignore .macosx_version_min and others without crashing.
=> Ignore meta data emitted by clang on Mac OS X

src/support/colors.cpp
Apple OSes define `__APPLE__` instead of the lower case `__apple__`.
=> Fix colors on OSX.

CMakeLists.txt, src/pass.h, src/passes/Metrics.cpp, src/wasm.h
This prints metrics about the state of an AST at a certain point in the optimization pipeline. You can specify `--metrics` multiple times to see how a set of optimization passes modify the AST, e.g. the `./bin/binaryen-shell --metrics -O --metrics test/passes/O.wast` command prints:
```
Counts
call           : 150     
call_import    : 105     
call_indirect  : 9       
block          : 779     
if             : 702     
loop           : 103     
nop            : 17      
switch         : 6       
break          : 413     
get_local      : 4125    
set_local      : 1735    
load           : 606     
store          : 589     
const          : 2858    
unary          : 13      
binary         : 2762    
Counts
call           : 150     
call_import    : 105     
call_indirect  : 9 …
```
=> Adds a --metrics command line argument.

CMakeLists.txt
Use -DCMAKE_BUILD_TYPE=Debug to use the debug build (by default you get Release). I was getting tired of manually changing the cmake file.
=> cmake: add debug option

src/binaryen-shell.cpp, src/wasm-interpreter.h, src/wasm.h, test/s2wasm_known_binaryen_shell_test_failures.txt
When running the shell with --entry it was assumed that the signature had zero parameters. This isn't true for main, so look at the function's parameter list and construct a zero-initialized arguments vector of the right types. This fixes a few failures, some of which were hiding other failures.
=> Shell: fix --entry parameter numbers

src/asm2wasm.h, src/binaryen-shell.cpp, src/wasm.h, src/wasm2asm.h
This tends to avoid silly mistakes, which I'm worried about after adding an explicit ctor with the enum WasmType parameter. See 'C++ Coding Standards: 101 Rules, Guidelines, and Best Practices' rule #40 'avoid providing implicit conversion'.
=> Make Literal's ctors explicit

src/asm2wasm.h, src/binaryen-shell.cpp, src/parsing.h, src/s2wasm.h, src/wasm-binary.h, src/wasm-interpreter.h, src/wasm.h, src/wasm2asm.h
Followup to #151.
This began as just using `bit_cast` in the `Literal.reinterpret` methods. But this made some tests break. Investigating, I ended up with the following patch, which also refactors out float and double payload methods.
**This uses only the payload+signbit to compare floats and doubles when they are nans.** It fixes the test failures. But is this correct? What are the proper semantics for comparing floats for equality when they are nans?
Taking into account only the payload seems reasonable given that we now only print the payload for nans. If that's not true, how do those two make sense?
cc @jfbastien @sunfishcode
=> Float refactoring and nan comparison change

src/wasm-interpreter.h
Fixes the build.
Still has test failures on Travis and for me locally though; not sure if they're related.
=> Fix ambiguous constructor call with explicit cast

src/support/bits.h
=> De-inline signed wrapper templates for bit manipulation functions

src/wasm-interpreter.h
Instead of defaulting to signed types and casting as necessary, use
unsigned types. Explicitly make signed copies of them and us them where
appropriate, avoiding lots of casting and improving readability. Avoids
undefined behavior of signed overflow.
=> Use unsigned types to evaluate i32 and i64 binary operators

src/s2wasm-main.cpp, src/s2wasm.h
Currently s2wasm pre-allocates space for the special __stack_pointer
variable but not for the actual stack, and __stack_pointer is null. On
real systems the stack is allocated by the dynamic linker, thread
runtime, or other toolchain/system-provided startup code. Since we don't
have any of that in wasm yet, just allocate the stack in the linker for now.
=> Allocate space for user stack at link time

src/wasm-s-parser.h
Fixes the case where the import doesn't have a name. See corresponding test case: https://github.com/WebAssembly/spec/pull/229
Not sure if there is a nicer way to parse this.
=> Fix import parsing.

src/asm2wasm.h, src/s2wasm.h, src/wasm-interpreter.h, src/wasm-s-parser.h, src/wasm.h, src/wasm2asm.h, test/llvm_autogenerated/legalize.wast, test/llvm_autogenerated/select.wast, test/s2wasm_known_binaryen_shell_test_failures.txt, test/unit.2asm.js, test/unit.fromasm, test/unit.wast, test/unit.wast.fromBinary
The ordering changed in: https://github.com/WebAssembly/spec/pull/221
Which changed the spec tests, breaking sexpr-wasm because it pulls in the spec tests. This was then fixed:
https://github.com/WebAssembly/sexpr-wasm-prototype/commit/23dc368148fc7827a603e3853f5a40287eb9effe
Which in turn breaks when binaryen feeds sexpr-wasm .wast files with the old select operand ordering.
Note that this PR has new failures when running the torture tests in binaryen-shell: the order of evaluation is correct in binaryen-shell but isn't emitted properly by LLVM in the .s files. This will require another patch to fix LLVM.
=> Fix select

.travis.yml
This should reduce most of the noise in the ASan build
=> Suppress leak detection in ASan builder

.travis.yml
We've fixed the ASan errors, so this bot can stay green. Now there's
flake on the TSan bot :(
=> Allow failures on TSan Travis build, require ASan to pass

src/s2wasm.h, test/dot_s/memops.wast
=> s2wasm: don't export functions unless they are marked with .globl.

check.py, src/js/wasm.js-post.js
This allows people do things like say at compile time "try native wasm, and if that fails, use the interpreter" or "try native wasm, and if that fails, use asm.js".
=> Support a comma-separated list of methods in wasm/js integration

README.md
=> binaryen-shell does not have --print-before/after, only --print

README.md
This is a link to a tutorial on how to compile Binaryen under Windows 10 x64 with CMake & Visual Studio 2015.
=> added link to the tutorial on building under Win32

README.md, check.py, src/js/wasm.js-post.js, src/wasm-binary.h
Now `interpret-*` means to interpret either s-exprs, or asm2wasm, or binary.
=> Better method names

src/passes/Print.cpp, src/s2wasm-main.cpp, src/s2wasm.h, src/wasm-s-parser.h, src/wasm.h
Make type of EqZ unary operators always i32. This makes them symmetric to binary relational operators. Also support eqz in the s2wasm parser.
Also allow specifying --initial-memory and/or --max-memory flags on the command line to control the linear memory size. If they are not given, fall back to the calculated size.
=> Update EqZ operators and support specifying memory size on the command line

src/wasm-binary.h
Speeds up the assembler 5X.
```
time ./bin/wasm-as AngryBots/release_binaryen.wast
```
before:
```
real  0m26.216s
user  0m25.636s
sys   0m0.560s
```
after:
```
real  0m5.282s
user  0m4.752s
sys   0m0.520s
```
=> Optimize function => index mapping.

src/support/safe_integer.cpp
#282 removed the assert, but the code didn't handle negative -> unsigned conversion properly, and doesn't behave well with -0.0. I'm not super comfortable with 64-bit int min / max to double conversions either, but that'll be for another patch.
=> Tighten safe integer

src/s2wasm.h, test/llvm_autogenerated/memory-addr32.wast, test/llvm_autogenerated/memory-addr64.wast
s2wasm used to mistranslate grow_memory operation in .s into memory_size
in .wast, and this CL fixes it.
=> Fix grow_memory translation on s2wasm

src/support/file.cpp
I build binaryen in 32 bit and it allowed a file with size > 4 GB. The
problem was, that you cast to size_t and then check if it fits into
size_t.
=> Repair broken file-size check

src/asm2wasm-main.cpp, src/binaryen-shell.cpp, src/s2wasm-main.cpp, src/support/file.cpp, src/support/file.h, src/wasm-as.cpp, src/wasm-dis.cpp, src/wasm2asm-main.cpp
This might fix binaryen on windows, [which seems broken on emscripten's windows bot](http://clb.demon.fi:8112/builders/win-incoming/builds/1221/steps/Tests-default/logs/stdio)
=> Set the binary bit on files we need to open in binary mode

src/s2wasm.h, test/dot_s/alias.wast, test/dot_s/alternate-lcomm.wast, test/dot_s/data-offset-folding.wast, test/dot_s/dso_handle.s, test/dot_s/dso_handle.wast, test/dot_s/exit.wast, test/dot_s/function-data-sections.wast, test/dot_s/initializers.wast, test/dot_s/lcomm-in-text-segment.wast, test/dot_s/minimal.wast, test/dot_s/relocation.wast, test/dot_s/start_main0.wast, test/dot_s/start_main2.wast, test/dot_s/symbolic-offset.wast, test/dot_s/visibilities.wast, test/llvm_autogenerated/global.wast, test/llvm_autogenerated/offset-folding.wast, test/llvm_autogenerated/offset.wast, test/llvm_autogenerated/store-results.wast
Unlike asm.js modules, wasm modules cannot have imported/extern
objects. So allocate __dso_handle (which is traditionally defined in
a crtbegin or similar toolchain file linked with the user code) in s2wasm.
=> Allocate __dso_handle in s2wasm

src/s2wasm.h, test/dot_s/alias.s, test/dot_s/alias.wast
This fixes 2 bugs in s2wasm:
* Handle address-taken aliases (i.e. when they appear in relocations), by lookup up and subsituting the address of the aliasee.
* Skip whitespace at the top of the scan() loop instead of requiring it to match. When there are multiple alias declarations in a row, th match("FUNCTOIN") at the end of an alias delcaration consumes the whitespace at the beginning of the next line, causing it to fail to match the tab character specified in the match pattern at the top of the loop
=> Fix s2wasm handling of aliased functions

src/s2wasm.h, test/dot_s/initializers.wast
Turns out trailing commas aren't valid JSON
=> Fix output of initializer list metadata

src/asm2wasm.h, src/passes/NameManager.cpp, src/passes/Print.cpp, src/passes/ReorderLocals.cpp, src/s2wasm.h, src/wasm-binary.h, src/wasm-builder.h, src/wasm-interpreter.h, src/wasm-s-parser.h, src/wasm.h, src/wasm2asm.h
Just a minor refactoring. Seems nice to do this before more major work on #336.
All this does is rename function->locals to vars. Before this, we have params and locals, and we also use the term "locals" to refer to both. Which makes sense, since the params are also locals, and can be used and written to, etc. After this change, we have params and vars, and together they can be called "locals" without risk of confusion.
=> Rename function->locals to function->vars

README.md
More detail about what wasm.js actually is. Also added bullet for binaryen.js.
When I read the Binaryen repo README.md the first time, it was difficult to understand what wasm.js does and is used for. This hopefully clarifies the description.
#290
=> Clarified wasm.js & binaryen.js use cases

CMakeLists.txt, check.py, src/emscripten-optimizer/istring.h, src/mixed_arena.h, src/passes/MergeBlocks.cpp, src/passes/OptimizeInstructions.cpp, src/passes/PostEmscripten.cpp, src/passes/RemoveUnusedBrs.cpp, src/passes/RemoveUnusedNames.cpp, src/passes/ReorderLocals.cpp, src/passes/SimplifyLocals.cpp, src/passes/Vacuum.cpp, src/s2wasm.h, src/support/threads.cpp, src/support/threads.h, src/wasm-traversal.h
This adds function parallelism as an option to AST walking. Details are in `wasm-traversal.h`, but basically, this could apply to almost every pass, since the AST has by design no global data structures, so we can optimize using all cores.
I wanted to get parallelism working at this early stage because it will make sure we don't unknowingly add anything that prevents this later, and also I've already heard requests that new toolchain components are fast on big codebases, and this is a simple way to get a massive speedup.
I'm pretty sure this code could be even faster (there is no batching, no work-stealing, no optimization of atomics, nothing clever ;)), but benchmarks show good results already.
Also added are a bunch of asserts on some risky things that should not run in parallel, like …
=> Function parallelism

src/pass.cpp
Example output:
````
[PassRunner] running passes...
[PassRunner]   running pass: remove-unused-brs...     0.0568142 seconds.
[PassRunner]   running pass: remove-unused-names...   0.0639781 seconds.
[PassRunner]   running pass: merge-blocks...          0.0497385 seconds.
[PassRunner]   running pass: optimize-instructions... 0.0520239 seconds.
[PassRunner]   running pass: simplify-locals...       1.04345 seconds.
[PassRunner]   running pass: reorder-locals...        0.109968 seconds.
[PassRunner]   running pass: vacuum...                0.0498161 seconds.
[PassRunner] passes took 1.42691 seconds.
````
=> Nicer pass printing

src/asm2wasm-main.cpp, src/asm2wasm.h, src/binaryen-shell.cpp, src/js/binaryen.idl, src/s2wasm-main.cpp, src/s2wasm.h, src/wasm-as.cpp, src/wasm-binary.h, src/wasm-builder.h, src/wasm-dis.cpp, src/wasm-js.cpp, src/wasm-s-parser.h, src/wasm.h, src/wasm2asm-main.cpp, test/example/find_div0s.cpp
The distinction was not really that useful, and passes do need to allocate, so we would need to pass around AllocatingModules all around anyhow. All modules being as allocating modules in all the builders, as well.
=> Unify AllocatingModule into Module

src/passes/SimplifyLocals.cpp
This makes it 5% faster. Depends on #354 and #355.
=> Use a vector for get_local counts in SimplifyLocals

src/ast_utils.h, src/pass.h, src/passes/LowerIfElse.cpp, src/passes/MergeBlocks.cpp, src/passes/Metrics.cpp, src/passes/OptimizeInstructions.cpp, src/passes/PostEmscripten.cpp, src/passes/RemoveImports.cpp, src/passes/RemoveUnusedBrs.cpp, src/passes/RemoveUnusedNames.cpp, src/passes/ReorderLocals.cpp, src/passes/SimplifyLocals.cpp, src/passes/Vacuum.cpp, src/s2wasm.h, src/wasm-traversal.h, src/wasm-validator.h, src/wasm2asm.h, test/example/find_div0s.cpp
Motivated by @dschuff 's comment that having visitBlock etc and also the generic visitExpression is confusing (what's the order, what happens if the node is replaced, etc.). This pull templates on the visitor, and there is the usual visitor that most want (visitBlock, etc.), but also a visitor with a unified single visitExpression for all expressions.
Depends on #355.
=> Unified traversal option

src/wasm-binary.h
For https://github.com/WebAssembly/design/pull/640
=> Extensible type forms

src/s2wasm.h, test/dot_s/initializers.s, test/dot_s/initializers.wast
Allows more than one function in the the .init_array section to be parsed. Found during building of wast.js.
See also #315
=> Parses more than one entry in the .init_array section.

src/js/binaryen.idl
Continuation of #345 (see https://github.com/WebAssembly/binaryen/commit/2887883029de293458344a5d564039074d93246e#diff-499c4e70c8aadb9837261ebcc4725f78R262)
Currently building of binaryen.js fails with
"src/../glue.cpp:102:14: error: no matching constructor for initialization of
'wasm::SExpressionWasmBuilder'"
=> Removes wasm-s-parser debug logging from binaryen.idl.

src/s2wasm-main.cpp, src/s2wasm.h, src/wasm-linker.cpp, src/wasm-linker.h, test/dot_s/basics.s
Also defer address assignment until layout time in preparation for
separating linker objects out from Linker
=> Simplify statics, segments, and relocations

src/s2wasm-main.cpp, src/s2wasm.h, src/wasm-linker.cpp, src/wasm-linker.h
Create the `LinkerObject` class, which is associated with a wasm `Module` and represents the module plus the information needed to relocate and lay it out. Each Linker owns a "main executable" `LinkerObject`, and S2WasmBuilder requires a `LinkerObject` instead of just a `Module` because LLVM asm files require relocation/linking before they represent a full wasm module.
No merging support yet, but the real functionality for #370 is coming soon.
=> Separate LinkerObject from Linker

src/ast_utils.h, src/passes/RemoveUnusedBrs.cpp, test/emcc_O2_hello_world.fromasm, test/emcc_O2_hello_world.fromasm.imprecise, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.imprecise, test/memorygrowth.fromasm, test/memorygrowth.fromasm.imprecise, test/passes/remove-unused-brs.txt, test/passes/remove-unused-brs.wast
Turning an if-else into a select removes control flow and allows other optimizations to work better.
This selectifies 11% of ifs, after which other opts can remove 0.2% of the total nodes.
=> Selectify if-elses with no side effects

src/asm2wasm.h, src/asmjs/CMakeLists.txt, src/asmjs/shared-constants.cpp, src/asmjs/shared-constants.h, src/parsing.h, src/s2wasm-main.cpp, src/s2wasm.h, src/shell-interface.h, src/wasm-binary.h, src/wasm-linker.cpp, src/wasm-linker.h, src/wasm-s-parser.h, src/wasm2asm.h
Instead of doing all of the S2Wasm work in the constructor, split
construction, scanning (to determine implemented functions) and building
of the wasm module.
This allows the linker to get the symbol information (e.g. implemented
functions) without having to build an entire module (which will be
useful for archives) and to allow the linker to link a new object into
the existing one by building the wasm module in place on the existing
module.
=> Split construction, scanning, and building phases of S2WasmBuilder

.travis.yml, src/asm2wasm.h, src/asm_v_wasm.h, src/asmjs/asm_v_wasm.cpp, src/binaryen-shell.cpp, src/emscripten-optimizer/istring.h, src/emscripten-optimizer/parser.cpp, src/emscripten-optimizer/simple_ast.cpp, src/emscripten-optimizer/simple_ast.h, src/passes/Print.cpp, src/passes/RemoveImports.cpp, src/s2wasm.h, src/shell-interface.h, src/wasm-binary.h, src/wasm-builder.h, src/wasm-linker.cpp, src/wasm-linker.h, src/wasm-s-parser.h, src/wasm-traversal.h, src/wasm-validator.h, src/wasm.h, src/wasm2asm.h
Let's see where things stand now.
=> Enable leak checks

src/js/wasm.js-post.js
By doing it later, we share more code, and also can fall back on more errors (like a wasm compilation error), and can then use a fallback method like interpreting or asm.js.
=> Refactor js/wasm glue to defer the wasm/wasm-polyfill/asmjs-fallback point

src/asm2wasm.h, test/unit.asm.js, test/unit.fromasm, test/unit.fromasm.imprecise
In asm.js we have an implicit cast of f64 to f32 when writing to memory in the bitcast pattern. In wasm we need to demote it explicitly.
=> Fix asm2wasm f64->f32->i32 bitcast

src/wasm-binary.h, test/kitchen_sink.wast.fromBinary
We flipped i32 to i64 on reinterprets, turns out. Miraculously, code still worked somehow...
=> Fix size detection on reinterpret operations in binary format

src/wasm-binary.h
As found by #404, the insignificant LEB128 bits were silently dropped when dealing with signed LEB values which tripped UBSAN in hello_world.
This fixes #409.
=> Check LEB128 encoding fits in destination integer

src/support/file.cpp
Changed type of flags (line 26) in read_file() from auto to std::ios_base::openmode to fix Visual Studio 2015 error.
Visual Studio 2015 Build Error support/file.cpp #414
=> Changed type of flags to fix Visual Studio 2015 Issue #414

src/wasm.h
Can't call memcpy with size of 0 and nullptr init.
Another fix for #404.
=> Fix memcpy UB

.travis.yml
I fixed a few of the existing ubsan failures as part of #404, but would
like to prevent regressions. This patch allows some of the sanitizer
checks to continue execution (null, shift, signed-integer-overflow) and
makes all the other ones hard errors (preventing regressions).
Once the remaining errors are addressed we should commit #404 which
moves ubsan to -fno-sanitize-recover=all. This likely requires a good
checked-math library.
=> ubsan: only recover from some of the failures

.travis.yml, src/wasm-s-parser.h
As a continuation to #404, fix a dereference of a std::vector's zeroth element when the size of the vector is zero.
Symptom: stl_vector.h:866:9: runtime error: reference binding to null pointer of type 'char'
=> Fix null UB

.travis.yml, src/wasm.h
Getting close to finishing #404.
Also not the extra mask which just used to return the right result on x86. Those cases would have failed on A32.
=> Fix shift UB

.travis.yml, src/support/bits.cpp, src/wasm.h
This puts us back where #404 wanted to be: all UB that ubsan knows about now causes an abort. This ins't to say that it's all gone, merely that our tests don't trigger any more UB which ubsan knows how to find :-)
=> Fix signed integer overflow UB

auto_update_tests.py, src/asm2wasm.h, src/binaryen-c.cpp, src/binaryen-c.h, src/passes/Print.cpp, src/passes/Vacuum.cpp, src/s2wasm.h, src/wasm-binary.h, src/wasm-builder.h, src/wasm-interpreter.h, src/wasm-s-parser.h, src/wasm-validator.h, src/wasm.h, src/wasm2asm.h, test/example/c-api-kitchen-sink.c, test/example/c-api-kitchen-sink.txt
This makes them parallel the binary format better, and we no longer need the type to disambiguate some of them, which allows the C API to be simpler (no extra type param to Unary).
=> Harmonize the internal opcodes with the binary format

CMakeLists.txt, src/ast_utils.h, src/binaryen-c.cpp, src/binaryen-c.h, src/cfg/Relooper.cpp, src/cfg/Relooper.h, src/wasm-builder.h, test/example/c-api-kitchen-sink.c, test/example/c-api-kitchen-sink.txt, ubsan.blacklist
This turned out to be easier and nicer than I thought. Switching from JS output in text to wasm in AST was a nice change in itself. In addition, we don't need a bunch of relooper optimizations, since binaryen has AST control flow optimizations already, and we can just rely on those. So this is simpler and cleaner than the previous relooper.
Current limitations: no switches, and while basic tests pass, it should be tested a lot more.
=> Import emscripten's relooper, port it to the binaryen AST, and provide a C API

src/js/wasm.js-post.js
We need to prevent closure from renaming the Wasm.* methods. Bug was reported on emscripten mailing list.
=> Make wasm.js safe in closure compiler

src/passes/SimplifyLocals.cpp, test/passes/simplify-locals.txt, test/passes/simplify-locals.wast
We failed to note that a block that is switched to has merging control flow, so we must clear sinkables on it, and not optimize a block return value.
=> Fix switches in simplify-locals

auto_update_tests.py, check.py
It needs to be concatenated, not overwritten.
RPATH is probably still a better solution, as discussed here:
https://github.com/WebAssembly/binaryen/pull/435#discussion_r62245931
=> Fix LD_LIBRARY_PATH

src/wasm.h
As discussed in: https://github.com/WebAssembly/spec/pull/282#issuecomment-217280544
=> Fix NaN / 0

src/binaryen-c.cpp, src/binaryen-c.h, test/example/c-api-kitchen-sink.c, test/example/c-api-kitchen-sink.txt
Now the C API can write and read binaries. I suspect only writing is really going to be needed, at least for a while, but might as well add reading. Also nice for testing.
Depends on #439.
=> Add binary format methods to C API

CMakeLists.txt, auto_update_tests.py, check.py
Use the -rpath linker flag to locate libbinaryen-c.so instead of
injecting paths into the user's LD_LIBRARY_PATH.
Fixes #444
=> Use rpath instead of LD_LIBRARY_PATH for shared object use

scripts/fuzz_relooper.py, src/binaryen-c.cpp, src/binaryen-c.h, src/wasm.h, test/example/c-api-kitchen-sink.c, test/example/c-api-kitchen-sink.txt, test/example/relooper-fuzz.c, test/example/relooper-fuzz.txt
This adds a fuzzer for the relooper, and fixes a minor C API bug this found so far.
The relooper is a port of emscripten's which has been heavily fuzzed in the past, but it's still worth fuzzing this one since it's another test of the C API, it tests the new wasm-specific code in this port of the relooper, and also I plan to optimize the relooper and this will be useful for that.
=> Fuzz relooper

.gitignore, CMakeLists.txt, check.py
As suggested by @dschuff, since it contains the C++ API as well.
=> Rename binaryen-c library to binaryen

CMakeLists.txt, src/binaryen-c.cpp, src/wasm-binary.h, src/wasm-dis.cpp, src/wasm-s-parser.h
Update spec tests, and add support for the new binary-in-wast stuff that they include.
Also remove wasm2asm from the build. It's not tested already, I was hoping to get back to it at some point, or that someone else would, but it looks like it's no longer maintained, and it's a burden to keep it building with updates like these.
=> Spec test update

src/binaryen-c.h
We convert the structs anyhow, and this makes it easier to bind to other languages, no int that depends on the arch.
=> Use an int32_t for BinaryenLiteral in the C API

src/cfg/Relooper.cpp
Change NULL to nullptr. Quiet Visual C++ 2015 optimizer errors by using "!!".
=> Use nullptr instead of NULL. Quiet VS warnings.

src/binaryen-c.cpp
Replace NULL with nullptr. Quiet Visual Studio 2015 optimizer warnings by prepending "!!".
=> Replace NULL with nullptr. Quiet VS warnings.

src/cfg/Relooper.h
Fix Visual Studio 2015 compiler warning by using "!!".
=> Fix Visual Studio warning.

src/ast_utils.h
Fix Visual Studio 2015 C++ compiler warning about conversion from int to bool.
=> Fix Visual C++ warning

src/passes/ReorderFunctions.cpp
Fixes build failure with libstdc++ 4.8
=> Pass sort comparison function arguments by const-reference

src/support/bits.h
Fix Visual Studio 2015 C++ warning about negating unsigned value by adding typename U.
=> Fix Visual C++ unsigned warning

test/example/c-api-kitchen-sink.c
Visual C++ warned that double constants shouldn't be used as float args. Fix is to append an "f" to float constants.
=> Fix Visual C++ float constants

src/s2wasm.h, src/shell-interface.h, src/wasm-interpreter.h, src/wasm-linker.cpp, src/wasm-linker.h, src/wasm.h
We've been using size_t (and other things) for addresses, which is
generally wrong because it depends on the host, when it should in fact
depend on the target. This is a partial fix for #278 (i.e. it's the
right fix, I don't think it's applied quite everywhere yet).
=> Introduce a separate type for linear memory addresses

src/s2wasm.h
Fixes Visual Studio 2015 warning about returning a pointer as a bool.
=> Quiet Visual C++ ptr-to-bool warning

src/support/safe_integer.cpp
Fix Visual Studio 2015 warnings about casting from double to *int32_t.
=> Quiet Visual C++ cast warnings

src/passes/Print.cpp, src/wasm-js.cpp, src/wasm.h
Memory sizes are now specified in page-size units. Binaryen was using (uint32_t)-1 to indicate the lack of a maximum, but this evokes validation errors because scaling it up by the page size overflows. This patch changes it to use (uint32_t)-1 / kPageSize.
No tests yet because I don't understand how the tests work.
=> Fix the maximum size to be valid.

test/example/c-api-kitchen-sink.c
Visual Studio 2015 wants float constants to be terminated with an `f`.
=> Correct float constant

src/cfg/cfg-traversal.h, src/passes/CMakeLists.txt, src/passes/CoalesceLocals.cpp, src/passes/pass.cpp, src/tools/wasm-as.cpp, src/wasm-traversal.h, test/emcc_O2_hello_world.fromasm, test/emcc_O2_hello_world.fromasm.imprecise, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.imprecise, test/example/relooper-fuzz.txt, test/hello_world.fromasm, test/hello_world.fromasm.imprecise, test/memorygrowth.fromasm, test/memorygrowth.fromasm.imprecise, test/min.fromasm, test/min.fromasm.imprecise, test/passes/coalesce-locals.txt, test/passes/coalesce-locals.wast, test/two_sides.fromasm, test/two_sides.fromasm.imprecise, test/unit.fromasm, test/unit.fromasm.imprecise
This generates a CFG from the AST, finds live ranges, and does local coloring.
Currently it does simple greedy coloring, which obviously should be improved on. However it currently removes 2% of local definitions on BananaBread from asm2wasm and 1% from wasm-backend, so it's already useful. Further work can also focus on stuff like the distribution of locals (gzip would do better on 99 accesses of 0 and 1 of 1, as opposed to 50 of each, even though the total number of locals is the same, etc.).
This is the slowest optimization pass we have so far. I didn't do much tuning yet. Currently it uses sorted vectors for the sets of live locals, which is good for functions with many locals but short average lists. Suggestions are very welcome.
=> Coalesce locals

src/passes/Vacuum.cpp, src/passes/pass.cpp, test/emcc_O2_hello_world.fromasm, test/emcc_O2_hello_world.fromasm.imprecise, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.imprecise, test/memorygrowth.fromasm, test/memorygrowth.fromasm.imprecise, test/passes/vacuum.txt, test/passes/vacuum.wast, test/unit.fromasm, test/unit.fromasm.imprecise
Get rid of more dead code in vacuum, in particular the dead code left by coalesce-locals.
=> Vacuum improvements

src/passes/Metrics.cpp, test/passes/metrics.txt, test/passes/metrics.wast
Allows diffs on subsequent metrics calls for the total nodes, and also adds total vars (non-param-locals) to the metrics, as we have opts that can reduce them now.
=> Metrics improvements

check.py
Verbose exctraction makes the Travis build less readable. Also print the
URL before downloading it.
=> Quietly extract the waterfall tarball

src/passes/CoalesceLocals.cpp, src/support/learning.h, src/wasm-traversal.h, test/passes/coalesce-locals-learning.txt, test/passes/coalesce-locals-learning.wast
This tries multiple orders of greedy local coloring instead of just the natural order, and picks the best.
It uses a genetic learning class, but no learning for now, it just creates the first generation of random elements, and picks the best. Later we can tune to see if multiple generations with mixing etc is worthwhile.
This makes the local index selection stage linearly slower by the number of extra orders (currently I picked 10). This can be significant, however, in some cases finding the interference graph is most of the time anyhow, and that is unchanged. This can be slow, so it's not in the default opt passes (that still has normal coalescing). However, we can probably optimize this stage significantly, I didn't look at it yet.
Some numbers: with previous coalescing (just use 1 …
=> Smarter local coalescing

src/passes/CoalesceLocals.cpp, src/support/learning.h, test/passes/coalesce-locals-learning.txt
This turns on multi-generational learning using the genetic learner. It keeps running generations until it doesn't see an improvement.
It's hard to say if this generates better code quality than just doing more random orders, I see mixed results. However, it probably helps in some cases. And it provides a natural way to decide when to stop trying, which reduces run times. It may also matter more when the cost function is more complex (right now it is # of locals, and also a bonus for not reordering locals unnecessarily).
=> Activate true learning in local coalescing

src/wasm-binary.h, test/unit.wast, test/unit.wast.fromBinary
Fixes #522.
We had a function for this and a TODO, but it just wasn't TODONE yet...
=> Don't emit extra unnecessary blocks for loops in binary format

src/binaryen-c.cpp
Fixes UB issue. When a pointer is converted to void* it has to be converted back to the same type (not a subtype). This forces the pointers of subclasses of Expression to be Expression* before converting to void*.
=> Added implicit_cast to prevent direct conversion from subclasses to void*.

.gitignore, check.py
(... at least important part of it)
Also tries to cleanup example.dSYM files and hide libbinaryen.dylib.
=> Allows running check.py on the Mac OSX.

src/s2wasm.h, test/dot_s/return.s, test/dot_s/return.wast
This allows .s producers to omit return opcodes at the ends of functions.
=> Allow implicit function returns.

src/ast_utils.h, test/emcc_O2_hello_world.fromasm, test/emcc_O2_hello_world.fromasm.imprecise, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.imprecise, test/example/c-api-kitchen-sink.txt, test/memorygrowth.fromasm, test/memorygrowth.fromasm.imprecise, test/passes/simplify-locals.txt, test/passes/vacuum.txt
Previously it considered every branch to be an effect of the entire expression, but we can ignore internal control flow.
This makes entire ifs sinkable, etc., allowing more local operations to be removed.
=> Notice only branches out in EffectAnalyzer

src/wasm-linker.cpp, test/dot_s/basics.s, test/dot_s/basics.wast, test/dot_s/bcp-1.wast, test/dot_s/dyncall.wast
WebAssembly functions can return the last value in the function body implicitly, without an explicit `return` opcode.
=> Avoid a redundant return in dynCall functions.

src/passes/MergeBlocks.cpp, src/tools/binaryen-shell.cpp, src/wasm-s-parser.h, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.imprecise, test/min.fromasm, test/min.fromasm.imprecise, test/passes/merge-blocks.txt, test/passes/merge-blocks.wast, test/unit.asm.js, test/unit.fromasm, test/unit.fromasm.imprecise, test/unit.fromasm.imprecise.no-opts, test/unit.fromasm.no-opts
Moves blocks outside when possible, which allows more merging. Suggested at https://github.com/WebAssembly/design/pull/694#issuecomment-221263488
Also improves an s-expr error, which I noticed when writing tests.
=> Merge blocks improvements

src/ast_utils.h, src/passes/CMakeLists.txt, src/passes/RemoveUnusedFunctions.cpp, test/passes/remove-unused-functions.txt, test/passes/remove-unused-functions.wast
This pass removes functions that are not reachable from a root set of functions. The root set includes the start function, all exported functions and all functions that can be called indirectly.
(We could make the pass more precise by using a type-based indirect call graph analysis. In large programs, each type is going to be called so it would probably not help much.)
=> Add remove unused functions pass.

src/compiler-support.h, src/s2wasm.h, test/dot_s/debug.s, test/dot_s/debug.wast
(Portion of #347)
The patch allows parsing of the debug information, but currently it ignores/skips it. This will allows parse files with -asm-verbose=true too.
=> Allows parsing debug information in the .S files

src/cfg/cfg-traversal.h, src/pass.h, src/passes/CoalesceLocals.cpp, src/passes/DuplicateFunctionElimination.cpp, src/passes/RemoveUnusedBrs.cpp, src/passes/SimplifyLocals.cpp, src/wasm-linker.cpp, src/wasm-traversal.h, src/wasm-validator.h, test/example/find_div0s.cpp
For a more regular API that is clearer where stuff should be overridden.
=> Refactor walk logic into walk* and doWalk* methods

src/asm2wasm.h, src/wasm-interpreter.h, test/unit.asm.js, test/unit.fromasm, test/unit.fromasm.imprecise, test/unit.fromasm.imprecise.no-opts, test/unit.fromasm.no-opts
From running the full emscripten test suite.
* handle duplicate exports (ok in asm, not in wasm)
* handle stack frame skipping (longjmp, exceptions) in manual stack frame management
=> asm2wasm regression fixes

check.py
Without this, the script won't work on distros that use python3 by default.
=> Specify version of python interpreter

.travis.yml, check.py
LLVM have disabled clang's apt server (#553) which broke our clang builds. This is one option for an alternative, to use clang from the waterfall.
The waterfall clang doesn't have what we need for the sanitizers, though, so this unbreaks the clang build but not the 3 sanitizer builds. @dschuff, @jfbastien, would it be possible to add the sanitizer library to the waterfall (looks like some library called `libclang_rt.a`)? If not, then this route is not going to make sense.
=> Use clang from the waterfall

src/asm2wasm.h, src/pass.h, src/passes/pass.cpp, src/support/threads.cpp, src/support/threads.h, src/tools/asm2wasm.cpp, src/wasm-module-building.h, src/wasm-traversal.h, test/memorygrowth.fromasm, test/memorygrowth.fromasm.imprecise
Before this PR, asm2wasm builds asm.js into wasm, finishes the whole module, then runs the optimizer. The optimizer is multithreaded, but we use just a single core during the asm2wasm step, so this is inefficient.
This PR adds an option to optimize while still building: as soon as a function is ready, it goes in a list and workers can grab it and optimize it. Only function passes are relevant for this, of course (not LTO type things) but they still account for almost all the work.
This makes asm2wasm noticeably faster, e.g. 15% on one benchmark I tested.
We could use this in more places if it makes sense. For example, if s2wasm would optimize, we could get the same benefits there.
=> Option to optimize while building modules

src/s2wasm.h, test/dot_s/indirect-import.wast
Pass ownership into the wasm module.
=> Fix leak of FunctionType from parseFuncType when not already in the module

src/pass.h, src/passes/CoalesceLocals.cpp, src/passes/DeadCodeElimination.cpp, src/passes/DropReturnValues.cpp, src/passes/DuplicateFunctionElimination.cpp, src/passes/MergeBlocks.cpp, src/passes/OptimizeInstructions.cpp, src/passes/PostEmscripten.cpp, src/passes/Print.cpp, src/passes/RemoveUnusedBrs.cpp, src/passes/RemoveUnusedNames.cpp, src/passes/ReorderLocals.cpp, src/passes/SimplifyLocals.cpp, src/passes/Vacuum.cpp, src/passes/pass.cpp, src/wasm-printing.h, src/wasm-traversal.h
By doing it at the pass/pass runner level, we can be smarter about things. Previously we ran each pass, in parallel, and waited for it to finish entirely before moving to the next. With this PR we run all the passes we can on a single function. This avoids the join after each pass, and also is good for locality.
This speeds up optimization by a few %. Also feels like a cleaner API, to let traversals worry just about traversing, and the pass runner deals with running multiple passes in a parallel and efficient manner.
=> Move function parallelism to pass and pass runner

src/wasm-linker.cpp, src/wasm-linker.h, test/dot_s/indirect-import.c, test/dot_s/indirect-import.s, test/dot_s/indirect-import.wast
Previously every address-take of an import would cause a new thunk to be
generated. Now check in getImportThunk if the thunk exists already and
just return it if so.
=> Do not generate duplicate import thunks at link time.

src/asm2wasm.h, src/ast_utils.h, src/binaryen-c.cpp, src/binaryen-c.h, src/passes/Print.cpp, src/wasm-binary.h, src/wasm-builder.h, src/wasm-interpreter.h, src/wasm-s-parser.h, src/wasm-validator.h, src/wasm.h, test/example/c-api-kitchen-sink.c
This makes it like call and call_import, whose target info is also a name, instead of a raw pointer.
Avoiding a raw pointer makes parallel optimization passes simpler: to access global module data, it must be explicitly retrieved from the module object. Operating on a function by itself is always thread-safe.
=> Make call_indirect type a name

src/wasm.h
If one is none and the other is concrete, still none is the final result.
This isn't noticeable in tests, but is noticeable internally so it's worth fixing.
=> Fix if type

src/passes/DeadCodeElimination.cpp, src/support/threads.cpp, src/tools/binaryen-shell.cpp, src/wasm-binary.h
Fixes compiler warnings/errors on variables we only use in asserts.
=> Use WASM_UNUSED in some places

check.py, src/tools/s2wasm.cpp, src/tools/wasm-as.cpp, src/wasm-binary.h, src/wasm-validator.h, test/validator/invalid_export.wast, test/validator/invalid_import.wast, test/validator/invalid_return.wast
In the web embedding, modules are not allowed to import or export
functions which have i64 params or return values. Add a mode to the
validator to check for this, and add flags to s2wasm and wasm-as to
enable or disable this check. Also add tests.
=> Add mode to wasm validator to check for web-environment constraints

src/passes/CMakeLists.txt, src/passes/Precompute.cpp, src/passes/pass.cpp, src/shell-interface.h, src/tools/binaryen-shell.cpp, src/wasm-builder.h, src/wasm-interpreter.h, src/wasm.cpp, test/emcc_O2_hello_world.fromasm, test/emcc_O2_hello_world.fromasm.imprecise, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.imprecise, test/memorygrowth.fromasm, test/memorygrowth.fromasm.imprecise, test/min.fromasm, test/min.fromasm.imprecise, test/passes/precompute.txt, test/passes/precompute.wast, test/unit.fromasm, test/unit.fromasm.imprecise
In unoptimized code, we can precompute stuff. This new pass just uses the interpreter code to do so directly.
=> Precompute expressions pass

src/tools/binaryen-shell.cpp
=> Prefix make_unique in binaryen_shell, for visual studio workarounds

src/cfg/Relooper.cpp, test/example/c-api-kitchen-sink.c, test/example/c-api-kitchen-sink.txt
`return` statements in particular were not handled properly without this.
=> Finalize blocks properly in relooper

CMakeLists.txt
1) the option is OFF by default
2) cmake -DBUILD_STATIC_LIB=ON . triggers it
Should fix #598
=> Add the option to build libbinaryen as a static lib

src/passes/Print.cpp, src/wasm-s-parser.h, test/example/c-api-kitchen-sink.c, test/example/c-api-kitchen-sink.txt
Function names and other things can have stuff that can mix up s-parsers, as seen in #618.
=> Parsing fixes

src/asm2wasm.h, test/unit.asm.js, test/unit.fromasm, test/unit.fromasm.imprecise, test/unit.fromasm.imprecise.no-opts, test/unit.fromasm.no-opts
We handled missing params, but fastcomp output can also overload them, in the case of `abort()` calls that represent a function call that was to an absolute address (in which case we keep the params as is). Upgrading everything to a double is ok in this case.
=> Handle param overloading in asm2wasm ffis

src/passes/CoalesceLocals.cpp, test/emcc_O2_hello_world.fromasm, test/emcc_O2_hello_world.fromasm.imprecise, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.imprecise, test/memorygrowth.fromasm, test/memorygrowth.fromasm.imprecise, test/passes/coalesce-locals.txt, test/passes/coalesce-locals.wast
Removes almost 1% of locals on BB.
Makes the pass significantly slower, but not horribly so. If there is an issue perhaps we should split it out into a separate option.
=> Optimize to remove as many copies as possible in coalesce-locals

scripts/fuzz_relooper.py, src/cfg/Relooper.cpp, src/cfg/Relooper.h, src/passes/RemoveUnusedNames.cpp, src/wasm-validator.h, test/emcc_O2_hello_world.fromasm, test/emcc_O2_hello_world.fromasm.imprecise, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.imprecise, test/example/c-api-kitchen-sink.c, test/example/c-api-kitchen-sink.txt, test/example/c-api-kitchen-sink.txt.txt, test/example/relooper-fuzz.c, test/example/relooper-fuzz.txt, test/example/relooper-fuzz1.c, test/example/relooper-fuzz1.txt, test/memorygrowth.fromasm, test/memorygrowth.fromasm.imprecise, test/passes/remove-unused-names.txt, test/passes/remove-unused-names.wast, test/unit.fromasm, test/unit.fromasm.imprecise
This improves the relooper by using @sunfishcode's "stack" approach to forward jumps, using a stack of blocks. This should remove all usage of a helper variable except for actually irreducible control flow, while still reconstructing control flow into ifs, if-elses, etc.
The implementation is fairly simple, basically, each `Process()` call in the relooper receives a self-contained set of blocks, and can ignore the outside (as branches outside have already been handled/"solipsized"). Forward jumps in that set must be implementable using a block stack, as our output is a linked list of shapes, and we simply emit the stack by looking forward in the list, each Multiple shape entry is a jump target, and the final shape is also a target as well (we can't jump to after it, as we must enter a …
=> Relooper opts

src/ast_utils.h, src/passes/Precompute.cpp, src/passes/Print.cpp, src/wasm-builder.h, src/wasm-interpreter.h, src/wasm-s-parser.h, src/wasm-traversal.h, src/wasm-validator.h, src/wasm.h
Support for the new globals preparing to land in the spec repo,
https://github.com/WebAssembly/spec/pull/313
This passes the wast test in that PR.
=> Support wasm globals

src/wasm-binary.h, src/wasm.cpp
I think this is right, but not sure I read the spec correctly.
Each global has a type and a normally-emitted expression, with a 0 ending, and it must contain one expression which is popped and used as the initial value for the global. @rossberg-chromium, is that correct?
=> Binary format support for wasm globals

auto_update_tests.py, src/wasm-s-parser.h, src/wasm.h, test/hello_world.wast, test/kitchen_sink.wast, test/min.wast, test/passes/coalesce-locals-learning.txt, test/passes/coalesce-locals.txt, test/passes/dce.txt, test/passes/drop-return-values.txt, test/passes/duplicate-function-elimination.txt, test/passes/lower-if-else.txt, test/passes/metrics.txt, test/passes/nm.txt, test/passes/optimize-instructions.txt, test/passes/post-emscripten.txt, test/passes/precompute.txt, test/passes/remove-imports.txt, test/passes/remove-unused-brs.txt, test/passes/remove-unused-functions.txt, test/passes/remove-unused-names.txt, test/passes/remove-unused-names_merge-blocks.txt, test/passes/reorder-functions.txt, test/passes/reorder-locals.txt, test/passes/simplify-locals.txt, test/passes/vacuum.txt, test/reg_switch.wast, test/unit.wast
Update spec tests, and a fix for the desugaring change, cherry-picked from `spec-updates` branch.
=> wast function type name desugaring is changing in spec:301

src/s2wasm.h, src/wasm-linker.cpp, src/wasm-linker.h, test/dot_s/indidx.s, test/dot_s/indidx.wast
This patch adds support for an ".indidx" primitive that pre-assigns table indexes for functions that are called indirectly. It is used by the upstream LLVM WebAssembly backend to support fine-grained [control-flow integrity](http://clang.llvm.org/docs/ControlFlowIntegrity.html) for indirect function calls by emitting instrumentation at each indirect call site to check that the destination index is within certain ranges that correspond to disjoint equivalence classes of indirect call targets. The reason that this primitive is necessary is because the layout of the table section isn't determined until the WebAssembly linker is executed, but indirect function to table index mappings need to be known when `opt` is executed to generate the correct range checking in the LLVM IR.
=> Support pre-assigning indexes for functions that are called indirectly

src/s2wasm.h, test/dot_s/text_before_type.s, test/dot_s/text_before_type.wast
```
Name lhs = getStrToSep();
if (!skipEqual()){
s = strchr(s, '\n');
if (!s) break;
continue;
}
```
The above code snippet introduced by #615 by @ddcc has a bug when there is 
only one word (e.g. ".text") in a line. If there is only one word in a line,
skipEqual() also skips the newline character at the end of the line, and
strchr(s, '\n') moves the cursor to the end of the next line,
effectively skipping the whole next line.
This patch fixes this bug.
=> Fix a parsing bug introduced by #615

src/s2wasm.h, test/dot_s/local_align.s, test/dot_s/local_align.wast
When parsing .lcomm directives, s2wasm does not parse the alignment number and skips it. This causes alignment bugs in some cases. (In the test case attached, 'buf' should be 4 bytes aligned, but it does not align it properly, so this code was generated:
```
(call $foo
(i32.const 13)
)
```
13 is not 4-bytes aligned. This patch fixes this bug.
@dschuff @jpporto
=> Fix alignment bug in .lcomm

src/asm2wasm.h, src/cfg/Relooper.cpp, src/passes/LowerIfElse.cpp, src/passes/LowerInt64.cpp, src/support/threads.cpp, src/wasm-module-building.h, test/empty.asm.js, test/empty.fromasm, test/empty.fromasm.imprecise, test/empty.fromasm.imprecise.no-opts, test/empty.fromasm.no-opts
These commits fix an asm2wasm dead lock when asm2wasm is compiling an empty module, i.e. a module without any functions.
Without this commit, worker threads are likely to leave `workerMain()` and decrease `liveWorkers` early.  Consequently, `waitUntilAllReady()` will never observe `liveWorkers == numWorkers`.
=> Fix asm2wasm dead lock caused by empty module

src/wasm-linker.cpp, test/dot_s/export_malloc_free.s, test/dot_s/export_malloc_free.wast
To support asm.js style setjmp/longjmp, wasm needs to export realloc as well, in addition to malloc and free handled in #4469. saveSetjmp() uses realloc within it, and realloc is not implemented in JS glue code.
@dschuff @jpporto
=> Asm.js-style setjmp/longjmp support for wasm

src/support/colors.cpp, src/support/colors.h
The only feature Windows does not support is changing font type to bold. Tested with Mingw64 gcc 5.4.0, should work with MSVC as well.
=> Color support for Windows

src/passes/OptimizeInstructions.cpp, src/support/threads.h, src/wasm-binary.h, src/wasm-module-building.h
First commit fixes call order being unspecified over `|`.
Second fixes #692, where we relied on the order of global ctors.
=> Ordering bug fixes for windows

src/wasm-emscripten.cpp
It's possible to generate an EM_ASM call with empty contents (due to
ifdefs, for example), and this gets converted to an empty string.
AsmConstWalker assumes that by this point any addresses it is pointing
to have a corresponding data section, which is reasonable. However in
the case of an empty string, we don't create a data section, but just
leave that address uninitialized, i.e. set to 0.
In the case of AsmConstWalker, a correct thing to do is to emit the
empty string as metadata, which becomes an empty emscripten_asm_v call.
=> In AsmConstWalker, don't assume a segment exists

src/asm2wasm.h, src/ast_utils.h, src/passes/SimplifyLocals.cpp, src/passes/Vacuum.cpp, test/example/c-api-kitchen-sink.txt, test/example/c-api-kitchen-sink.txt.txt, test/passes/simplify-locals.txt, test/passes/simplify-locals.wast, test/passes/vacuum.txt, test/passes/vacuum.wast, test/unit.asm.js, test/unit.fromasm, test/unit.fromasm.imprecise, test/unit.fromasm.imprecise.no-opts, test/unit.fromasm.no-opts
Found by the new fuzzer, the autodrop logic was not quite right, sometimes dropping an already dropped value higher in the AST. This fixes that, and as a bonus optimizes two drops in an if into a single drop of the if.
=> Autodrop fix

scripts/fuzz_passes.py
This contains just the fuzzer script. Separate issues/PRs can handle what it finds.
So far it found #708, and an autoDrop issue that I am fixing and will open a PR for.
=> Add a pass fuzzer script

src/passes/Precompute.cpp, src/passes/Vacuum.cpp, test/example/c-api-kitchen-sink.txt, test/example/c-api-kitchen-sink.txt.txt, test/passes/precompute.txt, test/passes/precompute.wast, test/passes/vacuum.txt, test/passes/vacuum.wast, test/unit.asm.js, test/unit.fromasm, test/unit.fromasm.imprecise, test/unit.fromasm.imprecise.no-opts, test/unit.fromasm.no-opts
The precompute pass already did everything to handle void expressions, but didn't actually do it. It just needs to nop an expression it managed to precompute if that expression isn't a concrete value. This gets rid of e.g. `if (0) { .. anything .. }` type things.
=> Precompute void expressions too

src/passes/Precompute.cpp, src/wasm-builder.h, test/passes/O.txt, test/passes/O.wast, test/passes/precompute.txt, test/passes/precompute.wast
Normal code doesn't generally benefit from it, but might as well do it for completeness, since it's easy (the only reason it's more than a few lines is to avoid unnecessary allocations), and we might as well optimize silly code too.
=> Precompute breaks and returns

auto_update_tests.py, check.py, src/tools/wasm-as.cpp, src/wasm-binary.h, test/hello_world.wast.fromBinary.noDebugInfo, test/kitchen_sink.wast.fromBinary.noDebugInfo, test/min.wast.fromBinary.noDebugInfo, test/reg_switch.wast.fromBinary.noDebugInfo, test/unit.wast.fromBinary.noDebugInfo
As discussed in #700.
This also needs emscripten repo support (to invoke with `-g` when appropriate), I'll add that next.
This touches wasm-binary.h so it should wait to be rebased and merged after the 0xc binary changes are done.
=> Make wasm-as emit the names section/debug info only with -g

src/passes/Print.cpp, src/wasm-binary.h, src/wasm-s-parser.h, src/wasm.cpp, test/example/c-api-kitchen-sink.txt, test/example/c-api-kitchen-sink.txt.txt, test/passes/nm.txt, test/passes/simplify-locals.txt, test/unit.wast, test/unit.wast.fromBinary, test/unit.wast.fromBinary.noDebugInfo
As noted in the individual commits. There's still some kind of problem with autoblock types/breaks which target the function implicit block, so not merging yet
=> Update binary encoding for block, loop, and if signatures

src/wasm-validator.h, test/passes/vacuum.txt, test/passes/vacuum.wast
This makes the validator enforce drop being used on a value that is droppable. Apparently no spec test checks this, so it wasn't done already. The new pass fuzzer noticed this.
Spec tests are updated here since the previous version had some incorrect drops (which I meanwhile noticed and fixed in https://github.com/WebAssembly/spec/pull/351.
This can't be merged yet due to #708, we need to fix either the wasm backend or s2wasm to emit proper drops, so they pass this new validation.
=> Validate drop

auto_update_tests.py, check.py, src/asm2wasm.h, test/wasm-only.asm.js, test/wasm-only.fromasm, test/wasm-only.fromasm.imprecise, test/wasm-only.fromasm.imprecise.no-opts, test/wasm-only.fromasm.no-opts
Counterpart to https://github.com/kripken/emscripten-fastcomp/pull/153
=> More wasm-only opts

src/js/wasm.js-post.js
The JS API in VMs has changed in 0xc.
=> Use new WebAssembly.Instance/Module API

src/asm2wasm.h, src/binaryen-c.cpp, src/passes/LegalizeJSInterface.cpp, src/passes/Print.cpp, src/shell-interface.h, src/tools/wasm-shell.cpp, src/wasm-binary.h, src/wasm-emscripten.cpp, src/wasm-js.cpp, src/wasm-linker.cpp, src/wasm-linker.h, src/wasm-s-parser.h, src/wasm-validator.h, src/wasm.h
This seems cleaner, the only reason I didn't do it this way originally is I didn't realize yet that import and export kinds are in fact the same thing.
This also makes talking about global entities easier, e.g. we can talk of a Function without knowing if its exported or imported.
=> Refactor Import::Kind and Export::Kind into a Kind enum class

src/asm2wasm.h, src/binaryen-c.cpp, src/passes/Print.cpp, src/wasm-binary.h, src/wasm-linker.cpp, src/wasm-linker.h, src/wasm-s-parser.h, src/wasm.h
Refine tables to explicitly exist or not. Previously they were printed
or encoded if it had any segments, or an initial or max size. However
tables can be defined but empty, so we had a special hack that defined
an empty segment when we really just wanted an empty table. Now, just
make the existence explicit.
Update Function table encoding for 0xc (Table and Element sections)
Add end opcodes after function bodies (these are consumed by
getMaybeBlock with the same behavior that it had before when it reached
the function end, so no explicit decode)
Update call_indirect encoding for 0xc (no arity, call target is last)
=> More binary updates for 0xc 

check.py, src/wasm-binary.h
Also skip binary roundtrip on stacky spec tests
=> Binary 0xc: Remove arity on return instruction

src/wasm-validator.h
It's valid by construction in s-parsing, but when generating IR (e.g. using the C API in mir2wasm) it is possible to get it wrong.
=> Validate get_local type

src/cfg/cfg-traversal.h, src/passes/CoalesceLocals.cpp, test/passes/coalesce-locals-learning.txt, test/passes/coalesce-locals.txt, test/passes/coalesce-locals.wast
Cleans up and removes some obviously unneeded processing in Coalesce-Locals. Makes it 7% faster.
=> Minor cfg-traversal opts

src/asm2wasm.h, src/passes/Print.cpp, src/wasm-binary.h, src/wasm-s-parser.h, src/wasm-validator.h, src/wasm.h, test/table-import.wast, test/table-import.wast.fromBinary, test/table-import.wast.fromBinary.noDebugInfo
Previously the Print pass searched the imports for for a table import and skipped printing a local table declaration if found. Instead this refactors to make importation explicit, and also create importation records (previously we were inconsistent about whether such records were created in the IR depending on the wast syntax).
=> Don't create table sections for imported tables

src/asm2wasm.h, src/js/wasm.js-post.js, test/memorygrowth.fromasm, test/memorygrowth.fromasm.imprecise, test/memorygrowth.fromasm.imprecise.no-opts, test/memorygrowth.fromasm.no-opts
This makes the wast valid. However, running it natively hangs, something else worse is going on.
=> Remove memory maximum in asm2wasm when memory growth is on

src/passes/CoalesceLocals.cpp
Not sure if `LocalSet` is large enough for binary search to be a more efficient solution, but still implement it anyway.
Probably should move the following block to a new function?
```cpp
Index low = 0, high = size() - 1;
while (low < high) {
Index mid = (low + high) / 2;
if ((*this)[mid] >= x) high = mid;
else low = mid + 1;
}
```
Maybe binary search function from `<algorithm>` is more optimized?
Test: https://gist.github.com/rongjiecomputer/006990a47edb477497e221590136aafb
=> Implement binary search

src/wasm-s-parser.h, test/empty_imported_table.wast, test/empty_imported_table.wast.fromBinary, test/empty_imported_table.wast.fromBinary.noDebugInfo, test/imported_memory.wast, test/imported_memory.wast.fromBinary, test/imported_memory.wast.fromBinary.noDebugInfo, test/imported_memory_growth.wast, test/imported_memory_growth.wast.fromBinary, test/imported_memory_growth.wast.fromBinary.noDebugInfo
If no max is specified, then there is no max.
=> Fix bug where we set memory max unnecessarily

src/passes/CoalesceLocals.cpp, test/passes/coalesce-locals.txt, test/passes/coalesce-locals.wast
Found by the fuzzer. A `tee_local` in unreachable code can't be converted into a `nop` as the type is wrong.
=> Handle unreachable tee_local properly in coalesce-locals

check.py
We can now use the `binary-0xc` branch as [our stack test refactoring](https://github.com/WebAssembly/spec/pull/351) landed in upstream.
Meanwhile a new `unwind.wast` test was added upstream which we need to ignore as it is too stacky.
=> Update spec tests

src/asm2wasm.h, src/passes/Print.cpp, src/wasm-binary.h, src/wasm-s-parser.h, src/wasm-validator.h, src/wasm.h, test/memory-import.wast, test/memory-import.wast.fromBinary, test/memory-import.wast.fromBinary.noDebugInfo
I've made a naive and simple code similar to what's being done for tables. Tests all pass until I get an error just before running the torture tests:
```
[ checking torture testcases... ]
Traceback (most recent call last):
File "./check.py", line 558, in <module>
import test.waterfall.src.link_assembly_files as link_assembly_files
ImportError: No module named waterfall.src.link_assembly_files
```
=> Don't create memory sections for imported memories; fixes #772

src/support/archive.cpp
Fix crash on loading archives, firstRegularData member field was not initialized to null which caused dereferencing a garbage pointer.
=> fix_uninit_pointer_deref

scripts/fuzz_passes_wast.py, src/passes/SimplifyLocals.cpp, test/passes/simplify-locals.txt, test/passes/simplify-locals.wast
Per new wasm rules the `br_if` returns the value too, so we must `drop` it too.
=> Fix simplify-locals when adding a value to a br_if

check.py
Fix check.py to run on Windows and improve it to be configurable to be executed in different environments. Relates to #762.
=> more_flexible_check_py

src/passes/RemoveUnusedFunctions.cpp, test/passes/remove-unused-functions.txt, test/passes/remove-unused-functions.wast
RemoveUnusedFunctions pass of wasm-opt fails when the memory is exported.
That's due to a wrong root set handling on the exported symbols.
This CL fixes the failure by ignoring non-function exported symbol.
=> Do not use exported memory as a root set of RemoveUnusedFunctions pass

src/support/archive.cpp
Fix crash when loading archive files, dereferencing iterator .end() is undefined behavior.
=> fix_iterator_end_deref

src/passes/pass.cpp, test/emcc_O2_hello_world.fromasm, test/emcc_O2_hello_world.fromasm.imprecise, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.imprecise, test/memorygrowth.fromasm, test/memorygrowth.fromasm.imprecise
Reordering and getting rid of unneeded locals makes coalesce-locals much faster. Embarrassing we didn't do this before, it makes coalesce-locals almost twice as fast (since simplify-locals gets rid of most of the locals).
=> Reorder locals after simplify-locals

src/passes/Metrics.cpp, test/passes/metrics.txt, test/passes/metrics.wast
Prints out the total size of table and memory segment contents.
=> Add table and memory to metrics

CMakeLists.txt, src/wasm-interpreter.cpp, src/wasm-interpreter.h
1. Indent nested blocks for more readable structure (with numeric labels
to make it even clearer)
2. Print the names of the variables used for NOTE_EVALs
3. Print the values of arguments when entering a function call
=> Minor improvements to the wasm-interpreter debug messages

auto_update_tests.py, check.py, src/asm2wasm.h, src/pass.h, src/tools/asm2wasm.cpp, src/tools/optimization-options.h, src/tools/wasm-opt.cpp
Adds them to both `wasm-opt` and `asm2wasm`, for a consistent interface (before `asm2wasm` always optimized unless `--no-opts` was passed; this deprecates that old option).
=> Add -O0,-O1,etc. options

src/emscripten-optimizer/simple_ast.h, src/wasm-s-parser.h
Fix some C6246: "Local declaration of 'i' hides declaration of the same name in outer scope." warnings.
=> local_declaration_hides

src/wasm-js.cpp
It now expects a `PassOptions` object.
=> Update wasm-js.cpp code for asm2wasm constructor change

src/passes/OptimizeInstructions.cpp, test/passes/optimize-instructions.txt, test/passes/optimize-instructions.wast
Avoids a wrap instruction when the store would wrap anyhow. See #789.
=> Optimize to i64.store[less]

scripts/strip_local_names.py, src/cfg/cfg-traversal.h, src/passes/CoalesceLocals.cpp, test/emcc_O2_hello_world.fromasm, test/emcc_O2_hello_world.fromasm.imprecise, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.imprecise, test/memorygrowth.fromasm, test/memorygrowth.fromasm.imprecise, test/passes/coalesce-locals.txt, test/passes/coalesce-locals.wast
Working harder to remove copies on backedges to loops helps both on code size (often such a copy ends up requiring a branch for) and performance (as noticed when comparing to asm.js, where the js optimizer has a special "loop variable" hack for this).
=> Add priority to copies on backedges

src/passes/CMakeLists.txt, src/passes/PrintCallGraph.cpp, src/passes/pass.cpp, src/passes/passes.h, test/passes/print-call-graph.txt, test/passes/print-call-graph.wast
When optimizing for size, it's sometimes hard to figure out why some functions are not being eliminated. Visualizing the call graph can help identify the functions that are most responsible for hanging on to large parts of the code.
The graph below is represents `printf("Hello World");`.
=> Adds a pass to print call graphs in .dot (graphviz) format.

src/wasm-binary.h, src/wasm/wasm-binary.cpp
See #800. The problem was indeed that  we must handle float literals carefully to not change their sign bit on some platforms/compilers, and that commit made relevant functions non-inline which hit a bug.
=> Fix binary format regression

CMakeLists.txt
This creates install rules for the binaryen shlib and the C header, as
well as for the various JS files (wasm.js and binaryen.js, as well as
those used by emscripten). It recreates in the install target the
current layout used by an in-tree build.
=> Create CMake install targets for libs and JS files

src/ast/cost.h, src/ast_utils.h, src/passes/OptimizeInstructions.cpp, test/passes/optimize-instructions_optimize-level=2.txt, test/passes/optimize-instructions_optimize-level=2.wast
When we have `expensive | expensive`, and both are boolean, then we can execute one of them conditionally if it doesn't have side effects.
Noticed on the conditionals benchmark, like #804. This brings us from 1.56x the execution time of asm.js to 0.87x.
=> Conditionalize boolean operations based on cost

src/ast_utils.h, src/passes/CMakeLists.txt, src/passes/CodePushing.cpp, src/passes/pass.cpp, src/passes/passes.h, test/emcc_O2_hello_world.fromasm, test/emcc_O2_hello_world.fromasm.imprecise, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.imprecise, test/memorygrowth.fromasm, test/memorygrowth.fromasm.imprecise, test/passes/code-pushing.txt, test/passes/code-pushing.wast
This "pushes" code forward in blocks, past conditional control flow when possible. That brings definitions closer to their uses, allowing better optimizations elsewhere, and can also move code to a location where it executes only some of the time.
This doesn't do a full CFG analysis, instead it does a simple and cheap computation on our AST, using the structure in our control flow. That isn't enough for everything, but it should be for most things and for inner loops in particular.
This makes the `primes` benchmark as fast as asm.js (or slightly faster). Also has some (very minor, but consistent) code size benefits.
=> Code pushing

src/s2wasm.h, test/dot_s/return.s, test/dot_s/return.wast
Loops are modeled in Binaryen IR as having a Block as a body. The block
is added to module walkers and validated like a normal block.
In s2wasm when we add the blocks, we need to make sure that the type of
the loop body matches the type of the loop itself, or we run into
issues.
=> Set the type of the implicit blocks we use for a loop body in s2wasm

src/passes/RemoveUnusedBrs.cpp, test/emcc_O2_hello_world.fromasm, test/emcc_O2_hello_world.fromasm.imprecise, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.imprecise, test/memorygrowth.fromasm, test/memorygrowth.fromasm.imprecise, test/passes/remove-unused-brs.txt, test/passes/remove-unused-brs.wast, test/passes/remove-unused-brs_shrink-level=1.txt, test/passes/remove-unused-brs_shrink-level=1.wast
Noticed on the `ifs` benchmark.
=> Some minor if/br_if opts

src/passes/MergeBlocks.cpp, test/passes/merge-blocks.txt, test/passes/merge-blocks.wast
A dropped `br_if` changes its type. We still dropped it, which was wrong. Also noticed some other minor non-optimal code here and fixed that. Also we didn't handle the case of a `br_if` which is *not* dropped (which we don't ever emit, but maybe someone will), fixed too.
=> Fix mergeblocks drop br if

src/passes/ExtractFunction.cpp, src/passes/RelooperJumpThreading.cpp, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.imprecise, test/unit.asm.js, test/unit.fromasm, test/unit.fromasm.imprecise, test/unit.fromasm.imprecise.no-opts, test/unit.fromasm.no-opts
This improves RelooperJumpThreading to handle a more cases, specifically an if on a label with a loop for the body, which can have more label settings going to the same place. Those are ok to ignore, since they get to the right place anyhow, so we can thread them.
Turns out this is more common than I thought, it reduces zlib size by 3%.
=> Reloop if-loops with label targets

src/asm2wasm.h, test/unit.asm.js, test/unit.fromasm, test/unit.fromasm.imprecise, test/unit.fromasm.imprecise.no-opts, test/unit.fromasm.no-opts
Reported in #829.
We supported the opposite case, but not this one.
=> Support assigns of f32 to HEAP64 in asm2wasm

src/tools/wasm-as.cpp, src/wasm-binary.h, src/wasm/wasm-binary.cpp
`test_demangle_stacks` was broken. This fixes it by updating the Names section to the latest upstream changes, where Names contains imports (first, before the others). This was updated in SpiderMonkey which was how this was noticed.
Also add a `--symbolmap` option to `wasm-as`, to fix emitting symbols in a side file instead of the Names section (which users like for demangling stack traces from production, etc.).
@dschuff: looks like latest v8 (of a day or so ago) still has the old Names section, so this might break that test on v8 until it's fixed.
=> Symbols fixes

src/js/wasm.js-post.js
Give users some help when hitting this issue, which can happen when changing `TOTAL_MEMORY` at runtime. For now, just recommend memory growth which can solve it, but maybe we can do even better here later (add an option for specifying the allowed range?).
=> Show a warning with guidance on a memory size incompatibility issue

src/asm2wasm.h
We may not have the marker symbols (e.g. in ONLY_MY_CODE that is the case).
Fixes https://github.com/kripken/emscripten/issues/4715
=> improve memory growth ignoring code in asm2wasm

src/js/wasm.js-post.js
Interpreting as a fallback was useful in the early days, but now we have proper native support and are focused on testing that. Removing the interpreter fallback avoids bundling the interpreter by default in builds, and avoids surprising users with slow execution when their VM lacks native support.
=> Run wasm natively by default, no fallbacks to interpreting

src/tools/asm2wasm.cpp
Gives users full customization over the memory sizes in the emitted wasm.
=> Add --mem-max option to set the maximum size of memory

src/passes/MergeBlocks.cpp, test/passes/remove-unused-names_merge-blocks.txt, test/passes/remove-unused-names_merge-blocks.wast
Found by fuzzer. We checked for side effects, but not full reordering.
=> Fix a reordering bug in merge-blocks

src/support/command-line.cpp, src/support/file.cpp, src/support/file.h
Example:
```
asm2wasm INFILE
Translate asm.js files to .wast files 
Options:
--help,-h            Show this help message and exit 
--debug,-d           Print debug information to stderr 
--output,-o          Output file (stdout if not specified) 
--mapped-globals,-n  Mapped globals 
--mem-init,-t        Import a memory initialization file into the output 
module 
--mem-base,-mb       Set the location to write the memory initialization 
(--mem-init) file (GLOBAL_BASE in emscripten). If not 
provided, the memoryBase global import is used. 
--mem-max,-mm        Set the maximum size of memory in the wasm module (in 
bytes). Without this, TOTAL_MEMORY is used (as it is used
for the initial value), or if memory growth is enabled, 
no limit is set. This overrides both of those. …
```
=> Wrap description

src/asm2wasm.h, src/passes/OptimizeInstructions.cpp, src/passes/PostEmscripten.cpp, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.imprecise, test/memorygrowth.fromasm, test/memorygrowth.fromasm.imprecise, test/passes/optimize-instructions.txt, test/passes/post-emscripten.txt, test/passes/post-emscripten.wast
It is not always safe to fold added offsets into load/store offsets, as the add wraps but offset does not. But it is safe if we know a range of "impossible" values to load/store from, which is the case in asm2wasm output, so move that logic into the `post-emscripten` pass.
=> Fix regression from #850

src/wasm-binary.h, src/wasm/wasm-binary.cpp
Not an easy way to test this without checking in a binary. But after either dynamic or static linking works, we can use those to add a test.
=> Ignore unknown user sections, fixes #857

src/ast_utils.h
As detailed in the commit, this makes it work properly even when hashing expressions from different functions and modules.
=> Hash the type of nodes

src/ast_utils.h
We need to copy it, as it is an expression. Instead we just copied the pointer.
=> fix copy of call_indirect bug

src/binaryen-c.cpp, src/wasm-binary.h, src/wasm/wasm-binary.cpp, test/example/c-api-unused-mem.cpp, test/example/c-api-unused-mem.txt
Fixes #870. The C API forgot to mark the created memory as existing, and no other usage of it caused that, so it wasn't written out. One-line fix.
=> Mark memory as existing when it is created in the C API

src/asm2wasm.h, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.imprecise, test/wasm-only.asm.js, test/wasm-only.fromasm, test/wasm-only.fromasm.imprecise, test/wasm-only.fromasm.imprecise.no-opts, test/wasm-only.fromasm.no-opts
On a unity testcase we still had some dead code, turns out not to be a bug in dce but that we run it too early, and one other opt pass can create dceable code - relooper jump threading.
=> DCE at the end of asm2wasm

src/asm2wasm.h, test/wasm-only.asm.js, test/wasm-only.fromasm.imprecise.no-opts, test/wasm-only.fromasm.no-opts
(diff with `-w` is much clearer)
Addresses #873. We are given a switch that is far too big to make sense, and we construct a jump table very slowly and in fact start to read out of bounds in this case due to integer overflow.
We should figure out why that happens in fastcomp, but regardless, it's good for asm2wasm to be able to handle such things.
=> When a switch is too big, create an if-else chain instead

CMakeLists.txt
The posix build enables assertions on release builds with
`ADD_NONDEBUG_COMPILE_FLAG("-UNDEBUG")`
but the windows build does not. This PR adds /UNDEBUG to the release
build flags but has the additional complication that /DNDEBUG is added
to CFLAGS by CMake by default, and MSVC will warn about having /UFOO
after /DFOO on the command line. So we scrub DNDEBUG from CFLAGS
as well.
Additional windows build cleanups:
* Disable conversion/truncation warnings
* Canonicalize flag style to use slashes everywhere instead of mixing
* MSVC uses /Od (not /O0) to disable optimization
=> Allow release builds with asserts on windows

test/unreachable-import_wasm-only.fromasm.imprecise.no-opts, test/unreachable-import_wasm-only.fromasm.no-opts
PR before last added a test, last PR changed DCE settings which affected that test, and I guess I landed the latter too soon after the first to see anything on CI.
=> fix bustage caused by conflict between last two landings

auto_update_tests.py, check.py, scripts/test/shared.py, src/tools/asm2wasm.cpp, src/tools/wasm-opt.cpp, src/wasm-binary.h, src/wasm-io.h, src/wasm/CMakeLists.txt, src/wasm/wasm-io.cpp
This implements ModuleReader/Writer classes, that can read/write modules in either binary or text form. They pick which according to the suffix, or if the suffix is ambiguous, they default to text.
=> Read/Write Abstraction

src/passes/OptimizeInstructions.cpp
PatternDatabase serves no purposes since #717. This saves about 30KB to 160KB in final executables (MSVC).
=> Hide dead code (PatternDatabase)

test/unit.asm.js, test/unit.fromasm, test/unit.fromasm.imprecise, test/unit.fromasm.imprecise.no-opts, test/unit.fromasm.no-opts
I noticed we don't have a test for emitting `f32/64.sqrt`.
=> add sqrt test

src/passes/OptimizeInstructions.cpp, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.imprecise, test/passes/optimize-instructions.txt, test/passes/optimize-instructions.wast, test/passes/precompute.txt, test/passes/precompute.wast
This was found by the superoptimizer #900. wasm doesn't have i8 and i16 values, so we need to manually sign-extend/zero-extend them when necessary. For loads, we have an opcodes for that, but otherwise, we must use an and for zero-extend or two shifts for sign-extend. It is therefore useful to find out when we can avoid a sign-extend or at least replace it with a zero-extend.
This PR implements two aspects of this:
* When a sign-extend output goes into a compare, we may not need the sign-extend (if we compare to an integer, or to another sign-extend).
* When a sign-extend receives a value without a sign bit, we can skip it.
This saves 0.4% of binary size in Unity and Lua, for example.
=> Optimize sign-extends

src/passes/OptimizeInstructions.cpp, src/support/bits.cpp, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.imprecise, test/passes/optimize-instructions.txt, test/passes/optimize-instructions.wast, test/unit.fromasm, test/unit.fromasm.imprecise
This builds upon #902, and is another superoptimizer-directed optimization (see #900). Here we optimize linear sums, i.e., nested adds + subs + muls + left-shifts, to combine all the constant factors.
This saves 0.2% of lua code size, but more importantly, it's more efficient code.
=> Optimize linear sums

src/passes/OptimizeInstructions.cpp, test/emcc_O2_hello_world.fromasm, test/emcc_O2_hello_world.fromasm.imprecise, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.imprecise, test/memorygrowth.fromasm, test/memorygrowth.fromasm.imprecise, test/passes/optimize-instructions.txt, test/passes/optimize-instructions.wast, test/unit.fromasm, test/unit.fromasm.imprecise
E.g. combine a shift of a shift, and of an and, etc., when on constant factors.
To enable this, also optimize "almost" sign extends, which are sign extends with some extra shifts on the inside. The extra shifts can come from combining the sign extend shift with an additional one, so without this squared operations could hurt us.
This shrinks lua by 0.35%.
=> Optimize "squared" operations

src/wasm-traversal.h, test/passes/metrics.txt
When wasm added init expressions to table and memory segments, we added support for them but apparently never added traversal logic. This fixes that. So far not much uses it, just the metrics pass now counts those nodes as you can see in the changeset.
=> allow traversing the offset inits of table/memory segments

src/asm2wasm.h, src/binaryen-c.cpp, src/passes/LegalizeJSInterface.cpp, src/passes/Print.cpp, src/passes/RemoveImports.cpp, src/wasm-emscripten.cpp, src/wasm-linker.cpp, src/wasm-validator.h, src/wasm.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp
Seems to be the only raw pointer in the core wasm.h classes (except for `Expression*` pointers, of course). Probably a relic of the very early days of this header. This PRs makes it consistent with everything else.
=> Clean up raw pointer in import->functionType

src/wasm-traversal.h, test/passes/metrics.txt, test/passes/metrics.wast
Similar to #916, another thing we didn't traverse, the init expressions of globals.
=> allow traversing the inits of globals

src/shell-interface.h, src/support/name.h, src/wasm-emscripten.cpp, src/wasm-linker.h, src/wasm.h, test/dot_s/asm_const.wast, test/dot_s/memops.wast
Check the function's name by substring, so as to handle the various lowered forms, `emscripten_asm_const`, `emscripten_asm_const_int`, and `emscripten_asm_const_double`. This also catches the C++ mangled forms of these functions (regardless of how their template arguments expand).
=> Fully handle EM_ASM in s2wasm

src/asm2wasm.h, src/ast/count.h, src/ast_utils.h, src/pass.h, src/passes/CodePushing.cpp, src/passes/DeadCodeElimination.cpp, src/passes/DuplicateFunctionElimination.cpp, src/passes/Inlining.cpp, src/passes/LegalizeJSInterface.cpp, src/passes/MergeBlocks.cpp, src/passes/OptimizeInstructions.cpp, src/passes/PickLoadSigns.cpp, src/passes/PostEmscripten.cpp, src/passes/PrintCallGraph.cpp, src/passes/RelooperJumpThreading.cpp, src/passes/RemoveImports.cpp, src/passes/RemoveUnusedBrs.cpp, src/passes/RemoveUnusedModuleElements.cpp, src/passes/RemoveUnusedNames.cpp, src/passes/ReorderFunctions.cpp, src/passes/ReorderLocals.cpp, src/passes/SimplifyLocals.cpp, src/passes/Vacuum.cpp, src/wasm-emscripten.cpp, src/wasm-traversal.h, src/wasm-validator.h, src/wasm/wasm.cpp, src/wasm2asm.h
Most module walkers use `PostWalker<T, Visitor<T>>`, let that pattern be
expressed as simply `PostWalker<T>`
=> Default Walker subclasses to using Visitor<SubType>

src/tools/optimization-options.h
Fixes below error
```
In file included from /***/binaryen/src/tools/wasm-opt.cpp:53:
/***/binaryen/src/tools/optimization-options.h:81:14: error: lambda capture 'runOptimizationPasses' is not used [-Werror,-Wunused-lambda-capture]
[&runOptimizationPasses, &passOptions](Options*, const std::string&) {
^
In file included from /***/binaryen/src/tools/asm2wasm.cpp:74:
/***/binaryen/src/tools/optimization-options.h:81:14: error: lambda capture 'runOptimizationPasses' is not used [-Werror,-Wunused-lambda-capture]
[&runOptimizationPasses, &passOptions](Options*, const std::string&) {
^
1 error generated.
```
=> Fixes compilation error on clang

src/asm2wasm.h, test/use-import-and-drop.asm.js, test/use-import-and-drop.fromasm, test/use-import-and-drop.fromasm.imprecise, test/use-import-and-drop.fromasm.imprecise.no-opts, test/use-import-and-drop.fromasm.no-opts
When an import could return i32 or f32 etc., to handle that overloading we make it return an f64 which can contain any JS number. However, we also did that with none, i.e., an import returning i32 in one place and no used return value in another, we turned into f64. This was just a bug due to the ordering logic.
I noticed this when doing https://github.com/kripken/emscripten/pull/4976 - the problem was we turned an i32 import into an f64, and the f64 conversion operator trapped, I guess since converting a JS undefined is no longer valid (`setTempRet0` was not returning a value, which is what that other PR fixes).
Anyhow, this PR fixes the bug, which is not just more correct but also avoids the extra unnecessary cast operation.
=> asm2wasm import overloading fix

src/passes/Vacuum.cpp, test/passes/vacuum.txt, test/passes/vacuum.wast
Fuzz bug. We merge if-else that drops both sides into a single drop of the if, but that only works if the two sides have the same type.
=> Do not merge a drop out of an if if the sides have different types

src/wasm/wasm-binary.cpp, test/unit.wast, test/unit.wast.from-wast, test/unit.wast.fromBinary, test/unit.wast.fromBinary.noDebugInfo
We didn't handle one corner case there (if with unreachable condition but without an else) which it turns out the optimizer can now emit sometimes.
=> fix emitting of unreachable ifs

src/s2wasm.h
Changes to the wasm backend wind up adding `.size` directives after `.import_global` statements.
My understanding of what's going on:
LLVM models data about all globals
LLVM emits `.size` annotations for things it knows the size of, such that they might get allocated in the data section
LLVM additionally emits `.import_global` for globals that are imported
s2wasm uses `.import_global` to generate import statements for arbitrary globals
s2wasm uses `.size`s to initialize and/or reserve space in data
s2wasm doesn't use or need the size of imported globals, so we can just ignore it
So, a better fix may be to not emit the `.size`s from LLVM when the global is imported. Not sure what's optimal here. Also not sure how important it is to find the best thing, if we're going to move to o2wasm in a …
=> Skip .size directives that follow .import_global directives

src/passes/OptimizeInstructions.cpp, test/passes/optimize-instructions.txt, test/passes/optimize-instructions.wast
A sign-extend compared to a constant that it can never be equal to sometimes happens (in unoptimized LLVM code, so this wasn't noticed til now). This confused our optimizer a little.
We now check if the comparison can never be true, and if so, emit something guaranteed to give the right result.
=> Fix comparisons of sign-extends to weird constants

src/emscripten-optimizer/optimizer-shared.cpp, src/support/threads.h
This PR changes two things:
1. Add a missing `<functional>` include
2. Put the `// fallthrough` comment after the closing bracket so the compiler does not emit a implicit fallthrough warning.
=> Fix build with gcc 7

CMakeLists.txt
This is a fix for an asm2wasm stack-overflow crash on Windows. The default stack size (MSDN: "For ARM, x86 and x64 machines, the default stack size is 1 MB.") does not seem to be enough for some use cases. Setting the stack size to 2 MB fixes the crash.
=> fix asm2wasm stack-overflow on windows

src/wasm-binary.h, src/wasm/wasm-binary.cpp, test/example/c-api-unused-mem.txt
First stab at addressing https://github.com/WebAssembly/binaryen/issues/914.
No locals yet, but we weren't emitting those before.
Are there any tests I should be running?
=> Extensible name section

src/asm2wasm.h, src/passes/Print.cpp, src/wasm.h
Rather than storing debug info as text annotations, store explicit file and line information. This will make it easier to experiment with outputting other serializations or representations (e.g. source maps), and will allow outputting debug info for binaries as well.
=> Replace text annotations with explicit file/line for debug info

scripts/test/s2wasm.py
This was landed when ci wasn't working, so we didn't notice the bustage.
=> fix s2wasm.py hanging indent

.travis.yml
The "trusty" dist is new, and just pulls in newer versions of all the tools (except for e.g. the compiler which we handle separately).
=> Use Trusty instead of the defaut (Precise) on Travis bots

src/asm2wasm.h, src/ast_utils.h, src/pass.h, src/passes/CoalesceLocals.cpp, src/passes/pass.cpp, src/tools/asm2wasm.cpp, src/wasm-module-building.h, test/debugInfo.asm.js, test/debugInfo.fromasm, test/debugInfo.fromasm.clamp, test/debugInfo.fromasm.clamp.no-opts, test/debugInfo.fromasm.imprecise, test/debugInfo.fromasm.imprecise.no-opts, test/debugInfo.fromasm.no-opts
This notes in our pass options whether we have debug info, and if so, disables optimizations that could eliminate the debug info (which are represented as intrinsic calls, i.e., call imports, which we might remove if they are not live etc.)
cc @yurydelendik @dschuff 
For this fib.c:
````
int fib(int n) {
int i, t, a = 0, b = 1;
for (i = 0; i < n; i++) {
t = a + b;
a = b;
b = t;
}
return b;
}
````
Before we had
````
(func $_fib (param $0 i32) (result i32)
(local $1 i32)
(local $2 i32)
(local $3 i32)
(local $4 i32)
(if
(i32.gt_s
(get_local $0)
(i32.const 0)
)
(block
(set_local $2
(i32.const 0)
)
(set_local $3
(i32.const 0)
)
(set_local $1
(i32.const 1)
)
)
(return
(i32.const 1)
)
)
(loop $while-in
;; fib.c:4
(set_local $4
(i32.add
(get_local $1)
(get_local $2)
)
)
(if
(i32.ne
(tee_local $3 …
```
=> Preserve debug info through the optimizer

src/s2wasm.h, src/wasm-validator.h, test/dot_s/unreachable_blocks.wast
Found by afl. If we have `(block i32)` then it can get broken in optimizing, as it makes no sense, there is a promise of a value but no value provided.
s2wasm apparently was ok emitting this, and we had a test accepting inputs like this:
````
block     i32
end_block
````
so I fixed that up by emitting an unreachable in the block. But perhaps this is a bug in the llvm backend, or perhaps it never emits that and the test case was in error?
=> disallow empty blocks with a type

src/passes/DeadCodeElimination.cpp, src/wasm-validator.h, src/wasm.h, src/wasm/wasm.cpp, test/passes/dce.txt, test/passes/dce.wast
This makes e.g.
````
(i32.add
(unreachable)
(i32.const 1)
)
````
have type unreachable, which is what we changed blocks to do.
This also fixes the types of blocks created by dce, to fit properly in the ast. Separate commit so that you can see the effect of consistent use of unreachable in the second, it improves our handling of unreachable code, as before, e.g. `(drop (unreachable))` did not have type unreachable, so we didn't clean it out.
=> Make use of unreachable type consistent

src/passes/Precompute.cpp, test/passes/precompute_coalesce-locals_vacuum.txt, test/passes/precompute_coalesce-locals_vacuum.wast
Where precompute alters a br to remove its condition, but does not properly modify the type.
Took afl-fuzz 3 days to find this.
=> fix an afl-fuzz bug in precompute pass

src/emscripten-optimizer/istring.h, src/passes/RelooperJumpThreading.cpp
By having a thread-local set and a global set guarded by a mutex. Each time a new string shows up in a thread, it will be added to that thread's set, after accessing the global set through the lock first, which means we lock at most once per new string per thread.
This does mean we allocate more memory, since we have a string set per thread with duplicate data. But the actual strings are still stored uniquely, so this is just the hash map. Overall it should be a small fragment of total memory usage. I measure less than 1% change on bullet.
With this, we can create new function/local/block/etc. names even when running in parallel, so all parts of module creation and optimization should be parallelizable.
=> Parallelize istring creation

check.py
The files may not exist, and it is not an error if they do not, we just want them to not be there.
Noticed this when cleaning up some stuff in emcc.py, not emitting unnecessary things.
(we already properly used `delete_from_orbit` for some things, this just makes us do it consistently)
=> Be more careful when deleting files when testing binaryen methods

src/tools/asm2wasm.cpp, src/tools/optimization-options.h, src/tools/wasm-opt.cpp
Adds a nice class instead of hackish inline-c-include of a header.
=> Refactor optimization opts

src/wasm-validator.h, test/dot_s/alias.s, test/dot_s/alias.wast, test/dot_s/unreachable_blocks.s, test/dot_s/unreachable_blocks.wast
Even if the function returns none we should still not have returns with a value, etc.
The reason we got this wrong is that some spec tests are stacky and break that assumption, i.e., they have return with a value when the function does not return. This PR also updates our spec tests to not do those ones.
This required fixing up some handwritten s2wasm tests, as they also did things like return from a non-returning function. I think I kept them sensible, still testing what they are supposed to.
=> Validate returned values in all cases

src/wasm/literal.cpp, test/llvm_autogenerated/immediates.wast
wast2wasm was recently updated to only support the
former: https://github.com/WebAssembly/wabt/pull/482
=> Output inf/-inf rather than infinity/-infinity

src/compiler-support.h, src/shell-interface.h, src/support/utilities.h
Since the following line aborts, the write to cout
can be lost (when not writing to a TTY).
=> Log callImport fatal error to cerr so it is not buffered.

CMakeLists.txt
I noticed that when settings -DCMAKE_C_COMPILER=clang I was
getting a cmake when building dummy.c:
error: invalid argument '-std=c++11' not allowed with 'C/ObjC'
=> Don't add C++-only flags to CMAKE_C_FLAGS

test/s2wasm_known_binaryen_shell_test_failures.txt
The two new failures are calling aboirt().  They back the
last LKGR build: https://wasm-stat.us/builders/linux/builds/20068
So its hard to say when they started failing.
=> Update known failures running s2wasm results in wasm-shell

test/s2wasm_known_binaryen_shell_test_failures.txt
Reverts WebAssembly/binaryen#1057
This change was made to fix the wasm waterfall expectations but broke the local binaryen tests.  Will investigate the inconsistency.
=> Revert "Update known failures running s2wasm results in wasm-shell"

auto_update_tests.py, test/print/min.minified.txt, test/print/min.txt, test/print/min.wast
It was using wasm-shell instead of wasm-opt to print. This was
emitting an error and empty output. Also this means that the min.wast
test input didn't get updated along with the spec, so I fixed that as well.
=> Fix auto_update_tests for printing/minifier tests

src/asm2wasm.h, src/binaryen-c.cpp, src/compiler-support.h, src/passes/Print.cpp, src/s2wasm.h, src/wasm-binary.h, src/wasm-builder.h, src/wasm-s-parser.h, src/wasm.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, test/atomics.wast, test/atomics.wast.from-wast, test/atomics.wast.fromBinary, test/atomics.wast.fromBinary.noDebugInfo
Add IR, wast and binary support for atomic loads and stores.
Currently all IR generated by means other than parsing wast and binary files always generates non-atomic accesses, and optimizations have not yet been made aware of atomics, so they are certainly not ready to be used yet.
=> Add atomic loads and stores

src/compiler-support.h
For even better debugging support.
=> Use sanitizer runtime to print pretty stack traces on unreachable

src/passes/Print.cpp, src/wasm-binary.h, src/wasm-s-parser.h, src/wasm-traversal.h, src/wasm.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, src/wasm/wasm.cpp, test/atomics.wast, test/atomics.wast.from-wast, test/atomics.wast.fromBinary, test/atomics.wast.fromBinary.noDebugInfo
Also leave a stub (but valid) visitAtomicRMW in the visitor template so that not all visitors need to implement this function yet.
=> Add IR, parsing and binary support for AtomicRMW instructions from wasm threads proposal

src/wasm-traversal.h
Making them valid means that derived implementations need not implement all of them, and can fall back on the ones in the template.
=> Fix visitor stubs in traversal templates

.travis.yml
1. Refactored `.travis.yml` to use Travis Build Stages (this allows to define jobs with completely different configuration).
2. Added job that builds and tests binaryen with gcc 6.3 on Alpine Linux v3.6 (inside chroot), i.e. verifies that it works with musl libc.
3. Added jobs that build binaryen with gcc 6.3 on Alpine Linux v3.6 **aarch64, armhf, and ppc64le** architectures emulated using QEMU user-mode emulator and binfmt. Emulation is quite slow, so it takes significantly more time to build. Some tests fail, although they don’t fail on native platform, so it just builds it without running tests for now.
I hope that this will help to avoid errors like #1059 in future.
BTW, this setup also allows to easily build fully statically linked binaries (i.e. they will work on every Linux, …
=> Set up Travis to run build on various architectures using Alpine and deploy statically linked binaries to GH Releases

build-js.sh
Without, calling `Module#validate` using binaryen.js errors with
> missing function: _ZN4wasm13WasmValidator11visitExportEPNS_6ExportE
As this also affects wasm.js in that building it emits warnings, I added it to the shared bitcode phase.
=> Added wasm-validator.cpp to build-js.sh

src/wasm-validator.h, src/wasm/wasm-validator.cpp, test/atomics.wast, test/atomics.wast.from-wast, test/atomics.wast.fromBinary, test/atomics.wast.fromBinary.noDebugInfo
Also fix cases where `fail()` had the arguments backwards. Wasn't an error because lol templates.
Also fix `printModuleComponent` template to SFINAE on `Expression*` so we properly get the specialized version.
=> Validation for AtomicRMW and cmpxchg

src/tools/wasm-ctor-eval.cpp
The `--help` output in `tools/wasm-ctor-eval.cpp` refers to the name `wasm-opt` rather than `wasm-ctor-eval`. I'd guess this comes from a copy+modify process for initially creating this tool.
=> Fix wrong name in --help output

src/support/file.cpp
Fix wasm::read_file() to read correctly sized input strings in text mode.
=> fix_text_file_reads

src/wasm/wasm-validator.cpp
Check for unreasonable sizes even if type is unreachable
=> improve WasmValidator::validateMemBytes

src/asm2wasm.h, test/unit.asm.js, test/unit.fromasm, test/unit.fromasm.clamp, test/unit.fromasm.clamp.no-opts, test/unit.fromasm.imprecise, test/unit.fromasm.imprecise.no-opts, test/unit.fromasm.no-opts
We handled f64 rem but not f32. (I think clang+fastcomp might never emit the latter, so this was missed.)
=> fix f32 frem in asm2wasm #1105

src/asm2wasm.h, test/wasm-only.asm.js, test/wasm-only.fromasm, test/wasm-only.fromasm.clamp, test/wasm-only.fromasm.clamp.no-opts, test/wasm-only.fromasm.imprecise, test/wasm-only.fromasm.imprecise.no-opts, test/wasm-only.fromasm.no-opts
We had a TODO on this, but forgot about it...
=> Fix asm2wasm wasm-only i64 switches with a large (>32 bit) offset #1109

src/asm2wasm.h, test/unit.asm.js, test/unit.fromasm, test/unit.fromasm.clamp, test/unit.fromasm.clamp.no-opts, test/unit.fromasm.imprecise, test/unit.fromasm.imprecise.no-opts, test/unit.fromasm.no-opts, test/use-import-and-drop.fromasm.clamp.no-opts, test/use-import-and-drop.fromasm.imprecise.no-opts, test/use-import-and-drop.fromasm.no-opts
For example,
````
x = (import(), 0);
````
We mistakenly identified the result type of `import` as having a value, when it should be none. Basically, when the parent is a comma, it can't be a coercion (or that would have been the parent), so there is no coercion, so the result type is none. We had logic for this, but it wasn't in the proper central place where it would affect all the necessary things.
=> asm2wasm: fix import type detection of calls in comma operators

src/wasm/wasm-binary.cpp, test/polymorphic_stack.wast, test/polymorphic_stack.wast.from-wast, test/polymorphic_stack.wast.fromBinary, test/polymorphic_stack.wast.fromBinary.noDebugInfo, test/unit.wast.fromBinary, test/unit.wast.fromBinary.noDebugInfo
Emit proper wasm binaries for unreachable code. We support unreachability in our AST in ways that require emitting more "unreachable" nodes for wasm validation.
=> Polymophic stack support

src/passes/Inlining.cpp, test/passes/inlining.txt, test/passes/inlining.wast, test/unit.fromasm, test/unit.fromasm.clamp, test/unit.fromasm.imprecise
As their initial zero value may be depended on.
=> When inlining, we must zero out non-param locals

src/wasm-binary.h, src/wasm/wasm-binary.cpp, test/debugInfo.fromasm.clamp.map, test/debugInfo.fromasm.clamp.no-opts.map, test/debugInfo.fromasm.imprecise.map, test/debugInfo.fromasm.imprecise.no-opts.map, test/debugInfo.fromasm.map, test/debugInfo.fromasm.no-opts.map, test/example/c-api-unused-mem.txt
Instead of preallocating 5 bytes, emit the minimal bytes and move the code back.
The extra copying makes us a tiny bit slower to write (less than a quarter of a percent). But larger effect in code size than I thought, about 1% smaller. I guess it's because there are often small functions, and each got an extra 4 bytes earlier.
Fixes #1121.
=> Emit optimal-size LEBs in section/subsection/function body sizes

src/wasm-linker.cpp, test/dot_s/start_main0.wast, test/dot_s/start_main2.wast
More a cosmetic issue aiming at clean exports.
I must admit that I do not know if this change might have implications on other tooling. At least in my scenario, it doesn't cause any runtime issues / isn't dead code eliminated, and relieves the JS side from having a `_start` function that it actually doesn't ever call. Nonetheless, this might be an undesired change and is merely a nice-to-(not-)have on my side.
=> Do not export _start function

src/ast/effects.h, test/passes/simplify-locals-nostructure.txt, test/passes/simplify-locals-nostructure.wast
Found by fuzzing. Moving an implicit trap in a way that prevents a global side effect from happening causes noticeable changes and so should not be done. Local side effects (writing to locals, etc.) are fine of course.
=> Don't reorder an implicit trap with a global side effect

src/tools/execution-results.h, test/passes/fuzz-exec_O.txt
So side effects of memory writes persist, which is the same as when we run the code in a js vm, so we can directly compare the two when fuzzing.
=> Run execution results on the same instance

.gitignore, scripts/test/shared.py
This means you can do `rm -rf test/wasm-install` and have
it get redownloaded.
=> Move test/local-revision into test/wasm-install

build-js.sh
Besides preventing the usual compile time warnings ([1](https://travis-ci.org/AssemblyScript/binaryen.js#L3533)), this fixes an abort ([2](https://travis-ci.org/AssemblyScript/binaryen.js#L3566)) when calling `Module#emitAsmjs`, due to `missing function: _ZN4wasm26createI64ToI32LoweringPassEv`.
=> Updated build-js.sh with I64ToI32Lowering and SafeHeap passes

src/ast/branch-utils.h, src/ast_utils.h, src/passes/RemoveUnusedBrs.cpp, src/passes/SimplifyLocals.cpp, src/wasm-validator.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-validator.cpp
Also cleans up unnecessary validation stuff from when we differentiated reachable from unreachable breaks.
=> Followup to #1148: untaken=>unreachable

src/passes/OptimizeInstructions.cpp, src/passes/Print.cpp, src/wasm-binary.h, src/wasm.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, src/wasm/wasm-validator.cpp, src/wasm/wasm.cpp, test/signext.wast, test/signext.wast.from-wast, test/signext.wast.fromBinary, test/signext.wast.fromBinary.noDebugInfo
These are not atomic operations, but are added with the atomic operations to keep from having to define atomic versions of all the sign-extending loads (an atomic zero-extending load + signext operation can be used instead).
=> Add support for sign-extension operators from threading proposal

.travis.yml
Fixes #1161.
In popular OSS projects major parts of builds is usually triggered by pull requests. So I think it should be sufficient to disable build stage for pull requests and let them run only on master branch and release tags. This is IMO better than run them only periodically by cron.
WDYT?
/cc @kripken
=> Travis: Run build stage only for master and release tags

src/passes/ReReloop.cpp, src/shell-interface.h
Recent versions of clang turn on -Wdelete-non-virtual-dtor at our warning
level, which fires when deleting a non-final class that has virtual functions
but a non-virtual destructor. Pre-C++11 standard rule of thumb is to just always
have a virtual destructor if there are virtual functions, but C++11 final is
even better since it may allow for devirtualization optimizations.
=> Make several derived classes final

src/binaryen-c.cpp, src/binaryen-c.h
I'm wondering why these are not published in binaryen-c.h?
Looks like binaryen.js already uses those ([1](https://github.com/WebAssembly/binaryen/blob/master/src/js/binaryen.js-post.js#L771), [2](https://github.com/WebAssembly/binaryen/blob/4f58e1e666cff6f1e61d888279dba42d1be14251/build-js.sh#L146
)).
=> Add missing prototypes for globals in binaryen-c.h

src/binaryen-c.cpp, test/example/c-api-kitchen-sink.c, test/example/c-api-kitchen-sink.txt
Looks like `finalize` call is missing in `BinaryenCallIndirect`.
This may cause validation fail in the case when target and/or operands have the unreachable type.
```
[wasm-validator error in function $test] 1 != 2: function body type must match, if function returns, on
[i64] (call_indirect $return_i64
[unreachable] (unreachable)
)
(module
(type $0 (func (result i32)))
(type $return_i64 (func (result i64)))
(memory $0 0)
(func $test (type $0) (result i32)
(call_indirect $return_i64
(unreachable)
)
)
)
```
=> Add missing finalize() call

.travis.yml, scripts/test/shared.py
This PR proposes we default the waterfall tests to off instead of on. It keeps running it on travis of course.
The motivation is
* In general, I find that when I work locally, I almost always type `./check --no-test-waterfall`, and I think most people running the tests would do the same. It's a big download that is mostly not needed for local work.
* See [PR 1184](https://github.com/WebAssembly/binaryen/pull/1184#issuecomment-329430966) for some issues on running it.
=> Default waterfall testing to off

build-js.sh
Added missing symbols which have triggered following warnings during executing `build-js.sh`:
```
warning: unresolved symbol: _ZN4wasm10LocalGraph17computeInfluencesEv
warning: unresolved symbol: _ZN4wasm23createConstHoistingPassEv
warning: unresolved symbol: _ZN4wasm10LocalGraphC1EPNS_8FunctionEPNS_6ModuleE
```
=> Add missing objects to build-js.sh

src/tools/translate-to-fuzz.h, src/wasm/wasm-s-parser.cpp, test/passes/translate-to-fuzz.txt
Fixes two implicit fall through warnings which caused building to fail.
Closes #1194
=> remove implicit fallthroughs (#1194)

src/ast_utils.h, test/passes/remove-unused-brs.txt, test/passes/remove-unused-brs.wast
When we re-finalize a function body, we may have changed it from unreachable to none. That is bad if the function has a return value, as unreachable was ok but none is not. In that case, we must add an unreachable.
=> Fix re-finalize of toplevel code from unreachable to none

src/passes/ReorderLocals.cpp, src/wasm-builder.h, src/wasm.h, src/wasm/wasm.cpp
A new fix for the comments at the end of #1134 to replace #1159. This change cleans up the code by making localNames into a map that is simply the inverse of localIndices. This way, neither indices nor names are treated specially in the lookup tables.
=> Make localNames into a map

src/ast/type-updating.h, src/passes/DeadCodeElimination.cpp, test/passes/dce.txt, test/passes/dce.wast
We remove the node when dce kills code (turns it into an unreachable), but we didn't propagate that type upwards. The new unreachable may turn parents unreachable.
=> Fix dce bug with not updating the parent when turning a node unreachable

src/wasm-binary.h, src/wasm/wasm-binary.cpp
Use a set of the breaks we've seen, don't rescan blocks to see if they have breaks to them.
This makes wasm loading 25% faster, ignoring validation.
Side note: Validation is by far most of the time spent when loading wasm. Perhaps we should have a `--no-validation` option?
=> Optimize wasm reading

src/passes/OptimizeInstructions.cpp, test/passes/optimize-instructions.txt, test/passes/optimize-instructions.wast
Had a little logic error that the fuzzer found.
=> fix optimize-instructions handling of shifts by/of a zero

src/passes/OptimizeInstructions.cpp, test/passes/optimize-instructions.txt, test/passes/optimize-instructions.wast
`left` may not exist, need to return `curr->left` after that change.
45d88e3ef5f895b2fde77e3588f84d66e67bdd88
=> fix regression from 45d88e3ef5f895b2fde77e3588f84d66e67bdd88

scripts/test/support.py, src/passes/pass.cpp, src/tools/s2wasm.cpp, src/tools/wasm-as.cpp, src/tools/wasm-reduce.cpp, src/wasm-validator.h, src/wasm/wasm-validator.cpp
As suggested in #1204 
I may be missing something in how to use enums here - I  seem to need to cast to the enum type when I `or` two values. There's probably a better way, I think?
=> Refactor validator API to use enums

src/wasm-builder.h, test/passes/O3_inlining.txt, test/passes/O3_inlining.wast
We must call finalize, as the value may be unreachable.
Found by fuzzer.
=> fix wasm-builder set_global creation

src/passes/SimplifyLocals.cpp, test/passes/simplify-locals.txt, test/passes/simplify-locals.wast
When we create a `br_if` value, it is dangerous if we are moving code out of the `br_if`'s condition - the value executes before. See example in the comment added to the pass.
=> Fix simplify-locals fuzz bug

src/ast/LocalGraph.cpp, src/passes/SSAify.cpp, test/passes/ssa.txt, test/passes/ssa.wast
We failed to update the location of values as we moved them around, causing us to zero out the wrong thing in another place.
=> SSA fuzz fix

src/s2wasm.h, test/dot_s/debug.wast
.s files beginning like this:
.text
.file	"main.c"
.file	1 "stdio.h"
.file	2 "stdlib.h"
.file	3 "string.h"
are now parsed correctly.
=> Fixed parseFile() skipping every other line

src/ast_utils.h, src/passes/RemoveUnusedBrs.cpp, test/passes/remove-unused-brs.txt, test/passes/remove-unused-brs.wast
We had a hackish way of doing it, and can now just use the type system - `unreachable` type means we don't flow out.
=> Use the type system to check if something is flowed out of

src/ast/import-utils.h, src/passes/SafeHeap.cpp, src/tools/wasm-ctor-eval.cpp
Make getImport return the import (more consistent with other similar APIs) and fix some ctor-evalling handling of imports, which was incorrect - we need to create fake globals when importing globals, not later, which is too late for initialized globals from imports.
Minor stuff I had to do for the atomics fuzzing patch I'm working on, that I separated out.
=> Import utils cleanup

src/pass.h, src/tools/optimization-options.h, src/tools/wasm-opt.cpp
It would need a more careful design with a copy constructor. instead, just simplify the API to do the thing we need, which is run the passes.
See #1228.
=> Avoid returning a PassRunner just for OptimizationOptions

src/wasm/wasm-binary.cpp
By moving the addition outside of the vector's subscript operator it avoids the possibility for an out-of-bounds check raising an error/assertion, such as when compiled in Debug with MSVC.
=> Move pointer positioning outside of vector access operator

src/ast/ExpressionAnalyzer.cpp, src/ast/load-utils.h, src/passes/OptimizeInstructions.cpp
Running the fuzzer with valgrind noticed this. We don't set the `signed` field if it isn't relevant (like a full-size int load or a float load), and we were reading it in such a case, which is wrong.
=> Only look at the |signed| field of loads if it is relevant

src/tools/wasm-reduce.cpp
Before we had just a fixed 2 second timeout. Sometimes reduction needs more.
=> Add a timeout param to wasm-reduce

src/tools/wasm-ctor-eval.cpp
|passOptions| in wasm-ctor-eval.cpp causes  a compile failure, -Wunused-variable on the clang build.
=> Remove unused PassOptions from wasm-ctor-eval.cpp

src/passes/SafeHeap.cpp, test/passes/safe-heap.txt, test/passes/safe-heap.wast
That case wasn't tested. Added a test with the fix.
=> Fix safe-heap regression with handling of existing imports

src/ast_utils.h, src/wasm-traversal.h
And add a visitor which must override all its elements, so this never happens again.
If the visitors were virtual methods, they could be `= 0`. We use the CRTP pattern here instead, so it's at compile time, and it seems like there should be a way to get the compiler to error at compile time if a method isn't overridden (currently the PR aborts at runtime). Is there a way?
=> Fix atomics refinalization (we were missing some glue)

src/tools/translate-to-fuzz.h, test/passes/translate-to-fuzz.txt
I can't quite figure out #1240. Pushing various stuff to the bot, the error doesn't depend on the value at all, just the number of values. But it also depends on context somehow since other `pick()` lists are longer. And as mentioned in that issue, it's windows-only. So after several hours I am not much wiser than before.
However, as it happens I noticed that we should refactor the const creating code to improve it anyhow, to not special-case +-1, we can just put 0, since we already have code later that can perturb each value by +-1. And doing that works around the bug. So two birds with one stone I guess..?
=> Workaround gcc-7.2/windows issue

.travis.yml, appveyor.yml
As per #1237, and https://github.com/WebAssembly/waterfall/pull/260
=> Pin flake8 to specific version on travis

scripts/test/asm2wasm.py, src/asm2wasm.h, src/pass.h, src/passes/pass.cpp, src/tools/asm2wasm.cpp, src/tools/optimization-options.h, src/tools/wasm-as.cpp, src/tools/wasm-opt.cpp, src/wasm-printing.h, src/wasm-validator.h, src/wasm.h, src/wasm/wasm-validator.cpp
This enum describes which wasm features the IR is expected to include. The
validator should reject operations which require excluded features, and passes
should avoid producing IR which requires excluded features.
This makes it easier to catch possible errors in Binaryen producers (e.g.
emscripten). Asm2wasm has a flag to enable or disable atomics. Other
tools currently just accept all features (as, dis and opt are just for
inspecting or modifying existing modules, so it would be annoying to have to use
flags with those tools and I expect the risk of accidentally introducing
atomics to be low).
=> Add Features enum to IR

CMakeLists.txt, README.md, src/tools/wasm2asm.cpp
We were missing a try-catch for the parse error. See #1231
=> Print wasm2asm parsing errors

src/passes/pass.cpp, src/tools/asm2wasm.cpp, src/tools/s2wasm.cpp, src/tools/wasm-as.cpp, src/tools/wasm-merge.cpp, src/tools/wasm-opt.cpp, src/tools/wasm-shell.cpp, src/wasm/wasm-validator.cpp
This restricts validation output to validation errors in the API, leaving additional and possibly very longish printing of the entire module up to the respective tool.
=> Restrict validation output to just validation errors in the API

src/binaryen-c.cpp, src/binaryen-c.h
This fixes `BinaryenImportRef` being used for globals in the C-API, instead of using its own type.
Because the change doesn't functionally affect binaryen.js, the respective JS binaries haven't been updated.
This is part of multiple PRs as previously tracked in #1261.
=> Use 'BinaryenGlobalRef' for globals in binaryen-c

src/tools/wasm-reduce.cpp
So we were ignoring the quiet mode and had a lot of noise.
=> Fix wasm-reduce bug, the second validator param is the features, not the flags

src/binaryen-c.cpp
The tracing code for BinaryenAddGlobal references a `types` array that doesn't seem to exist. All other functions use just `type` directly.
Appears that `BinaryenAddGlobal` isn't part of any (tracing) test, btw.
=> Fixed use of undefined 'types' array in BinaryenAddGlobal tracing

src/tools/fuzzing.h, src/tools/wasm-opt.cpp
Adds `--fuzz-passes` to wasm-opt, which makes it pick random passes to run on the random wasm it generates, and sees if they break anything. Before I used some python to pick the passes, but doing this in wasm-opt is a lot faster (like an order of magnitude in afl-fuzz).
Amusingly, when fuzzing with this the map density passes 70%, leading to this afl-fuzz warning:
````
The fuzzer will flag high percentages [of map density] in red.
Chances are, you will never see that unless you're fuzzing
extremely hairy software (say, v8, perl, ffmpeg).
````
So I guess we're in good company? ;)
=> Fast pass fuzzing

src/wasm/wasm-validator.cpp, test/segment-overlap.wast, test/segment-overlap.wast.from-wast, test/segment-overlap.wast.fromBinary, test/segment-overlap.wast.fromBinary.noDebugInfo
Apparently it is ok to have wasms like this:
````
(module
(memory $0 10)
(data (i32.const 100) "\ff\ff\ff\ff\ff\ff\ff\ff") ;; overlaps with the next
(data (i32.const 104) "\00\00\00\00")
)
````
The first segment writes to 100-108, and the second to 104-108, so they overlap. Everything seems to support this: browsers, wabt, spec interpreter, all except for binaryen.
It seems odd that binaryen would add an assert like that for no reason - was this perhaps something that changed in wasm at some point? Or was it always ok?
This PR removes that assertion, so binaryen accepts such modules too.
=> Accept overlapping segments

src/ir/ExpressionManipulator.cpp, src/wasm-builder.h, test/passes/inlining.txt, test/passes/inlining.wast
We should preserve the forced explicit type if there is one, and not just infer it from the arms. this adds a builder method for makeIf that receives a type to apply to the if, and for blocks a method that makes a block from a list, also with a variant with a provided type.
Found by the fuzzer, this affected inlining which assumes types of copied code are identical to what they were before.
=> Fix if copying

src/ir/effects.h, src/passes/CodeFolding.cpp, test/passes/code-folding.txt, test/passes/code-folding.wast
When merging code paths leading to a function exit, we move the code to the outermost scope, so it can't have break targets, as it would no longer be able to reach them.
=> Fix a code-folding fuzz bug

scripts/test/shared.py, src/support/path.h, src/tools/wasm-reduce.cpp
wasm-reduce used to assume the build was in-tree and it did `bin/wasm-opt` etc. This PR make sit use BINARYEN_ROOT, which the test harness now ensures exists.
This should fix binaryen tests on http://clb.demon.fi:8112/#/ which builds out of tree. cc @juj
=> Fix wasm-reduce testing out of tree

src/passes/CodeFolding.cpp, test/passes/code-folding.txt, test/passes/code-folding.wast
Make sure we do not fold out code from blocks with a fallthrough value, and then since the parent blocks do not have such values, we can finalize them with their type as a concrete type should not vanish.
=> Code-folding fuzz fix

src/tools/fuzzing.h, src/wasm-interpreter.h, test/passes/fuzz-exec.txt, test/passes/fuzz-exec.wast, test/passes/translate-to-fuzz.txt
This fixes running the `precompute` pass on them.
=> support i*.extend* instructions in interpreter

src/ir/LocalGraph.cpp, src/ir/local-graph.h, src/passes/CMakeLists.txt, src/passes/MergeLocals.cpp, src/passes/pass.cpp, src/passes/passes.h, src/tools/fuzzing.h, src/tools/wasm-opt.cpp, test/passes/merge-locals.txt, test/passes/merge-locals.wast, test/passes/translate-to-fuzz.txt
This optimizes the situation described in #1331. Namely, when x is copied into y, then on subsequent gets of x we could use y instead, and vice versa, as their value is equal. Specifically, this seems to get rid of the definite overlap in the live ranges of x and y, as removing it allows coalesce-locals to merge them. The pass therefore does nothing if the live range of y ends there anyhow.
The danger here is that we may extend the live range so that it causes more conflicts with other things, so this is a heuristic, but I've tested it on every codebase I can find and it always produces a net win, even on one I saw a 0.4% reduction of code size, which surprised me.
This is a fairly slow pass, because it uses LocalGraph which isn't much optimized. This PR includes a minor optimization for …
=> merge-locals pass

src/tools/fuzzing.h
Otherwise we break on wabt, cretonne, etc.
=> Fuzzing: when not allowing atomics, don't emit the new extend instructions that arrive with them

src/passes/Metrics.cpp, src/passes/pass.cpp, src/passes/passes.h, src/wasm-binary.h, src/wasm/wasm-binary.cpp, test/passes/func-metrics.txt, test/passes/func-metrics.wast
The existing metrics pass emits everything together, this adds an option to emit function-specific metrics. Example output:
````
global
[funcs]        : 3       
[memory-data]  : 9       
[table-data]   : 3       
[total]        : 18      
const          : 3       
func: empty
[binary-bytes] : 3       
[total]        : 4       
[vars]         : 0       
nop            : 1       
func: small
[binary-bytes] : 9       
[total]        : 14      
[vars]         : 0       
block          : 1       
const          : 1       
drop           : 1       
nop            : 1       
return         : 1       
func: ifs
[binary-bytes] : 51      
[total]        : 76      
[vars]         : 1       
binary         : 1       
block          : 1       
const          : 12      
drop           : 6       
if …
```
=> Function metrics

README.md
s2wasm currently depends on the wasm32-unknown-unknown-elf triple.
Depend on it explicitly, rather than relying on it being the default.
=> Make the triple explicit in the llc command-line in the README.

src/passes/OptimizeInstructions.cpp, test/emcc_O2_hello_world.fromasm, test/emcc_O2_hello_world.fromasm.clamp, test/emcc_O2_hello_world.fromasm.imprecise, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.clamp, test/emcc_hello_world.fromasm.imprecise, test/memorygrowth.fromasm, test/memorygrowth.fromasm.clamp, test/memorygrowth.fromasm.imprecise, test/passes/optimize-instructions.txt, test/passes/optimize-instructions.wast
=> optimize out 0-x, a zero only used to negate an int, when possible

src/wasm-binary.h
I do not see any reason the `input` should be modified by the builder and as such this simplifies certain use cases (at least the ones I have).
Perhaps I have missed something and there is a good reason to keep it non-const.
=> Make input a const reference to WasmBinaryBuilder

src/passes/I64ToI32Lowering.cpp
Currently, whenever a global is used, wasm2asm fails with an assertion error here. While this PR doesn't implement anything, it allows the use of non-i64 globals that aren't lowered anyway.
=> Skip not applicable globals in I64ToI32Lowering

src/tools/fuzzing.h
I'm working on a [wrapper](https://github.com/pepyakin/binaryen-rs/pull/2/files#diff-ad14bd6cd9ed6a7d2e39bf9feeb2b93cR11) for a wasm-opt's `--translate-to-fuzz`. Putting fuzzer into a fuzzing process (im using libfuzzer) makes a great speed up!
This change will make things easier for me.
=> Add read data

src/ir/module-utils.h, src/passes/Metrics.cpp, test/passes/func-metrics.txt, test/passes/func-metrics.wast, test/passes/metrics.txt
This shows how much binary size each export is responsible for. For example, something like
```
(module
(export "a" (func $func_a))
(export "b" (func $func_b))
(func $func_a
(call $func_c)
)
(func $func_b
;; small
)
(func $func_c
;; very big
)
)
```
will report something like
```
export: a (func_a)
[removable-bytes-without-it]: (very big number)      
export: b (func_b)
[removable-bytes-without-it]: (small number)      
```
since `a` keeps alive `c` which is very big.
In practice this copies the module, removes the export, runs the optimizer, and sees how big the result is, so its size estimates include things like new inlining or function ordering opportunities that arise thanks to removing functions. In other words, the savings may be larger than just removing all the reachable code and …
=> Show the binary bytes we can remove without each export, in --func-metrics

src/support/threads.cpp, src/support/threads.h
Be careful when creating the pool (more than one thread may try to) and don't create it just to check if its running in the thread constructor assertions.
See #1376
=> Threading fixes

CMakeLists.txt, src/s2wasm.h, src/tools/wasm2asm.cpp
This addresses most of the easy cases in #1385.  I think my line numbers for some of the signed/unsigned mismatch warnings were off, so I didn't try addressing those.  The signed/unsigned warnings were also drowned in the noise from other warnings triggered from headers, so ideally these commits will make things a little less noisy.
=> address some MSVC warnings

src/wasm/wasm-binary.cpp
To keep, wasm output clean, we will not emit sourceMappingURL custom section, when empty source map URL is specified for the WasmBinaryWriter. Affected tools are wasm-as and s2wasm. (The URL can be specified via 'SourceMap: ' HTTP header)
=> Don't write sourceMappingURL section if URL is empty.

src/support/threads.cpp, src/support/threads.h
It doesn't need to be static and to go through the global unique_ptr.
=> Simplify ThreadPool::isRunning

src/tools/asm2wasm.cpp, src/tools/s2wasm.cpp, src/wasm/wasm-s-parser.cpp
These instances may simply be caught by reference instead.
Closes #1399.
=> Fix -Wcatch-value from GCC 8

src/s2wasm.h, src/support/command-line.h, src/support/file.cpp, src/support/file.h, src/tools/asm2wasm.cpp, src/tools/optimization-options.h, src/tools/s2wasm.cpp, src/tools/wasm-as.cpp, src/tools/wasm-ctor-eval.cpp, src/tools/wasm-dis.cpp, src/tools/wasm-emscripten-finalize.cpp, src/tools/wasm-link-metadata.cpp, src/tools/wasm-merge.cpp, src/tools/wasm-metadce.cpp, src/tools/wasm-opt.cpp, src/tools/wasm2asm.cpp
The `&` on the type is the proper convention.
=> 'std::string &' => 'std::string& '

src/ir/ExpressionAnalyzer.cpp, test/passes/code-folding.txt, test/passes/code-folding.wast
It needs to be taken into account in comparisons and hashing. Found by the fuzzer, an optimization thought a load could be folded with an atomic load that was otherwise the same.
=> Note isAtomic in loads and stores

src/asmjs/shared-constants.cpp, src/asmjs/shared-constants.h, src/wasm2asm.h, test/grow_memory.2asm.js, test/grow_memory.wast, test/grow_memory.wast.from-wast, test/grow_memory.wast.fromBinary, test/grow_memory.wast.fromBinary.noDebugInfo
Emits "almost asm" if grow_memory, current_memory or export memory is used.
=> Update wasm2asm to generate "almost asm" if grow_memory is used

.travis.yml
Ubuntu has apparently deleted qemu-user-static packages for Zesty…
The script uses packages from Artful since 0.7.0.
=> Travis: Fix failures, update alpine-chroot-install to 0.7.0

src/tools/fuzzing.h
Now that we have hang prevention it's safe and useful to test infinite loops.
=> Remove recursion-avoiding code in fuzzer

src/passes/SafeHeap.cpp, test/passes/safe-heap.txt
The check ignored the number of bytes in the load/store, so we were comparing the pointer + 4 (or 8 for i64) to the top of memory, instead of the pointer + the number of bytes.
This happened to fail on a malloc I'm experimenting with, which apparently unlike dmlalloc will put things very close to the top of memory without extra padding.
=> Fix safe-heap bounds checking

check.py, scripts/test/wasm2asm.py
Many places assume that test/blah is valid, but that's only valid if
you're executing scripts from the binaryen source directory.  The
binaryen_test option is more general, and enables out-of-tree testing,
so that's what we should be using instead.
=> adjust test scripts to cope with out-of-tree builds

src/wasm2asm.h, test/float-ops.2asm.js, test/wasm2asm/float-ops.wast
Running `wasm2asm` on files in `test/` revealed some errors in handling float operations.  This pull request is a first attempt at handling them.  More complex operations, like conversion, reinterpretation, and copysign, are left for later.
=> better handling of float ops in wasm2asm

src/passes/DuplicateFunctionElimination.cpp
Hash results may differ between runs, as they can depend on pointers. In remove-duplicate-functions, that shouldn't matter, except that we only considered the first item in each hash group vs the others (to avoid `O(N^2)`), which is fine except for hash collisions (collisions mean 2 groups are merged into one, and considering just the first item vs the rest we miss out on the other duplicates in that single group). And hash collisions do occur (rarely) in practice. Instead, consider all comparisons in each hash group, which should be fine unless we have large amounts of hash collisions.
=> Determinism fix

scripts/test/wasm2asm.py, src/wasm2asm.h, test/float-ops.2asm.js
We don't have spidermonkey on CI, so we don't run the asm.js compilation validation checks, and we had some breakage there:
* If we don't emit "use asm", we shouldn't check for it (like in memory growth).
* We got several f32 operations wrong.
I see some more failures after this, but don't have time to look into them atm.
We should also try to figure out a better testing solution here. Perhaps we can find a way to get the spidermonkey shell running on CI, for example.
=> wasm2asm fixes

src/ir/local-graph.h, src/passes/SSAify.cpp, test/passes/ssa.txt, test/passes/ssa.wast
We can't assume that even if all set locations assign to the same local that it is ok to read that local, as locals may also be written elsewhere.
This basically just removes an optimization that was not valid.
=> Fix an ssa bug

CMakeLists.txt
[CMAKE_SYSTEM_PROCESSOR](https://cmake.org/cmake/help/v3.1/variable/CMAKE_SYSTEM_PROCESSOR.html) already exposes target architecture. No need to call [file(1)](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/file.html) utility on the compiler output.
=> Unbreak build on BSDs

README.md
http://webassembly.org/docs/text-format/ says:
> The recommended file extension for WebAssembly code in textual format
> is .wat.
> Note: The .wast format understood by some of the listed tools is a
> superset of the .wat format that is intended for writing test scripts.
=> Say "wat" instead of "wast".

src/shell-interface.h, src/tools/execution-results.h
We need to issue a proper trap when the offset is invalid, not just assert it is valid.
We also had some problems with receiving that trap in the fuzz-exec code.
=> afl-fuzz fixes for table/memory instantiation

src/asm2wasm.h
Limit the amount of asm2wasm warnings on arguments added/removed in flexible argument handling (e.g. in Python there can be many thousands of such warnings, flooding the output...)
=> asm2wasm warning improvement

src/cfg/liveness-traversal.h
An action can be either a get, a set, or an other, and we assumed a non-get is a set (caught by valgrind).
=> Fix liveness-traversal

build-js.sh
Did not include the builds because of `warning: unresolved symbol: llvm_nearbyint_f64` with 1.37.35 as mentioned in https://github.com/kripken/emscripten/pull/6298#issuecomment-372994241
=> Include FuncCastEmulation pass in build-js.sh

check.py, scripts/test/asm2wasm.py, scripts/test/lld.py, scripts/test/s2wasm.py, scripts/test/shared.py, scripts/test/wasm2asm.py
Failing test cases often start out with:
```
incorrect output, diff:
--- expected
+++ actual
```
which makes it difficult to figure out where the expected output might
live.  That information can be derived from examining the tests, of
course, but it'd be much nicer if it were provided in the diff to see
straightaway.
We do this by introducing a new check, one which takes a filename of
expected output, which then enables us to display the failing file,
e.g.:
```
incorrect output, diff:
--- /home/froydnj/src/binaryen.git/test/passes/code-folding.txt
+++ actual
```
which is arguably nicer.  Having this new check also enables reducing
some boilerplate open(...).read() calls in various places.
There are still a few places using fail_if_not_identical, usually
because `.strip()` is used on the …
=> include the filename in erroneous diff output where possible

src/passes/I64ToI32Lowering.cpp, test/address.2asm.js, test/binaryen.js/emit_asmjs.js.txt, test/br_table_temp.2asm.js, test/empty_imported_table.2asm.js, test/empty_table.2asm.js, test/float-ops.2asm.js, test/forward.2asm.js, test/grow_memory.2asm.js, test/hello_world.2asm.js, test/i32.2asm.js, test/i64-add-sub.2asm.js, test/i64-lowering.2asm.js, test/unary-ops.2asm.js, test/wasm2asm.asserts.js, test/wasm2asm.traps.js
We were using the global to return 64-bit values from functions, but
said global wasn't actually present in the IR.  This omission caused the
generated code to fail validation.
=> add the highbits global to the IR

auto_update_tests.py
After #1450, it looks like `auto_update_tests.py` was not changed to
account for the new, updated expectations filename.
=> fix auto_update_tests.py for wasm-opt

src/support/CMakeLists.txt, src/support/path.cpp, src/support/path.h, src/tools/wasm-reduce.cpp
Store the bin/ dir so that all users of the API can use it by the standard calls, even if it was modified by user input. This moves the logic out of just being done in a specific way in wasm-reduce.cpp.
=> Refactor Path utils

src/s2wasm.h, test/dot_s/alias.s
llvm-mirror/llvm@9273bb3([Phabricator](https://reviews.llvm.org/D44256)) changed alias assignment syntax from
```
x = y
```
to
```
.set x, y
```
This patch reflects the change.
=> Use .set instead of = for aliases

src/wasm-binary.h, src/wasm.h, src/wasm/wasm-binary.cpp, src/wasm/wasm.cpp
When creating blocks in binary format parsing, we know if a block has a break to it - use that to avoid rescanning blocks for unreachability purposes. This should make block creation linear instead of quadratic, and should also make all of binary reading linear (unless I forgot something).
This makes the testcase from #1493 (which has many blocks) 10x faster to load.
=> Linearize block creation in binary reading

check.py, src/pass.h, src/tools/asm2wasm.cpp, src/tools/optimization-options.h, src/tools/wasm-opt.cpp
Disabling validation makes loading large wasm files more than twice as fast.
Validation is still on by default, like I believe it is in llvm's commandline tools as well.
=> Add a --no-validation option to the commandline tools

src/literal.h, src/wasm-interpreter.h, src/wasm/literal.cpp
* Move more logic to the Literal class. We now leave all the work to there, except for handling traps.
* Avoid switching on the type, then the opcode, then Literal method usually switches on the type again - instead, do one big switch for the opcodes (then the Literal method is unchanged) which is shorter and clearer, and avoids that first switching.
=> Refactor interpreter

.gitattributes
Otherwise `git grep` is rendered rather useless.
I'm not sure what the `-test` that was in here previously
was for but it doesn't mark something as binary which I
imagine was the intention.
=> Mark prebuilt js files as binary

src/passes/Precompute.cpp, test/passes/precompute-propagate.txt, test/passes/precompute-propagate.wast, test/wasm-only.fromasm, test/wasm-only.fromasm.clamp
Propagate constants through a `tee_local`. Found by [Souper](https://github.com/google/souper/issues/323#issuecomment-384165785). Details in patch comments - basically we didn't differentiate precomputing a value and an expression.
=> Improve precompute-propagate

src/passes/Precompute.cpp, test/passes/precompute-propagate.txt, test/passes/precompute-propagate.wast
One pass may remove code that includes a `tee` which then makes more optimization possible. Found by the Souper investigations.
=> precompute-propagate may benefit from multiple passes

src/tools/fuzzing.h
Hello,
I've developed a [cargo-fuzz WebAssembly fuzz target for cretonne](https://github.com/cretonne/cretonne/pull/306) that indirectly calls the [binaryen-rs](https://github.com/pepyakin/binaryen-rs) translateToFuzz function. Because cretonne does not support post-MVP WebAssembly functionality like atomics yet, I'd like to make generation of atomics optional in the binaryen translate-to-fuzz functionality. Then, if all goes well I plan to update the [corresponding binaryen-rs translateToFuzz PR](https://github.com/pepyakin/binaryen-rs/pull/4) to use the binaryen modification implemented here.
I'm not sure if this is the best way to implement this change binaryen, but I figured it would be best to supply a patch for reference. When you have a moment could you take a look and let me know …
=> Make generating atomics optional in translate-to-fuzz

src/passes/SimplifyLocals.cpp, src/passes/pass.cpp, src/passes/passes.h, test/passes/converge_O3_metrics.bin.txt, test/passes/simplify-locals-nonesting.txt, test/passes/simplify-locals-nonesting.wast
Add a version of simplify-locals which does not create nesting. This keeps the IR flat (in the sense of --flatten).
Also refactor simpify-locals to be a template, so the various modes are all template parameters.
=> --simplify-locals-nonesting

auto_update_tests.py, check.py
Tested with:
./auto_update_tests.py  --binaryen-bin=../binaryen-out/install/bin/
./check.py  --binaryen-bin=../binaryen-out/install/bin/
=> A couple of fixes for out-of-tree builds

src/ir/abstract.h, src/passes/CoalesceLocals.cpp, src/passes/OptimizeInstructions.cpp, src/passes/Precompute.cpp, src/passes/Print.cpp, src/passes/RemoveUnusedBrs.cpp, src/wasm/wasm-binary.cpp, src/wasm/wasm-validator.cpp
Not super important, but this fixes the warnings I've seen when compiling the `binaryen` target in Visual Studio, except
`wasm-interpreter.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library`
=> Fix MSVC warnings when compiling the binaryen target

src/passes/I64ToI32Lowering.cpp, src/wasm2asm.h, test/wasm2asm/reinterpret.2asm.js, test/wasm2asm/reinterpret.wast
As mentioned in #1458 a naive implementation of these instructions is to round
trip the value through address 0 in linear memory. Also pointed out in #1458
this isn't necessarily valid for all languages. For now, though, languages like
Rust, C, and C++ would likely be horribly broken if valid data could be stored
at low addresses, so this commit goes ahead and adds an implementation of the
reinterpretation instructions by traveling data through address 0. This will
likely need an update if a language comes a long which can validly store data in
the first 8 bytes of linear memory, but it seems like that won't happen in the
near future.
Closes #1458
=> wasm2asm: Implement reinterpretation instructions

src/passes/Print.cpp, test/wasm2asm/i64-rotate.2asm.js
Like this:
```
(block $x
..
) ;; end block $x
```
Also fix some current breakage on master.
=> In full-printing mode, print comments for control flow endings, to help readability

build-js.sh, src/passes/CMakeLists.txt, src/passes/RemoveCopysign.cpp, src/passes/pass.cpp, src/passes/passes.h, src/wasm2asm.h, test/passes/remove-copysign.txt, test/passes/remove-copysign.wast, test/wasm2asm/float-ops.2asm.js, test/wasm2asm/float-ops.wast, test/wasm2asm/i64-rotate.2asm.js
This commit implements the `copysign` instruction for the wasm2asm binary. The
implementation here is a new pass which wholesale replaces `copysign`
instructions with the equivalent bit ops and reinterpretation instructions. It's
intended that this matches Emscripten's implementation of lowering here.
=> wasm2asm: Implement f32/f64.copysign

src/pass.h, src/passes/Print.cpp, src/wasm-printing.h
1. make the iostream overrides receive a reference, not a pointer (i.e., like e.g. LLVM IR printing works, and avoiding overriding printing of pointer addresses which is sort of odd)
2. move more code out of headers, especially unrelated headers.
=> Clean up printing code:

src/passes/SimplifyLocals.cpp, test/passes/simplify-locals.txt, test/passes/simplify-locals.wast
Don't skip through flowing tee values, just drop the current outermost which we find is redundant. the child tees may still be necessary.
=> Fix optimizing equivalent locals bug introduced in #1540

auto_update_tests.py, check.py, scripts/__init__.py, scripts/clean_c_api_trace.py, scripts/fuzz_passes.py, scripts/fuzz_passes_wast.py, scripts/fuzz_relooper.py, scripts/spidermonkify.py, scripts/storage.py, scripts/test/__init__.py, scripts/test/asm2wasm.py, scripts/test/generate_lld_tests.py, scripts/test/lld.py, scripts/test/s2wasm.py, scripts/test/shared.py, scripts/test/support.py, scripts/test/wasm2asm.py, test/__init__.py, test/llvm_autogenerated/llvm-to-s.py
Remove executable bit and #! from scripts that don't have
entry point.
Add missing licence test.
Move arg parsing into a function.
Remove legacy --only_prepare (with underscrore) argument.
=> Cleanup scripts in scripts/test

src/tools/asm2wasm.cpp
Browsers don't really support it yet, but right now we silently wrap them to a signed integer which is confusing.
=> Allow --total-memory to be greater than a signed int32

src/emscripten-optimizer/istring.h, src/wasm/wasm-validator.cpp, test/example/c-api-kitchen-sink.c, test/example/c-api-kitchen-sink.txt
On the testcase from https://github.com/tweag/asterius/issues/19#issuecomment-393052653 this makes us almost 3x faster, and use 25% less memory.
The main improvement here is to simplify and optimize the data structures the validator uses to validate br targets: use unordered maps, and use one less of them. Also some speedups from using that map more effectively (use of iterators to avoid multiple lookups).
Also move the duplicate-node checks to the internal IR validation section, which makes more sense anyhow (it's not wasm validation, it's internal IR validation, which like the check for stale internal types, we do only if debugging).
=> Optimize validation of many nested blocks

src/tools/wasm-emscripten-finalize.cpp
This brings this tool into parity with the existing s2wasm
=> Add -g/--debuginfo flag to wasm-emscripten-finalize

src/wasm/wasm-emscripten.cpp
We ran into an issue recently where wasm-emscripten-finalize
was being passed input without any debug names and this is not
currently supported.
=> Ensure import and function names match during fixInvokeFunctionNames

src/wasm/wasm-emscripten.cpp
This check is supposed to check if rename is needed so it
need to compare to the original.
=> Fix check in fixInvokeFunctionNames

build-js.sh
To make sure we never regress it. Also add a currently missing file.
Fixes #1599
=> Build js files with errors on undefined symbols

check.py, src/wasm-binary.h, src/wasm/wasm-binary.cpp
This separates out the WasmBinaryWriter parts that do stack writing into a separate class, StackWriter. Previously the WasmBinaryWriter did both the general writing and the stack stuff, and the stack stuff has global state, which it manually cleaned up etc. - seems nicer to have it as a separate class, a class focused on just that one thing.
Should be no functional changes in this PR.
Also add a timeout to the wasm-reduce test, which happened to fail on one of the commits here. It was running slower on that commit for some reason, could have been random - I verified that general wasm writing speed is unaffected by this PR. (But I added the timeout to prevent future random timeouts.)
=> Refactor stack writing code into a new StackWriter class

src/wasm-interpreter.h
The `arguments` is read only and therefore could be const. The immediate benefit is callers do not need to define it as a local variable (see ` Literal callExport(Name name)`).
=> Mark arguments const in callExport

src/asm2wasm.h, src/pass.h, src/wasm-module-building.h
The problem this fixes is that we made precompute look at globals in #1622, while asm2wasm was creating globals while adding functions and optimizing them - which could race. This was caught by threadSanitizer (with low frequency, so we missed it on the initial landing).
The underlying issue is that function-parallel passes should be able to read global state, just not modify it, and not read other functions' contents (which is why the Call node has a name, not a pointer to a function). This PR clarifies that in the docs, and fixes asm2wasm by not handling function bodies in parallel to creating globals.
=> Clarify what function-parallel passes can do, and fix an asm2wasm bug

check.py, src/parsing.h, test/passes/vacuum.wast, test/passes/vacuum_ignore-implicit-traps.wast, test/validator/invalid_number.wast
Currently the wast reader fails to read invalid values when using Visual Studio.
This PR changes the behaviour to match the GCC/Clang ones.
Maybe a test could be interesting ?
=> Fix read out of range numbers in text mode when using Visual Studio

src/wasm-binary.h, src/wasm/wasm-binary.cpp, test/binaryen.js/sourcemap.js.txt, test/debugInfo.fromasm.clamp.map, test/debugInfo.fromasm.clamp.no-opts.map, test/debugInfo.fromasm.imprecise.map, test/debugInfo.fromasm.imprecise.no-opts.map, test/debugInfo.fromasm.map, test/debugInfo.fromasm.no-opts.map, test/debugInfo.fromasm.read-written
Fixes #1591.
During fixup of the section and function sizes LEBs, the offsets needs to be adjusted by amount of moved bytes.
(Addresses regression after #1128)
=> Fix source map entries offset when LEB is compressed.

CMakeLists.txt, src/passes/CMakeLists.txt
If someone wishes to build binaryen as part of their cmake custom compiler project, one potential solution is to add the project via git submodule and utilize the library's CMakeLists.txt (e.g. binaryen/CMakeLists.txt) by using `add_subdirectory(path/to/binaryen)`. However, this only works if the library utilizes PROJECT_SOURCE_DIR instead of CMAKE_SOURCE_DIR because the former refers to the last `project(name)` path and the later is the top-most source. In this case, the consumer of binaryen.
=> switch from CMAKE_SOURCE_DIR to PROJECT_SOURCE_DIR to support add_subdirectory(binaryen)

src/pass.h, src/tools/wasm-emscripten-finalize.cpp, src/wasm/wasm-emscripten.cpp
This ensures that 64-bit values are correctly handled on the
JS boundary.
With this change the `other.test_sixtyfour_bit_return_value` emscripten test
now works with the wasm backend.  I guess this is the only test which covers
this feature, which suggests maybe it should move to core?
=> Run legalize-js-interface during wasm-emscripten-finalize

auto_update_tests.py, check.py
on MacOS with gcc-8 the equals sign `-rpath=` is invalid. Best I can tell a comma can be used instead `-rpath,` more cross-platform, but only Travis will tell us 👍 
I think this fixes #1185 provided you install _real_ GCC (Mac has clang pretend to be gcc) and provide it `CC=gcc-8 CXX=g++-8 ./check.py`. If you can spare a few minutes to test @pepyakin to confirm?
=> use comma for -rpath instead of equals sign to fix MacOS

src/passes/LegalizeJSInterface.cpp, test/i64-setTempRet0.fromasm.clamp.no-opts, test/i64-setTempRet0.fromasm.imprecise.no-opts, test/i64-setTempRet0.fromasm.no-opts, test/lld/duplicate_imports.wast.out, test/wasm-only.fromasm.clamp.no-opts, test/wasm-only.fromasm.imprecise.no-opts, test/wasm-only.fromasm.no-opts
This pass was replacing all the uses of certain imports but
wasn't bothering to delete the old ones.
=> Remove replaced imports in LegalizeJSInterface

check.py, src/tools/wasm-merge.cpp, src/wasm-binary.h, src/wasm/wasm-binary.cpp, src/wasm/wasm.cpp
The dylink section must be first, per the spec (to make it easy to parse by loaders). We used to emit all user sections at the end, which was incorrect, so reading-writing a dynamic library broke it.
=> Fix read-write of dylink section

src/wasm/wasm-binary.cpp
The issue is that WasmBinaryBuilder::readSourceMapHeader's findField can match some well sequenced random set of chars, e.g. `"1ma-p_pingstest"`. This patch is attempt to address it.
=> Fix findField

src/wasm/wasm-emscripten.cpp
We're about to rewrite both names anyway.
This fixes LLVM's c++ invokes, which get escaped to not match as of
PR #1646
=> Remove assert that import names match

src/ir/ExpressionAnalyzer.cpp, src/literal.h, src/passes/Precompute.cpp, src/tools/execution-results.h, src/tools/wasm-shell.cpp, src/wasm/literal.cpp, test/passes/rse.txt, test/passes/rse.wast
The change means that nan values will be compared bitwise when writing `A == B`, and so the float rule of a nan is different from itself would not apply.
I think this is a safer default. In particular this PR fixes a fuzz bug in the rse pass, which placed Literals in a hash table, and due to nan != nan, an infinite loop... Also, looks like we really want a bitwise comparison pretty much everywhere anyhow, as can be seen in the diff here. Really the single place we need a floaty comparison is in the intepreter where we implement f32.eq etc., and there the code was already using the proper code path anyhow.
=> Change the Literal class's operator== to be bitwise

src/wasm2js.h, test/wasm2js/nested-selects.2asm.js, test/wasm2js/nested-selects.wast
In wasmjs, the nested selects are trying to use the same temporary locals. The patch reserves temporaries "at right time" to avoid overriding the values.
=> [wasmjs] Fix nested selects

src/wasm2js.h, test/wasm2js/base64.2asm.js, test/wasm2js/base64.wast
The `static std::string base64Encode(std::vector<char> &data) {` uses signed char in input data. The `((int)data[0])` converts it the signed int, making '\xFF' char into -1. The patch fixes casting.
=> [wasm2js] Fix base64 encoding

src/wasm/wasm-s-parser.cpp
We need to check not to read past the length of the string.
From #1665
=> Fix parsing of memory attributes in s-expression parser

src/passes/Inlining.cpp, test/passes/inlining-optimizing_optimize-level=3.txt
We noted that internal calls were not lightweight, but forgot calls to imports.
I noticed this while unifying calls and call_imports in #1649
=> Note that calls to imports are not lightweight in inlining pass

CHANGELOG.md, src/binaryen-c.cpp, src/binaryen-c.h, src/js/binaryen.js-post.js, test/binaryen.js/kitchen-sink.js, test/binaryen.js/kitchen-sink.js.txt, test/example/c-api-kitchen-sink.c, test/example/c-api-kitchen-sink.txt
Mirrors the API of `BinaryenSetMemory` for `BinaryenSetFunctionTable`, allowing to set function tables that can be grown dynamically. Technically a breaking change that can be worked around in the JS-API by checking whether the first parameter is a number, but didn't do that because the API just broke anyway in #1678.
Fixes #1683
=>  Add initial/maximum table size parameters to C/JS API

src/passes/SafeHeap.cpp, src/wasm/wasm-validator.cpp, test/passes/safe-heap.txt
SafeHeap was emitting them, but it looks like they are invalid according to the wasm-threads spec.
Fixes https://github.com/kripken/emscripten/issues/7208
=> No atomic float operations

.gitignore, src/binaryen-c.cpp, src/binaryen-c.h, src/js/binaryen.js-post.js, test/binaryen.js/kitchen-sink.js.txt, test/example/c-api-kitchen-sink.c, test/example/c-api-kitchen-sink.txt, test/example/c-api-relooper-unreachable-if.cpp, test/example/c-api-unused-mem.cpp, test/example/relooper-fuzz.c, test/example/relooper-fuzz1.c
New argument `bool shared` added to `BinaryenAddMemoryImport` and `BinaryenSetMemory`.  Default value is `false`. WASM memory will be set to shared if this argument is true.
JS wrapper updated accordingly.
<strike>New argument `BinaryenIndex sharedMemoryMax` added to `BinaryenAddMemoryImport`.
if `sharedMemoryMax > 0 ` imported memory will be declared as shared and
initial and max memory will set to `sharedMemoryMax`. Default value is `0`.</strike>
Closes #1679
=> Shared memory support for add memory import and set memory functions.

src/wasm/wasm-validator.cpp
After that PR, we errored on them.
Noticed by the fuzzer.
=> Properly handle unreachable atomic operations, fixes a regression from #1693

src/tools/wasm-ctor-eval.cpp
Not being able to evaluate a ctor is different to that ctor
being absent.  This is masked a bug in emscripten where we
were spelling the names of the ctors wrong on the command line.
See https://github.com/kripken/emscripten/pull/7458
=> wasm-ctor-eval: Hard error if requested ctor does not exist

src/ir/effects.h, src/passes/MinifyImportsAndExports.cpp, src/passes/OptimizeInstructions.cpp, test/passes/optimize-instructions.txt, test/passes/optimize-instructions.wast
We need to verify that the reordering is valid if there are side effects.
Original bug report: https://groups.google.com/forum/?nomobile=true#!topic/emscripten-discuss/HIlGf8o2Ato
=> Fix a bug with (add (sub 0 X) Y) => (sub Y X)

src/dataflow/graph.h, src/passes/DataFlowOpts.cpp, test/passes/flatten_dfo_O3.txt, test/passes/flatten_dfo_O3.wast
We create some fake nodes for internal use, and were looking at one by mistake. This fixes that by
* Creating a non-ambiguous fake node, a call (which represents an unknown value properly, unlike a zero which we had before).
* Make DFO not rely on those values, if it knows a node is constant, apply those constant values.
=> Fix a DataFlowOpts bug

src/passes/MergeBlocks.cpp, test/passes/merge-blocks.txt, test/passes/remove-unused-names_merge-blocks.txt, test/passes/remove-unused-names_merge-blocks.wast
If a block has code after an unreachable element, it makes merging to an outer block tricky - the child block may be unreachable, but the parent have a return type,
```
(block (result i32)
..
(block
(unreachable)
(nop)
)
)
```
It's ok to end an unreachable block with a nop, but not a typed one.
To avoid this, if a child block has dce-able code, just ignore it.
=> Fix a merge-blocks fuzz bug

check.py, src/tools/fuzzing.h, test/passes/translate-to-fuzz.txt
* Recombine function pieces after randomly generating them, by creating copies and moving them around. This gives a realistic probability to seeing duplicate expressions, which some optimizations look for, which otherwise the fuzzer would have almost never reached.
* Mutate function pieces after recombination, giving not only perfect duplicates but also near-duplicates.
These operations take into account the type, but not the nesting and uniqueness of labels, so we fix that up afterwards (when something is broken, we replace it with something trivial).
=> Better fuzzing

src/emscripten-optimizer/simple_ast.h, src/mixed_arena.h, src/wasm/wasm-s-parser.cpp
Necessary for simd, as we add a type with alignment >8. We were just broken on that before this PR.
=> Fix alignment in MixedAllocator

src/ir/utils.h, test/passes/code-folding.txt, test/passes/precompute.txt, test/passes/remove-unused-brs.txt, test/passes/remove-unused-brs.wast, test/wasm2js/br.2asm.js
Handle a corner case in ReFinalize, which incrementally re-types code after changes. The problem is that if we need to figure out the type of a block, we look to the last element flowing out, or to breaks with values. If there is no such last element, and the breaks are not taken - they have unreachable values - then they don't tell us the block's proper type. We asserted that in such a case the block still had a type, and didn't handle this.
To fix it, we could look on the parent to see what type would fit. However, it seem simpler to just remove untaken breaks/switches as part of ReFinalization - they carry no useful info anyhow. After removing them, if the block has no other signal of a concrete type, it can just be unreachable.
This bug existed for at least 1.5 years - I didn't look …
=> ReFinalize fix

src/wasm/wasm-binary.cpp
`finalize()` will do it properly a few lines later.
=> Clean up unnecessary type setting in binary format loading

src/passes/Print.cpp
`strpbrk` segfaults when `name.str` is nullptr, so check first.
=> Avoid segfault when printing null name

src/tools/wasm-emscripten-finalize.cpp, src/wasm-emscripten.h, src/wasm/wasm-emscripten.cpp
In this case we won't want generate any of the normal memory
helper functions (they come from the main module).
=> wasm-emscripten-finalize: Initial support for handling shared libraries

src/asm2wasm.h, src/passes/MergeBlocks.cpp, test/emcc_O2_hello_world.fromasm, test/emcc_O2_hello_world.fromasm.clamp, test/emcc_O2_hello_world.fromasm.imprecise, test/emcc_hello_world.fromasm, test/emcc_hello_world.fromasm.clamp, test/emcc_hello_world.fromasm.imprecise, test/memorygrowth.fromasm, test/memorygrowth.fromasm.clamp, test/memorygrowth.fromasm.imprecise, test/passes/converge_O3_metrics.bin.txt, test/passes/inlining-optimizing_optimize-level=3.txt, test/passes/merge-blocks.txt, test/passes/merge-blocks.wast, test/unit.fromasm, test/unit.fromasm.clamp, test/unit.fromasm.imprecise
If an if is enclosed in a block which is only used to exit one arm, move it into that arm, so it can be better optimized. Similar to what we did for loops in #1736.
=> Optimize an if exit block into an if arm

src/tools/wasm-reduce.cpp
I found this helpful to reduce a testcase that had a huge switch. This tries to reduce by replacing targets with the default, and by shrinking the list of targets.
=> wasm-reduce: reduce switch targets

src/tools/wasm-opt.cpp
This would be pretty useful for compilers which don't support atomics yet, and would partially solve #1676.
=> wasm-opt: Add an option to prevent generation of atomic opcodes

src/passes/LegalizeJSInterface.cpp, test/i64-setTempRet0.fromasm, test/i64-setTempRet0.fromasm.clamp, test/i64-setTempRet0.fromasm.clamp.no-opts, test/i64-setTempRet0.fromasm.imprecise, test/i64-setTempRet0.fromasm.imprecise.no-opts, test/i64-setTempRet0.fromasm.no-opts, test/passes/legalize-js-interface.txt, test/threads.wasm-only.fromasm, test/threads.wasm-only.fromasm.clamp, test/threads.wasm-only.fromasm.clamp.no-opts, test/threads.wasm-only.fromasm.imprecise, test/threads.wasm-only.fromasm.imprecise.no-opts, test/threads.wasm-only.fromasm.no-opts, test/wasm-only.fromasm, test/wasm-only.fromasm.clamp, test/wasm-only.fromasm.clamp.no-opts, test/wasm-only.fromasm.imprecise, test/wasm-only.fromasm.imprecise.no-opts, test/wasm-only.fromasm.no-opts
Its simpler if we always import these functions from
the embedder rather then synthesizing them various
placed.
This is part of a 4 part change:
LLVM: https://reviews.llvm.org/D53240
fastcomp: https://github.com/kripken/emscripten-fastcomp/pull/237
emscripten: https://github.com/kripken/emscripten/pull/7358
binaryen: https://github.com/kripken/emscripten/pull/7358
Fixes: https://github.com/kripken/emscripten/issues/7273
Fixes: https://github.com/kripken/emscripten/issues/7304
=> Use getTempRet0/setTempRet0 in LegalizeJSInterface.cpp

src/binaryen-c.cpp, src/binaryen-c.h
=> Fix () vs (void) C warnings in the C API

CMakeLists.txt, src/asmjs/asm_v_wasm.cpp, src/binaryen-c.cpp, src/ir/ExpressionAnalyzer.cpp, src/ir/abstract.h, src/ir/cost.h, src/ir/literal-utils.h, src/parsing.h, src/passes/ConstHoisting.cpp, src/passes/DeadCodeElimination.cpp, src/passes/FuncCastEmulation.cpp, src/passes/InstrumentLocals.cpp, src/passes/Print.cpp, src/passes/Souperify.cpp, src/shell-interface.h, src/tools/fuzzing.h, src/tools/spec-wrapper.h, src/tools/wasm-reduce.cpp, src/wasm-binary.h, src/wasm-interpreter.h, src/wasm-js.cpp, src/wasm-stack.h, src/wasm-traversal.h, src/wasm/literal.cpp, src/wasm/wasm-binary.cpp, src/wasm/wasm-type.cpp, src/wasm/wasm-validator.cpp, src/wasm/wasm.cpp
Where reasonable from a readability perspective, remove default cases
in switches over types and instructions. This makes future feature
additions easier by making the compiler complain about each location
where new types and instructions are not yet handled.
=> Remove default cases

src/passes/LocalCSE.cpp, test/passes/local-cse.txt, test/passes/local-cse.wast
We invalidated based on effects of set values, but not of the sets themselves. Without that, a set could be overridden by something irrelevant and we thought we could still reuse the old value.
Before this PR, the testcase would have the last set's value be optimized into a get, incorrectly.
=> LocalCSE fuzz fix: invalidate the set operations too

.clang-format, src/cfg/Relooper.cpp, src/emscripten-optimizer/istring.h, src/emscripten-optimizer/simple_ast.cpp, src/mixed_arena.h, src/pass.h, src/passes/I64ToI32Lowering.cpp, src/passes/TrapMode.cpp, src/shell-interface.h, src/support/bits.h, src/support/file.cpp, src/support/file.h, src/support/name.h, src/support/utilities.h, src/tools/wasm-ctor-eval.cpp, src/wasm-binary.h, src/wasm-interpreter.h, src/wasm/wasm-validator.cpp
As that is 5x more common already in our codebase.
=> standardize on 'template<' over 'template <' (i.e., remove a space)

src/asm_v_wasm.h, src/asmjs/asm_v_wasm.cpp, src/passes/Print.cpp, src/shell-interface.h, src/tools/execution-results.h, src/tools/fuzzing.h, src/wasm/wasm-s-parser.cpp, test/passes/translate-to-fuzz.txt, test/reduce/imports.wast.txt
Before we just looked at function return values when looking for differences before and after running some passes, while fuzzing. This adds logging of values during execution, which can represent control flow, monitor locals, etc., giving a lot more opportunities for the fuzzer to find problems.
Also:
* Also clean up the sigToFunctionType function, which allocated a struct and returned it. This makes it safer by returning the struct by value, which is also easier to use in this PR.
* Fix printing of imported function calls without a function type - turns out we always generate function types in loading, so we didn't notice this was broken, but this new fuzzer feature hit it.
=> Fuzzing: log values during execution

src/tools/wasm-emscripten-finalize.cpp, src/wasm-emscripten.h, src/wasm/wasm-emscripten.cpp
The wasm backend uses a wasm global (__stack_pointer) for the shadow
stack location.   In order to make this work with shared libraries the
main module would have to export this global and shared libraries would
need to import it.  This means we'd be relying of mutable globals which
are not yet implemented in all browsers.
This change allows is to move forward with shared libraries without
mutable global support by replacing all stack pointer access in shared
libraries with functions calls.
=> wasm-emscripten-finalize: Remove stack pointer global from shared libs

src/shell-interface.h
This error started showing up after: #1779
error: delete called on non-final 'wasm::ShellExternalInterface' that
has virtual functions but non-virtual destructor
=> Add virtual destructor to fix build warning/error

auto_update_tests.py, src/tools/wasm-emscripten-finalize.cpp, test/lld/duplicate_imports.wast.out, test/lld/em_asm.wast.out, test/lld/hello_world.wast.mem.out, test/lld/hello_world.wast.out, test/lld/init.wast.out, test/lld/recursive.wast.out, test/lld/reserved_func_ptr.wast.jscall.out, test/lld/reserved_func_ptr.wast.out
This means lld and emscripten can disagree about the naming of these
imports and emscripten-wasm-finalize will take care of paper over the
differences.
=> wasm-emscripten-finalize: ensure table/memory imports use emscripten's expected names

src/ir/module-utils.h
In this case simple update all the uses of the missing function.
This fixed the current emscripten failures.
=> Handle missing function in renameFunctions

build-js.sh, src/passes/CMakeLists.txt, src/passes/Inlining.cpp, src/passes/MergeBlocks.cpp, src/passes/Metrics.cpp, src/passes/NoExitRuntime.cpp, src/passes/pass.cpp, src/passes/passes.h, test/passes/no-exit-runtime.txt, test/passes/no-exit-runtime.wast
When emscripten knows that the runtime will not be exited, it can tell codegen to not emit atexit() calls (since those callbacks will never be run). This saves both code size and startup time. In asm2wasm the JSBackend does it directly. For the wasm backend, this pass does the same on the output wasm.
=> No exit runtime pass

src/wasm/wasm-emscripten.cpp, test/lld/duplicate_imports.wast.out, test/lld/em_asm.wast.out, test/lld/em_asm_table.wast.out, test/lld/hello_world.wast.mem.out, test/lld/hello_world.wast.out, test/lld/init.wast.out, test/lld/recursive.wast.out, test/lld/reserved_func_ptr.wast.jscall.out, test/lld/reserved_func_ptr.wast.out
This allows emscripten to generate table of the correct size.
Right now is simply defaults to creating a table to size 1024.
=> wasm-emscripten-finalize: Add tableSize to metadata

src/ir/ExpressionAnalyzer.cpp, src/support/safe_integer.h, src/wasm-js.cpp
I don't care either way, but the simplest thing was to add a line of space around `namespace {`, as almost all places already had that.
=> Consistent spacing around the namespace keyword

src/passes/RemoveUnusedBrs.cpp, test/passes/remove-unused-brs.txt, test/passes/remove-unused-brs.wast
=> remove-unused-brs: do not flow a value through a block if the block does not actually flow a value

src/passes/NoExitRuntime.cpp
I'm not super-happy about having a static global vector like that, though. Is there a better C++ way?
=> Use interned Names in NoExitRuntime

src/ir/cost.h, src/passes/LocalCSE.cpp, test/example/cpp-unit.cpp, test/example/cpp-unit.txt, test/passes/licm.txt, test/passes/licm.wast, test/passes/local-cse.txt, test/passes/local-cse.wast
With this we can optimize redundant global accesses fairly well (at least locally; licm also works), see #1831
=> LocalCSE: Consider pass options, both size and cost

src/passes/SSAify.cpp
=> Determinism fix for SSAify::computeGetsAndPhis

scripts/fuzz_opt.py
* Allow fuzzing from other directories, by looking for wasm-opt relative to the script itself. (Is anything necessary at the C++ level too? Seems like this is enough.)
* Ignore some VM debug assertions which are fuzz bugs that have already been filed.
* Pick the random seed based on the process ID too, for better parallel fuzzing.
=> wasm-opt fuzz script improvements

src/passes/CodeFolding.cpp, test/passes/code-folding.txt, test/passes/code-folding.wast, test/passes/remove-unused-names_code-folding.txt
Don't depend on the hash values for ordering - use a fixed order based on their order of appearance.
=> Determinism fix for code-folding

CMakeLists.txt
We removed wasm.js but left behind some code to install it if it existed.
=> Remove wasm.js reference from CMakeLists.txt

src/asmjs/asm_v_wasm.cpp, src/binaryen-c.cpp, src/ir/module-utils.h, src/passes/LegalizeJSInterface.cpp, src/tools/wasm-merge.cpp, src/wasm.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, src/wasm/wasm.cpp
This fixes the memory leak in WasmBinaryBuilder::readSignatures() caused probably the exception thrown there before the FunctionType object is safe.
This also makes it clear that the Module becomes the owner of the FunctionType objects.
=> Require unique_ptr to Module::addFunctionType()

src/support/alloc.h
Fix build on macOS High Sierra 10.13.1 and Xcode 9.2 (9C40b), which does not have aligned_alloc() (not sure if newer macOS/Xcodes do, or if this an issue with old macOS/Xcode version)
=> fix_macos_high_sierra_10_13_1 build

src/cfg/Relooper.cpp, src/cfg/Relooper.h, src/emscripten-optimizer/istring.h, src/emscripten-optimizer/optimizer.h, src/emscripten-optimizer/parser.h, src/emscripten-optimizer/simple_ast.cpp, src/emscripten-optimizer/simple_ast.h, src/ir/branch-utils.h, src/ir/count.h, src/pass.h, src/passes/Print.cpp, src/shell-interface.h, src/support/archive.h, src/support/json.h, src/support/sorted_vector.h, src/tools/wasm-metadce.cpp, src/tools/wasm-reduce.cpp, src/wasm-binary.h, src/wasm-interpreter.h, src/wasm-s-parser.h, src/wasm-traversal.h, src/wasm.h, src/wasm/wasm-s-parser.cpp
You had some recent experience with this ;)
=> Use modern  T p = v;  notation to initialize class fields

src/passes/FuncCastEmulation.cpp, test/passes/fpcast-emu.txt
`FuncCastEmulation` supports a hardcoded number of parameters:
```cpp
// This should be enough for everybody. (As described above, we need this
// to match when dynamically linking, and also dynamic linking is why we
// can't just detect this automatically in the module we see.)
static const int NUM_PARAMS = 15;
```
Turns out 15 is _not_ enough for everybody: Ruby 2.6.0 needs `NUM_PARAMS = 16`. This patch is necessary to support [Ruby 2.6.0 in WebAssembly](https://runrb.io), and in fact is the only patch needed to make [the relevant build process](https://github.com/jasoncharnes/run.rb/blob/master/src/emscripten/ruby-2.6.0/Dockerfile) work with an otherwise normal `emscripten` toolchain.
=> Increase FuncCastEmulation NUM_PARAMS

src/wasm/wasm-s-parser.cpp
=> Throw an early error in s-expr-parsing makeBlock, if not inside a function

src/binaryen-c.cpp, src/js/binaryen.js-post.js, src/literal.h, test/binaryen.js/kitchen-sink.js, test/binaryen.js/kitchen-sink.js.txt
The hardcoded 16 size was no longer valid. This was broken for a while, but happened to not overwrite important memory. Testing with the wasm backend did hit breakage.
cc @tlively @dcodeIO
=> Fix binaryen.js bindings handling of literals

src/ir/ExpressionAnalyzer.cpp
We landed two PRs that had a logic conflict but not a source conflict (bulk memory added ops, comparison optimization removed the need for PUSH ops that bulk memory added).
=> Fix merge breakage

src/wasm-stack.h
Also remove some annoying old debug printouts we had here.
=> Optimize stack writer on deeply nested blocks, fixes #1903

src/tools/wasm-opt.cpp
A user that just does
```
wasm-opt input.wasm -O
```
may assume that the input file should have been optimized. But without `-o` we don't emit any output.
Often you may not want any output, like if you just want to run a pass like `--metrics`. But for most users wasm-opt is probably going to be used as an optimizer of files. So this PR suggests we emit a warning in that case.
For comparison, `llvm-opt` would print to the console, but it avoids printing a binary there so it issues a warning. Instead of this warning, perhaps we should do the same? That would also not be confusing.
=> If no output is specified to wasm-opt, warn that we are emitting nothing

src/passes/pass.cpp, src/wasm-traversal.h, test/debugInfo.fromasm, test/debugInfo.fromasm.clamp, test/debugInfo.fromasm.clamp.map, test/debugInfo.fromasm.map, test/debugInfo.fromasm.read-written
Some of it may be removed, but that's the price of higher optimization levels. By optimizing normally in profiling and -g2 etc. builds they are more comparable to normal ones, yielding better data (for example, if we don't inline in a profiling build, the data can be misleading).
This has no change on debug info in -O0 builds, and almost no change on -O1 builds (we now run dce there, which could eliminate some debug info, but it wasn't interesting anyhow almost certainly).
=> Optimize normally with debug info

src/support/command-line.cpp
Noramlly --help is considered normal output not error output.  For
example its normally to pipe the output of --help to a pager.
=> Use stdout for --help message

src/ir/branch-utils.h, test/passes/code-folding.txt, test/passes/code-folding.wast
That caused it to miss switch targets, and a code-folding bug.
Fixes https://github.com/WebAssembly/binaryen/issues/1838
Sadly the fuzzer didn't find this because code folding looks for very particular code patterns that are unlikely to be emitted randomly.
=> Fix getExitingBranches, which had |targets| instead of |curr->targets|

src/passes/Strip.cpp
The pass was unconditionally erasing it in all --strip passes, which broke source maps in the wasm backend.
=> Do not erase internal debug info in --strip-producers

src/ir/block-utils.h, src/ir/global-utils.h, src/passes/CoalesceLocals.cpp, src/support/colors.h, src/wasm.h
Removed semicolons that cause errors when compiling with `-pedantic-errors`.
=> Remove unnecessary semicolons

src/parsing.h, src/wasm.h
and now we can write below:
```cpp
const wasm::Expression* p;
const wasm::Binary* q = p->cast<wasm::Binary>();
```
=> Add a const specifier to some member functions

src/support/file.cpp, src/support/file.h, src/tools/wasm-opt.cpp, src/wasm-io.h, src/wasm/wasm-io.cpp
This is necessary to write tests that don't require temporary files,
such as in #1948, and is generally useful.
=> Allow tools to read from stdin

src/wasm-features.h, src/wasm-type.h, src/wasm.h, src/wasm/wasm-type.cpp, src/wasm/wasm-validator.cpp
Refactors features into a new wasm-features.h file and updates the
validator to check that all types are allowed. Currently this is only
relevant for the v128 SIMD type, but new types will be added in the
future. The test for this change is in #1948.
=> Validate that types match features

auto_update_tests.py, check.py, scripts/test/generate_lld_tests.py, scripts/test/lld.py, scripts/test/wasm2js.py
- Move auto_update_tests.py code into respective scripts
- Use shared argument parsing in generate_lld_tests.py
- Use wasm-ld rather than passing -flavor
=> Improve test scripts

src/passes/pass.cpp, test/passes/O1.txt, test/passes/O1.wast
A propagated constant can be helpful in the various patterns in optimize instructions.
Testcase shows an example of this in action - we can optimize out a load offset for a constant, but if we propagated it afterwards, we would miss that.
In general these two passes can help each other, so maybe they should be combined and run multiple iterations, but that's what `--converge` is for. Meanwhile this change improves us on what seems to be the more common case - guessed at by it being what I noticed in practice, and when I run the fuzzer, I see only this type of case.
=> optimize-instructions after the last precompute-propagate

src/mixed_arena.h
to pass iterators to the functions defined in &lt;algorithm&gt;.
=> Change ArenaVector<T>::Iterator to satisfy standard (Legacy)RandomAccessIterator concept

src/wasm/wasm-binary.cpp
Not an actual problem, but hits an assertion in `D_GLIBCXX_DEBUG`, and is likely UB.
=> Avoid risky iterator addition

CMakeLists.txt, appveyor.yml
This commit tweaks the AppVeyor configuration to publish 64 and 32-bit
artifacts as part of the normal release builds. Configuration was also
added to be sure to compile code with `/MT` on MSVC to ensure that the
released artifacts depend on as few DLLs as possible, hopefully making
them as portable as possible.
cc #1695
=> Add Windows binary releases through AppVeyor

scripts/test/generate_lld_tests.py, scripts/test/lld.py, src/shared-constants.h, src/tools/wasm-emscripten-finalize.cpp, src/wasm-emscripten.h, src/wasm/wasm-emscripten.cpp, src/wasm/wasm.cpp, test/lld/duplicate_imports.wast.out, test/lld/em_asm.wast.mem.out, test/lld/em_asm.wast.out, test/lld/em_asm_O0.wast.out, test/lld/hello_world.wast.mem.out, test/lld/hello_world.wast.out, test/lld/init.wast.out, test/lld/recursive.wast.out, test/lld/reserved_func_ptr.wast.out, test/lld/shared.c, test/lld/shared.wast, test/lld/shared.wast.out
Convert PIC code generated by llvm to work with the current emscripten
ABI for dynamic linking:
- Convert mutable global imports from GOT.mem and GOT.func into
internal globals.
- Initialize these globals on started up in g$foo and f$foo imported functions
to calculate addresses at runtime.
Also:
- Add a test case for linking and finalizing a shared library
- Allow __stack_pointer global to be non-existent as can be case for
a shared library.
- Allow __stack_pointer global to be an import, as can be the case for
a shared library.
=> wasm-emscripten-finalize: Improve shared library support

.travis.yml
The `sha256sum` command doesn't exist on OSX, but it's available as `shasum` on OSX.
=> Attempt to fix sha256 generation on OSX

CHANGELOG.md, src/tools/wasm-emscripten-finalize.cpp, src/wasm/wasm-emscripten.cpp, test/lld/duplicate_imports.wast.out, test/lld/em_asm.wast.mem.out, test/lld/em_asm.wast.out, test/lld/em_asm_O0.wast.out, test/lld/em_asm_table.wast.out, test/lld/em_js_O0.wast.out, test/lld/hello_world.wast.mem.out, test/lld/hello_world.wast.out, test/lld/init.wast.out, test/lld/recursive.wast.out, test/lld/reserved_func_ptr.wast.out, test/lld/shared.wast.out
This key is used by emscripten when building with MAIN_MODULE in order
to export global variables from the main module to the side modules.
=> wasm-emscripten-finalize: add namedGlobals to output metadata

src/tools/tool-options.h, src/tools/wasm-emscripten-finalize.cpp, src/wasm-emscripten.h, src/wasm-features.h, src/wasm/wasm-emscripten.cpp, test/lld/duplicate_imports.wast.out, test/lld/em_asm.wast.mem.out, test/lld/em_asm.wast.out, test/lld/em_asm_O0.wast.out, test/lld/em_asm_table.wast.out, test/lld/em_js_O0.wast.out, test/lld/hello_world.wast.mem.out, test/lld/hello_world.wast.out, test/lld/init.wast.out, test/lld/recursive.wast.out, test/lld/reserved_func_ptr.wast.out, test/lld/shared.wast.out
Emscripten runs wasm-emscripten-finalize before running wasm-opt, so the target features section is stripped out before optimizations are run. One option would have been to add another wasm-opt invocation at the very end to strip the target features section, but dumping the features as metadata avoids the extra tool invocation. In the long run, it would be nice to have only as single binaryen invocation to do all the work that needs doing.
=> Add feature options to emscripten metadata

src/wasm/wasm-emscripten.cpp, test/lld/shared.wast.out
Turns out there was already a precedent in emscripten for using
`fp$` for these functions.
Also, improve the heuristics for guessing the stack pointer global.
There are cases where we don't use have an explicit stack pointer at
all but *do* have both imported and exported globals.
=> wasm-emscripten-finalize: rename function pointer getter functions

src/passes/Directize.cpp, test/passes/directize.txt, test/passes/directize.wast
=> Directize: if we change a type to unreachable, we need to propagate that out

.clang-format
Modifies .clang-format to reflect discussions in #1981. This basically
removes the custom 100 cols line length and allows one-line
ifs/cases/functions. There is one more similar option in clang-format,
`AllowShortLoopsOnASingleLine`, but I couldn't find any one-line for
loop in our codebase, so I think we don't use it.
=> Modify .clang-format

src/wasm2js.h, test/wasm2js/address.2asm.js, test/wasm2js/endianness.2asm.js, test/wasm2js/grow-memory-tricky.2asm.js, test/wasm2js/i64.2asm.js, test/wasm2js/left-to-right.2asm.js
* Only look at the sign of loads when they actually matter.
* Prepare for imported globals (just refactoring/cleanup).
=> Minor wasm2js cleanups

scripts/fuzz_opt.py
(as that can lead to spurious fuzz failures)
=> Don't compare running before and after binaryen opts on non-binaryen VMs if nans are present

src/passes/Precompute.cpp, test/passes/precompute.txt, test/passes/precompute.wast
We handled this for the normal case, but the optimizer can also precompute a return into a value, so check the output of the precomputation as well.
=> Don't precompute anything to a vector for now

src/ir/effects.h, test/passes/simplify-locals.txt, test/passes/simplify-locals.wast
Record side effects for bulk memory operations and change EffectAnalyzer to inherit from OverriddenVisitor to avoid overlooking the side effects of future operations.
=> Bulk memory side effects

src/wasm2js.h, test/wasm2js/emscripten.2asm.js, test/wasm2js/emscripten.wast
* Emit an import statement for the memory.
* Update the imported memory's buffer when we grow.
=> wasm2js: Support memory imports properly, updating their buffer too

src/wasm2js.h
We forgot to set them as unsigned, which meant that we were reading uninitialized memory when checking that field, which mostly worked, except if it previously contained something...
=> wasm2js: Fix unaligned loads and stores

src/wasm2js.h
We do not actually analyze scopes properly there, see comment in the commit. For now, just demote it to a warning. Not sure if it's worth fixing it or just removing it.
=> Demote a wasm2js warning on scopes

src/emscripten-optimizer/simple_ast.h, test/wasm2js/block.2asm.js, test/wasm2js/br.2asm.js, test/wasm2js/br_if.2asm.js, test/wasm2js/br_table.2asm.js, test/wasm2js/br_table_temp.2asm.js, test/wasm2js/f32.2asm.js, test/wasm2js/f64.2asm.js, test/wasm2js/fac.2asm.js, test/wasm2js/float_misc.2asm.js, test/wasm2js/func.2asm.js, test/wasm2js/i32.2asm.js, test/wasm2js/i64-ctz.2asm.js, test/wasm2js/i64.2asm.js, test/wasm2js/if_unreachable.2asm.js, test/wasm2js/if_unreachable.wast, test/wasm2js/int_exprs.2asm.js, test/wasm2js/labels.2asm.js, test/wasm2js/left-to-right.2asm.js, test/wasm2js/loop.2asm.js, test/wasm2js/stack-modified.2asm.js, test/wasm2js/switch.2asm.js, test/wasm2js/traps.2asm.js, test/wasm2js/unary-ops.2asm.js
Before, we'd print
```
if (..) label: { .. }; else ..
```
But that is wrong, as it ends the if too early. After this, we print
```
if (..) label: { .. } else ..
```
The bug was we checked if the if body was a block, but not if it was a labelled block.
=> Fix if else JS printing when if body is a labelled block

src/passes/I64ToI32Lowering.cpp, src/wasm/wasm.cpp, src/wasm2js.h, test/passes/flatten_i64-to-i32-lowering.txt, test/passes/flatten_i64-to-i32-lowering.wast, test/wasm2js/global_i64.2asm.js, test/wasm2js/global_i64.wast
Split them into two i32 globals.
=> Wasm2js: support i64 globals

src/shell-interface.h, src/tools/wasm-ctor-eval.cpp, src/wasm-interpreter.h
This corresponds to changes made to the initialization procedure in
the spec. It also removes all the heavy initialization work from the
external interface of the interpreter, which is a nice encapsulation
win.
Implementation of the interpretation of the remaining bulk memory
operations and more rigorous tests of that interpretation will come in
a follow-up PR.
=> Refactor interpreter initialization to use bulk memory

auto_update_tests.py, scripts/test/shared.py, src/tools/wasm-as.cpp, src/wasm/wasm-binary.cpp, test/unit/test_datacount.py
This reverts commit cb2d63586c08a3dd194d2b733ceb3f5051c081f8.
The issues with feature validation were mostly resolved in #1993, and
this PR finishes the job by adding feature flags to wasm-as to avoid
emitting the DataCount section when bulk-memory is not enabled.
=> Re-land emitting of DataCount section

src/wasm2js.h
The risk is that the children's type may be unreachable, in which case we may have forgotten the signing, and could get incorrect results.
=> wasm2js: remove some unneeded code, which also has some risks of incorrectness

src/emscripten-optimizer/simple_ast.h, test/wasm2js/minus_minus.2asm.js, test/wasm2js/minus_minus.wast
It is invalid to print `--5`, we need to add a space `- -5` so that it is valid JS to parse.
=> wasm2js: fix printing of negated negative constants

CHANGELOG.md, src/wasm/wasm-emscripten.cpp, test/lld/em_asm_O0.wast.out, test/lld/em_asm_shared.wast.out
When replacing the first argument to an asm call, allow more complex
expressions for expressing the address.
This fixes the case where the first argument might be the result
of adding a constant to __memory_base.
=> wasm-emscripten-finalize: Handle relocatable code in AsmConstWalker

.clang-format
Looking at the current codebase, we mostly don't binpack arguments and
parameters when they don't fit in a single line. 
BinPackArguments:
```
true:
void f() {
f(aaaaaaaaaaaaaaaaaaaa, aaaaaaaaaaaaaaaaaaaa,
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa);
}
false:
void f() {
f(aaaaaaaaaaaaaaaaaaaa,
aaaaaaaaaaaaaaaaaaaa,
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa);
}
```
BinPackParameters:
```
true:
void f(int aaaaaaaaaaaaaaaaaaaa, int aaaaaaaaaaaaaaaaaaaa,
int aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa) {}
false:
void f(int aaaaaaaaaaaaaaaaaaaa,
int aaaaaaaaaaaaaaaaaaaa,
int aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa) {}
```
=> Don't binpack arguments and parameters

.clang-format
While looking at code changes after mass clang-formatting our current
codebase, I think this rather hurts readability than improves it. And
none of preset styles (LLVM, Chrome, Google, Mozilla, and WebKit) allows
these, with only exception that Google allows short ifs on a single
line.
=> Don't allow short if/case/blocks on a single line

src/binaryen-c.h
The function `BinaryeGlobalImportGetModule` should be called `BinaryenGlobalImportGetModule` (missing `n`), leading to a linking error, as the function is called properly called `BinaryenGlobalImportGetModule`:
https://github.com/WebAssembly/binaryen/blob/9495b338121140d585648d64fb99e8ef7f92f867/src/binaryen-c.cpp#L2866
=> Fix typo in C API

src/passes/SimplifyLocals.cpp, test/passes/simplify-locals.txt, test/passes/simplify-locals.wast
Details in lengthy comment in the source.
Fixes #2063
=> Properly handle optimizing out a set from inside the value of another set in SimplifyLocals

.clang-tidy
We can add more checks later, but for now, this checks
- If the styles for variables, functions, and classes match what we
currently have
- If bodies of if/for/while/do_while are inside braces
- Some clang-tidy default checks that are related to possibly buggy code
=> Add .clang-tidy

src/wasm2js.h, test/wasm2js/block.2asm.js, test/wasm2js/br_table.2asm.js, test/wasm2js/br_table_temp.2asm.js, test/wasm2js/br_table_to_loop.2asm.js, test/wasm2js/func.2asm.js, test/wasm2js/loop.2asm.js
Don't emit unneeded breaks in switch cases, instead do
```
case X:
case Y:
..
case W: break ..
```
for each group. Also, the group with the default doesn't need any cases but the default itself.
=> wasm2js: optimize switches

.clang-tidy
Without this header file errors would be ignored.
=> Make clang-tidy check header files too

.travis.yml
Reenable the clang-tidy hook temporarily disabled by #2075.
=> Reenable clang-tidy Travis CI hook

clang-tidy-diff.sh
When we run clang-tidy for the second time to show the error, don't show
stderr output because they are not very helpful and all error messages
are printed in stdout.
=> Don't show stderr output of clang-tidy in Travis CI

src/wasm2js.h
We don't handle any of them precisely anyhow (we never checked for traps etc.), so just do the same for these... cc @tlively
=> wasm2js: "handle" saturating float to int conversions

scripts/gen-s-parser.py, src/gen-s-parser.inc
Our current clang-tidy setting requires {} after ifs. Unlike
clang-format, I couldn't find any directives or options that allow us to
exclude the generated inc file from clang-tidy. Anyway adding a pair of
braces is all it takes to make it pass.
=> Make sexp instruction parser pass clang-tidy

CHANGELOG.md, src/wasm-emscripten.h, src/wasm/wasm-emscripten.cpp
Previously we were only creating `dynCall` functions for signatures
that we have statically in the table.  However for dynamic linking we
may need to invoke functions that we don't have table entries for
(e.g. table entries from a different module).
=> Generate `dynCall` function for all signature used by `invoke` functions.

src/wasm-binary.h, src/wasm/wasm-binary.cpp
It doesn't seem to be used anywhere and I don't know why the
implementation for `WasmBinaryBuilder::getGlobalName` and
`WasmBinaryBuilder::getFunctionIndexName` are different. Renamed
`getFunctionIndexName` to `getFunctionName` for consistency.
=> Delete WasmBinaryBuilder::mappedGlobals (NFC)

build-js.sh, src/binaryen-c.cpp, src/binaryen-c.h, src/js/binaryen.js-post.js, test/binaryen.js/functions.js, test/binaryen.js/functions.js.txt, test/binaryen.js/global.js, test/binaryen.js/global.js.txt, test/binaryen.js/kitchen-sink.js, test/binaryen.js/kitchen-sink.js.txt, test/example/c-api-kitchen-sink.txt
- Print `globals` array in the tracing mode like other arrays
(`functions`, `exports`, `imports`, ...)
- Add missing accessor functions for globals
=> Add missing methods for globals to binaryen.js

scripts/fuzz_opt.py, src/tools/fuzzing.h, src/tools/wasm-opt.cpp
This is useful for wasm2js, as we don't emit traps for OOB loads etc. like wasm (like we don't trap on bad float-to-int, as it's too hard in JS, and it's undefined behavior in C anyhow). It may also help general fuzzing, as those traps may make other interesting patterns less likely.
Also add more wasm2js support in the fuzzer, which includes using this no-OOB option.
=> Add a fuzzer option to not emit code with OOB loads/indirect calls

src/binaryen-c.cpp, src/binaryen-c.h, src/passes/pass.cpp, src/support/colors.cpp, src/support/colors.h, src/tools/asm2wasm.cpp, src/tools/wasm-as.cpp, src/tools/wasm-ctor-eval.cpp, src/tools/wasm-dis.cpp, src/tools/wasm-emscripten-finalize.cpp, src/tools/wasm-metadce.cpp, src/tools/wasm-opt.cpp, src/tools/wasm-reduce.cpp, src/tools/wasm2js.cpp, test/example/c-api-kitchen-sink.c
This is useful for front-ends which wish to selectively enable or
disable coloring.
Also expose this API through the C API
=> allow color API to enable and disable colors

src/passes/AvoidReinterprets.cpp, test/wasm2js/unreachable-get-cycle.2asm.js, test/wasm2js/unreachable-get-cycle.2asm.js.opt, test/wasm2js/unreachable-get-cycle.wast
In unreachable code, a get may have a single set that assigns to it, and that set may be assigned to by that very get.
=> Fix an infinite loop in avoid-reinterprets in unreachable code with loops of gets

src/passes/DeadArgumentElimination.cpp, test/passes/dae-optimizing.txt, test/passes/dae-optimizing.wast
We forgot to clear a data structure, which meant that later iterations could get confused and do the wrong thing. Here we thought all calls were dropped when they weren't.
=> Fix a DeadArgumenElimination fuzz bug

src/passes/AvoidReinterprets.cpp, test/passes/avoid-reinterprets.txt, test/passes/avoid-reinterprets.wast
If we load only 2 or 1 byte in a load, we can't just switch it to a reinterpret of a float load, as floats must be of full size.
=> Fix AvoidReinterprets on reinterpreted loads of fewer than the full size

src/wasm-s-parser.h, src/wasm/wasm-s-parser.cpp
- Created `parseParamOrLocals`, `parseNamedParamOrLocals`,
`parseResult`, and `parseTypeRef` and make other methods use them
- Deleted some unnecessary member variables
=> Refactor type/signature/local parsing methods (NFC)

src/binaryen-c.cpp, src/binaryen-c.h, test/example/c-api-kitchen-sink.c, test/example/c-api-kitchen-sink.txt
Closes Issue #2103.
I'd like some helping with adding and running the test case:
```
$ python check.py test/example/
$ python check.py test/example/c-api-kitchen-sink.c
```
both try to run the entire test suite. I'd be glad if someone could help me understand how to run a single test case.
=> Add BinaryenModuleWriteSExpr to write a module to a string in s-expr format

.clang-tidy
clang-tidy by default enables two groups of checks: clang-diagnostic-*
and clang-analyzer-*. Between the two, clang-analyzer is a static
analyzer, but it seems to often produces false warnings. For example,
when you write `object->someFunction()`, if it is not sure if object is
not a NULL, i.e., if there's no assert(object) before, it produces a
warning. This is sometimes annoying and inserting `assert` everywhere
does not seem to be very appealing. I also noticed LLVM and V8 also
disabled this analyzer.
`-*` disables all checks. Then I re-enabled clang-diagnostic and
readability-braces-around-statements.
=> Disable clang static analyzer in clang-tidy

src/shared-constants.h, src/wasm/wasm-s-parser.cpp, src/wasm/wasm.cpp
Checking if a first string matches a certain string within a list
element appears many times within the parser, so extracted it as a
helper function.
=> Factor out elementStartsWith in wast parser (NFC)

src/pass.h, src/passes/Inlining.cpp, src/tools/optimization-options.h
This will allow easier experimentation with optimal settings.
Also tweaked the default logic slightly to always inline single
caller functions up to a certain size.
The command-line arguments were tested to have the desired effect
for example by the Makefile change in this commit:
https://github.com/aardappel/lobster/commit/39ae393e27ff363ab095bbb26c90d6fe17570104
which in turn relies on:
https://github.com/emscripten-core/emscripten/pull/8635
=> Inlining: exposed inlining thresholds as command-line parameters.

src/passes/RemoveUnusedModuleElements.cpp
It looks there's no need to maintain `functions` and `functionImports`
separately.
=> Simplify function lists in RemoveUnusedModuleElements (NFC)

src/passes/OptimizeInstructions.cpp
This helps avoid issues with smaller stack sizes on some OSes.
Should fix the last Mac test failure on emscripten-releases CI (`other.test_js_function_names_are_minified`, which happens to have massively-nested additions of constants).
=> Un-recursify OptimizeInstructions::optimizeAddedConstants

build-js.sh, src/passes/CMakeLists.txt, src/passes/PrintFunctionMap.cpp, src/passes/pass.cpp, src/passes/passes.h, test/passes/print-function-map.txt, test/passes/print-function-map.wast
This can be useful for interpreting a stack trace from a production environment where names did not exist on the client. Emscripten will use this to implement `emcc --emit-symbol-map` for the wasm backend.
=> Add --print-function-map to print out a map of function index to name

src/wasm-interpreter.h
We previously had one for calls (the spec tests check for infinite recursion).
This is an internal limit of the interpreter, until we un-recursify it, which may make sense at some point - but it's unlikely interpreting massively-recursive things will be beneficial in the optimizer anyhow, since if it could do something with them, it could also do so on the smaller pieces iteratively.
This could fix the current recursion issue on the mac bot, but as with the last fix, there might be more...
=> Add a recursion limit for the interpreter's expression runner

src/wasm-interpreter.h, test/spec/call.wast, test/spec/call_indirect.wast
This should be small enough to work in a 512K stack on Linux, which may then be small enough to work on all common OSes.
I had to update some spec tests which actually did more recursive calls, but I don't think the change reduces any relevant amount of test coverage.
This may fix the Mac bot finally, as with this it passes for me on the stack size I think Macs have by default.
=> Reduce interpreter recursion limit

src/ir/literal-utils.h, test/passes/ssa-nomerge_enable-simd.txt, test/passes/ssa-nomerge_enable-simd.wast
This prevents the optimizer from producing v128.const instructions,
which are not supported by V8 at this time.
=> Use splatted zero vector in makeZero

clang-format-diff.sh, clang-tidy-diff.sh
- Error out of shell script if any command fails.
- Don't try to run on travis builds that are not PRs (i.e. don't have any upstream).
- Prefer origin/master over just master (some folks don't use master locally).
- Don't hide stderr by piping it to dev/null.
=> Improve error detection in clang-tidy/clang-format scripts.

src/cfg/Relooper.cpp, test/example/relooper-merge7.c, test/example/relooper-merge7.txt
Fixes in Relooper merge consecutive blocks:
1. Entry block getting removed when it is part of a loop:
```
bb1->AddBranchTo(bb2, nullptr);
bb1->AddBranchTo(bb3, ...);
bb2->AddBranchTo(bb1, nullptr);
bb3->AddBranchTo(bb4, nullptr);
relooper.AddBlock(bb1);
relooper.AddBlock(bb2);
relooper.AddBlock(bb3);
relooper.AddBlock(bb4);
relooper.Calculate(bb1);
```
2. Branches memory leak
=> Fix bug and leak in relooper merge consecutive blocks

src/tools/asm2wasm.cpp, src/tools/optimization-options.h, src/tools/wasm-opt.cpp
Use one shared location in optimization-options as much as possible.
This also allows tools like wasm2js to receive that flag.
=> Refactor -g param parsing

src/support/alloc.h
`_ISOC11_SOURCE` is the preprocessor flag that specifies whether or not `aligned_alloc` is defined and exists. While GCC versions lower than 5 do include C++11 and C++14 constructs, they do not include `std::aligned_alloc`, so this check allows compiling on those versions of GCC by defaulting down to `posix_memalign` in those situations appropriately.
=> Enable compiling on GCC < 5

src/wasm/wasm-binary.cpp
Otherwise there is no way to view a wasm object file that uses atomics in binaryen.
=> Make feature section errors into warnings

src/passes/Bysyncify.cpp, src/tools/optimization-options.h, test/passes/bysyncify_pass-arg=bysyncify-ignore-imports.txt, test/passes/bysyncify_pass-arg=bysyncify-ignore-imports.wast
`ignore-imports` makes it not assume that any import may unwind/rewind the stack. `ignore-indirect` makes it not assume any indirect call can reach an unwind/rewind (which means, it assumes there is not an indirect call on the stack while unwinding).
=> Bysyncify: add ignore-imports and ignore-indirect options

src/passes/Bysyncify.cpp, src/tools/wasm-reduce.cpp, test/passes/bysyncify.txt, test/passes/bysyncify_optimize-level=1.txt, test/passes/bysyncify_pass-arg=bysyncify-ignore-imports.txt, test/passes/bysyncify_pass-arg=bysyncify-ignore-indirect.txt, test/passes/bysyncify_pass-arg=bysyncify-imports@env.import,env.import2.txt
This results in better code sizes on many testcases, sometimes much better. For example, on SQLite the 150K function has only 27 locals instead of 3,874 which it had before (!). This also reduces total code size on SQLite by 15%.
The key issue is that after instrumenting control flow we have a lot bigger live ranges.
This must be done rather carefully, as we need to introduce some temp locals early on (for breaking up ifs, for call return values, etc.).
=> Bysyncify: optimize better by coalescing before instrumenting control flow

scripts/fuzz_opt.py
Create a class for handling the current fuzz testcase, and implement subclasses for the various fuzz things we do. This disentangles a lot of code.
=> Refactor python fuzz script

build-js.sh
(which it isn't when using the wasm backend with object files)
=> binaryen.js building: don' t assume the intermediate form is bitcode

src/passes/Bysyncify.cpp, test/passes/bysyncify.txt, test/passes/bysyncify.wast
We need memory in order to read and write rewinding info, so add it if the module didn't have any memory at all.
=> Bysyncify: ensure memory exists

src/passes/Bysyncify.cpp
We flatten and then optimize a little, which works for passes that don't unflatten too much. Vacuum does have cases where it causes fuzz bugs, and it isn't necessary for good results anyhow, so remove it.
=> Bysyncify: avoid the vacuum pass

src/passes/Bysyncify.cpp, test/passes/bysyncify.txt, test/passes/bysyncify_optimize-level=1.txt, test/passes/bysyncify_pass-arg=bysyncify-ignore-indirect.txt
We assigned it to a local, but didn't run `maybeSkip` on it. As a result, it was executed during rewinding, which broke restoring the saved value.
=> Bysyncify: fix skipping of flattened if condition

src/passes/Bysyncify.cpp, src/support/name.h, src/support/string.h
This allows us to do things in emscripten like note that all `env.invoke_*` functions are important.
=> Bysyncify: allow wildcard endings in import list

src/wasm2js.h, test/wasm2js/address.2asm.js, test/wasm2js/dynamicLibrary.2asm.js, test/wasm2js/dynamicLibrary.2asm.js.opt, test/wasm2js/emscripten.2asm.js, test/wasm2js/emscripten.2asm.js.opt
When using emscripten with -O2 and --memory-init-file 0, the
JS minification breaks on this function for memory initialization
setup, causing an exception to be thrown during module setup.
Moving from two 'var' declarations for the same variable to one
should avoid hitting this with no change in functionality (the
var gets hoisted anyway).
https://github.com/emscripten-core/emscripten/issues/8886
=> Workaround for wasm2js output minification issue with emscripten

scripts/fuzz_opt.py, scripts/fuzz_shell.js, src/tools/fuzzing.h, src/wasm-builder.h, test/passes/translate-to-fuzz_all-features.txt, test/passes/translate-to-fuzz_no-fuzz-nans_all-features.txt, test/unit/input/bysyncify.js
Gets fuzzing support for Bysyncify working.
* Add the python to run the fuzzing on bysyncify.
* Add a JS script to load and run a testcase with bysyncify support. The code has all the runtime support for sleep/resume etc., which it does on calls to imports at random in a deterministic manner.
* Export memory from fuzzer so JS can access it.
* Fix tiny builder bug with makeExport.
=> Bysyncify: Fuzzing

src/passes/Precompute.cpp, src/wasm-interpreter.h
Keep limiting in precompute as before: that is useful since that pass is run as part of normal compilation, and we want to avoid native stack limits on all platforms. Also that pass is not likely to find any pattern of size 50 of higher that it can't precompute as a sum of smaller pieces.
Restore the 250 limit from before for interpreting entire modules, as without that the fuzzer will sometimes hit the limit and cause a false positive.
=> Limit interpreter depth in precompute, but not when running whole modules

src/wasm/wasm-binary.cpp
The event section should be between the global section and the export
section, if present. Here tests are missing, but we don't have a very
good way of testing validity of binary anyway. We are planning to add d8
tests in a separate PR. Fixes #2195.
=> Fix event section order

src/wasm2js.h, test/wasm2js/emscripten-grow-no.2asm.js, test/wasm2js/emscripten-grow-no.2asm.js.opt, test/wasm2js/emscripten-grow-no.wast, test/wasm2js/emscripten-grow-yes.2asm.js, test/wasm2js/emscripten-grow-yes.2asm.js.opt, test/wasm2js/emscripten-grow-yes.wast
Previously we tried to export it if the memory was exported, even if growth was not on, which caused an error.
=> wasm2js: export memory growth function only if memory growth is enabled

src/pass.h
```cpp
struct FooPass : public wasm::Pass {
FooPass(int a, int b);
};
PassRunner runner {module};
runner.add<FooPass>(1, 2); // To allow this
```
This change avoids unnecessary copying and allows us to pass the reference without `reference_wrapper`.
```cpp
struct BarPass : public wasm::Pass {
BarPass(std::ostream& s);
};
runner.add<BarPass>(std::cout); // Error (cout is uncopyable)
runner.add<BarPass>(std::ref(std::cout)); // OK
↓
runner.add<BarPass>(std::cout); // OK (passed by reference)
runner.add<BarPass>(std::ref(std::cout)); // OK
```
=> Allows multiple arguments to be passed to PassRunner::add<T>()

CHANGELOG.md, src/tools/wasm-emscripten-finalize.cpp, src/wasm-emscripten.h, src/wasm/wasm-emscripten.cpp
I'm working on a change to lld that will cause `-pie` binaries to
import __stack_pointer, just like -shared do already.  Because we
don't yet support mutable globals everywhere this change will
internalize the import and create a new immutable import that is used
to initialize the internal one.
This change is part of the fix for:
https://github.com/emscripten-core/emscripten/issues/8915
=> wasm-emscripten-finalize: Internalize mutable __stack_pointer import

src/passes/OptimizeInstructions.cpp
This pull request fixes a build error when fuzzing Cranelift. Cranelift uses binaryen via binaryen-rs.
When compiling, binaryen would produce the following signedness error (just one given, for an example):
> /home/sstangl/.cargo/git/checkouts/binaryen-rs-2ef43ee92a3c1c21/7fb899c/binaryen-sys/binaryen/src/passes/OptimizeInstructions.cpp:1027:30: error: comparison of integer expressions of different signedness: ‘uint64_t’ {aka ‘long unsigned int’} and ‘int’ [-Werror=sign-compare]
>  1027 |           value64 + offset64 <= std::numeric_limits<int32_t>::max()) {
>       |           ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> cc1plus: all warnings being treated as errors
> gmake[2]: *** [src/passes/CMakeFiles/passes.dir/build.make:458: …
=> Fix comparison signedness errors in optimizeMemoryAccess()

src/passes/MinifyImportsAndExports.cpp, src/shared-constants.h, src/wasm/wasm-emscripten.cpp, src/wasm/wasm.cpp
This is core import like __memory_base and __table_base.
=> Don't minify __stack_pointer import

src/tools/wasm2js.cpp, src/wasm2js.h
This can't use the normal wasm-opt mechanism because we modify the discard the wasm as part of running wasm2js, so we need to emit it in the proper place in the middle.
=> Add an option to emit a symbols file from wasm2js.

scripts/fuzz_opt.py
That way we can still test new flags on modes that do support them (e.g. FuzzExec runs on everything)
=> [fuzzing] Give each testcase handler a list of feature flags it requires

src/passes/Asyncify.cpp, src/passes/pass.cpp
* Clarify the difference between old and new Asyncify.
* Remove the old `--bysyncify` pass option.
=> Cleanups after renaming Bysyncify to Asyncify

src/wasm/wasm-emscripten.cpp
The key thing is that there is a single constant, which may or may not be saved/loaded from a local, and may or may not get an added global if in relocatable code.
Fixes https://github.com/emscripten-core/emscripten/issues/8993
=> Generalize EM_JS parsing code. 

scripts/fuzz_opt.py
When it finds a failing testcase, it reduces the list of optimizations, and then runs wasm-reduce to reduce the wasm itself.
This refactors the testcase handlers into two kinds: one returns a list of commands to run (`get_commands()`), and we can auto-reduce them. The others get all the parameters and do whatever they want internally, and we can't auto-reduce them yet. If it is useful, auto-reducing could be added to the other handlers (CompareVMs, Wasm2JS, etc.) by modifying them to the new form.
Tested manually by breaking stuff.
=> Auto-reduce testcases from the FuzzExec handler in the fuzzer

src/asm2wasm.h, src/binaryen-c.cpp, src/ir/flat.h, src/ir/module-utils.h, src/pass.h, src/passes/Asyncify.cpp, src/passes/DeadArgumentElimination.cpp, src/passes/Directize.cpp, src/passes/DuplicateFunctionElimination.cpp, src/passes/FuncCastEmulation.cpp, src/passes/Inlining.cpp, src/passes/LegalizeJSInterface.cpp, src/passes/Print.cpp, src/passes/ReorderFunctions.cpp, src/passes/SafeHeap.cpp, src/passes/SimplifyGlobals.cpp, src/passes/pass.cpp, src/tools/wasm-metadce.cpp, src/tools/wasm2js.cpp, src/wasm/wasm-validator.cpp, src/wasm2js.h
Main change here is in `pass.h`, everything else is changes to work with the new API.
The `add("name")` remains as before, while the weird variadic `add(..)` which constructed the pass now just gets a `std::unique_ptr` of a pass. This also makes the memory management internally fully automatic. And it makes it trivial to parallelize `WalkerPass::run` on parallel passes.
As a benefit, this allows removing a lot of code since in many cases there is no need to create a new pass runner, and running a pass can be just a single line.
=> Simpify PassRunner.add() and automatically parallelize parallel functions

src/ir/manipulation.h, src/passes/MemoryPacking.cpp, src/wasm/wasm-validator.cpp, test/passes/memory-packing_all-features.txt, test/passes/memory-packing_all-features.wast
This prevents those instructions from becoming invalid due to memory
packing optimizations and is also a code size win. Fixes #2227.
=> Remove bulk memory instructions refering to active segments

src/passes/SimplifyGlobals.cpp, test/passes/simplify-globals_enable-mutable-globals.txt
```
(global $g1 (mut i32) (i32.const 42))
(global $g2 i32 (global.get $g1))
```
can be optimized to
```
(global $g1 (mut i32) (i32.const 42))
(global $g2 i32 (i32.const 42))
```
even though `$g1` is mutable - because it can't be mutated during module instantiation.
=> SimplifyGlobals: Propagate constants in global initializers

src/wasm/wasm-emscripten.cpp, test/lld/duplicate_imports.wast.out, test/lld/em_asm.wast.mem.out, test/lld/em_asm.wast.out, test/lld/em_asm_O0.wast.out, test/lld/em_asm_shared.wast.out, test/lld/em_asm_table.wast.out, test/lld/em_js_O0.wast.out, test/lld/hello_world.passive.wast.out, test/lld/hello_world.wast.mem.out, test/lld/hello_world.wast.out, test/lld/init.wast.out, test/lld/recursive.wast.out, test/lld/reserved_func_ptr.wast.out, test/lld/shared.wast.out
The new flag indicates whether main reads the argc/argv parameters. If it does not, we can avoid emitting code to generate those arguments in the JS, which is not trivial in small programs - it requires some string conversion code.
Nicely the existing test inputs were enough for testing this (see outputs).
This depends on an emscripten change to land first, as emscripten.py asserts on metadata fields it doesn't recognize.
=> wasm-emscripten-finalize: Add mainReadsParams metadata

.travis.yml, build-js.sh, src/passes/StackIR.cpp, src/wasm-stack.h, src/wasm/CMakeLists.txt, src/wasm/wasm-binary.cpp, src/wasm/wasm-stack.cpp
Previously `StackWriter` and its subclasses had routines for all three
modes (`Binaryen2Binary`, `Binaryen2Stack`, and `Stack2Binary`) within a
single class. This splits routines for each in a separate class and
also factors out binary writing into a separate class
(`BinaryInstWriter`) so other classes can make use of it.
The new classes are:
- `BinaryInstWriter`:
Binary instruction writer. Only responsible for emitting binary
contents and no other logic
- `BinaryenIRWriter`: Converts binaryen IR into something else
- `BinaryenIRToBinaryWriter`: Writes binaryen IR to binary
- `StackIRGenerator`: Converts binaryen IR to stack IR
- `StackIRToBinaryWriter`: Writes stack IR to binary
I didn't use the existing `***StackWriter` names because I couldn't
exactly understand their meanings, but I …
=> Refactor stack IR / binary writer (NFC)

.travis.yml, check.py
This upgrades the OS in the Travis CI to Bionic and GCC version to 7. This also
fixes a bug that `COMPILER_FLAGS` was not correctly added at build time in gcc
tests. Somehow this bug hasn't manifested so far, but after upgrading, this
failed thread sanitizer tests because `-fsanitize=thread` was added only at link
time and not in build time.
=> Upgrade Travis CI system

src/wasm/wasm-validator.cpp, test/events.wast, test/events.wast.from-wast, test/events.wast.fromBinary, test/events.wast.fromBinary.noDebugInfo, test/spec/events.wast
Before I disallowed values with no events, but spec does not say
anything about it, so I think that restriction is not necessary.
=> Allow 0-value events

src/passes/Print.cpp
This prints events in color like other module elements such as globals.
This also splits `visitEvent` into two functions to be consistent with
`visitGlobals` or `visitFunctions`.
=> Print events in color

build-js.sh, scripts/gen-s-parser.py, src/binaryen-c.cpp, src/binaryen-c.h, src/gen-s-parser.inc, src/js/binaryen.js-post.js, test/binaryen.js/kitchen-sink.js, test/binaryen.js/kitchen-sink.js.txt, test/binaryen.js/push-pop.js, test/binaryen.js/push-pop.js.txt
This adds
- `push`/`pop` support for other types: v128 and exnref
- `push`/`pop` support for binaryen.js
Because binaryen.js follows Binaryen's AST structure, without `pop` in
binaryen.js, EH instructions cannot be represented in binaryen.js.
=> More push/pop support

src/tools/wasm-shell.cpp
If we don't enable features in assertion failure tests, new feature
tests fail not because they are malformed but because they have
unsupported features. It's hard to add tests because existing
`assert_invalid` tests were already failing because they have
unsupported features.
=> Enable all features in wasm-shell assert failure tests

src/passes/Asyncify.cpp, src/wasm-binary.h, src/wasm/wasm-binary.cpp, test/passes/asyncify_pass-arg=asyncify-blacklist@foo,bar.txt, test/passes/asyncify_pass-arg=asyncify-blacklist@foo,bar.wast, test/passes/asyncify_pass-arg=asyncify-whitelist@foo,bar.txt, test/passes/asyncify_pass-arg=asyncify-whitelist@foo,bar.wast, test/unit/test_asyncify.py
The blacklist means "functions here are to be ignored and not instrumented, we can assume they never unwind." The whitelist means "only these functions, and no others, can unwind." I had hoped such lists would not be necessary, since Asyncify's overhead is much smaller than the old Asyncify and Emterpreter, but as projects have noticed, the overhead to size and speed is still significant. The lists give power users a way to reduce any unnecessary overhead.
A slightly tricky thing is escaping of names: we escape names from the names section (see #2261 #1646). The lists arrive in human-readable format, so we escape them before comparing to the internal escaped names. To enable that I refactored wasm-binary a little bit to provide the escaping logic, cc @yurydelendik
If both lists are …
=> Asyncify: whitelist and blacklist support

README.md, scripts/test/mod.ule.js, scripts/test/node-esm-loader.mjs, src/wasm2js.h, test/wasm2js/dot_import.2asm.js, test/wasm2js/dot_import.2asm.js.opt, test/wasm2js/dot_import.wast
This fixes names that would be invalid in JS, like `a.b`. Turns out the Go compiler emits wasm with such imports.
Also add some docs on how to use wasm2js.
Fixes #2263
=> wasm2js: Mangle import names for JS

test/binaryen.js/atomics.js, test/binaryen.js/debug-info.js, test/binaryen.js/emit_asmjs.js, test/binaryen.js/event.js, test/binaryen.js/functions.js, test/binaryen.js/global.js, test/binaryen.js/hello-world.js, test/binaryen.js/optimize-levels.js, test/binaryen.js/push-pop.js, test/binaryen.js/sourcemap.js, test/binaryen.js/stackir.js
Without `assert`, even if a test does not validate, the errors will only
show up in its corresponding `.txt` file while the test will succeed.
This makes sure it errors out when a test fails to validate. This also
adds validation checks if there is none.
=> Make sure binaryen.js tests validate

src/wasm/wasm-emscripten.cpp, test/lld/em_asm_table.wast, test/lld/em_asm_table.wast.out
Refs https://github.com/emscripten-core/emscripten/issues/8894. This fix does not handle dynamic linking, which requires additional work.
=> Fix EM_ASM not working with setjmp/longjmp

.travis.yml
This fixes #2273 for... unknown reasons. The tl;dr; is that the current
release binaries built in this Alpine container seem to segfault when
run over some wasm files when an exception is thrown, but clang-built
binaries magically seems to not segfault!
=> Compile Linux release binaries with Clang

.travis.yml
It appears that the previous PR I had for `clang` didn't actually run on
the PR and I forgot to include the removal of `-no-pie` in the PR. Sorry
about that! This should fix the CI issues seen [here]
[here]: https://travis-ci.org/WebAssembly/binaryen/jobs/566546589
=> Remove `-no-pie` since clang doesn't like it

scripts/test/lld.py, src/tools/wasm-emscripten-finalize.cpp, src/wasm-emscripten.h, src/wasm/wasm-emscripten.cpp, test/lld/recursive_safe_stack.wast, test/lld/recursive_safe_stack.wast.out
When `--check-stack-overflow` is passed to `wasm-emscripten-finalize`, a function called `__set_stack_limit` is exported. Calling this function with the low end of the stack will signal to the module how far the stack is allowed to grow.
When the stack pointer dips below the value set by `__set_stack_limit`, an imported function `__handle_stack_overflow` is called.
If `__set_stack_limit` is not called, then stack overflow check is disabled.
Refs https://github.com/emscripten-core/emscripten/issues/9039.
=> Implement --check-stack-overflow flag for wasm-emscripten-finalize

CHANGELOG.md, src/tools/wasm-emscripten-finalize.cpp, src/wasm/wasm-emscripten.cpp
There were a couple of places where we were relying on internal
names and therefore a name section.  After this change
wasm-emscripten-finalize works correctly on binaries without a name
section at all and only relies on the names of imports and exports.
=> wasm-emscripten-finalize: Remove reliance on name section

src/ir/ExpressionManipulator.cpp
We didn't have an OverriddenVisitor in the copying code, and sadly unimplemented visitors just return null. That explains the crash in https://github.com/WebAssembly/binaryen/issues/2288
The missing visitors were push and pop.
=> Copying fixes

build-js.sh, src/passes/CMakeLists.txt, src/passes/DuplicateFunctionElimination.cpp, src/passes/DuplicateImportElimination.cpp, src/passes/opt-utils.h, src/passes/pass.cpp, src/passes/passes.h, test/passes/duplicate-import-elimination.txt, test/passes/duplicate-import-elimination.wast
This is both an optimization and a workaround for the problem that https://github.com/emscripten-core/emscripten/pull/7641 uncovered and had to be reverted because of.
What's going on there is that wasm-emscripten-finalize turns `emscripten_longjmp_jmpbuf` into `emscripten_longjmp` (for some LLVM internal reason - there's a long comment in the source that I didn't fully follow). There are two such imports already, one for each name, and before that PR, we ended up with just one. After that PR, we end up with two. And with two, the minification of import names gets confused - we have two imports with the same name, and the code there ends up ignoring one of them.
I'm not sure why that PR changed things - I guess the wasm-emscripten-finalize code looks at the name, and that PR changed what …
=> Duplicate Import Elimination

src/asmjs/asmangle.cpp, src/wasm/wasm-validator.cpp, test/wasm2js/empty_export.2asm.js, test/wasm2js/empty_export.2asm.js.opt, test/wasm2js/empty_export.wast
We were missing this silly validation rule, which explains the non-crash in https://github.com/WebAssembly/binaryen/issues/2288
=> Support empty export names in wasm2js and JS mangling in general

src/ir/ExpressionManipulator.cpp
It seems this was missing in #2289.
=> Add missing copy in Copier::visitPush

src/wasm2js.h, test/wasm2js/br_table_hoisting.2asm.js, test/wasm2js/br_table_hoisting.2asm.js.opt, test/wasm2js/br_table_temp.2asm.js.opt, test/wasm2js/excess_fallthrough.2asm.js, test/wasm2js/excess_fallthrough.2asm.js.opt, test/wasm2js/excess_fallthrough.wast, test/wasm2js/switch.2asm.js
The switch lowering will "hoist" blocks of code into the JS switch when it can. If it can hoist some but not others, it must not fall through into those others (while it can fall through the hoisted ones - they began as nested blocks with falling-through between them). To fix this, after the hoisted ones issue a break out of the switch (which now contains all the hoisted code, so breaking out of it gets to the code right after the hoisted ones).
fixes #2300
=> wasm2js: Fix switch lowering, don't fall through after the hoisted parts

src/wasm/wasm-emscripten.cpp, test/lld/em_asm_table.wast, test/lld/em_asm_table.wast.out
This reverts commit 12add6f17c377de7ac334e8fa7885b61b98f3db4 (#2283).
This is done due to the complexity of supporting EM_ASM and setjmp/longjmp, especially with dynamic linking thrown into the mix.
Since https://reviews.llvm.org/D66356, using EM_ASM and setjmp/longjmp in the same function is now an error.
=> Remove code to handle EM_ASM and setjmp/longjmp

src/wasm/wasm-emscripten.cpp, test/unit/input/em_asm_mangled_string.wast, test/unit/test_finalize.py, test/unit/test_lld.py
Show an error message when the `local.get` can't be traced back to a constant in the first argument to `emscripten_asm_const_*`, and suggest that the user try `EM_JS`.
=> Fix infinite loop in AsmConstWalker::visitCall

build-js.sh, src/binaryen-c.cpp, src/binaryen-c.h, src/js/binaryen.js-post.js, test/binaryen.js/kitchen-sink.js, test/binaryen.js/kitchen-sink.js.txt, test/example/c-api-kitchen-sink.c, test/example/c-api-kitchen-sink.txt
This PR exposes the tail-call and reference-types feature flags via the C and JS APIs, so a generator can set them.
=> Expose new feature flags in C & JS API

src/wasm2js.h, test/wasm2js/address.2asm.js, test/wasm2js/dynamicLibrary.2asm.js, test/wasm2js/dynamicLibrary.2asm.js.opt, test/wasm2js/emscripten-grow-no.2asm.js, test/wasm2js/emscripten-grow-no.2asm.js.opt, test/wasm2js/emscripten-grow-yes.2asm.js, test/wasm2js/emscripten-grow-yes.2asm.js.opt, test/wasm2js/emscripten.2asm.js, test/wasm2js/emscripten.2asm.js.opt
Emscripten's minifier mis-minifies a couple bits in the memory
init function that's used with wasm2js when not using an external
memory init file:
https://github.com/emscripten-core/emscripten/issues/8886
Previous fix worked around the bug in one place but failed to
account for another. Have now confirmed that it works with this
change in place.
Updated test cases to match.
=> Followup to workaround for minification of wasm2js mem init

src/passes/Asyncify.cpp, src/support/file.cpp, src/support/file.h, src/support/string.h, test/unit/test_asyncify.py
See https://github.com/emscripten-core/emscripten/issues/9206, the asyncify names can need complex escaping, so this provides an escape hatch.
=> Support response files, and use that in Asyncify

src/passes/MinifyImportsAndExports.cpp, src/shared-constants.h, src/wasm/wasm.cpp, test/passes/minify-imports-and-exports_all-features.txt, test/passes/minify-imports-and-exports_all-features.wast
This makes the minification pass aware of `wasi_unstable` and `wasi` as well.
=> Minify wasi imports and exports, and not just "env"

CHANGELOG.md, src/binaryen-c.cpp, src/binaryen-c.h, src/js/binaryen.js-post.js, test/binaryen.js/global.js, test/binaryen.js/global.js.txt, test/binaryen.js/kitchen-sink.js, test/binaryen.js/kitchen-sink.js.txt
This PR adds a new parameter to `BinaryenAddGlobalImport` (C) respectively `Module#addGlobalImport` (JS) to support importing of mutable globals.
=> Add 'mutable' parameter to global imports in C/JS API

check.py
These files are produced alongside .exe when CMake is used on Windows.
Subsequently, check.py finds, tries to execute them and fails since they're not excluded.
=> Ignore .manifest files in check.py

src/passes/MinifyImportsAndExports.cpp, src/shared-constants.h, src/wasm/wasm.cpp
Remove shared constants (if we need them later, can add them then).
Remove "wasi", support just "wasi_unstable".
=> Wasi followups to #2323

scripts/test/wasm2js.py, src/wasm2js.h, test/wasm2js/address.2asm.js, test/wasm2js/atomic_fence.2asm.js, test/wasm2js/dynamicLibrary.2asm.js, test/wasm2js/dynamicLibrary.2asm.js.opt, test/wasm2js/emscripten-grow-no.2asm.js, test/wasm2js/emscripten-grow-no.2asm.js.opt, test/wasm2js/emscripten-grow-yes.2asm.js, test/wasm2js/emscripten-grow-yes.2asm.js.opt, test/wasm2js/emscripten.2asm.js, test/wasm2js/emscripten.2asm.js.opt, test/wasm2js/endianness.2asm.js, test/wasm2js/grow-memory-tricky.2asm.js, test/wasm2js/grow-memory-tricky.2asm.js.opt, test/wasm2js/grow_memory.2asm.js, test/wasm2js/left-to-right.2asm.js, test/wasm2js/traps.2asm.js, test/wasm2js/unaligned.2asm.js, test/wasm2js/unaligned.2asm.js.opt
We emitted the `__wasm_memory_size` function only when memory growth was enabled, but it can be used without that too.
In theory we could only emit it if either memory growth or `memory.size` is used, but I think we can expect JS minifiers to do that later.
Also fix a test suite bug - the check/auto_update script didn't run all the wasm2js tests when you run it with argument `wasm2js` (it used that as the list of tests, instead of the list of files, which confused me here for a while...).
=> [wasm2js] Fix memory.size

src/passes/SafeHeap.cpp, test/passes/safe-heap_disable-simd.txt, test/passes/safe-heap_disable-simd.wast, test/passes/safe-heap_enable-threads_enable-simd.txt, test/passes/safe-heap_low-memory-unused_enable-threads_enable-simd.txt
Currently emscripten links the wasm, then links the JS, then computes the final static allocations and in particular the location of the sbrk ptr (i.e. the location in memory of the brk location). Emscripten then imports that into the asm.js or wasm as `env.DYNAMICTOP_PTR`. However, this didn't work in the wasm backend where we didn't have support for importing globals from JS, so we implement sbrk in JS.
I am proposing that we change this model to allow us to write sbrk in C and compile it to wasm. To do so, that C code can import an extern C function, `emscripten_get_sbrk_ptr()`, which basically just returns that location. The PostEmscripten pass can even apply that value at compile time, so we avoid the function call, and end up in the optimal place, see …
=>  SafeHeap: Prepare for emscripten_get_sbrk_ptr

src/passes/Print.cpp, test/fib-dbg.wasm.fromBinary
This helps with debugging human-readable sections like sourceMappingURL.
=> Print custom section contents if printable

src/passes/SafeHeap.cpp
To allow #2331 to roll, I forgot that upstream and fastcomp handle sbrk differently. This fixes that, and handles the upstream case where we import `sbrk` itself from JS.
We can simplify this after https://github.com/emscripten-core/emscripten/pull/9397 lands, however, it may also be nice to keep the backwards compatibility for running on existing wasm files in the wild.
=> Handle sbrk import by emscripten+upstream in SafeHeap

src/passes/SafeHeap.cpp, test/passes/safe-heap_disable-simd.txt, test/passes/safe-heap_disable-simd.wast
emscripten_get_sbrk_ptr is an asm.js library function, which means it is *inside* the wasm after asm2wasm, and exported. Find it via the export.
(Hopefully the last PR on this topic, sorry...)
=> Properly handle fastcomp *wasm* safe heap

src/passes/Asyncify.cpp, test/passes/asyncify_pass-arg=asyncify-asserts_pass-arg=asyncify-whitelist@waka.txt, test/passes/asyncify_pass-arg=asyncify-asserts_pass-arg=asyncify-whitelist@waka.wast
With the optional asserts, we throw if we see an unwind begin in code that we thought could never unwind (say, because the user incorrectly blacklisted it).
Helps with https://github.com/emscripten-core/emscripten/issues/9389
=> Add asserts in Asyncify

src/passes/CMakeLists.txt
Even though we do support python3 and if the python in your path
happens to be python3 that will work just fine, we also want to
continue to support those users who still only have python2 (i.e.
mac users who are relying on the default system python).
See https://github.com/emscripten-core/emsdk/issues/356
=> Revert part of #2281 to allow the possiblity of building under python2

src/passes/Asyncify.cpp, src/support/string.h, test/unit/test_asyncify.py
See https://github.com/emscripten-core/emscripten/issues/9381 for rationale.
The impacted code seem to lack proper testing framework, ideally we'd unit-test `wildcardMatch`, and check what functions precisely were instrumented in the final output. I'd like feedback/guidance on this.
Also currently the performance appears significantly slower (~+30% time). I'm not sure if this is purely related to the matching algorithm, in which case we may need a larger beast like http://developforperformance.com/MatchingWildcards_AnImprovedAlgorithmForBigData.html
EDIT: +30% time of my full link (+15s from initial 45s), so probably X00% increase for the pass itself.
=> asyncify: support *-matching in whitelist and blacklist

src/passes/Asyncify.cpp
This is part of the fix for
https://logs.chromium.org/logs/emscripten-releases/buildbucket/cr-buildbucket.appspot.com/8901492015302662960/+/steps/Emscripten_testsuite__upstream__other_/0/stdout
Specifically it fixes that the name shown there should not be escaped.
Followup for #2344 cc @Beuc
=> Show the unescaped name in Asyncify pattern warnings

CMakeLists.txt
Since the waterfall's CMake was too old to target C++17 and many LTS
systems may not yet support C++17. Also updates the minimum required
CMake version to one that mentions the CXX_STANDARD variable in its
docs.
=> Move back to C++14

src/tools/wasm-reduce.cpp
The capitalisation causes issues on case-sensitive file systems, for example when cross-compiling binaryen for windows.
=> Fix case of `windows.h` include

src/passes/InstrumentLocals.cpp, test/passes/instrument-locals_all-features.txt, test/passes/instrument-locals_all-features.wast
`pop` is not a real instruction and automatically generated when reading
binary and deleted when writing binary, so this does not work with
instrumentation.
=> Don't instrument pops in InstrumentLocals

CHANGELOG.md, src/binaryen-c.cpp, src/binaryen-c.h, src/js/binaryen.js-post.js, test/binaryen.js/kitchen-sink.js.txt, test/binaryen.js/reloc.js, test/binaryen.js/reloc.js.txt, test/example/c-api-kitchen-sink.c, test/example/c-api-kitchen-sink.txt
This PR adds an `offset` parameter to `BinaryenSetFunctionTable` so table elements can start at the value of an (imported constant) global. Previously, the offset was fixed to zero. As usual this is a breaking change to the C-API but backwards compatible when using the JS-API.
Background is that we are currently [experimenting](https://github.com/AssemblyScript/assemblyscript/pull/890) with a preliminary dynamic linking mechanism, for example to have a shared runtime that not every module has to ship on its own, and this is a missing building block.
=> Add offset parameter to BinaryenSetFunctionTable

build-js.sh, src/binaryen-c.cpp, src/binaryen-c.h, src/js/binaryen.js-post.js, test/binaryen.js/custom-section.js, test/binaryen.js/custom-section.js.txt
This adds a new `BinaryenAddCustomSection` API so a generator can add arbitrary custom sections to a module.
In our use case this is useful to toy around with custom sections that are not yet supported out of the box by Binaryen.
=> Add BinaryenAddCustomSection API

check.py, scripts/test/shared.py
This allows fuzzing in parallel invocations of `fuzz_opt.py`.
=> Add --binaryen-test-out to allow setting the test output dir.

src/support/path.cpp, src/support/path.h, src/tools/wasm-reduce.cpp
wasm-reduce needs to find the binaries.
Alternatively maybe we can set that env var all the time, like in `tests/shared.py`? Not sure how people would feel about that. cc @sbc100
=> Fix autoreducing when not in the binaryen directory

build-js.sh, src/binaryen-c.cpp, src/binaryen-c.h, src/js/binaryen.js-post.js, test/binaryen.js/kitchen-sink.js, test/binaryen.js/kitchen-sink.js.txt, test/example/c-api-kitchen-sink.c, test/example/c-api-kitchen-sink.txt
It gives the possibility to list several contents in a decoded module.
Some examples of the use of the JS api:
```javascript
const decodedModule = binaryen.parseText( my_wast_content );
for ( let i = 0, len = decodedModule.getNumExports() ; i !== len ; ++i )
{
const ptr = decodedModule.getExportByIndex(i);
const expInfo = binaryen.getExportInfo(ptr);
console.log('export id: ' + i.toString(10));
console.log('ptr: ' + ptr.toString(10));
console.log('expName: ' + expInfo.name);
}
for ( let i = 0, len = decodedModule.getNumFunctions() ; i !== len ; ++i )
{
const ptr = decodedModule.getFunctionByIndex(i);
const funcInfo = binaryen.getFunctionInfo( ptr );
console.log('function id: ' + i.toString(10));
console.log('ptr: ' + ptr.toString(10));
console.log(funcInfo);
}
for ( let i = 0, len = …
```
=> Ability to list each item on Exports/Data Segments/Functions

src/js/binaryen.js-post.js, test/binaryen.js/kitchen-sink.js, test/binaryen.js/kitchen-sink.js.txt
This fixes #2396.  This converts the use of the old `Pointer_stringify` to the new `UTF8ToString`.  Added a js test in kitchen-sink.js to cover this.
=> Convert usage of Pointer_stringify to UTF8ToString

src/passes/Asyncify.cpp, src/passes/pass.cpp, src/passes/passes.h, test/passes/asyncify_mod-asyncify-always-and-only-unwind.txt, test/passes/asyncify_mod-asyncify-always-and-only-unwind.wast, test/passes/asyncify_mod-asyncify-always-and-only-unwind_O.txt, test/passes/asyncify_mod-asyncify-always-and-only-unwind_O.wast, test/passes/asyncify_mod-asyncify-never-unwind.txt, test/passes/asyncify_mod-asyncify-never-unwind.wast, test/passes/asyncify_mod-asyncify-never-unwind_O.txt, test/passes/asyncify_mod-asyncify-never-unwind_O.wast
These passes are meant to be run after Asyncify has been run, they modify the output. We can assume that we will always unwind if we reach an import, or that we will never unwind, etc.
This is meant to help with lazy code loading, that is, the ability for an initially-downloaded wasm to not contain all the code, and if code not present there is called, we download all the rest and continue with that. That could work something like this:
* The wasm is created. It contains calls to a special import for lazy code loading.
* Asyncify is run on it.
* The initially downloaded wasm is created by running --mod-asyncify-always-and-only-unwind: if the special import for lazy code loading is called, we will definitely unwind, and we won't rewind in this binary.
* The lazily downloaded wasm is …
=> Add ModAsyncify* passes

.travis.yml, scripts/test/node-esm-loader.mjs, scripts/test/wasm2js.py
This is a continued effort to try and track down #2273 which came up
again and is still present in the current release binaries. Issues like
crystal-lang/crystal#4276 may indicate that C++ exceptions are just
somewhat broken with static linking when using alpine, but I've at least
locally been able to verify that upgrading the container produces
working binaries which previously segfaulted on some wasm files.
=> Upgrade the build container for linux releases

scripts/test/generate_lld_tests.py, scripts/test/shared.py, src/wasm/wasm-emscripten.cpp, test/lld/shared_longjmp.c, test/lld/shared_longjmp.wast, test/lld/shared_longjmp.wast.out
Fixes https://github.com/WebAssembly/binaryen/issues/2180
=> When renaming functions ensure the corresponding GOT.func entry is also renamed

src/binaryen-c.cpp, src/binaryen-c.h
I think the parameter of ``BinaryenModuleAllocateAndWriteText`` should be of type ``BinaryenModuleRef`` instread of a pointer to that (which is already a pointer itself).
This fixes a compiler error when trying to compile code calling this function with a C++ compiler.
=> fix BinaryenModuleAllocateAndWriteText parameter type

Contributing.md, src/passes/Precompute.cpp, test/passes/precompute-propagate_all-features.txt, test/passes/precompute-propagate_all-features.wast
This fixes a crash when programs containing load_splats are optimized.
=> Do not precompute SIMDLoad

src/wasm/wasm-emscripten.cpp, test/lld/em_asm.wast.mem.out, test/lld/em_asm.wast.out, test/lld/em_asm_O0.wast.out, test/lld/em_asm_main_thread.wast.out, test/lld/em_asm_shared.wast.out
Before we used 0-based indexes which meant that we needed to modify the
code calling the emask function to replace the first argument.
Now we use the string address itself as the index/code for the emasm
constant.  This allows use code to go unmodifed as the emscripten side
will accept the memory address as the index/code.
See: https://github.com/emscripten-core/emscripten/issues/9013
=> Use absolute memory addresses for emasm string indexes.

src/passes/RemoveUnusedModuleElements.cpp, test/passes/remove-unused-module-elements_all-features.txt, test/passes/remove-unused-module-elements_all-features.wast
Previously RemoveUnusedModuleElements pass only preserved exported
events and did not preserve events used in `throw` and `br_on_exn`
instructions. This fixes it.
=> Don't remove events used in instructions

src/ir/type-updating.h, src/passes/DeadCodeElimination.cpp, test/passes/dce_all-features.txt, test/passes/dce_all-features.wast
Like an `If`, `Try` construct is reachable when either its try body or
catch body is reachable. This adds support for that.
=> Add EH support for DCE pass

src/passes/OptimizeInstructions.cpp, test/passes/O.bin.txt, test/passes/optimize-instructions_enable-threads.txt, test/passes/optimize-instructions_enable-threads.wast
=> OptimizeInstructions: Eq64 of 0 => Eqz64

src/wasm/wasm-emscripten.cpp, test/lld/em_asm.wast.mem.out, test/lld/em_asm.wast.out, test/lld/em_asm_O0.wast.out, test/lld/em_asm_main_thread.wast.out, test/lld/em_asm_shared.wast.out
Since we switched the using memory addresses for asm const indexes
and stopping trying to modify the code we can no loner de-duplicate
the asm const strings here.
If we want to de-dupliate in the strings in emscripten we could do that
but it seems like a marginal benefit.
This fixes the test_html5_gamepad failures which is currently showing
up on the emscripten waterfall.
=> Don't attempt to de-duplicate asm consts

check.py, scripts/fuzz_opt.py, src/tools/fuzzing.h, test/passes/translate-to-fuzz_all-features.txt, test/passes/translate-to-fuzz_no-fuzz-nans_all-features.txt
- Adds `items` function for `FeatureOptions` so we can get a vector of
eligible types
- Replaces hardcoded enumeration of MVP types with `getConcreteTypes`,
which also adds v128 type to the list if SIMD is enabled
- Removes `getType()` function; this does not seem to be used anywhere
- Renames `vectorPick` with `pick`
=> Improve type selection in fuzzer

scripts/gen-s-parser.py, src/gen-s-parser.inc, src/wasm-s-parser.h, src/wasm/wasm-s-parser.cpp, test/exception-handling.wast.fromBinary, test/exception-handling.wast.fromBinary.noDebugInfo, test/passes/remove-unused-module-elements_all-features.txt, test/passes/remove-unused-module-elements_all-features.wast
- When a catch body is a block, call its `finalize` function with the
correct type
- Don't create a block when there's one instruction in a catch body
- Remove `makeCatch` from gen-s-parser.py; it's not necessary
- Fix a test case that has a `catch` without `try`
=> Fix catch parsing
