WebAssembly/binaryen

- src/pass.h
- src/tools/optimization-options.h
- src/tools/tool-options.h
- src/tools/wasm-emscripten-finalize.cpp
This will allow us to pass pass args to
wasm-emscripten-finalize, which runs
legalize-js-interface internally, which recently
added an optional argument.
> Support --pass-arg in ToolOptions

- src/binaryen-c.cpp
- src/binaryen-c.h
- test/example/c-api-hello-world.c
- test/example/c-api-kitchen-sink.c
> uint32_t instead of int64_t as return type for GetMemorySegmentByteOffset

- src/wasm-type.h
- src/wasm/literal.cpp
The plan is to extend `Type` to represent arbitrary multivalue types,
and as a prerequisite for that it is necessary to make it a class
instead of an enum. This PR bends over backwards to add all the
automatic conversions and constants necessary to allow the rest of the
code to compile unmodified, but in the future it should be possible to
standardize usage across the code base and remove some of these
utilities.
> [NFC] Make Type a class instead of enum

- .gitattributes
- build-js.sh
- src/binaryen-c.h
This is an alternative to #2361 in that it only implements reusing `BINARYEN_API` so we don't have to list all the functions in `build-js.sh`. Differs in that it keeps the sh file relatively straight forward without going overboard with bash functionality. Also adds various quotes in case of whitespace in paths and makes it so that `*.sh` files always use LF line endings to ease Windows support. For instance, I am pulling the repository in Windows but compile in WSL, which, if Git isn't properly configured to check out line endings as-is, would otherwise break the sh files.
If this one is preferred, it also fixes #2361.
> Reuse BINARYEN_API for Emscripten builds

- src/ir/module-utils.h
- src/passes/Asyncify.cpp
This moves code out of Asyncify into a general helper class. The class
automates scanning the functions for a property, then propagating it to
functions that call them. In Asyncify, the property is "may call something
that leads to sleep".
This will be useful in a future exceptions-optimizing pass I want to write,
where the property will be "may throw". We will then be able to remove
exceptions overhead in cases that definitely do not throw.
> Refactor a WholeProgramAnalysis helper [NFC]

- auto_update_tests.py
- check.py
- scripts/test/asm2wasm.py
- scripts/test/lld.py
- scripts/test/shared.py
- scripts/test/wasm2js.py
This makes test scripts simpler by reducing loop depths and extracting
repeating code into methods or variables.
- `get_tests` returns a list of tests with specified extensions. This
includes files with a full path rather than just file names.
- Adds `***_TEST_DIR` variables in shared.py.
- Reduces loop depths by using early exits and `get_tests`.
> Simplify test scripts (NFC)

- CMakeLists.txt
- src/asmjs/CMakeLists.txt
- src/cfg/CMakeLists.txt
- src/emscripten-optimizer/CMakeLists.txt
- src/ir/CMakeLists.txt
- src/passes/CMakeLists.txt
- src/support/CMakeLists.txt
- src/wasm/CMakeLists.txt
This PR addressess issue #2450 
So far, the CMake configuration did not produce a standalone statically linked or shared library of libbinaryen. The command
```cmake
TARGET_LINK_LIBRARIES(binaryen passes wasm asmjs emscripten-optimizer ir cfg support)
```
that was intended to provide this library actually just told CMake that every target, to which the library `binaryen` is linked, the other libraries (`passes`, `wasm`, ...) must also be linked. This works fine if you include this repository with CMake `add_subdirectory` but fails to provide a standalone library that can be used by third-parties.
This PR solves this problem by constructing the libraries of the subdirectories (`passes`, `wasm`, ...) as `OBJECT` libraries. From the CMake documentation: "An object library compiles source …
> Build libbinaryen as a monolithic statically/shared library

- auto_update_tests.py
- check.py
- scripts/fuzz_opt.py
- scripts/test/asm2wasm.py
- scripts/test/binaryenjs.py
- scripts/test/generate_lld_tests.py
- scripts/test/lld.py
- scripts/test/wasm2js.py
- test/unit/test_asyncify.py
- test/unit/test_datacount.py
- test/unit/test_features.py
- test/unit/test_finalize.py
- test/unit/test_memory_packing.py
- test/unit/test_parsing_error.py
- test/unit/test_tail_call_type.py
- test/unit/test_warnings.py
- test/unit/utils.py
- travis-emcc-tests.sh
Don't directly import names from shared.py and support.py, and use
prefixes instead. Also this reorders imports based on [PEP
recommendation](https://www.python.org/dev/peps/pep-0008/#imports).
Suggested in https://github.com/WebAssembly/binaryen/pull/2457#discussion_r348642424.
> Use package name in imports (NFC)

- src/binaryen-c.cpp
- src/binaryen-c.h
This improves typechecking by verifying that user passes pointers of correct types.
> Use opaque types for handle references

- src/wasm/wasm-emscripten.cpp
We were only updating the imported Function's type name
field and failing to update its params and results. This caused the
binary writer to start using the wrong types after #2466.
This PR fixes the code to update both type representations on the
imported function. This double bookkeeping will be removed entirely in
an upcoming PR.
> Update type information for em_asm functions

- auto_update_tests.py
- check.py
- scripts/test/shared.py
- test/spec/expected-output/if-label-scope.fail.wast.log
This makes auto_update_tests.py update spec test outputs (ones that are
printed with `spectest.print` import) and extracts spec tests blacklist
into shared.py with comments for reasons why each of them fails.
Also deletes if-label-scope.fail.wast.log because it does not seem to
match with any of existing tests.
> Auto-update spec test outputs

- auto_update_tests.py
- check.py
- src/passes/DuplicateFunctionElimination.cpp
- src/passes/Inlining.cpp
- src/passes/RemoveUnusedModuleElements.cpp
- src/wasm.h
- src/wasm/wasm.cpp
This creates utility functions for removing module elements: removing
one element by name, and removing multiple elements using a predicate
function. And makes other parts of code use it. I think this is a
light-handed approach than calling `Module::updateMaps` after removing
only a part of module elements.
This also fixes a bug in the inlining pass: it didn't call
`Module::updateMaps` after removing functions. After this patch callers
don't need to additionally call it anyway.
> Refactor removing module elements

- CMakeLists.txt
And use LTO in upstream opt builds, which improves code size by >20%.
> Apply old fastcomp flags, reverting a large 30% size regression

- src/binaryen-c.cpp
We already have exports for `_malloc` and `_free` in the Emscripten build, but there is no way yet to initialize the data without resorting to JS. Hence this PR adds a few additional memory helpers to the Emscripten build so it becomes possible to manipulate Binaryen memory without the need for extra glue code, for example when Binaryen is a WebAssembly import, and one is allocating strings to be used by / reading strings returned by Binaryen.
I expect this to be a bit controversial because the use case is relatively specific, but it makes sense for us because we are consuming the C-API directly (from JS and eventually Wasm) and don't rely on `binaryen.js-post.js`.
> Add memory helpers for using the C-API (from Wasm)

- CMakeLists.txt
With https://github.com/WebAssembly/binaryen/pull/2483 merged, emcc hits the following warning when attempting to compile `wasm-opt` to JS with Emsdk:latest-fastcomp:
```
shared:WARNING: for wasm there is no need to set ELIMINATE_DUPLICATE_FUNCTIONS, the binaryen optimizer does it automatically
shared:ERROR: treating warnings as errors (-Werror)
```
Appears this happens because `ELIMINATE_DUPLICATE_FUNCTIONS` is set for all targets when using fastcomp, even though only `binaryen_js` uses `WASM=0`. So this PR moves it into the `binaryen_js` target.
> Fix error when building wasm-opt.js with latest-fastcomp

- src/support/CMakeLists.txt
- src/support/command-line.cpp
- src/support/debug.cpp
- src/support/debug.h
- src/tools/wasm-opt.cpp
This allows for debug trace message to be split my channel.  So you
can pass `--debug` to simply debug everything, or `--debug-only=opt`
to only debug wasm-opt.
This change is the initial introduction but as a followup I hope to
convert all tracing over to this new system so we can more easily
control the debug output.
> Add BYN_DEBUG/BYN_TRACE macros similar to LLVM's debug system

- src/asm2wasm.h
- src/binaryen-c.cpp
- src/support/file.cpp
- src/support/file.h
- src/tools/asm2wasm.cpp
- src/tools/fuzzing.h
- src/tools/wasm-as.cpp
- src/tools/wasm-ctor-eval.cpp
- src/tools/wasm-dis.cpp
- src/tools/wasm-emscripten-finalize.cpp
- src/tools/wasm-metadce.cpp
- src/tools/wasm-opt.cpp
- src/tools/wasm-shell.cpp
- src/tools/wasm2js.cpp
- src/wasm-binary.h
- src/wasm-io.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-io.cpp
- src/wasm/wasm-s-parser.cpp
- src/wasm2js.h
This means that debugging/tracing can now be enabled and controlled
centrally without managing and passing state around the codebase.
> Convert to using DEBUG macros

- CMakeLists.txt
- src/asmjs/CMakeLists.txt
- src/cfg/CMakeLists.txt
- src/emscripten-optimizer/CMakeLists.txt
- src/ir/CMakeLists.txt
- src/passes/CMakeLists.txt
- src/support/CMakeLists.txt
- src/wasm/CMakeLists.txt
This is line with modern cmake conventions is much less SHOUTY!
> cmake: Convert to using lowercase for and functions/macros

- src/cfg/Relooper.cpp
- src/ir/ReFinalize.cpp
- src/ir/block-utils.h
- src/ir/branch-utils.h
- src/passes/DeadCodeElimination.cpp
- src/passes/MergeBlocks.cpp
- src/passes/RemoveUnusedBrs.cpp
- src/passes/StackIR.cpp
- src/passes/Vacuum.cpp
- src/tools/wasm-reduce.cpp
- src/wasm-stack.h
- src/wasm/wasm-s-parser.cpp
- src/wasm/wasm.cpp
That was needed for super-old wasm type system, where we allowed
```
(block $x
(br_if $x
(unreachable)
(nop)
)
)
```
That is, we differentiated "taken" branches from "named" ones (just
referred to by name, but not actually taken as it's in unreachable code).
We don't need to differentiate those any more. Remove the ReFinalize
code that considered it, and also remove the named/taken distinction in
other places.
> Remove 'none' type as a branch target in ReFinalize

- src/tools/wasm-metadce.cpp
This like was mistakenly removed as part of the BYN_TRACE conversion.
> Fix metadce debug info after #2497

- CMakeLists.txt
- src/asm2wasm.h
- src/cfg/Relooper.cpp
- src/dataflow/graph.h
- src/ir/memory-utils.h
- src/passes/PostAssemblyScript.cpp
- src/support/debug.cpp
- src/support/debug.h
- src/support/threads.h
- src/wasm-binary.h
We always enable assertions by default, but this options allows for
a build without them.
Fix all errors in the ASSERTIONS=OFF build, even though we don't
normally build this its good to keep it building.
> Add BYN_ENABLE_ASSERTSION option to allow assertions to be disabled.

- src/support/debug.cpp
- src/tools/wasm-emscripten-finalize.cpp
- src/wasm/wasm-emscripten.cpp
Also fix, but in splitting the names of the trace channels.  Obviously
I can't write string.split correctly in C first time around.
> Add some tracing to wasm-emscripten-finalize

- src/passes/MinifyImportsAndExports.cpp
This allows us to support not just wasi_unstable but also the new
wasi_snapshot_preview1 and beyond.
See https://github.com/emscripten-core/emscripten/pull/9956
> Include in minification all imports from modules starting with `wasi_`

- src/passes/Print.cpp
- src/support/name.h
- test/binaryen.js/fatal.js.txt
- test/binaryen.js/kitchen-sink.js.txt
- test/binaryen.js/validation_errors.js.txt
- test/passes/flatten_simplify-locals-nonesting_souperify-single-use_enable-threads.txt
- test/passes/flatten_simplify-locals-nonesting_souperify_enable-threads.txt
- test/passes/fuzz-exec_O.txt
- test/passes/fuzz-exec_enable-sign-ext.txt
- test/passes/nm.txt
- test/passes/print-call-graph.txt
- test/passes/ssa_fuzz-exec_enable-threads.txt
- test/unit/test_finalize.py
- travis-emcc-tests.sh
The `$` is not actually part of the name, its the marker that starts
a name in the wat format.  It can be confusing to see it show up when
doing `cerr << name`, for example.
This change has Print.cpp add the `$` which seem like the right place
to do this.  Plus it revealed a bunch of places where were not calling
printName to escape all the names we were printing.
> Don't include `$` with names unless outputting to wat format

- src/wasm/wasm-type.cpp
- test/binaryen.js/kitchen-sink.js.txt
- test/example/c-api-kitchen-sink.c
- test/passes/translate-to-fuzz_all-features.txt
- test/passes/translate-to-fuzz_no-fuzz-nans_all-features.txt
Currently `none` and `unreachable` types are [stored as the same empty
`{}`](https://github.com/WebAssembly/binaryen/blob/b232033385b025ba276423613fb67f644c0596ce/src/wasm/wasm-type.cpp#L58-L59) in src/wasm/wasm-type.cpp. This makes [`Type::operator<`](https://github.com/WebAssembly/binaryen/blob/b232033385b025ba276423613fb67f644c0596ce/src/wasm/wasm-type.cpp#L132-L141) incorrectly
when given `none` and `unreachable`, because it expands both given types
and lexicographically compare them, when both of the expanded vector
will be empty.
This was found by the fuzzer. [This line](https://github.com/WebAssembly/binaryen/blob/b232033385b025ba276423613fb67f644c0596ce/src/tools/fuzzing.h#L652) in `Modder::visitExpression`
tries to retrieve candidates of the same type. Because we can't really …
> Fix comparison of none and unreachable types

- src/dataflow/graph.h
- test/passes/souperify.txt
- test/passes/souperify.wast
This fixes the parent-child relationship computation in `DataFlow.Graph`
when there is a loop. This wasn't discovered until now because this is
used in Souperify and Souperify only runs after Flatten pass, which
produces redundant blocks between inside and outside of a loop.
> Fix loop parent computation in DataFlow.Graph

- src/passes/Flatten.cpp
- test/passes/asyncify.txt
- test/passes/asyncify_mod-asyncify-always-and-only-unwind.txt
- test/passes/asyncify_mod-asyncify-never-unwind.txt
- test/passes/asyncify_pass-arg=asyncify-asserts_pass-arg=asyncify-whitelist@waka.txt
- test/passes/asyncify_pass-arg=asyncify-blacklist@foo,bar.txt
- test/passes/asyncify_pass-arg=asyncify-ignore-imports.txt
- test/passes/asyncify_pass-arg=asyncify-ignore-indirect.txt
- test/passes/asyncify_pass-arg=asyncify-imports@env.import,env.import2.txt
- test/passes/asyncify_pass-arg=asyncify-whitelist@foo,bar.txt
- test/passes/flatten.bin.txt
- test/passes/flatten.txt
- test/passes/flatten_i64-to-i32-lowering.txt
- test/passes/flatten_local-cse.txt
- test/passes/flatten_rereloop.txt
- test/passes/flatten_simplify-locals-nonesting_souperify-single-use_enable-threads.txt
- test/passes/flatten_simplify-locals-nonesting_souperify_enable-threads.txt
When the expression type is none, it does not seem to be necessary to
make it a prelude and insert a nop. This also results in unnecessary
blocks that contains an expression with a nop, which can be reduced to
just the expression. This also adds some newlines to improve
readability.
> Remove redundant instructions in Flatten

- src/passes/pass.cpp
Currently `BINARYEN_PASS_DEBUG=3` prints `.wasm` files but they are
actually text wast files. This makes `BINARYEN_PASS_DEBUG=3` prints both
wasm/wast files, where wasm contains a binary file and wast a text file.
> Write wasm/wast files with BINARYEN_PASS_DEBUG=3

- src/passes/MemoryPacking.cpp
- src/wasm-interpreter.h
- test/passes/memory-packing_all-features.txt
- test/passes/memory-packing_all-features.wast
- test/spec/bulk-memory.wast
This implements recent bulk memory spec changes
(WebAssembly/bulk-memory-operations#126) in Binaryen. Now `data.drop` is
equivalent to shrinking a segment size to 0, and dropping already
dropped segments or active segments (which are thought to be dropped in
the beginning) is treated as a no-op. And all bounds checking is
performed in advance, so partial copying/filling/initializing does not
occur.
I tried to implement `visitDataDrop` in the interpreter as
`segment.data.clear();`, which is exactly what the revised spec says. I
didn't end up doing that because this also deletes all contents from
active segments, and there are cases we shouldn't do that:
- `wasm-ctor-eval` shouldn't delete active segments, because it will
store the changed contents back into segments
- When `--fuzz-exec` is …
> Implement 0-len/drop spec changes in bulk memory

- CHANGELOG.md
- src/ir/module-utils.h
- src/wasm.h
- test/passes/roundtrip.txt
- test/passes/roundtrip.wast
Currently `ModuleUtils::clearModule` does not clear `exists` flags in
the memory and table, and running RoundTrip pass on any module that has
a memory or a table fails as a result. This creates `clear` function in
`Memory` and `Table` and makes `clearModule` call them.
> Correctly clear memory / table info in clearModule

- src/passes/MemoryPacking.cpp
- test/passes/memory-packing_all-features.txt
- test/passes/memory-packing_all-features.wast
This does two things:
- Restore `visitDataDrop` handler deleted in #2529, but now we convert
invalid `data.drop`s to not `unreachable` but `nop`. This conforms to
the revised spec that `data.drop` on the active segment can be treated
as a nop.
- Make `visitMemoryInit` trap if offset or size are not equal to 0 or if
the dest address is out of bounds. Otherwise drop all its argument.
Fixes #2535.
> Fix trapping and dangling insts in memory packing

- src/tools/wasm-emscripten-finalize.cpp
Without this, the first wasm-opt invocation will remove it. But it
can be very large, and we will soon start to automatically do
updating on it when it exists, so avoid the work if we aren't
actually building a final output with dwarf.
> Strip DWARF in finalize, to avoid keeping it around til later unnecessarily

- src/passes/MemoryPacking.cpp
- test/passes/memory-packing_all-features.txt
Because `memory.size` returns the size in number of pages, we have to
multiply the size with the page size when converting `memory.init`.
> Fix memory size calculation in MemoryPacking

- .gitignore
> Reorder git ignores

- src/wasm.h
- src/wasm/wasm.cpp
This does something similar to #2489 for more functions, removing
boilerplate code for each module element using template functions.
> Refactor module element related functions (NFC)

- src/js/binaryen.js-post.js
- test/binaryen.js/kitchen-sink.js
- test/binaryen.js/kitchen-sink.js.txt
Switch label names for br_table instructions were corrupted in the
binaryen.js API layer, with each label cropped down to the number of
characters that it is an index into the list.
This was due to passing UTF8ToString as a callback method to
Array.prototype.map, which passes the index as second parameter. The
second parameter of UTF8ToString is the max number of bytes to copy,
so the initial label came out as '', then 'l', then 'la', 'lab', etc.
> Fix for binaryen.js getExpressionInfo on switch names

- src/asm2wasm.h
- src/ir/ExpressionAnalyzer.cpp
- src/ir/load-utils.h
- src/passes/Asyncify.cpp
- src/passes/AvoidReinterprets.cpp
- src/passes/ConstHoisting.cpp
- src/passes/Print.cpp
- src/passes/SafeHeap.cpp
- src/passes/SpillPointers.cpp
- src/wasm-interpreter.h
- src/wasm-type.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-s-parser.cpp
- src/wasm/wasm-type.cpp
- src/wasm/wasm-validator.cpp
Several type-related functions currently exist outside of `Type`
class and thus in the `wasm`, effectively global, namespace. This moves
these functions into `Type` class, making them either member functions
or static functions.
Also this renames `getSize` to `getByteSize` to make it not to be
confused with `size`, which returns the number of types in multiple
types. This also reorders the order of functions in `wasm-type.cpp` to
match that of `wasm-type.h`.
> Move Type-related functions into Type class (NFC)

- src/binaryen-c.cpp
- src/tools/fuzzing.h
- src/wasm-features.h
This uses `FeatureSet` in place of `FeatureSet::Feature` when possible,
making it possible for functions take a set of multiple features as one
argument.
> Use FeatureSet instead of FeatureSet::Feature(NFC)

- src/wasm-stack.h
- src/wasm-traversal.h
- src/wasm/wasm-stack.cpp
- test/passes/Os_print-stack-ir.txt
- test/passes/generate-stack-ir_optimize-stack-ir_print-stack-ir_all-features.txt
We have not been generating push and pop instructions in the stack IR.
Even though they are not written in binary, they have to be in the stack
IR to match the number of inputs and outputs of instructions.
Currently `BinaryenIRWriter` is used both for stack IR generation and
binary generation, so we should emit those instructions in
`BinaryenIRWriter`. `BinaryenIRToBinaryWriter`, which inherits
`BinaryenIRWriter`, does not do anything for push and pop instructions,
so they are still not emitted in binary.
> Generate push/pop in stack IR

- src/wasm/wasm-s-parser.cpp
- src/wasm/wasm-stack.cpp
- test/atomics.wast
- test/atomics.wast.from-wast
- test/atomics.wast.fromBinary
- test/atomics.wast.fromBinary.noDebugInfo
- Allow `atomic.notify` and `atomic.wait` instructions to parse memory
arguments (`align` and `offset`) and print the offset in these
instruction when writing binary, rather than assuming it to be 0
- Change arguments of `parseMemAttributes` to be references
> Parse memarg in atomic.wait and atomic.notify

- src/wasm/wasm-s-parser.cpp
This adds line and column info to wast parser exception messages to be
more readable when they are encoutered. In other cases this makes
existing line and column number more fine grained, or adds some helpful
strings (if line and column info is not available).
> Add line and col info to wast parser exceptions

- src/wasm/wasm-validator.cpp
- test/exception-handling.wast
- test/exception-handling.wast.from-wast
- test/exception-handling.wast.fromBinary
- test/exception-handling.wast.fromBinary.noDebugInfo
This allows subtype for arguments of `throw`. This also renames
`shouldBeSubTypeOrUnreachable` to `shouldBeSubTypeOrFirstIsUnreachable`,
to be consistent with `shouldBeEqualOrFirstIsUnreachable`.
> Allow subtype in throw instruction

- src/passes/Print.cpp
- test/passes/Os_print-stack-ir.txt
- test/passes/generate-stack-ir_optimize-stack-ir_print-stack-ir_all-features.txt
This makes push and pop instructions not printed in the stack IR format
to make it valid wat form. Push and pop are still generated in the stack
IR in memory but not printed in the text format.
> Do not print push/pop in stack IR

- src/wasm2js.h
- test/wasm2js/br.2asm.js
- test/wasm2js/br_table.2asm.js
- test/wasm2js/br_table_temp.2asm.js
- test/wasm2js/unreachable-later.2asm.js
- test/wasm2js/unreachable-later.2asm.js.opt
- test/wasm2js/unreachable-later.wast
By doing so we ensure that our calls to convert wasm
types to JS  types never try to convert an unreachable.
Fixes #2558
> DCE at the end of wasm2js

- src/asm2wasm.h
- src/asmjs/asm_v_wasm.cpp
- src/binaryen-c.cpp
- src/ir/ExpressionAnalyzer.cpp
- src/ir/ReFinalize.cpp
- src/ir/abstract.h
- src/ir/hashed.h
- src/literal.h
- src/parsing.h
- src/passes/ConstHoisting.cpp
- src/passes/FuncCastEmulation.cpp
- src/passes/I64ToI32Lowering.cpp
- src/passes/InstrumentLocals.cpp
- src/passes/InstrumentMemory.cpp
- src/passes/OptimizeInstructions.cpp
- src/passes/RemoveNonJSOps.cpp
- src/shell-interface.h
- src/tools/fuzzing.h
- src/tools/spec-wrapper.h
- src/tools/wasm-reduce.cpp
- src/tools/wasm2js.cpp
- src/wasm-binary.h
- src/wasm-builder.h
- src/wasm-interpreter.h
- src/wasm-type.h
- src/wasm/literal.cpp
- src/wasm/wasm-stack.cpp
- src/wasm/wasm-type.cpp
- src/wasm/wasm-validator.cpp
- src/wasm2js.h
Now types must be explicitly converted to uint32_t with Type::getID or
to ValueType with Type::getVT. This fixes #2572 for switches that use
Type::getVT.
> Remove implicit conversion operators from Type

- test/passes/dwarfdump_roundtrip_dwarfdump.bin.txt
- test/passes/fannkuch3.bin.txt
- test/passes/fannkuch3_manyopts.bin.txt
- test/passes/fib2.bin.txt
- test/passes/multi_line_table.bin.txt
- third_party/llvm-project/DWARFEmitter.cpp
gimli-rs and perhaps also the spec require a final 0
to terminate the list. LLVM itself is fine without that.
Found with @RReverser . With this the Chrome
devtools can load the dwarf emcc emits with
`-gforce_dwarf` and show the original C++ source.
(edit: tested on Dev 81)
> Fix emitting of .debug_abbrev

- src/cfg/cfg-traversal.h
- test/passes/rse_all-features.txt
- test/passes/rse_all-features.wast
This adds EH instruction support for `CFGWalker`. This also implements
`call` instruction handling within a try-catch; every call can possibly
throw and unwind to the innermost catch block.
This adds tests for RedundantSetElimination pass, which uses
`CFGWalker`.
> Add EH support for CFGWalker

- scripts/fuzz_opt.py
It is convenient to have the full command when debugging fuzzing errors.
The fuzzer sometimes fails before running `wasm-reduce` and being able
to reproduce the command right away from the log is very handy in that
case.
> Remove limit in the log length in fuzz_opt.py

- src/wasm/wasm-binary.cpp
Instead of hackishly advancing the read position in the
binary buffer, call `readExpression` which will do that, and
also do all the debug info handling for us.
> Simplify binary parsing a little

- src/wasm.h
- third_party/llvm-project/DWARFVisitor.cpp
Fixes the testcase in https://github.com/WebAssembly/binaryen/issues/2343#issuecomment-575704484
Looks like that's from Rust. Not sure why it would have an invalid
abbreviation code, but perhaps the LLVM there emits dwarf differently
than we've tested on so far. May be worth investigating further, but
for now emit a warning, skip that element, and don't crash.
Also fix valgrind warnings about Span values not being initialized,
which was invalid and bad as well (wasted memory in our maps,
and might have overlapped with real values), and interfered with
figuring this out.
> Handle an invalid AbbrCode in DWARF handling

- src/wasm-binary.h
- src/wasm-stack.h
- src/wasm.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-debug.cpp
- src/wasm/wasm-stack.cpp
- test/passes/fannkuch3.bin.txt
- test/passes/fannkuch3_manyopts.bin.txt
Control flow structures have those in addition to the normal span of
(start, end), and we need to track them too.
Tracking them during reading requires us to track control flow
structures while parsing, so that we can know to which structure
an end/else/catch refers to.
We track these locations using a map on the side of instruction
to its "extra" locations. That avoids increasing the size of the
tracking info for the much more common non-control flow
instructions.
Note that there is one more 'end' location, that of the function
(not referring to any instruction). I left that to a later PR to
not increase this one too much.
> DWARF: Track the positions of 'end', 'else', 'catch' binary locations

- src/wasm.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-debug.cpp
- test/passes/fib2.bin.txt
DWARF from LLVM can refer to the first byte belonging to the function,
where the size LEB is, or to the first byte after that, where the local
declarations are, or the end opcode, or to one byte past that which is
one byte past the bytes that belong to the function. We aren't sure why
LLVM does this, but track it all for now.
After this all debug line positions are identified. However,
in some cases a debug line refers to one past the end of the
function, which may be an LLVM bug. That location is ambiguous
as it could also be the first byte of the next function (what
made this discovery possible was when this happened to the
last function, after which there is another section).
> DWARF: Track more function locations

- src/wasm/wasm-debug.cpp
- test/passes/fannkuch3.bin.txt
- test/passes/fannkuch3_manyopts.bin.txt
- test/passes/fib2.bin.txt
- test/passes/ignore_missing_func.bin.txt
- test/passes/multi_line_table.bin.txt
While line and address values of 0 should be skipped, it
seems like column 0 are valid lines emitted by LLVM.
> DWARF: Allow debug lines with column 0

- src/wasm/wasm-debug.cpp
- test/passes/fannkuch3.bin.txt
- test/passes/fannkuch3_manyopts.bin.txt
- test/passes/fib2.bin.txt
- test/passes/ignore_missing_func.bin.txt
- test/passes/multi_line_table.bin.txt
We need to track end_sequence directly, and use either
end_sequence or copy (copy emits a line without marking
it as ending a sequence).
After this, fib2 debug line output looks perfect.
> DWARF: Use end_sequence and copy properly

- src/wasm/wasm-debug.cpp
- test/passes/fannkuch0.bin.txt
- test/passes/fannkuch3.bin.txt
- test/passes/fannkuch3_manyopts.bin.txt
- test/passes/fib2.bin.txt
- test/passes/ignore_missing_func.bin.txt
Pretty straightforward given all we have so far.
Note that fannkuch3_manyopts has an example of
a sequence of ranges of which some must be skipped
while others must not, showing we handle that by
skipping the bad ones and updating the remaining.
> DWARF: Update Ranges

- src/passes/LegalizeJSInterface.cpp
I missed this in the review of #2451 - this was doing quadratic
work, each function touched the entire array which is the size
of the functions.
This speeds up the pspdfkit testcase from the mailing list from
several minutes (15 on CI; I stopped measuring after 2 minutes
locally) to 5 seconds. I suspect this was not noticed earlier because
that testcase has a very large number of functions, which
hit this issue especially hard.
> Initialize the LegalizeJSInterface vector once, not once in each function

- CMakeLists.txt
This can occurs in a shallow clone for example that doesn't have
any version tags in its history.  This is happening on travis CI
which is causing the builds to fail since travis uses `--depth=50`
when it clones.
Fixes #2617
> Don't error out if `git describe` fails

- src/passes/PostEmscripten.cpp
We should be looking at the import name when determining if a function
is an invoke function.
This is a precursor to re-landing the fix for
https://github.com/emscripten-core/emscripten/issues/9950.
> Consistent detection of invoke_ functions in PostEmscripten.cpp

- .travis.yml
Using 13 led to a problem when they updated to 13.7.0, which
breaks our ES module test suite integration. It's not clear to me
if those are bugs or not. One change is we now get file://X paths
instead of X in node-esm-loader.js, but working around that isn't
enough, as even once the path is correct, it doesn't even try to
load the env.js file, it just says it doesn't have the requested export,
so the behavior has changed quite a bit it seems, perhaps
intentionally. Rather than spend more time, it seems safer to just
use the LTS release there. (But if this is intended and it reaches
LTS, we'll need to investigate more.)
fixes #2615
> Use node LTS in Alpine

- src/wasm/wasm-debug.cpp
- test/passes/fannkuch0.bin.txt
- test/passes/fannkuch3.bin.txt
- test/passes/fannkuch3_manyopts.bin.txt
- test/passes/fib2.bin.txt
The LLVM SData field is 64-bit (to support 64-bit
addresses I suppose) so when we assigned to it we
actually led it to emit an LEB for a signed 64-bit value
that is an unsigned 32-bit one. This worked in LLVM
(where I guess it forces the value to 32-bit anyhow?)
but failed in gimli (where I guess it doesn't?).
Found by @RReverser
> DWARF: Properly emit signed 32 bit values for advance_line

- src/wasm/wasm-debug.cpp
- third_party/llvm-project/DWARFEmitter.cpp
- third_party/llvm-project/include/llvm/ObjectYAML/DWARFEmitter.h
The debug_line section is the only one in which we change
sizes and so must update offsets. It turns out that there are such
offsets, `DW_AT_stmt_list`, so without updating them we can't
handle multi-unit dwarf files.
This enables the fix after it which will also come with a test
for them both.
> DWARF: Update DW_AT_stmt_list which are offsets into the debug_line section

- src/tools/fuzzing.h
We've been throwing some fuzzing at some wasm implementations recently
and one of our strategies is to use `wasm-opt -ttf` with the fuzzer's
input to generate a wasm module. Some of our tests, though, have been
failing due to out-of-memory while `wasm-opt` is generating a module.
This loop appears to be infinitely executing since the input
just-so-happens that `oneIn(3)` returns true for every byte of the input
file, or at least enough such that when the xor factor is merged in it
at least generates very long sequence of `true`.
It looks like elsewhere in the file when `while (oneIn(N))` is used it's
also guarded by `!finishedInput`, so I've added a similar guard here as
well.
> Avoid an infinite loop in `-ttf` generation

- src/ir/hashed.h
- src/passes/LocalCSE.cpp
- src/wasm/wasm-validator.cpp
- test/passes/flatten_local-cse_all-features.txt
- test/passes/flatten_local-cse_all-features.wast
Now that we have subtypes, we cannot reuse any local that contains the
same expression, because that local's type can be a supertype. For
example:
```
(local $0 anyref)
(local $1 nullref)
...
(local.set $0 (ref.null))
(local.set $1 (ref.null)) ;; cannot be replaced with (local.get $0)
```
This extends `usables` map's key to contain both `HashedExpression` and
the local's type, so we can get the right usable local in the presence of
subtypes.
> Fix LocalCSE's usable local selection

- src/passes/pass.cpp
- test/passes/fannkuch3_manyopts.bin.txt
Anything that merges/swaps/etc. locals, or inlines, or merges functions,
must be disabled for now. However, that does still leave almost all
passes, so this should not affect output sizes much (and the full LLVM
optimizer can be run before too).
Over time we can resolve each of those FIXMEs.
The test output here shows how disabling those allows over twice as
much debug_line info to be preserved.
> DWARF: Disable optimization passes not fully compatible with DWARF yet

- .travis.yml
- explicitly name each job so its clear in the UI.
- split flake8 out into its own job rather than running it N times.
- rename the `build` phase to `archive` since build could mean any
number of things (normally it means that thing you do before testing
not after).
> Cleanup travis configuration

- src/binaryen-c.cpp
- src/binaryen-c.h
- src/js/binaryen.js-post.js
- test/binaryen.js/low-memory-unused.js
- test/binaryen.js/low-memory-unused.js.txt
- test/binaryen.js/pass-arguments.js
- test/binaryen.js/pass-arguments.js.txt
Allows a user to enable/disable the `lowMemoryUnused` option and to get/set/clear arbitrary pass arguments when using the C- or JS-APIs.
* binaryen.**getLowMemoryUnused**(): `boolean`
* binaryen.**setLowMemoryUnused**(on: `boolean`): `void`
* binaryen.**getPassArgument**(key: `string`): `string | null`
* binaryen.**setPassArgument**(key: `string`, value: `string | null`): `void`
* binaryen.**clearPassArguments**(): `void`
> Add C-/JS-APIs for lowMemoryUnused and pass arguments

- src/passes/Vacuum.cpp
- test/passes/vacuum_all-features.txt
- test/passes/vacuum_all-features.wast
If try's body does not throw, the whole try-catch can be replaced with
the try body.
> Optimize Try in Vacuum

- src/wasm2js.h
- test/wasm2js/emscripten-grow-no.2asm.js
- test/wasm2js/emscripten-grow-no.2asm.js.opt
- test/wasm2js/emscripten-grow-yes.2asm.js
- test/wasm2js/emscripten-grow-yes.2asm.js.opt
- test/wasm2js/emscripten.2asm.js
- test/wasm2js/emscripten.2asm.js.opt
Fix missing newline after // EMSCRIPTEN_START_FUNCS and // EMSCRIPTEN_END_FUNCS markers.
I am getting incorrect codegen in some build modes with wasm2js code being emitted on the same line as `// EMSCRIPTEN_START_FUNCS`, and all the rest of it is being treated as a comment. It does not always occur though, so I am not sure what kind of interaction is needed for it to happen. Hopefully this fixes it up.
> Fix missing newline after // EMSCRIPTEN_START_FUNCS and // EMSCRIPTEN_END_FUNCS markers.

- scripts/test/node-esm-loader.mjs
An attempt to fix the node-esm-loader related [issues](https://travis-ci.org/WebAssembly/binaryen/jobs/649056649#L22931) seen on CI currently, apparently due to CI automatically picking up a newer node LTS (12.16.0 released 2020/02/11) where the API changed.
> Update node-esm-loader to work with latest node LTS

- .travis.yml
On archive configs, cmake does not generate build.ninja but we try to
use it. This is currently causing failures on Travis builds for commits.
> Fix Ninja build on Travis archive configurations

- src/dataflow/graph.h
- src/passes/CodePushing.cpp
- src/passes/Vacuum.cpp
- src/wasm-traversal.h
- test/passes/code-pushing_all-features.txt
- test/passes/code-pushing_all-features.wast
Like `br_if`, `br_on_exn` is a conditional branch and across which code
can be pushed past when conditions are satisfied.
Also adds a few lines of comments and NFC changes in a couple places.
Changes in Vacuum are NFC because they were being handled in `default:`
in the same way anyway, but I added them to be more explicit and
consistent with existing code.
> Code pushing support for br_on_exn

- src/parsing.h
- test/passes/inlining_all-features.txt
- test/passes/inlining_all-features.wast
This adds support for UniqueNameMapper, and adds a test in Inlining
pass, which uses UniqueNameMapper.
> Add br_on_exn support for UniqueNameMapper

- src/asm2wasm.h
For the provided test case, fastcomp emits
```js
function _main($0,$1) {
$0 = $0|0;
$1 = $1|0;
var $2 = 0, $3 = 0, $4 = 0, $5 = 0, $6 = 0, $7 = 0, $8 = 0, $9 = 0, label = 0, sp = 0;
sp = STACKTOP;
STACKTOP = STACKTOP + 16|0; if ((STACKTOP|0) >= (STACK_MAX|0)) abortStackOverflow(16|0);
$4 = sp + 10|0;
$2 = $0;
$3 = $1;
store1($4,10);
$5 = 1;
$6 = 2;
$7 = $5;
$8 = $6;
$9 = (Atomics_compareExchange(HEAP8, $4,$7,$8)|0);
STACKTOP = sp;return 0;
}
```
whereas Binaryen was expecting the CAS operation to read
```js
$9 = (Atomics_compareExchange(HEAP8, $4>>0,$7,$8)|0);
```
With the change in this PR, the test case added in https://github.com/juj/emscripten/commit/e2ec4b779bae17a19d420a0ef106c9477ea84fa6 passes for me with fastcomp.
> Fix to https://github.com/WebAssembly/binaryen/issues/2170

- src/ir/iteration.h
- src/passes/CodeFolding.cpp
- test/passes/remove-unused-names_code-folding_all-features.txt
- test/passes/remove-unused-names_code-folding_all-features.wast
This does two things:
- Treats the target branch of `br_on_exn` as unoptimizables, because it
is a conditional branch.
- Makes sure we don't move expressions that contain `exnref.pop`, which
should follow right after `catch`.
- Adds `containsChild` utility function, which can search all children,
optionally with limited depth. This was actually added to be used in
CodeFolding but ended up not being used, but wasn't removed in case
there will be uses later.
> Add EH support for CodeFolding

- third_party/llvm-project/raw_ostream.cpp
On OpenBSD (6.6) libc++ fileno seems to be defined as a MACRO which cannot support the :: qualifier.
> Fix build issue due to ::fileno() on OpenBSD

- src/wasm-stack.h
- src/wasm/wasm-stack.cpp
Updates `BinaryInstWriter::mapLocalsAndEmitHeader` so it no longer hardcodes
each possible local type. Also adds a new inner loop over the elements of any
local tuple type in the IR. Updates the map from IR local indices to binary
indices to be additionally keyed on the index within a tuple type. Since we do
not generate tuple types yet, this additional index is hardcoded to zero
everywhere it is used for now. A later PR adding tuple creation operations will
extend this functionality and add tests.
> Generalize binary writing for tuples

- src/ir/module-utils.h
- src/passes/Asyncify.cpp
- test/unit/test_asyncify.py
We assumed that the imports were already named (in their
internal name) properly. When processing a binary file without
names, or if the names don't match in general, that's not true.
To fix this, use `ModuleUtils::renameFunctions` to do a proper
renaming up front.
Also fix `renameFunctions` to not assert on the case of
renaming a function to the same name it already has.
Helps #2680
cc @RReverser
> Asyncify: Fix wasm-only instrumentation of unnamed imports

- src/literal.h
- src/passes/Precompute.cpp
- src/passes/SimplifyGlobals.cpp
- src/shell-interface.h
- src/support/small_vector.h
- src/tools/execution-results.h
- src/tools/wasm-ctor-eval.cpp
- src/tools/wasm-shell.cpp
- src/wasm-interpreter.h
- src/wasm-type.h
- src/wasm.h
- src/wasm/literal.cpp
- src/wasm/wasm.cpp
- test/spec/multivalue.wast
Updates the interpreter to properly flow vectors of values, including
at function boundaries. Adds a small spec test for multivalue return.
> Handle multivalue returns in the interpreter

- src/ir/properties.h
- src/passes/RedundantSetElimination.cpp
- test/passes/rse_all-features.txt
- test/passes/rse_all-features.wast
Also makes it work with any other constant expression such as a
ref.func or ref.null instructions. This optimization may not be very
important, but it illustrates how simple it can be to update a pass to
handle tuples (and also I was already looking at it because of the
prior changes that had to be made to it).
> Update RedundantSetElimination to work with tuples

- src/wasm/wasm-binary.cpp
- src/wasm/wasm-stack.cpp
It should be a signed LEB128, not an unsigned LEB128. This bug was
causing modules to be invalid when the number of signatures in the
type section was large and multivalue blocks were present.
> Fix binary emitting of signature indices

- src/ir/literal-utils.h
- src/passes/SimplifyGlobals.cpp
- src/tools/wasm-reduce.cpp
- src/wasm-builder.h
- src/wasm-interpreter.h
I think we discussed this before but I don't remember what
we decided. But in recent PRs it's been a little confusing to
me to have `makeConstExpression` not return a `Const`.
The meaning we intend is "constant", so I think the full
name is less confusing.
Thoughts?
> makeConstExpression => makeConstantExpression

- scripts/fuzz_opt.py
Tuple operations lower to stacky code, so round tripping from IR to
binary and back is a lossy operation. To help make diagnosing bugs
uncovered by the fuzzer easier, this change writes the original IR
generated by the fuzzer and the IR produced by optimizations to files
that can be inspected after a crash to determine exactly what IR was
emitted.
> Dump initial wasts in fuzzer

- src/wasm-stack.h
We previously though unreachable `tuple.make` instructions did not
require special unreachable handling, but consider the following wast:
```
(module
(func $foo
(tuple.make
(unreachable)
(i32.const 42)
)
)
)
```
This validates because the only expression in the body is unreachable,
but when it is emitted as a binary it becomes
```
unreachable
i32.const 42
```
This does not validate because it ends with an i32, but the function
expected an empty stack at the end. The fix is to emit an extra
`unreachable` after unreachable `tuple.make`
instructions. Unfortunately it is impossible to write a test for this
right now because the binary parser silently drops the `i32.const 42`,
making the function valid again.
> Emit unreachable tuple.make properly

- src/wasm/wasm-validator.cpp
Some optimizations may replace tuple elements with simpler values, and
those simpler values may be a subtype of the original value. Tuple
operations should continue to validate without being refinalized in
these cases.
> Allow subtypes in tuple operations

- src/wasm/wasm-binary.cpp
The version of V8 pulled in by JSVU recently updated to expect the new ordering of the event section, so this PR should fix the CI.
> Fix Event section ordering

- src/passes/Asyncify.cpp
We decided it would be easier to allow tuple-typed globals than to
make calls work here after all.
> Revert to using globals in Asyncify call support

- src/ir/global-utils.h
- src/ir/module-utils.h
- src/passes/Print.cpp
- src/passes/SimplifyGlobals.cpp
- src/shell-interface.h
- src/tools/wasm-ctor-eval.cpp
- src/wasm-interpreter.h
- src/wasm-s-parser.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-s-parser.cpp
- src/wasm/wasm-stack.cpp
- src/wasm/wasm-validator.cpp
- test/multivalue.wast
- test/multivalue.wast.from-wast
- test/multivalue.wast.fromBinary
- test/multivalue.wast.fromBinary.noDebugInfo
- test/spec/multivalue.wast
Since it wasn't easy to support tuples in Asyncify's call support
using temporary functions, we decided to allow tuple-typed globals
after all. This PR adds support for parsing, printing, lowering, and
interpreting tuple globals and also adds validation ensuring that
imported and exported globals do not have tuple types.
> Tuple globals

- src/tools/fuzzing.h
- test/passes/translate-to-fuzz_all-features.txt
- test/passes/translate-to-fuzz_no-fuzz-nans_all-features.txt
Unless the multivalue feature is enabled. The validation for events
recently changed to disallow events returning multiple items unless
the multivalue feature is enabled, but the fuzzer was not updated
accordingly. This PR fixes the glitch.
> Do not emit multivalue events in fuzzer

- scripts/test/lld.py
- src/tools/wasm-emscripten-finalize.cpp
- test/lld/bigint.wat
- test/lld/bigint.wat.out
If wasm-emscripten-finalize is given the BigInt flag, then we will
be using BigInts on the JS side, and need no legalization at all
since i64s will just be BigInts.
> BigInt support

- src/wasm/wasm-emscripten.cpp
- test/lld/main_module.wat
- test/lld/main_module.wat.out
- test/lld/shared.wat.out
- test/lld/shared_add_to_table.wasm.out
Weak symbols and interposition etc. mean that we should not
replace an `fp$` call with a symbol from the module itself if there
is a chance there is another symbol that would have overridden it.
In side modules this risk exists and so this PR makes us stop
doing that. In main modules it is ok because they are loaded
first and so any symbol they provide will "win" over others anyhow.
> Only do fp$ optimization in the main module

- src/passes/ReorderLocals.cpp
I think the history here is that `localNames` used to be a
vector, then we made it a map, but didn't update this pass...
so in rare cases it could end up emitting wrong stuff.
> Fix ReorderLocals handling of local names

- src/passes/CoalesceLocals.cpp
- src/wasm2js.h
`coalesce-locals` is nonlinear in the number of locals, so it is
greatly beneficial to reorder the locals (which then drops the
unused ones at the end automatically). The default passes
do this already, but wasm2js does some custom work, and
this was missing.
With this change that pass takes 10x less time on poppler
with `--flatten --flatten --simplify-locals-notee-nostructure`
which approximates what wasm2js does.
> Run reorder-locals more in wasm2js

- scripts/test/shared.py
It looks like these were only uses as part of the vanilla tests
which were removed back in #2482.
> Remove references to vanilla emcc

- scripts/test/asm2wasm.py
- scripts/test/binaryenjs.py
- scripts/test/lld.py
- scripts/test/wasm2js.py
These are no all driven by only by the two top level scripts:
-  check.py
-  auto_update_tests.py
What is more all of them were broken when run isolation due to
relative import rules in python3.  e.g.:
```
$ scripts/test/binaryenjs.py
Traceback (most recent call last):
File "scripts/test/binaryenjs.py", line 21, in <module>
from . import shared
ImportError: cannot import name 'shared' from '__main__' (scripts/test/binaryenjs.py)
```
> Remove executable bit from test scripts

- src/wasm-type.h
- src/wasm/wasm-type.cpp
- src/wasm/wasm.cpp
Cache type sizes in unused bits from the type ID and rewrite some Type
methods to avoid unnecessary calls to `expand` when the type is known
to be a basic non-tuple type. This eliminates most of the locking
traffic and reduces wall clock time by 52% and CPU time by 73% percent
for one real-world program on my machine.
> Performance optimizations for Type

- setup.cfg
I believe this was originally used to drive the pep8 (which is now
called pycodestyle) and flake8 (which we still use and is configured
via the .flake8 file).  Its clear it hasn't been used in a while since
the warning suppressions are all wrong now (no now use 4 space indents).
> Remove old setup.cfg

- README.md
General multivalue and stacky code is now represented using
tuples. Push should never be used and should be removed, and pop
should only be used for exception catch blocks.
> [NFC] Update readme to discuss tuples rather than push/pop

- src/passes/Asyncify.cpp
- src/wasm-type.h
- src/wasm/wasm-type.cpp
- test/passes/asyncify_enable-multivalue.txt
- test/passes/asyncify_enable-multivalue.wast
Instead of adding globals for hardcoded basic types, traverse the
module to collect all call types that might need to be handled and
emit a global for each of them. Adapted from #2712.
> Handle tuples in Asyncify call support

- src/wasm/wasm-type.cpp
Avoid taking the type interning lock to look up the size when the
provided ID corresponds to a statically known type. This eliminates a
considerable amount of unnecessary lock traffic when using the C or JS
APIs.
> Optimize uint32_t Type constructor

- src/passes/SimplifyGlobals.cpp
- src/passes/pass.cpp
- test/emcc_O2_hello_world.fromasm
- test/emcc_O2_hello_world.fromasm.clamp
- test/emcc_O2_hello_world.fromasm.imprecise
- test/emcc_hello_world.fromasm
- test/emcc_hello_world.fromasm.clamp
- test/emcc_hello_world.fromasm.imprecise
- test/memorygrowth.fromasm
- test/memorygrowth.fromasm.clamp
- test/memorygrowth.fromasm.imprecise
- test/passes/O1.txt
- test/passes/O4_disable-bulk-memory.txt
- test/passes/simplify-globals-optimizing_enable-mutable-globals.txt
- test/passes/simplify-globals_all-features.txt
- test/passes/simplify-globals_all-features.wast
- test/wasm2js/global_i64.2asm.js.opt
Since the global is never read, we know that any write operation
will be unobservable.
> Remove writes to globals that are never written to

- src/passes/SimplifyGlobals.cpp
- src/passes/pass.cpp
- test/passes/O1.txt
Based on freedback in #2741 it looks like we can use the existing
`simplify-globals-optimizing` pass to trigger this cleanups we need.
> Remove redundant vacume pass.  Followup on #2741

- src/tools/fuzzing.h
- test/passes/translate-to-fuzz_all-features.txt
- test/passes/translate-to-fuzz_no-fuzz-nans_all-features.txt
The fuzzer was previously unconditionally emitting one event parameter
more than it was supposed to, which meant multivalue events were
emitted when multivalue was not enabled.
> Fix multivalue event fuzzing

- src/asm2wasm.h
- src/tools/fuzzing.h
- src/wasm2js.h
These seem to be accidentally introduced in when we enforced use of
`Type::` on type names in #2434.
By the way TIL this actually compiles, and don't know why:
```
Type::Type::Type::Type::Type::Type::Type::Type::none
```
> Remove duplicate Type:: prefixes (NFC)

- src/passes/SimplifyGlobals.cpp
- test/passes/O1.txt
- test/passes/simplify-globals-optimizing_enable-mutable-globals.txt
- test/passes/simplify-globals-optimizing_enable-mutable-globals.wast
- test/passes/simplify-globals_all-features.txt
We shouldn't actually nop, we forgot that the value may have
side effects, so just drop it (opts will remove it later, if possible).
> Fuzz fix for SimplifyGlobals nopping

- check.py
- src/shell-interface.h
- test/passes/fuzz-exec_O.txt
We used `std::cerr` as a workaround for that this logging
interfered with spec testing. But it's easy enough to filter
out this stuff for the spec tests.
The benefit to using `std::cout` is that as you can see in
the test output here, this is relevant test output - it's not
a side channel for debugging. If the rest of the interpreter
output is in `std::cout` but only traps are in `std::cerr` then
they might end up out of order etc., so best to keep them
all together.
This will allow easier additions of tests for fuzz testcases
that I am working on now.
> Use std::cout for interpreter trap logging

- check.py
The test there just wants to see that the reducer can remove
a significant amount of code. I changed it from a file of 3.6K
to 200 bytes, which is enough to see the effect, and much faster
(10x on that test - oddly on my laptop that test is one of the
slowest to run, which I'm not sure was the case on my desktop
back in the office).
> Speed up wasm-reduce test

- scripts/test/wasm2js.py
- src/tools/wasm2js.cpp
- src/wasm2js.h
- test/wasm2js/deterministic.2asm.js
- test/wasm2js/deterministic.2asm.js.opt
- test/wasm2js/deterministic.wast
In wasm2js we ignore things that trap in wasm that we can't
really handle, like a load from memory out of bounds would
trap in wasm, but in JS we don't want to emit a bounds check
on each load. So wasm2js focuses on programs that don't
trap.
However, this is annoying in the fuzzer as it turns out that
our behavior for places where wasm would trap was not
deterministic. That is, wasm would trap, wasm2js would not
trap and do behavior X, and wasm2js with optimizations
would also not trap but do behavior Y != X. This produced
false positives in the fuzzer (and might be annoying in
manual debugging too).
As a workaround, this adds a `--deterministic` flag to wasm2js,
which tries to be deterministic about what it does for cases
where wasm would trap. This handles the case of an int
division by …
> Add --deterministic flag to wasm2js, for fuzzing

- scripts/test/shared.py
Two no longer exist, after I believe they were enabled
by default.
The new staging flag should help us avoid to add many new
specific flags in the future.
> Update v8 flags

- src/binaryen-c.cpp
- src/binaryen-c.h
- src/passes/LocalCSE.cpp
- src/wasm-type.h
- src/wasm/wasm-type.cpp
- test/binaryen.js/custom-section.js.txt
- test/binaryen.js/inlining-options.js.txt
- test/binaryen.js/kitchen-sink.js
- test/binaryen.js/kitchen-sink.js.txt
- test/binaryen.js/low-memory-unused.js.txt
- test/binaryen.js/pass-arguments.js.txt
- test/example/c-api-kitchen-sink.txt
Instead of using indices into the global interned type table. This
means that a lock is *never* needed to access an expanded Type. The
Type lock is now only acquired when a complex Type is created. On a
real-world wasm2js workload this improves wall clock time by 23% on my
machine with 72 cores and makes traffic on the Type lock entirely
insignificant.
**Before**
72 cores
real    6.914s
user    184.014s
sys     3.995s
1 core
real    25.903s
user    25.658s
sys     0.253s
**After**
72 cores
real    5.349s
user    70.309s
sys     9.691s
1 core
real    25.859s
user    25.615s
sys     0.253s
> Use direct pointers as Type IDs

- src/passes/Vacuum.cpp
- test/passes/vacuum_all-features.txt
- test/passes/vacuum_all-features.wast
When it is certain that the try body does not throw, we can replace the
try-catch with the try body. But in this case we have to notify the type
updater that the catch body is removed, so that all parents' type should
be updated properly.
> Note removal of catch body in Vacuum

- src/passes/Precompute.cpp
- test/passes/precompute_all-features.txt
- test/passes/precompute_all-features.wast
Previously we tried to reuse `Const` node if a precomputed value is a
constant node. But now we have two more kinds of constant node
(`RefNull` and `RefFunc`), so we shouldn't reuse them interchangeably,
meaning we shouldn't try to reuse a `Const` node when the value at hand
is a `RefNull`. This correctly checks the type of node and tries to
reuse only if the types of nodes match.
Fixes #2759.
> Fix reuse of constant nodes in Precompute

- check.py
- scripts/fuzz_opt.py
- src/tools/fuzzing.h
- test/passes/translate-to-fuzz_all-features.txt
- test/passes/translate-to-fuzz_no-fuzz-nans_all-features.txt
tuple.make and tuple.extract instructions are always enabled, but
control flow is only allowed to have tuple types when the multivalue
feature is enabled. Also slightly refactors the top-level
`makeConcrete` function to be more selective about what it tries to
make based on the requested type to reduce the number of trivial nodes
created because the requested type is incompatible with the requested
node.
Note that this should probably not be merged yet because it is still turning
up new bugs after just a few iterations.
> Emit tuples in the fuzzer

- src/tools/fuzzing.h
We should only do weird changes to the fuzz code if we
allow out of bounds operations, because the OOB checks
are generated as we build the IR, and changing them can
remove the checks.
(we fuzz 50% of the time with and 50% without OOBs,
so this doesn't really hurt us)
> Fix oob fuzzing

- src/wasm/wasm-validator.cpp
This was previously an unwritten and unchecked assumption.
> Validate that tuples have multiple operands

- scripts/fuzz_opt.py
I thought the line at the end was a mistake, but maybe it was
intentional? Anyhow I think disabling it up front, with a comment,
might be clearer.
> Disable multivalue in fuzzer in a clearer way

- src/wasm-interpreter.h
- test/spec/exception-handling.wast
This adds dummy interpreter support for EH instructions, mainly for
fuzzing. The plan is to make the interpreter support for EH instructions
correctly using Asyncify in the future. Also to support the correct
behavior we will need a `Literal` of `exnref` type too, which will be
added later too.
Currently what this dummy implementation does is:
- `try`-`catch`-`end`: only runs `try` body and ignores `catch` body
- `throw`: traps
- `retyrow`:
- Traps on nullref argument (correct behavior based on the spec)
- Traps otherwise too (dummy implementation for now)
- `br_on_exn`:
- Traps on nullref (correct behavior)
- Otherwise we assume the current expression matches the current event
and extracts a 0 literal based on the current type.
This also adds some interpreter tests, which tests the basic …
> Dummy interpreter support for EH

- scripts/fuzz_opt.py
- src/tools/fuzzing.h
- src/wasm/wasm-type.cpp
1. Only emit exnref as part of a subtype if exception-handling is
enabled in the fuzzer.
2. Correctly report that funcref and nullref require reference-types
to be enabled.
3. Re-enable multivalue as a normal feature in the fuzzer.
Possibly fixes #2770.
> Fix issues with Types and Features

- .travis.yml
These have not been working since #1554, where we switch to using
an alpine docker image rather than the alpine sysroot install
script (that honors the ARCH environment variable).
So nobody has noticed in the last 2 years that we've been releasing
copies of x86_64 binaries.  e.g: this file actually contains x86_64
binaries:
https://github.com/WebAssembly/binaryen/releases/download/version_91/binaryen-version_91-aarch64-linux.tar.gz
What is more its not really our job to release binaries for all these
different architectures.  We can let downstream distos do that.
Node itself doesn't 32bit x86 linux images.
> Remove non-x86_64 architectures build from our travis config

- src/wasm/wasm-emscripten.cpp
- test/lld/longjmp.wat.out
- test/lld/shared_longjmp.wat.out
Without this change only the import gets renamed not the internal
name. Since the internal name is the one that ends up in the name
section this means that rename wasn't effecting the name section.
> Also update internal name in fixEmJsFuncsAndReturnWalker

- src/tools/wasm-reduce.cpp
Without this we emitted binary, which confused the size comparisons.
> Emit text in pass reduction when in text mode

- src/js/binaryen.js-post.js
- test/binaryen.js/kitchen-sink.js
- test/binaryen.js/tail_calls.js
This fixes the broken `return_call`/`return_call_indirect` methods in `binaryen.js`.
> Add snake_case method names for returnCall/returnCallIndirect in JS API

- .github/workflows/build_release.yml
- .github/workflows/ci.yml
The alpine linux build exists to produce portable binaries.  It should
be used when building release assets, rather than during CI.
> CI: Use alpine linux when building official linux releases

- .github/workflows/ci.yml
For inter-repository PRs that branch is not pushed to the main repo
so was not triggering in that case.  I'm just hoping it doesn't end
up triggering twice for intra-repository PRs (like this one).
> CI: Also triggers on pull_request

- src/passes/RemoveUnusedNames.cpp
- test/passes/remove-unused-names.txt
- test/passes/remove-unused-names.wast
> Fix RemoveUnusedNames on a loop with no name and a child with a different type

- scripts/fuzz_opt.py
- src/tools/wasm2c-wrapper.h
This adds a variant on wasm2c that uses emcc instead of a
native compiler. This helps us fuzz emcc.
To make that practical, rewrite the setjmp glue to only use one
setjmp. The wasm backend ends up doing linear work per setjmp,
so it's quadratic with many setjmps. Instead, do a big switch-loop
construct around a single setjmp.
> Wasm2c2Wasm Fuzzer: wasm2c + emcc

- auto_update_tests.py
- check.py
- scripts/emcc-tests.sh
- scripts/test/binaryenjs.py
These tests are now optional. However, if you run them and the
build is not found they will now error out, in order to avoid silently
failing.
> Fix binaryenjs testing

- .github/workflows/ci.yml
- src/binaryen-c.cpp
- src/passes/Precompute.cpp
- src/wasm-interpreter.h
Tackles the concerns raised in https://github.com/WebAssembly/binaryen/issues/2797 directly related to https://github.com/WebAssembly/binaryen/pull/2702 by reverting merging all of `PrecomputeExpressionRunner` into the base `ExpressionRunner`, instead adding a common base for both the precompute pass and the new C-API to inherit. No functional changes.
---
```
ExpressionRunner
├ [PrecomputeExpressionRunner]
├ [CExpressionRunner]
├ ConstantExpressionRunner
└ RuntimeExpressionRunner
```
where `ExpressionRunner` contains functionality not utilized by `ConstantExpressionRunner` and `RuntimeExpressionRunner`.
```
ExpressionRunner
├ ConstantExpressionRunner
│  ├ [PrecomputeExpressionRunner]
│  └ [CExpressionRunner]
├ InitializerExpressionRunner
└ RuntimeExpressionRunner
```
with the precompute …
> Refactor ExpressionRunner

- scripts/fuzz_opt.py
Just like the parent wasm2c, with NaNs don't compare to self before
and after optimizations. The binaryen optimizer does different things than the
LLVM optimizer there, and NaN bits can change.
> Remove wasm2c2wasm can_compare_self

- src/tools/wasm2c-wrapper.h
The refactoring of the loop in #2812 was wrong - we need to
loop over all the exports and ignore the non-function ones.
Rewrote it to stress that part.
> Fix wasm2c loop

- scripts/fuzz_opt.py
* Don't run wasm2c2wasm on large wasm files, as it can OOM the VM.
I've seen this happen on a single wasm on multiple engines, so it's not
a specific engine bug. Sticking to below-average wasm sizes seems ok.
* That change means that we check if a vm can run on a per-wasm basis.
That required some refactoring as it means we may be able to run on
the "before" wasm but not the "after" one, or vice versa.
* Fix a tiny nondeterminism issue with iterating on a `set()`.
* Some tiny docs improvements to the error shown when a bug is found.
> fuzz_opt.py improvements

- src/passes/PostEmscripten.cpp
- src/wasm-emscripten.h
- src/wasm/wasm-emscripten.cpp
- test/passes/post-emscripten_pass-arg=stack-pointer@1234.txt
- test/passes/post-emscripten_pass-arg=stack-pointer@1234.wast
This allows emscripten to statically set the initial value of the
stack pointer.
Should allow use to avoid doing it dynamically at startup:
https://github.com/emscripten-core/emscripten/pull/11031
> Add stack-pointer argument to post-emscripten pass.

- .github/workflows/build_release.yml
- .github/workflows/ci.yml
Even though `Release` is the default configuration for make better
to be explicit.
Also, for windows build we need to make sure we pass `--config Release`
when actually building since the projects files will build Debug by
default regardless of CMAKE_BUILD_TYPE.
Fixes: #2825
> CI: Use stripped release builds for distribution

- src/wasm-features.h
GCC complains that the enclosing class of the constexpr member
function is not a literal type. This change removes the constexpr
qualifier to fix the GCC build.
Fixes #2827.
> Remove `constexpr` that causes GCC build to fail

- .github/workflows/ci.yml
We need to find another approach than MODULARIZE_INSTANCE, which
is not trivial. This unbreaks CI for now.
> Use emscripten latest, as tot has removed MODULARIZE_INSTANCE

- .github/workflows/ci.yml
- scripts/fuzz_opt.py
With this, when it finds a bug all you need to do is copy-paste
a single line and it runs the reducer. To do that, it creates a
reducer script and fills it out for you. The script has all the docs
we used to print out to the console, so the console output is
more focused and concise now.
In most cases just running the single line it suggests should
work, however I found that it doesn't always. One reason is
#2831
Also add a missing `sys.exit(1)`, without which we returned 0
despite printing out an error on a failing testcase.
> Make reduction even easier from fuzz_opt.py

- src/wasm-type.h
- src/wasm/wasm-type.cpp
This hopefully fixes a build problem on older GCC as reported in #2827.
> Move std::hash specializations into the std namespace

- CHANGELOG.md
Forgot to add a changelog entry covering the removal of API tracing (https://github.com/WebAssembly/binaryen/pull/2841).
> Mention removed API tracing in changelog

- src/passes/DeadCodeElimination.cpp
- test/passes/dce_all-features.txt
- test/passes/dce_all-features.wast
This adds missing handlings for `throw` and `rethrow` in DCE. They
should set `reachable` variable to `false`, like other branches.
> Handle throw and rethrow in DCE

- scripts/fuzz_opt.py
Currently the fuzzer only generate a script for wasm-reduce only when it
first discovers a case and doesn't do that when a seed is given. But
when you get a bug report with a seed or you want to reproduce the
situation, is still helpful if the fuzzer generates a reduce script for
you.
> Generate wasm-reduce scripts when given a seed too

- src/passes/MergeBlocks.cpp
- test/passes/remove-unused-names_merge-blocks_all-features.txt
- test/passes/remove-unused-names_merge-blocks_all-features.wast
This adds support for `throw`, `rethrow`, and `br_on_exn` in
MergeBlocks. While unrelated instructions within blocks can be hoisted
as in other instructions, `br_on_exn` requires a special handling in
`ProblemFinder`, because unlike `br_if`, its `exnref` argument itself
cannot be moved out of `br_on_exn`.
> Add EH support in MergeBlocks

- src/wasm/wasm-s-parser.cpp
- test/exception-handling.wast
- test/passes/dce_all-features.txt
- test/passes/dce_all-features.wast
- test/passes/remove-unused-names_code-folding_all-features.wast
- test/passes/remove-unused-names_optimize-instructions_all-features.wast
- test/passes/rse_all-features.wast
Previously we were able to omit the new syntax `do` when `try` body is
empty. This makes `do` clause mandatory, so when a `try` body is empty,
the folded text format will be
```
(try
(do)
(catch
...
)
```
Suggested in
https://github.com/WebAssembly/exception-handling/issues/52#issuecomment-626696720.
> Make 'do' clause mandatory in 'try'

- src/wasm/wasm-emscripten.cpp
This should allow https://github.com/emscripten-core/emscripten/pull/11166
to land, afterwhich we can completely remove these functions.
> Skip generating emscripten stack functions if they already exist

- src/ir/ReFinalize.cpp
- src/wasm-interpreter.h
- test/passes/precompute_all-features.txt
- test/passes/precompute_all-features.wast
In `ReFinalize`'s branch handling, `updateBreakValueType` is supposed to
be executed only when the branch itself is not replaced with its
argument (because it is guaranteed not to be taken).
Also this moves `visitBrOnExn` from `RuntimeExpressionRunner` to its
base class `ExpressionRunner`, because it does not depend on anything on
the runtime instance to work. This is effectively NFC for now because
`visitTry` is still only implemented only in `RuntimeExpressionRunner`
because it relies on multivalue handling of it, and without it we cannot
create a valid exception `Literal`.
> Fix br_on_exn handling in ReFinalize

- src/wasm/wasm-binary.cpp
That is only for the old source maps logic, not DWARF, and it is
only useful to debug source maps (it's not actually useful for
users that see the message) which we do not plan to do
since DWARF is the future.
> Don't warn 'skipping debug location info'

- scripts/test/generate_lld_tests.py
- scripts/test/lld.py
- test/lld/basic_safe_stack.s
- test/lld/basic_safe_stack.wat
- test/lld/basic_safe_stack.wat.out
This test verifies that functions in the llvm input source that
do stack pointer manipulation get correctly handled by
`wasm-emscripten-finalize --check-stack-overflow` (StackLimitEnforcer)
> Add additional test for --check-stack-overflow

- src/ir/effects.h
- src/passes/SimplifyLocals.cpp
- test/passes/simplify-locals_all-features.txt
- test/passes/simplify-locals_all-features.wast
- `br_on_exn`'s target block cannot be optimized to have a separate
return value. This handles that in `SimplifyLocals`.
- `br_on_exn` and `rethrow` can trap (when the arg is null). This
handles that in `EffectAnalyzer`.
- Fix a few nits
> Add EH support for SimplifyLocals

- auto_update_tests.py
- check.py
Without this I always catch an error during auto-update tests on Mac
```
FileNotFoundError: [Errno 2] No such file or directory: .../Github/binaryen/bin/example.dSYM'
```
> Fix issues with cleanup dSYM in scripts for MacOS

- README.md
With this changes when you click to CI badge you redirect to Github Actions tab
> Add link to Github Action tab for CI badge

- scripts/fuzz_shell.js
We need the memory to be exported in order to read and
write stuff for the asyncify data structure.
> Fuzz asyncify fuzzer: when no exported memory, skip

- src/passes/Flatten.cpp
- test/passes/flatten.bin.txt
- test/passes/flatten_all-features.txt
- test/passes/flatten_all-features.wast
- test/passes/flatten_i64-to-i32-lowering.txt
- test/passes/flatten_local-cse_all-features.txt
- test/passes/flatten_rereloop.txt
- test/passes/flatten_simplify-locals-nonesting_souperify-single-use_enable-threads.txt
- test/passes/flatten_simplify-locals-nonesting_souperify_enable-threads.txt
The special-casing of `unreachable` there could lead to bad
behavior, where we did nothing to the unreachable and ended
up moving something with side effects before it, see testcase
in `test/passes/flatten_all-features.wast`.
This emits less efficient code, but only if `--dce` was not run
earlier, so probably not worth optimizing.
> Flatten fuzz fix with unreachable special-casing

- check.py
We now put outputs of all other tests in out/test in order not to
pollute the test directory, but validator tests didn't have a output
file specified so their output files were written within test/validator.
This adds `-o a.wasm` to validator tests command lines, in the same way
as other tests, to make them go into out/test directory.
> Put validator test outputs in out/test

- src/passes/CodeFolding.cpp
- test/passes/remove-unused-names_code-folding_all-features.txt
- test/passes/remove-unused-names_code-folding_all-features.wast
In CodeFolding, we should not take an expression that may throw out of a
`try` scope. This patch adds this restriction in `canMove`.
> Prevent calls from escaping try in CodeFolding

- scripts/fuzz_opt.py
`FUZZ_OPTS` are things like `--denan` which affect generation of
the original wasm. We were passing those to testcase handlers,
which meant that in addition to the random optimizations we picked
they were also running `--denan` etc. again. That can be confusing,
so remove it.
> Fuzzer: Don't keep doing `--denan` etc. in testcase handlers

- scripts/fuzz_opt.py
We already avoid that in CompareVMs but Asyncify has the
same issue, as it also can optimize in binaryen but run in
another VM (with different nondeterministic NaN behavior).
> When fuzzing asyncify, avoid optimizations with nans

- scripts/fuzz_opt.py
When the fuzzer script is given a wasm we don't create a new
one from scratch. But we should still apply `--denan` and other
things so that we preserve those properties while reducing.
Without this it's possible for reduction to start with a wasm with
no nans but to lose the property eventually, and end up with a
reduced testcase which is not quite what you want.
> Fuzzing: Run --denan etc. even on a given wasm

- src/binaryen-c.cpp
- src/binaryen-c.h
- src/ir/effects.h
- src/js/binaryen.js-post.js
- src/passes/CodeFolding.cpp
- src/passes/SimplifyLocals.cpp
- test/binaryen.js/sideffects.js
- test/binaryen.js/sideffects.js.txt
- test/passes/simplify-locals_all-features.txt
- test/passes/simplify-locals_all-features.wast
This prevents `exnref.pop`s from being sinked and separated from
`catch`. For example,
```wast
(try
(do)
(catch
(local.set $0 (exnref.pop))
(call $foo
(i32.const 3)
(local.get $0)
)
)
)
```
Here, if we sink `exnref.pop` to remove `local.set $0` and
`local.get $0`, it becomes this:
```wast
(try
(do)
(catch
(nop)
(call $foo
(i32.const 3)
(exnref.pop)
)
)
)
```
This move was possible because `i32.const 3` does not have any side
effects. But this is incorrect because now `exnref.pop` does not follow
right after `catch`.
To prevent this, this patch checks this case in `canSink` in
SimplifyLocals. When we encountered a similar case in CodeFolding, we
prevented every expression that contains `Pop` anywhere in it from being
moved, which was too conservative. This adds `danglingPop` property in …
> Prevent pops from sinking in SimplifyLocals

- CMakeLists.txt
- src/asmjs/shared-constants.cpp
- src/asmjs/shared-constants.h
- src/tools/wasm2js.cpp
- src/wasm2js.h
Reland of #2864
Also ensure a relative install rpath by adding setup to each tool config.
The CMake code is cribbed from LLVM's implementation.
> Reland "Link binaryen tools against the dylib" 

- src/passes/SimplifyLocals.cpp
- test/passes/simplify-locals_all-features.txt
- test/passes/simplify-locals_all-features.wast
Expressions that may throw cannot be sinked into 'try'. At the start of
'try', we drop all sinkables that may throw.
> Prevent calls from sinking into 'try'

- src/tools/wasm-emscripten-finalize.cpp
- src/wasm-emscripten.h
- src/wasm/wasm-emscripten.cpp
The plan is that for standlone mode we can function just like wasi-sdk
and call the correct main from crt1.c.
For non-standalone mode we still want to export can call main directly
so we rename __main_argc_argv back to main as part of finalize.
See https://reviews.llvm.org/D70700
> Support new clang mangling of main (__main_argc_argv)

- src/wasm/wasm-emscripten.cpp
- test/lld/safe_stack_standalone-wasm.wat.out
- test/lld/standalone-wasm-with-start.wat.out
- test/lld/standalone-wasm.wat.out
- test/lld/standalone-wasm2.wat.out
- test/lld/standalone-wasm3.wat.out
The process of DCE'ing the argument handling is already handled in
a different way in standalone more.   In standalone mode the entry
point is `_start` which takes no args, and argv code is included
on-demand via the presence or absence the wasi syscalls for argument
processing (__wasi_args_get/__wasi_args_sizes_get).
> Default mainReadsParams to true in standalone mode

- src/wasm.h
- src/wasm/wasm.cpp
I have found that similar dump functions have been extremely helpful
while debugging LLVM. Rather than re-implement this locally whenever I
need it, it would be better have this utility upstream.
> Add Expression::dump for use while debugging

- src/passes/Asyncify.cpp
- test/passes/asyncify_pass-arg=asyncify-addlist@foo_pass-arg=asyncify-ignore-indirect.txt
- test/passes/asyncify_pass-arg=asyncify-addlist@foo_pass-arg=asyncify-ignore-indirect.wast
When doing manual tuning of calls using asyncify lists, we want it to
be possible to write out all the functions that can be on the stack when
pausing, and for that to work. This did not quite work right with the
`ignore-indirect` option: that would ignore all indirect calls all the
time, so that if `foo()` calls `bar()` indirectly, that indirect call was
not instrumented (we didn't check for a pause around it), even if
both `foo()` and `bar()` were listed. There was no way to make that
work (except for not ignoring indirect calls at all).
This PR makes the add-list and only-lists fully instrument the functions
mentioned in them: both themselves, and indirect calls from them.
(Note that direct calls need no special handling - we can just add
the direct call target to the add-list or …
> Asyncify: Instrument indirect calls from functions in add-list or only-list

- src/wasm/wasm-debug.cpp
- test/passes/fannkuch0.bin.txt
We must emit those, even if otherwise it looks like a line we can
omit, as the ends of sequences have important meaning and
dwarfdump will warn without them.
Looks like fannkuch0 in the test suite already had an example
of an incorrectly-omitted sequence_end, so no need for a new
testcase.
Verified that without this e.g. `wasm2.test_exceptions` with `-g`
added will lead to a wasm that warns, but with this PR the debug_line
section is reported as valid by dwarfdump.
> DWARF: Fix sequence_end emitting

- src/wasm/wasm-debug.cpp
- test/passes/fannkuch0.bin.txt
Previously we tracked sequence ends, so if an instruction was marked
as the end, we'd keep marking it that way in the output. However, if
X, Y, Z form a sequence that is then reordered into Z, Y, X then we need
to emit the end on X now.
To do that, give a "sequence number" to each debug line. Then when
emitting, we can tell if two adjacent lines are in a sequence or not, and
emit the end properly.
This fixes a large partner testcase, allowing
`llvm-dwarfdump --verify --debug-line` to pass on it.
With this change it is easier to remove the hackish handling of
`prologueEnd` that we had before, where we reset it. Instead, just
emit it when it is set, and that's all. In particular we can get rid
of the `// Reset the state` and `resetAfterLine()` calls in `emitDiff`.
That function now just …
> DWARF: Track sequences so that we can handle reordering within one

- src/wasm/wasm-debug.cpp
- test/passes/fannkuch3.bin.txt
- test/passes/fannkuch3_manyopts.bin.txt
- test/passes/fib2.bin.txt
`.debug_loc` entries can have bases: a value that all values after
it in the list are relative to. Previously we used to keep the base
value as it was, to keep things as similar to the original DWARF as
possible. However, if optimizations move code around so that the
values after the base are *before* the base, then the values could
no longer be emitted, and we skipped them in effect.
This PR makes us always pick a new base for each list. This
allows the base to always work for the values after it, but does
mean we change the lists quite a lot more. If there is any extra
meaning to the original bases here we may lose that, but the
DWARF spec doesn't seem to indicate anything like that
(however, it isn't clear to me why LLVM then doesn't always
choose the maximal base as the code here does …
> DWARF: Always update .debug_loc base offsets

- src/wasm/wasm-debug.cpp
An (x, y) span is updated to some (q, r) in the new binary. If q > r then the
span is no longer valid - the optimizer has reordered things too much.
It's possible this could be flipped, but I'm not certain. It seems safer to
just omit these, which are very rare (I only see this on some larger
testcases in the emscripten test suite).
> DWARF: Ignore debug_loc spans that are invalid

- src/ir/bits.h
- src/support/bits.cpp
> Avoid __popcnt and __popcnt64 intrinsics for MSC

- src/passes/OptimizeInstructions.cpp
- test/passes/optimize-instructions_all-features.txt
- test/passes/optimize-instructions_all-features.wast
> Optimize booleans when argument is negative integer

- src/wasm2js.h
- test/wasm2js/sign_ext.2asm.js
- test/wasm2js/sign_ext.2asm.js.opt
- test/wasm2js/sign_ext.wast
The usual "trick" to extend: shift left so the sign bit in the small
integer is now the sign bit in a 32-bit integer, then shift right to
spread that sign bit out and return the lower bits to their
proper place, `(x << 24) >> 24`.
> wasm2js: Sign-extend support

- src/passes/NoExitRuntime.cpp
- test/passes/no-exit-runtime.txt
- test/passes/no-exit-runtime.wast
This bug was present from the very first version of this pass from 2018,
but it went unnoticed until now when a large project broke on it, for
some reason after
https://github.com/emscripten-core/emscripten/pull/11403
Nothing wrong in that PR, probably just luck that it started to happen
there...
cc @dschuff @pfaffe
> NoExitRuntime pass: Don't assume arguments have no side effects

- scripts/fuzz_opt.py
- src/tools/wasm2c-wrapper.h
Use `WASM_RT_SETJMP` so we use `sigsetjmp` when we need to.
Also disable signals in emcc+wasm2c in the fuzzer. emcc looks like
unix, so it enters the ifdef to use signals, but wasm has no signals...
This might also be done in the ifdef on the wabt side perhaps? I'm
ok either way.
> wasm2c signal handler fixes

- src/wasm/literal.cpp
- test/passes/fuzz-exec_O.txt
- test/passes/fuzz-exec_O.wast
- test/spec/old_float_exprs.wast
It's valid to change NaN bits in that case per the wasm spec, but
if we do so then fuzz testcases will fail on the optimization of
`nan:foo / 1  =>  nan:foo`
That is, it is ok to leave the bits as they are, and if we do that then
we are consistent with the simple and valid optimization of removing
a divide by 1.
Found by the fuzzer - looks like on x64 on some float32 NaNs,
the bits will actually change (see the testcase). I've seen this on
two machines consistently, so it's normal apparently.
> Interpreter: Don't change NaN bits when dividing by 1

- src/passes/InstrumentLocals.cpp
- test/passes/instrument-locals_all-features.txt
- test/passes/instrument-locals_all-features.wast
In instrument-locals_all-features.wast I added the tests to the end of
the file so that the diff of expected output is smaller and easier to
read. Otherwise the constants will have to all change since they are
order dependent.
> Add v128 support to instrument locals

- .github/workflows/build_release.yml
- .github/workflows/ci.yml
Also, perform cmake --install before archive assets during
normal CI builds.  This means we include the binaryen shared
library on platforms that use it.
Fixes: #2946 #2962
> Fix github actions for releases

- src/passes/wasm-intrinsics.wat
- src/wasm2js.h
- test/wasm2js/atomics_32.2asm.js
- test/wasm2js/atomics_32.2asm.js.opt
- test/wasm2js/bulk-memory.2asm.js
- test/wasm2js/bulk-memory.2asm.js.opt
- test/wasm2js/conversions-modified.2asm.js
- test/wasm2js/conversions-modified.2asm.js.opt
- test/wasm2js/endianness.2asm.js
- test/wasm2js/float_literals-modified.2asm.js
- test/wasm2js/float_literals-modified.2asm.js.opt
- test/wasm2js/float_misc.2asm.js
- test/wasm2js/left-to-right.2asm.js
- test/wasm2js/reinterpret.2asm.js
- test/wasm2js/reinterpret_scratch.2asm.js
- test/wasm2js/reinterpret_scratch.2asm.js.opt
- test/wasm2js/reinterpret_scratch.wast
- test/wasm2js/unaligned.2asm.js
- test/wasm2js/unaligned.2asm.js.opt
i64 reinterprets were lowered in the i64 pass, and i32s at the very end, in
wasm2js itself. This could break since in between the i64 pass and wasm2js
we run optimizations, and the optimizer was not aware of what we lower
the i32 reinterprets to - calls to use scratch memory. Those calls have a
side effect of altering scratch memory. The optimizer just saw an i32
reinterpret, and moved it across the i64 reinterpret's scratch memory calls.
To fix this, lower i32 reinterprets early on, just like i64 ones. Then the
optimizer sees them all as calls, and does not assume they have no side
effects.
Note that it's not really possible to remove the side effects from the
scratch memory helpers - we write to scratch memory in one, and read
from scratch memory in the other. The former has to have a …
> wasm2js: Fix a bug with adjacent reinterprets

- scripts/test/wasm2js.py
Fixes issue #2970
Exception: 'run_command unexpected stderr' when running wasm2js tests with nodejs-14.5.0
> disable nodejs warnings

- src/wasm2js.h
- test/wasm2js/emscripten.2asm.js
- test/wasm2js/func-ptr-offset.2asm.js
- test/wasm2js/func-ptr-offset.2asm.js.opt
- test/wasm2js/func_ptrs.2asm.js
- test/wasm2js/indirect-select.2asm.js
- test/wasm2js/indirect-select.2asm.js.opt
- test/wasm2js/indirect-select.wast
- test/wasm2js/left-to-right.2asm.js
- test/wasm2js/ordering.2asm.js
We emit `FUNCTION_TABLE[ptr]`, where `FUNCTION_TABLE` is a JS
array. That is a rare case where `true` is handled differently than `1`
(a typed array or an add would cast, etc.), so we must explicitly cast
there.
Fixes an issue that existed before, but became a problem due to
#2869 which optimized some selects into a form that emitted a true
or a false, and if that was a function pointer, it could be bad, see
https://app.circleci.com/pipelines/github/emscripten-core/emscripten/6699/workflows/0c4da49c-75d0-4b0a-8fac-686a8330a3fe/jobs/336520
The new `test/wasm2js/indirect-select.2asm.js.opt` output shows
what happened there.
> wasm2js: coerce function pointer indexes

- scripts/fuzz_opt.py
wasm2js fuzzing should not compare outputs if the wasm would
trap. wasm2js traps on far fewer things, and if wasm would trap
(like an indirect call with the wrong type) it can just do weird undefined
things. Previously, if running wasm2js trapped then we ignored
the output, but that't not good enough, as we need to check if
wasm would, exactly for the cases just mentioned where wasm
would trap but wasm2js wouldn't. So run the wasm interpreter
to see if that happens.
When we see such a trap, ignore everything from that function
call onwards. This at least lets us compare the results of
previous calls, which adds some amount of coverage (before
we just ignored the entire output completely, so only if there
was no trap at all did we do any comparisons at all).
Also give better names than …
> wasm2js fuzzing: properly ignore trapping code

- src/passes/CMakeLists.txt
- src/passes/ReplaceStackPointer.cpp
- src/passes/pass.cpp
- src/passes/passes.h
- src/tools/wasm-emscripten-finalize.cpp
- src/wasm-emscripten.h
- src/wasm/wasm-emscripten.cpp
First step in making wasm-emscripten-finalize use more passes.
> Move ReplaceStackPointer into a pass

- scripts/test/generate_lld_tests.py
The `--no-gc-sections` was added as part of #2857 but is not
needed and in fact changes the output of some tests.
`--experimental-pic` is needed these days when building shared
libraries with emscripten's abi.
After these two changes I verfied that the following command
generated no local changes (i.e. is a no-op):
./scripts/test/generate_lld_tests.py --binaryen-bin=$PWD/../binaryen-out/bin/ $PWD/../llvm-build/bin/ $PWD/../emscripten
> Update flags used in generate_lld_tests

- src/tools/wasm-emscripten-finalize.cpp
- src/wasm-emscripten.h
- src/wasm/wasm-emscripten.cpp
- test/lld/safe_stack_standalone-wasm.wat.out
- test/lld/standalone-wasm.wat.out
- test/lld/standalone-wasm2.wat.out
This should not be needed since in emscripten standalone mode we
always include a crt1.o that includes _start.
> wasm-emscripten-finalize: remove exportWasiStart

- src/tools/wasm2js.cpp
- test/wasm2js/br_table_temp.2asm.js.opt
- test/wasm2js/emscripten.2asm.js.opt
It is usually fine to do `if (x | 0)` => `if (x)` since it just cares if the
value is 0 or not. However, if the cast turns it into 0, then that is
incorrect, which the fuzzer found as
```
-2147483648 + -2147483648 | 0
```
(the sum is `2^32`, which `| 0` is 0).
We can maybe look into doing this in a safe way, but for now
just remove it. It doesn't have a big impact on code size as this
is pretty rare (e.g. the minimal runtime code size test is not
broken by this).
> wasm2js: Don't remove an | 0 or >>> 0 in a boolean context

- src/ir/effects.h
- test/passes/simplify-locals_all-features.txt
- test/passes/simplify-locals_all-features.wast
- test/passes/simplify-locals_all-features_disable-exception-handling.txt
We marked it as `readsMemory` so that it could be reordered with various
things, except for `memory.init`. However, the fuzzer found that's not quite
right, as it has a global side effect - `memory.init`s that run later can notice
that. So it can't be reordered with anything that might affect global side
effects from happening, as in the testcase added here (an instruction that
may trap cannot be reordered with a `data.drop`, as it may prevent the
`data.drop` from happening and changing global state).
There may be a way to optimize this more carefully that would allow more
optimizations, but as this is a rare instruction I'm not sure it's worth more
work.
> Fix the side effects of data.drop

- src/passes/AvoidReinterprets.cpp
- test/passes/avoid-reinterprets.txt
- test/passes/avoid-reinterprets.wast
We can turn a reinterpret of a load into a different load, and so forth, but if
the reinterpret has a non-load child with a load fallthrough, that's not good
enough - we can't remove the extra code:
```wat
(reinterpret
(block
..extra code..
(load)
)
)
```
That can't be turned into a load of the flipped type.
Not sure why I thought this made sense to do - seems obvious it's been wrong
all along. Fuzzer found an issue only now.
> AvoidReinterpreters should not look at a reinterpret's value's fallthrough

- src/tools/wasm2js.cpp
- test/wasm2js/emscripten.2asm.js.opt
optimizeBoolean does not receive a boolean, it is done when the
output flows into a boolean context.
(found by the fuzzer)
> wasm2js: Remove an incorrect optimization

- scripts/test/support.py
Current locale may not be UTF-8, which makes the spec/names.wast
test fail. Fixes issue #3003.
> specify UTF-8 encoding instead of relying on locale default

- src/passes/CMakeLists.txt
- src/passes/DeAlign.cpp
- src/passes/pass.cpp
- src/passes/passes.h
- test/passes/dealign.txt
- test/passes/dealign.wast
Pretty trivial, but will be useful in wasm2js testing, where we
can't assume an incorrectly-aligned load/store will still work,
so we'll need to be pessimistic about alignment there.
> New Dealign pass: reduce load/store alignment to 1

- scripts/gen-s-parser.py
- src/binaryen-c.h
- src/gen-s-parser.inc
- src/passes/Print.cpp
- src/tools/fuzzing.h
- src/wasm-binary.h
- src/wasm-interpreter.h
- src/wasm.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-s-parser.cpp
- src/wasm/wasm-stack.cpp
- src/wasm/wasm-validator.cpp
- src/wasm/wasm.cpp
- test/simd.wast
- test/simd.wast.from-wast
- test/simd.wast.fromBinary
- test/simd.wast.fromBinary.noDebugInfo
- test/spec/simd.wast
Specified in https://github.com/WebAssembly/simd/pull/237. Since these
are just prototypes necessary for benchmarking, this PR does not add
support for these instructions to the fuzzer or the C or JS APIs. This
PR also renumbers the QFMA instructions that previously used the
opcodes for these new instructions. The renumbering matches the
renumbering in V8 and LLVM.
> Implement prototype v128.load{32,64}_zero instructions

- src/ir/bits.h
- src/passes/OptimizeInstructions.cpp
- test/example/cpp-unit.cpp
`getMaxBits` just moves around, no logic is changed.
Aside from adding `getMaxBits`, the change in bits.h is 99% whitespace.
helps #2879 cc @MaxGraey
> Refactor getMaxBits() out of OptimizeInstructions and add beginnings of unit testing for it

- src/ir/module-utils.h
- src/passes/Asyncify.cpp
- src/passes/PostEmscripten.cpp
- test/passes/asyncify_pass-arg=asyncify-verbose.txt
- test/passes/asyncify_pass-arg=asyncify-verbose.wast
This logs out the decisions made about instrumenting functions, which
can help figure out why a function is instrumented, or to get a list of
what might need to be.
As the test shows, it can print things like this:
```
[asyncify] import is an import that can change the state
[asyncify] calls-import can change the state due to import
[asyncify] calls-calls-import can change the state due to calls-import
[asyncify] calls-calls-calls-import can change the state due to calls-calls-import
```
(the test has `calls-calls-calls-import => calls-calls-import => calls-import -> import`).
Not sure how useful this might be, but it was easy to write up. Thoughts?
cc @curiousdannii @aardappel
> Asyncify verbose option

- src/support/bits.cpp
We just had the logic there wrong - MSVC's intrinsic returns the bit
index, not the number of leading zeros. That's identical when scanning
forward but not in reverse...
This fixes one set of windows (or rather MSVC) specific errors on CI,
which I verified on CI. (But other issues remain after this, so we can't
turn on windows CI yet.)
This hopefully will fix #2942 , cc @RReverser
> Fix CountLeadingZeroes on MSVC

- src/passes/RemoveNonJSOps.cpp
- src/tools/fuzzing.h
- test/passes/stub-unsupported-js.txt
- test/passes/stub-unsupported-js.wast
wasm2js does not have full `call_indirect` support as we don't trap if
the type is incorrect, which wasm does. Therefore the StubUnsupportedJSOps
pass needs to remove those operations so that the fuzzer doesn't find
spurious issues.
> StubUnsupportedJSOps: Remove CallIndirects

- src/asmjs/CMakeLists.txt
- src/cfg/CMakeLists.txt
- src/emscripten-optimizer/CMakeLists.txt
- src/ir/CMakeLists.txt
- src/passes/CMakeLists.txt
- src/support/CMakeLists.txt
- src/wasm/CMakeLists.txt
This is needed for headers to show up in IDE projects, and has no other effect on the build.
> Added headers to CMake files

- check.py
- scripts/test/shared.py
This was useful back when we didn't have many VMs to test in, and
we weren't confident in our binaries being valid wasm. Today we have
lots of testing on VMs, and in particular, this test tends to fail when we
do things like reorder SIMD opcode constants. (This doesn't fail on CI
as we don't have v8 installed there, so this path is never reached, but
it does happen locally.)
> Remove unneeded old binary validation in test suite

- CHANGELOG.md
- CMakeLists.txt
Contains in particular the MSVC fix for clz.
> Release 96

- src/support/hash.h
Currently only the low 32-bits of a hash are guaranteed to be shuffled before combining with the other hash, so this PR also adds a 64-bit variant of `hash_combine`, including a comment on where the constants are coming from.
> Add 64-bit hash_combine

- .gitattributes
Python scripts were previously checked out with CRLF line endings by default on Windows (unless configured otherwise globally), leading to problems with the shebang not being correctly recognized when mounted into WSL and trying to run `./thescript.py` without prepending `python3` (just like `*.sh` files and `bash` that have already been addressed). NFC except that it helps in mixed setups.
> Checkout python scripts with LF to keep shebangs intact in mixed setups

- test/lld/em_asm.wat
- test/lld/em_asm_O0.c
- test/lld/em_asm_O0.wat
- test/lld/em_asm_O0.wat.out
- test/lld/em_asm_shared.wat
- test/lld/hello_world.wat
- test/lld/init.wat
- test/lld/longjmp.wat
- test/lld/recursive.wat
- test/lld/reserved_func_ptr.wat
- test/lld/shared.wat
- test/lld/shared_longjmp.wat
That had just a wat file, with no C. This adds a C file as best I
can guess - looks pretty close - and updates all the lld tests with
`scripts/test/generate_lld_tests.py` and `./auto_update_tests.py lld`
As the diff shows, the handwritten wat was very different than what
emcc+lld emit now. I think we must have switches EM_ASMs to
be variadic at some point? That is what they currently are, and
would explain the diff.
See the discussion that led to this in #3044
> Add a C source for for test/lld/em_asm_O0

- src/tools/wasm-emscripten-finalize.cpp
- test/unit/input/empty_lld.wat
- test/unit/test_finalize.py
This helps towards the goal of allowing emscripten to not always modify
the wasm during link. Until now wasm-emscripten-finalize always wrote
an output, while with this PR it only does so if it was asked to, either by
giving it an output filename, or asking for text output.
The only noticeable change from this should be to make what was an
error before (not specify an output or ask for text) into a non-error (run
and print metadata, but do not write the wasm).
> Make wasm-emscripten-finalize's output optional

- scripts/fuzz_opt.py
* Can now run `scripts/fuzz_opt.py --binaryen-bin build/bin [opts...]` to fuzz an out-of-tree build
* Handle positional arguments by looking at `shared.requested` (with options removed) instead of raw `sys.argv`
> Support fuzzing out of tree

- CMakeLists.txt
It was apparently not being run anymore since it referred to a file
that was removed with asm2wasm. I suspect when we changed CI
we didn't keep running these. Anyhow they were just useful for
windows, which we have a lot more testing for now.
> Remove test code from CMakeLists.txt.

- src/asmjs/asm_v_wasm.cpp
- src/binaryen-c.cpp
- src/passes/Asyncify.cpp
- src/passes/DeadArgumentElimination.cpp
- src/passes/FuncCastEmulation.cpp
- src/passes/I64ToI32Lowering.cpp
- src/passes/LegalizeJSInterface.cpp
- src/passes/Print.cpp
- src/shell-interface.h
- src/tools/execution-results.h
- src/tools/fuzzing.h
- src/tools/js-wrapper.h
- src/tools/spec-wrapper.h
- src/tools/wasm-shell.cpp
- src/tools/wasm2c-wrapper.h
- src/wasm-builder.h
- src/wasm-interpreter.h
- src/wasm-type.h
- src/wasm/literal.cpp
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-emscripten.cpp
- src/wasm/wasm-s-parser.cpp
- src/wasm/wasm-stack.cpp
- src/wasm/wasm-type.cpp
- src/wasm/wasm-validator.cpp
- src/wasm/wasm.cpp
As a follow-up to https://github.com/WebAssembly/binaryen/pull/3012#discussion_r471842763, this PR replaces `Type::expand()` incl. its usages with an iterator-based approach.
> Replace Type::expand() with an iterator-based approach

- src/asmjs/asm_v_wasm.cpp
- src/binaryen-c.cpp
- src/passes/Asyncify.cpp
- src/passes/FuncCastEmulation.cpp
- src/passes/I64ToI32Lowering.cpp
- src/passes/LegalizeJSInterface.cpp
- src/passes/Print.cpp
- src/shell-interface.h
- src/tools/execution-results.h
- src/tools/fuzzing.h
- src/tools/js-wrapper.h
- src/tools/spec-wrapper.h
- src/tools/wasm-shell.cpp
- src/tools/wasm2c-wrapper.h
- src/wasm-type.h
- src/wasm/literal.cpp
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-emscripten.cpp
- src/wasm/wasm-s-parser.cpp
- src/wasm/wasm-stack.cpp
- src/wasm/wasm-type.cpp
- src/wasm/wasm-validator.cpp
As a follow-up to https://github.com/WebAssembly/binaryen/pull/3012#discussion_r473756121, this PR
* Changes the use of `auto&`  introduced in https://github.com/WebAssembly/binaryen/pull/3061 to `const auto&` for clarity when dealing with `Type`s
> Use const modifier when dealing with types

- auto_update_tests.py
- scripts/test/wasm_opt.py
It was confusing that you had to run `./auto_update_tests.py binfmt` to update
a test checked by `./check.py wasm-opt`. Instead, make
`./auto_update_tests.py wasm-opt` update those, so it's symmetrical.
> Harmonize auto updater with test runner: wasm-opt should update .fromBinary files

- scripts/test/shared.py
Since list comprehensions are generally easier to read.
> Use fnmatch for test filtering

- src/passes/OptimizeInstructions.cpp
- test/passes/optimize-instructions_all-features.txt
- test/passes/optimize-instructions_all-features.wast
It seems we couldn't simply remove `memory.copy(x, x, C)` even if all arguments are side effect free due to `x` value could exceeds memory bounds.
See: https://github.com/WebAssembly/binaryen/pull/3038#issuecomment-678790358
> Remove optimization for memory.copy(x, x, C)

- src/passes/OptimizeInstructions.cpp
- test/passes/optimize-instructions_all-features.txt
- test/passes/optimize-instructions_all-features.wast
- test/passes/optimize-instructions_optimize-level=2_all-features_ignore-implicit-traps.txt
- test/passes/optimize-instructions_optimize-level=2_all-features_ignore-implicit-traps.wast
According to changes in spec:
https://github.com/WebAssembly/bulk-memory-operations/issues/124
https://github.com/WebAssembly/bulk-memory-operations/issues/145
we unfortunately can't fold to `nop` even for `memory.copy(x, y, 0)`.
So this PR revert all reductions to `nop` but do this only under `ignoreImplicitTraps` flag
> memory.copy: use nop reductions only for ignoreImplicitTraps

- src/passes/OptimizeInstructions.cpp
- test/passes/optimize-instructions_optimize-level=2_all-features_ignore-implicit-traps.txt
> memory.copy: Also drop size for memory.copy(x, x, y) case

- src/passes/RedundantSetElimination.cpp
- src/passes/ReorderLocals.cpp
- src/passes/SimplifyLocals.cpp
It seems some optimization passes which manipulate only locals could be early rejected when number of locals is zero
> Fast reject expensive optimizations for passes with zero number of locals

- src/passes/SafeHeap.cpp
- test/passes/safe-heap_disable-simd.txt
- test/passes/safe-heap_disable-simd.wast
In fastcomp we implemented `emscripten_get_sbrk_ptr` in wasm, and
exported `_emscripten_get_sbrk_ptr`. We don't need that anymore and
can remove it.
However I want to switch us to implementing `emscripten_get_sbrk_ptr`
in wasm in upstream too, as part of removing `DYNAMICTOP_PTR` and
other silliness that we have around link (https://github.com/WebAssembly/binaryen/issues/3043).
This makes us support an export of `emscripten_get_sbrk_ptr` (no
prefix), and also it makes sure not to instrument that function, which
may contain some memory operations itself, but if we SAFE_HEAP-ify
them we'd get infinite recursion, as the SAFE_HEAP methods need to
call that.
> SAFE_HEAP: remove fastcomp, prepare for new emscripten approach

- src/binaryen-c.cpp
- src/binaryen-c.h
- src/js/binaryen.js-post.js
- test/binaryen.js/inlining-options.js
- test/binaryen.js/inlining-options.js.txt
It's finished #3032 and fix https://github.com/AssemblyScript/assemblyscript/pull/1449
> add Binaryen(Get|Set)AllowHeavyweight to binaryen-c.h

- src/literal.h
- src/wasm-interpreter.h
- src/wasm/literal.cpp
First, adds an explicit destructor call to fix a memory leak in
`Literal::operator=` in which existing `ExceptionPackage`s would be
silently dropped. Next, changes `Literal::getExceptionPackage` to
return the `ExceptionPackage` by value to avoid a use-after-free bug
in the interpreter that was surfaced by the new destructor call.
Fixes #3087.
> Fix ExceptionPackage memory errors

- src/literal.h
- src/passes/DeadArgumentElimination.cpp
- src/passes/RemoveImports.cpp
- src/wasm-interpreter.h
- src/wasm/literal.cpp
Outsourced safety guards for `exnref` `Literal`s I came up with in https://github.com/WebAssembly/binaryen/pull/3084.
* Make `Literal::type` immutable to guarantee that we do not lose track of `Literal::exn` by changing the literal's type
* Add an assert to guarantee that we don't create `exnref` literals without an `ExceptionPackage` (for now)
* Enforce rvalue reference when creating an `exnref` Literal from a `std::unique_ptr<ExceptionPackage>`, avoiding a redundant copy by means of requiring `std::move`
> Harden exnref literals

- src/passes/DataFlowOpts.cpp
Fixes `DataFlowOpts` leaking allocated temporary functions created to precompute an expression as their body. Reusing the `body` afterwards is fine because expressions are arena allocated.
> Fix DataFlowOpts leaking temporary Functions

- src/passes/StackCheck.cpp
- test/lld/basic_safe_stack.wat.out
- test/lld/recursive_safe_stack.wat.out
- test/lld/safe_stack_standalone-wasm.wat.out
- test/passes/stack-check_enable-mutable-globals.txt
- test/passes/stack-check_enable-mutable-globals.wast
See https://github.com/emscripten-core/emscripten/issues/9039#issuecomment-683358105
The valid stack area is a region `[A, B]` in memory. Previously we just checked that
new stack positions `S` were `S >= A`, which prevented us from growing too much
(the stack grows down). But that only worked if the growth was small enough to not
overflow and become a big unsigned value. This PR makes us check the other way
too, which requires us to know where the stack starts out at.
This still supports the old way of just passing in the growth limit. We can remove it
after the roll.
In principle this can all be done on the LLVM side too after https://github.com/emscripten-core/emscripten/pull/12057
but I'm not sure of the details there, and this is easy to fix here and get testing up
(which can help …
> StackCheck: Check both under and overflow

- src/ir/module-utils.h
- src/passes/MinifyImportsAndExports.cpp
- test/passes/minify-imports-and-exports-and-modules.txt
- test/passes/minify-imports-and-exports_all-features.txt
- test/passes/minify-imports_all-features.txt
We were careful not to minify those, as well as the stack pointer, which
makes sense in dynamic linking. But we don't run this pass in dynamic linking
anyhow - we need the proper names of symbols in that case. So this was
not helping us, and was just a leftover from an early state.
This both a useful optimization and also important for https://github.com/WebAssembly/binaryen/issues/3043,
as the wasm backend exports the table as `__indirect_function_table` - a much
longer name than emscripten's `table`. So just changing to that would regress
code size on small projects. Once we land this, the name won't matter as it will
be minified anyhow.
This will break some tests on the roller as it improves code size beyond
current expectations, so it will require a double-roll or a temporary test …
> MinifyImportsAndExports: Minify the memory and table as well.

- src/passes/LegalizeJSInterface.cpp
Fixes `LegalizeJSInterface::makeLegalStub` forgetting to `delete` stub Functions that turned out to be not needed. Now checks whether a stub is needed and otherwise skips creating the redundant stub right away.
> Fix LegalizeJSInterface leaking duplicate stub Functions

- src/wasm2js.h
Fixes `Wasm2JSBuilder` leaking a temporary `Function` (`WASM_FETCH_HIGH_BITS`) in `Wasm2JSBuilder::processWasm`. The function is created to be converted to JS, but is not actually part of the module, so it either needs to be cleaned up separately or be added to the module. This PR does the latter in case it is useful.
> Fix Wasm2JSBuilder leaking temporary Function

- src/tools/wasm-emscripten-finalize.cpp
When minimizing wasm changes, leave it as `__indirect_function_table`
which is what LLVM emits.
This also removes the renaming of the memory. That was never needed
as LLVM already emits "memory" there.
See https://github.com/WebAssembly/binaryen/issues/3043
> wasm-emscripten-finalize: Don't rename the imported table

- src/ir/branch-utils.h
- src/passes/MergeBlocks.cpp
- src/wasm/wasm-validator.cpp
`BranchSeekerCache` caches the set of branches in a node +
its children, and helps compute new results by looking in the cache
and using data for the children. This avoids quadratic time in the
common case of a post-walk on a tower of nested blocks which is
common in a switch.
Fixes https://github.com/WebAssembly/binaryen/issues/3090 . On the testcase there this pass goes from
over a minute to less than a second.
I haven't looked at the validator yet which may also be helped by this,
but as this ended up more work than I thought I didn't want to do too
much in one PR.
Fuzzed for a few thousand iterations + random50 on emscripten test suite.
> Optimize MergeBlocks by caching branch results

- src/ir/CMakeLists.txt
- src/ir/stack-utils.cpp
- src/ir/stack-utils.h
- src/wasm-type.h
- test/example/stack-utils.cpp
- test/example/stack-utils.txt
Implement and test utilities for manipulating and analyzing a new
stacky form of Binaryen IR that is able to express arbitrary stack
machine code. This new Poppy IR will eventually replace Stack IR, and
new optimization passes will be built with these utilities. See #3059.
> Stack utils

- src/binaryen-c.cpp
- src/cfg/Relooper.cpp
- src/cfg/Relooper.h
- src/passes/ReReloop.cpp
Fixes the `Relooper` leaking `Branch`es in `Optimizer::SkipEmptyBlocks` (and potentially elsewhere), by refactoring the API so a `std::unique_ptr` is ensured for each `Block`, `Branch` and `Shape` upon adding to the relooper.
Fixes https://github.com/WebAssembly/binaryen/issues/3094
> Fix Relooper leaking Branches

- CHANGELOG.md
- CMakeLists.txt
- README.md
- scripts/test/shared.py
An alternative to https://github.com/WebAssembly/binaryen/pull/3107 just switching C++ standard support to `14` (for now), so we can easily upgrade again once the autoroller issues are resolved.
> Stay on C++14 for now

- .github/workflows/ci.yml
- check.py
With the respective fixes
* https://github.com/WebAssembly/binaryen/pull/3088
* https://github.com/WebAssembly/binaryen/pull/3093
* https://github.com/WebAssembly/binaryen/pull/3095
* https://github.com/WebAssembly/binaryen/pull/3098
* https://github.com/WebAssembly/binaryen/pull/3097
merged, it should now be possible to enable LSan on CI again.
> Enable LeakSanitizer on CI again

- src/wasm/literal.cpp
- test/passes/fuzz-exec_O.txt
- test/passes/fuzz-exec_O.wast
- test/spec/old_float_exprs.wast
Similar to #2958, but for multiplication. I thought this was limited
only to division (it doesn't happen for addition, for example), but the
fuzzer found that it does indeed happen for multiplication as well.
Overall these are kind of workarounds for the interpreter doing
normal f32/f64 multiplications using the host CPU, so we pick up
any oddness of its NaN behavior. Using soft float might be safer
(but much slower).
> Interpreter: Don't change NaN bits when multiplying by 1

- src/binaryen-c.cpp
- src/ir/stack-utils.cpp
- src/ir/stack-utils.h
- src/passes/RemoveNonJSOps.cpp
- src/tools/tool-options.h
- src/tools/wasm-as.cpp
- src/tools/wasm-opt.cpp
- src/tools/wasm-shell.cpp
- src/tools/wasm2js.cpp
- src/wasm-io.h
- src/wasm-s-parser.h
- src/wasm.h
- src/wasm/wasm-io.cpp
- src/wasm/wasm-s-parser.cpp
- src/wasm/wasm-validator.cpp
- test/unit/test_poppy_validation.py
Adds an IR Profile to each function so the validator can determine
which validation rules to apply and adds a flag to have the wast
parser set the profile to Poppy for testing purposes. See #3059.
> Poppy IR wast parsing and validation

- src/wasm2js.h
- test/wasm2js/minified-memory.2asm.js
- test/wasm2js/minified-memory.2asm.js.opt
- test/wasm2js/minified-memory.wast
It was hardcoded as "env.memory", which is usually correct. But if we minify
import names, as in `-O3` in emscripten, we need to use the minified name.
Note how in the test it now emits
```javascript
var memory = env.a;
```
for the import.
Fixes https://github.com/emscripten-core/emscripten/issues/12123
This was not noticed earlier since that import is only used in memory
growth. The tests that would catch it are `wasm2js3.test*memory_growth*`
but we only run `wasm2js1` on CI. I'll add testing after this lands.
> Fix wasm2js memory import in case it is minified

- src/ir/iteration.h
- src/ir/properties.h
- src/ir/stack-utils.cpp
- src/wasm-stack.h
- test/example/c-api-unused-mem.txt
- test/passes/fannkuch0_dwarf.bin.txt
- test/passes/fannkuch3_dwarf.bin.txt
- test/passes/fannkuch3_manyopts_dwarf.bin.txt
- test/passes/remove-unused-brs_generate-stack-ir_print-stack-ir.txt
BinaryenIRWriter was previously inconsistent about whether or not it
emitted an instruction if that instruction was not reachable.
Instructions that produced values were not emitted if they were
unreachable, but instructions that did not produce values were always
emitted. Additionally, blocks continued to emit their children even
after emitting an unreachable child.
Since it was not possible to tell whether an unreachable instruction's
parent would be emitted, BinaryenIRWriter had to be very defensive and
emit many extra `unreachable` instructions around unreachable code to
avoid type errors.
This PR unifies the logic for emitting all non-control flow
instructions and changes the behavior of BinaryenIRWriter so that it
never emits instructions that cannot be reached due to having …
> Simplify BinaryenIRWriter

- src/passes/PostEmscripten.cpp
- src/wasm/wasm-emscripten.cpp
- test/lld/longjmp.wat.out
- test/lld/shared_longjmp.wat.out
- test/passes/post-emscripten.txt
- test/passes/post-emscripten.wast
Instead of finalize renaming `emscripten_longjmp_jmpbuf` to `emscripten_longjmp`,
do nothing in finalize. But in the optional `--post-emscripten` pass, rename it there if
both exist, so that we don't end up using two imports (other optimization passes
can then remove an unneeded import).
Depends on https://github.com/emscripten-core/emscripten/pull/12157 to land first.
> Stop renaming longjmp in wasm-emscripten-finalize

- src/tools/wasm-emscripten-finalize.cpp
This option skips the PIC ABI transforms that are normally done by
wasm-emscripten-finalize and keeps the llvm PIC ABI in place.
The LLVM abi uses mutable globals (GOT.mem.foo and GOT.func.bar) for
data and function offsets rather than accessor functions (g$foo and
fp$bar)
> wasm-emscripten-finalize: Add --new-pic-abi option

- scripts/fuzz_opt.py
Since #3050 `fuzz_opt.py` can test out-of-tree builds by specifying the `--binaryen-bin` argument, which I forgot to add to the generated `reduce.sh`s so it "just works".
> Fuzzing: Include potential out-of-tree bin directory in reduce.sh

- src/ir/properties.h
- src/passes/OptimizeInstructions.cpp
- test/passes/O4_disable-bulk-memory.txt
- test/passes/inlining-optimizing_optimize-level=3.txt
- test/wasm2js/conversions-modified.2asm.js.opt
- test/wasm2js/float-ops.2asm.js.opt
Implement #3126
Add float point ops to `isSymmetric`:
AddFloat(32|64)*
MulFloat(32|64)*
EqFloat(32|64)
NeFloat(32|64)
`*` - only if we know that LHS is constant and not NaN
> Add float operations for isSymmetric util

- src/binaryen-c.h
Changes the storage type of type ids in `BinaryenLiteral` from `int32_t` to `uintptr_t`, matching `Literal`. The maximum storage size of type ids changed with the introduction of tuples, with their type id being the memory address of the canonicalized type vector.
Interestingly, the related check
https://github.com/WebAssembly/binaryen/blob/bced89d2986bde990bf9bf52306e55772b02707e/src/binaryen-c.cpp#L48-L49
did not catch this due to implicit struct alignment, and other tests did not notice because type ids typically do not grow to values larger than 32 bits.
> Fix 64-bit UB in BinaryenLiteral

- CMakeLists.txt
- auto_update_tests.py
- check.py
- scripts/fuzz_opt.py
- scripts/test/wasm_opt.py
- src/passes/ExtractFunction.cpp
- src/passes/pass.cpp
- src/tools/execution-results.h
- src/tools/wasm-as.cpp
- src/tools/wasm-opt.cpp
- src/tools/wasm-shell.cpp
- src/tools/wasm2js.cpp
- src/wasm/CMakeLists.txt
- src/wasm2js.h
- test/unit/test_asyncify.py
- test/unit/utils.py
This PR contains:
- Changes that enable/disable tests on Windows to allow for better local testing.
- Also changes many abort() into exit(1) when it is really just exiting on error. This is because abort() generates a dialog window on Windows which is not great in automated scripts.
- Improvements to CMake to better work with the project in IDEs (VS).
> Improve testing on Windows

- src/js/binaryen.js-post.js
- test/binaryen.js/expressions.js
- test/binaryen.js/functions.js
- test/binaryen.js/functions.js.txt
Follow-up on https://github.com/WebAssembly/binaryen/pull/3115#discussion_r487205710.
Updates the JS API `Function` wrapper introduced in #3115 with bindings for more C API functions (unrelated to #3115). Also adds additional comments to describe the inner workings of wrappers in more detail.
> Update JS API function wrapper

- src/binaryen-c.cpp
- src/binaryen-c.h
- src/js/binaryen.js-post.js
- test/binaryen.js/kitchen-sink.js
- test/binaryen.js/kitchen-sink.js.txt
- test/example/c-api-kitchen-sink.c
- test/example/c-api-kitchen-sink.txt
Noticed that these are missing while updating our custom bindings. Sorry for not noticing earlier.
> Add Memory64 feature flag to the C and JS APIs

- src/ir/bits.h
It looks like it existed for a very long time, but since the DummyLocalInfoProvider is never practically used, this did not create problems.
> fix i64 type checking in getMaxBitsForLocal of DummyLocalInfoProvider

- src/ir/bits.h
Improve some comments, and remove fast paths that are just optimizations for
compile time.
About the fast paths, is there a previous discussion I missed? They seem
unnecessary unless I'm not seeing something. A minor speedup from them
doesn't seem worth more complicated code - this code is pretty complex as
it is.
cc @MaxGraey
> bits.h cleanups after #2879

- src/tools/wasm2js.cpp
- src/wasm-builder.h
- src/wasm-s-parser.h
- src/wasm2js.h
Builders gained a `Module` field in #3130 because they now require extra context
to properly finalize some Expressions. Since modules contain allocators, the old
allocator field on the builder became redundant after that change. This PR
removes the redundant allocator field.
> Remove redundant allocator in Builder

- scripts/emcc-tests.sh
- Use ninja
- Use a sub-directory
- Don't use emmake when running make/ninja (this is redundant if you
use emconfigure to configure the build).
> Cleanup emcc-tests.sh

- src/ir/match.h
- test/example/match.cpp
- test/example/match.txt
Adds new binary matchers that allow for matching any binary operation and
optionally extracting it. The previous matchers only allowed matching specific
binary operations. This should help simplify #3132.
cc @MaxGraey
> Add new binary matchers

- src/wasm/wasm-validator.cpp
Adds feature checks to `ref.null`, `ref.is_null`, `ref.func`, `try`, `throw`, `rethrow` and `br_on_exn` instructions.
fixes #3147
> Validator: Fix missing feature checks

- src/wasm/wasm-validator.cpp
- test/atomics-unshared.wast
- test/atomics-unshared.wast.from-wast
- test/atomics-unshared.wast.fromBinary
- test/atomics-unshared.wast.fromBinary.noDebugInfo
This relaxation has made it to Chrome stable, so it makes sense that we would
allow it in the tools.
> Allow atomics to validate with unshared memory

- src/passes/OptimizeInstructions.cpp
- test/passes/optimize-instructions_all-features.txt
- test/passes/optimize-instructions_all-features.wast
`i64(bool(x)) != 0` -> `i32(bool(x))`
> Add also non-equal with zero  simplification for boolean context

- src/passes/OptimizeInstructions.cpp
- test/passes/optimize-instructions_all-features.txt
- test/passes/optimize-instructions_all-features.wast
(found by the fuzzer)
It is not valid to replace `x | (y | x)  ==>  y | x`, if `x, y` cannot be reordered.
It is also not valid to replace `x ^ (y ^ x)  ==>  y`, if `x, y` cannot be reordered,
for a more subtle reason: if they cannot be reordered then `y` can affect the
value of `x` (the opposite is not possible as we checked `x` for side effects so
that we could remove one copy). If so, then the second appearance of `x`
could be different, if e.g. it reads a local `y` writes to. Whereas, if it's ok to
reorder, then it's ok to do `x ^ (y ^ x)  ==>  x ^ (x ^ y)  ==>  y`.
PTAL @MaxGraey @tlively , and also please check for similar things in
other code - I think I fixed up all of `deduplicateBinary` but maybe there are
similar patterns elsewhere?
> Ordering correction fix in OptimizeInstructions for #3047

- src/literal.h
- src/passes/OptimizeInstructions.cpp
- test/passes/optimize-instructions_all-features.txt
- test/passes/optimize-instructions_all-features.wast
It's more general (additional) version of #3153 which also handle negative constant dividers:
`(int32)x % -4 == 0` --> `(x & 3) == 0`
`x % -C_pot == 0` --> `(x & (abs(C_pot) - 1)) == 0`
and special two-complement values as well:
`(int32)x % 0x80000000 == 0` --> `(x & 0x7fffffff) == 0`
`(int64)x % 0x8000000000000000 == 0` --> `(x & 0x7fffffffffffffff) == 0`
as separete rules:
`(int32)x % 0x80000000` --> `x & 0x7fffffff`
`(int64)x % 0x8000000000000000` --> `x & 0x7fffffffffffffff`
The [previous pr](https://github.com/WebAssembly/binaryen/pull/3153) didn't use these possibilities.
cc @kripken @tlively
> Generalize transforms for #3153

- src/passes/OptimizeInstructions.cpp
- test/passes/optimize-instructions_all-features.txt
Fuzzed found `(seed 17400736677355043573)` invalid transform which introduced in #3193.
`(signed)x % (i32|i64).min_s`   ==>  `(x & (i32|i64).max_s)`
This not valid without equal / unequal with zero unfortunately. So this PR fix that.
cc @tlively
> Revert some changes from #3193

- src/wasm.h
This add compile time guards for `Expression::cast` and `Expression::dynCast` for making sure type `T` derived from `Expression`.
> Add static guards for cast and dynCast

- src/passes/opt-utils.h
- test/passes/duplicate-function-elimination_all-features.txt
- test/passes/duplicate-function-elimination_all-features.wast
The `replaceFunctions` utility replaced exports by name, but did not check
the kind, so it could get confused when names happen to overlap (see
testcase).
> Fuzz fix for DuplicateFunctionElimination

- src/tools/fuzzing.h
Previously `getLoggableType` would allocate a vector every time. This
caches it.
Also add `isLoggableType` which will need this caching as I will be
calling it quite a lot in a future patch to the fuzzer.
> Optimize getLoggableTypes in fuzzer, and add isLoggableType

- src/tools/fuzzing.h
`fixLabels()` in the fuzzer looks for invalid labels and fixes them up,
after doing some random changes to existing wasm (which checks
for types while doing so, but it may invalidate labels if we remove the
target of a branch, for example). This adds trivial support for
`BrOnExn` and `Try` there.
I wasn't working on exceptions, just a fuzz testcase happened to hit
this, and this was enough to get past it.
> Add a little code to prepare exception handling support in fuzzer

- scripts/test/support.py
Normally a wast file has a module and then asserts on it, but
some tests have just asserts without a module. Before this PR
we would break if such asserts happened before the first
module, as we didn't know what module to attach them to.
> Fix split_wast on asserts before the first module

- scripts/fuzz_shell.js
Fuzzing Asyncify on data with a memory growth showed that the harness
did not handle a growth. When growth happens we must recreate the view.
> Asyncify fuzzing harness fix for growth

- src/passes/RemoveUnusedBrs.cpp
- test/passes/remove-unused-brs_enable-multivalue.txt
- test/passes/remove-unused-brs_enable-multivalue.wast
We turn a `br_table` with a single target into a `br`, but we reverse the order of the
condition and the value when doing so, which we forgot to take into account.
> RemoveUnusedBrs fuzz fix

- src/wasm/wasm-validator.cpp
Mentioning if it's a memory or a table segment is convenient.
> Slightly improve validator error text on segments

- src/shell-interface.h
- src/tools/wasm-ctor-eval.cpp
- src/wasm-interpreter.h
`growMemory()` now also returns whether we succeeded.
Without this it could eventually start to swap etc., which is annoying.
> Interpreter: Add a limit to how much we try to grow memory, to avoid DOS

- src/binaryen-c.h
According to the WebAssembly spec, Wasm is an abbreviation, not an acronym.
> Fix Wasm capitalization in binaryen-c.h comments

- src/passes/MemoryPacking.cpp
- test/passes/memory-packing_all-features.txt
- test/passes/memory-packing_all-features.wast
This PR fixes a bug in which the segment index of a memory.init instruction was
incorrect in some circumstances. Specifically, the first segment index used in
output memory.init instructions was always the index of the first segment
created from splitting up the corresponding input segment. This was incorrect
when the input memory.init had an offset that caused it to skip over that first
emitted segment so that the first output memory.init should have referred to a
subsequent output segment.
Fixes #3225.
> [MemoryPacking] Emit the correct segment indices on memory.init

- src/tools/wasm-emscripten-finalize.cpp
Internalizing of the stack pointer is only needed in legacy
PIC mode, since in the new PIC mode we support mutable globals.
Also the additional ASSIGN_GOT_ENTRIES function only exists
in support of the legacy mode.
> finalize: move more functionality behind legacyPIC

- src/tools/wasm-emscripten-finalize.cpp
This flag disables the features of wasm-emscripten-finalize
the replace the mutable global import of `__stack_pointer`.
See the corresponding emscripten change that depends on this
one: https://github.com/emscripten-core/emscripten/pull/12536
> finalize: add --mutable-sp flag

- src/tools/wasm-emscripten-finalize.cpp
- test/lld/em_asm_shared.wat.out
- test/lld/main_module.wat.out
- test/lld/shared.wat.out
- test/lld/shared_add_to_table.wasm.out
- test/lld/shared_longjmp.wat.out
These days we always export the table, except in the
case of dynamic linking, and even then we use the name
`__indirect_function_table`.
> finalize: remove legacy support for "table" import

- src/pass.h
- src/tools/optimization-options.h
When set, we can assume an imported memory was not modified before us.
That lets us assume it is all zeros and so we can optimize out zeros from
memory segments.
This does not actually do anything with the flag, just adds it. This is to avoid
a rolling problem. Next emscripten can emit it without erroring, and then we
can start to use it.
> Add unmodifiedImportedMemory pass option

- .gitignore
I'm trying to include binaryen in an archive that the Grain team needs to publish, and I ran into this problem with the `.gitignore`. Basically, the publishing tool filters things based on the gitignore file and https://github.com/WebAssembly/binaryen/blob/master/third_party/llvm-project/include/llvm/Config/config.h was removed from the archive because of the `config.h` reference.
By prefixing it with `/`, only the root `config.h` file is excluded from the archive.
> Only ignore the root `config.h` file

- src/passes/I64ToI32Lowering.cpp
- src/wasm/wasm-validator.cpp
- test/passes/flatten_i64-to-i32-lowering.txt
- test/passes/flatten_i64-to-i32-lowering.wast
validateGlobally means that we can't do lookups on the module. A few places
were missing that, or had it wrong. I think the reason for the wrong usages is
that we used to have types on the module, and then removed that, so more is
now validatable actually.
> Fix validateGlobally usage in validator

- src/ir/names.h
- src/passes/MemoryPacking.cpp
- test/passes/memory-packing_all-features.txt
Such a collision can happen if we run the pass twice, and somehow it finds
more to optimize.
To make this easy, add a general utility for getting a unique name based on
a root + a numeric suffix to avoid collisions.
Fixes the testcase in https://github.com/WebAssembly/binaryen/issues/3225#issuecomment-709395467
> Avoid name collisions in MemoryPacking

- check.py
- scripts/test/shared.py
The spec interpreter is no longer used at all. Mozjs is still used optionally, but
while it was crucial in the past for test coverage, it is entirely optional now and
not run by default, so no need to warn.
> Test cleanup: Remove remnants of spec interpreter, and excess mozjs warning

- src/tools/fuzzing.h
- test/passes/fuzz_metrics_noprint.bin.txt
Move the tweak function to an outer location, and call it from `mutate()` with
some probability.
> Fuzzer: Tweak constants during mutation as well

- src/passes/SimplifyLocals.cpp
- test/passes/simplify-locals_all-features.txt
- test/passes/simplify-locals_all-features.wast
We checked if the type matches when deciding if two locals are equivalent,
but if the type didn't match, we forgot to reset any previously equivalent
things. So we thought something was equivalent when it wasn't, see the
reduced testcase.
Fixes #3266
> SimplifyLocals fuzz fix: Don't be confused by subtype assigns. 

- src/tools/execution-results.h
`log_execution` can be useful to run on a fuzz testcase for debugging purposes. This
adds support to `--fuzz-exec` for printing out those values.
In general `--fuzz-exec` ignores unknown imports (so that it can be run on more wasm
files, for at least some fuzz testing there). This also adds a warning in that case, so it
is less surprising (the behavior does not change in this PR).
> Fuzzer: Handle log_execution instrumentation, and warn on unknown imports

- scripts/fuzz_opt.py
If we can't run the `-ttf` stage, there is no point in printing out the
instructions to reduce things - we can't reduce without a wasm.
> Fuzzer: Handle the case where we can't even generate the wasm file

- CMakeLists.txt
This should have been possible for a very long time. Were there any problems? exceptions? std::bad_alloc?
> Build without RTTI (-fno-rtti)

- src/tools/execution-results.h
This avoids it printing a warning and doing nothing for them.
It also increases coverage, for checking 64-bit return values, but any such
bug would have already been found already, I think (as we ignored the
high bits), so likely the fuzzer is not emitting such things when running JS
at least.
> Handle get/setTempRet0 in fuzzer support

- src/tools/wasm2c-wrapper.h
This is necessary for cases where the input has an export name that
needs mangling, like a name with `-` (common in the spec test suite).
> Fuzzer: Fix wasm2c name mangling

- src/passes/OptimizeInstructions.cpp
- test/passes/optimize-instructions_all-features.txt
- test/passes/optimize-instructions_all-features.wast
`x <<>> (y & (32 | 64))` -> `x`
> Drop RHS of shift expression if effective shift always equal to zero

- .github/workflows/ci.yml
- CMakeLists.txt
This PR adds a failing MinGW build to the CI (as I mentioned in #3039) and then a separate PR that adds the recommended solution from the comments.
I was reading in the `check.py` that Windows + gcc tests need additional work, so I didn't enable tests for the MinGW build, but it at least builds successfully now.
I'm hoping this helps our integration with Binaryen into Grain.
> Fix MinGW build & add to GitHub Actions

- src/wasm.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-debug.cpp
- src/wasm/wasm-stack.cpp
- test/passes/fannkuch0_dwarf.bin.txt
- test/passes/fannkuch3_dwarf.bin.txt
- test/passes/fannkuch3_manyopts_dwarf.bin.txt
- test/passes/fib_nonzero-low-pc_dwarf.bin.txt
Previously when we processed a block for example, we'd do this:
```
;; start is here
(block (result type)
;; end is here
.. contents ..
)
;; end delimiter is here
```
Not how this represents the block's start and end as the "header", and
uses an extra delimiter to mark the end.
I think this is wrong, and was an attempt to handle some offsets from
LLVM that otherwise made no sense, ones at the end of the "header".
But it turns out that this makes us completely incorrect on some things
where there is a low/high pc pair, and we need to understand that the
end of a block is at the end opcode at the very end, and not the end of
the header. This PR changes us to do that, i.e.
```
;; start is here
(block (result type)
.. contents ..
)
;; end is here
```
This fixes a testcase already in the test …
> DWARF: Fix handling of the end of control flow instructions

- src/wasm-delegations.h
- src/wasm-traversal.h
Split off from #3264, this part is hopefully non-controversial.
> Reduce boilerplate with a C macro for class delegations. NFC

- src/passes/Inlining.cpp
- test/passes/inlining_all-features.txt
- test/passes/inlining_all-features.wast
Without this, we might think a function has no global uses if the only
global use of it is the start.
> Inlining fix: Note the start function

- src/js/binaryen.js-post.js
During debugging of a related problem using a debug build of binaryen.js, I was hitting the following error:
```
Error: abort(Error: abort(Assertion failed: allocate no longer takes a type argument)
at jsStackTrace (path\to\binaryen.js:1279776:19)
at stackTrace (path\to\binaryen.js:1279793:16)
at abort (path\to\binaryen.js:1279488:44)
at assert (path\to\binaryen.js:1278645:5)
at allocate (path\to\binaryen.js:1278734:3)
at strToStack (path\to\binaryen.js:1287254:16)
```
triggered [around here](https://github.com/emscripten-core/emscripten/blob/437266ac3dfd61747e53bc6e4ae57b81c92dc093/src/preamble.js#L212-L217), introduced in https://github.com/emscripten-core/emscripten/pull/12279.
Is this the right fix?
> Fix usage of `allocate` in JS (no longer takes a type argument)

- src/passes/OptimizeInstructions.cpp
- test/passes/optimize-instructions_all-features.txt
We could still make `x * -1.0` cheaper for non-fastMath mode as:
`x * -1.0` -> `-0.0 - x`
Also it could potentially optimize in later for this scenario:
```ts
a + b * -1
> a + (-0.0 - b)
> (a - 0.0) - b
> a - b
```
> Optimize x * -1.0 for non-fastMath case

- src/pass.h
- src/passes/Inlining.cpp
This simplifies the three size-related inlining flags, so that their
meanings are clearer. Also improve the comments and put them
in a consistent order in both files.
This should not make any difference in general, except that it is now
possible to have `oneCallerInlineMaxSize > flexibleInlineMaxSize`,
and we will inline a function with one caller if
`flexibleInlineMaxSize < FUNCTION_SIZE <= oneCallerInlineMaxSize`
which we would not before. As the defaults of the flags didn't fit that
case, this should not change anything for anyone not passing in
those specific inlining flags. For people that pass in those flags, this
PR makes more things possible.
Resolves the FIXME in that code, and is a refactoring before some
more inlining work I have planned.
> Inlining: Slight reordering of options

- src/asmjs/shared-constants.cpp
- src/asmjs/shared-constants.h
- src/passes/PostEmscripten.cpp
- test/passes/post-emscripten.txt
- test/passes/post-emscripten.wast
We no longer build modules that import `global.Math`.
> Remove OptimizeCalls from PostEmscripten. 

- check.py
- scripts/test/shared.py
This makes it easier to install libbinaryen.so into an alternative
locations. Fixes part of issue #2999 for me.
> Allow setting the path to libbinaryen.so shared library

- src/passes/OptimizeInstructions.cpp
- test/passes/optimize-instructions_all-features.txt
- test/passes/optimize-instructions_fuzz-exec.txt
- test/passes/optimize-instructions_fuzz-exec.wast
```
X - Y <= 0
=>
X <= Y
```
That is true mathematically, but not in the case of an overflow, e.g. 
X=10, Y=0x8000000000000000. X - Y is a negative number, so
X - Y <= 0 is true. But it is not true that X <= Y (as Y is negative, but
X is not).
See discussion in https://github.com/WebAssembly/binaryen/pull/3303#issuecomment-725632036
The actual regression was in #3275, but the fuzzer had an easier time
finding it due to #3303
> OptimizeInstructions: Fix regression from #3303 / #3275

- scripts/fuzz_opt.py
- test/passes/optimize-instructions_all-features.txt
- test/passes/optimize-instructions_all-features.wast
`OptimizeInstructions` is seeing the most work these days (thanks @MaxGraey !)
so it's good for the fuzzer to focus on that some more.
Also move some code around in the main test wast: it's useful to put each
feature in its own module to maximize the chance of getting them to be used.
That is, if a module has a single use of atomics, then if atomics are disabled
in the current run, we can't use any of the module and we skip initial contents
entirely. Moving each feature to it's own module reduces that risk. (We do
pick randomly between the modules, and atm a small module has the same
chance as a big one, but this still seems worth it.)
> [Fuzzer] Add a chance to pick particularly important initial contents

- scripts/fuzz_opt.py
Previously we picked one of the two compilers at the top level. But that doesn't
actually compare between them directly - each entire run used one of the two.
Instead, add separate "VMs" for each of them, and keep the existing D8 VM as
well (which tests tiering up).
The code also seems nicer this way.
> [Fuzzer] Compare D8 on Liftoff and TurboFan

- check.py
- src/ir/CMakeLists.txt
- src/ir/module-splitting.cpp
- src/ir/module-splitting.h
- src/ir/names.h
- src/wasm-builder.h
- src/wasm.h
- src/wasm/wasm.cpp
- test/example/module-splitting.cpp
- test/example/module-splitting.txt
Adds the capability to programatically split a module into a primary and
secondary module such that the primary module can be compiled and run before the
secondary module has been instantiated. All calls to secondary functions (i.e.
functions that have been split out into the secondary module) in the primary
module are rewritten to be indirect calls through the table. Initially, the
table slots of all secondary functions contain references to imported
placeholder functions. When the secondary module is instantiated, it will
automatically patch the table to insert references to the original functions.
The process of module splitting involves these steps:
1. Create the new secondary module.
2. Export globals, events, tables, and memories from the primary module and
import them in the …
> Module splitting

- CMakeLists.txt
Don't hardcode `lib`, it's incorrect for many systems (e.g. `lib64` is common on some x86_64 distros like openSUSE). Use `CMAKE_INSTALL_LIBDIR` instead.
The `APPLE` branch may need the same change, but I don't have any apple systems to confirm this, so I left it as-is.
> build/linux: more correct rpath handling

- src/wasm/wasm.cpp
This function does not return exact instruction names but more of
category names. But when there is a matching instruction, as in case of
`global.get/set` or `local.get/set`, it seems to return instruction
names. In that regard, this makes `getExpressionName`'s return values to
similar to that of real instruction names when possible, in case of
some atomic instructions and `memory.init/copy` and `data.drop`.
It is hard to make a test for this because this function is used in a
very limited way in the codebase, such as:
- When printing error messages
- When printing a stack instruction names, but only for control flow
instructions
- When printing instruction names in Metrics
> Make getExpressionName resemble instruction names

- src/wasm-delegations-fields.h
The end macro is not actually used yet, it is just for symmetry. And apparently
gcc/clang do not warn on this, so it was missed...
Fixes #3350
> Fix warnings in delegations-fields header

- src/wasm/wasm-debug.cpp
- third_party/llvm-project/DWARFEmitter.cpp
- third_party/llvm-project/include/llvm/ObjectYAML/DWARFYAML.h
We change the AddrSize which causes all DW_FORM_addr to be written differently.
Depends on https://reviews.llvm.org/D91395
This may need a test.. sadly dwarfdump doesn't show the size of DW_FORM_addr, they're always 64-bit. So its only `addr_size = 0x04` in the header thats evidence of this code working.
> [wasm64] fix for Memory64Lowering affecting DWARF data

- src/ir/module-utils.h
- src/passes/Asyncify.cpp
- src/passes/PostEmscripten.cpp
This is in preparation for [`CallRef`](https://github.com/WebAssembly/function-references/blob/master/proposals/function-references/Overview.md), which takes a reference to a function
and calls it.
CallGraphPropertyAnalysis needs to be aware of anything that is not a
direct call, and the best name I can think of that covers `CallIndirect` and
`CallRef` is "non-direct". Maybe there's a better idea though?
> Rename Indirect to NonDirect in CallGraphPropertyAnalysis

- src/wasm-s-parser.h
- src/wasm/wasm-s-parser.cpp
We will need this for typed function references support, as then we need
to know full function signatures for all functions when we reach a `ref.func`,
whose type is then that signature and not the generic `funcref`.
> [s-parsing] Store full function signatures

- src/literal.h
- src/wasm-interpreter.h
Before this, all function literals would have `funcref` type. This allows a custom type
to be provided.
The interpreter passes in the type of the `ref.func` expression. Currently this has
type `funcref` so there is no change, but when typed function references lands and
is enabled then the proper subtype will be used.
> [TypedFunctionReferences] Allow creation of literals with typed function types

- src/wasm/wasm-type.cpp
This is necessary to support typed function references.
> [Types] Identify subtyping between funcref and all typed function references

- .github/workflows/ci.yml
- requirements-dev.txt
This file makes it simple for users and CI bots to install all the Python dev
dependencies necessary to run the test suite. Right now it only contains flake8,
but soon it will contain lit and filecheck as well (see #3367).
> Add requirements-dev.txt

- src/ir/cost.h
cost.h now requires costs be defined, or it halts at runtime. But the fuzzer
already emits those two, so define them to unbreak the fuzzer.
Both access a reference, so they should be at least as costly as a load.
I31New also allocates, which is very cheap on a generational GC, so do not
add much for that.
> [cost.h] Define costs for I31New and I31Get which the fuzzer emits

- src/passes/ReReloop.cpp
I happened to notice that this was the one place that calls ReFinalize
without the module. That could error if the module is actually needed,
which the pass might use, based on the code (but rare enough that it's
never been an issue I guess).
> [ReReloop] Pass module when calling ReFinalize

- src/tools/execution-results.h
There are several issues here that we can't fully handle, see https://github.com/WebAssembly/binaryen/issues/3378, but basically
we are comparing results between two separate wasm modules (and
a separate instance of each) - we can't really identify an identical
reference between such things. We can only compare things structurally,
for which we compare the types.
This is a little unfortunate, but I don't see a better solution. For some
types of bugs we'll need another approach.
> [Fuzzer] Don't compare references, just their types

- src/ir/effects.h
- src/passes/LoopInvariantCodeMotion.cpp
The new `writesGlobalState` has a name that more clearly indicates what it
actually does. This removes `throw` from there, and handles it directly in the
single caller of the method.
Add `hasExternallyNoticeableEffects` which is what the old `hasGlobalSideEffects`
was maybe trying to be, but does it in a clearer way. There are currently no
users but a wip PR of mine will need this very soon.
I wrote this PR because that future PR tried to use `hasGlobalSideEffects` but
it really wasn't well-defined enough. The logic there is somewhat specific to
the single caller of the old method, I guess.
> [effects.h] Refactor hasGlobalSideEffects and throw handling. NFC

- src/tools/wasm-reduce.cpp
Let it reduce the other stuff it can, even if it can't reduce some things.
> [Reducer] Don't error on compound types, just skip them for now

- src/ir/effects.h
- src/passes/CodePushing.cpp
- src/passes/Vacuum.cpp
A user of `EffectAnalyzer` could call `walk` or `visit`, to walk the entire
input or just visit the node without chlidren. But this was unsafe - we just
exposed the Walker/Visitor API here, and did not ensure that users did
the stuff in `analyze` which does a little stuff before and after. In fact
`Vacuum` got this wrong.
To avoid that, move all the internals to an internal class. The external
API now only allows the caller to call `walk` or `visit`, and both are safe.
The change here is mostly whitespace + adding `parent.` prefixes.
This is NFC except for fixing possible Vacuum issues (which I am not sure
could happen in practice or not).
> [effects.h] Make internals internal, forcing the external API to be safe.

- src/passes/InstrumentLocals.cpp
- src/wasm-builder.h
- src/wasm/literal.cpp
- src/wasm/wasm-type.cpp
- src/wasm/wasm-validator.cpp
Call `isFunction` to check for a general function type instead of just
a `funcref`, in places where we care about both, and some other minor
miscellaneous typing fixes in preparation for typed function references
(this will be tested fully at that time).
Change is mostly whitespace.
> [Types] Handle function types fully in more places

- src/ir/effects.h
- test/example/cpp-unit.cpp
We did not really model the effects of `unreachable` properly before. It
always traps, so it's not an implicit trap, but we didn't do anything but mark
it as "branches out", which is not really enough, as while yes it does
branch inside the current function, it also traps which is noticeable outside.
To fix that, add a `trap` effect to track this. `implicitTrap` will set `trap` as well,
automatically, if we do not ignore implicit traps, so it is enough to check just
that (unless one cares about the difference between implicit and explicit
ones).
> [effects.h] Add a trap effect for unreachable

- src/passes/Asyncify.cpp
- src/passes/FuncCastEmulation.cpp
- src/passes/GenerateDynCalls.cpp
- src/passes/I64ToI32Lowering.cpp
- src/passes/LegalizeJSInterface.cpp
- src/passes/StackCheck.cpp
- src/tools/fuzzing.h
- src/wasm-binary.h
- src/wasm-builder.h
- src/wasm/wasm-binary.cpp
When Functions, Globals, Events, and Exports are added to a module, if they are
not already in std::unique_ptrs, they are wrapped in a new std::unique_ptr owned
by the Module. This adds an extra layer of indirection when accessing those
elements that can be avoided by allocating those elements as std::unique_ptrs.
This PR updates wasm-builder to allocate module elements via std::make_unique
rather than `new`. In the future, we should remove the raw pointer versions of
Module::add* to encourage using std::unique_ptrs more broadly.
> [wasm-builder] Construct module elements as unique_ptrs

- CMakeLists.txt
- src/tools/tool-options.h
- src/tools/wasm-split.cpp
- test/lit/wasm-split/basic.wast
- test/lit/wasm-split/invalid-options.wast
- test/lit/wasm-split/verbose.wast
Implement an initial version of the wasm-split tool, which splits modules into a
primary module and a secondary module that can be instantiated after the primary
module. Eventually, this tool will be able to not only split modules, but also
instrument modules to collect profiles that will be able to guide later
splitting. In this initial version, however, wasm-split can neither perform
instrumentation nor consume any kind of profile data.
Despite those shortcomings, this initial version of the tool is already able to
perform module splitting according to function lists manually provided by the
user via the command line. Follow-up PRs will implement the stubbed out
instrumentation and profile consumption functionality.
> Initial wasm-split tool

- src/passes/StackCheck.cpp
These can be simply raw pointers, given that they are stored in modules
using `unique_ptr`s.
Context:
https://github.com/WebAssembly/binaryen/pull/3391#discussion_r527495451
> Let EnforceStackLimits have pointers to Globals (NFC)

- src/support/file.h
- src/tools/wasm-split.cpp
- test/lit/wasm-split/call_exports.mjs
- test/lit/wasm-split/profile-guided.wast
Read the profiles produced by wasm-split's instrumentation to guide splitting.
In this initial implementation, all functions that the profile shows to have
been called are kept in the initial module. In the future, users may be able to
tune this so that functions that are run later will still be split out.
cc @sbc100 @awtcode
> [wasm-split] Read and use profiles

- src/ir/properties.h
Use matchers and more descriptive variable names to clarify the intent of the
functions for finding and inspecting sign extension patterns.
> [NFC] Clean up sign/zero extension code in properties.h

- src/passes/OptimizeInstructions.cpp
- test/passes/optimize-instructions_all-features.txt
- test/passes/optimize-instructions_fuzz-exec.txt
- test/passes/optimize-instructions_fuzz-exec.wast
The old code there was buggy, it turns out. I rewrote it to handle only the cases
that are obviously correct, which removes the bug. I believe this does not lose
any valid optimization cases, but frankly the old code was hard to read - best
to just read the new code there, I think (very unlikely this optimization is that
important anyhow).
> [OptimizeInstructions] Fix a fuzz bug with comparing signed and unsigned values

- scripts/fuzz_opt.py
When running d8, run it in liftoff, to avoid tiering up causing nondeterminism
in the results.
When we do want to compare the tiers, we already do so in CompareVMs. This
fixes others places where we just wanted to run some JS in some VM.
> [Fuzzer] Do not compare V8 tiers unintentionally

- src/passes/Print.cpp
- test/passes/optimize-instructions_all-features.txt
- test/typed-function-references.wast.from-wast
- test/typed-function-references.wast.fromBinary
- test/typed-function-references.wast.fromBinary.noDebugInfo
For a nested type, we used to print e.g.
```wat
(param $x (ref (func (param i32))))
```
Instead of expanding the full type inline, which can get long for
a deeply nested type, print a name when running the Print pass.
In this example that would be something like
```wat
(param $x (ref $i32_=>_none))
```
> [Printing] Print type names where possible.

- auto_update_tests.py
- src/emscripten-optimizer/istring.h
- src/ir/module-splitting.cpp
- src/ir/module-splitting.h
- test/example/module-splitting.cpp
- test/example/module-splitting.txt
Extend the splitting logic to handle splitting modules with a single table
segment with a non-const offset. In this situation the placeholder function
names are interpreted as offsets from the table base global rather than absolute
indices into the table. Since addition is not allowed in segment offset
expressions, the secondary module's segment must start at the same place as the
first table's segment. That means that some primary functions must be duplicated
in the secondary segment to fill any gaps. They are exported and imported as
necessary.
cc @sbc100 @awtcode I hope this is sufficient to get wasm-split working with
dynamic linking and PIC more generally.
> [module-splitting] Allow splitting with non-const table offsets

- src/tools/wasm-split.cpp
- test/lit/wasm-split/instrument-funcs.wast
- test/lit/wasm-split/mismatched-hashes.wast
Calculate a checksum of the original uninstrumented module and emit it as part
of the profile data. When reading the profile, compare the checksum it contains
to the checksum of the module that is being split. Error out if the module being
split is not the same as the module that was originally instrumented.
Also fixes a bug in how the profile data was being read. When `char` is signed,
bytes read from the profile were being incorrectly sign extended. We had not
noticed this before because the profiles we have tested have contained only
small-valued counts.
cc @sbc100 @awtcode.
> [wasm-split] Record checksums in profiles

- src/ir/properties.h
- test/passes/optimize-instructions_all-features.txt
- test/passes/optimize-instructions_all-features.wast
This code was edited recently but it seems to not be a regression, rather a
bug that was there all along.
> [OptimizeInstructions] Fix a fuzz bug with getting the shifts of an unreachable

- src/wasm/wasm-debug.cpp
See https://reviews.llvm.org/D91803 -  there are now -1 or -2 in places that
mark something that the linker removed as not existing/not relevant. We should
ignore those like we ignore 0s there.
> [DWARF] Properly handle LLVM's new tombstone values

- src/wasm-type.h
- src/wasm/wasm-type.cpp
I am starting to write lines like
```cpp
curr->value->type.getHeapType().getStruct().fields[curr->index].type
```
and it scares me to think that there may be copies going on there.
The issue is that Types are interned, but HeapTypes and their components
are not.
Talking to @tlively , we think this should avoid the perf issue and also
allow for possible interning of more things in the future. I am happy to see
that it compiles without needing any changes.
> [Types] Return const& for HeapTypes and their Structs and Arrays. NFC

- src/literal.h
- src/wasm-type.h
- src/wasm/literal.cpp
- src/wasm/wasm-type.cpp
This name is more descriptive and paves the way toward interning HeapTypes as
well, with an analogous BasicHeapType.
> [NFC] Rename BasicID to BasicType

- src/passes/SafeHeap.cpp
- test/passes/safe-heap_start-function.passes
- test/passes/safe-heap_start-function.txt
- test/passes/safe-heap_start-function.wast
In relocable code (MAIN/SIDE modules) we use the start function to run
`__wasm_init_memory` which loads the data segments into place.   We
can't call get_sbkr pointer during that function because the sbrk
pointer itself lives in static data segment.
> Don't apply SafeHeap to wasm start function

- src/ir/cost.h
- src/ir/effects.h
- src/ir/module-utils.h
- src/literal.h
- src/passes/Print.cpp
- src/wasm-builder.h
- src/wasm-delegations-fields.h
- src/wasm-interpreter.h
- src/wasm.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-s-parser.cpp
- src/wasm/wasm-stack.cpp
- src/wasm/wasm-validator.cpp
- src/wasm/wasm.cpp
- test/heap-types.wast
- test/heap-types.wast.from-wast
- test/heap-types.wast.fromBinary
- test/heap-types.wast.fromBinary.noDebugInfo
Mostly straightforward after `struct.get`.
This renames the `value` field in `struct.get` to `ref`. I think this makes
more sense because `struct.set` has both a reference to a thing, and a
value to set onto that thing. So calling the former `ref` seems more
consistent, giving us `ref, value`. This mirrors `load/store` for example
where we use `ptr, value`, and `ref` is playing the role of `ptr` here
basically.
> [GC] Add struct.set

- .github/workflows/ci.yml
- CMakeLists.txt
- check.py
- scripts/binaryen-lit.in
- test/lit/lit.cfg.py
- test/lit/lit.site.cfg.py.in
This uses the same technique used in llvm-lit to enable
running on in-tree tests with out-of-tree builds.
So you can run something like this:
../binaryen-out/bin/binaryen-lit test/lit/
> Improve lit support

- src/ir/cost.h
- src/ir/effects.h
- src/literal.h
- src/passes/Print.cpp
- src/support/small_vector.h
- src/wasm-binary.h
- src/wasm-builder.h
- src/wasm-delegations-fields.h
- src/wasm-interpreter.h
- src/wasm-s-parser.h
- src/wasm.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-s-parser.cpp
- src/wasm/wasm-stack.cpp
- src/wasm/wasm-type.cpp
- src/wasm/wasm-validator.cpp
- src/wasm/wasm.cpp
- test/heap-types.wast
- test/heap-types.wast.from-wast
- test/heap-types.wast.fromBinary
- test/heap-types.wast.fromBinary.noDebugInfo
array.new/get/set/len - pretty straightforward after structs and all the
infrastructure for them.
Also fixes validation of the unnecessary heapType param in the
text and binary formats in structs as well as arrays.
Fixes printing of packed types in type names, which emitted i32
for them. That broke when we emitted the same name for an array
of i8 and i32 as in the new testing here.
Also fix a bug in `Field::operator<` which was wrong for packed
types; again, this was easy to notice with the new testing.
> [GC] Add Array operations

- src/tools/fuzzing.h
- src/wasm-binary.h
- src/wasm-type.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-s-parser.cpp
- src/wasm/wasm-type.cpp
- src/wasm/wasm.cpp
- test/example/type-builder.cpp
- test/example/typeinfo.cpp
Previously we were using bools for both of these concepts, but using enums makes
the code clearer. In particular, the PR removes many instances of
`/*nullability=*/ true`.
> Use enums for mutability and nullability

- src/ir/module-splitting.cpp
- test/lit/wasm-split/name-collision.wast
During module splitting, a map is constructed from internal names to their
corresponding export names. This code previously did not take into account the
fact that the same internal name may be used by different kinds of
entities (e.g. a table and a memory may have the same internal name), which
resulted in the secondary module incorrectly using the same import name for all
of the entities that shared an internal name. This PR fixes the problem by
including the ExternalKind of the entity in the keys of the export map.
> Fix wasm-split name collision bug

- src/tools/wasm-split.cpp
- test/lit/wasm-split/initial-table.wast
Adds an option to wasm-split to allow the user to specify the initial table size
for both instrumenting and splitting use cases. In the short term this will be
used in Emscripten SPLIT_MODULE + dynamic linking workflow to ensure that the
expected table size baked into the JS works for both the instrumented and the
primary split modules. In the longer term this may be replaced with a more
elegant mechanism for making the JS works in both cases.
cc @awtcode @sbc100
> [wasm-split] Add an --initial-table option

- src/ir/module-splitting.cpp
- test/example/module-splitting.cpp
- test/example/module-splitting.txt
`ModuleSplitter::thunkExportedSecondaryFunctions` creates a thunk for each
secondary function that needs to be exported from the main module. Previously,
if a secondary function was exported twice, this code would try to create two
thunks for it rather than just making one thunk and exporting it twice. This
caused a fatal error because the second thunk had the same name as the first
thunk and therefore could not be added to the module. This PR fixes the issue by
creating no more than one thunk per function.
> [module-splitting] Fix a crash when a function is exported twice

- src/wasm/wasm-validator.cpp
- test/heap-types.wast
- test/heap-types.wast.from-wast
- test/heap-types.wast.fromBinary
- test/heap-types.wast.fromBinary.noDebugInfo
As suggested, the validation code can be further simplified after adding `castType`.
> Followup to #3451 after feedback

- src/binaryen-c.cpp
- src/passes/MemoryPacking.cpp
- src/wasm-s-parser.h
- src/wasm.h
- src/wasm/wasm-s-parser.cpp
- test/unit/test_memory_packing.py
Also avoid packing builtin llvm segments names so that
segments such as `__llvm_covfun` (use by llvm-cov) are
preserved in the final output.
> MemoryPacking: Preserve segment names

- scripts/test/shared.py
`node` is the name used by the upstream project.  `nodejs` is a legacy
name used on older debian/ubunru systems.
Searching for `nodejs` first meant it was finding my local (old)
`nodejs` package even those I have a more recent `node` in my $PATH.
> When looking for node binary, search for 'node' first

- src/ir/module-utils.h
- src/passes/Print.cpp
- src/support/string.h
- src/wasm-type.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-s-parser.cpp
- src/wasm/wasm-type.cpp
- src/wasm/wasm-validator.cpp
- test/gc.wast
- test/gc.wast.from-wast
- test/gc.wast.fromBinary
- test/gc.wast.fromBinary.noDebugInfo
- test/passes/simplify-globals_all-features_fuzz-exec.txt
- test/passes/simplify-locals_all-features.txt
This lets us parse `(ref null i31)` and `(ref i31)` and not just `i31ref`.
It also fixes the parsing of `i31ref`, making it nullable for now, which we
need to do until we support non-nullability.
Fix some internal handling of i31 where we had just i31ref (which meant we
just handled the non-nullable type).
After fixing a bug in printing (where we didn't print out `(ref null i31)`
properly), I found some a simplification, to remove `TypeName`.
> [GC] Fix parsing/printing of ref types using i31

- src/wasm/wasm-validator.cpp
- test/heap-types.wast
- test/heap-types.wast.from-wast
- test/heap-types.wast.fromBinary
- test/heap-types.wast.fromBinary.noDebugInfo
- test/passes/Oz_fuzz-exec_all-features.txt
- test/passes/Oz_fuzz-exec_all-features.wast
This required a few test fixes, to ensure we don't have invalid wasts with
writes to immutable fields.
> [GC] Validate that struct.set is to a mutable field.

- src/wasm/literal.cpp
I tried to investigate this from every angle I can think of and it makes no sense...
I am 99% sure the type there is an `externref`, which is basic of course. So the
only possibility is that some other type is present somehow..? Anyway, this may
help figure it out.
See https://github.com/WebAssembly/binaryen/issues/3459
> Add more verbose logging of an assert that only happens on the release builder

- src/literal.h
- src/tools/wasm-shell.cpp
- src/wasm/literal.cpp
- test/example/cpp-unit.cpp
- test/example/cpp-unit.txt
To handle both nullable and non-nullable i31s and other heap types, we cannot
just look at the isBasic case (which is just one of the two).
This *may* fix this issue on the release builder: https://github.com/WebAssembly/binaryen/runs/1669944081?check_suite_focus=true but the issue does not reproduce locally, so I worry it is something else...
> [GC] More HeapType instead of Type

- src/wasm-interpreter.h
- test/passes/Oz_fuzz-exec_all-features.txt
- test/passes/Oz_fuzz-exec_all-features.wast
The code previously assumed it could always call `getGCData`, but
that assumes the input is an array or a struct. It could also be an
anyref etc. that contains something other than GC data.
> [GC] Fix casts of non-GC data

- src/mixed_arena.h
Because `resize()` [sets](https://github.com/WebAssembly/binaryen/blob/dc7184afcbdcc72d0a6d66e2b36fc5857050dd87/src/mixed_arena.h#L204) `usedElements` to its argument, we were
accessing `data[usedElements]`, which can be outside of allocated memory
depending the internal state, i.e., `allocatedElements`'s value.
It is hard to come up with a test case for this because apparently the
failure condition depends on the vector's internal state.
> Fix an index error in ArenaVectorBase::insertAt

- src/mixed_arena.h
Followup to #3486, I wonder if it isn't a little more clear this way,
which avoids the confusion of `usedElements` being changed
while we are using it?
In general I think it's best to only use `usedElements` in the most
internal methods, and to call `size()` otherwise. But I don't feel
strongly.
> Avoid usedElements around code that modifies that value

- CMakeLists.txt
Also uses lld as the linker. Not on by default, so far tested on Linux and Windows.
> Add support for building with thinLTO

- src/tools/wasm-reduce.cpp
- test/unit/test_reduce.py
The risk the warning checks for is giving the reducer a script that ignores
the input. To do so it runs the command in the input, and runs it on a
garbage file, and checks if the result is different. However, if the script
does immediately fail on the input - because the input is a crash testcase
or such - then this does not work, as the result on a garbage input may be
the same error.
To avoid that, also check what happens on a trivial valid wasm as input.
Only show the warning if the result on the original input, on a garbage
wasm, and on a trivial wasm, are all the same - in that case, likely the
script really is ignoring the input.
> Reducer: Improve warning on scripts that ignore the input

- .github/workflows/ci.yml
- Contributing.md
- README.md
- scripts/clang-format-diff.sh
- scripts/clang-tidy-diff.sh
We have updated the default branch name from "master" to "main." This PR updates
scripts, configurations, and docs to reflect this change.
> Replace "master" with "main" in scripts and docs

- src/js/binaryen.js-post.js
- test/binaryen.js/expressions.js
This uses existing `getAllNested` function in `ExpressionWrapper`
functions. Also adds `setAllNested` which works in the other direction
and uses it within `ExpressionWrapper` functions.
> Simplify set/gets of vectors in binaryen.js

- check.py
- src/shell-interface.h
- src/tools/wasm-ctor-eval.cpp
- src/tools/wasm-shell.cpp
- src/wasm-interpreter.h
- src/wasm/wasm-interpreter.cpp
- src/wasm/wasm-validator.cpp
- test/spec/exception-handling.wast
This updates the interpreter for the EH instructions (modulo `delegate`)
to match the new spec. Before we had an `exnref` type so threw a
`Literal` of `exnref` type which contained `ExceptionPackage`. But now
that we don't have `exnref` anymore, so we add the contents of
`ExceptionPackage` to `WasmException`, which is used only for the
`ExpressionRunner` class hierarchy. `exnref` and `ExceptionPackage` will
be removed in a followup CL.
This allows nonzero depths for `rethrow` for now for testing; we
disallowed that for safety measure, but given that there are no passes
that modifies that field, I think the risk is low.
> Update interpreter for new EH spec

- test/lit/passes/optimize-instructions.wast
FileCheck test cases are much more readable when their output assertions are
close to the corresponding input lines. #3503 introduced a script for updating
FileCheck assertions, but it only knows how to place input and output lines
together at the function boundary, so smaller functions will produce more
readable tests. optimize-instructions.wast has some very large functions that
include many test cases, so this PR breaks up some of those functions into
smaller functions to make the tests more readable. This PR only changes the
first quarter of the file, leaving further improvements as future work.
> Partially split up functions in optimize-instructions.wast

- CMakeLists.txt
This was originally landed as part of #3484 but this broke the emsdk CI
because we build binaryen on bionic there which is stuck on 3.10.2:
https://packages.ubuntu.com/bionic/cmake
We do use `add_link_options` but only when EMSCRIPTEN is defined which
doesn't effect normal desktop builds.
> Revert cmake version requirement bump

- src/wasm-binary.h
- src/wasm/wasm-binary.cpp
wasm-finalize currently makes byte-wise copies of section data in the user and data sections. If the section is large, that's extraordinarily expensive. With a memcpy instead I see a speedup of 1.6 for a large wasm binary with DWARF data.
> Memcpy data instead of bytewise copies

- scripts/test/shared.py
`minify_check` checks that we can print and read minified wast. The test
also, however, assumed that we round-trip such things perfectly. That's
never been true, and only by chance did this go unnoticed until now,
in https://github.com/WebAssembly/binaryen/pull/3523
The specific issue happening there is that we create a block without a
name. Then we write that as text, then read it. When we read it, we give
all such blocks a name (and we rely on optimizations to remove it later
when possible - this avoids optimizing in the parser). The extra name
looks like a bug to minify_check.
> Remove test suite's assumption of minify_check roundtripping perfectly

- scripts/test/shared.py
- src/passes/Print.cpp
- src/wasm-builder.h
- src/wasm-delegations-fields.h
- src/wasm.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-s-parser.cpp
- src/wasm/wasm-validator.cpp
- src/wasm/wasm.cpp
- test/heap-types.wast
- test/heap-types.wast.from-wast
- test/heap-types.wast.fromBinary
- test/heap-types.wast.fromBinary.noDebugInfo
- test/passes/Oz_fuzz-exec_all-features.wast
I removed it from the binary format earlier, but forgot the text.
As a result, we cannot handle a `br_on_cast` with an unreachable RTT. The
binary format solves the problem by ignoring unreachable code, and this makes
the text format do the same.
A nice benefit of this is that we can remove the `castType` extra field.
> [GC] Update br_on_cast: the text format also no longer has a heap type

- scripts/gen-s-parser.py
- src/gen-s-parser.inc
- src/passes/Print.cpp
- src/wasm-binary.h
- src/wasm-interpreter.h
- src/wasm.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-stack.cpp
- src/wasm/wasm.cpp
- test/heap-types.wast
- test/heap-types.wast.from-wast
- test/heap-types.wast.fromBinary
- test/heap-types.wast.fromBinary.noDebugInfo
This is different than the other RefAs variants in that it is part of the
typed functions proposal, and not GC. But it is part of GC prototype 3.
Note: This is not useful to us yet as we don't support non-nullable types.
> [GC] ref.as_non_null

- src/wasm/wasm-stack.cpp
This break stack is maintained to compute branch depths, but it seems we
don't need to push and pop for each of if and else block or every single
catch/catch_all block; it would be sufficient to have just one stack
entry for the whole try-catch or if-else.
> Remove unnecessary breakStack pushes for if/try (NFC)

- src/tools/fuzzing.h
- test/passes/translate-to-fuzz_all-features_metrics_noprint.txt
That type is non-nullable, so we need to disable it until we fully support that.
Right now if we emit such locals we immediately get a validation error.
With this change the fuzzer can run at least a few thousand iterations with
no errors once more.
> [GC] Don't emit i31ref in fuzzer

- src/literal.h
- src/wasm-interpreter.h
- src/wasm-type.h
- src/wasm/literal.cpp
- src/wasm/wasm-type.cpp
We added `isGCData()` before we had dataref. But now there is a clear
parallel of Function vs Data. This PR makes us more consistent there,
renaming `isGCData` to `isData` and using that throughout.
This also fixes a bug where the old isGCData just checked if the input
was an Array or a Struct, and ignored the `data` heap type itself. It is not
possible to test that, however, due to other bugs, so that is deferred.
> [GC] isGCData => isData

- src/passes/Print.cpp
As discussed in #3517, we need a way to maintain the ability to print
expressions in a backward-compatible way. This adds a `FeatureSet`
to `PrintExpressionContents` which defaults to `FeatureSet::All` in
case a feature set is not available.
This will be used for call_indirect to decide whether to print the table
name arg.
> Allow printing expressions based on feature set

- src/passes/Print.cpp
- src/passes/StackIR.cpp
- src/wasm/wasm-stack.cpp
- test/passes/generate-stack-ir_optimize-stack-ir_print-stack-ir_all-features.txt
- test/passes/generate-stack-ir_optimize-stack-ir_print-stack-ir_all-features.wast
This adds missing stack IR printing support for the new form of
try-catch-catch_all. Also uses `printMedium` when printing instructions
consistently.
> Support Stack IR for new try-catch(_all)

- src/wasm/wasm-type.cpp
This addresses the feedback to #3536 , except for @tlively 's suggestion to add
an `isEq()` method. I feel that might not be worth it, since it may be used only in
that one place in the last upper bound computation - we won't need it in the
interpreter or anything I can think of, because there is no `br_on_eq` etc. - thoughts?
> [GC] Feedback for #3536

- src/passes/Print.cpp
- src/wasm/wasm-validator.cpp
- test/heap-types.wast
- test/heap-types.wast.from-wast
- test/heap-types.wast.fromBinary
- test/heap-types.wast.fromBinary.noDebugInfo
If the reference is unreachable then we cannot find the heap type to print
in the text format. Instead of crashing or emitting something invalid, print
a block instead -  the block contains the children so they are emitted, and
as the instruction was unreachable anyhow, this has no noticeable effect.
It also parallels what we do in the binary format - skip unreachable code.
> [GC] Do not crash on unreachable inputs to struct.get/set

- test/wasm2js/emscripten-grow-yes.2asm.js
- test/wasm2js/emscripten-grow-yes.2asm.js.opt
- test/wasm2js/emscripten-grow-yes.wast
Support has been there all along, but we didn't have a reference test of it.
> Add a test for memory.size in wasm2js

- CHANGELOG.md
- scripts/test/shared.py
- scripts/test/wasm_opt.py
- src/tools/wasm-dis.cpp
This will allow .fromBinary tests be executed with the desired features
so there will be no difference between those tests and .from-wast tests.
Fixes #3545, unblocks #3517
> Add feature options to wasm-dis

- src/wasm/wasm-emscripten.cpp
- test/lit/wasm-emscripten-finalize/em_js.wat
The algorithm was trying to remove all __em_js functions but it was
using the names of functions rather than export names so it was failing
to remove these functions unless the internal function names happened to
match (this turns out of the true for build with debug names).
> Fix removal of EM_JS functions

- src/asm_v_wasm.h
- src/wasm-interpreter.h
- test/passes/Oz_fuzz-exec_all-features.txt
- test/passes/Oz_fuzz-exec_all-features.wast
I had completely missed that the spec allows `ref.cast` etc. of function types,
and not just data. Function types do not have an RTT, unlike GC data, but we
can still cast them. A function reference has the canonical RTT of the signature
for that type, so it's like a simplified case of the GC world, without a hierarchy
of RTTs.
cc @jakobkummerow who pointed this out - thanks!
As it turns out, our validation did not rule out `rtt.canon` of a function type,
nor `ref.cast` of one, so we unintentionally already had all the support for this
aside from the actual casting, which this PR adds.
The addition is mostly trivial, except that we now need a Module in the base
ExpressionRunner class, so that we can go from a function name to the actual
function. This PR refactors things to allow that.
> [GC] Support casts of function types

- src/tools/fuzzing.h
- src/wasm-builder.h
This allows the reducer to operate on RTTs, but could help other
things too.
> [GC] Support RTT constants in Builder::makeConstantExpression

- src/wasm/wasm-emscripten.cpp
- test/lit/wasm-emscripten-finalize/passive-pic.wat
- test/lld/em_asm.wat.mem.out
- test/lld/em_asm.wat.out
- test/lld/em_asm64.wat.out
- test/lld/em_asm_O0.wat.out
- test/lld/em_asm_main_thread.wat.out
- test/lld/em_asm_shared.wat.out
Support for multiple signatures per JS code string was removed in #2422.
emscripten now only needs to know that address and the body of the JS
function.
See https://github.com/emscripten-core/emscripten/pull/13452 for the
emscripten side that ignores this data.
> Simplify asmConst handling. NFC.

- src/ir/stack-utils.cpp
- src/ir/stack-utils.h
- src/wasm/wasm-validator.cpp
- test/example/stack-utils.cpp
- test/example/stack-utils.txt
Add a utility for calculating the least upper bounds of two StackSignatures,
taking into account polymorphic unreachable behavior. This will important in the
finalization and validation of Poppy IR blocks, where a block is allowed to
directly produce fewer values than the branches that target it carry if the
difference can be made up for by polymorphism due to an unreachable instruction
in the block.
Also removes the Poppy IR documentation from stack-utils.h because that
documentation is moved to the Stackify pass in #3541.
> StackSignature LUBs

- src/binaryen-c.h
- src/wasm/wasm-emscripten.cpp
- test/lit/wasm-emscripten-finalize/em_asm.wat
- test/lit/wasm-emscripten-finalize/em_asm_partial.wat
- test/lit/wasm-emscripten-finalize/em_js.wat
If we find a data segment whose entire contents is EM_JS or EM_ASM
strings then strip it from the binary.
This change also introduces a new way to exact EM_ASM strings based
on the __start_ and _stop_ sections symbols.   This code will no be active
until the emscripten-side change lands.
See: https://github.com/emscripten-core/emscripten/pull/13443
> finalize: strip segments that contain only EM_ASM/EM_JS data

- src/tools/tool-options.h
- test/unit/test_features.py
Perhaps I'm missing something, but is there a reason not to allow this?
That is, if a wasm says "simd", it seems ok to let the user specify simd
as well as more features, and the the optimizer can perhaps do something
with them.
> Allow specifying additional features past the features section

- src/passes/Print.cpp
- src/wasm-features.h
- test/example/c-api-multiple-tables.c
- test/passes/dwarf_with_exceptions.bin.txt
This can help in debugging issues with the features section.
As it happens we already had a wasm using the features section
in the test suite, so no addition was needed here...
> Print the features section in a comment

- src/binaryen-c.cpp
- src/binaryen-c.h
- src/js/binaryen.js-post.js
- src/wasm-builder.h
- test/binaryen.js/exception-handling.js
- test/binaryen.js/exception-handling.js.txt
- test/binaryen.js/expressions.js
- test/binaryen.js/expressions.js.txt
- test/binaryen.js/kitchen-sink.js
- test/example/c-api-kitchen-sink.c
- test/example/c-api-kitchen-sink.txt
This updates C and binaryen.js API to match the new `Try` structure to
support `delegate`, added in #3561. Now `try` can take a name (which can
be null) like a block, and also has an additional `delegateTarget` field
argument which should only be used for try-delegate and otherwise null.
This also adds several more variant of `makeTry` methods in
wasm-builder. Some are for making try-delegate and some are for
try-catch(_all).
> [EH] Update C and binaryen.js API for delegate

- scripts/test/shared.py
This removes feature flags that are now included in `--wasm-staging` and
adds new experimental flags. Does not change the fuzzer's behavior at
the moment because the fuzzer does not seem to be currently enabled for
GC or typed funcref yet.
> Update V8 feature flags for the fuzzer

- src/ir/module-splitting.cpp
- src/passes/Poppify.cpp
- src/support/debug.h
- src/wasm-interpreter.h
- third_party/llvm-project/Twine.cpp
I verified that a build without assertions builds ok with this PR.
Perhaps it makes sense to add a job that builds without assertions here? Extra work, but otherwise we'll have regressions.
> Remove assertions that prevent non-assertion builds

- src/wasm/wasm-emscripten.cpp
- test/lit/wasm-emscripten-finalize/em_js.wat
Previously emscripten always exports __em_js_XXX strings as function
that return the address of a string.
These days we can do better and simply export the address as a global.
Simpler and cleaner.
I've updated the lit tests to the new style but left the old test to covert
the function-exports.  Once the emscripten side lands I will remove
the legacy support and convert the other tests.
See corresponding emscripten side change: https://github.com/emscripten-core/emscripten/pull/13526
> Allow em_js strings to be exported as globals 

- src/passes/GenerateDynCalls.cpp
This was intended to fix [current LLVM=>emscripten autoroller breakage](https://logs.chromium.org/logs/emscripten-releases/buildbucket/cr-buildbucket.appspot.com/8854969628629209744/+/steps/Emscripten_testsuite__upstream__wasms_/0/stdout) due to https://github.com/llvm/llvm-project/commit/f48923e884611e6271a8da821a58aedd24d91cf7
```
commit f48923e884611e6271a8da821a58aedd24d91cf7 (HEAD)
Author: Andy Wingo <wingo@igalia.com>
Date:   Wed Feb 17 17:20:28 2021 +0100
[WebAssembly][lld] --importTable flag only imports table if needed
Before, --importTable forced the creation of an indirect function table,
whether it was needed or not.  Now it only imports a table if needed.
Differential Revision: https://reviews.llvm.org/D96872
```
However, this does **not** fix the issue. The assert does not …
> Create a table if there is none in GenerateDynCalls::generateDynCallThunk (?)

- src/passes/RemoveUnusedModuleElements.cpp
- test/passes/remove-unused-module-elements_all-features.txt
There was an existing test for this, it turns out.
Also refactor away some annoying repeated code in that pass. `visitTry` is
the only actual change.
Noticed by the exceptions fuzzer https://github.com/emscripten-core/emscripten/pull/13485, e.g. on `wasm-opt -O1` on
```cpp
#include <stdio.h> // avoid iostream C++ code, just test libc++abi, not libc++
#include <stdint.h>
extern void refuel();
extern void checkRecursion();
extern bool getBoolean();
struct Class {
Class();
~Class();
};
void func_0() {
while (getBoolean()) {
}
}
int main() {
// func_0
puts("calling func_0");
refuel();
try {
func_0();
} catch(...) {
puts("main caught from func_0");
}
return 0;
}```
> [Wasm Exceptions] Scan catch events in RemoveUnusedModuleElements

- src/passes/RemoveUnusedNames.cpp
- test/passes/remove-unused-names_all-features.txt
- test/passes/remove-unused-names_all-features.wast
The `delegate` field of Try was not being scanned, so we could
remove a name that was used only by a delegate.
The bug was because `visitTry` overrides the generic visitor
`visitExpression`. So we need to call it manually. Sadly the code here
was pretty old (I probably wrote it back in 2015 or so) and it was
misleading, as it had unnecessary calls from the generic visitor
to `visitBlock, visitLoop`, which are not needed. This PR removes
them which is shorter and cleaner.
Also, we must handle the case of the delegate field being unset,
so check `name.is()`.
> [Wasm Exceptions] Fix RemoveUnusedNames on Try

- src/passes/RemoveUnusedNames.cpp
- test/passes/remove-unused-names_all-features.txt
- test/passes/remove-unused-names_all-features.wast
Without this, the assertion just below fires, as we should erase each
branch target after we reach it, end end up with nothing left.
After this fix it looks like fuzzing can't find anything new after ~1000
iterations (100x more than before).
> [Wasm Exceptions] Handle delegation to the caller in RemoveUnusedNames

- src/wasm/wasm-type.cpp
- test/example/type-builder.cpp
When types or heap types were used multiple times in a TypeBuilder instance, it
was possible for the canonicalization algorithm to canonicalize a parent type
before canonicalizing all of its component child types, leaking the temporary
types into globally interned types. This bug led to incorrect canonicalization
results and use-after free bugs.
The cause of the bug was that types were canonicalized in the reverse of the
order that they were visited in, but children were visited after the first
occurrence of their parents, not necessarily after the last occurrence of their
parents. One fix could have been to remove the logic that prevented types from
being visited multiple times so that children would always be visited after
their parents. That simple fix, however, would not scale …
> Fix TypeBuilder canonicalization

- src/passes/Print.cpp
- src/wasm-s-parser.h
- src/wasm/wasm-s-parser.cpp
- test/lit/forward-declared-types.wast
- test/spec/old_func.wast
- test/typed-function-references.wast
- test/typed-function-references.wast.from-wast
- test/typed-function-references.wast.fromBinary
- test/typed-function-references.wast.fromBinary.noDebugInfo
Traverses the module to find type definitions and uses a TypeBuilder to
construct the corresponding HeapTypes rather than constructing them directly.
This allows types to be used in the definitions of other types before they
themselves are defined, which is an important step toward supporting recursive
types. After this PR, no further text parsing changes will be necessary to
support recursive types.
Beyond allowing types to be used before their definitions, this PR also makes a
couple incidental changes to the parser's behavior. First, compound heaptypes
can now only be declared in `(type ...)` elements and cannot be declared inline
at their site of use. This reduces the flexibility of the parser, but is in line
with what the text format spec will probably look like eventually (see …
> Support type uses before definitions in text parser

- src/tools/wasm-shell.cpp
On Windows/VS the maps in this code caused a double-delete of a Literal.
Given that order of destruction is unspecified, I decided to make them locals, which fixed it.
Not sure if there is still a latent ordering bug, but not having these as globals seems an improvement regardless.
> Fix global destructor ordering problem

- src/cfg/cfg-traversal.h
- test/passes/coalesce-locals_all-features.txt
- test/passes/coalesce-locals_all-features.wast
This was an unfortunate case of the order of execution of call
arguments. `link(self->currBasicBlock, self->startBasicBlock())` would
run the call first, which sets `currBasicBlock`, so we'd end up with
the same value for both parameters.
Without this fix, the testcase would `drop` the result of the call,
as it thought it had no uses.
Also improve debug logging here a tiny bit.
Found by https://github.com/emscripten-core/emscripten/pull/13485
> [Wasm Exceptions] Fix cfg-traversal on linking the basic block after a call

- src/wasm-stack.h
- src/wasm/wasm-stack.cpp
- test/passes/generate-stack-ir_roundtrip_all-features.txt
- test/passes/generate-stack-ir_roundtrip_all-features.wast
We were missing a pop of catchIndexStack at a Delegate. It ends the scope,
so it should do that, like TryEnd does.
Found by https://github.com/emscripten-core/emscripten/pull/13485 on `-O2`.
> [Wasm Exceptions] Fix StackIR writing of nested delegates

- src/ir/ExpressionAnalyzer.cpp
- test/example/hash.cpp
Before this we would assert on hashing e.g. `(br $x)` by itself, without the
context so we recognized the name `$x`. Somehow that was not an issue
until delegate, we just happened to not hash such things. I believe I remember
that @aheejin noticed this issue before, but given we didn't have a testcase,
we deferred fixing it - now is the time, I guess, as with delegate it is easy to
get e.g. CodeFolding to hash a Try with a delegate.
Issue found by https://github.com/emscripten-core/emscripten/pull/13485
> Fix hashing of a use of a name without the context/target for it

- src/wasm-type.h
- src/wasm/wasm-s-parser.cpp
#3591 adds type and field names to the Module object, and used that
for the type but not the fields. This uses it for the fields as well, and removes
the "name" field from the Field objects itself, completing the refactoring.
After this, binary format support can be added as a proper replacement for
#3589
edit: a big part of this is just whitespace
> [Wasm GC] Move struct field names to their proper place

- src/wasm/wasm-binary.cpp
(not 100% NFC since it also fixes a bug by moving a line out of
a loop)
> Refactor name processing (escaping/deduplication) to a shared place. NFC

- src/wasm/wasm-type.cpp
- test/example/type-builder.cpp
Updates TypeBuilder to support recursive types. Recursive types are particularly
problematic because under the current scheme it is necessary to canonicalize the
uses of a type's immediate children before canonicalizing the type itself to
avoid leaking non-canonical, temporary types out of the TypeBuilder and into the
global type stores. In the case of recursive types, it is not possible to do
this because of their cyclic nature. In principle this could be overcome by
hashing recursive types based on their structure rather than their contents, but
that would be complicated. Instead, this PR takes the shortcut of not
canonicalizing self-referential HeapTypes at all, but rather moving them out of the
TypeBuilder and into the global type store without changing their addresses or
needing to …
> Support building recursive types

- src/wasm.h
The comment refers the refer to a nonexisting comment in Table.
This comment was added in 95d00d6 and refers to a field (`bool
exists`) that was removed in the meantime, along with the comment in
Table.
> Remove comment as context is nonexistent

- src/binaryen-c.h
The first occurrence of segment refers to memory.
> Fix typo in API header

- .gitignore
Cmake puts all its object files inside CMakeFiles so they
are already handled by the CMakeFiles entry.
Having `*.o` in this file means that `git status` and `git clean`
don't help to find stray `.o` files that one might have made
inadvertently in the tree.
I personally often create small source files and object files
at the top level when working on a project and I expect them
to be cleanup by `git clean`.
> Remove .o and .obj from gitignore

- src/passes/Print.cpp
- test/passes/dce_all-features.txt
We can just iterate on children using the standard order as in
delegates.h, as used by the binary format as well. The only
exceptions are control flow instructions which need some
special handling.
> Simplify printing code

- src/binaryen-c.cpp
- src/binaryen-c.h
- src/js/binaryen.js-post.js
- test/binaryen.js/expressions.js
Adds `BinaryenRefIsGetOp` and `BinaryenRefIsSetOp` to the C API, respectively `RefIs#getOp` and `RefIs#setOp` to the JS API. Plus tests, and updates related descriptions.
> Add RefIsGetOp/SetOp in C and JS API

- src/binaryen-c.cpp
- src/binaryen-c.h
- src/js/binaryen.js-post.js
- test/binaryen.js/kitchen-sink.js
- test/binaryen.js/kitchen-sink.js.txt
- test/example/c-api-kitchen-sink.c
- test/example/c-api-kitchen-sink.txt
Adds `BinaryenFeatureTypedFunctionReferences` to the C API and `Features.TypedFunctionReferences` to the JS API, plus tests.
> Add TypedFunctionReferences feature to C and JS API

- src/binaryen-c.cpp
- src/binaryen-c.h
- test/example/c-api-multiple-tables.c
- test/example/c-api-multiple-tables.txt
Uses `BinaryenIndex` instead of `int` to mirror parameter types in table construction, and adds setters for `name`, `initial` and `max`. Plus descriptions and tests.
> Slightly improve new table C APIs

- src/wasm/wasm-type.cpp
Previously we computed the fixed point of the parent-child relation to identify
self-referential HeapTypes in the TypeBuilder canonicalizer. That algorithm was
O(|V|^3) in the worst case and took over five seconds to find the
self-referential HeapTypes in an example program with just 1134 HeapTypes,
probably due to high allocation traffic from the std::unordered_map and
std::unordered_sets used to implement the parent-child graph's adjacency list.
This PR replaces that algorithm with Tarjan's strongly connected component
algorithm, which runs in O(|V|+|E|) and finds the self-referential HeapTypes in
the mentioned example program in under 30 ms. All strongly connected components
of more than one element in the HeapType parent-child graph correspond to sets
of mutually recursive HeapTypes …
> Use Tarjan's SCC alg. to find self-referential types

- src/ir/ExpressionAnalyzer.cpp
The assertion is not really needed. Wasm64 will need changes to support
more than `2^32` names, in theory, but (1) wasm64 is just memory64 atm,
and (2) we'd need to add a general option for `Index` to be larger than 32
bits in general, so there is nothing specific to the hashing code here.
> Remove unneeded static_assert on number of Names in hashing

- src/passes/Print.cpp
- src/wasm-type.h
- src/wasm/wasm-type.cpp
- test/example/type-builder.cpp
- test/example/type-builder.txt
Also fixes a few locations in Print.cpp where types were being printed directly
rather than going through the s-expression type printer and removes vestigial
wrapper types that were no longer used.
> Support printing recursive types

- src/ir/stack-utils.cpp
- src/ir/stack-utils.h
- src/wasm/wasm-validator.cpp
- test/example/stack-utils.cpp
As a readability improvement, use an enum with `Polymorphic` and `Fixed`
variants to represent the polymorphic behavior of StackSignatures rather than a
`bool uneachable`.
As suggested in https://github.com/WebAssembly/binaryen/pull/3543#discussion_r570421727.
> Use enum instead of bool for StackSignature kind

- src/wasm/wasm-type.cpp
- test/lit/recursive-types.wast
This PR makes the TypeBuilder move self-referential HeapTypes to global HeapType
store so that they are considered canonical. This means that when a HeapType is
constructed with an identical definition, it will be equivalent to the original
HeapType constructed by the TypeBuilder, but it does _not_ mean that
self-referential HeapTypes are deduplicated.
This fixes a bug in which two versions of each self-referential function
signature were emitted. Before this PR, the global HeapType store was not aware
of the original self-referential HeapTypes. When the function signatures were
used to construct HeapTypes during type collection, new HeapTypes were allocated
and emitted in addition to the original HeapTypes. Now the global HeapType store
returns the original HeapTypes, so the extra …
> Consider self-referential HeapTypes to be canonical

- src/wasm/wasm-s-parser.cpp
- test/exception-handling.wast
- test/exception-handling.wast.from-wast
- test/exception-handling.wast.fromBinary
- test/exception-handling.wast.fromBinary.noDebugInfo
Previously we assumed catch body's size should be at least 3: `catch`
keyword, event name, and body. But catch's body can be empty when the
event's type is none. This PR fixes the bug and allows empty catch
bodies to be parsed correctly.
Fixes #3629.
> Allow empty body within catch block

- src/parsing.h
- src/wasm/wasm-validator.cpp
- test/passes/inlining_all-features.txt
- test/passes/inlining_all-features.wast
The old code here just referred to Block and Loop. Refactor it to use the
generic helper code that also handles Try.
Also add validation of Try names in the validator.
The testcase here would have `$label` appear twice before this fix. After
the fix there is `$label0` for one of them.
> [Wasm Exceptions] Properly ensure unique try labels after an inlining

- src/parsing.h
- src/passes/Inlining.cpp
- test/passes/inlining_all-features.txt
- test/passes/inlining_all-features.wast
1. Ignore the fake delegate target in the unique name mapper. The mapper
is run after inlining, so this fixes inlining into a function that has a delegate 0.
2. Do not inline a function with delegate 0. We should support this eventually,
but for now I think this is good enough.
(Btw what are the proper semantics of an inlined delegate 0? Should it delegate
to a new try at the inlining site, and do a rethrow from there, something like
that?)
After this Inlining should be safe to run on exceptions code.
> [Wasm Exceptions] Fix/work around delegate 0 issues in Inlining pass

- src/binaryen-c.cpp
- src/binaryen-c.h
- src/js/binaryen.js-post.js
- test/binaryen.js/expressions.js
- test/binaryen.js/expressions.js.txt
- test/example/c-api-kitchen-sink.c
- test/example/c-api-kitchen-sink.txt
Adds C / JS bindings for the constants
* BinaryenRefAsNonNull / Operations.RefAsNonNull
* BinaryenRefAsFunc / Operations.RefAsFunc
* BinaryenRefAsData / Operations.RefAsData
* BinaryenRefAsI31 / Operations.RefAsI31
and the respective construction, inspection and modification APIs
* BinaryenRefAs / RefAs wrapper, ref.as_non_null, ref.as_func, ref.as_data, ref.as_i31
* BinaryenRefAsGetOp / RefAs#getOp
* BinaryenRefAsSetOp / RefAs#setOp
* BinaryenRefAsGetValue / RefAs#getValue
* BinaryenRefAsSetValue / RefAs#setValue
plus descriptions and preliminary (cannot represent non-nullable reference types yet) tests.
> Add C and JS API bindings for ref.as_*

- .github/workflows/build_release.yml
- .github/workflows/ci.yml
Also fix the underlying issue which was that `lit` was not
being correctly installed via pip3.
See #3459
> ci: Build alpine linux to match what the release builder does

- test/passes/code-pushing_all-features.txt
- test/passes/code-pushing_all-features.wast
`catch_all` should not have a pop.
> [Wasm Exceptions] Fix a handwritten exceptions test

- src/wasm-s-parser.h
- src/wasm/wasm-s-parser.cpp
- test/heap-types.wast
- test/heap-types.wast.from-wast
- test/heap-types.wast.fromBinary
- test/heap-types.wast.fromBinary.noDebugInfo
Names of structurally identical types end up "collapsed" together after the
types are canonicalized, but with this PR we can properly read content that
has structurally identical types with different names.
> [Wasm GC] Parse text field names even of types that end up canonicalized together

- scripts/fuzz_opt.py
The check for a valid wasm file must be different if the wasm has
a feature section or not, so just try both ways, with `--detect-features`
and `--all-features`. If the wasm is valid, at least one will work.
> Make the reduction script more robust, and document text reduction

- scripts/fuzz_opt.py
I'm not sure what this was added - @tlively maybe you know?
It seems unneeded as we call all the commands with all the feature
args on the commandline anyhow.
Also, this caused an actual problem on a particular fuzz testcase I
found. Rather than figure out the details there, it seems simpler to not
depend on the features section while fuzzing?
> Stop emitting features section in fuzzer

- src/ir/module-utils.h
- src/wasm/wasm-type.cpp
- test/lit/recursive-type-sort.wast
The comparison implemented by TypeComparator was not previously antisymmetric
because it held that both A < B and B < A when A and B were structurally
identical but nominally distinct recursive types. This meant that it did not
satisfy the conditions of C++'s "Compare" requirement, which meant that std::set
did not operate correctly, as discovered in #3648. The PR fixes the problem by
having making A < B be false (and vice versa), making type comparisons properly
antisymmetric.
As a drive by, also switches to using std::stable_sort in collectHeapTypes to
make the order of the type section completely deterministic accross platforms.
Fixes #3648.
> Fix TypeComparator to satisfy C++'s Compare requirement

- CMakeLists.txt
This option will avoid installing the static library and headers, for
distributions that want to be as small as possible, and don't need
to support development with libbinaryen (such as emsdk).
It still installs the dynamic library since that's needed by the
tools.
> Add a CMake option to install only the tools

- src/wasm-binary.h
- src/wasm-stack.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-stack.cpp
- test/atomics64.wast.fromBinary
- test/atomics64.wast.fromBinary.noDebugInfo
- test/heap-types.wast.fromBinary
- test/heap-types.wast.fromBinary.noDebugInfo
- test/passes/reorder-locals_print_roundtrip.txt
- test/passes/reorder-locals_print_roundtrip.wast
- test/reference-types.wast.fromBinary
- test/reference-types.wast.fromBinary.noDebugInfo
- test/typed-function-references.wast.fromBinary
- test/typed-function-references.wast.fromBinary.noDebugInfo
When writing a binary, we take the local indexes in the IR and turn
them into the format in the binary, which clumps them by type. When
writing the names section we should be aware of that ordering, but
we never were, as noticed in https://github.com/WebAssembly/binaryen/issues/3499
This fixes that by saving the mapping of locals when we are emitting
the name section, then using it when emitting the local names.
This also fixes the order of the types themselves as part of the
refactoring. We used to depend on the ordering of types to decide
which to emit first, but that isn't good for at least two reasons. First,
it hits https://github.com/WebAssembly/binaryen/issues/3648 - that order is not fully
defined for recursive types. Also, it's not good for code size - we've
ordered the locals in …
> Fix binary writing of local name indexes

- src/ir/cost.h
- test/passes/remove-unused-brs_all-features.txt
- test/passes/remove-unused-brs_all-features.wast
Trivial fix. Found by reducing a real-world codebase.
The test here is what actually crashed, a case of a pass that uses
cost analysis. With some extra work this could be a unit test perhaps
in C++. Would that be worth it?
> [Wasm GC] Fix cost.h on array.new_default

- third_party/llvm-project/DWARFEmitter.cpp
- third_party/llvm-project/dwarf2yaml.cpp
The address size was hard-coded to 4, it now gets this information from .debug_info.
This required changing the parsing order.
Also made failure to parse .debug_loc fail the program, as before this error was easy to ignore.
Note there is no test specific to the combination of dwarf + wasm64 in binaryen, as I am only just working on the tests in emscripten that uncovered this issue.
> Fixed .debug_loc parsing for wasm64 files

- src/wasm/wasm-binary.cpp
RTT types have type indexes, not heap types (there is no `(rtt funcref)`).
Noticed by @manoskouk - thanks!
Fixes https://github.com/WebAssembly/binaryen/issues/3656 after which we can parse
that testcase - but not validate it yet, there is another issue remaining with typing.
> [Wasm GC] Fix RTT type parsing

- src/passes/Print.cpp
Also limit it to reasonable amounts of recursion.
> [Wasm GC] Avoid extremely large outputs in TypeNamePrinter

- src/passes/OptimizeInstructions.cpp
Instead of a single big `optimize()` method we now use separate functions
per instruction. This gives us smaller functions and less nesting in some cases,
and avoids manually casting and checking etc.
The reason this was not done originally is that this pass does repeated
applications. That is, if `optimize()` changed something, it would run again
on the result, perhaps further optimizing it. It did not need to run on the
children, but just on the result itself, so it didn't just do another full walk,
and so the simplest way was to just do a loop on `optimize()`. To replace that,
this PR modifies `replaceCurrent()` which the methods now call to report
that the current node can be replaced. There is some code in there now that
keeps doing more processing while changes happen. It's not …
> Refactor OptimizeInstructions to use visit* methods. NFC

- src/wasm/wasm-stack.cpp
Works around https://github.com/WebAssembly/binaryen/issues/3682 With this, I can roundtrip
a large real-world testcase.
There are other cases of `std::map<Type,..>` in the codebase, but none on
a critical path, so this PR only changes that one place.
> [Wasm GC] Avoid std::map<Type,..> in mapLocals

- src/tools/fuzzing.h
Rather than use delegates.h, we have helpers for scope names.
> Simplify fuzzer fixup code for names

- src/wasm/wasm-validator.cpp
- test/passes/Oz_fuzz-exec_all-features.txt
- test/passes/Oz_fuzz-exec_all-features.wast
- test/spec/ref_cast.wast
- test/spec/struct.wast
Also add more spec tests, including one that verifies we validate
`rtt.sub` and on a global location as fixed by #3694
> [Wasm GC] Validate static subtyping in rtt.sub

- src/wasm/wasm-type.cpp
`isTemp` is used in new assertions that guard against leaking temporary types
and heap types into the global stores and `isSelfReferential` replaces and
external set of self-referential types. Both fields will additionally be used in
upcoming PRs improving type canonicalization.
> [NFC] Record isTemp and isSelfReferential on TypeInfos

- src/tools/fuzzing.h
- src/tools/wasm-emscripten-finalize.cpp
- src/wasm-binary.h
- src/wasm-io.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-io.cpp
After @sbc100 's work on `EM_ASM` and `EM_JS` they are now parsed from
the wasm using exports etc. and so we no longer need to parse function bodies.
As a result if we are not emitting a wasm from `wasm-emscripten-finalize` then all we are
doing is scanning global structures like imports and exports and emitting metadata
about them. And indeed we do not need to emit a wasm in some cases, specifically
when not optimizing and when using `WASM_BIGINT` (to avoid needing to
legalize).
We had considering skipping wasm-emscripten-finalize entirely in that situation,
and instead to parse the metadata from the wasm in python on the emscripten
side. However @sbc100 had the brilliant idea today to just skip function bodies.
That is very simple to do - no need to write another parser for wasm, and …
> Skip function bodies in wasm-emscripten-finalize when we don't need them

- src/wasm/wasm-debug.cpp
- third_party/llvm-project/dwarf2yaml.cpp
- third_party/llvm-project/include/llvm/ObjectYAML/DWARFYAML.h
A recent change in LLVM causes it to sometimes end up with a thing
with no parent. That is, a debug_line or a debug_loc that has no CU that
refers to it. This is perhaps LLVM DCEing CUs, or something else that
changed - not sure. But it seems like valid DWARF we should handle.
This PR handles that in our code. Two things broke here. First, locs must
be simply ignored when there is no CU. Second, lines are trickier as we
used to compute their position by scanning them, and that list contained
only ones with a CU. So we missed some and ended up with wrong offsets.
To make things simpler and more robust, just track the position of each
line table on itself.
Fixes https://github.com/WebAssembly/binaryen/issues/3697
> Ignore missing CUs in DWARF rewriting

- src/tools/wasm-emscripten-finalize.cpp
That PR assumed that wasm-emscripten-finalize does not need to scan
function bodies for metadata. But there is a case where it does, which is
that EM_ASMs with pthreads do still require scanning of the code. So that
approach is not valid.
We could maybe disable the optimization just on pthreads, but I think
major use cases need that. Also there is no simple way to disable it atm,
we'd need changes on both emscripten and binaryen. Also that PR can
no longer be reverted cleanly due to other changes. For all those reasons,
this just disables the optimization so that users of `tot` are no longer
broken, while we figure out how a valid way to optimize this use case.
> Revert the effect of #3689

- scripts/clang-format-diff.sh
- scripts/clang-tidy-diff.sh
- scripts/emcc-tests.sh
This means that if any command in a pipelines fails the whole
pipeline will also fail.
> Add `-o pipefail` to shell scripts

- src/wasm/wasm-type.cpp
It is a little "fun" to fake their uses because of the overloaded type.
cppreference says that this is the way to do it, and I've found no
other way than a C cast like this (std::function fails).
> Avoid warnings/errors on isTemp(*Type) being unused

- src/wasm/wasm-binary.cpp
- src/wasm/wasm-emscripten.cpp
This was triggered by my on-going wasm64 testing in emscripten
> Fixed reading 64-bit memories and output of globals

- scripts/clang-format-diff.sh
- scripts/clang-tidy-diff.sh
Also update clang-format-diff.sh to match recent changes to branch
name and CI system (these changes mirror those already made to
clang-tidy-diff.sh).
> Allow clang-format-diff/clang-tidy-diff to take branch as argument

- src/wasm/wasm-type.cpp
- test/example/type-builder.cpp
- test/example/type-builder.txt
- test/lit/recursive-types.wast
Use Hopcroft's DFA minimization algorithm to properly canonicalize and
deduplicate recursive types. Type canonicalization has two stages:
1. Structural canonicalization
- The top-level structure of HeapTypes is used to split the declared HeapTypes
into their initial partitions.
- Hopcroft's algorithm refines the partitions such that all pairs of
distinguishable types end up in different partitions.
- A fresh HeapTypeInfo is created for each final partition. Each new
HeapTypeInfo is linked to other new HeapTypeInfos to create a minimal type
definition graph that defines the same types as the original graph.
2. Global canonicalization
- Each new minimal HeapTypeInfo that does not have the same finite
structure as an existing globally canonical HeapTypeInfo is moved to the
global heap type …
> Equirecursive type canonicalization

- src/ir/literal-utils.h
- test/passes/vacuum_all-features.txt
- test/passes/vacuum_all-features.wast
We can't make a zero tuple if any field cannot be a zero.
> [Wasm GC] Fix canMakeZero on tuples

- src/passes/RemoveUnusedBrs.cpp
- test/passes/remove-unused-brs_all-features.txt
- test/passes/remove-unused-brs_all-features.wast
The type may prove the value is not null, and may also show it to be
of the type we are casting to. In that case, we can simplify things.
This kind of thing can happen after inlining for example.
>  [Wasm GC] Optimize br_on_*

- src/passes/Flatten.cpp
- test/passes/flatten_all-features.txt
- test/passes/flatten_all-features.wast
That pass adds lots of new locals, and we need to handle non-nullable ones.
> [Wasm GC] Handle non-nullable locals in Flatten pass

- src/passes/Print.cpp
- src/wasm.h
- src/wasm/wasm-validator.cpp
For example, on this invalid wat:
```wat
(module
(type $vec (struct (field i64)))
(func $test
(drop
(struct.new_with_rtt $vec (i32.const 1) (rtt.canon $vec))
)
)
)
```
We used to print:
```
[wasm-validator error in function test] struct.new operand must have proper type, on 
(struct.new_with_rtt ${i64}
(i32.const 1)
(rtt.canon ${i64})
)
```
We will now print:
```
[wasm-validator error in function test] struct.new operand must have proper type, on 
(struct.new_with_rtt $vec
(i32.const 1)
(rtt.canon $vec)
)
```
Note that `$vec` is used. In real-world examples the autogenerated structural name
can be huge, which this avoids.
> Validator: Pass the module along when printing errors, so type names are used

- src/wasm/wasm-type.cpp
This variable is only used when asserts are enabled, so it was causing
compilation errors on optimized builds with -Wunused-variable -Werror. This PR
fixes the build errors by hiding the variable and its uses behind ifdefs.
> Resolve unused variable `globalStore`

- src/wasm-type.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-s-parser.cpp
- src/wasm/wasm-type.cpp
- test/example/type-builder.cpp
- test/example/type-builder.txt
Makes TypeBuilders growable, adds a `getTempHeapType` method, allows the
`getTemp*Type` methods to take arbitrary temporary or canonical HeapTypes rather
than just an index, and allows BasicHeapTypes to be assigned to TypeBuilder
slots. All of these changes are necessary for the upcoming re-implementation of
equirecursive LUB calculation.
Also adds a new utility to TypeBuilder for using `operator[]` as an intuitive
and readable wrapper around the `getTempHeapType` and `setHeapType` methods.
> Refactor TypeBuilder

- src/wasm/wasm-validator.cpp
- test/spec/struct.wast
I almost fixed this recently, but forgot that a validation error is not an
early exit...
I wonder if maybe it should be. That would mean more usage of
exceptions in our codebase, and that we'd stop at the first validation
error in all cases, but it would be simpler...
> [Wasm GC] Properly validate struct.new number of operands

- src/tools/fuzzing.h
- src/wasm/wasm-type.cpp
- test/spec/tuples.wast
This looks like a pre-existing issue to https://github.com/WebAssembly/binaryen/pull/3731, but
the testcase only fails on that PR for a reason I did not investigate in
depth, so it should land first.
Also fix the check for nondefaultability in the fuzzer.
> Fix nondefaultability of Tuple types

- src/passes/RoundTrip.cpp
- src/tools/wasm-reduce.cpp
Without this, crashes from things like #3736 simply get reported as
"a parse exception was thrown" with no detail.
> Print parse errors in reducer and roundtrip

- src/tools/fuzzing.h
Without this the fuzzer calls `getSignature` on `HeapType::func` which asserts.
> Fix fuzzer on creating a function with a heaptype of just 'func'

- src/tools/wasm-reduce.cpp
There is a `makeZeros` right below that, which will assert on a nondefaultable
type.
> Fix reduction of nondefaultable tuples

- src/passes/DeadArgumentElimination.cpp
- src/passes/FuncCastEmulation.cpp
- src/passes/Inlining.cpp
- src/passes/opt-utils.h
- src/wasm-traversal.h
- src/wasm/wasm-validator.cpp
- test/example/c-api-kitchen-sink.c
- test/passes/dae_all-features.txt
- test/passes/dae_all-features.wast
- test/passes/duplicate-function-elimination_all-features.txt
- test/passes/duplicate-function-elimination_all-features.wast
Several old passes like DeadArgumentElimination and DuplicateFunctionElimination
need to look at all `ref.func`s, and they scanned functions for that, but that is not
enough as such an instruction might appear in a global initializer. To fix this, add a
`walkModuleCode` method.
`walkModuleCode` is useful when doing the pattern of creating a function-parallel
pass to scan functions quickly, but we also want to do the same scanning of code
at the module level. This allows doing so in a single line.
(It is also possible to just do `walk()` on the entire module, which will find all code,
but that is not function-parallel. Perhaps we should have a `walkParallel()` option
to simplify this further in a followup, and that would call `walkModuleCode` afterwards
etc.)
Also add some missing …
> Scan module-level code in necessary places

- src/passes/DeadArgumentElimination.cpp
- test/passes/dae_all-features.txt
- test/passes/dae_all-features.wast
In this case, there is a natural place to fix things up right after
removing a parameter (which is where a local gets added). Doing it
there avoids doing work on all functions unnecessarily.
Note that we could do something even simpler here than calling
the generic code: the parameter was not used, so the new local
is not used, and we could just change the type of the local or not
add it at all. Those would be slightly more code though, and add
complexity to the parameter removal method itself.
> Fix DeadArgumentElimination pass on non-nullable locals

- src/tools/execution-results.h
- test/passes/fuzz-exec_all-features.txt
- test/passes/simplify-globals_all-features_fuzz-exec.txt
* Log out an i64 as two i32s. That keeps the output consistent regardless of
whether we legalize.
* Do not print a reference result. The printed value cannot be compared, as
`funcref(10)` (where 10 is the index of the function) is not guaranteed to be
the same after opts.
* Trap when trying to call an export with a nondefaultable type (instead of
asserting when trying to create zeros for it).
> Fuzzing: Minor execution-results.h fixes

- src/passes/CMakeLists.txt
- src/passes/SetGlobals.cpp
- src/passes/pass.cpp
- src/passes/passes.h
- test/passes/set-globals.passes
- test/passes/set-globals.txt
- test/passes/set-globals.wast
This allows changing a global's value on the commandline in an easy way.
In some toolchains this is useful as the build can contain a global that
indicates something like a logging level, which this can customize.
> SetGlobals pass

- src/wasm/wasm-s-parser.cpp
- src/wasm/wasm.cpp
- test/lit/parse-bad-tuple-extract-index.wast
Previously an out-of-bounds index would result in an out-of-bounds read during
finalization of the tuple.extract expression.
Fixes #3703.
> Catch bad tuple.extract index in parser

- scripts/fuzz_opt.py
RTTs are not defaultable, and we cannot spill them to locals.
> Disallow flatten + GC in the fuzzer due to RTTs

- src/wasm/wasm-type.cpp
- test/example/type-builder.cpp
- test/example/type-builder.txt
- test/lit/passes/roundtrip-gc-types.wast
When canonical heap types were already present in the global store, for example
during the --roundtrip pass, type canonicalization was not working correctly.
The issue was that the GlobalCanonicalizer was replacing temporary HeapTypes
with their canonical equivalents one type at a time, but the act of replacing a
temporary HeapType use with a canonical HeapType use could change the shape of
later HeapTypes, preventing them from being correctly matched with their
canonical counterparts. This PR fixes that problem by computing all the
temporary-to-canonical heap type replacements before executing them.
To avoid a similar problem when canonicalizing Types, one solution would have
been to pre-calculate the replacements before executing them just like with the
HeapTypes, but that would have …
> Fix type canonicalization bugs

- src/tools/wasm-reduce.cpp
This avoids an annoying case where in each iteration we try to remove
every function one by one and keep failing. Instead, we'll skip large
numbers of them when the factor is large at least.
Also shorten some unnecessary logging.
> Reducer: skip more functions when failing to remove them

- src/tools/js-wrapper.h
VMs will not convert a 0 or `undefined` from JS into a wasm null reference - it must be `null`.
> Wasm2JS fuzzing: Emit null for reference type params instead of 0

- scripts/fuzz_opt.py
We give `br_if` a too specific type: https://github.com/WebAssembly/binaryen/issues/3767
This is only noticeable with GC, and in rare cases where the type of `br_if`
is actually used - which realistically it never is, so really just fuzzer testcases.
> Fuzzer: Ignore our current bug with the type of br_if

- scripts/fuzz_opt.py
The fuzzer doesn't generate much GC code yet, but it does fuzz things in
the test suite and adds fuzz to them. This PR allows GC when using initial
content, and also in CompareVMs, both of which have been fuzzed for
days locally for me with no issues.
> [Wasm GC] Enable more GC fuzzing

- src/binaryen-c.cpp
- src/ir/module-splitting.cpp
- src/ir/table-utils.h
- src/tools/fuzzing.h
- src/wasm-builder.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-s-parser.cpp
- src/wasm/wasm-validator.cpp
- test/binaryen.js/expressions.js
The builder can receive a HeapType so that callers don't need to set non-nullability
themselves.
Not NFC as some of the callers were in fact still making it nullable.
> RefFunc: Validate that the type is non-nullable, and avoid possible bugs in the builder

- src/wasm/wasm-emscripten.cpp
I'm not sure what `stack$init` is but I don't think its been
used for many years.
> wasm-emscripten: Remove unused EM_ASM_PREFIX and STACK_INIT

- scripts/fuzz_opt.py
- src/shell-interface.h
- src/tools/execution-results.h
- src/tools/wasm-ctor-eval.cpp
- src/wasm-interpreter.h
- test/passes/Oz_fuzz-exec_all-features.txt
- test/passes/Oz_fuzz-exec_all-features.wast
Host limitations are arbitrary and can be modified by optimizations, so
ignore them. For example, if the optimizer removes allocations then a
host limit on an allocation error may vanish. Or, an optimization that
removes recursion and replaces it with a loop may avoid a host limit
on call depth (that is not done currently, but might some day).
This removes a class of annoying false positives in the fuzzer.
> Fuzzer: Distinguish traps from host limitations

- src/ir/type-updating.cpp
- src/ir/type-updating.h
- src/passes/DeadArgumentElimination.cpp
- src/passes/Flatten.cpp
- src/passes/Inlining.cpp
- src/passes/SSAify.cpp
- src/wasm/wasm-binary.cpp
- test/passes/inlining_all-features.txt
- test/passes/inlining_all-features.wast
Inlined parameters become locals, and rtts cannot be handled as locals, unlike
non-nullable values which we can at least fix up. So do not inline functions with
rtt params.
> [Wasm GC] Do not inline a function with an RTT parameter

- src/mixed_arena.h
To reduce allocator contention, MixedArena transparently forwards allocations to a
thread-local arena by traversing a linked list of arenas, looking for the one
corresponding to the current thread. If the search reaches the end of the linked
list, it allocates a new arena for the current thread and atomically appends it
to the end of the list using a compare-and-swap operation.
The problem was that the previous code used `compare_exchange_weak`, which is
allowed to spuriously fail, i.e. it is allowed to behave as though the original
value is not the same as the expected value, even when it is. In this case, that
means that it might fail to append the new allocation to the list even if the
`next` pointer is still null, which results in a subsequent null pointer
dereference. The fix is to …
> Fix lock-free MixedArena allocation

- src/shared-constants.h
- src/tools/wasm-emscripten-finalize.cpp
- src/wasm/wasm.cpp
- test/lld/em_asm_shared.wat.out
- test/lld/shared.wat.out
- test/lld/shared_add_to_table.wasm.out
- test/lld/shared_longjmp.wat.out
See https://github.com/emscripten-core/emscripten/issues/13893
> Remove renaming of __wasm_call_ctors

- scripts/fuzz_opt.py
There is a conflict between multivalue and GC, see the details in the
comment. There isn't a good way to get the fuzzer to avoid the combination
of them, and GC is more urgent, so disable multivalue in that area for now.
(This does not disable all multivalue fuzzing - the fuzzer can still emit stuff.
This just disables initial content from test suite having multivalue, which
is enough for now, until the fuzzer can emit more GC things, and then we'll
need to do more.)
> Fuzzer: Do not fuzz multivalue testcases in initial contents

- scripts/fuzz_opt.py
- src/passes/OptimizeInstructions.cpp
- test/lit/passes/optimize-instructions.wast
- test/passes/asyncify_mod-asyncify-never-unwind_O.txt
- test/passes/asyncify_optimize-level=1.txt
```
(select
(i32.eqz (X))
(i32.const 0|1)
(Y)
)
=>
(i32.eqz
(select
(X)
(i32.const 1|0)
(Y)
)
)
```
This is beneficial as the eqz may be folded into something on the outside. I
see this pattern in real-world code, both a GC benchmark (which is why I
noticed it) and it shrinks code size by tiny amounts on the emscripten
benchmark suite as well.
> Optimize if/select with one arm an EqZ and another a 0 or a 1

- src/wasm/wasm.cpp
It's easy to make a mistake like this because the spec varies on whether
a basic type is nullable or not (funcref is nullable, dataref and i31ref are not)...
It's not easy to test this - perhaps a contrived test could depend on it in
an optimization, but I'm not sure if it's worth it.
> [Wasm GC] Fix the type of ref.as_func, which should be non-nullable

- scripts/fuzz_opt.py
- src/passes/RemoveUnusedBrs.cpp
- test/lit/passes/remove-unused-brs.wast
- test/passes/remove-unused-brs_enable-multivalue.txt
- test/passes/remove-unused-brs_enable-multivalue.wast
The existing restructuring code could turn a block+br_if into an if in
simple cases, but it had some TODOs that I noticed were helpful on
GC benchmarks.
One limitation was that we need to reorder the condition and the value,
```wat
(block
(br_if
(value)
(condition)
)
(...)
)
=>
(if
(condition)
(value)
(...)
)
```
The old code checked for side effects in the condition. But it is ok for it
to have side effects if they can be reordered with the value (for example,
if the value is a constant then it definitely does not care about side effects
in the condition).
The other missing TODO is to use a select when we can't use an if:
```wat
(block
(br_if
(value)
(condition)
)
(...)
)
=>
(select
(value)
(...)
(condition)
)
```
In this case we do not reorder the condition and the value, but we do …
> Implement missing if restructuring

- src/ir/module-splitting.cpp
- src/ir/module-splitting.h
- src/wasm-builder.h
- test/example/module-splitting.cpp
- test/example/module-splitting.txt
- Support functions appearing more than once in the table. It turns out we
were assuming and asserting that functions would appear at most once, but we
weren't making use of that assumption in any way.
- Make TableSlotManager::getSlot take a function Name rather than a RefFunc
expression to avoid allocating and leaking unnecessary expressions.
- Add and use a Builder interface for building TableElementSegments to make
them more similar to other module-level items.
cc @martianboy, comments welcome!
Possibly fixes https://github.com/emscripten-core/emscripten/issues/13928, but I'll check to make sure tomorrow.
> Minor wasm-split improvements

- check.py
- scripts/test/shared.py
- scripts/test/support.py
- src/tools/wasm-shell.cpp
- src/wasm-interpreter.h
- test/spec/imports.wast
#3792 added support for module linking and `(register` command to
`wasm-shell`, but forgot about three problems:
1. Splitting spec tests prevents linking test modules together.
2. Registered modules may still be used in assertions or an `invoke`
3. Modules may re-export imported objects
This PR appends transformed modules after binary checks to a `spec.wast`
file, plus assertion tests and register commands. Then runs `wasm-shell`
on the whole file. It also keeps both the module name and its registered
name available in `wasm-shell` for use in shell commands and linked
modules. Furthermore, it correctly finds the module where an object is
defined even if it is imported and re-exported several times.
The updated version of `imports.wast` spec test is enabled to verify the
fixes.
> Run spec test all at once after binary transform

- src/tools/wasm-metadce.cpp
This prevents the DCE of used-via-address-only symbols in emscripten's `MAIN_MODULE=2`
use case which we are starting to use and recommend a lot more.
Part of the fix for https://github.com/emscripten-core/emscripten/issues/13786
> wasm-metadce: Keep symbols alive if there is any reference to corresponding GOT.mem or GOT.func import

- scripts/fuzz_opt.py
- src/ir/effects.h
- src/passes/OptimizeInstructions.cpp
- test/lit/passes/optimize-instructions-gc.wast
- test/lit/passes/optimize-instructions.wast
* Effects are fine in the moved code, if we are doing so on an `if`
(which runs just one arm anyhow).
* Allow `unreachable`, which lets us hoist `return`s for example.
* Allow `none,` which lets us hoist `drop` and `call` for example. For
this we also need to be careful with subtyping, as at least `drop`
is polymorphic, so the child types may not have an LUB (see
example in code).
Adds a small ShallowEffectAnalyzer child of EffectAnalyzer that
calls `visit` to just do a shallow analysis (instead of `walk` which
walks the children).
> Generalize moving of identical code from if/select arms

- src/passes/DeadArgumentElimination.cpp
- test/lit/passes/dae-gc.wast
We could more carefully see when a local is not needed there, but atm
we always add one, and that doesn't work for something nondefaultable.
> [Wasm GC] Skip DeadArgumentElimination of an RTT parameter

- .github/workflows/build_release.yml
CMake has a `sha256sum` subcommand that can be used to calculate checksums portably. Use it in the release workflow to create checksums on Windows.
For consistency, use it on macOS and Linux too.
> Create a shasum file for the Windows tarball

- src/passes/OptimizeInstructions.cpp
- test/lit/passes/optimize-instructions.wast
We tried to ignore unreachable code, but only checked the type of
the entire node. But an arm might be unreachable, and after moving
code around that requires more work to update the type. But such
cases are best left to DCE anyhow, so just check for any unreachability
and stop there.
(found by fuzzing)
> OptimizeInstructions: Fix eqz hoisting of if with unreachable arm

- src/wasm-type.h
Fixes #3838 and current breakage on CI here.
IIUC the warning is that we define a copy assignment operator, but
did not define a copy constructor. Clang wants both to exist now. However,
we delete the copy assignment one, so perhaps we should find a way to
avoid a copy on construction too? That happens here:
```cpp
../src/wasm/wasm-type.cpp:60:51: note: in implicit copy constructor for 'wasm::Tuple' first required here
TypeInfo(const Tuple& tuple) : kind(TupleKind), tuple(tuple) {}
^
```
But I don't see an easy way to remove the copy there, so this PR
defines the copy constructor as clang wants.
> Fix a new clang warning on implicit Tuple construction

- src/passes/OptimizeInstructions.cpp
- test/lit/passes/optimize-instructions.wast
For example,
```wat
(if (result i32)
(local.get $x)
(return
(local.get $y)
)
(return
(local.get $z)
)
)
```
If we move the returns outside we'd become unreachable, but we should
not make such type changes in this pass (they are handled by DCE and
Vacuum).
(found by the fuzzer)
> OptimizeInstructions: Do not change unreachability in if/select changes

- src/cfg/cfg-traversal.h
This will be used (and tested) in dead store elimination.
> Save the exit block, if any, in CFGTraversal. NFC

- src/support/unique_deferring_queue.h
- test/example/cpp-unit.cpp
Add `clear()`.
Add `UniqueNonrepeatingDeferredQueue` which also has the property
that it never repeats values in the output.
Also add unit tests.
This will be used in dead store elimination.
> UniqueDeferredQueue improvements

- src/wasm/wasm-type.cpp
This is similar to the limit in `TypeNamePrinter` in `Print.cpp`. This limit
affects the printed type when debugging with `std::cout << type` etc.,
which just prints the structure and not the name.
This made debugging a recent wasm GC testcase much easier.
> [Wasm GC] Add a print limit in TypePrinter

- auto_update_tests.py
- src/ir/LocalGraph.cpp
- src/ir/local-graph.h
- test/example/local-graph.cpp
- test/example/local-graph.txt
This compares two `local.get`s and checks whether we are sure they are
equivalent, that is, they contain the same value.
This does not solve the general problem, but uses the existing info to get
a positive answer for the common case where two gets only receive values
by a single set, like
```wat
(local.set $x ..)
(a use.. (local.get $x))
(another use.. (local.get $x))
```
If they only receive values from the same single set, then we know it must
dominate them. The only risk is that the set is "in between" the gets, that is,
that the set occurs after one get and before the other. That can happen in
a loop in theory,
```wat
(loop $loop
(use (local.get $x))
(local.set $x ..some new value each iteration..)
(use (local.get $x))
(br_if $loop ..)
)
```
Both of those gets receive a value from …
> Add LocalGraph::equivalent

- src/ir/module-utils.h
- src/wasm-type.h
- src/wasm/wasm-type.cpp
Add new public `getHeapTypeChildren` methods to Type and HeapType, implemented
in using the standard machinery from #3844, and use them to simplify
`ModuleUtils::collectHeapTypes`.
Now that the type traversal code in wasm-type.cpp is not just used in
canonicalization, move it to a more appropriate place in the file. Also, since
the only users of `HeapTypePathWalker` were using it to visit top-level children
only, replace that with a more specialized `HeapTypeChildWalker` to reduce code
duplication.
> Use standard type traversal in module-utils.h

- src/wasm/wasm-type.cpp
Fix two potential sources of data races identified with the help of thread
sanitizer.
First, keep a lock on the global HeapType store as long as it can reach
temporary types to ensure that no other threads observe the temporary types, for
example if another thread concurrently constructs a new HeapType with the same
shape as one being canonicalized here. This cannot happen with Types because
they are hashed in the global store by pointer identity, which has not yet
escaped the builder, rather than shape.
Second, in the shape canonicalizer, do not replace children of the new, minimal
HeapTypeInfos if they are already canonical. Even though these writes are always
no-ops, they still race because they are visible to other threads via canonical
Types.
Fix two sources of potential data races. …
> Fix data races in type canonicalization

- src/ir/LocalGraph.cpp
- src/ir/local-graph.h
- src/passes/MergeLocals.cpp
- src/passes/OptimizeAddedConstants.cpp
- src/passes/SSAify.cpp
- src/passes/StackIR.cpp
Some passes need `setInfluences` but not `getInfluences`, but were
computing them nonetheless.
(To verify correctness, can see that there is no reference to
`getInfluences` in the modified passes.)
This makes e.g. MergeLocals 12% faster. It will also help use LocalGraph
in new passes with less worries about speed.
> Allow only computing necessary influences in LocalGraph. NFC

- src/ir/properties.h
A new `getImmediateFallthrough` is called in the loop.
Aside from this being more efficient than recursion,  the new method will
be used in escape analysis.
> Refactor getFallthrough() to use a loop instead of recursion. NFC

- src/ir/branch-utils.h
Add `operateOnScopeNameUsesAndSentValues` which is like the
existing utilities, but provides the child expression that is sent as a
value on the branch.
Also provide a `BranchTargets` utility that maps target names to the
control flow structure for them.
Both will be used and tested in escape analysis.
> BranchUtils additions

- scripts/fuzz_opt.py
(can ignore whitespace to remove most of the diff)
We only ignored known issues if the process failed. However, some things
do not bring the process down, but are still necessary to ignore, which this
fixes.
Another approach might be to make all the things we need to ignore fail
the entire process. However, that could be annoying for other debugging:
we don't want a host limit on say hitting a VM limit on recursion to bring
down the entire process, as those limits manifest as traps, and we can
still run after them (and do need to test that). The specific host limit that
made me fix this was the trap on OOM when trying to allocate an array
of size 4GB.
> Fuzzer: Ignore things we should ignore even if the process succeeded

- src/wasm-interpreter.h
- test/passes/Oz_fuzz-exec_all-features.txt
- test/passes/Oz_fuzz-exec_all-features.wast
We truncated and extended packed values in get and set, but
not during initialization.
> [Wasm GC] Fix Array initialization of a packed value

- src/wasm-interpreter.h
- test/passes/Oz_fuzz-exec_all-features.txt
- test/passes/Oz_fuzz-exec_all-features.wast
The logic there would construct the cast value separately for functions and data
(as we must), and then in an attempt to share code, would then check if the
cast succeed or not (and if not, do nothing with the cast value).
But this was wrong, as in some weird casts (like a struct to a function) we
cannot construct a valid cast value, and we error there. Instead, check if the
cast works first, once we know enough to do so, and only then construct the
cast value if so.
> [Wasm GC] Fix casting code in interpreter

- src/passes/CoalesceLocals.cpp
- src/passes/Precompute.cpp
- test/lit/passes/precompute-gc.wast
Precompute not only computes values, but looks at the fallthrough,
```wat
(local.set 0
(block
..stuff we can ignore..
;; the fallthrough we care about - if a value is set to local 0, it is this
(i32.const 10)
)
)
```
Normally that is fine, but the fuzzer found a case where it is not: RefCast may
return a different type than the fallthrough, even an incompatible type if we
try to do something bad like cast a function to a struct. As we may then
propagate the value to a place that expects the proper type, this can cause an
error.
To fix this, check if the precomputed value is a proper subtype. If it is not,
then do not look through into the fallthrough, but compute the entire thing.
(In the case of a bad RefCast of a func to a struct, it would then indicate a
trap happens, and we would not …
> [Wasm GC] Fix precomputing of incompatible fallthrough values

- src/passes/RemoveUnusedModuleElements.cpp
- test/passes/remove-unused-module-elements_all-features.txt
- test/passes/remove-unused-module-elements_all-features.wast
Without this fix we can segfault, as it has no body.
Fixes #3879
> RemoveUnusedModuleElements: The start function may be imported

- src/pretty_printing.h
Affects `printMajor` and `printMedium`. There is no usage of this optional
argument in the source code.
> Remove unused argument `major`

- src/cfg/Relooper.h
- src/support/insert_ordered.h
Move the `InsertOrderedSet` and `InsertOrderedMap` implementations out of
Relooper.h and into a new insert_ordered.h so they can be used more widely. Only
changes the implementation code to use unordered_maps.
> [NFC] Move InsertOrdered{Set,Map} into a new header

- src/pass.h
- src/passes/pass.cpp
- src/tools/wasm-opt.cpp
- test/unit/test_dwarf.py
If we run a pass that removes DWARF followed by one that could destroy it, then
there is no possible problem - there is nothing left to destroy. We can run the later
pass with no issues (and no warnings).
Fixes https://github.com/emscripten-core/emscripten/issues/14161
> Do not attempt to preserve DWARF if a previous pass removes it

- src/passes/Print.cpp
- test/heap-types.wast
- test/heap-types.wast.from-wast
- test/heap-types.wast.fromBinary
- test/heap-types.wast.fromBinary.noDebugInfo
Similar to struct operations, if the reference is unreachable then we do
not know the heap type, and cannot print the full expression.
> [Wasm GC] Fix printing of unreachable Array operations

- src/passes/Heap2Local.cpp
- test/lit/passes/heap2local.wast
Previously we would try to stop using the allocation as much as possible,
for example not writing it to locals any more, and leaving it to other passes
to actually remove it (and remove gets of those locals etc.). This seemed
simpler and more modular, but does not actually work in some cases as
the fuzzer has found. Specifically, if we stop writing our allocation to
locals, then if we do a `(ref.as_non_null (local.get ..))` of that, then we
will trap on the null present in the local.
Instead, this changes our rewriting to do slightly more work, but it is
simpler in the end. We replace the allocation with a null, and replace
all the places that use it accordingly, for example, updating types to be
nullable, and removing RefAsNonNulls, etc. This literally gets rid of the
allocation and all …
> [Wasm GC] Heap2Local: Replace the allocation with null

- src/tools/wasm-reduce.cpp
When things go well, the reducer shrinks the factor by 50% or more, but
when things are slow it kept the factor unchanged. That is annoying in
some cases where you really have no benefit from reduction until the
factor gets small. So this at least reduces it by 10% in each iteration.
On the large wasm GC testcase I recently reduced this helped a lot. I
don't have a guarantee it will help elsewhere, though... but seems low risk.
> wasm-reduce: Always decrease the factor

- src/tools/wasm-split.cpp
- test/lit/wasm-split/invalid-options.wast
- test/lit/wasm-split/symbolmap.wast
The new option emits a symbol map file for each of the split modules. The file
names are created by appending ".symbolmap" to each of the Wasm output file
names.
> [wasm-split] Add a --symbolmap option

- src/wasm/wasm-s-parser.cpp
We must do that before assuming the type is a heap type in getStructIndex,
or we'd hit an assert there.
> [Wasm GC] Validate struct.get/set heap types early

- src/passes/PrintFunctionMap.cpp
- test/lit/wasm-split/symbolmap.wast
Imported functions come first when modules are emitted, so to ensure the
function indices are correct, they need to come first in the symbol maps. We
never noticed this bug before because imported functions are always the first
functions when a module is parsed, so the bug never mattered in practice.
However, wasm-split adds new imported functions after parsing and these were
causing the symbol map indices to be incorrect.
> Emit imported functions first in symbol maps

- src/cfg/cfg-traversal.h
- src/wasm-traversal.h
- test/passes/rse_all-features.txt
- test/passes/rse_all-features.wast
[`Walker::TaskFunc`](https://github.com/WebAssembly/binaryen/blob/35f9da76d53401ba4de054f4db631ce4177b32f1/src/wasm-traversal.h#L285) has changed from a function pointer to
`std::function` in #3494, mainly to make the EH support for `CFGWalker`
easier. We didn't notice much performance difference then, but it was
recently reported that it creased binaryen.js code size and performance.
This changes `Walker::TaskFunc` back to a function pointer and does a
little more work to manage catch index in `CFGWalker` side.
Hopefully fixes #3857.
cc @MaxGraey
> [EH] Change Walker::TaskFunc back to function pointer

- src/support/path.cpp
- src/tools/wasm-split.cpp
- src/wasm-binary.h
- src/wasm-io.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-io.cpp
- test/lit/wasm-split/module-names.wast
Even when other names are stripped, it can be useful for wasm-split to preserve
the module name so that the split modules can be differentiated in stack traces.
Adding this option to wasm-split requires adding similar options to ModuleWriter
and WasmBinaryWriter.
> [wasm-split] Add an option to emit only the module names

- src/cfg/cfg-traversal.h
- test/lit/passes/coalesce-locals-gc.wast
Without adding logic there, it simply ignored the branch, which could
lead to bad optimizations (thinking code is unreachable when it was).
There isn't a trivial way to add a static error to force us to add new
classes to CFGWalker. But this PR generalizes the code there to
handle all branches and all unreachable instructions in a generic
way. The only thing we'll need to remember to do in the future is to
add control flow structures. (And normally the fuzzer should quickly
find such bugs, but we don't have full fuzzing enabled for GC yet.)
Fixes #3907
> [Wasm GC] Implement CFGWalker support for BrOn*

- src/ir/CMakeLists.txt
- src/ir/names.cpp
- src/ir/names.h
- src/passes/MinifyImportsAndExports.cpp
Simplifies the public API to not unnecessarily take an index and simplifies the
implementation to use a single integer as state rather than a vector of indices.
> [NFC] Factor out and simplify minified name generation

- src/tools/wasm-split.cpp
- test/lit/lit.cfg.py
- test/lit/wasm-split/help.test
- test/lit/wasm-split/invalid-options.wast
In anticipation of adding a third wasm-split mode, merge-profiles, in addition
to the existing split and instrument modes, refactor wasm-split's option
validation to let the valid modes be declared for each option. This approach is
more scalable and robust than the ad-hoc validation we had previously.
> [wasm-split] Make option validation declarative

- src/tools/wasm-split.cpp
- test/lit/wasm-split/help.test
- test/lit/wasm-split/invalid-options.wast
- test/lit/wasm-split/merge-profiles.wast
Given a list of profiles for the same module, --merge-profiles produces a single
combined profile the contains the minimum timestamp among the original profiles
for each function. When verbose output is enabled, also emit a message for each
profile that could individually be removed without affecting the set of
functions in the combined profile, as suggested in #3912.
Marking this draft until #3916, which this includes, is merged. At that point I will
rebase this PR and mark it non-draft. Until then, just look at the diff for commits
after the first one.
>  [wasm-split] Add a merge-profiles mode

- check.py
Rename the test suite from 'gcc' to 'example' to match the name in
auto_update_tests.py. Also retrieve the tests to run using `shared.get_tests`,
which properly applies the --filter argument, again to match
auto_update_tests.py.
> Fix 'example' tests in check.py

- scripts/fuzz_opt.py
The support code there emits "`low high`" as the result, for example, `25 0` would
be `25` (as the high bits are all 0). This is different than how numbers are reported
in other things we fuzz, so this caused an error.
Fixes #3915
> Properly handle comparisons of 64-bit ints in wasm2c in the fuzzer.

- src/wasm-type.h
- src/wasm/wasm-type.cpp
- test/example/type-builder-nominal.cpp
- test/example/type-builder-nominal.txt
In nominal mode, HeapType constructors besides the Signature constructor always
produce fresh types distinct from any previously created types. The HeapType
constructor that takes a Signature maintains its previous behavior of
constructing a canonical representative of the given signature because it is
used frequently throughout the code base and never in a situation that would
benefit from creating a fresh type. It is left as future work to clean up this
discrepancy between the Signature HeapType constructor and other HeapType
constructors.
TypeBuilder skips shape canonicalization in nominal mode and always creates a
fresh type for each of its entries. It is left as future work to simplify the
global canonicalization step in nominal mode by disallowing the construction of
basic …
> Initial nominal typing support

- src/wasm/wasm-validator.cpp
- test/spec/br_on_null.wast
The `noteBreak` call was in the wrong place, causing us to not note breaks
from BrOnNull for example, which could make validation miss errors.
Noticed in #3926
> [Wasm GC] Properly validate BrOn*

- src/wasm-binary.h
- src/wasm/wasm-binary.cpp
When parsing func.ref instructions, we need to get the HeapType corresponding to
the referenced function's signature. Since constructing HeapTypes from
Signatures can be expensive under equirecursive typing, keep track of the
original function signature HeapTypes directly during parsing rather than
storing them as Signatures.
@kripken, what do you think about this as an alternative to #3925? IMO it would be good to avoid adding more state to binary parsing if possible. The possible downside of this approach is that it will not deduplicate signature HeapTypes in a nominal system. If that's something we want to do, we will have to either go with the caching approach or possibly perform the deduplication in `ModuleUtils::collectHeapTypes`. Without knowing more about the semantics of a …
> Store signatures as HeapTypes when parsing binaries

- src/wasm/wasm-binary.cpp
- src/wasm/wasm-s-parser.cpp
- src/wasm/wasm-validator.cpp
- test/exception-handling.wast
- test/exception-handling.wast.from-wast
- test/exception-handling.wast.fromBinary
- test/exception-handling.wast.fromBinary.noDebugInfo
This removes the restriction that `try` should have at least one
`catch`/`catch_all`/`delegate`. See WebAssembly/exception-handling#157.
> [EH] Allow catch/delegate-less trys

- src/wasm-type.h
- src/wasm/wasm-type.cpp
- test/example/type-builder-nominal.cpp
- test/example/type-builder-nominal.txt
Add methods to the TypeBuilder interface to declare subtyping relationships
between the built types. These relationships are validated and recorded globally
as part of type building. If the relationships are not valid, a fatal error is
produced. In the future, it would be better to report the error to the
TypeBuilder client code, but this behavior is sufficient for now. Also updates
SubTyper and TypeBounder to be aware of nominal mode so that subtyping and LUBs
are correctly calculated.
Tests of the failing behavior will be added in a future PR that exposes this
functionality to the command line, since the current `example` testing
infrastructure cannot handle testing fatal errors.
> Nominal subtyping

- src/ir/module-splitting.cpp
- src/ir/module-splitting.h
- src/tools/wasm-split.cpp
- test/example/module-splitting.cpp
- test/lit/wasm-split/help.test
- test/lit/wasm-split/placeholdermap.wast
The new instruction emits a file containing a map between placeholder index and
the name of the split out function that placeholder is replacing in the table.
This map is intended to be useful for debugging, as discussed in
https://github.com/emscripten-core/emscripten/issues/14330.
> [wasm-split] Add an option to emit a placeholder map

- src/tools/wasm2js.cpp
- test/wasm2js.asserts.js
- test/wasm2js.traps.js
Assertions were previously parsed by replacing "invoke" with "call" and using
the normal s-expr parser. The parseCall method of the s-expr parser uses the
call target to look up the correct signature on the module, but the invoke
targets in assertions use export names rather than internal function names, so
the signature lookups were inserting new bogus entries with default values.
This issue didn't seem to cause any big problems before, but #3935 turns it into
a hard error because the default `HeapType` does not have an associated
signature.
Fix the problem (at least in the common case of trivial arguments and expected
results) by manually construction a `Call` expression rather than depending on
the s-expr parser to construct it.
> [wasm2js] Refactor assertion parsing

- src/support/command-line.cpp
- test/lit/wasm-split/help.test
Improve the legibility of the option documentation by adding vertical space
between options. This is particularly helpful to delimit the text of options
with longer explanations.
> Add space between options in --help text

- src/binaryen-c.cpp
- src/binaryen-c.h
- src/ir/module-splitting.cpp
- src/ir/module-utils.h
- src/js/binaryen.js-post.js
- src/tools/fuzzing.h
- src/wasm-builder.h
- src/wasm.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-validator.cpp
- test/binaryen.js/exception-handling.js
- test/binaryen.js/kitchen-sink.js
- test/binaryen.js/tag.js
- test/binaryen.js/tag.js.txt
- test/example/c-api-kitchen-sink.c
This removes `attribute` field from `Tag` class, making the reserved and
unused field known only to binary encoder and decoder. This also removes
the `attribute` parameter from `makeTag` and `addTag` methods in
wasm-builder.h, C API, and Binaryen JS API.
Suggested in
https://github.com/WebAssembly/binaryen/pull/3946#pullrequestreview-687756523.
> [EH] Make tag's attribute encoding detail

- src/wasm/wasm-binary.cpp
This changes the encoding of the `attribute` field, which currently only
contains the value `0` denoting this tag is for an exception, from
`varuint32` to `uint8`. This field is effectively unused at the moment
and reserved for future use, and it is not likely to need `varuint32`
even in future.
See https://github.com/WebAssembly/exception-handling/pull/162.
This does not change any encoded binaries because `0` is encoded in the
same way both in `varuint32` and `uint8`.
> [EH] Make tag attribute's encoding uint8

- src/passes/PostEmscripten.cpp
- test/passes/post-emscripten.txt
- test/passes/post-emscripten.wast
PostEmscripten will turn an invoke of a constant function
pointer index into a direct call. However, due to UB it is possible to
have invalid function pointers, and we should not crash on that
(and do nothing to optimize, of course).
Mostly whitespace; to avoid deep nesting, I added more
early returns.
> PostEmscripten: Handle invokes of invalid function pointers. See #14174

- src/ir/utils.h
- src/passes/Inlining.cpp
We have seen some cases in both Chrome and Firefox where
extremely large modules cause overhead,
https://github.com/WebAssembly/binaryen/pull/3730#issuecomment-867939138 (and link therein)
https://github.com/emscripten-core/emscripten/issues/13899#issuecomment-825073344
There is no "right" value to use as a limit here, but pick an
arbitrary one that is very high. (This setting is verified to have
no effect on the emscripten benchmark suite.)
> Set an absolute maximum inlining limit

- src/binaryen-c.cpp
- src/passes/RoundTrip.cpp
- src/tools/tool-options.h
- src/tools/wasm-as.cpp
- src/tools/wasm-ctor-eval.cpp
- src/tools/wasm-dis.cpp
- src/tools/wasm-emscripten-finalize.cpp
- src/tools/wasm-metadce.cpp
- src/tools/wasm-opt.cpp
- src/tools/wasm-split.cpp
- src/wasm-binary.h
- src/wasm/wasm-binary.cpp
- src/wasm/wasm-io.cpp
- src/wasm/wasm-s-parser.cpp
- test/unit/test_features.py
As suggested in
https://github.com/WebAssembly/binaryen/pull/3955#issuecomment-871016647
This applies commandline features first. If the features section is present, and
disallows some of them, then we warn. Otherwise, the features can combine
(for example, a wasm may enable feature X because it has to use it, and a user
can simply add the flag for feature Y if they want the optimizer to try to use it;
both flags will then be enabled).
This is important because in some cases we need to know the features before
parsing the wasm, in the case that the wasm does not use the features section.
In particular, non-nullable GC locals have an effect during parsing. (Typed
function references also does, but we found a way to apply its effect all the time,
that is, always use the refined type, and …
> Apply features from the commandline first

- scripts/port_passes_tests_to_lit.py
Filter out tests using --metrics, --emit-{js,spec}-wrapper, --fuzz-exec,
--print-stack-ir, --dwarfdump, etc. because they have ouput that will not be
captured in the automatically generated checks. Also filter based on the list of
passes rather than the test file in case the test uses a .passes file.
> Filter more passes tests in porting script

- test/lit/lit.cfg.py
We were previously configuring lit to execute test scripts via an external
shell, which caused lit to look for a bash installation on Windows. To make lit
tests work more "out of the box" on Windows, change the configuration to use
lit's built in shell capabilities instead.
> Do not execute lit tests via an external shell

- scripts/fuzz_opt.py
Emscripten stopped emitting shell support code by default (as most users
run node.js, but here we are literally fuzzing d8).
Fixes #3967
> Fix the fuzzer on wasm2c2wasm: emcc must request d8 support now

- scripts/fuzz_opt.py
The features section is additive since #3960. For the fuzzer to know which features
are used, it therefore needs to also scan the features section. To do this,
run `--print-features` to get the total features used from both flags + the
features section.
A result of this is that we now have a list of enabled features instead of
"enable all, then disable". This is actually clearer I think, but it does require
inverting the logic in some places.
May help with #3979 , although I haven't checked yet (cc @MaxGraey ).
> Fix features section handling in the fuzzer

- src/literal.h
- src/wasm-interpreter.h
- src/wasm/literal.cpp
- test/spec/simd.wast
Like a few other SIMD operations, this i64x2.bitmask had not been implemented in
the interpreter yet. Unlike the others, i64x2.bitmask has type i32 rather than
type v128, so Precompute was not skipping it, leading to a crash, as in
https://github.com/emscripten-core/emscripten/issues/14629. Fix the problem by
implementing i64x2.bitmask in the interpreter.
> Implement interpretation of i64x2.bitmask

- scripts/fuzz_opt.py
This works around the issue with wasm gc types sometimes getting
truncated (as the default names can be very long or even infinitely
recursive). If the truncation leads to name collision, the wast is not
valid.
Should we run name-types during load of a file using wasm GC? I
think you had some other idea here @tlively but I don't remember
what.
> Fuzzer: Use NameTypes in RoundTrip

- scripts/fuzz_opt.py
Now that the features section adds on top of the commandline arguments,
it means the way we test if initial contents are ok to use will not work if
the wasm has a features section - as it will enable a feature, even if
we wanted to see if the wasm can work without that feature. To fix this,
strip the features section there.
> Fuzzer: Fix handling of features with initial contents

- src/wasm/wasm.cpp
- test/passes/dce_all-features.txt
- test/passes/dce_all-features.wast
Without this fix, DCE would end up calling getHeapType() on the unreachable
input, which hits an assertion as it has no heap type.
> [Wasm GC] Fix getSentType() of BrOn with an unreachable input

- src/passes/Precompute.cpp
- test/passes/precompute_all-features.txt
- test/passes/precompute_all-features.wast
Reverts WebAssembly/binaryen#3983
Instead of applying the workaround to avoid precomputing SIMD in more places,
which prevents things we could optimize before, we should probably focus on
making the workaround not needed - that is, implement full SIMD support in the
intepreter (the reason for that PR), and the other TODO in the comment here,
```
// Until engines implement v128.const and we have SIMD-aware optimizations
// that can break large v128.const instructions into smaller consts and
// splats, do not try to precompute v128 expressions.
```
> Revert "Fix Precompute on SIMD"

- scripts/clang-tidy-diff.sh
> [clang-tidy-diff] Replace readlink -f to inline python script

- src/passes/RemoveUnusedBrs.cpp
- test/lit/passes/remove-unused-brs.wast
The spec disallows that.
Fixes #3990
> RemoveUnusedBrs: Do not create a select with a multivalue result

- src/tools/wasm-reduce.cpp
This removes the code that did so one at a time, and instead adds it
in a way that we can do it in an exponentially growing set of functions.
On large testcases where other methods do not work, this is very
useful.
Also adjust the factor to do this 20x more often, which in practice
is very useful too.
> Exponentially empty out function bodies when reducing

- src/ir/abstract.h
- src/ir/properties.h
- src/passes/OptimizeInstructions.cpp
- test/lit/passes/optimize-instructions-atomics.wast
- test/lit/passes/optimize-instructions.wast
- test/wasm2js/reinterpret.2asm.js.opt
FIx #3973
```rust
f32.reinterpret_i32(i32.load(x))  =>  f32.load(x)
f64.reinterpret_i64(i64.load(x))  =>  f64.load(x)
i32.reinterpret_f32(f32.load(x))  =>  i32.load(x)
i64.reinterpret_f64(f64.load(x))  =>  i64.load(x)
```
```rust
f32.store(y, f32.reinterpret_i32(x))  =>  i32.store(y, x)
f64.store(y, f64.reinterpret_i64(x))  =>  i64.store(y, x)
i32.store(y, i32.reinterpret_f32(x))  =>  f32.store(y, x)
i64.store(y, i64.reinterpret_f64(x))  =>  f64.store(y, x)
```
```rust
i32.reinterpret_f32(f32.reinterpret_i32(x))  =>  x
i64.reinterpret_f64(f64.reinterpret_i64(x))  =>  x
f32.reinterpret_i32(i32.reinterpret_f32(x))  =>  x
f64.reinterpret_i64(i64.reinterpret_f64(x))  =>  x
```
> [Optimize Instructions] Combine reinterprets, loads and stores

- src/passes/OptimizeInstructions.cpp
- test/lit/passes/optimize-instructions-sign-ext.wast
- test/lit/passes/optimize-instructions.wast
For signed or unsigned extension to 64-bits after lowering from partially filled 64-bit arguments:
```rust
i64.extend_i32_u(i32.wrap_i64(x))  =>  x   // where maxBits(x) <= 32
i64.extend_i32_s(i32.wrap_i64(x))  =>  x   // where maxBits(x) <= 31
```
> [Optimize Instructions] Simplify zero/sign extentions (special case)

- src/tools/wasm-reduce.cpp
Instead of skipping to the end, move quickly towards the end. This is
sometimes more efficient (as jumping from a big factor to a factor of 1
can skip over big opportunities to remove code all at once instead of
once instruction at a time).
> Reduce more carefully when it looks like we are failing

- src/tools/wasm-reduce.cpp
`tryToRemoveFunctions()` will reload the wasm from binary if it fails to
optimize, and without the names section we don't have a guarantee on the
names being the same after that. And then `tryToEmptyFunctions` would
look for a name, and crash.
In the reverse order there is no risk, as `tryToEmptyFunctions` does not
reload the wasm from binary, it carefully undoes what it tried to do when
it fails.
> wasm-reduce: Avoid a crash where function names change after tryToRemoveFunctions()

- src/passes/Heap2Local.cpp
- src/passes/Precompute.cpp
- src/wasm-builder.h
- test/lit/passes/heap2local.wast
Given
```wat
(local $x (ref $foo))
(local.set $x ..)
(.. (local.get $x))
```
If we remove the `local.set` but not the get, then we end up with
```wat
(local $x (ref $foo))
(.. (local.get $x))
```
It looks like the `local.get` reads the initial value of a non-nullable local,
which is not allowed.
In practice, this would crash in `precompute-propagate` which would
try to propagate the initial value to the get. Add an assertion there with
a clear message, as until we have full validation of non-nullable locals
(and the spec for that is in flux), that pass is where bugs will end up
being noticed.
To fix this, replace the get as well. We can replace it with a null
for simplicity; it will never be used anyhow.
This also uncovered a small bug with `reached` not containing all
the things we …
> [Wasm GC] Fix Heap2Local + non-nullable locals

- src/passes/LocalSubtyping.cpp
- test/lit/passes/local-subtyping.wast
The pass handled non-nullability, but another case is a tuple with nullable
values in it that is assigned non-nullable values, and in general, other stuff
that is nondefaultable (but not non-nullable). Ignore those.
> [Wasm GC] Handle nondefaultable types in LocalSubtyping

- src/passes/DeadArgumentElimination.cpp
- test/lit/passes/dae-gc.wast
Corresponds to #4014 which did the same for parameter types. This sees
whether the return types actually returned from a function allow us to use
a more specific type for the function's return. If so, we update that type, as
well as calls to the function.
> [Wasm GC] Refine return types

- src/passes/DeadArgumentElimination.cpp
- test/lit/passes/dae-gc.wast
If there is a tail call, we can't change the return type of the function, as it
must match in the functions doing a tail call of it.
> [Wasm GC] DeadArgumentElimination: Do not refine return types of tail callees

- src/passes/DeadArgumentElimination.cpp
- test/lit/passes/dae-gc.wast
Partially reverts #4025, removing the code and updates the test to show
we do the optimization.
> [Wasm GC] Allow tail call subtyping in DeadArgumentElimination

- src/passes/LocalSubtyping.cpp
- src/passes/Precompute.cpp
- src/tools/execution-results.h
- test/lit/passes/local-subtyping-nn.wast
- test/lit/passes/local-subtyping.wast
If the default value is used, it is better to not change the local type. See
details in the comment.
> [Wasm GC] Handle uses of default values in LocalSubtyping

- src/passes/DeadArgumentElimination.cpp
- test/lit/passes/dae-gc-refine-return.wast
This should be the last call type...
If this pattern appears anywhere else (get all the return types) we should
have a helper for it, but it seems to only happen in this one pass.
> [Wasm GC] Handle call_ref in DeadArgument return refinement

- src/passes/ExtractFunction.cpp
- test/lit/passes/extract-function.wast
We just cleared the list of exports, but the exportMap was still populated, so
the data was in an inconsistent state. We should perhaps have `clearExport()`
etc. methods. If those sound good I can add them as a followup.
This fixes the case of running `--extract-function` multiple times on a file (which
is usually not useful, unless one of the passes you are debugging adds new
functions to the file - which some do).
> Do not crash in ExtractFunction if an export already exists

- src/passes/LocalSubtyping.cpp
- test/lit/passes/local-subtyping.wast
Validation cares about unreachable gets and tees, so we must fix
them up as well.
> [Wasm GC] Handle unreachability in LocalSubtyping

- third_party/llvm-project/DWARFVisitor.cpp
(on VS2019)
Triggered by:
wasm-emscripten-finalize --minimize-wasm-changes -g --bigint --no-dyncalls --dwarf test_asan_api.wasm -o test_asan_api.wasm --detect-features
> Fix assert on access of empty vector

- src/passes/OptimizeForJS.cpp
`rewritePopcntEqualOne` routine could be simplified using Abstract namespace
> [OptimizeForJS] Refactor rewritePopcntEqualOne

- src/passes/Directize.cpp
We assign a `const&` to there, and were copying it...
> Avoid an unnecessary copy in Directize

- src/passes/Print.cpp
- test/heap-types.wast
- test/heap-types.wast.from-wast
- test/heap-types.wast.fromBinary
- test/heap-types.wast.fromBinary.noDebugInfo
We were missing StructNew and ArrayLen.
> [Wasm GC] Fix printing of more unreachable struct/array instructions

- src/ir/global-utils.h
- src/ir/properties.h
We have a not-very-clear distinction between
isSingleConstantExpression
and
canInitializeGlobal
To make it useful, the former should mean a constant expression:
something that is a simple constant like a number or a ref.func, that
will always be the same value at runtime. That means we should
move the I31 constructor from there to the second function. After that,
the I31 constructor is no longer in a weird place, and is alongside its
sibling constructors for other GC things.
This is NFC, but perhaps it also fixes a bug in a pass that uses
isSingleConstantExpression incorrectly. I was unable to find such
a bug, however. After this PR, I think we can use
isSingleConstantExpression in more places (like in an upcoming
GC type LTO pass I am working on, that wants to propagate
constant values). …
> [Wasm GC] Remove I31New from isSingleConstantExpression. NFC

- src/passes/OptimizeForJS.cpp
- test/lit/passes/optimize-for-js.wast
We should use `loacalizer.expr` in first usage instead get local. Fixing this
> [OptimizeForJS] Fix fist usafe of localized variable in popcnt(x) == 1 rule

- CMakeLists.txt
- src/tools/wasm-shell.cpp
Partial fix for https://github.com/WebAssembly/binaryen/issues/3661
> Clean up warnings on MSVC

- src/ir/type-updating.cpp
- src/ir/type-updating.h
This moves code out of the existing methods so that it can be
called directly from more places. A later PR will use the new
methods.
> Refactor TypeUpdating non-nullability code. NFC

- src/passes/ConstantFieldPropagation.cpp
- test/lit/passes/cfp.wast
Previously we tracked them in the same way. That means that we did the same
when seeing if either a `struct.new` or a `struct.set` can write to the memory that
is read by a `struct.get`, where the rule is that if either type is a subtype of the
other then they might. But with `struct.new` we know the precise type, which
means we can do better.
Specifically, if we see a new of type B, then only a get of a supertype of B can
possibly read that data: it is not possible for our struct of type B to appear in
a location that requires a subtype of B. Conceptually:
```python
A = type struct
B = type extends A
C = type extends B
x = struct.new<B>
struct.get<A>(y) // x might appear here, as it can be assigned to a
// variable y of a supertype
struct.get<C>(y) // x cannot appear here
```
This allows …
> [Wasm GC] Track struct.new and struct.set separately in ConstantFieldPropagation

- src/passes/RemoveUnusedBrs.cpp
- test/lit/passes/remove-unused-brs-gc.wast
This only moves code around. `visitBrOn` was in the main part of the pass,
which was incorrect as it could interfere with other work being done there.
Specifically, we have a stack of Ifs there, and if we replace a BrOn with
an If, an assertion was hit.  To fix this, run it like `sinkBlocks()`, in a separate
interleaved phase.
This fixes a bug reported by @askeksa-google here:
https://github.com/WebAssembly/gc/issues/226#issuecomment-868739853
> Fix BrOn logic in RemoveUnusedBrs

- src/wasm.h
- src/wasm/wasm-binary.cpp
This was being set in the creation of Loads in the binary reader, but
forgotten in the SIMD logic - which ends up creating a Load with
type v128, and `signed_` was uninitialized.
Very hard to test this, but I saw it "break" hash value computation
which is how I noticed this.
Also initialize the I31 sign field. Now all of them in wasm.h are
properly initialized.
> Fix signed_ field initialization in Load

- src/ir/linear-execution.h
- src/wasm.h
This caused no noticeable bugs, but it could in theory in new passes - in fact
in a pass I will open later this week it did.
Also fix the order in wasm.h. That part has no effect, but it is nice to be
consistent. After this PR, everything should match the single source of
truth which is wasm-delegations-fields.h (as that is used in printing, binary
reading/writing, etc., so it has to be correct). Also Switch now matches
the ordering in Break.
> Fix the Switch operand order in LinearExecutionWalker

- src/ir/ExpressionAnalyzer.cpp
- src/ir/utils.h
- test/example/hash.cpp
This adds and tests the new method. It will be used in a new pass later, where
computing shallow hashes allows it to be done in linear time.
99% of the diff is whitespace.
> Add a shallowHash() method

- src/tools/wasm-reduce.cpp
- test/lit/help/wasm-reduce.test
1. Use ToolOptions there, which adds `--nominal` support.
2. We must also pass `--nominal` to the sub-commands we run.
> Support nominal typing in wasm-reduce

- src/passes/ConstantFieldPropagation.cpp
- test/lit/passes/cfp.wast
When looking for all values written to a field, we can ignore
values that are loaded from that same field, i.e., are copied from
something already present there. Such operations never introduce
new values.
This helps by a small but non-zero amount on j2cl.
> [Wasm GC] ConstantFieldPropagation: Ignore copies

- src/passes/LocalCSE.cpp
- test/lit/passes/local-cse.wast
- test/lit/passes/local-cse_all-features.wast
If we replace
```
A
A
A
```
with
```
(local.set A)
(local.get)
(local.get)
```
then it is ok for A to trap (so long as it does so deterministically), as if
it does trap then the first appearance will do so, and the others not
be reached anyhow.
This helps GC code as often there are repeated `struct.gets` and such that
may trap.
> LocalCSE: ignore traps

- src/ir/effects.h
- test/lit/passes/local-cse_all-features.wast
This allows common patterns in J2CL to be optimized, where we write
to various array indices and get the values or the reference from a
struct.
It would be nice to do even better here, and look at actually specific
types, but I think we should be careful to keep the runtime constant.
That seems hard to do if we accumulate a list of types and do
`Type::isSubType` on them etc. But maybe someone has a better
idea than this PR?
> [Wasm GC] Effects: Differentiate Struct and Array types

- src/ir/properties.h
- src/passes/LocalCSE.cpp
Before, we'd compute the hash of a child, then store that in a map, then
the parent would find the child's hash in the map using the pointer to the
child. But as we do a simple postorder walk, we can use a stack, and
avoid hashing the child pointers.
This makes it 10% faster or so.
> Optimize LocalCSE hash computations using a stack. NFC

- src/wasm/literal.cpp
- test/spec/ref_eq.wast
Found by the fuzzer. I'm surprised it didn't do so earlier...
> [Wasm GC] Nulls compare equal regardless of type

- src/cfg/cfg-traversal.h
Reverse postorder basically just means that a block's immediate dominator
must precede it in the list. That is useful because then algorithms that look at
dominance can simply process the list in order, and the immediate dominator
will have already been seen before each block.
Another way to put it is that in reverse postorder a block's dominators
appear before it in the list, as do all non-loop predecessors. At least in
reducible graphs that is the case, and our IR, like wasm, is reducible.
It is pretty natural to emit reverse postorder on wasm given the
reducibility: simply process the wasm in postorder, and make sure to
create new basic blocks only when reaching their code - that is, do not
create them "ahead of time". We were doing that in a single place, for
try-catch, so this PR …
> Ensure cfg-traversal emits blocks in reverse postorder, refactoring try. NFC

- README.md
These paragraphs talked about push and pop, which are no longer relevant. More up-to-date information is already included above in the "Tree structure" section.
> Remove out-of-date multivalue info in README

- src/ir/block-utils.h
- src/ir/effects.h
- src/ir/properties.h
- src/passes/CodeFolding.cpp
- src/passes/DeadArgumentElimination.cpp
- src/passes/LocalCSE.cpp
- src/passes/LoopInvariantCodeMotion.cpp
- src/passes/MergeBlocks.cpp
- src/passes/OptimizeInstructions.cpp
- src/passes/RemoveUnusedBrs.cpp
- src/passes/SimplifyGlobals.cpp
- src/passes/SimplifyLocals.cpp
- src/passes/Vacuum.cpp
- src/wasm2js.h
Knowing the module will allow us to do more analysis in the
effect analyzer. For now, this just refactors the code to allow
providing a module instead of features, and to infer the
features from the module. This actually shortens the code in
most places which is nice (just pass `module` instead of
`module->features`).
This modifies basically all callers to use the new module
form, except for the fallthrough logic. That would require
some more refactoring, so to keep this PR reasonably small
that is not yet done.
> Add a Module parameter to EffectAnalyzer. NFC

- CHANGELOG.md
- src/binaryen-c.cpp
- src/binaryen-c.h
- src/ir/effects.h
- src/ir/local-utils.h
- src/ir/ordering.h
- src/ir/properties.h
- src/js/binaryen.js-post.js
- src/passes/AvoidReinterprets.cpp
- src/passes/CodePushing.cpp
- src/passes/ConstantFieldPropagation.cpp
- src/passes/Heap2Local.cpp
- src/passes/OptimizeAddedConstants.cpp
- src/passes/OptimizeInstructions.cpp
- src/passes/Precompute.cpp
- src/passes/SimplifyLocals.cpp
- test/binaryen.js/sideffects.js
- test/example/cpp-unit.cpp
This finishes the refactoring started in #4115 by doing the
same change to pass a Module into EffectAnalyzer instead of
features. To do so this refactors the fallthrough API and a few
other small things. After those changes, this PR removes the
old feature constructor of EffectAnalyzer entirely.
This requires a small breaking change in the C API, changing
`BinaryenExpressionGetSideEffects`'s feature param to a
module. That makes this change not NFC, but otherwise it is.
> Use the new module version of EffectAnalyzer

- src/ir/effects.h
- src/passes/Vacuum.cpp
- test/lit/passes/vacuum-tnh.wast
We had already replaced the check on `drop`, but we can also
use that mode on all the other things there, as the pass never
does reorderings of things - it just removes them.
For example, the pass can now remove part of a dropped thing,
```wat
(drop (struct.get (foo)))
=>
(drop (foo))
```
In this example the `struct.get` can be removed, even if the `foo`
can't.
> Use TrapsNeverHappen mode in more places in Vacuum

- src/ir/effects.h
- src/passes/OptimizeInstructions.cpp
- test/example/cpp-unit.cpp
This appeared to be a regression from #4117, however this
was always a bug, and that PR just exposed it. That is,
somehow we forgot to indicate the effects of ArrayCopy, and
after that PR we'd vacuum it out incorrectly.
> Fix the effects of array.copy

- src/tools/wasm-split/instrumenter.cpp
- src/tools/wasm-split/instrumenter.h
- src/tools/wasm-split/split-options.cpp
- src/tools/wasm-split/split-options.h
- src/tools/wasm-split/wasm-split.cpp
- test/lit/help/wasm-split.test
- test/lit/wasm-split/call_exports.mjs
- test/lit/wasm-split/instrument-in-memory.wast
- test/lit/wasm-split/profile-guided.wast
To avoid requiring a static memory allocation, wasm-split's instrumentation
defaults to recording profile data in Wasm globals. This causes problems for
multithreaded applications because the globals are thread-local, but it is not
always feasible to arrange for a separate profile to be dumped on each thread.
To simplify the profiling of such multithreaded applications, add a new
instrumentation mode that stores the profiling data in shared memory instead of
in globals. This allows a single profile to be written that correctly reflects
the called functions on all threads.
This new mode is not on by default because it requires users to ensure that the
program will not trample the in-memory profiling data. The data is stored
beginning at address zero and occupies one byte per declared …
> [wasm-split] Add an option for recording profile data in memory

- src/passes/Inlining.cpp
It can be confusing during debugging to keep a map of pointers when
we might have removed some of those functions from the module
meanwhile (if you iterate over it in some additional debug logging).
This change has no observable effect, however, as no bug could have
actually occurred in practice given that nothing is done with the
pointers in the actual code.
> [NFC] Inlining: Track names over multiple iterations, not pointers

- src/tools/wasm-split/CMakeLists.txt
In an attempt to fix https://github.com/emscripten-core/emsdk/issues/886.
> Use STATIC instead of OBJECT for wasm-split-lib

- src/tools/wasm-split/instrumenter.cpp
- test/lit/wasm-split/imported-memory.wast
We can assume that imported memories (and the profiling data they contain) are
already accessible from the module's environment, so there's no need to export
them. This also avoids needing to add knowledge of "profile-memory" to
Emscripten's library_dylink.js.
> [wasm-split] Do not add exports of imported memories

- src/emscripten-optimizer/simple_ast.h
Validation is performed on multiple threads at once and when there are multiple
validation failures, those threads can all end up in `numToString` at the same
time as they construct their respective error messages. Previously the threads
would race on their access to the snprintf buffers, sometimes leading to
segfaults. Fix the data races by making the buffers thread local.
> Make static buffers in numToString thread local

- src/passes/MergeBlocks.cpp
Followup to #4137 , I looked into the idea @tlively had but I
realized it is actually not necessary for a non-obvious reason.
This PR adds a comment.
> [NFC] Add a comment in MergeBlocks about subtyping

- scripts/fuzz_opt.py
- src/passes/RemoveUnusedBrs.cpp
- test/passes/remove-unused-brs_enable-multivalue.txt
- test/passes/remove-unused-brs_enable-multivalue.wast
`tablify()` attempts to turns a sequence of `br_if`s into a single
`br_table`. This PR adds some flexibility to the specific pattern it
looks for, specifically:
* Accept `i32.eqz` as a comparison to zero, and not just to look
for `i32.eq` against a constant.
* Allow the first condition to be a `tee`. If it is, compare later
conditions to `local.get` of that local.
This will allow more `br_table`s to be emitted in j2cl output.
> RemoveUnusedBrs::tablify() improvements: handle EqZ and tee

- scripts/fuzz_opt.py
- src/passes/OptimizeInstructions.cpp
- test/lit/passes/optimize-instructions-gc.wast
Avoids a crash in calling `getHeapType` when there isn't one.
Also add the relevant lit test (and a few others) to the list of files to
fuzz more heavily.
> [Wasm GC] Fix OptimizeInstructions on unreachable ref.test

- test/lit/lit.cfg.py
As well BINARYEN_CORES for good measure. This means that when check.py tries to
run the lit tests with BINARYEN_PASS_DEBUG, this is now correctly reflected in
the tests. Manually validated to catch the bug identified in
#4130 (comment).
> Propagate BINARYEN_PASS_DEBUG to lit test commands

- src/ir/match.h
- src/passes/OptimizeInstructions.cpp
- test/example/match.cpp
- test/example/match.txt
Also refactor `check` util in `optimizeTernary`.
cc @tlively
> [Matcher] Add bval for matching boolean literals

- src/ir/iteration.h
- src/wasm-delegations-fields.def
Remove an unnecessary include, and fix a typo in a macro
declaration (that macro is not tested as it seems nothing uses
`DELEGATE_END` yet, but I may be soon).
> Tiny code cleanups. NFC

- src/wasm-s-parser.h
- src/wasm/wasm-s-parser.cpp
Without this we hit an assert which is not that helpful.
> Properly error on bad function names in text format

- src/passes/Precompute.cpp
- src/support/unique_deferring_queue.h
This makes the code a little shorter, and more consistent with other
similar queue situations we have in the codebase.
> Use UniqueDeferringQueue in Precompute

- src/passes/RemoveUnusedBrs.cpp
- test/lit/passes/asyncify_optimize-level=1.wast
- test/lit/passes/remove-unused-brs.wast
```js
if (A) {
if (B) {
C
}
}
=>
if (A ? B : 0) {
C
}
```
when B has no side effects, and is fast enough to consider running
unconditionally. In that case, we replace an `if` with a `select` and a
zero, which is the same size, but should be faster and may be
further optimized.
As suggested by @MaxGraey in #4168 (thanks!)
An asyncify test happens to be helped by this; the diff there is
mostly whitespace. Proper new testing appears after that in the
`lit` test for this.
> RemoveUnusedBrs: Optimize if-of-if pattern

- src/passes/Precompute.cpp
- test/passes/precompute-propagate_all-features.txt
- test/passes/precompute-propagate_all-features.wast
Precompute has a mode in which it propagates results from `local.set`s to
`local.get`s. That constructs a LocalGraph which is a non-trivial amount of
work. We used to run multiple iterations of this, but investigation shows that
such opportunities are extremely rare, as doing just a single propagation
iteration has no effect on the entire emscripten benchmark suite, nor on
j2cl output. Furthermore, we run this pass twice in the normal pipeline (once
early, once late) so even if there are such opportunities they may be
optimized already. And, `--converge` is a way to get additional iterations of
all passes if a user wants that, so it makes sense not to costly work for more
iterations automatically.
In effect, 99.99% of the time before this pass we would create the LocalGraph
twice: once …
> Precompute: Only run a single LocalGraph iteration

- scripts/fuzz_opt.py
Fuzzer shows the initial contents and prompts the user if they want to
proceed after #4173, but when the fuzzer is used within a script called
from `wasm-reduce`, we shouldn't pause for the user input. This shows
the prompt only when there is no seed given.
To do that, we now initialize the important initial contents from
`main`. We used to assign those variables before we start `main`.
> [Fuzzer] Don't prompt user when seed is given

- src/tools/wasm-split/split-options.cpp
- src/tools/wasm-split/wasm-split.cpp
- test/lit/help/wasm-split.test
- test/lit/wasm-split/basic.wast
- test/lit/wasm-split/invalid-options.wast
- test/lit/wasm-split/verbose.wast
Previously the set of functions to keep was initially empty, then the profile
added new functions to keep, then the --keep-funcs functions were added, then
the --split-funcs functions were removed. This method of composing these
different options was arbitrary and not necessarily intuitive, and it prevented
reasonable workflows from working. For example, providing only a --split-funcs
list would result in all functions being split out not matter which functions
were listed.
To make the behavior of these options, and --split-funcs in particular, more
intuitive, disallow mixing them and when --split-funcs is used, split out only
the listed functions.
> [wasm-split] Disallow mixing --profile, --keep-funcs, and --split-funcs

- src/passes/Inlining.cpp
By mistake the recent partial inlining work introduced quadratic time into
the compiler: erasing a function from the list of functions takes linear time,
which is why we have `removeFunctions` that does a group at a time.
This isn't noticeable on small programs, but on j2cl output this makes the
`inlining-optimizing` step 2x faster.
See #4165
> Inlining: Remove unneeded functions in linear time

- scripts/clang-tidy-diff.sh
We don't keep files within test/ clang-tidy compliant, so including this
directory can generate CI errors when test files change.
> Exclude test/ from clang-tidy

- scripts/fuzz_opt.py
Without this, the reduction script won't use the same initial contents,
which means it may see different things.
> Fuzzer: Add --auto-initial-contents automatically to reduction script

- src/passes/OptimizeInstructions.cpp
- test/example/c-api-kitchen-sink.c
- test/lit/passes/optimize-instructions-gc.wast
- test/passes/Oz_fuzz-exec_all-features.txt
Now that they are all implemented, we can optimize them. This removes the
big `if` that ignored static operations, and implements things for them.
In general this matches the existing rtt-using case, but there are a few things
we can do better, which this does:
* A cast of a subtype to a type always succeeds.
* A test of a subtype to a type is always 1 (if non-nullable).
* Repeated static casts can leave just the most demanding of them.
(diff without whitespace is smaller)
> [Wasm GC] Optimize static (rtt-free) operations

- scripts/clang-tidy-diff.sh
While making clang-tidy CI only check for src/, #4193 accidentally
overrided the existing default regex that checks only c/cpp/h... files:
https://github.com/llvm/llvm-project/blob/8971b99c8387f3daf2e802956f2688b3b77335a4/clang-tools-extra/clang-tidy/tool/clang-tidy-diff.py#L131-L132
This fixes the problem by appending all those extensions after `src/`.
> Fix clang-tidy regex

- scripts/update_lit_checks.py
The upstream name of the command in LLVM is FileCheck, but we use a Python
package called filecheck instead and using `FileCheck` in lit tests will not
work. To make catching this common error easier, add a warning about it in
scripts/update_lit_checks.py.
> Detect erroneous use of "FileCheck" in update script
