WebAssembly/binaryen

src/passes/CoalesceLocals.cpp
Emscripten must have rolled in a new warning about using `|` on booleans.
=> Fix Emscripten build by changing `|` to `||`

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-call_ref.wast
Rather than load from the table and call that reference, call using the table.
Am I missing some corner case that prevents doing this? (Would be sad if so, as I
hope to build on this to do more devirtualization.)
=> Optimize call_ref+table.get => call_indirect

src/wasm-delegations-fields.def
The `type` field is present in all Expressions, but RefNull's delegations
marked it as if it were a new field. That meant that we process it twice.
This was just some extra work mostly, but a new pass I will open later
will actually error on such things.
=> Fix RefNull in wasm-delegations-fields.def

src/wasm/wasm-binary.cpp
Update the binary format used in --nominal mode to match the format of nominal
types in milestone 4. In particular, types without declared supertypes are now
emitted using the nominal type codes with either `func` or `data` as their
supertypes. This change is hopefully enough to get --nominal mode code running
on V8's milestone 4 implementation until the rest of the type system changes can
be implemented for use without --nominal.
=> Update nominal binary format to match milestone 4

CMakeLists.txt
The thinLTO backend is already multithreaded, so combining with
build system-level parallelism can bog a machine down.
=> Limit to 2 parallel link jobs when using LTO

src/ir/lubs.h, src/passes/DeadArgumentElimination.cpp, src/passes/LocalSubtyping.cpp
This is a minor refactoring in DAE to have a helper class that does the
incremental LUB calculation. The class is also used in LocalSubtyping,
where it has the effect of making the work incremental which it was not
before (that would have no observable consequence, but it should make
us faster in the common case where we fail to find a new LUB).
This refactoring by itself does little, but it provides a central place to
further optimize this LUB calculation, which will be in a later PR.
=> [Wasm GC] LUBFinder helper. NFC

CMakeLists.txt
This version represents that current reality although we
would like to lower this for increased compatibility. See: #4299
=> Set CMAKE_OSX_DEPLOYMENT_TARGET

src/literal.h, src/wasm-builder.h, src/wasm-interpreter.h, src/wasm-type.h, src/wasm/literal.cpp, src/wasm/wasm-type.cpp, src/wasm/wasm-validator.cpp, test/lit/exec/rtts.wast, test/passes/Oz_fuzz-exec_all-features.txt, test/passes/Oz_fuzz-exec_all-features.wast
Allocation and cast instructions without explicit RTTs should use the canonical
RTTs for the given types. Furthermore, the RTTs for nominal types should reflect
the static type hierarchy. Previously, however, we implemented allocations and
casts without RTTs using an alternative system that only used static types
rather than RTT values. This alternative system would work fine in a world
without first-class RTTs, but it did not properly allow mixing instructions that
use RTTs and instructions that do not use RTTs as intended by the M4 GC spec.
This PR fixes the issue by using canonical RTTs where appropriate and cleans up
the relevant casting code using std::variant.
-----
The code in this PR should be complete, but it will need tests.
=> Fix RTTs for RTT-less instructions

src/tools/fuzzing.h, src/tools/fuzzing/fuzzing.cpp, test/passes/fuzz_metrics_noprint.bin.txt, test/passes/translate-to-fuzz_all-features_metrics_noprint.txt
Generate both nullable and non-nullable references to basic HeapTypes and
introduce `i31` and `data` HeapTypes. Generate subtypes rather than exact types
for all concrete-typed children.
=> Fuzz more basic GC types

src/passes/RemoveUnusedBrs.cpp, test/lit/passes/remove-unused-brs-gc.wast
The BrOn logic there is incremental in optimizing and updating types, and so
we cannot assume that at every point in the middle the types are fully
updated.
=> Fix fuzz bug in RemoveUnusedBrs with incremental type updating

src/ir/CMakeLists.txt, src/ir/eh-utils.cpp, src/ir/eh-utils.h, src/ir/iteration.h, src/wasm/wasm-validator.cpp, test/exception-handling.wast, test/exception-handling.wast.from-wast, test/exception-handling.wast.fromBinary, test/exception-handling.wast.fromBinary.noDebugInfo, test/lit/passes/inlining-eh.wast, test/lit/passes/remove-unused-names-eh.wast, test/spec/exception-handling.wast
This improves validation of `catch` bodies mostly by checking the
validity of `pop`s.
For every `catch` body:
- Checks if its tag exists
- If the tag's type is none:
- Ensures there shouldn't be any `pop`s
- If the tag's type is not none:
- Checks if there's a single `pop` within the catch body
- Checks if the tag type matches the `pop`'s type
- Checks if the `pop`'s location is valid
For every `catch_all` body:
- Ensures there shuldn't be any `pop`s
This uncovers several bugs related to `pop`s in existing tests, which
this PR also fixes.
=> [EH] Improve catch validation

src/ir/struct-utils.h, src/passes/ConstantFieldPropagation.cpp, src/passes/GlobalTypeOptimization.cpp
This avoids cluttering the main `wasm` namespace, and clarifies what the
scanner does.
=> [NFC] Add StructUtils namespace, and Scanner => StructScanner

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-gc.wast
We found one cast that has another as its input, and forgot that
the child was possibly a fallthrough value. That is, there might be more
code that needs to be kept around.
Rather than fix the middle of the three cases there - the one with
`HeapType::isSubType(childIntendedType, intendedType)` - I
noticed it is not actually needed. That case checks if the child's
type is more specific than the parent's, and if so, then the parent
is not needed. But we already handle that earlier above in the
same function: regardless of what the child of a static cast is,
if the cast is static and the input is the proper type already, the
cast is unneeded (see lines 1565-1566).
=> OptimizeInstructions: Fix static cast optimizations

src/passes/CoalesceLocals.cpp, test/lit/passes/Oz.wast, test/lit/passes/coalesce-locals.wast, test/lit/passes/optimize-instructions-gc.wast
Tiny followup to #4314
Existing tests happen to already cover this pretty well.
Also updates some function types in test output - I suspect that is from a
race in landing of PRs.
=> CoalesceLocals: Remove a redundant tee of the same local as a parent set

src/ir/type-updating.cpp, src/ir/type-updating.h, src/passes/DeadArgumentElimination.cpp
This just moves code around. The code will be used from a new pass in
a subsequent PR (that does subtyping of function signatures - that is,
DAE subtypes each function's params by themselves, while the new
pass will subtype particular signature types, which allows subtyping of
functions called indirectly, that DAE can't help with).
=> [NFC] Refactor param updating code to a shared location

src/ir/literal-utils.h, test/lit/passes/vacuum-gc.wast
Found by the fuzzer. Calling makeZero on an rtt with depth will
error because we try to create a zero Literal from it, and we can't
do that - we don't know a list of super types to give it. We could
work around it, but we don't want to: if the rtt has depth then we
can't make a nice zero for it, we'd need some rtt.subs anyhow,
so simply mark it as a type we can't make a zero for.
=> Fix vacuum on rtts with depth

src/passes/Directize.cpp, test/lit/passes/directize_all-features.wast
The order of operations could allow us to add vars but then later decide
not to do the optimization due to unreachability. And then we did not do a
fixup for non-nullability for those args, leading to a fuzzer error.
=> Directize: Fix handling of non-nullable locals and unreachability

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions.wast
It's first part of #4265
```rust
(i32(x) == 0) & (i32(y) == 0)   ==>   i32(x | y) == 0
(i64(x) == 0) & (i64(y) == 0)   ==>   i64(x | y) == 0
```
=> [OptimizeInstructions] Combine some relational ops joined Or/And (Part 1)

src/ir/numbering.h, src/passes/RedundantSetElimination.cpp
This just moves code out of RedundantSetElimination. This code will be
useful in a future PR to improve CoalesceLocals in the direction suggested
by @tlively in https://github.com/WebAssembly/binaryen/pull/4314#discussion_r745944545
=> [NFC] Move value numbering code to a header

src/tools/fuzzing/heap-types.cpp, src/tools/fuzzing/heap-types.h, src/tools/wasm-fuzz-types.cpp, src/wasm-type.h, src/wasm/wasm-type.cpp
Check that types that were meant to have a subtype relationship actually do. To
expose the intended subtyping to the fuzzer, expose `subtypeIndices` in the
return value of the type generation function.
=> Check for correct subtyping in the type fuzzer

src/wasm2js.h, test/wasm2js/atomics_32.2asm.js, test/wasm2js/atomics_32.2asm.js.opt
Its seems that with this emscripten change DCE is able to remove
the `assert` JS runtime function making this call to assert fail
with `ReferenceError: assert is not defined`:
https://github.com/emscripten-core/emscripten/pull/15588
I guess this generated code is not included in the DCE graph?
=> wasm2js: Don't assume the existence of js assert function

CMakeLists.txt
=> [CMake] Use -O2 for all targets

src/passes/LocalCSE.cpp, src/passes/OptimizeInstructions.cpp
PassOptions is a fairly large structure and even includes a `std::map`. I also
have plans to add further fields there to make it even larger. Before doing that
I noticed that in some places we copy it instead of being consistent and taking
it by reference, which this PR fixes.
=> [NFC] Avoid unnecessary copies of PassOptions

src/wasm/wasm-binary.cpp, test/exception-handling.wast, test/exception-handling.wast.from-wast, test/exception-handling.wast.fromBinary, test/exception-handling.wast.fromBinary.noDebugInfo
We do some postprocessing after parsing `Try` to make sure `delegate`
only targets `try`s and not `block`s:
https://github.com/WebAssembly/binaryen/blob/9659f9b07c1196447edee68fe04c8d7dd2480652/src/wasm/wasm-binary.cpp#L6404-L6426
But in case the outer `try` has neither of `catch` nor `delegate`, the
previous code just return prematurely, skipping the postprocessing part,
resulting in a binary parsing error. This PR removes that early-exiting
code.
Some test outputs have changed because `try`s are assigned labels after
the early exit. But those labels can be removed by other optimization
passes when there is no inner `rethrow` or `delegate` that targets them.
(On a side note, the restriction that `delegate` cannot target a `block`
has been removed a few months ago in the spec, so if a …
=> [EH] Fix binary parsing for catchless try + inner delegate

src/ir/effects.h, test/example/cpp-unit.cpp
As suggested by @aheejin , we don't use those effects now in any way, and
if we need them some day we can add them back. For now they just add
overhead and complexity.
=> Do not track effects of immutable things

src/wasm2js.h, test/wasm2js/atomics_32.2asm.js, test/wasm2js/atomics_32.2asm.js.opt
Also, fix bug where pointer was being used direcltly to
index into Int32Array.  I suppose this code had basically
zero users until I tried to land this change in emscripten:
https://github.com/emscripten-core/emscripten/pull/15742
=> Implement timeout argument in wasm2js_atomic_wait_i32

src/passes/DeadArgumentElimination.cpp
We iterate on that data structure in two loops, and the fuzzer found a case
where the difference in ordering actually ended up mattering in the output.
Doing it this way is actually faster when I tested it now, so this seems like a
win-win...
=> Fix a DeadArgumentElimination determinism bug

src/wasm2js.h, test/wasm2js/atomics_32.2asm.js, test/wasm2js/atomics_32.2asm.js.opt
Opening a quick PR for this so we don't forget - this is the kind of issue that
can be easily missed later as noticing the lack of fractional timeouts is very, very
hard...
=> Allow fractional timeouts in wasm2js Atomics.wait. Followup to #4385

src/wasm/wasm-binary.cpp
=> Add requireFunctionContext in necessary places

src/tools/wasm-fuzz-types.cpp, src/wasm-type.h, src/wasm/wasm-type.cpp
Update the LUB calculation code to use std::optional rather than out params and
validate LUBs in the fuzzer to ensure that the change is NFC as intended. Also
add HeapType::getLeastUpperBound to the public API as a convenience.
=> Validate LUBs in the type fuzzer

README.md, src/passes/Inlining.cpp, test/lit/passes/inlining-eh.wast
Inlining creates additional `block`s at inlined call sites, which can be
inside a `catch`. For example:
```wast
(try
(do)
(catch $tag
(call $callee
(pop i32)
)
)
)
```
After inlining, this becomes
```wast
(try
(do)
(catch $tag
(block $__inlined_func$callee
(local.set $0
(pop i32) ;; Invalid!!
)
(nop)
)
)
)
```
Now the `pop` is nested in a `block`, which makes this invalid. This PR
runs `EHUtils::handleBlockNestedPops` at the end to assign the `pop` to
a local right after the `catch`, making the code valid again:
```wast
(try
(do)
(catch $tag
(local.set $new ;; New local to store `pop` result
(pop i32)
)
(block $__inlined_func$callee
(local.set $0
(local.get $new)
)
(nop)
)
)
)
```
=> [EH] Handle nested pops after inlining

src/tools/fuzzing/random.cpp, test/unit/test_fuzz_empty_data.py
When a parameter and a member variable have the same name within a
constructor, to access (and change) the member variable, we need to
either use `this->` or change the name of the parameter. The current
code ended up changing the parameter and didn't affect the status of the
member variable, which remained empty.
=> [Fuzzer] Allow empty data in --translate-to-fuzz

src/wasm/wasm-type.cpp
Equirecursive canonicalization generates new minimal type definitions for each
distinct type, but then it must replace the old, non-minimial definitions with
the new ones. That second part where the types are replaced is not unique to
equirecursive canonicalization; the same replacement happens with BasicKind
types and in the future the hybrid isorecursive system will also need to do that
kind of replacement. To improve code reuse and separation of concerns, factor
the type replacement logic out into a separate utility.
This change slightly slows down shape canonicalization, but shape
canonicalization is still much faster than global canonicalization. Nominal
typing performance is not affected.
=> Factor out a utility for replacing types during canonicalization

src/wasm/wasm-binary.cpp
Without this we hit an assertion later, which is less clear.
See #4413
=> Add binary format parse check for imported function types

.git-blame-ignore-revs
Since version 2.23, git-blame has a feature to ignore certain commits. This feature is useful to ignore large formatting changes when blaming.
=> Adds support for blame ignore using ignoreRevsFile

.github/workflows/ci.yml, .github/workflows/create_release.yml
This allows them to run on both Intel and ARM hardware.
=> Build ARM64 MacOS releases

src/tools/wasm-ctor-eval.cpp
This logging is central to what this tool does, and not optional, so stdout
makes more sense I think. Also, as I'm re-integrating this on the emscripten
side, this makes it simpler.
=> [ctor-eval] Switch logging from stderr to stdout

src/binaryen-c.cpp
Since https://github.com/emscripten-core/emscripten/pull/15905 landed
emscripten now includes its own dummy atexit function when building with
EXIT_RUNTIME=0.
This dummy function conflicts with the emscripten-provided one:
```
wasm-ld: error: duplicate symbol: atexit
>>> defined in CMakeFiles/binaryen_wasm.dir/src/binaryen-c.cpp.o
>>> defined in ...wasm32-emscripten/lto/libnoexit.a(atexit_dummy.o)
```
Normally overriding symbols from libc does not causes issues but one
needs to be sure to override all the symbols in a given object file so
that the object in question (atexit_dummy.o) does not get linked in.  In
this case some other symbol being defined in in atexit_dummy.o (e.g.
__cxa_atexit) is likely the cause of the conflict.
Overriding symbols from libc is likely to break in this way …
=> Fix emscripten build by removing dummy atexit function

src/wasm/wasm-emscripten.cpp, test/lld/em_asm.cpp, test/lld/em_asm.wat, test/lld/em_asm.wat.mem.out, test/lld/em_asm.wat.out
As it happens, this doesn't (normally) break the resulting EM_ASM or
EM_JS strings because (IIUC) JS supports the tab literal inside of
strings as well as "\t".
However, it's better to preserve the original text so that it looks
the same in the JS file as it did in the original source.
=> Escape \t as well as \n when writing JSON output.

src/passes/SafeHeap.cpp, test/passes/safe-heap_start-function.txt, test/passes/safe-heap_start-function.wast
The `__wasm_memory_init` function is not always used as the start
function.  Sometimes it is just one of a sequence of functions that are
called from the start function.  In order to handle this case we can
instead avoid instrumenting the start function as well as any functions
call from it.
This fixes the SAFE_HEAP + USE_PTHREADS + MAIN_MODULE configuration
which is currently broken in emscripten.
=> SafeHeap: Avoid instrumenting functions directly called from the "start"

auto_update_tests.py, check.py, src/tools/wasm-ctor-eval.cpp, test/ctor-eval/results.wast, test/ctor-eval/results.wast.ctors, test/ctor-eval/results.wast.out, test/lit/help/wasm-ctor-eval.test
By default wasm-ctor-eval removes exports that it manages to completely
eval (if it just partially evals then the export remains, but points to a function
with partially-evalled contents). However, in some cases we do want to keep
the export around even so, for example during fuzzing (as the fuzzer wants
to call the same exports before and after wasm-ctor-eval runs) and also
if there is an ABI we need to preserve (like if we manage to eval all of
`main()`), or if the function returns a value (which we don't support yet, but
this is a PR to prepare for that).
Specifically, there is now a new option:
```
--kept-exports foo,bar
```
That is a list of exports to keep around.
Note that when we keep around an export after evalling the ctor we
make the export point to a new function. That new …
=> [ctor-eval] Add an option to keep some exports

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-bulk-memory.wast
I guess we could optimize even this cases like:
```rust
memory.copy(dst, src, 0)  ==>  { drop(i32.load8_u(dst)), drop(i32.load8_u(src)) }
``` 
i.e. adding one read each for source and destination pointers.
Same for `memory.fill`:
```rust
memory.fill(d, v, 0)  ==>  { drop(i32.load8_u(d)), drop(v) }
```
@kripken wdyt?
=> [OptimizeInstructions] Optimize zero sized bulk memory ops even without "ignoreImplicitTraps"

src/shell-interface.h, src/support/small_vector.h, src/tools/execution-results.h, src/tools/wasm-ctor-eval.cpp, src/tools/wasm-shell.cpp, src/wasm-interpreter.h, test/example/small_vector.cpp
`LiteralList` overlaps with `Literals`, but is less efficient as it is not a
`SmallVector`.
Add reserve/capacity methods to `SmallVector` which are now
necessary to compile.
=> LiteralList => Literals

src/wasm/wasm-type.cpp
Apparently constructing that object is expensive? And we call it very
frequently in the interpreter.
This is a 25% speedup on the benchmark in https://github.com/WebAssembly/binaryen/issues/4452
=> Add a fast path to isSubType

src/wasm/literal.cpp
Handle the `isBasic()` case first - that inlined function is very fast to call,
and it is the common case. Also, do not do unnecessary work there: just
write out what we need, instead of always doing a memcpy of 16 bytes.
This makes us over 2x faster on the benchmark in https://github.com/WebAssembly/binaryen/issues/4452
=> Optimize Literal constructors and destructor

src/literal.h
In the common case, avoid allocating a vector and calling malloc.
This makes us over 3x faster on the benchmark in https://github.com/WebAssembly/binaryen/issues/4452
=> Add fast paths for Literals::getType

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-bulk-memory.wast
Reverts WebAssembly/binaryen#4295
This optimization could introduce a new trap in cases where the destination address is out of bounds and the second operand to memory.fill could branch. In that case, the memory.fill in the original code would never have been executed but the first out-of-bounds load in the optimized code would be executed.
=> Revert "[OptimizeInstructions] Optimize zero sized bulk memory ops even without "ignoreImplicitTraps""

src/ir/CMakeLists.txt, src/ir/module-utils.cpp, src/ir/module-utils.h, src/ir/subtypes.h, src/ir/type-updating.cpp, src/ir/type-updating.h, src/passes/NameTypes.cpp, src/passes/Print.cpp, src/wasm-binary.h, src/wasm/wasm-binary.cpp
Move the code into a new .cpp file because it is too complicated for a header
and update the API to make both the type indices and optimized sorting optional.
It will become more important to avoid unnecessary sorting once isorecursive
types have been implemented because they will make the sorting more complicated.
=> Refactor ModuleUtils::collectHeapTypes

src/tools/tool-options.h, src/wasm-type.h, src/wasm/wasm-type.cpp, test/lit/help/wasm-as.test, test/lit/help/wasm-ctor-eval.test, test/lit/help/wasm-dis.test, test/lit/help/wasm-emscripten-finalize.test, test/lit/help/wasm-metadce.test, test/lit/help/wasm-opt.test, test/lit/help/wasm-reduce.test, test/lit/help/wasm-split.test, test/lit/help/wasm2js.test
Eventually this will enable the isorecursive hybrid type system described in
https://github.com/WebAssembly/gc/pull/243, but for now it just throws a fatal
error if used.
=> Add a `--hybrid` type system option

src/passes/SafeHeap.cpp, test/passes/safe-heap_start-function.txt, test/passes/safe-heap_start-function.wast
Since https://reviews.llvm.org/D117412 landed it has causes a bunch of
SAFE_HEAP tests in emscripten to start failing, because
`__wasm_apply_data_relocs` can now sometimes be called from with
`__wasm_init_memory` as opposed to directly from the start function.
=> SAFE_HEAP: Avoid annotating any function reachable from start function

.flake8, .github/workflows/ci.yml, .gitmodules, CMakeLists.txt, check.py, src/tools/CMakeLists.txt, test/example/type-builder.cpp, test/example/type-builder.txt, test/gtest/CMakeLists.txt, test/gtest/type-builder.cpp, third_party/CMakeLists.txt
Add gtest as a git submodule in third_party and integrate it into the build the
same way WABT does. Adds a new executable, `binaryen-unittests`, to execute
`gtest_main`. As a nontrivial example test, port one of the `TypeBuilder` tests
from example/ to gtest/.
Using gtest has a number of advantages over the current example tests:
- Tests are compiled and linked at build time rather than runtime, surfacing
errors earlier and speeding up test execution.
- Tests are all built into a single binary, reducing overall link time and
further reducing test overhead.
- Tests are built from the same CMake project as the rest of Binaryen, so
compiler settings (e.g. sanitizers) are applied uniformly rather than having
to be separately set via the COMPILER_FLAGS environment variable.
- Using the …
=> Introduce gtest

src/wasm/wasm-emscripten.cpp
There is no reason the `__stack_pointer` global can't be exported from
the module, and in fact I'm experimenting with a non-relocatable main
module that requires this.
See https://github.com/emscripten-core/emscripten/issues/12682
This heuristic still kind of sucks but should always be good enough
for llvm output that always puts the stack pointer first.
=> Update heuristic for finding `__stack_pointer` to allow exports. NFC

src/wasm-type.h, src/wasm/wasm-type.cpp, test/gtest/type-builder.cpp
Add a `destroyAllTypes` function to clear the global state of the type system
and use it in a custom gtest test fixture to ensure that each test starts and
ends with a fresh state.
=> Reset global type state between tests

src/support/parent_index_iterator.h, src/wasm-type.h, src/wasm/wasm-type.cpp, test/gtest/type-builder.cpp
Add a utility class for defining all the common operations like pre- and post-
increment and decrement, addition and subtraction, and assigning addition and
subtraction for iterators that are comprised of a parent object and an index
into that parent object. Use the new utility to reduce the boilerplate in
wasm-type.h. Add a new test of the iterator behavior.
=> Create `ParentIndexIterator` to reduce iterator boilerplate

src/passes/StackCheck.cpp, test/lld/basic_safe_stack.wat.out, test/lld/recursive_safe_stack.wat.out
This function call now takes the address (which by defintion is outside
of the stack range) that the program was attempting to set SP to.
This allows emscripten to provide a more useful error message on stack
over/under flow.
=> StackCheck: Add argument stack-check-handler call

src/ir/type-updating.cpp, src/tools/wasm-fuzz-types.cpp, src/wasm-type.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, src/wasm/wasm-type.cpp, test/example/type-builder-nominal.cpp, test/example/type-builder.cpp, test/gtest/type-builder.cpp
It is possible for type building to fail, for example if the declared nominal
supertypes form a cycle or are structurally invalid. Previously we would report
a fatal error and kill the program from inside `TypeBuilder::build()` in these
situations, but this handles errors at the wrong layer of the code base and is
inconvenient for testing the error cases.
In preparation for testing the new error cases introduced by isorecursive
typing, make type building fallible and add new tests for existing error cases.
Also fix supertype cycle detection, which it turns out did not work correctly.
=> Make `TypeBuilder::build()` fallible

src/passes/Asyncify.cpp
Rewrite `AsyncifyFlow.process` to use stack instead of recursive call.
This patch resolves https://github.com/WebAssembly/binaryen/issues/4401
I did not see significant performance regressions at my end for CRuby port.
```console
$ hyperfine "wasm-opt.old --asyncify --pass-arg=asyncify-ignore-imports -o miniruby.opt miniruby" "wasm-opt.new --asyncify --pass-arg=asyncify-ignore-imports -o miniruby.opt miniruby" --warmup 2
Benchmark #1: wasm-opt.old --asyncify --pass-arg=asyncify-ignore-imports -o miniruby.opt miniruby
Time (mean ± σ):      6.525 s ±  1.779 s    [User: 13.730 s, System: 0.800 s]
Range (min … max):    4.493 s …  9.517 s    10 runs
Benchmark #2: wasm-opt.new --asyncify --pass-arg=asyncify-ignore-imports -o miniruby.opt miniruby
Time (mean ± σ):      5.922 s ±  2.218 s …
```
=> Asyncify: Use stack instead of recursive call to avoid stack overflow

src/wasm-type.h, src/wasm/wasm-type.cpp, test/gtest/type-builder.cpp
When building isorecursive types, validate their relationships according to the
rules described in https://github.com/WebAssembly/gc/pull/243. Specifically,
supertypes must be declared before their subtypes to statically prevent cycles
and child types must be declared either before or in the same recursion group as
their parents.
=> Isorecursive type validation

src/ir/effects.h
In asm2wasm we modelled debugInfo using special imports. And we tried
to not move them around much. Current debugInfo is tracked on
instructions and is not affected by removing this.
This may have some tiny effect beneficial effect on code size in debug
builds, perhaps.
=> Remove old EffectAnalyzer hacks for asm.js debugInfo

src/wasm-interpreter.h
Add a base class for it, that is templated and can be extended in general
ways, and make `callFunction` templated on the runner to use as well.
This allows the interpreter's behavior to be customized in a way that we
couldn't so far. wasm-ctor-eval wants to use a special Runner when it
evals a function, so that it can track certain operations, which this will
enable.
=> [NFC] Templatize/generalize RuntimeExpressionRunner

src/wasm-type.h, src/wasm/wasm-type.cpp, test/gtest/type-builder.cpp
Storing the rec group index on the HeapTypeInfo avoids having to do a linear
scan through the rec group to find the index for a particular type. This will
be important for isorecursive canonicalization, which uses rec group indices.
=> Add a HeapType method for getting the rec group index

src/wasm/wasm-type.cpp, test/gtest/type-builder.cpp
Update the HeapType constructors that take Signature, Structs, and Arrays to
work properly with isorecursive typing. This is particularly important for the
Signature constructor, which is used frequently throughout the code base.
=> Isorecursive HeapType constructors

README.md
Add the missing initialization instructions to the `Building` section.
Fixes #4488.
=> Document submodule initialization in README

src/ir/module-utils.cpp, src/ir/module-utils.h, src/ir/type-updating.cpp, src/support/insert_ordered.h, src/wasm-type.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-type.cpp, test/lit/isorecursive-output-ordering.wast
Generally we try to order types by decreasing use count so that frequently used
types get smaller indices. For the equirecursive and nominal systems, there are
no contraints on the ordering of types, so we just have to sort them according
to their use counts. For the isorecursive type system, however, there are a
number of ordering constraints that have to be met for the type section to be
valid. First, types in the same recursion group must be adjacent so they can be
grouped together. Second, groups must be ordered topologically so that they only
refer to types in themselves or prior groups.
Update type ordering to produce a valid isorecursive output by performing a
topological sort on the recursion groups. While performing the sort, prefer to
visit and finish processing the most used …
=> Topological sorting of types in isorecursive output

test/gtest/type-builder.cpp
The IsorecursiveTest.CanonicalizeSelfReferences has been frequently failing on
Windows and MacOS CI. Disable it for now until I can investigate thoroughly.
=> Disable a flaky isorecursion test

src/wasm/wasm-validator.cpp
We can only call getHeapType if it is indeed a function type. Otherwise we should
show the error and move on.
=> Fix an assertion in the validator on call_ref heaptypes

src/wasm-binary.h, src/wasm/wasm-binary.cpp, test/lit/isorecursive-good.wast, test/lit/isorecursive-output-ordering.wast, test/lit/isorecursive-singleton-group.wast, test/lit/isorecursive-whole-group.wast
Write and parse recursion groups in binary type sections. Unlike in the text
format, where we ignore recursion groups when not using isorecursive types, do
not allow parsing binary recursion group when using other type systems. Doing so
would produce incorrect results because recursions groups only count as single
entries in the type system vector so we dynamically grow the TypeBuilder when we
encounter them. That would change the mapping of later indices to types, and
would change the meaning of previous type definitions that use those later
indices. This is not a problem in the isorecursive system because in that system
type definitions are not allowed to use later indices.
=> Isorecursive binary format

src/ir/module-utils.cpp
Using a vector and lazily skipping finished items in `pop` rather than using a
linked list and eagerly removing duplicated items makes the code simpler and
more than twice as fast on my test case. The algorithmic complexity is unchanged
because the work to skip duplicates remains linear in the number of duplicates
added, it's just not spread out over the linear duplicate pushes any more.
=> [NFC] Simplify TopologicalSortStack

src/ir/module-utils.cpp, src/support/topological_sort.h
Refactor the `TopologicalSortStack` into a `TopologicalSort` CRTP utility that
manipulates the DFS stack internally instead of exposing it to the user. The
only method users have to implement to use the utility is `pushPredecessors`,
which should call the provided `push` method on all the predecessors of a given
item. The public interface to `TopologicalSort` is an input iterator, so it can
easily be used in range-based for loops.
=> CRTP topological sort utility

src/wasm/wasm-type.cpp, test/gtest/type-builder.cpp
Validating nominally declared supertypes depends on being able to test type
equality, which in turn depends on the compared types having already been
canonicalized. Previously we validated supertypes before canonicalization, so
validation would fail in cases where it should have succeeded. Fix the bug by
canonicalizing first. This means that the global type store can now end up
holding invalid types, but those types will never be exposed to the user, so
that's not a huge problem.
Also fix an unrelated bug that was preventing the test from passing, which is
that supertypes were being hashed and compared without the special logic for
detecting self-references. This bug preventing the equivalent recursion groups
in the test from being deduplicated.
=> Validate supertypes after isorecursive canonicalization

src/wasm/wasm-type.cpp, test/gtest/type-builder.cpp
We were already eagerly canonicalizing basic HeapTypes when building types so
the more complicated canonicalization algorithms would not have to handle
noncanonical heap types, but we were not doing the same for Types. Equirecursive
canonicalization was properly handling noncanonical Types everywhere, but
isorecursive canonicalization was not. Rather than update isorecursive
canonicalization in multiple places, remove the special handling from
equirecursive canonicalization and canonicalize types in a single location.
=> Eagerly canonicalize basic types

src/tools/wasm-split/split-options.cpp, src/tools/wasm-split/split-options.h, src/tools/wasm-split/wasm-split.cpp, test/lit/help/wasm-split.test, test/lit/wasm-split/asyncify.wast
Add an option for running the asyncify transformation on the primary module
emitted by wasm-split. The idea is that the placeholder functions should be able
to unwind the stack while the secondary module is asynchronously loaded, then
once the placeholder functions have been patched out by the secondary module the
stack should be rewound and end up in the correct secondary function.
=> [wasm-split] Add an --asyncify option

src/tools/wasm-fuzz-types.cpp, src/wasm-type-printing.h, test/example/type-builder-nominal.cpp, test/gtest/type-builder.cpp
Allow IndexedTypeNameGenerator to be configured with a custom prefix and also
allow it to forward additional arguments to initializing its fallback generator.
This allows multiple IndexedTypeNameGenerators to be composed together, for
example.
=> Make IndexedTypeNameGenerator more powerful

src/pass.h, src/tools/optimization-options.h, test/lit/help/wasm-opt.test, test/lit/help/wasm2js.test
Also update two relevant tests.
#4285
=> #4285: Clarify that `-O` is equivalent to `-Os` in tools help message.

src/wasm/wasm-s-parser.cpp, test/lit/parse-bad-supertype.wast
Instead of just reporting the type index that causes an error when building
types, report the name of the responsible type when parsing the text format.
=> Include type names in error messages from building

src/ir/gc-type-utils.h, test/lit/passes/remove-unused-brs-gc.wast
We were missing this particular case, which we can in fact handle
when the cast is static.
Noticed by @jakobkummerow
=> [Wasm GC] Optimize static casts in br_on_cast*

CHANGELOG.md
We (the Grain team) ran into a funny thing when upgrading to Binaryen 102—we occasionally use tuples to use the wasm stack via a direct `BinaryenTupleExtract` on a `BinaryenTupleMake` to avoid managing an extra local. We support some runtimes that still don't have multivalue, but by never returning a tuple from an `if` or `block` we've avoided any actual use of multivalue in the generated binaries. The update to OptimizeInstructions allows the `BinaryenTupleExtract` to be pulled outside of an `if`, which makes the `if` actually return multiple values. We shouldn't have been abusing tuples in this way, but we figured we'd call it out in the changelog for anyone else who might have done the same 😅
=> Add CHANGELOG entry for v102 OptimizeInstructions

CMakeLists.txt, src/compiler-support.h, src/support/utilities.cpp, src/support/utilities.h, src/tools/tool-options.h, src/wasm-features.h
C++:
* use [[noreturn]] available since C++11 instead of compiler-specific attributes
* replace deprecated std::is_pod with is_trivial&&is_standard_layout (also available since C++11/14)
* explicitly capture this in [=] lambdas
* extra const functions in FeatureSet, fix ambiguous operator& call error
CMake:
* Use CMAKE_CXX_STANDARD set in the directory scope to set the default CXX_STANDARD for all targets
* The above made it unnecessary for the -std=c++17 flag to be passed directly in compiler options
* Explicitly disable vendor c++ standard extensions (GNU/MSVC) in directory scope as they are on by default in CMake
=> Fix errors when building in C++20 mode

CHANGELOG.md, CMakeLists.txt, README.md, check.py
Turning it off removes the build dependency on the third-party googletest
library.
=> Add BUILD_TESTS CMake option

CHANGELOG.md, requirements-dev.txt, test/lit/wasm-split/basic.wast
This update includes a
[fix](https://github.com/mull-project/FileCheck.py/pull/188) to how the
filecheck Python package matches whitespace to more closely match the behavior
of upstream filecheck in LLVM. We have one test affected by this change, so all
users who run the test suite will have to update their installed filecheck. This
can be done via
```
pip3 install -r requirements-dev.txt
```
=> Update filecheck to 0.0.22

test/gtest/type-builder.cpp, test/gtest/type-test.h
Allow the fixture to be shared with other test .cpp files we might add in the
future.
=> [NFC] Move type system test fixture to its own header

src/passes/DeadArgumentElimination.cpp
I believe this old code was written before we had LocalGraph. It does a flow
analysis to see if the values arriving in parameters are actually used, but
there is no reason to do it manually since we have LocalGraph now which
makes that trivial, as it matches the values for each get, so we can just check
if any get can read the param's incoming value.
=> [NFC] Refactor DeadArgumentElimination code to use LocalGraph

src/ir/possible-constant.h, src/passes/ConstantFieldPropagation.cpp
This just moves `PossibleConstantValues` to a new separate file
(as a preparation for other passes using it too).
=> [NFC] Refactor constant argument finding code

third_party/CMakeLists.txt
=> Do not build gtest libs unless BUILD_TESTS is set

src/ir/struct-utils.h, src/ir/type-updating.cpp, src/passes/GlobalTypeOptimization.cpp, test/lit/passes/gto-removals.wast
Previously we'd remove a field from a type if that field has no uses in any
sub- or super-type. In that case we'd remove it from all the types at once.
However, there is a case where we can remove a field only from a parent
but not from its children, if the field is at the end: if `A` has fields `{x, y, z}`
and its subtype `B` has fields `{x, y, z, w}`, and `A` pointers only access
field `y` while `B` pointers access all the fields, then we can remove `z`
from `A`. Removing it from the end is safe, and then `B` will not only add
`w` as it did before but also add `z`. Note that we cannot remove `x`,
because it is not at the end: removing it from just `A` but not `B` would
shift the indexes, making them incompatible.
=> [Wasm GC] GlobalTypeOptimization: Remove fields from end based on subtypes

src/tools/wasm-shell.cpp, src/wasm-features.h, test/binaryen.js/kitchen-sink.js.txt, test/example/c-api-kitchen-sink.txt
As we recently noted in #4555, that `Feature::All` and `FeatureSet.setAll()`
are different is potentially confusing...
I think the best thing is to make them identical. This does that, and adds a
new `Feature::AllPossible` which is everything possible and not just the
set of all features that are enabled by `-all`.
This undoes part of #4555 as now the old/simpler code works properly.
=> [NFC] Refactor Feature::All to match FeatureSet.setAll()

.github/workflows/ci.yml
To help debug them when they go wrong, as seems to be happening on #4574.
=> Add '-vv' verbosity to binaryen-lit tests

src/cfg/liveness-traversal.h, test/lit/passes/coalesce-locals-gc-nn.wast, test/lit/passes/coalesce-locals-gc.wast
Normally we just replace unreachable `local.get`s with a constant (0, or null), but if
the local is non-nullable we can't do that.
Fixes #4573
=> [Wasm GC] Fix unreachable local.gets of non-nullable locals in CoalesceLocals

test/gtest/type-builder.cpp
I don't know what exactly was causing this test to flake, but since it was
disabled we added the type fuzzer and fixed a lot of bugs, so I hope it is no
longer flaky. If that turns out to be wrong, I can dig deeper.
=> Re-enable a previously flaky type test

scripts/gen-s-parser.py, src/binaryen-c.cpp, src/binaryen-c.h, src/gen-s-parser.inc, src/ir/cost.h, src/js/binaryen.js-post.js, src/passes/Print.cpp, src/tools/fuzzing/fuzzing.cpp, src/wasm-interpreter.h, src/wasm.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-stack.cpp, src/wasm/wasm-validator.cpp, test/example/c-api-kitchen-sink.c
Other opcode ends with `Inxm` or `Fnxm` (where n and m are integers),
while `i8x16.swizzle`'s opcode name doesn't have an `I` in there.
=> [SIMD] Make swizzle's opcode name consistent (NFC)

src/passes/Inlining.cpp, test/lit/passes/inlining_enable-tail-call.wast
We can preserve return_calls in inlined functions when the inlined call site is
itself a return_call, since the call result types must transitively match in
that case. This solves a problem where the previous inlining logic could
introduce stack exhaustion by downgrading recursive return_calls to normal
calls.
Fixes #4587.
cc @ospencer
=> [Inlining] Preserve return_calls when possible

scripts/gen-s-parser.py, src/gen-s-parser.inc, src/ir/cost.h, src/literal.h, src/passes/Print.cpp, src/wasm-binary.h, src/wasm-interpreter.h, src/wasm.h, src/wasm/literal.cpp, src/wasm/wasm-binary.cpp, src/wasm/wasm-stack.cpp, src/wasm/wasm-validator.cpp, test/lit/relaxed-simd.wast
As proposed in https://github.com/WebAssembly/relaxed-simd/issues/52.
=> Implement relaxed SIMD dot product instructions

test/gtest/type-builder.cpp
Reverts WebAssembly/binaryen#4582.
This test is still sporadically failing on at least the mac builder.
=> Revert "Re-enable a previously flaky type test"

src/wasm-builder.h
I noticed this bug when running the reducer (it crashed the reducer internally).
=> [NominalFuzzing] Fix replaceWithIdenticalType() on nondefaultable tuples

src/tools/execution-results.h
The same module will have a different type after some transformations, even
though that is not observable, like `--roundtrip`. Basically, we should not be
comparing types between separate modules, which is what the fuzzer does.
=> [NominalFuzzing] Don't compare nominal types in the fuzzer

src/tools/fuzzing/fuzzing.cpp
Randomly selecting a depth is ok for structural typing, but in nominal it
must match the actual hierarchy of types.
=> [NominalFuzzing] Fix TranslateToFuzzReader::getSubType(Rtt)

src/wasm/wasm-validator.cpp
`(ref.cast func (..))` for example is not allowed (and the binary format emitter will
crash when it looks for the heap type index).
=> [NominalFuzzing] Add a validation error on ref.cast's intended type

src/passes/GlobalTypeOptimization.cpp, test/lit/passes/gto-removals.wast
When a field has no reads, we remove all its writes, but we did this:
```wat
(struct.set $foo A B)
=>
(drop A) (drop B)
```
We also need to trap if `A`, the reference, is null, which this PR
fixes,
```wat
(struct.set $foo A B)
=>
(drop (ref.as_non_null A)) (drop B)
```
=> [NominalFuzzing] GTO: trap on null ref in removed struct.set

src/ir/module-utils.cpp, test/lit/passes/signature-pruning.wast
The cast instruction may be unreachable but the intended type for the cast
still needs to be collected. Otherwise we end up with problems both during
optimizations that look at heap types and in printing (which will use the heap
type in code but not declare it).
Diff without whitespace is much smaller: this just moves code around so
that we can use a template to avoid code duplication. The actual change
is just to scan `->intendedType` unconditionally, and not ignore it if the
cast is unreachable.
After this nominal fuzzing reaches 93K iterations without an issue, so
things may be getting more stable...
=> [NominalFuzzing] Fix getHeapTypeCounts() on unreachable casts

src/ir/export-utils.h, src/passes/SignatureRefining.cpp, test/lit/passes/signature-refining.wast
This hits the fuzzer when it tries to call reference exports with a null.
=> [NominalFuzzing] SignatureRefining: Ignore exported functions

scripts/fuzz_opt.py
This adds a parameter `NOMINAL` in the fuzzer, turns it on by default, and
applies `--nominal` when it is active. It also adds all the new GC passes to
the list of fuzzable passes.
This should be ready to land once #4601 #4609 do, as with them and all
the other recent PRs I ran the fuzzer overnight for well over 100,000 iterations
without issues.
=> [NominalFuzzing] Switch to nominal fuzzing by default

src/support/small_set.h
We already assume the parent does not change,
https://github.com/WebAssembly/binaryen/blob/94d77efa788b46ec3d245fd0e180163877fe2a88/src/support/small_set.h#L202-L208
This also marks the parent as const to reflect that.
This fixed a weird C++ compilation error I had when working on
something unrelated, but seems worth landing independently.
=> SmallSet: Mark iterator parent as const

scripts/foreach.py
This is probably not the right fix, but it's been extremely useful for me locally. With this change, the auto-update script will print out a failing module, which is nice if the failing module was one out of dozens in a single file - without this change, there is no hint as to which of the modules failed, just the filename.
I suspect this is wrong as it stops at the first failing module, but we don't want that for the check script, I assume. If this is the right direction I could look into fixing that part.
=> Lit tests: print failing modules

src/passes/GlobalTypeOptimization.cpp, src/passes/TypeRefining.cpp
* We implemented specialization of field types (the TypeRefining pass).
* LUBFinder now handles nulls, so we need nothing extra for it in TypeRefining.
=> [NFC] Fix some outdated comments

src/ir/module-utils.cpp, src/ir/module-utils.h, src/passes/SignatureRefining.cpp
Normally ParallelFunctionAnalysis is just an analysis, and has no effects. However, in
SignatureRefining we actually do have side effects, due to an internal limitation of the
helper code it runs. This adds a template parameter to the class so users can note that
they do modify the IR. The parameter is added in the middle as it is easier to add this
param than to add the last one (the map).
=> [NominalFuzzing] SignatureRefining can modify the IR while running a parallel analysis

src/wasm-binary.h, src/wasm/wasm-binary.cpp, test/lit/nominal-to-isorecursive.wast
Print subtype declarations using the standards-track format with a vector of
supertypes followed by a normal type declaration rather than our interim nominal
format that used alternative versions of the func, struct, and array forms.
Desugar the nominal format to additionally emit all the types into a single
large recursion group. Currently V8 is performing this desugaring, but after
this change and a future change that fixes the order of nominal types to ensure
supertypes precede subtypes, it will no longer need to.
=> Update the type section binary format

scripts/fuzz_opt.py
Instead of a raw run command, use the helper function, which adds the
feature flags. That adds `--nominal` which is needed more now after #4625 
This fixes the fuzz failures mentioned in https://github.com/WebAssembly/binaryen/pull/4625#issuecomment-1115033311
=> [NominalFuzzing] Use feature flags in a missing place

src/passes/ExtractFunction.cpp
This makes a build on Windows fail with `Errors : 'isdigit': is not a member of 'std'`
=> Missing include

src/ir/module-utils.cpp, test/lit/lub-bug-3843.wast, test/lit/nominal-chain.wast, test/lit/parse-nominal-types-extends.wast, test/lit/parse-nominal-types.wast, test/lit/passes/cfp.wast, test/lit/passes/dae-gc-refine-params.wast, test/lit/passes/dae-gc-refine-return.wast, test/lit/passes/gto-mutability.wast, test/lit/passes/gto-removals.wast, test/lit/passes/optimize-instructions-gc-iit.wast, test/lit/passes/signature-refining.wast, test/lit/passes/type-refining.wast
V8 requires that supertypes come before subtypes when it parses
isorecursive (i.e. standards-track) type definitions. Since 2268f2a we are
emitting nominal types using the standard isorecursive format, so respect the
ordering requirement.
=> Update nominal type ordering

.github/workflows/create_release.yml
Without this the CMake step fails on not finding
`googletest/googletest/src/gtest_main.cc`
Fixes #4639 
This won't be tested in this PR. What's the best way to test it? Make a fake release I guess?
=> Setup git submodules so googletest is fetched, unbreaking alpine in releases

src/tools/fuzzing/fuzzing.cpp, test/passes/translate-to-fuzz_all-features_metrics_noprint.txt
1. Don't emit "`i31`" or "`data`" if GC is not enabled, as only the GC feature adds those.
2. Don't emit "`any`" without GC either. While it is allowed, fuzzer limitations prevent
this atm (see details in comment - it's fixable).
Not sure why this wasn't noticed before, I guess we were just lucky...
=> Fix fuzzer's choosing of reference types

scripts/fuzz_opt.py
`wasm-dis` does enable all features by default, so we don't need the
feature flags, but we do need `--nominal` etc. since we emit such
modules now.
=> [NominalFuzzing] Add typesystem flag to wasm-dis

src/ir/branch-utils.h
A null target is not a valid name so nothing can branch to there. This just
saves the wasted work.
No existing code in the codebase benefits from this atm, but a later PR
will. In particular this lets callers call this without checking if the name
is non-null, which is more concise.
=> [NFC] Avoid scanning code in hasBranchTarget if the target is null

scripts/fuzz_opt.py
Without this the reduction will fail on not being able to
parse the input file, if the input file depends on
nominal typing.
=> [Fuzzer] Add typesystem flag to reduction script

src/tools/fuzzing/fuzzing.cpp, test/passes/translate-to-fuzz_all-features_metrics_noprint.txt
We can't emit `HeapType::data` without GC. Fixing that by switching to `func`,
another problem was uncovered: `makeRefFuncConst` had a TODO to handle
the case where we need a function to refer to but have created none yet. In
fact that TODO was done at the end of the function. Fix up the logic in
between to actually get there.
=> [Fuzzer] Fix another reference types vs gc types issue

CMakeLists.txt
Adds `BUILD_TOOLS` flag that can be disabled to build just the library. Saves time and storage space for developers who need only the library. Is set to `ON` by default
=> Add option to disable building tools

src/passes/SignaturePruning.cpp, test/lit/passes/signature-refining.wast
Do not prune parameters if there is a supertype that is a signature.
Without this we crash on an assertion in TypeBuilder when we try to
recreate the types (as we try to make a a subtype with fewer fields
than the super).
=> [NominalFuzzing] Fix SignaturePruning on types with a super

src/ir/cost.h, src/passes/RemoveUnusedBrs.cpp, test/lit/passes/remove-unused-brs-gc.wast
Casts involve branches in the VM, so adding a cast in return for removing a branch
(like If=>Select) is not beneficial. We don't want to ever do any more casts than we
already are.
=> Costs: Increase cost of casts

src/wasm.h
This prevents new `RefCast` expressions that don't explicitly have their safety
set from getting an unitialized safety value.
=> Make RefCast safe by default

src/binaryen-c.cpp, src/literal.h, src/wasm-interpreter.h, src/wasm/literal.cpp
Taking a Type is redundant as we only care about the heap type -
the nullability must be Nullable.
This avoids needing an assertion in the function, that is, it makes
the API more type-safe.
=> [NFC] Make Literal::makeNull take a HeapType

src/ir/possible-constant.h, test/lit/passes/dae-gc.wast
Previously we could return different results depending on the order we
noted things:
```js
note(anyref.null);
note(funcref.null);
get() => anyref.null
note(funcref.null);
note(anyref.null);
get() => funcref.null
```
This is correct, as nulls are equal anyhow, and any could be used in
the location we are optimizing. However, it can lead to nondeterminism
if the caller's order of notes is nondeterministic. That is the case in
DeadArgumentElimination, where we scan functions in parallel, then
merge them without special ordering.
To fix this, make the note operation symmetric. That seems simplest and
least likely to be confusing. We can use the LUB to do that.
To avoid duplicating the null logic, refactor `note()` to use `combine()`.
=> Ensure symmetric results in PossibleConstantValues

src/wasm/wasm-type.cpp, test/gtest/type-builder.cpp
There's no reason not to allow growing by zero slots, but previously doing so
would trigger an assertion. This caused a crash when roundtripping a trivial
module.
Fixes #4667.
=> Allow TypeBuilder::grow to take 0 as an argument

src/support/insert_ordered.h
Being a const reference allows writing `insert({a, b})`, which will be
useful in a future PR, and there is no reason to actually update the
reference.
=> [NFC] Make InsertOrderedMap::insert's param const

src/tools/wasm-reduce.cpp
The old code would short-circuit and not do anything after we managed
any reduction in the loop here. That would end up doing entire iterations of
the whole pipeline before removing another element segment, which could
be slow.
=> wasm-reduce: Fix order in shrinkByReduction call

src/tools/fuzzing/fuzzing.cpp, src/wasm/wasm-validator.cpp, test/lit/validation/eqref.wast
Yet another case of this. `eq` only requires reference types, so we can't
unconditionally pick `i31` or `data` as subtypes of it, we need GC to be
enabled.
=> Validator: Check features for ref.null's type

src/wasm/wasm-binary.cpp, test/lit/binary/prototype-nominal-format.test
We were checking that nominal modules only had a single element in their type
sections, but that's not correct for the prototype nominal binary format we
still want to support. The test for this missed catching the bug because it
wasn't actually parsing in nominal mode.
=> Fix binary parsing of the prototype nominal format

README.md
The wasm-opt example was using a test pass that was deleted. Updating to use one of the test passes in test/lit/passes.
=> Updating wasm-opt example to an available pass

scripts/fuzz_opt.py
If we use it as initial contents, we will try to execute it, and hit the TODOs
in the interpreter for unimplemented parts.
=> [Fuzzer] Ignore relaxed-simd test for initial contents

src/cfg/cfg-traversal.h, src/wasm/wasm-validator.cpp, test/lit/validation/nn-locals-bad-call_ref.wast, test/lit/validation/nn-locals-bad.wast, test/lit/validation/nn-locals-ok.wast
We were missing `CallRef` in the CFG traversal code in a place where we
note possible exceptions. As a result we thought `CallRef` cannot throw, and
were missing some control flow edges.
To actually detect the problem, we need to validate non-nullable locals
properly, which we were not doing. This adds that as well.
This could be split into two PRs if we prefer, one to add validation, and one
to add the CFG fix, but then full testing would only arrive with the second.
Happy to do that if we prefer, but OTOH this PR is fairly small.
Fixes #4689
cc @askeksa-google
=> [Wasm GC] Fix CFG traversal of call_ref and add missing validation check

src/wasm/wat-parser-internal.h, test/gtest/wat-parser.cpp
Also include reserved words that look like keywords to avoid having to find and
enumerate all the valid keywords. Invalid keywords will be rejected at a higher
level in the parser instead.
=> [Parser] Lex keywords

src/wasm/wat-parser-internal.h, test/gtest/wat-parser.cpp
Rather than trying to actually implement the parsing of float values, which
cannot be done naively due to precision concerns, just parse the float grammar
then postprocess the parsed text into a form we can pass to `strtod` to do the
actual parsing of the value.
Since the float grammar reuses `num` and `hexnum` from the integer grammar but
does not care about overflow, add a mode to `LexIntCtx`, `num`, and `hexnum` to
allow parsing overflowing numbers.
For NaNs, store the payload as a separate value rather than as part of the
parsed double. The payload will be injected into the NaN at a higher level of
the parser once we know whether we are parsing an f64 or an f32 and therefore
know what the allowable payload values are.
=> [Parser] Lex floating point values

src/wasm/wat-parser-internal.h, test/gtest/wat-parser.cpp
Improve comments and variable names to make it clear that we allocate and build
a separate string only when necessary to handle escape sequences.
=> [Parser][NFC] Clarify escaped string lexing

src/wasm/CMakeLists.txt, src/wasm/wat-lexer.cpp, src/wat-lexer.h, test/gtest/CMakeLists.txt, test/gtest/wat-lexer.cpp
wat-parser-internal.h was already quite large after implementing just the lexer,
so it made sense to rename it to be lexer-specific and start a new file for the
higher-level parser. Also make it a proper .cpp file and split the testable
interface out into wat-lexer.h.
=> [Parser][NFC] Create a public wat-lexer.h header

src/wasm/wat-lexer.cpp, src/wat-lexer.h, test/gtest/wat-lexer.cpp
Previously we were tracking whether integer tokens were signed but we did not
differentiate between positive and negative signs. Unfortunately, without
differentiating them, there's no way to tell the difference between an in-bounds
negative integer and a wildly out-of-bounds positive integer when trying to
perform bounds checks for s32 tokens. Fix the problem by tracking not only
whether there is a sign on an integer token, but also what the sign is.
=> [Parser] Replace Signedness with ternary Sign

src/tools/wasm-emscripten-finalize.cpp, src/wasm-emscripten.h, src/wasm/wasm-emscripten.cpp
This part to finalize is currently not used and was added in preparation
for https://reviews.llvm.org/D75277.
However, the better solution to dealing with this alternative name for
main is on the emscripten side.  The main reason for this is that
doing the rename here in binaryen would require finalize to always
re-write the binary, which is expensive.
=> Remove renameMainArgcArgv from wasm-emscripten-finalize

src/wasm/wasm-emscripten.cpp, test/lld/basic_safe_stack.wat.out, test/lld/duplicate_imports.wat.out
The first way to should detect this is if the main function actually
doesn't take any params.   They we fallback to looking deeper.
In preparation for https://reviews.llvm.org/D75277
=> wasm-emscripten-finalize: Improve detection of mainReadsParams

src/passes/SimplifyLocals.cpp, test/lit/passes/simplify-locals-gc-nn.wast
Followup to #4703, this also handles the case where there is a non-
nullable local.set in the value of a nullable one, which we also cannot
optimize.
Fixes #4702 
cc @askeksa-google
=> [WasmGC] Fix try-catch and non-nullable local sets in values in SimplifyLocals

src/ir/eh-utils.cpp, src/ir/eh-utils.h, src/wasm/wasm-validator.cpp
This moves it out of the validator so it can be used elsewhere. It will be
used in https://github.com/WebAssembly/binaryen/pull/4685#discussion_r883983340
=> [NFC] Refactor EHUtils::findPops() method

src/wasm/wat-lexer.cpp, src/wat-lexer.h, test/gtest/wat-lexer.cpp
Add methods to `Token` for determining whether the token can be interpreted as a
particular token type, returning the interpreted value as appropriate. These
methods perform additional bounds checks for integers and NaN payloads that
could not be done during the initial lexing because the lexer did not know what
the intended token type was. The float methods also reinterpret integer tokens
as floating point tokens since the float grammar is a superset of the integer
grammar and inject the NaN payloads into parsed NaN values.
=> [Parser] Token classification

src/tools/fuzzing/fuzzing.cpp
#4659 adds a testcase with an import of `(ref $struct)`. This could cause an error in
the fuzzer, since it wants to remove imports (because the various fuzzers cannot pass
in custom imports - they want to just run the wasm). When it tries to remove that
import it tries to create a constant for a struct reference, and fails. To fix that, add
enough support to create structs and arrays at least in the simple case where all their
fields are defaultable.
=> Fuzzer: Add support for creating structs and arrays in makeConst

src/passes/GlobalStructInference.cpp, test/lit/passes/gsi.wast
In GSI we look for a read of a global in a situation like this:
```wat
$global1: value1
$global2: value2
(struct.get $Type (ref))
```
If global inference shows this get must be of either `$global1` or `$global2`, then we
can optimize to this:
```
(ref) == $global1 ? value1 : value2
```
We focus on the case of two values because 1 is handled by other passes, and >2
makes the tradeoffs less clear.
However, a simple extension is the case where there are more than 2 globals, but
there are only two values, and one value is unique to one global:
```wat
$global1: valueA
$global2: valueB
$global3: valueA
=>
(ref) == $global2 ? valueB : valueA
```
We can still use a single comparison here, on the global that has the
unique value. Then the else will handle all the other globals.
This increases the …
=> GlobalStructInference: Handle >2 globals if values coincide

src/wasm/wat-parser.cpp, test/lit/wat-kitchen-sink.wast
Begin implementing the second phase of parsing, parsing of type definitions.
Extend `valtype` to parse both user-defined and built in ref types, add `type`
as a top-level module field, and implement parsers for params, results, and
functype definitions.
=> [Parser] Parse function types

src/passes/SignatureRefining.cpp, test/lit/passes/signature-refining.wast
Spec and VM support for that is not yet stable (atm VMs do not allow complex user-
defined types to be passed around).
=> SignatureRefining: Do not refine types of imported functions

src/passes/pass.cpp
This pass helps on at least one Java microbenchmark in a clear way. Real-world data
is mixed, with no obvious benefit. But it does optimize 819 callsites on the real-world
14 MB J2Wasm binary, so we may find it helps if/when we run into those code paths.
On that binary (the biggest we have for GC) this pass runs in 0.12 seconds, so there
is very little downside to enabling it. It is a fast linear-time operation.
=> Enable GlobalStructInference by default

CHANGELOG.md
See https://github.com/WebAssembly/binaryen/issues/4730 for a recent possible user report.
=> Add changelog entry for --zero-filled-memory / 3306

src/wasm/wat-parser.cpp, test/lit/wat-kitchen-sink.wast
Parse struct and array type definitions along with field names. Only the most
basic definitions are parsed for now; subtype definitions (both nominal
prototype and standard formats) and recursion groups are left to follow-on PRs.
Since there is no official standard for the text format for GC type definitions,
attempt to define a grammar that allows abbreviations that we already use
widely, such as making `(field ... )` optional except for named fields.
=> [Parser] Parse struct and array types

scripts/fuzz_opt.py
Instead, to print opts as row-based, I propose switch to column-based output for better readability:
```
...
randomized feature opts: 
--all-features
--nominal
--disable-mutable-globals
--disable-nontrapping-float-to-int
--disable-simd
--disable-bulk-memory
--disable-multivalue
--disable-memory64
--disable-typed-function-references
--disable-extended-const
randomized settings (NaNs, OOB, legalize): False True True
randomized opts: 
--duplicate-function-elimination
--rse
--shrink-level=3
-fimfs=99999999
...
```
=> [fuzz-opt] Pretty print of feature opts

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-gc-tnh.wast
#4748 regressed us in some cases, because it removed casts first:
```wat
(ref.is_func
(ref.as_func
(local.get $anyref)))
```
If the cast is removed first, and the local has no useful type info, then
we'd have removed the cast but could not remove the `ref.is`. But
the `ref.is` could be optimized to 1, as it must be a func - the type
info proves it thanks to the cast. To avoid this, remove casts after
everything else.
=> [WasmGC] OptimizeInstructions: Improve RefIs cast ordering

src/js/binaryen.js-post.js, test/binaryen.js/kitchen-sink.js, test/binaryen.js/kitchen-sink.js.txt
When trying to implement some tests in Binaryen.ml, @ospencer encountered an issue where `getMemorySegmentInfoByIndex` throws if the segment is passive. This happens because the helper function was trying to *always* read the offset, even if it isn't a valid operation.
This just re-orders the calls and defaults `offset` to null for passive segments.
I want to make a follow-up PR that allows Binaryen.ml to use these utilities individually, but this is the quickest fix.
=> fix: Avoid trying to read offset if segment is passive

src/passes/Print.cpp, test/exception-handling.wast, test/exception-handling.wast.from-wast, test/exception-handling.wast.fromBinary, test/exception-handling.wast.fromBinary.noDebugInfo
`controlFlowDepth` is a variable used to print `delegate`'s target. When
printing nested blocks, we increase `controlFlowDepth` by the number of
nested blocks at once. But we should decrement it as we finish each
block, rather than decrease by the number of nested blocks at once,
because we need correct `controlFlowDepth` within nested blocks.
=> [EH] Fix printing bug in nested blocks + delegate

scripts/fuzz_opt.py, src/passes/ConstantFieldPropagation.cpp, src/passes/GlobalRefining.cpp, src/passes/GlobalStructInference.cpp, src/passes/GlobalTypeOptimization.cpp, src/passes/SignaturePruning.cpp, src/passes/SignatureRefining.cpp, src/passes/TypeRefining.cpp, src/tools/tool-options.h, test/lit/nominal-no-gc.wast
Nominal types don't make much sense without GC, and in particular trying to emit
them with typed function references but not GC enabled can result in invalid
binaries because nominal types do not respect the type ordering constraints
required by the typed function references proposal. Making this change was
mostly straightforward, but required fixing the fuzzer to use --nominal only
when GC is enabled and required exiting early from nominal-only optimizations
when GC was not enabled.
Fixes #4756.
=> Disallow --nominal with GC

src/passes/Print.cpp, src/wasm/wasm-type.cpp, test/lit/strings.wast
As suggested in #4755
It doesn't look like there's an obvious way to share this code. Perhaps `TypePrinter`
could be in a header and used from `Print`?
=> [Strings] Print shorthand types where possible

scripts/fuzz_opt.py
#4758 regressed the determinism fuzzer. First, `FEATURE_OPTS` is not a
list but a string. Second, as a hack another location would add `--strip-dwarf`
to that list, but that only works in `wasm-opt`. To fix that, remove the hack
and instead just ignore DWARF-containing files.
=> Fuzzer: Fix determinism fuzzing

scripts/gen-s-parser.py, src/gen-s-parser.inc, src/ir/ReFinalize.cpp, src/ir/cost.h, src/ir/effects.h, src/ir/possible-contents.cpp, src/passes/Print.cpp, src/wasm-binary.h, src/wasm-builder.h, src/wasm-delegations-fields.def, src/wasm-delegations.def, src/wasm-interpreter.h, src/wasm-s-parser.h, src/wasm.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, src/wasm/wasm-stack.cpp, src/wasm/wasm.cpp, src/wasm2js.h, test/lit/strings.wast
I considered maybe making this a shared class with `RefEq`. They are quite similar. But the internal opcode would need to be something like "compare references" versus "compare data", which seems slightly awkward. Overall the amount of boilerplate per new class is fairly small now, so I lean towards that.
=> [Strings] string.eq

scripts/gen-s-parser.py, src/gen-s-parser.inc, src/passes/Print.cpp, src/wasm-binary.h, src/wasm.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-stack.cpp, test/lit/strings.wast
This implements it as a StringMeasure opcode. They do have the same number of
operands, same trapping behavior, and same return type. They both get a string and
do some inspection of it to return an `i32`. Perhaps the name could be `StringInspect`
or something like that, rather than `StringMeasure`..? But I think for now this might be
good enough, and the spec may change anyhow later.
=> [Strings] string.is_usv_sequence

src/ir/bits.h, src/ir/boolean.h, src/ir/properties.h, src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-gc.wast
This marks all reference operations that return 0/1 as doing so. This
allows various bitwise operations to be optimized on them.
This also marks StringEq as a boolean, though we can't test that fully yet
as Strings support is wip (no interpreter or other stuff yet).
As a driveby this moves `emitsBoolean` to its own file, and uses it
in `getMaxBits` to avoid redundancy (the redundant code paths now have
a `WASM_UNREACHABLE`). I could do that in a prior PR if you prefer but it
seems trivial?
This removes 14% of all `select` operations on j2wasm. Those selects
are `x ? 1 : 0` which we turn into `x` if the input is already a boolean.
=> [Wasm GC] RefIs / RefEq / RefTest all return a boolean

scripts/gen-s-parser.py, src/gen-s-parser.inc, src/wasm/wat-parser.cpp, test/lit/wat-kitchen-sink.wast
Update gen-s-parser.py to produce a second version of its parsing code that
works with the new wat parser. The new version automatically replaces the `s`
element argument in the existing parser with the `ctx` and `in` arguments used
by the new parser, so adding new instructions will not require any additional
work in gen-s-parser.py after this change.
Also add stub `make***` functions to the new wat parser, with a few filled out,
namely `makeNop`, `makeUnreachable`, `makeConst`, and `makeRefNull`. Update the
`global` parser to parse global initializer instructions and update
wat-kitchen-sink.wast to demonstrate that the instructions are parsed correctly.
Adding new instruction classes will require adding a new `make***` function to
wat-parser.cpp in additional to wasm-s-parser.{h,cpp} …
=> [Parser] Start to parse instructions

src/wasm/wat-parser.cpp, src/wat-parser.h
The parser functions previously both parsed the input and controlled what was
done with the results using `constexpr` if-else chains. As the number of parsing
contexts grew, these if-else chains became increasingly complex and distracting
from the core parsing logic of the parsing functions.
To simplify the code, refactor the parsing functions to replace the `constexpr`
if-else chains with unconditional calls to methods on the context. To avoid
duplicating most method definitions for multiple parsing contexts, introduce new
utility contexts that implement common methods and (ab)use inheritance and
multiple inheritance to reuse their methods from the main parsing contexts.
This change will also make it easier to reuse the parser code for entirely
different purposes in the future by …
=> [Parser][NFC] Refactor to use context callbacks

scripts/gen-s-parser.py, src/gen-s-parser.inc, src/ir/ReFinalize.cpp, src/ir/cost.h, src/ir/effects.h, src/ir/possible-contents.cpp, src/passes/Print.cpp, src/wasm-binary.h, src/wasm-builder.h, src/wasm-delegations-fields.def, src/wasm-delegations.def, src/wasm-interpreter.h, src/wasm-s-parser.h, src/wasm.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, src/wasm/wasm-stack.cpp, src/wasm/wasm.cpp, src/wasm/wat-parser.cpp, src/wasm2js.h, test/lit/strings.wast
`stringview`s have a variety of access types based on what they are: wtf8 can
only advance forward as it reads, wtf16 only random access, and `iter` can iterate in any
direction. I think it's best to merge all these into a single class for simplicity.
=> [Strings] stringview access operations

src/ir/ordering.h, src/passes/GlobalTypeOptimization.cpp, test/lit/passes/gto-removals.wast
Minor fuzz bug. When we replace a `struct.set` with its children we also
add a `ref.as_non_null` on the reference, but that must not occur before
effects in the other child.
=> [Wasm GC] GTO should not reorder trapping of removed sets

scripts/gen-s-parser.py, src/gen-s-parser.inc, src/ir/ReFinalize.cpp, src/ir/cost.h, src/ir/effects.h, src/ir/possible-contents.cpp, src/passes/Print.cpp, src/wasm-binary.h, src/wasm-builder.h, src/wasm-delegations-fields.def, src/wasm-delegations.def, src/wasm-interpreter.h, src/wasm-s-parser.h, src/wasm.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, src/wasm/wasm-stack.cpp, src/wasm/wasm.cpp, src/wasm/wat-parser.cpp, src/wasm2js.h, test/lit/strings.wast
Unfortunately one slice is the same as python `[start:end]`, using 2 params,
and the other slice is one param, `[CURR:CURR+num]` (where CURR is implied
by the current state in the iter). So we can't use a single class here. Perhaps
a different name would be good, like `slice` vs `substring` (like JS does), but
I picked names to match the current spec.
=> [Strings] stringview_*.slice

scripts/gen-s-parser.py, src/gen-s-parser.inc, src/ir/cost.h, src/ir/effects.h, src/passes/Print.cpp, src/wasm-binary.h, src/wasm-delegations-fields.def, src/wasm.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, src/wasm/wasm-stack.cpp, src/wasm/wasm.cpp, test/lit/strings.wast
These just add `_array` to the existing instructions, and instead of getting
a pointer and a length they just get a pointer (which is a GC array).
=> [Strings] Add string.new GC variants

test/example/c-api-kitchen-sink.c, test/example/c-api-unused-mem.cpp
The C tests print `uintptr_t`s respectively `size_t`s in a few places, previously producing warnings.
The z-specifier appears to be [a C99 addition](https://linux.die.net/man/3/printf). The alternative would be to cast to `(int)` instead, lmk :)
=> [C API] Fix printf-related warnings when compiling C tests (NFC)

src/tools/wasm-split/split-options.cpp, src/tools/wasm-split/split-options.h, src/tools/wasm-split/wasm-split.cpp, test/lit/help/wasm-split.test
There are several reasons why a function may not be trained in deterministically. 
So to perform quick validation we need to inspect profile.data (another ways requires split to be performed). However as profile.data is a binary file and is not self sufficient, so we cannot currently use it to perform such validation.
Therefore to allow quick check on whether a particular function has been trained in, we need to dump profile.data in a more readable format. 
This PR, allows us to output, the list of functions to be kept (in main wasm) and those split functions (to be moved to deferred.wasm) in a readable format, to console. 
Added a new option `--print-profile` 
- input path to orig.wasm (its the original wasm file that will be used later during split)
- input path to profile.data that we …
=> changes to print profile data to readable format 

src/ir/effects.h
This is not observable in practice atm since `call_ref` also does a call,
which has even more effects. However, future optimizations might benefit
from this, and it is more consistent to avoid marking the instruction as
trapping if it can't.
=> [Effects] call_ref traps only when the target is null

src/ir/CMakeLists.txt, src/ir/drop.cpp, src/ir/drop.h, src/passes/GUFA.cpp, src/passes/OptimizeInstructions.cpp
Now that we have `getDroppedUnconditionalChildrenAndAppend`, all passes
need to use it rather than the old `getDroppedChildrenAndAppend`, which
is used within the new method
`getDroppedUnconditionalChildrenAndAppend`.
This creates `drop.cpp` and move method implementations in drop.h there,
and merge two methods given that the old method is not supposed to be
used from outside anyway, and drops `Unconditional` from the new method
name because this is the only method and doesn't have to be specific
about that.
=> Move method implementations to drop.cpp

src/wasm-binary.h, src/wasm/wasm-binary.cpp
wasm-binary.h/.cpp has maps of Index to Expression* to link already parsed global/function/table expression indexes with the corresponding name for the global/function/table. This structure assumes that each expression type will need only a single reference to the corresponding global/function/table, but this breaks down with the introduction of multi-memories as the MemoryCopy instruction has a pointer to the source memory and a pointer to the destination memory.
This change provides a mechanism for a single expression to have multiple Name* pointers set. That said, we lose the possibility of hitting WASM_UNREACHABLE, as we won't know the Expression type. In practice, this seems a difficult condition to reach?
=> Changing ref maps in wasm-binary to use a value of a vector of Name*

src/tools/wasm-reduce.cpp
This lets `wasm-reduce --enable-FOO` work. Usually this is not needed as we do
enable all features by default, but sometimes it is nice to disable features (e.g. to
avoid reducing into a testcase that uses something the original wasm did not use).
=> wasm-reduce: Apply commandline features

src/ir/drop.cpp
The previous code assumes if `last`'s type is unreachable it traps. But
it's not always the case because it can be other instructions like `br`
whose type is unreachable but doesn't necessarily trap.
Context:
https://github.com/WebAssembly/binaryen/pull/4827#discussion_r929395477
Not sure how I can add a test for this, because the `last` argument of
this function is currently only used in GUFA, and we only add
`unreachable` for it, so to add a test case, I think we need a separate
test pass or something to test this. I'm not sure if it's worth it, but
please let me know if you think it does.
=> Fix unreachable handling in getDroppedChildrenAndAppend

src/dataflow/utils.h, src/passes/Print.cpp, src/pretty_printing.h
Refactor everywhere from:
```c++
for (size_t i = 0; i < indent; i++) {
o << ' ';
}
```
to:
```c++
o << std::string(indent, ' ');
```
It is much simpler and should produce smaller code.See godbolt:
https://godbolt.org/z/KMYMdn7z5
=> Refactor doIndent

CMakeLists.txt
When building Binaryen to wasm in debug mode,
1) Avoid post-link Binaryen changes with WASM_BIGINT and by avoiding O3
2) Don't use SINGLE_FILE, to make it easier to analyze the resulting wasm
=> Improve wasm debug build

src/tools/wasm-reduce.cpp
It was wasted work to see a drop and then check if we can replace it with
a drop of its child, which is identical to the original state. This didn't cause
any harm (we'd not reduce code size, and stop eventually) but it did slow us
down.
=> [NFC] wasm-reduce: Avoid wasted work on drops

src/ir/possible-contents.cpp, src/passes/RemoveUnusedModuleElements.cpp, test/lit/passes/gufa.wast
Like RemoveUnusedModuleElements, places that build graphs of function
reachability must special-case the call-without-effects intrinsic. Without that,
it looks like a call to an import. Normally a call to an import is fine - it makes us
be super-pessimistic, as we think things escape all the way out - but in GC
for now we are assuming a closed world, and so we end up broken. To fix that,
properly handle the intrinsic case.
=> [GUFA] Handle GUFA + Intrinsics

src/binaryen-c.cpp, src/ir/possible-contents.cpp, src/ir/properties.h, src/literal.h, src/passes/Precompute.cpp, src/wasm-interpreter.h, src/wasm/literal.cpp, test/gtest/possible-contents.cpp
We already require non-null literals to have non-null types, but with this
change we can enforce that constraint by construction. Also remove the default
behavior of creating a function reference literal with heap type `func`, since
there is always a more specific function type to use.
=> Update reference type Literal constructors to use HeapType

src/binaryen-c.cpp
Avoids a "may fall through" warning.
=> Fix a new compiler warning

src/ir/abstract.h, src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions.wast
As I promised [in this comment](https://github.com/WebAssembly/binaryen/pull/4808#issuecomment-1194982890)
+ Move this rules to separate function;
+ Refactor it with matches;
+ Add comments;
+ Handle rotational shifts as well;
+ Handle overflows for `<<`, `>>`, `>>>` shifts;
+ Add mixed rotate rules:
```rust
rotl(rotr(x, C1), C2)   =>   rotr(x, C1 - C2)
rotr(rotl(x, C1), C2)   =>   rotl(x, C1 - C2)
```
=> [Optimize Instructions] Refactor squared rules

src/wasm/wasm-emscripten.cpp
We already remove `__start_em_asm` and `__stop_em_asm`.  This change
is needed since I want to start exporting `__start_em_js` and
`__stop_em_js` from emscripten without causing regressions.
As a followup I'm planning on moving all of the em_js and em_asm
stripping code it PostEmscripten.cpp.. which itself is needed in order
to completely remove the metadata extraction code from binaryen.
=> wasm-emscripten-finalize: Remove __start/__stop_em_js exports

src/ir/flat.h, src/ir/hashed.h, src/ir/struct-utils.h, src/passes/NameList.cpp, src/passes/OnceReduction.cpp, src/passes/PrintFeatures.cpp, src/passes/ReorderFunctions.cpp
Atm this saves only a super-tiny amount of work. However, with 1a validation
it will save a lot more, since then we will be able to skip any 1a fixup work if
a pass does not modify the IR at all.
=> [NFC] Mark modifiesBinaryenIR=false in more places

README.md, src/support/command-line.cpp
For example I found it useful to able to do something like this:
```
$ BINARYEN_DEBUG=post-emscripten ./test/runner sometest
```
=> Allow `BINARYEN_DEBUG` environment variable to be used in place of `--debug`. NFC

src/wasm/wasm-emscripten.cpp, test/lld/em_asm.wat.mem.out
This avoid a fatal crash in `--post-emscripten` where it tries to remove
data that is no longer part of the file.
This fixes bug introduced by #4871 that causes emscripten tests to fail.
=> wasm-emscripten-finalize: Remove em_js/em_asm start/stop symbols when stripping data segments.

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions.wast
```wat
eqz(eqz(i32(x)))   ->   i32(x) != 0
eqz(eqz(i64(x)))   ->   i64(x) != 0
```
Only when `shrinkLevel == 0` (prefer speed over binary size).
+ This could probably unblock some further optimizations like DeMorgan's rules etc.
+ Currently most of the wasm engines don't optimize such pattern on their side also it may improve perf on lower tiers / interpreters. See [also](https://github.com/WebAssembly/binaryen/pull/4194#issuecomment-931489983)
=> [Optimize Instructions] Fold eqz(eqz(x)) to relational binary

src/ir/possible-contents.cpp, test/lit/passes/gufa-refs.wast
A function literal (`ref.func`) should never reach a struct or array get, but
if there is a cast then it can look like they might arrive. We filter in `ref.cast`
which avoids that (since casting a function to a data type will trap), but
there is also `br_on_cast` which is not yet optimized. This PR adds code
to avoid an assert in `readFromData` in that case.
=> [GUFA] Fix readFromData on a function literal

src/passes/SignaturePruning.cpp, test/lit/passes/signature-pruning.wast
`call.without.effects` will turn into a normal call of the last parameter later,
```wat
(call $call.without.effects
A
B
(ref.func $foo)
)
;; => intrinsic lowering
(call $foo
A
B
)
```
SignaturePruning needs to be aware of that: we can't remove a parameter from `$foo` without
also updating relevant calls to `$call.without.effects`. Rather than handle that, just skip such
cases, and leave them to be optimized after intrinsics are lowered away.
=> [Wasm GC] Fix SignaturePruning on CallWithoutEffects

src/passes/RedundantSetElimination.cpp, test/lit/passes/rse-gc.wast
It turns out that even simple passes like that may end up needing to
refinalize. Any time we replace an instruction with a different type, in fact,
that may be necessary.
This is unfortunate, and other passes will need fixes as well. I'm not
sure why the fuzzer never found this - it was only uncovered by a huge
a huge j2wasm binary.
=> RedundantSetElimination: ReFinalize when needed

src/ir/cost.h, src/wasm-builder.h, src/wasm-delegations-fields.def, src/wasm.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, test/lit/strings.wast
I missed this in the spec. They don't operate on the entire GC array given
to them, but on a specified range.
https://github.com/WebAssembly/stringref/blob/main/proposals/stringref/Overview.md#gc-integration
=> [Strings] string.new.array methods have start:end arguments

src/wasm/wasm-binary.cpp, src/wasm/wasm-stack.cpp
This starts to matter with strings, it turns out. This change should make us
runnable in v8.
https://github.com/WebAssembly/gc/blob/main/proposals/gc/MVP.md#instructions-1
=> [Wasm GC] GC-prefixed opcodes are int8, not LEBs

src/wasm/wasm-binary.cpp, src/wasm/wasm-stack.cpp, test/lit/strings.wast
For now this index is always 0, but we must emit it.
Spec: https://github.com/WebAssembly/stringref/blob/main/proposals/stringref/Overview.md#binary-encoding
Also clean up the wat test a little - we don't have validation yet, but we should
not validate without a memory in that file.
=> [Strings] Linear memory string operations should emit a memory index

scripts/fuzz_opt.py, src/support/small_set.h
Any filename that shows up in a command that we log for the user should be
an absolute path, so that the user can just copy and paste the command. Otherwise,
the fuzzer runs in `out/test/` which the user has to constantly type.
I looked for a better/general way to do this, but can't find anything good other than
manually annotating all the relevant places...
=> Fuzzer: Emit absolute paths in commands

src/wasm/wasm-validator.cpp, test/exception-handling.wast, test/exception-handling.wast.from-wast, test/exception-handling.wast.fromBinary, test/exception-handling.wast.fromBinary.noDebugInfo
`pop`s type should be a supertype, not a subtype, of the tag's type
within `catch`.
Thanks @tlively for catching this!
=> [EH] Pop should be supertype of tag type

src/wasm/wasm-validator.cpp, test/lit/validation/intrinsics.wast
`call.without.effects` has a specific form, where the last parameter is a
function reference, and that function reference must have the right type
for the other parameters if called with them:
```wat
(call $call.without.effects
(..i32..)
(..f64..)
(..function reference, which takes params i32 and f64..)
)
````
=> Validator: Validate intrinsics

src/wasm/wasm-validator.cpp
The validation logic to check for stale types (code where we forgot to run
refinalize) had a workaround for a control flow issue. That workaround meant
we didn't catch errors where a type was concrete but it should be unreachable.
This PR makes that workaround only apply for control flow structures, so we can
catch more errors.
=> Validator: More carefully check for stale types

src/pass.h
I'm not sure why this defaulted to non-global. Perhaps because of limitations in the asm.js days. A better default is to validate globally, and this also applies in pass-debug mode (since that just uses the default there), so this will catch more problems there.
=> Validator: Validate globally by default

scripts/test/node-esm-loader.mjs
```
"/src/scripts/test/node-esm-loader.mjs 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
```
Seems like it might be due to a node update in Alpine?
Hopefully this PR fixes that, but I have no idea...
=> Try to fix Alpine breakage on CI

src/wasm-stack.h, test/example/c-api-unused-mem.txt
We already did this if the block was a child of a control flow structure, which is
the common case (see the new added comment around that code, which clarifies
why). This does the same for all other blocks. This is simple to do and a minor
optimization, but the main benefit from this is just to make our handling of blocks
uniform: after this, we never emit a block with no name. This will make 1a non-
nullable locals easier to handle (since they will be able to assume that property;
and not emitting such blocks avoids some work to handle non-nullable locals
in them).
=> Avoid emitting a block in the binary format when it has no name

test/lit/wasm-split/print-profile.wast
In a multi-memories world, memory must be explicitly defined before being exported. Fix CI for 6b3f3af606f2cbe8da29996e5600d174c5653d05.
/cc @sps-gold
=> Fixing print-profile.wast test

src/binaryen-c.cpp, src/binaryen-c.h
Resolving a couple of issues from the multi-memories PR landing:
- https://github.com/WebAssembly/binaryen/issues/4916
- https://github.com/WebAssembly/binaryen/issues/4917
Note: CI will not pass until https://github.com/WebAssembly/binaryen/pull/4939 lands.
=> Multi-Memories improvements to binaryen-c.cpp

src/ir/possible-contents.cpp, test/lit/passes/gufa.wast
Such globals can be written to from the outside, so we cannot infer anything about
their contents.
Fixes #4932
=> GUFA: Mutable exported globals are roots

src/tools/fuzzing/fuzzing.cpp
Some fuzzer initial contents contain non-nullable externrefs that cause the
fuzzer to try to materialize non-nullable externref values. Perviously the
fuzzer did not support this and crashed with an assertion failure. Fix the
assertion failure by instead returning a null cast to non-null, which will trap
at runtime but at least produce a valid module.
=> Materialize non-null externrefs in the fuzzer

src/passes/RemoveUnusedBrs.cpp, test/passes/remove-unused-brs_enable-multivalue.txt
This fixes what looks like it might be a regression in #4943. It's not actually
an issue since it just affects wat files, but it did uncover an existing
inefficiency. The situation is this:
```wat
(block
..
(br $somewhere)
(nop)
)
```
Removing such a `nop` is always helpful, as the pass might see that that
`br` goes to where control flow is going anyhow, and the `nop` would
confuse it. We used to remove such nops only when the block had a name,
which is why wat testcases looks optimal, but we were actually doing the
less-efficient thing on real-world code. It was a minor inefficiency, though, as
the nop is quickly removed by later passes anyhow. Still, the fix is trivial (to
always remove such nops, regardless of a name on the block or not).
=> RemoveUnusedBrs: Remove final block nops in all cases

scripts/fuzz_opt.py
This mode is tricky to fuzz because the mode is basically "assume traps never
happen; if a trap *does* happen, that is undefined behavior". So if any trap occurs
in the random fuzz testcase, we can't optimize with `-tnh` and assume the results
stay to same. To avoid that, we ignore all functions from the first one that traps,
that is, we only compare the code that ran without trapping. That often is a small
subset of the total functions, sadly, but I do see that this ends up with some useful
coverage despite the drawback.
This also requires some fixes to comparing of references, specifically, funcrefs
are printed with the function name/index, but that can change during opts, so
ignore that. This wasn't noticed before because this new fuzzer mode does
comparisons of `--fuzz-exec-before` …
=> [Fuzzer] Fuzz TrapsNeverHappen mode

src/wasm/wasm-validator.cpp
This change loops through memories to validate each meets wasm spec. I also factored out data segment validation from memory validation, as it makes more sense for data segments to stand alone like the other module-level elements.
=> Multi-Memories Validate

src/binaryen-c.cpp, src/binaryen-c.h, src/js/binaryen.js-post.js, src/wasm-builder.h, test/example/c-api-kitchen-sink.c
Those instructions need to know if the memory is 64-bit or not. We looked that
up on the module globally, which is convenient, but in the C API this was actually
a breaking change, it turns out. To keep things working, provide that information
when creating a MemoryGrow or MemorySize, as another parameter in the C
API. In the C++ API (wasm-builder), support both modes, and default to the
automatic lookup.
We already require a bunch of other explicit info when creating expressions, like
making a Call requires the return type (we don't look it up globally), and even a
LocalGet requires the local type (we don't look it up on the function), so this is
consistent with those.
Fixes #4946
=> Fix multi-memory + C API for MemoryGrow and MemorySize

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-ignore-traps.wast, test/lit/passes/optimize-instructions.wast
Fuzzing with TrapsNeverHappen found a bug, and then reading similar code
I found another, where we check structural equality but ignored effects. Some
things look equal but may have different values at runtime:
```wat
(foo
(call $x)
(call $y)
)
```
The arms are identical structurally but due to side effects may not be identical
in value.
=> [TNH Fuzzing] Fix some equality checks that ignored effects

src/wasm-binary.h, src/wasm/wasm-binary.cpp
We do a call to `updateMaps()` at the end of `processNames` anyhow, and so we
may as well call `addFunction` immediately (and the names will get fixed up in that
`updateMaps` later). The old code for some reason did that for function imports, but
not normal functions. It also stored them separately in temporary storage for some
unclear reason...
I happened to notice this while starting to add support for tag names.
=> [NFC] Simplify binary reading logic for functions

src/wasm/wat-parser.cpp, src/wat-lexer.h, test/lit/wat-kitchen-sink.wast
Implement function parsing, including parsing of locals and type uses. Also add
a new phase of parsing that iterates through type uses that do not have explicit
types to create any implicitly defined types and append them to the type index
space. This is important because the implicitly defined types may be referred to
by index elsewhere and because the legacy parser does not handle these
implicitly defined types correctly. Finally, maintain a map of implicit type use
locations to corresponding types for use in later phases of parsing.
=> [Parser] Parse functions and implicit types

CHANGELOG.md
These entries were accidentally removed in 9d20a4e1.
=> [NFC] Remove accidentally-deleted changelog entries

src/wasm-binary.h, src/wasm/wasm-binary.cpp
Similar to #4969 but for tables.
(After this, we have these to clean up: globals, memories, and segments.)
=> [NFC] Simplify binary reading logic for tables

src/passes/OptimizeInstructions.cpp, test/lit/passes/asyncify_optimize-level=1.wast, test/lit/passes/optimize-instructions.wast
It's just reordering some rules in `optimizeSelect` which unblock some optimizations.
For example this:
```wat
(select
(i32.eqz (local.get $x))
(i32.const 0)
(i32.eqz (local.get $y))
)
```
Optimized Before as:
```wat
(i32.eqz
(select
(i32.const 1)
(local.get $x)
(local.get $y)
)
)
```
Due to `optimizeSelect` apply `!x ? !y : 0  ->  x ? 0 : !y` first and `!(x ? 1 : y)` in second stage which block next rules which can fold this to `or` / `and`.
After this PR same example will optimize more optimal:
```wat
(i32.eqz
(i32.or
(local.get $x)
(local.get $y)
)
)
```
=> [OptimizeInstruction] Reorder rules in optimizeSelect

src/support/small_vector.h, test/example/small_vector.cpp
A resize from a large amount to a small amount would sometimes not clear
the flexible storage, if we used it before but not after.
=> Fix SmallVector's resize() method

src/passes/Print.cpp, test/lit/isorecursive-good.wast, test/lit/isorecursive-output-ordering.wast, test/lit/isorecursive-whole-group.wast, test/lit/nominal-to-isorecursive.wast, test/lit/passes/signature-refining-isorecursive.wast, test/lit/passes/type-refining-isorecursive.wast, test/lit/wat-kitchen-sink.wast
A recent test update seems to have added or removed a space here. Running
the auto-updater script keeps showing this diff.
=> Fix test spacing after recent update

src/ir/module-utils.h
It had hardcoded handling of the table, but was missing RefFunc (and maybe more?)
Also rewrite it to be clearer (avoid special-casing the table) and faster (parallel).
=> Fix ModuleUtils::renameFunctions on RefFunc

src/binaryen-c.cpp, src/binaryen-c.h, src/js/binaryen.js-post.js
Fix #4988.
`BinaryenAddMemoryImport`
`BinaryenAddTableImport`
`BinaryenGlobalTableImport`
`BinaryenAddTagImport`
Also use unique pointers for entity creation.
Now carefully check if entry already exists and just modify `module` and `base` if this true.
=> [C-/JS-Api] Avoid add imports for existing entities in BinaryenSetMemoryImport and etc

src/wasm-binary.h, src/wasm/wasm-binary.cpp
Similar to #4969 but for data segments.
This is the last of this sequence of cleanups.
=> [NFC] Simplify binary reading logic for data segments

src/tools/fuzzing/fuzzing.cpp, test/passes/translate-to-fuzz_all-features_metrics_noprint.txt
Do not export functions that have types not allowed in the rules for
JS interop. Only very few GC types can be on the JS boundary atm.
=> Update fuzzer to newer GC spec regarding JS interop

CHANGELOG.md, CMakeLists.txt
Been a while, and there is a request for it, https://github.com/WebAssembly/binaryen/pull/4736#issuecomment-1232809784
=> Release 110

src/binaryen-c.cpp, src/binaryen-c.h, src/js/binaryen.js-post.js, test/binaryen.js/kitchen-sink.js, test/binaryen.js/kitchen-sink.js.txt, test/example/c-api-kitchen-sink.c, test/example/c-api-kitchen-sink.txt
Adds C-API bindings for the expression classes
* `RefTest`
* `RefCast`
* `BrOn` with operations `BrOnNull`, `BrOnNonNull`, `BrOnCast`, `BrOnCastFail`, `BrOnFunc`, `BrOnNonFunc`, `BrOnData`, `BrOnNonData`, `BrOnI31`, `BrOnNonI31`
* `StructNew` with operations `StringNewUTF8`, `StringNewWTF8`, `StringNewReplace`, `StringNewWTF16`, `StringNewUTF8Array`, `StringNewWTF8Array`, `StringNewReplaceArray`, `StringNewWTF16Array`
* `StructGet`
* `StructSet`
* `ArrayNew`
* `ArrayInit`
* `ArrayGet`
* `ArraySet`
* `ArrayLen`
* `ArrayCopy`
* `StringNew`
* `StringConst`
* `StringMeasure` with operations `StringMeasureUTF8`, `StringMeasureWTF8`, `StringMeasureWTF16`, `StringMeasureIsUSV`, `StringMeasureWTF16View`
* `StringEncode` with operations `StringEncodeUTF8`, `StringEncodeWTF8`, `StringEncodeWTF16`, …
=> Add remaining GC and string instructions to C API

src/ir/ordering.h, src/wasm/wasm.cpp, test/lit/passes/gto-removals.wast
We replaced an unreachable struct.set with something reachable, which can
break validation in corner cases.
=> [Wasm GC] Fix GlobalTypeOptimization fuzz bug on replacing unreachable struct.set

src/ir/effects.h, test/lit/passes/simplify-locals-gc.wast
We explicitly wrote out memory, table, and globals, but did not add structs. This switches
us to use `readsMutableGlobalState` which has the full list of all relevant global state,
including the memory, table, and globals as well as structs.
=> [Effects] Fix hasAnything on mutable global state

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions.wast
```
x + C1 > C2  ==>  x > C2-C1
e.g.
x + 5 > 100  ==>  x > 95
```
Pretty simple, but we do need to be careful of overflows.
Helps #5008 - this is just `>` and `>=`, and just `+`, so far. See that issue for more
patterns.
Found by the superoptimizer #4994. This was the top suggestion for Java and Dart.
=> OptimizeInstructions: Optimize >, >= with an added offset

src/shell-interface.h, src/tools/wasm-ctor-eval.cpp
Replacing Fatal() call sites in src/shell-interface.h & src/tools/wasm-ctor-eval.cpp that were added in the [Multi-Memories PR](https://github.com/WebAssembly/binaryen/pull/4811) with assert()
=> Changing Fatal() to assert()

src/ir/bits.h, src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions.wast, test/passes/optimize-instructions_fuzz-exec.txt
When we see e.g. `x < y` and `x` has fewer bits set, we can infer a result.
Helps #5010. As mentioned there, this is one of the top superoptimizer findings.
On j2wasm it ends up removing a few hundred binary operations for example.
=> OptimizeInstructions: Use min/max bits in comparisons

src/passes/LogExecution.cpp
The name of the import object might not always be "env" (e.g. when Emscripten minifies the import name to a shorter string "a"). Adjust LogExecution pass to discover the import name that is used.
=> Fix LogExecution pass import name lookup

src/ir/effects.h, src/passes/CodePushing.cpp, test/lit/passes/code-pushing-eh.wast
We had some concerns about this not working in the past, but thinking about it
now, I believe it is safe to do. Specifically, a throw is either like a break or a return -
either it jumps out to an outer scope (like a break) or it jumps out of the function
(like a return), and both breaks and returns have already been handled here.
This change has some nice effects on J2Wasm output, where there are quite a
lot of throws, which we can now optimize around.
=> [Exceptions] Optimize in CodePushing even with exceptions thrown

src/binaryen-c.cpp, src/binaryen-c.h
Covers `CallRef`, `RefTest`, `RefCast`, `BrOn`, `StructNew`, `StructGet`, `StructSet`, `ArrayNew`, `ArrayInit`, `ArrayGet`, `ArraySet`, `ArrayLen`, `ArrayCopy`, `StringNew`, `StringConst`, `StringMeasure`, `StringEncode`, `StringConcat`, `StringEq`, `StringAs`, `StringWTF8Advance`, `StringWTF16Get`, `StringIterNext`, `StringIterMove`, `StringSliceWTF`, `StringSliceIter`.
=> [C API] Add getters and setters for various expressions

src/ir/properties.h, src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions.wast, test/passes/optimize-instructions_fuzz-exec.txt
```rust
x - C       ->    x + (-C)
min(C, x)   ->    min(x, C)
max(C, x)   ->    max(x, C)
```
And remove redundant rules
=> [OptimizeInstructions] More canonizations for floating points

src/ir/names.h, src/tools/wasm-split/instrumenter.cpp, src/tools/wasm-split/instrumenter.h, src/tools/wasm-split/split-options.cpp, src/tools/wasm-split/split-options.h, src/tools/wasm-split/wasm-split.cpp, test/lit/help/wasm-split.test, test/lit/wasm-split/instrument-in-secondary-memory-custom-names.wast, test/lit/wasm-split/instrument-in-secondary-memory.wast, test/lit/wasm-split/invalid-options.wast
Adds an --in-secondary-memory switch to wasm-split tool that allows profile data to be stored in a separate memory from module main memory. With this option, users do not need to reserve the initial memory region for profile data and the data can be shared between multiple threads.
=> Multi-Memories wasm-split

src/tools/tool-options.h, test/lit/help/wasm-as.test, test/lit/help/wasm-ctor-eval.test, test/lit/help/wasm-dis.test, test/lit/help/wasm-emscripten-finalize.test, test/lit/help/wasm-metadce.test, test/lit/help/wasm-opt.test, test/lit/help/wasm-reduce.test, test/lit/help/wasm-split.test, test/lit/help/wasm2js.test
This allows a three-step upgrade process where binaryen is updated with this
change, then users remove their use of these flags, then binaryen can remove the
flags permanently.
=> Temporarily restore the typed-function-references flags as no-ops

src/passes/JSPI.cpp, test/lit/passes/jspi.wast
Fixes: https://github.com/emscripten-core/emscripten/issues/17846
More detailed explanation of the issue from Thibaud:
- A promising export is entered, generating a suspender s1, which is stored in the global
- The wasm code calls a wrapped import, passing it the value in the global (s1) and suspends
- Another export is entered, generating suspender s2, which is stored in the global
- We call another wrapped import, which suspends s2 (so far so good)
- We return to the event loop and s1 is resumed
And now we are in an inconsistent state: the active suspender is "s1", but the object in the global is "s2". So the next time we call a wrapped import, there is a mismatch, which is what this runtime error reports.
=> JPSI - Support re-entering a suspended Wasm module.

src/ir/effects.h
I came across this when I started using string.encode_wtf16_array where the optimized tests started failing. I noticed that the code was removed by binaryen so this seems like the right fix.
I don't have an open-source setup but I tested in google3 and it correctly fixed the issue I was experiencing.
=> Fix the side-effects of the string encode instructions.

src/js/binaryen.js-extern-pre.js, src/js/binaryen.js-post.js
Instructs Closure about the types in play so the warnings go away. <del>Didn't encounter the externs warning regarding the `WebAssembly` object (need to see what CI states)</del>. Generally it looks that we could refactor the code slightly to use `class`es, then we'd not need to annotate in comments so much (except the dynamically generated expression methods).
Related #5062
Update: Seen the `WebAssembly` object externs warning now, which might require a fix to the externs provided by Emscripten.
=> Fix some Closure warnings in Emscripten builds

.github/workflows/ci.yml
Reverts WebAssembly/binaryen#5077
#5075 fixes the require() issue, so we don't need the pin.
=> Revert "Pin the emsdk for now"

src/ir/module-utils.cpp, src/passes/Print.cpp, src/wasm-binary.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, src/wasm/wasm-stack.cpp, test/lit/passes/dae-gc-refine-return.wast, test/lit/passes/inlining_all-features.wast, test/lit/passes/optimize-instructions-call_ref.wast, test/lit/types-function-references.wast
The GC spec has been updated to have heap type annotations on call_ref and
return_call_ref. To avoid breaking users, we will have a graceful, multi-step
upgrade to the annotated version of call_ref, but since return_call_ref has no
users yet, update it in a single step.
=> Add a type annotation to return_call_ref

CHANGELOG.md, src/passes/Print.cpp, src/wasm-binary.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, src/wasm/wasm-stack.cpp, test/lit/passes/dae_all-features.wast, test/lit/passes/gufa-refs.wast, test/lit/passes/inlining-optimizing.wast, test/lit/passes/inlining_all-features.wast, test/lit/passes/intrinsic-lowering.wast, test/lit/passes/local-cse_all-features.wast, test/lit/passes/merge-similar-functions.wast, test/lit/passes/merge-similar-functions_types.wast, test/lit/passes/optimize-instructions-call_ref.wast, test/lit/passes/precompute-gc.wast, test/lit/passes/remove-unused-module-elements-refs.wast, test/lit/passes/signature-pruning.wast, test/lit/passes/signature-refining.wast, test/lit/types-function-references.wast, test/passes/duplicate-function-elimination_all-features.txt
Emit call_ref instructions with type annotations and a temporary opcode. Also
implement support for parsing optional type annotations on call_ref in the text
and binary formats. This is part of a multi-part graceful update to switch
Binaryen and all of its users over to using the type-annotated version of
call_ref without there being any breakage.
=> Emit call_ref with a type annotation

src/pass.h, src/wasm-traversal.h
Make `walkModuleCode` set the module automatically, like `walkModule` already does.
Also remove some unneeded module settings when calling those methods.
=> [NFC] Simplify traversal code for setting the module

src/passes/Memory64Lowering.cpp, test/passes/memory64-lowering_enable-memory64_enable-bulk-memory_enable-threads.txt, test/passes/memory64-lowering_enable-memory64_enable-bulk-memory_enable-threads.wast
This is the case for dynamic linking where the segment offset are derived from he `__memory_base` import.
=> Memory64Lowering: Ignore data segments with non-const iniital offset

src/ir/possible-contents.cpp, src/passes/GUFA.cpp, test/gtest/possible-contents.cpp, test/lit/passes/gufa-refs.wast
We compared types and not heap types, so a difference in nullability
confused us. But at that point in the code, we've ruled out nulls, so we
should focus on heap types only.
This should unblock the binaryen roll into J2Wasm.
=> [GUFA] Fix haveIntersection on comparing nullable with non-nullable

src/ir/possible-contents.cpp, src/ir/possible-contents.h
This does not actually add cone types, but it does NFC refactoring towards that.
Specifically it replaces the internal `ExactType` with `ConeType`, and the latter
has a depth, so a cone type of depth 0 is the old exact type.
Cone types with `depth > 0` are not possible yet, keeping this NFC.
I believe this design with a depth for cone types has little overhead. It does add
to the size of `ConeType`, but the variant there is larger anyhow (it contains a
`Literal`). And things like `isSubType` need to loop anyhow, so looping up to the
depth etc. in checks won't make things slower. Does that sound right?
=> [GUFA] Prepare for cone types [NFC]

src/passes/GlobalStructInference.cpp
We append to vectors of globals in a nondeterministically-ordered loop, which can lead to
different orderings of the vectors. This happens quite frequently in very large J2Wasm
files it turns out. As a solution, simply sort them after the nondeterministic stage.
=> Fix nondeterminism in GlobalStructInference

.github/workflows/ci.yml
The current CI breakage is due to
https://github.com/emscripten-core/emscripten/pull/17948. Pin the Emscripten
version used in CI until that can be investigated and resolved.
=> Pin Emscripten

README.md
This currently links to the section on the C++ API, which is much smaller than the "C API" section, and probably not intended.
=> Fix 'C API' readme link

.github/workflows/ci.yml, src/mixed_arena.h, src/support/utilities.h, src/wasm.h
It does not make sense to construct an `Expression` directly because all
expressions must be specific expressions. However, we previously allowed
constructing Expressions, and in particular we allowed them to be copy
constructed. Unrelatedly, `Fatal::operator<<` took its argument by value.
Together, these two facts produced UB when printing Expressions in fatal error
messages because a new Expression would be copy constructed with the original
expression ID but without any of the actual data from the original specific
expression. For example, when trying to print a Block, the printing code would
try to look at the expression list, but the expression list would be junk stack
data because the copied Expression does not contain an expression list.
Fix the problem by making Expression's …
=> Fix bugs with copying expressions

CHANGELOG.md, src/support/file.cpp, src/support/utilities.h
This patch makes binaryen easier to call from other applications by making more errors recoverable instead of early-exiting.
The main thing it does is change three calls to `exit` on I/O errors into calls to `Fatal()`, which is an existing custom abstraction for handling unrecoverable errors. Currently `Fatal`'s destructor calls `_Exit(1)`.
My intent is to make it possible for `Fatal` to not exit, but to throw, allowing an embedding application to catch the exception.
Because the previous early exits were exiting with error code `EXIT_FAILURE`, I also changed `Fatal` to exit with `EXIT_FAILURE`. The test suite continues to pass so I assume this is ok.
Next I changed `Fatal` to buffer its error message until the destructor instead of immediately printing it to stderr. This is for ease of …
=> Change `exit()` to `Fatal()`; make it possible to throw on `Fatal()`.

test/gtest/type-builder.cpp
These comparisons were showing up as warnings with the latest emcc/clang.  I only noticed because I ran `ninja` to build everything whereas we only test the `binaryen` target under emscripten normally.
=> Fix compiler warnings under emcc. NFC

src/tools/fuzzing/fuzzing.cpp
Previously it would randomly replace an expression with another one with the
exact same type. Allowing a subtype may give us more coverage.
=> [Fuzzing] Allow recombine() to replace with a subtype

scripts/test/shared.py
More recent version of V8 include a change from `dataref` to `structref` that
prevent WasmGC modules produced by the fuzzer from validating. Use the last
compatible v8 version if it is in the path until we can update Binaryen to be
compatible with newer v8.
=> Pin v8 10.8.104

src/wasm-binary.h, src/wasm/wasm-binary.cpp, test/unit/test_web_limitations.py
Similar to our existing handling of memory segment size:
https://github.com/WebAssembly/binaryen/blob/e6be381b6f5adbd07af080a4e1f74ba04c8eda82/src/wasm/wasm-binary.cpp#L600-L604
Fixes https://github.com/emscripten-core/emscripten/issues/17988
=> Warn on too many parameters for Web VMs

src/wasm/wasm-debug.cpp, third_party/llvm-project/DWARFEmitter.cpp, third_party/llvm-project/include/llvm/include/llvm/DebugInfo/DWARFContext.h
Unfortunately there isn't a single place where an error may occur. I tested on
several files with different flags and added sufficient warnings so that we warn
on them all.
=> [DWARF] Warn on unsupport DWARF versions and content

src/wasm/wasm-validator.cpp
Making a change to wasm-validator so that Memory::kUnlimitedSize is treated properly like an unlimited case. The check for whether memory.initial < memory.max will only happen if memory.hasMax() — meaning if memory.max is not set to kUnlimitedSize.
=> Validate memory initial < max only if memory hasMax

src/wasm/wat-parser.cpp, test/lit/wat-kitchen-sink.wast
Parse folded expressions as described in the spec:
https://webassembly.github.io/spec/core/text/instructions.html#folded-instructions.
The old binaryen parser _only_ parses folded expressions, and furthermore
requires them to be folded such that a parent instruction consumes the values
produced by its children and only those values. The standard format is much more
general and allows folded instructions to have an arbitrary number of children
independent of dataflow.
To prevent the rest of the parser from having to know or care about the
difference between folded and unfolded instructions, parse folded instructions
after their children have been parsed. This means that a sequence of
instructions is always parsed in the order they would appear in a binary no
matter how they are folded (or …
=> [Parser] Parse folded instructions

src/ir/possible-contents.cpp, test/gtest/possible-contents.cpp
When the heap types are not subtypes of each other, but a null is possible, the
intersection exists and is a null. That null must be the shared bottom type.
=> [Wasm GC] Fix the intersection of a bottom type null

scripts/gen-s-parser.py, src/gen-s-parser.inc, src/wasm/wat-parser.cpp
Rather than passing both a `Ctx` and a `ParseInput` to every parsing function,
pass only a `Ctx` with a `ParseInput` inside of it. This significantly reduces
verbosity in the parser. To handle cases where parsing needs to happen at
specific locations, which used to be handled by constructing a new `ParseInput`
independent from the ctx, introduce a new RAII utility for temporarily changing
the location of the `ParseInput` inside a context.
Also add a utility for generating an error at a particular location to avoid
having to construct new `ParseInput` objects just for that purpose. This
resolves a few TODOs about correcting error locations, but since we don't test
those yet, I still consider this NFC.
=> [Parser][NFC] Move `ParseInput` into the parser context

src/ir/subtypes.h
Avoid allocating there. This is both faster and also it ensures we never modify
our internal data structure after our constructor.
=> [Wasm GC][NFC] Optimize getStrictSubTypes()

scripts/gen-s-parser.py, src/gen-s-parser.inc, src/wasm/wat-parser.cpp
The `makeXXX` functions that are responsible for individual instructions will
generally need the locations of those functions to emit useful errors. However,
since the instruction names are parsed before the `makeXXX` functions are
called, the functions have no good way of getting the location of the beginning
of the instruction. Fix this by explicitly passing them the location of the
beginning of the instruction.
=> [Parser][NFC] Pass instruction locations to `makeXXX` functions

src/ir/subtypes.h, test/gtest/type-builder.cpp
This will be useful in further cone type optimizations.
Depends on #5130
=> [Wasm GC] Add a method to traverse subtypes

src/wasm/wat-lexer.cpp, src/wasm/wat-parser.cpp, test/lit/wat-kitchen-sink.wast
Parse unary, binary, drop, and select instructions, properly fixing up stacky
code, unreachable code, and multivalue code so it can be represented in Binaryen
IR.
=> [Parser] Parse instructions with children

test/lit/passes/gufa-refs.wast
We had cone tests for `ref.eq` and `ref.cast` etc. but not for `struct.get`.
=> [Wasm GC] Add GUFA tests for struct reads from cones

src/wasm/wasm.cpp, src/wasm/wat-parser.cpp, test/lit/wat-kitchen-sink.wast
This requires parsing local indices and fixing a bug in `Function::setLocalName`
where it only set up the mapping from index to name and not the mapping from
name to index.
=> [Parser] Parse `local.get`

src/wasm/wat-parser.cpp
Since our usage of `WithPosition` depends on C++17 class template argument
deduction, it triggers a clang warning `-Wctad-maybe-unsupported`. Silence the
warning by providing an explicit deduction guide.
=> [NFC] Add an explicit deduction guide for `WithPosition`

src/wasm/wat-parser.cpp, test/lit/wat-kitchen-sink.wast
Since the type annotations are not stored explicitly in Binaryen IR, we have to
validate them in the parser. Implement this and fix a newly-caught incorrect
annotation in the tests.
=> [Parser] Validate type annotations on `select`

src/ir/possible-contents.cpp, src/ir/possible-contents.h, test/lit/passes/gufa-refs.wast
Instead of `Many`, use a proper Cone Type for the data, as appropriate.
This helps some existing tests. I'm not adding comprehensive tests for this as
a later PR will simply assert on `Many` not appearing anywhere.
=> [Wasm GC][GUFA] Avoid Many in roots

src/wasm/wasm-type.cpp, test/gtest/type-builder.cpp
As the number of basic heap types has grown, the complexity of the subtype and
LUB calculations has grown as well. To ensure that they are correct, test the
complete matrix of basic types and trivial user-defined types. Fix the subtype
calculation to make string types subtypes of `any` to make the test pass.
=> Exhaustively test basic heap type relationships

src/ir/possible-contents.cpp, test/gtest/possible-contents.cpp, test/lit/passes/gufa-refs.wast
Now that we have a cone type, we are able to represent in PossibleContents the
natural content of a wasm location: a type or any of its subtypes. This allows us to
enforce the wasm typing rules, that is, to filter the data arriving at a location by the
wasm type of the location.
Technically this could be unnecessary if we had full implementations of flowFoo
and so forth, that is, tailored code for each wasm expression that makes sure we
only contain and flow content that fits in the wasm type. Atm we don't have that,
and until the wasm spec stabilizes it's probably not worth the effort. Instead,
simply filter based on the type, which gives the same result (though it does take
a little more work; I measured it at 3% or so of runtime).
While doing so normalize cones to their actual maximum …
=> [Wasm GC] Filter GUFA expression locations by their type

src/ir/possible-contents.cpp
Modern nulls never compare equal unless they have the same type too.
=> [Wasm GC] [NFC] Remove .type checks from GUFA that are not needed with modern nulls

CHANGELOG.md, src/binaryen-c.cpp, test/binaryen.js/expressions.js, test/binaryen.js/kitchen-sink.js.txt
The C API still returned non nullable types for `dataref` (`ref data` instead of `ref null data`) and `i31ref` (`ref i31` instead of `ref null i31`). This PR aligns with the current state of the GC proposal, making them nullable when obtained via the C API.
=> [C API] Align I31ref and Dataref to be nullable

src/wasm-s-parser.h, src/wasm/wat-parser.cpp, test/lit/wat-kitchen-sink.wast
`Push` expressions were removed in #2867, so we no longer need to make them.
=> [NFC] Remove obsolete `makePush` functions

src/ir/possible-contents.h, src/support/hash.h
We already provided a specialization of `std::hash` for arbitrary pairs, so add
one for `std::tuple` as well. Use the new specialization where we were
previously using nested pairs just to be able to use the pair specialization.
=> [NFC] Add a generic hash implementation for tuples

src/wasm/wat-parser.cpp, test/lit/wat-kitchen-sink.wast
Parse 32-bit and 64-bit memories, including their initial and max sizes. Shared
memories are left to a follow-up PR. The memory abbreviation that includes
inline data is parsed, but the associated data segment is not yet created. Also
do some minor simplifications in neighboring helper functions for other kinds of
module elements.
=> [Parser] Parse memories

src/wasm.h
I believe all locations that create one already set it (or else we'd see errors), but it's not
easy to see that when reading the code. And other similar locations (like DataSegment)
do initialize to null, so do so for consistency.
=> [NFC] Add nullptr init for ElementSegment offset

src/wasm/wasm-validator.cpp
Specifically if a segment offset was a const, we checked that it made sense. But the
wasm spec doesn't do that, and it actually causes some issues (https://github.com/WebAssembly/binaryen/pull/5163).
In theory this extra validation might be useful - compile-time error rather than runtime -
but if we want this it should probably be an optional thing, like an opt-in flag or a `--lint`
pass or such. I'm not sure it's worth it.
=> Remove excessive validation that is not in the wasm spec

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-gc-heap.wast
These are encoded as RefAs operations, and we have optimizations that assume those
trap on null, but Externalize/Internalize do not. Skip them there to avoid an error on the
type being incorrect later.
Noticed on a [dart testcase](https://github.com/dart-lang/sdk/issues/50268).
=> [Wasm GC] Externalize/Internalize allow nulls

scripts/gen-s-parser.py, src/gen-s-parser.inc, src/wasm-builder.h, src/wasm-s-parser.h, src/wasm/wasm-s-parser.cpp, src/wasm/wat-parser.cpp, test/lit/wat-kitchen-sink.wast
Add parsing functions for `memarg`s, the offset and align fields of load and
store instructions. These fields are interesting because they are lexically
reserved words that need to be further parsed to extract their actual values. On
top of that, add support for parsing all of the load and store instructions.
This required fixing a buffer overflow problem in the generated parser code and
adding more information to the signatures of the SIMD load and store
instructions. `SIMDLoadStoreLane` instructions are particularly interesting
because they may require backtracking to parse correctly.
=> [Parser] Parse loads and stores

src/wasm-traversal.h
Doing so shortens the code by removing duplicate logic.
Also this will avoid a compile error in a future PR, as by inheriting from
Visitor we include functions like `visitFunction` which were otherwise
missing from OverriddenVisitor. We could duplicate those like we
duplicated the expression logic, but just removing all the duplication
seems best.
I manually verified OverriddenVisitor still provides the same error messages
as before.
=> [NFC] Inherit from Visitor in OverriddenVisitor

src/ir/ReFinalize.cpp, src/ir/utils.h, src/wasm-traversal.h
Poking in the git history, this was some kind of hack for a problem that appears to
no longer exist since at least 5 years ago.
Logically, refinalize should never change a type from unreachable to none, or at
least if we have a place that does this, we should manually do the necessary things
around that, like updating the function's return type. The opposite, none (or anything
else) to unreachable is the common case, where we use refinalize to propagate
that type upwards.
Fuzzing also finds no issues.
This will unblock a future PR where this hack just got in the way.
=> [NFC] Remove an ancient hack in ReFinalize

src/wasm/wat-parser.cpp, test/lit/wat-kitchen-sink.wast
Unlike in the legacy parser, we cannot depend on the folded text format to
determine how many values to return, so we determine that solely based on the
current function context.
To handle multivalue return correctly, fix a bug in which we could synthesize
new `unreachable`s and place them before existing unreachable instructions (like
returns) at the end of instruction sequences.
=> [Parser] Parse `return`

src/binaryen-c.cpp, src/binaryen-c.h, test/example/c-api-kitchen-sink.c
Adds heap type utility to the C API:
* `BinaryenHeapTypeIsBasic`
* `BinaryenHeapTypeIsSignature`
* `BinaryenHeapTypeIsStruct`
* `BinaryenHeapTypeIsArray`
* `BinaryenHeapTypeIsSubType`
Does not implement `BinaryenHeapTypeIsFunction` and `BinaryenHeapTypeIsData`, as these seem redundant, respectively are about to change in the case of `data`.
Note that it is theoretically possible to implement `IsSignature`, `IsStruct` and `IsArray` using `IsSubType` with additional comparisons to exclude the basic / bottom types in user code, reducing API surface at the expense of some complexity, if preferable? Example:
```
BinaryenHeapTypeIsSignature(ht)
-> BinaryenHeapTypeIsSubType(ht, BinaryenHeapTypeFunc()) && !BinaryenHeapTypeIsBasic(ht)
BinaryenHeapTypeIsStruct(ht)
-> BinaryenHeapTypeIsSubType(ht, …
```
=> [C API] Add essential heap type utilities

src/ir/subtypes.h, test/gtest/possible-contents.cpp, test/gtest/type-builder.cpp
Found by the fuzzer. Add some automatic testing that would have found this,
and also a dedicated test.
=> [Wasm GC] Fix the depth of the new array heap type

src/ir/possible-contents.cpp, src/ir/possible-contents.h, test/gtest/possible-contents.cpp
As suggested by @tlively in the past. This makes the method symmetric.
Measuring speed, this seems identical to before, so that concern seems fine.
However, after writing this I'm not sure this is worth it. Perhaps the `combine()` method itself is a little easier to read, but using the API gets more cumbersome in the common case:
```diff
-contents.combine(newContents);
+contents = PossibleContents::combine(contents, newContents);
```
(There is also some risk of using it without realizing it is static, `contents.combine(.., ..)` can be written, but it does not modify `contents`. I guess `[[nodiscard]]` could help there though.)
=> [NFC] Rewrite PossibleContents::combine to be static

src/passes/RedundantSetElimination.cpp, test/lit/passes/inlining-optimizing_optimize-level=3.wast
This can help in rare cases in MVP wasm, say for the return value of a block. But for
wasm GC it is very important due to casts.
Similar logic was added as part of #5194 for SimplifyLocals. It should probably have
been in a separate PR then. This does the right thing for RedundantSetElimination,
as a separate PR. Full tests will appear in that later PR (it is not really possible to test
the GC side yet - we need the logic in the later PR that actually switches to a more
refined local index when available).
=> RedundantSetElimination: Look at fallthrough values

scripts/fuzz_opt.py
That PR renamed test/lit/optimize-instructions.wast to
test/lit/optimize-instructions-mvp.wast. However, the fuzzer was explicitly
adding the test to the list of important initial contents under the old name, so
it was failing an assertion that the initial contents existed.  Update the fuzzer
to use the new test name.
=> Fix fuzzer default contents after #5212

src/passes/MultiMemoryLowering.cpp, test/lit/passes/multi-memory-lowering.wast
Per the [wasm spec](https://webassembly.github.io/spec/core/syntax/instructions.html#syntax-instr-memory), memory.grow instructions should return -1 when there is a failure to allocate enough memory. This PR adds support for returning this error code.
=> Handles memory.grow failure in MultiMemoryLowering Pass

src/ir/possible-contents.cpp, test/lit/passes/gufa-refs.wast
We don't actually have the transitive and distributive properties since our
PossibleContents representation is an approximation, and the fuzzer found
a case where that is noticeable. See more details in the new comment +
testcase.
I measured speed and memory usage and this actually causes almost no
noticeable change.
=> [Wasm GC] Fix nondeterminism in GUFA due to ordering

src/ir/possible-contents.cpp
All that code did was filter contents by the type of the RefCast. We do that for all
expressions now, so it was redundant.
=> [GUFA] [NFC] Remove RefCast special-casing

src/passes/RemoveUnusedModuleElements.cpp, src/wasm-interpreter.h, test/spec/array-new-data.wast, test/spec/array-new-elem.wast
The offset and size were previously being sign extended from 32 to 64 bits,
which meant that negative sizes could make the bounds check pass and cause an
exception to be thrown by an overly large allocation. Switch to using uint64_t
from the start rather than mixing sizes and signs, and update the tests to
reproduce the error more robustly in the absence of the fix.
Fixes #5249.
=> Fix arithmetic in interpretation of ArrayNewSeg

CHANGELOG.md, src/wasm-binary.h, src/wasm-builder.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, test/lit/passes/dae_all-features.wast, test/lit/passes/gufa-refs.wast, test/lit/passes/inlining-optimizing.wast, test/lit/passes/local-cse_all-features.wast, test/lit/passes/optimize-instructions-call_ref-roundtrip.wast, test/lit/passes/optimize-instructions-call_ref.wast, test/lit/passes/precompute-gc.wast, test/lit/passes/remove-unused-module-elements-refs.wast, test/lit/passes/signature-pruning.wast, test/lit/passes/signature-refining.wast, test/lit/types-function-references.wast, test/lit/validation/nn-locals-bad-call_ref.wast, test/passes/Oz_fuzz-exec_all-features.wast, test/passes/duplicate-function-elimination_all-features.wast, test/spec/br_on_null.wast, test/spec/call_ref.wast, test/spec/ref_as_non_null.wast
They were optional for a while to allow users to gracefully transition to using
them, but now make them mandatory to match the upstream WasmGC spec.
=> Make `call_ref` type annotations mandatory

CHANGELOG.md, src/wasm-binary.h, src/wasm-builder.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, test/lit/passes/dae_all-features.wast, test/lit/passes/gufa-refs.wast, test/lit/passes/inlining-optimizing.wast, test/lit/passes/local-cse_all-features.wast, test/lit/passes/optimize-instructions-call_ref-roundtrip.wast, test/lit/passes/optimize-instructions-call_ref.wast, test/lit/passes/precompute-gc.wast, test/lit/passes/remove-unused-module-elements-refs.wast, test/lit/passes/signature-pruning.wast, test/lit/passes/signature-refining.wast, test/lit/types-function-references.wast, test/lit/validation/nn-locals-bad-call_ref.wast, test/passes/Oz_fuzz-exec_all-features.wast, test/passes/duplicate-function-elimination_all-features.wast, test/spec/br_on_null.wast, test/spec/call_ref.wast, test/spec/ref_as_non_null.wast
Reverts WebAssembly/binaryen#5246
It looks like the necessary V8 change has not rolled out everywhere yet.
=> Revert "Make `call_ref` type annotations mandatory"

CHANGELOG.md, src/wasm-binary.h, src/wasm-builder.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, test/lit/passes/dae_all-features.wast, test/lit/passes/gufa-refs.wast, test/lit/passes/inlining-optimizing.wast, test/lit/passes/local-cse_all-features.wast, test/lit/passes/optimize-instructions-call_ref-roundtrip.wast, test/lit/passes/optimize-instructions-call_ref.wast, test/lit/passes/precompute-gc.wast, test/lit/passes/remove-unused-module-elements-refs.wast, test/lit/passes/signature-pruning.wast, test/lit/passes/signature-refining.wast, test/lit/types-function-references.wast, test/lit/validation/nn-locals-bad-call_ref.wast, test/passes/Oz_fuzz-exec_all-features.wast, test/passes/duplicate-function-elimination_all-features.wast, test/spec/br_on_null.wast, test/spec/call_ref.wast, test/spec/ref_as_non_null.wast
Reverts WebAssembly/binaryen#5265
It turns out that this revert was due to a false alarm.
=> Reland "Make `call_ref` type annotations mandatory"

src/tools/wasm-split/wasm-split.cpp
The previous error message was ambiguous and could easily be interpreted to mean
the opposite of what it meant.
=> [wasm-split] Improve the error message for bad checksums

src/emscripten-optimizer/optimizer-shared.cpp, src/emscripten-optimizer/optimizer.h, src/support/safe_integer.cpp
When `-Wheader-hygiene` is enabled, C compiler will warn when using namespace directive in global context in header file.
When `-Wimplicit-const-int-float-conversion` is enabled C compiler will warn on implicit integer to double conversions that change values.
=> Fix warnings that make build fail with -Werror,-Wheader-hygiene,-Wimplicit-const-int-float-conversion

src/wasm/wasm-type.cpp, test/gtest/type-builder.cpp
Fixes a longstanding problem with isorecursive canonicalization that only showed
up in MacOS and occasionally Windows builds. The problem was that
`RecGroupEquator` was not quite correct in the presence of self-references in
rec groups. Specifically, `RecGroupEquator` did not differentiate between
instances of the same type appearing across two rec groups where the type was a
self-reference in one group but not in the other.
The reason this only showed up occasionally on some platforms was that this bug
could only cause incorrect behavior if two groups that would incorrectly be
compared as equal were hashed into the same bucket of a hash map. Apparently the
hash map used on Linux never hashes the two problematic groups into the same
bucket.
=> Fix isorecursive canonicalization

src/passes/PostEmscripten.cpp
In this mode we don't remove the start/stop_em_asm symbols or data. This is because with side modules we read this information directly from the wasm binaryen at runtime.
See https://github.com/emscripten-core/emscripten/pull/18228
=> Add post-emscripten-side-module pass argument

src/support/path.cpp
std::string::back() is only well defined for non-empty strings.
Without the change, wasm-reduce fails if it is called from
$PATH, because then, the parent directory is an empty string.
A workaround is to explicitly set the binaryen path with -b,
but if wasm-reduce is in the $PATH, it can be reasonably assumed
that other binaryen binaries are available too, so an empty
path is inherently correct.
Example before the fix:
```
[sarna@sarna-pc binaryen]$ wasm-reduce -t test.wasm -w work.wasm
/usr/include/c++/12.2.0/bits/basic_string.h:1304: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::back() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; reference = char&]: Assertion '!empty()' failed. …
```
=> Avoid calling back() on an empty string in setBinaryenBinDir

src/passes/CodePushing.cpp, test/lit/passes/code-pushing-gc.wast, test/lit/passes/code-pushing_tnh.wast
Normally we ignore them anyhow (unreachability is an effect, either a trap or
a control flow switch), but in traps-never-happen mode we can ignore a trap, so
we need to check this manually.
Found by the fuzzer over the weekend after 500K iterations...
=> Code Pushing: Ignore unreachable sets

src/passes/CoalesceLocals.cpp, test/lit/passes/coalesce-locals-gc.wast
The testcase in #5287 led the fuzzer to quickly find a similar bug in another pass :smile:
=> [Wasm GC] Fix CoalesceLocals on tees that receive a refined type

src/passes/pass.cpp
Dumping the text is nice sometimes, but on huge testcases the wat can be 1 GB
in size (!), and so dumping one per pass can lead to using 20 GB or so for the full
optimization pipeline. Emit just the binary to avoid that.
=> Dump only the binary in pass-debug mode 3

src/tools/optimization-options.h, test/lit/help/wasm-opt.test, test/lit/help/wasm2js.test
The flag does nothing so far. My thinking is that we'll do this:
* Land this no-op flag.
* Get partners to pass the flag in (which will not error as there is this placeholder).
* Implement the flag, that is, make us open-world by default and make the flag switch to closed-world. This will not regress partners' performance since they pass the flag and so they are opting in to closed-world, making this part NFC for them.
See #5292
=> Add a placeholder closed-world flag

src/ir/type-updating.cpp, src/ir/type-updating.h
The logic that is split out into `mapTypes` gets a map of old type => new type and then
updates the module to replace the old with the new.
This will be useful in a future pass to merge types. We will tell it to map the types to
be merged with the types we want to merge them into.
This removes an assert on all types being in the map to allow some of them not to be.
(the new pass that will use this will only want to map some types).
=> [NFC] Refactor GlobalTypeRewriter to split out the type mapping logic

src/passes/GlobalTypeOptimization.cpp, test/lit/passes/Oz.wast, test/passes/Oz_fuzz-exec_all-features.txt, test/reduce/imports.wast.txt, test/reduce/memory_table.wast.txt, test/reduce/simple.wast.txt
As noticed in #5303, the test changes here are because we did unnecessary work
which created a new rec group, which then led to a rec group being printed out.
=> [NFC] Avoid unneeded work in GTO

src/wasm/wat-lexer.cpp, test/gtest/wat-lexer.cpp
In favor of the more portable code snippet using `std::copysign`. Also
reintroduce assertions that the NaNs have the expected signs. This continues
work started in #5302.
=> Remove more uses of NAN

src/wasm-type.h
We generalized the underlying API, TypeBuilder::setSubType, to allow it to take
any HeapType as the supertype in #5045. Make the same change now in the helper.
=> [NFC] Allow TypeBuilder::Entry::subTypeOf to take any HeapType

src/wasm/wat-lexer.cpp
MSVC's implementation of `strtod` doesn't return a negative Nan for "-nan", so
we already had a workaround to explicitly handle that case without calling
`strtod`. Unfortunately the workaround was not used for negative NaNs with
payloads, so there were still bugs. Fix the problem and make the code even more
portable by avoiding `strtod` completely for any kind of nan, positive or
negative, with or without payload.
=> [Parser] Avoid calling `strtod` on NaNs entirely

src/wasm/wasm-s-parser.cpp
wasm-s-parser.cpp was detecting the end of type strings by looking for null
characters, but those null characters would be past the end of the relevant
string_view. Bring that code in line with similar code by checking the length of
the string_view instead. Fixes an assertion failure in MSVC debug mode.
Fixes #5312.
=> [NFC] Do not read past the end of a string_view

CMakeLists.txt
This should unbreak the build. This is an old problem but was just noticed due to
a recent emscripten change (https://github.com/emscripten-core/emscripten/pull/18292).
=> binaryen.js: Properly export malloc/free

src/pass.h, src/passes/Asyncify.cpp, test/lit/passes/asyncify_enable-multivalue.wast, test/lit/passes/asyncify_mod-asyncify-always-and-only-unwind.wast, test/lit/passes/asyncify_mod-asyncify-never-unwind.wast, test/lit/passes/asyncify_optimize-level=1.wast, test/lit/passes/asyncify_pass-arg=asyncify-asserts_pass-arg=asyncify-onlylist@waka.wast, test/lit/passes/asyncify_pass-arg=asyncify-ignore-imports.wast, test/lit/passes/asyncify_pass-arg=asyncify-ignore-indirect.wast, test/lit/passes/asyncify_pass-arg=asyncify-imports@env.import,env.import2.wast
I tried to do what is described in #4822. I'm not sure if everything is correct, but it seems to work for my case. Compilation time was reduced from 14 minutes to 3.5 minutes and all my tests passed.
It's more like proposal, if idea is correct I can refactor as needed.
--
Related to [discussion](https://groups.google.com/g/emscripten-discuss/c/tpKmW0jLlmw/m/pFB9DSEGBQAJ?utm_medium=email&utm_source=footer)
=> #4822 optmize asyncify to not flatten/optimize unnecessarily

src/wasm/wat-parser.cpp
Previously we had types like `LocalT` and `MemoryT` to represent references to
locals and memories, but when we added field indices in #5255, we had to use
`FieldIdxT` instead of `FieldT` because `FieldT` was already in use as the type
representing a field itself. Update `LocalT`, `MemoryT` and `GlobalT` to have
`Idx` in their names to be consistent with `FieldIdxT`.
=> [Parser][NFC] Add `Idx` to type aliases representing indices

src/passes/Print.cpp, src/wasm-binary.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, src/wasm/wasm-stack.cpp, test/ctor-eval/gc-2.wast, test/ctor-eval/gc-2.wast.out, test/lit/passes/gufa-refs.wast, test/lit/passes/gufa-vs-cfp.wast, test/lit/passes/inlining-optimizing.wast, test/lit/passes/inlining_vacuum_optimize-instructions.wast, test/lit/passes/monomorphize.wast, test/lit/passes/optimize-casts.wast, test/lit/passes/optimize-instructions-call_ref.wast, test/lit/passes/optimize-instructions-gc-iit.wast, test/lit/passes/optimize-instructions-gc-tnh.wast, test/lit/passes/optimize-instructions-gc.wast, test/lit/passes/precompute-gc.wast, test/lit/passes/rse-gc.wast, test/lit/passes/signature-pruning.wast, test/lit/passes/simplify-locals-gc.wast, test/passes/Oz_fuzz-exec_all-features.wast, test/spec/ref_cast.wast
We switched from emitting the legacy `ref.cast_static` instruction to emitting
`ref.cast null` in #5331, but that wasn't quite correct. The legacy instruction
had polymorphic typing so that its output type was nullable if and only if its
input type was nullable. In contrast, `ref.cast null` always has a a nullable
output type.
Fix our output by instead emitting non-nullable `ref.cast` if the output should
be non-nullable. Parse `ref.cast` in binary and text forms as well. Since the IR
can only represent the legacy polymorphic semantics, disallow unsupported casts
from nullable to non-nullable references or vice versa for now.
=> Use non-nullable ref.cast for non-nullable input

src/passes/GlobalStructInference.cpp, test/lit/passes/gsi.wast
If a global's type is not fully refined, then when `--gsi` replaces a reference with
a `global.get`, we end up with a type that might not be good enough. For example,
if the type is `any` then it is not a subtype of `eq` and we can't do `ref.eq` on it, which
this pass requires. We also can't just do `struct.get` on it if it is a too-distant parent
or such.
=> [Wasm GC] Fix GlobalStructInference on unrefined globals

scripts/gen-s-parser.py, src/gen-s-parser.inc
The `op` string_view was intentionally created to point into the `buf` buffer so
that reading past its end would still be safe, but some C++ standard library
implementations assert when reading past the end of a string_view. Change the
generated code to read out of `buf` instead to avoid those assertions.
Fixes #5322.
Fixes #5342.
=> Fix OOB string_view read in generated parser code

CHANGELOG.md, src/tools/optimization-options.h, src/tools/wasm-opt.cpp, test/unit/test_passes.py
Previously `-O3 -O1` would run `-O1` twice since the last flag set the global opt level
to 1, and then all invocations of the optimizer pipeline read that. This makes each
pipeline define its own opt level.
This has been a long-standing annoyance, which wasn't much noticed except that
with wasm GC there is more of a need to run the optimization pipeline more than
once. And sometimes it is nice to run different levels.
=> Fix opt/shrink levels when running the optimizer multiple times

test/gtest/wat-lexer.cpp
MSVC is making `NAN` negative, so use an explicitly constructed positive NaN
instead.
=> Replace more uses of `NAN`

src/passes/MultiMemoryLowering.cpp
This PR breaks up the two main functions involved in each memory instruction (getPtr, makeBoundsCheck) into several smaller functions. This is a first step in adding support for bounds checks in the instructions memory: init, copy, and fill. Each of these instructions is a more unique case than the other memory instructions that have already been added to the Multi-Memory Lowering pass.
=> Refactor Multi-Memory Lowering pass to support additional instructions

src/passes/MultiMemoryLowering.cpp, test/lit/passes/multi-memory-lowering.wast
This PR adds support for [memory.init](https://webassembly.github.io/spec/core/exec/instructions.html#xref-syntax-instructions-syntax-instr-memory-mathsf-memory-init-x), [memory.copy](https://webassembly.github.io/spec/core/exec/instructions.html#xref-syntax-instructions-syntax-instr-memory-mathsf-memory-init-x), and [memory.fill](https://webassembly.github.io/spec/core/exec/instructions.html#xref-syntax-instructions-syntax-instr-memory-mathsf-memory-fill) instructions in the multi-memory lowering pass. Also includes optional bounds checks per the wasm spec guidelines.
Note: This PR depends on the refactor from https://github.com/WebAssembly/binaryen/pull/5352 landing first.
=> Add memory: init, copy, fill support to Multi-Memory Lowering Pass 

scripts/fuzz_opt.py
A initial content testcase may only work in open world, so check for that
using the existing mechanism of checking if such testcases work with out
feature flags.
=> Fixed fuzzing of closed-world after #5347

src/passes/MultiMemoryLowering.cpp
Moving the assert that checks whether the DataSegment* offset type is Const. This assert only needs to happen when the DataSegment belongs to a memory other than the first.
=> Move assert in MultiMemoryLowering

src/wasm/wat-parser.cpp
For each definition in a module, record that definition's index in the relevant
index space. Previously the index was inferred from its position in a list of
module definitions, but that scheme does not scale to data segments defined
inline inside memory definitions because these data segments occupy a slot in
the data segment index space but do not have their own independent definitions.
=> [NFC][Parser] Track definition indices

scripts/fuzz_opt.py
Do not fuzz some new testcases that have imported memories. The fuzzer doesn't seem
to have support for that (it errors when it tries to do operations on them, since the
import hasn't been created).
=> Skip some new initial content in the fuzzer, with imported memories

src/passes/pass.cpp
Without the names section debugging can be hard sometimes, on the binaries
that that mode emits for each pass.
Perhaps other cases are better without the names section, so maybe we'll need
a flag? But for now hopefully this will be ok.
=> Write debug info in Pass-Debug mode 3

scripts/fuzz_opt.py, src/passes/OptimizeInstructions.cpp, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, src/wasm/wasm-validator.cpp, src/wasm/wasm.cpp, test/lit/passes/optimize-instructions-gc.wast, test/spec/ref_cast.wast
This new cast configuration was not expressible with the legacy cast
instructions. Although it is valid in Wasm, do not allow nullable casts of
non-nullable references, since those would unnecessarily lose type information.
Convert such casts to be non-nullable in the parsers and during expression
finalization.
Fixes #5382.
=> Allow non-nullable ref.cast of nullable references

src/pass.h, src/passes/OptimizeInstructions.cpp, src/wasm2js.h, test/wasm2js/target_js.2asm.js, test/wasm2js/target_js.2asm.js.opt, test/wasm2js/target_js.wast
As noted in #4806, trying to optimize past level 0 can result in passes emitting non-JS code, which is then unable to be converted during final output.
This commit creates a new targetJs option in PassOptions, which can be checked inside each pass where non-JS code might be emitted.
This commit initially adds that logic to OptimizeInstructions, where this issue was first noticed.
=> wasm2js: Avoid emitting non-JS code during opt

scripts/gen-s-parser.py, src/gen-s-parser.inc, src/wasm-builder.h, src/wasm/wat-parser.cpp, test/lit/wat-kitchen-sink.wast
Parse both the folded and unfolded forms of blocks and structure the code to
make supporting additional block instructions like if-else and try-catch
relatively simple.
Parsing block types is extra fun because they may implicitly define new
signature heap types via a typeuse, but only if their types are not given by a
single result type. To figuring out whether a new type may be introduced in all
the relevant parsing stages, always track at least the arity of parsed results.
The parser parses block labels, but more work will be required to support branch
instructions that use them.
=> [Parser] Parse blocks

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-gc.wast
`visitRefCast` can use `trapOnNonNull`. To make this not regress, add fallthrough
analysis there as well.
Minor test changes are due to `trapOnNonNull` using `getDroppedChildren` which
only emits drops of necessary children. It also tells us to refinalize so it is ok for it
to change the type to unreachable.
=> [Wasm GC] Clean up null trap and cast optimizations

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-gc-tnh.wast
This fixes an oversight in #5395 - other children might have effects we need to
care about. See details in the new comment.
=> [Wasm GC] Fix non-nullable cast optimizations with multiple children

src/binaryen-c.cpp, src/binaryen-c.h, src/ir/gc-type-utils.h, src/ir/module-utils.cpp, src/passes/Print.cpp, src/passes/RemoveUnusedBrs.cpp, src/wasm-binary.h, src/wasm-builder.h, src/wasm-delegations-fields.def, src/wasm.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, src/wasm/wasm-stack.cpp, src/wasm/wasm-validator.cpp, src/wasm/wasm.cpp, test/lit/cast-to-basic.wast, test/lit/passes/remove-unused-brs-gc.wast, test/passes/Oz_fuzz-exec_all-features.txt, test/passes/Oz_fuzz-exec_all-features.wast, test/spec/ref_cast.wast
As well as br_on_cast_fail null. Unlike the existing br_on_cast* instructions,
these new instructions treat the cast as succeeding when the input is a null.
Update the internal representation of the cast type in `BrOn` expressions to be
a `Type` rather than a `HeapType` so it will include nullability information.
Also update and improve `RemoveUnusedBrs` to handle the new instructions
correctly and optimize in more cases.
=> Support br_on_cast null

src/passes/OptimizeInstructions.cpp, src/tools/fuzzing/fuzzing.cpp, test/lit/passes/optimize-instructions-gc.wast
We were checking the heap type, but now casts care about the nullability as
well.
If the nullability is the only problem, that is, the heap type will be fine but we
might have a null, we can at least switch a `ref.cast` (non-null) to a
`ref.as_non_null`.
I believe this might be related to recent cast/null changes. Found by the fuzzer.
=> [Wasm GC] Fix optimizations on ref.cast of null, and optimize to ref.as_non_null

src/ir/gc-type-utils.h, test/lit/passes/remove-unused-brs-gc.wast
We were considering casts between unrelated types as unconditionally failing,
but in the case where the unrelated types are nullable, the cast could still
succeed if the value is null.
This bug was introduced in #5397.
=> Fix a bug optimizing out br_on_cast

src/passes/Vacuum.cpp, test/lit/passes/vacuum-gc.wast
We use TypeUpdater there, which handles updating unreachability. But with wasm GC
we also need to refinalize if we refine types. Somehow, this was not noticed until now,
but the new `ref.cast null` assertion on not losing type info was enough to uncover
this long-existing issue.
Noticed in #5406 but it is likely not the core issue.
=> [Wasm GC] Refinalize in Vacuum

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-gc-tnh.wast
This handles the flip case of a nullable cast of `ref.as_non_null` which we already handled.
=> [Wasm GC] Optimize ref.as_non_null of a nullable cast

src/wasm/wasm.cpp, test/lit/passes/dce_all-features.wast
Without this we hit an assertion on unreachable not being a heap type.
=> [Wasm GC] Handle an unreachable br_on_cast_fail in DCE

src/js/binaryen.js-post.js
Error on CI that this should fix:
https://github.com/WebAssembly/binaryen/actions/runs/3894806501/jobs/6649299612
I am a little unclear as to why the error began on CI here... the emcc tot build has not been updated in a while as the roller is stalled (at least 6 days it seems). But this error began just over the last 24 hours somehow..? Anyhow, this fix is necessary given the change to remove this var.
=> [binaryen.js] Avoid use of the global buffer var which emcc has removed

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-gc-tnh.wast
`skipCast` takes an optional parameter that bounds how general the resulting
type is allowed to be. That parameter previously had a default value of `anyref`
with the intention of allowing all casts to be skipped, but that default
inadvertently prevented any casts in the `func` or `extern` type hierarchies
from being skipped. Update `skipCast` so that the default parameter allows all
casts to be skipped in all hierarchies.
=> [Wasm GC] Generalize `skipCast` to work with all type hierarchies

src/passes/TypeMerging.cpp, test/lit/passes/type-merging.wast
The cast finding code in TypeMerging has been broken since we refactored how
casts work to support nullable casts. The cast finding code only considered
HeapType fields and the return type of `RefCast` to be potential cast targets,
but `RefTest` and `BrOn` instructions now store their cast types as `Type`
fields. Since cast targets are represented more heterogenously now, do not use
the delegations macros to find them.
Add tests showing that each cast instruction independently inhibits merging.
=> [Wasm GC] Fix cast finding in TypeMerging

src/ir/gc-type-utils.h, src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-gc.wast
Instead of only looking at the final fallthrough value and seeing whether it is
a `RefNull` expression to determine if we are casting a null value, check the
type of each intermediate fallthrough value to see if it is a null reference.
Also improve `evaluateCastCheck` to return `Failure` instead of
`SuccessOnlyIfNonNull` if the cast value is a reference to bottom type, since
those can never be non-null.
=> [Wasm GC] Optimize casts of null values better

src/ir/properties.h, src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-gc.wast
Optimize ref.cast instructions that must succeed by simply replacing them with
their child in the case where the child has a more refined type or by
propagating a further removed fallthrough value with a more refined type using a
tee.
=> [Wasm GC] Optimize successful casts better

src/tools/optimization-options.h, src/tools/tool-options.h, test/lit/help/wasm-as.test, test/lit/help/wasm-ctor-eval.test, test/lit/help/wasm-dis.test, test/lit/help/wasm-emscripten-finalize.test, test/lit/help/wasm-metadce.test, test/lit/help/wasm-opt.test, test/lit/help/wasm-reduce.test, test/lit/help/wasm-split.test, test/lit/help/wasm2js.test
This allows tools like wasm-reduce to be told to operate in closed-world mode. That
lets them validate in the more strict way of that mode.
=> Move closed world flag to tool options

src/passes/SignaturePruning.cpp, test/lit/passes/signature-pruning.wast
For subtyping to not break, we must leave the number of fields equal in both
super and subtype, for each such pair.
=> [Wasm GC] SignaturePruning should not prune fields from a type with subtypes

src/passes/RemoveUnusedModuleElements.cpp
Before, we'd potentially add a new item to the queue multiple times, then
do nothing when popping it from the queue in the second and later times.
With this PR we add a new item to the reachable set and to the queue at
the same time, so items cannot appear more than once in the queue.
(diff without whitespace is smaller)
=> [NFC] Work a little more efficiently in RemoveUnusedModuleElements

src/support/CMakeLists.txt, src/support/dfa_minimization.cpp, src/support/dfa_minimization.h, test/gtest/CMakeLists.txt, test/gtest/dfa_minimization.cpp
We used to have this algorithm in wasm-type.cpp, where we used it to implement
equirecursive type canonicalization, but we removed it when we removed
equirecursive typing. Bring the algorithm back as a standalone utility for
future use in optimization passes. In particular, it will be useful in
TypeMerging for identifying the greatest fixed point of mergeable types rather
than the smallest fixed point.
=> Add Valmari-Lehtinen DFA minimization as a standalone utility

src/ir/type-updating.cpp, src/passes/TypeMerging.cpp, src/wasm-type-ordering.h
type-updating.cpp implemented a topological sorts on heap types that would visit
supertypes first. Since this same sort will be used by TypeMerging.cpp in #5432,
factor it out into a shared utility in a new wasm-type-ordering.h header.
At the same time, fix a bug in which the sort would visit types not in the input
collection. Concretely, this bug would cause public supertypes of private types
to be visited when only private types should have been visited. This
functionality change will be tested in #5432.
In principle the subtype-first sort used in subtypes.h could also be moved to
this header, but that is not yet duplicated in the code base and is more
efficient because it depends on implementation details of its current context,
so do not move it for now.
=> Factor supertype-first type sort into separate header

src/ir/type-updating.cpp, src/passes/TypeMerging.cpp, src/wasm-type-ordering.h, test/lit/passes/type-merging.wast
GlobalTypeRewriter made sure to order supertypes before their subtypes so that
type building would succeed, but this ordering previously did not account for
the fact that supertypes might be replaced by the type updating. When a
supertype is replaced, the replacement might not previously have had a
supertype/subtype relationship with the subtype, so it might have happened to be
ordered after the subtype.
Fix the problem by taking supertype replacements into account when ordering
types in the GlobalTypeRewriter. This requires generalizing the
`SupertypesFirst` utility in wasm-type-ordering.h to allow users to modify how
supertypes are found.
=> [Wasm GC] Fix supertype ordering bug in GlobalTypeRewriter

src/ir/flat.h
`doVisitFunction` does not exist, and we don't have static checking of that
sadly. Could `overrides` work here..?
=> Fix a typo in Flat IR validation logic

src/passes/TypeMerging.cpp, test/lit/passes/type-merging.wast
TypeMerging was previously able to merge identical root types and identical
siblings that were children of a distinct type, but only when the siblings had
the same top-level structure as their parent. Improve the optimization by also
merging identical children when they have a different top-level structure from
their parent.
This solution is not fully general because it does not merge shape-refining
children of separate types that would become identical siblings only after their
parent types are merged, but that full generality would require either
modifying Valmari-Lehtinen DFA minimization or performing the DFA minimization
in a loop until reaching a fixpoint.
=> Merge more sibling types in TypeMerging

src/wat-lexer.h
This fixes the following error when compiling with GCC 13:
```
In file included from /builddir/build/BUILD/binaryen-version_111/test/gtest/wat-lexer.cpp:19:
/builddir/build/BUILD/binaryen-version_111/src/wat-lexer.h:62:3: error: 'uint64_t' does not name a type
62 |   uint64_t n;
|   ^~~~~~~~
/builddir/build/BUILD/binaryen-version_111/src/wat-lexer.h:24:1: note: 'uint64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
23 | #include <variant>
+++ |+#include <cstdint>
...
```
This is required before #5456 can be reproduced.
=> add explicit include for <cstdint>

src/wasm/wasm-type.cpp
Use an `IndexedTypeNameGenerator` to give types stable names for the entire
`dump` method rather than generating fresh type names every time a single type
is printed. This makes it possible to understand the relationships between the
types in the debug output.
=> [NFC] Improve debug printing for type canonicalization

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-mvp.wast
We only checked for an unsigned overflow, which was wrong.
Fixes #5464
=> OptimizeInstructions: Handle signed overflow properly in canOverflow()

src/passes/RemoveUnusedModuleElements.cpp, test/lit/passes/remove-unused-module-elements-refs.wast
When we see a `call_ref` or `call_indirect` of a heap type, we might be calling a
subtype of that type.
=> RemoveUnusedModuleElements: Support function subtyping

src/passes/RemoveUnusedModuleElements.cpp, test/lit/passes/remove-unused-module-elements-refs.wast
If we see
```wat
(struct.new $A
(call $call.without.effects ;; intrinsic
(ref.func $getter)
)
)
```
then we can ignore side effects in that call, as the intrinsic tells us to. However,
that function is still called (it will be called normally, after intrinsics are lowered
away), and we should not remove it.
We can perhaps do better here, but I'm not sure yet. Leaving that as a TODO.
This fixes breakage on J2Wasm.
=> [Wasm GC] Fix RemoveUnusedModuleEffects struct field reads with call.without.effects

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-gc-tnh.wast
If traps can happen, then we can't always remove a trap on null
on the ref input to `struct.set`, since it has two children,
```wat
(struct.set
(ref.as_non_null X)
(call $foo))
```
Removing the `ref.as` would not prevent a trap, as the `struct.set`
will trap, but it does move the trap to after the call which is bad.
=> [Wasm GC] Fix struct.set / ref.as_non_null ordering issue

CMakeLists.txt, scripts/test/binaryenjs.py
This is useful for wasm performance (and for size tests, since Emscripten EH makes the binary unnecessarily slow and large).
=> Add a CMake flag to enable Wasm exceptions in the BinaryenJS build

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-gc-tnh.wast
Followup to #5474 - turns out it's simple. And probably worth doing as tees are
common.
=> Optimize ref.as_non_null removal effect computation

src/wasm-delegations-fields.def, src/wasm/wasm-binary.cpp, src/wasm/wasm-stack.cpp, test/lit/ref-cast-nop.wast
It did not have proper annotation for the safety field, and also
it could not handle basic heap types.
If we don't want to fix the latter in this way, we would need to
have optimization passes check `safety`, since the reason I noticed
this is that CastRefining will turn casts to cast to null, which then
errors for the `_nop` variant.
Is this even still needed, I wonder?
=> Fix issues with ref.cast_nop

src/passes/Vacuum.cpp, test/lit/passes/vacuum-gc.wast, test/passes/vacuum_all-features.txt, test/wasm2js/left-to-right.2asm.js
This can handle e.g.
```wat
(drop
(i32.add
(call ..)
(call ..)
)
)
```
We can remove the add and just leave two dropped calls:
```wat
(drop
(call ..)
)
(drop
(call ..)
)
```
=> Vacuum unneeded instructions even if children have effects

src/passes/Inlining.cpp, test/lit/passes/inlining-optimizing_optimize-level=3.wast, test/lit/passes/inlining-unreachable.wast, test/lit/passes/inlining_enable-tail-call.wast, test/lit/passes/inlining_optimize-level=3.wast
We must refinalize as inlining unreachable code can lead to
more things becoming unreachable.
We also must uniquify label names before refinalizing, as the
IR must be valid at that time, so that code is moved.
This causes some minor changes to existing test code (some
label changes, and refinalization makes more things
unreachable), but only the two new tests show actual problems
that needed to be fixed.
Found by fuzzing with a local patch to improve fuzzing of
unreachable code (PR to come).
=> Unreachability fixes for inlining

src/passes/Inlining.cpp, test/lit/passes/inlining-unreachable.wast, test/lit/passes/inlining_all-features.wast, test/lit/passes/inlining_enable-tail-call.wast, test/lit/passes/inlining_optimize-level=3.wast, test/lit/passes/inlining_splitting.wast
See example in the new comment. In general, we never want to go from
unreachable to reachable (refinalize doesn't even try), as it misses out on
DCE opportunities. Also it may have validation issues, which is how the
fuzzer found this.
Remove code in the same place that was redundant after the refinalize
was added in #5492. That simplifies some existing testcases slightly, by
removing an unneeded `br` we added, and now we add a new `unreachable`
at the end in other cases that need it.
=> Never flip a call from unreachable to reachable during inlining

src/tools/fuzzing/fuzzing.cpp
This is necessary to avoid fuzzer breakage after #5497 as it added a test with
strings. We could also ignore that file, like we do for other string files, but this
was not much work so just implement it.
=> [Strings] Start some basic fuzzing support for strings

src/wasm-binary.h, src/wasm-stack.h, src/wasm/wasm-binary.cpp, test/fib-dbg.wasm.fromBinary, test/lit/source-map.wast
fix: [5503](https://github.com/WebAssembly/binaryen/issues/5503)
=> fix: sourcemap generation for call instruction

.github/workflows/ci.yml
The runner ubuntu-latest is Ubuntu 22, which no longer use llvm-8, so this PATH can be remoted.
This llvm-8 here is misleading. Some developers spend a lot of time to compile llvm-8 from source, because llvm-8 is not available in new Ubuntu apt. But actually CI is not using llvm-8.
=> remote unnecessary echo PATH in CI

scripts/fuzz_opt.py
After the recent improvements and fixes this is now simple and the fuzzer found
no more issues overnight for me.
Also adjust some existing frequencies in ways I think make sense.
=> Fuzzing: Add wasm-ctor-eval fuzzing in fuzz_opt.py

src/wasm2js.h, test/wasm2js/atomics_32.2asm.js, test/wasm2js/atomics_32.2asm.js.opt, test/wasm2js/atomics_32.wast
Without this fix, the common idiom of using `INT_MAX` in C source to mean an
unlimited number of waiters should be woken up actually compiled down to an
argument of -1 in JS, causing zero waiters to be woken.
=> [wasm2js] Fix atomic notify to take an unsigned count

src/wasm-stack.h, test/lit/source-map.wast
With this, the sourcemap testcase outputs the exact same thing as the input.
Followup to #5504
cc @JesseCodeBones
=> Emit source map information for control flow structures

src/tools/fuzzing/fuzzing.cpp
Line 1980/1981 below is where we use a RefAs. We need to avoid getting
there if we are not in a function.
=> Fuzzer: Only use RefAs in a function context

scripts/fuzz_opt.py, src/tools/execution-results.h
We handle this like the existing handling of TrapException: we skip running
this module (since we can't even instantiate it, so there is nothing to run).
=> Fuzzer: Handle HostLimitException during instance creation

src/wasm/wasm-type.cpp, test/lit/validation/ref-func-multivalue.wast
This was not noticed before because normally if there is a function type
with multiple results then there is also a function with that property. But
it is possible to make small testcases without such a function, and one might
be imported etc., so we do need to validate this.
=> Function types with multiple results require multivalue

src/tools/fuzzing/fuzzing.cpp
Only very rarely ask to create a huge array, as that can easily hit a host
size limit and cause a run to be ignored.
=> Fuzzer: Be careful with ArrayNew sizes

src/tools/fuzzing/heap-types.cpp, src/tools/fuzzing/heap-types.h, src/tools/wasm-fuzz-types.cpp, src/wasm-type.h, src/wasm/wasm-type.cpp, test/lit/fuzz-types/isorecursive.test, test/lit/fuzz-types/nominal.test
Some valid GC types, such as non-nullable references to bottom heap types and
types that contain non-nullable references to themselves, are uninhabitable,
meaning it is not possible to construct values of those types. This can cause
problems for the fuzzer, which generally needs to be able to construct values of
arbitrary types.
To simplify things for the fuzzer, introduce a utility for transforming type
graphs such that all their types are inhabitable. The utility performs a DFS to
find cycles of non-nullable references and breaks those cycles by introducing
nullability.
The new utility is itself fuzzed in the type fuzzer.
=> Add a fuzzer utility for ensuring types are inhabitable

src/wasm-type.h, src/wasm/wasm-type.cpp, test/lit/validation/ref-func-simd.wast, test/lit/validation/ref-gc-simd.wast
As with #5535, this was not noticed because it can only happen on very
small modules where the param/result type appears nowhere else but
in a function signature, but my wip fuzzer branch now finds it.
=> Note function signature param/result features for validation

src/passes/SignatureRefining.cpp, test/lit/passes/signature-refining.wast
For now just skip them, to avoid problems. In the future we should look
into modifying their children, when possible.
Fixes #5463
=> [Wasm GC] Skip types with subtypes in SignatureRefining

src/tools/fuzzing/heap-types.cpp, src/tools/wasm-fuzz-types.cpp
Function references are always inhabitable because functions can be created with
any function type, even types that refer to uninhabitable types. Take advantage
of this by skipping function references when finding non-nullable reference
cycles that cause uninhabitability.
=> Skip function references when detecting uninhabitable types

src/passes/SignatureRefining.cpp, test/lit/passes/signature-refining.wast
We'd need to handle contravariance to optimize them.
=> SignatureRefining: Skip types with supertypes for now

src/tools/fuzzing/heap-types.cpp, src/tools/fuzzing/heap-types.h, src/tools/wasm-fuzz-types.cpp
The main fuzzer needs to be able to filter out uninhabitable types and the type
fuzzer has code for finding uninhabitable types. Move and refactor the code to
expose a `getInhabitable` function that can be used for both purposes.
=> Refactor type fuzzer to expose `getInhabitable` API

src/tools/fuzzing.h, src/tools/fuzzing/fuzzing.cpp, test/passes/fuzz_metrics_noprint.bin.txt, test/passes/translate-to-fuzz_all-features_metrics_noprint.txt
Previously we emitted it early, and would then modify it in random ways
like other initial content. But this function is called frequently during
execution, so if we were unlucky and modded that function to trap then
basically all other functions would trap as well.
After fixing this, some places assert on not having any functions or types
to pick a random one from, so fix those places too.
=> Emit the fuzzer hashMemory function after modifications

scripts/fuzz_opt.py
If the program tries to allocate an infinite number of objects, but is
prevented from doing that by a null pointer trap, then after we run
with trapsNeverHappen the trap may fail to occur, and we'll hit the
host limitation on allocations. As a result, we'd be comparing one
run with a trap and one run that is meant to be ignored (as we ignore
runs with host limitations), and before this PR we'd error as we would
expect to find the normal output and not the "ignore this host
limitation" marker.
=> TrapsNeverHappen fuzzing: Handle a trap vs a host limitation

src/tools/fuzzing.h, src/tools/fuzzing/fuzzing.cpp, test/passes/translate-to-fuzz_all-features_metrics_noprint.txt
In particular, the removed code path here that did a RefAsNonNull of a null
was causing a lot of code to just trap.
=> Fuzzer: Emit nulls with low probability in makeConstCompoundRef

src/ir/iteration.h
The missing associated types will become necessary if we ever use these
iterators in a nontrivial manner. Make the parent reference into a pointer so
that the copy constructor and assignment operator are not implicitly deleted.
=> [NFC] Add missing parts of `ChildIterator`

src/tools/fuzzing/fuzzing.cpp, test/passes/translate-to-fuzz_all-features_metrics_noprint.txt
Only rarely return an uninhabitable subtype of an inhabitable one. This
avoids a major source of uninhabitability and immediate traps.
=> Fuzzer: Emit fewer uninhabitable types in getSubType

src/support/parent_index_iterator.h
When resolving `operator!=`, C++20 also considers `operator==` implementations
when the types on `operator!=` do not match exactly. This caused the modified
code to have no most-specific overload to choose, resulting in an error. This is
actually a bug in the language that is being fixed, but there exist compilers
without the fix applied.
Work around the problem by updating the types in the declaration of `operator==`
and `operator!=` to be more exact.
This is a copy of #5029 with formatting fixes.
=> Fix ambiguous operators under C++20

src/tools/fuzzing/fuzzing.cpp, src/tools/fuzzing/parameters.h, test/passes/translate-to-fuzz_all-features_metrics_noprint.txt
Even with a 1% chance of a huge array, there is a second problem aside from
hitting an allocation failure, which is DoS - building such a huge array of
Literals takes noticeable time in the fuzzer. Instead, just limit array max sizes,
which is consistent with what we do for struct sizes etc.
=> Fuzzer: Limit array sizes

src/tools/fuzzing/fuzzing.cpp
The fuzzer had code to avoid emitting `global.get` of locally defined (i.e.
non-imported) globals in global initializers and data segment offsets, but that
code only handled top-level `global.get` because it predated the extended-const
proposal. Unfortunately this bug went undetected until #5557, which fixed the
validator to make it reject invalid uses of `global.get` in constant
expressions.
Fix the bug so the validator no longer produces invalid modules.
=> Fix fuzzer emitting invalid constant expressions

src/wasm-interpreter.h, test/lit/passes/precompute-gc.wast
StructSet and Array operations are all handled already, so this was the
one missing case.
=> [Wasm GC] Properly handle packed field truncation in StructNew

scripts/fuzz_opt.py
For example, we might hit an allocation limit in the wasm, but the
optimized wasm might optimize that allocation out. So we need to
ignore comparisons in such cases, as we cannot expect the output
to be identical. We already do similar things for FuzzExec and
#5560 adds it for TrapsNeverHappen; this adds it to CompareVMs.
=> Fuzzer: CompareVMs: Do not compare when hitting a host limitation

scripts/fuzz_opt.py, src/passes/TypeMerging.cpp, src/wasm-type-printing.h, test/lit/passes/type-merging.wast
TypeMerging previously tried to merge types with their supertypes and siblings
in a single step, but this could cause a misoptimization in which a type was
merged with its parent's sibling without being merged with its parent, breaking
subtyping.
Fix the bug by merging with supertypes and siblings separately. Since we now
have multiple merging steps, also take the opportunity to run the sibling
merging step multiple times to exploit more merging opportunities.
Fixes #5556.
=> Fix misoptimization in TypeMerging

src/passes/Print.cpp, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, src/wasm/wasm-validator.cpp, test/spec/bulk-array.wast
Add spec/bulk-array.wast, which contains an outline of the tests that will be
necessary for the upcoming bulk array instructions: array.copy (already
implemented), array.fill, array.init_data, and array.init_elem. Although the
test file does not actually contain any tests yet, it contains some setup code
defining types, globals, and element segments that the tests will use. Fix
miscellaneous bugs in parsing, validation, and printing to allow this setup code
to run without issues.
=> Add bulk-array.wast spec test outline

src/mixed_arena.h, src/wasm-builder.h
Replace the different overloads we previously had for different kinds of
containers with generic templates. We still need dedicated overloads for
`std::initializer_list` because it is never inferred in a template context,
though. Also, since `std::initializer_list` does not allow subscripting, update
the arena vector implementation to use iterators instead now that initializer
lists can be passed down to that layer without being reified as vectors.
=> [NFC] Templatize `makeBlock` so it can be used with any iterable

src/tools/fuzzing/fuzzing.cpp, src/wasm/wasm-binary.cpp, test/passes/translate-to-fuzz_all-features_metrics_noprint.txt
Before this PR we iterated over an unordered set. Replace that with an
iteration on a vector. (Also, the value in the set was not even used, so
this should even be faster.)
Add random names in the fuzzer to types, the lack of which is I believe
the reason this was not detected before.
=> Ensure a deterministic order in the type names section

src/ir/properties.cpp, src/ir/properties.h, test/lit/passes/type-ssa.wast
Both `isValidInConstantExpression` and `isSingleConstantExpression` must look
recursively at the internals of a RefAs that externalizes and internalizes, or else
we might do something like externalize a `local.get`, which is not constant.
`getLiteral` must handle externalize/internalize as well, and return a properly-
modified literal.
Without these fixes the testcase hits different internal assertions, and we either
fail to recognize something is constant or not, or think that it is but fail to
produce a literal for it.
=> [Wasm GC] Fix detection of externalize/internalize as constant

src/passes/GenerateDynCalls.cpp
=> Properly error on multivalue returns in GenerateDynCalls

src/passes/MergeBlocks.cpp
This makes the pass 2-3% faster in some measurements I did locally.
Noticed when profiling for https://github.com/WebAssembly/binaryen/issues/5561#issuecomment-1470783261
Helps https://github.com/WebAssembly/binaryen/issues/4165
=> Use a SmallVector in MergeBlocks [NFC]

scripts/fuzz_shell.js
I saw a testcase fail on the internal assertion of the buffer being too small.
Enlarge it to use as much of the memory we have anyhow to reduce that
risk (we can use 15 pages instead of 1, without changing anything else).
=> Use more than a single wasm page in Asyncify fuzzing

src/passes/MemoryPacking.cpp, test/lit/passes/memory-packing_all-features.wast
Fix the relevant pointer and size expressions produced by MemoryPacking to be
i64s when working with 64-bit memories.
Fixes #5578.
=> Support memory64 in MemoryPacking

src/passes/RemoveUnusedModuleElements.cpp, src/wasm/wasm-validator.cpp, test/lit/passes/remove-unused-module-elements_all-features.wast, test/wasm2js/atomic_fence.2asm.js
Update RemoveUnusedModuleElements so that it no longer keeps the memory alive
due to an `atomic.fence` instruction and update validation to allow modules to
use `atomic.fence` without a memory.
=> Do not treat `atomic.fence` as using a memory

scripts/fuzz_opt.py
This is the default, and also used by J2Wasm.
Fuzzing for a day with this I found no issues.
=> Switch fuzzer to the hybrid type system

scripts/fuzz_opt.py
I ran CheckDeterminism at full throttle overnight (set to 1, and disabled
all other things) and it found a bug, so we should focus on that more.
Also ctor-eval as there is ongoing work there.
I reduced a few other priorities of things that haven't seen bugs in a
very long time and are not high priority.
=> Adjust fuzzer frequencies

src/binaryen-c.cpp, src/cfg/Relooper.cpp, src/passes/Asyncify.cpp, src/passes/I64ToI32Lowering.cpp, src/passes/JSPI.cpp, src/passes/LegalizeJSInterface.cpp, src/passes/OptimizeAddedConstants.cpp, src/passes/ReReloop.cpp, src/passes/RemoveNonJSOps.cpp, src/passes/StackIR.cpp, src/passes/TrapMode.cpp, src/support/threads.cpp, src/support/utilities.h, src/tools/wasm-reduce.cpp, src/tools/wasm2js.cpp, src/wasm/wasm-binary.cpp, src/wasm/wasm-io.cpp, src/wasm/wasm-s-parser.cpp, src/wasm/wasm-validator.cpp, src/wasm2js.h
This code predates our adoption of C++14 and can now be removed in favor of
`std::make_unique`, which should be more efficient.
=> [NFC] Remove our bespoke `make_unique` implementation

src/wasm/wasm-stack.cpp
This is necessary to start fuzzing RefCast etc., as otherwise the fuzzer
errors on V8 which has already removed support for the deprecated
ones apparently.
Do not remove read support for them yet, as perhaps some users
still need that.
=> [Wasm GC] Stop emitting deprecated cast etc. instructions

src/wasm-module-building.h
Followup to #5613
Not sure how this builds for us, but it breaks on the J2Wasm roll on `make_unique` not being declared.
=> Fix a call to make_unique without std

src/wasm/wasm-s-parser.cpp, test/lit/isorecursive-good.wast, test/lit/wat-kitchen-sink.wast
The pretty-printer will still serialize these using the old func_subtype, array_subtype, and struct_subtype syntax, though.
=> [Wasm GC] Parse (sub $super _) for array, func, and struct

src/ir/type-updating.h, test/lit/passes/dce_all-features.wast
That code should only propagate unreachability, and not refine. If it refines when
we call `finalize()` then other code around it might end up invalid (as it could be
partially refined).
=> [Wasm GC] Avoid refining in TypeUpdating unreachability propagation

src/passes/RemoveUnusedModuleElements.cpp, src/wasm/wasm-validator.cpp, test/lit/passes/remove-unused-module-elements_all-features.wast
Add support for memory and data segment module elements and treat them uniformly
with other module elements rather than as special cases. There is a cyclic
dependency between memories (or tables) and their active segments because
exported or accessed memories (or tables) keep their active segments alive, but
active segments for imported memories (or tables) keep their memories (or
tables) alive as well.
=> Support multiple memories in RemoveUnusedModuleElements

scripts/fuzz_opt.py, src/tools/fuzzing.h, src/tools/fuzzing/fuzzing.cpp, test/passes/translate-to-fuzz_all-features_metrics_noprint.txt
Repurpose `makeBasicRef, makeCompoundRef` to generate not just "constant"
refs but any reference, and use those to create StructNew/ArrayNew.
The key changes are to add `makeCompoundRef` to `make()`, and to make
the function call `make()` for children, where possible, instead of just
`makeTrivial()`.
=> [Wasm GC] Fuzz struct.new and array.new

src/passes/MemoryPacking.cpp, test/lit/passes/memory-packing_all-features.wast
Previously, the pointer type for newly emitted instructions was determined by
the type of the destination pointer on a memory.init instruction, but that did
not take into account that the destination pointer may be unreachable. Properly
look up the pointer type on the memory instead to fix the problem.
Fixes #5620.
=> Fix a crash in MemoryPacking due to an unreachable pointer

src/passes/opt-utils.h, src/wasm.h, src/wasm/wasm.cpp
This saves the work of freeing and allocating for all the other maps. This is a
code path that is used by several passes so it showed up in profiling for
#5561
=> Only update functions in optimizeAfterInlining()

src/tools/fuzzing/fuzzing.cpp
We do similar things for globals already.
This fixes a crash that started to happen after recent landings added
tests with imported memories, but the problem is long-standing.
=> Avoid imported memories in the fuzzer

src/tools/fuzzing/fuzzing.cpp, test/passes/fuzz_metrics_noprint.bin.txt, test/passes/translate-to-fuzz_all-features_metrics_noprint.txt
1. Pick a subtype when mutating.
2. Don't use a fixed 10% chance to mutate, but pick a mutation rate in each function.
=> Fuzzer: Improve mutate()

src/ir/possible-contents.cpp, src/ir/possible-contents.h, test/gtest/possible-contents.cpp
Previously `(ref.as_non_null (global.get ..))` would return the global with no changes,
and if the global was nullable then the type didn't match the output, which hit an
assertion (where GUFA checks that the contents match the declared type in the wasm).
To fix this, refine global types, that is, the type we track on GlobalInfo may be more
refined than the global itself. In the above example, if the global is nullable then
the GlobalInfo would point to that global but have a non-nullable type.
In fact the code was already prepared for this, and few changes were needed.
=> [GUFA] Refine global types during flow

src/ir/bits.h, src/ir/gc-type-utils.h, src/ir/possible-contents.cpp, src/passes/ConstantFieldPropagation.cpp, test/lit/passes/cfp.wast, test/lit/passes/gufa-vs-cfp.wast
The same bug was present in both: We ignored packing, so writing a larger
value than fits in the field would lead to us propagating that original value.
=> [Wasm GC] Handle packed fields in GUFA and CFP

src/passes/MemoryPacking.cpp, test/lit/passes/memory-packing_all-features.wast
Do not optimize out or split segments that are referred to array.init_data
instructions. Fixes a bug where segments could get optimized out, producing
invalid modules. Doing the work to actually split segments used by
array.init_data is left for the future.
=> Fix MemoryPacking handling of array.init_data

src/passes/TypeRefining.cpp, test/lit/passes/type-refining.wast
We depended on ReFinalize doing it for us, and that usually works, but there is
a corner case that depends on knowing all the type changes being done, so we
need to handle that (see details in comment and testcase).
=> [Wasm GC] Update struct.get types in TypeRefining

src/js/binaryen.js-post.js
cleaned PR. Original: #5625
fixes #5595
=> use malloc/free instead of stackAlloc in setMemory (cleaned up)

src/ir/possible-contents.cpp, test/lit/passes/gufa-refs.wast
Technically we need to filter both before and after combining, that is,
if a location's contents will be filtered by `F()` then if the new contents
are `x` and old contents `y` then we need to end up with
`F(F(x) U F(y))`. That is, filtering before is necessary to ensure the union
of content does not end up unnecessarily large, and the filtering
after is necessary to ensure the final result is properly filtered to fit.
(If our representation were perfect then this would not be needed, but
it is not, as the union of two exact types can end up as a very large
cone, for example.)
For efficiency we have been filtering afterwards. But that is not enough
for packed fields, it turns out, where we must filter before. If we don't,
then if inputs `0` and `0x100` arrive to an `i8` field then …
=> [GUFA] Fix packed field filtering

src/tools/fuzzing.h, src/tools/fuzzing/fuzzing.cpp, test/passes/translate-to-fuzz_all-features_metrics_noprint.txt
Example output of the `array.set` length check:
```wat
(if
(i32.lt_u
(local.tee $8
(select
(i32.const -65536)
(ref.is_null
(array.new_fixed $[i8])
)
(local.get $4)
)
)
(array.len
(local.tee $14
(array.new $[mut:ref?|{i32_mut:ref|i31|_mut:i16_mut:f32}|]
(ref.null none)
(i32.const 88)
)
)
)
)
(array.set $[mut:ref?|{i32_mut:ref|i31|_mut:i16_mut:f32}|]
(local.get $14)
(local.get $8)
(ref.null none)
)
)
```
Locals `$14, $8` store the ref and the index, which are each used twice.
=> [Wasm GC] Fuzz struct.set and array.set

src/tools/fuzzing.h, src/tools/fuzzing/fuzzing.cpp, test/passes/translate-to-fuzz_all-features_metrics_noprint.txt
Without this, in certain complex operations we could end up calling a nested
`make()` operation that included nontrivial things, which could cause problems.
The specific problem I encountered was in `fixAfterChanges()` we tried to fix up
a duplicate label, but calling `makeTrivial()` emitted something very large that
happened to include a new block with a new label nested under a `struct.get`,
and that block's label conflicted with a label we'd already processed.
=> Fuzzer: When nested under makeTrivial(), avoid normal make()

src/tools/fuzzing/fuzzing.cpp
Turns out we'll need array checks for other array operations
like `array.copy`, so it's worth the refactor.
=> [NFC] Refactor fuzzer array check logic

src/tools/fuzzing/fuzzing.cpp
A return value was unused, and we have `BranchUtils::operateOnScopeNameDefs` now
which can replace old manual code.
=> [NFC] Refactor some old fuzzer code

src/ir/subtypes.h, test/lit/passes/signature-refining.wast
Before this PR we hit the assert on the type not being basic.
We could also look into fixing the caller to skip bottom types, but as
bottom types trivially have no subtypes, it is more future-facing to
simply handle it.
=> [Wasm GC] Fix SignatureRefining on a call_ref to a bottom type

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-gc.wast
Emit an unreachable, but guarded by a block as we do in other cases in this pass, to avoid
having unreachable code that is not fully propagated during the pass (as we only do a full
refinalize at the end). See existing comments starting with
"`Make sure to emit a block with the same type as us`" in the pass.
This is mostly not a problem with other casts, but `ref.test` returns an `i32` which we have
lots of code that tries to optimize.
=> [Wasm GC] OptimizeInstructions: Don't turn ref.test into unreachable immediately

src/tools/fuzzing/fuzzing.cpp
We picked a subtype there but only used it in some places. I don't see a reason not to
use it everywhere. This PR replaces the type with the subtype so we can't make such
mistakes in the future.
=> Fuzzer: Use subtype consistently in make()

scripts/fuzz_opt.py
DCE at the end avoids issues with non-nullable local operations in unreachable
code, which is still being discussed. This PR avoids fuzzer errors for now, but we
should revert it when we have a proper fix.
See
* https://github.com/WebAssembly/binaryen/issues/5599
* https://github.com/WebAssembly/binaryen/pull/5665
* https://github.com/WebAssembly/function-references/issues/98
=> Fuzzer: Run --dce when GC is enabled

src/passes/SignExtLowering.cpp, src/passes/pass.cpp, test/lit/help/wasm-opt.test, test/lit/help/wasm2js.test, test/lit/passes/signext-lowering-features.wast
The sign extension lowering pass would previously lower away the sign extension
instructions, but it wouldn't disable the sign extension feature, so follow-on
passes such as optimize-instructions could reintroduce sign extension
instructions.
Fix the pass to disable the sign extension feature to prevent sign extension
instructions from being reintroduced later.
=> Disable sign extension in SignExtLowering.cpp

src/passes/Memory64Lowering.cpp, src/passes/SignExtLowering.cpp, src/passes/pass.cpp, test/lit/help/wasm-opt.test, test/lit/help/wasm2js.test, test/lit/passes/memory64-lowering-features.wast, test/lit/passes/signext-lowering-features.wast
For consistency with other feature lowering passes, disable memory64 in addition
to lowering its use away. Although no other passes would introduce new uses of
memory64 at the moment, this makes the lowering pass more robust against a
future where memory64 might accidentally be reintroduced after being lowered away.
=> Disable the memory64 feature in Memory64Lowering.cpp

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-gc-tnh.wast
The logic says that if an if/select has an arm that returns a null type, and the if/select
goes into a cast, then we can ignore that arm in tnh mode (as it would trap, and we
are ignoring the possibility of a trap). But it is not enough to return a null type - the
null must actually flow out, rather than say a return be executed before.
One existing test needed adjustment, as it used calls for "thing with effects". But a
call can transfer control flow when EH is enabled, and this pass has `-all`. Rather
than mess with the features, I switched the effects to be locals.
=> [Wasm GC] Fix a trapsNeverHappen corner case with if/select of a trapping arm

src/wasm-type.h, src/wasm/wasm-type.cpp
Now that we no longer support constructing basic heap types in TypeBuilder, we
can fully initialize rec groups when they are created, rather than having to
initialize them later during the build step after any basic types have been
canonicalized. Alongside that change, also simplify the process of initializing
a type builder slot to avoid completely overwriting the HeapTypeInfo in the slot
and avoid the hacky workarounds that required.
=> [NFC] Simplify rec group initialization in wasm-type.cpp

src/wasm/wasm.cpp
If the names are not unique then the map would be smaller than
the vector it is built from. I am investigating a bug where that
happens, that these asserts would have helped with.
=> [NFC] Assert that module maps are the right size

CMakeLists.txt
CMake defaults to -O3 to release builds.  We were overriding that to -O2 in general and re-overriding back to -O3 for emscripten.
=> Avoid specifying multiple opt level in cflags

src/passes/SignatureRefining.cpp, test/lit/passes/signature-refining.wast
We used to refine only for result changes, but param changes can
also lead to opportunities.
=> [Wasm GC] Always refinalize in SignatureRefining

src/passes/Inlining.cpp
This also creates the backbone for canSplit to return different inlining modes.
=> [NFC] Start tracking InliningMode and memoize it to avoid re-analysis.

src/wasm/wasm-binary.cpp, test/lit/multi-memories-basics.wast
Before this fix we would flip all data segments to use the first memory.
Noticed while fuzzing a wip wasm-merge (it merges modules and so often it ends up with multiple memories, so a higher chance to find issues like this).
=> Emit memory segment index for data segments

src/passes/Inlining.cpp, test/lit/passes/inlining_splitting.wast
This workarounds the extra work around the edge case where;
- Function is too big to full-inline
- It is a candidate for partial inline
- Outlined version becomes eligible for full-inline.
In such a case, binaryen would introduce a temporary state with partial inlined functions and later on inline them. J2CL hit this scenario for String literal which resulted in significant regressions in compilation time.
This patch updates partial inlining analysis to identify the edge case and direct to full-inling when that happens.
It probably worths adding new tests but unfortunately I'm not familiar enough with Binaryen to add such tests.
=> Fallback to direct inline if the outline will be inlined.

src/passes/DeadArgumentElimination.cpp, test/lit/passes/dae_all-features.wast
The testcase here has a recursive call that is also nested in itself, something
like
```wat
(return
(call $me
(return
..
```
This found a bug in our return value removal logic. When we remove a return
value we both modify call sites (to add drops) and modify returns
(to remove their values). One of those uses pointers into the IR which the other
invalidated, so the order of the two matters. This PR just reorders that code to
fix the bug.
=> Fix DeadArgumentElimination return value opts on nesting+recursion

src/wasm/parsing.cpp
We can scan far faster than the name mapping process itself, so do that
first, as in the common case nothing needs to be fixed up.
This together with a PR to be opened will change the profile of
`--inlining-optimizing` from being 50% UniqueNameMapper (:scream: ) to
around 10%.
cc @gkdn
=> [NFC] Scan first in UniqueNameMapper

src/wasm/wasm.cpp, test/heap-types.wast.from-wast, test/heap-types.wast.fromBinary, test/heap-types.wast.fromBinary.noDebugInfo, test/lit/binary/legacy-static-casts.test, test/lit/cast-to-basic.wast, test/lit/heap-types.wast, test/lit/legacy-static-casts.wast, test/lit/passes/gufa-refs.wast, test/lit/passes/gufa-vs-cfp.wast, test/lit/passes/optimize-casts.wast, test/lit/passes/optimize-instructions-gc-iit.wast, test/lit/passes/optimize-instructions-gc-tnh.wast, test/lit/passes/remove-unused-brs-gc.wast, test/lit/passes/type-refining.wast
We already did this for nullablilty, and so for the same reasons we should do it
for heap types as well. Also, I realized that doing so  would solve #5703, which
is the new test added for TypeRefining here.
The fuzz bug solved here is that our analysis of struct gets/sets will skip
copy operations - a read from a field that is written into it. And we skip
fallthrough values while doing so, since it doesn't matter if the read goes
through an if arm or a cast. An if would automatically get a more precise
type during refinalize, so this PR does the same for a cast basically.
Fixes #5703
=> [Wasm GC] Automatically make RefCast heap types more precise

src/ir/effects.h, test/lit/passes/vacuum-tnh.wast, test/wasm2js/br_table_to_loop.2asm.js.opt
This changes loops from having the effect "may trap (timeout)" to having
"may not return." The only noticeable difference is in TrapsNeverHappen mode,
which ignores the former but not the latter. So after this PR, in TNH mode we do
not optimize away an infinite loop that seems to have no other side effects. We
may also use this for other things in the future, like continuations/stack switching.
There are upsides and downsides to allowing the optimizer to remove infinite
loops (the C and C++ communities have had interesting discussions on that topic
over the years...) but it seems safer to not optimize them out for now, to let the
most code work properly. If a need comes up to optimize such code, we can look
at various options then (like a flag to ignore infinite loops).
As suggested by …
=> Add a "mayNotReturn" effect

src/ir/drop.cpp, src/ir/drop.h, src/passes/Directize.cpp, test/lit/passes/directize_all-features.wast
This adds an option to ignore effects in the parent in
`getDroppedChildrenAndAppend`. With that, this becomes usable in more
places, like Directize, basically in situations where we know we can ignore
effects in the parent (since we've inferred they are not needed). This lets
us get rid of some boilerplate code in Directize.
Diff without whitespace is a lot smaller. A large other part of the diff is a
rename of `curr => parent` which I think it makes it more readable as then
`parent/children` is a clear contrast, and then the new parameter "ignore/
notice parent effects" is obviously connected to "parent".
The top comment in `drop.cpp` is removed as it just duplicated the top
comment in the header `drop.h`.
This is basically NFC but using `drop.h` does bring the advantage of
emitting less …
=> Extend drop.h and use it in Directize

src/wasm-interpreter.h
All array elements have the same type, so we can construct a single zero
and just copy it.
This makes ArrayNew of large arrays 2x faster. I also experimented with
putting `Literal::makeZero` in a header, in hopes of inlining leading to
licm helping here, but that did not help at all unfortunately, at least not
in gcc.
=> Optimize ArrayNew zero construction

src/ir/effects.h, test/example/cpp-unit.cpp, test/lit/passes/optimize-instructions-gc.wast
I honestly can't think of why we did that clearing... seems odd. Maybe I'm
forgetting something? Overall, in general we depend on repeated calls to
walk/visit accumulating effects; if we want to clear stuff then we create a
new EffectAnalyzer. So I think this PR is a correct change.
Removing that fixes the attached testcase. Also added a unit test. The fuzzer
seems happy as well after several thousand iterations.
=> EffectAnalyzer: Do not clear break targets before walk()/visit()

src/analysis/cfg.h
Swap the order of struct declarations to avoid using an incomplete type in a vector.
In C++20, using std::vector with an incomplete type often becomes a build failure due to increased usage of constexpr for vector members.
=> avoid incomplete type in a vector

scripts/fuzz_opt.py
We already ignore OOMs in the interpreter. This adds the syntax for V8, which
I saw an error on now (on an `array.new` of a massive size).
=> Fuzzer: Ignore testcases that V8 OOMs on

src/ir/module-utils.h, test/lit/merge/fusing.wat, test/lit/merge/fusing.wat.second, test/lit/merge/memory_data.wat, test/lit/merge/memory_data.wat.second, test/lit/merge/renamings.wat, test/lit/merge/renamings.wat.second
The import information of tags and memories were not preserved.
As a consequence, `wasm-merge` were not merging exported and imported tags.
For instance, consider this file `export.wat`:
```
(module
(tag $exn (export "exn")))
```
and this file `import.wat`:
```
(module
(import "env" "exn" (tag $exn))
(func $f (export "f") (throw $exn))
)
```
Then, the command `wasm-merge --enable-exception-handling /tmp/export.wat env /tmp/import.wat exec -S -o -` outputs the following:
```
(module
(type $none_=>_none (func))
(tag $exn (param))
(tag $exn_1 (param))
(export "exn" (tag $exn))
(export "f" (func $f))
(func $f
(throw $exn_1)
)
)
```
With this PR, I get the expected result:
```
(module
(type $none_=>_none (func))
(tag $exn (param))
(export "exn" (tag $exn))
(export "f" (func $f))
(func $f …
```
=> Preserve imports when copying module items

scripts/fuzz_opt.py, src/passes/StackIR.cpp, test/lit/passes/roundtrip-gc.wast, test/lit/passes/stack-ir-eh.wast, test/passes/generate-stack-ir_optimize-stack-ir_print-stack-ir_optimize-level=3.txt, test/reduce/memory_table.wast.txt
No `nop` instruction is necessary in wasm, so in StackIR we can simply
remove them all.
(Unless I'm forgetting something..?)
Fixes #5745
=> StackIR: Remove nops

src/passes/OptimizeCasts.cpp, test/lit/passes/optimize-casts.wast
In the `OptimizeCasts` pass, it is useful to move more refined casts as early as possible without causing side-effects. This will allow such casts to potentially trap earlier, and will allow the `OptimizeCasts` pass to use more refined casts earlier. This change allows a more refined cast to be duplicated at an earlier `local.get` expression. The later instance of the cast will then be eliminated in a later optimization pass.
For example, if we have the following instructions:
```
(drop
(local.get $x)
)
(drop
(ref.cast $A
(local.get $x)
)
(drop
(ref.cast $B
(local.get $x)
)
)
```
Where `$B` is a sublcass of `$A`, we can convert this to:
```
(drop
(ref.cast $B
(local.get $x)
)
)
(drop
(ref.cast $A
(local.get $x)
)
(drop
(ref.cast $B
(local.get $x)
)
)
```
Currently this change only moves …
=> Move casts which are immediate children of local.gets to earlier local.gets

src/ir/effects.h
This PR removes a check for
```cpp
transfersControlFlow() && other.trap
```
which is already checked higher up in the code, here:
```cpp
transfersControlFlow() && other.hasSideEffects()
```
https://github.com/WebAssembly/binaryen/blob/7b093e8d0cfe09471aed4eb40c093f0603f11efb/src/ir/effects.h#L223-L224
That last code handles the first code because trapping is part
of `hasSideEffects()`.
=> [NFC] Remove redundant code from EffectAnalyzer

src/wasm/wasm-binary.cpp, test/lit/downgrade-reftypes.wast
Related to #5737 which did something similar for other types.
=> [Strings] Fix non-nullable string emitting in the binary format

src/passes/TypeRefining.cpp, test/lit/passes/type-refining.wast
If we have
```wat
(struct.get $A
(struct.get $B
```
then if both types end up refined we may have a problem. If the inner one is
refined to emit `nullref` then the outer one no longer knows what type it is,
since it depends on the type of the `ref` child for that in our IR.
To avoid that, note all the types first before optimizing.
=> TypeRefining: Fix a bug with chains of StructGets

src/wasm/wasm-validator.cpp
This is far from comprehensive, but it checks strings being enabled for
all the instructions. Without this, the fuzzer can get confused because it
checks if code validates and then proceeds under that assumption, so
any missing validation checks can cause problems (specifically, if we have
a `string.const` without strings enabled then we error during writing of
the string, since we don't do the initial pass to find all strings to
deduplicate them).
=> Strings: Add initial validation checks

src/wasm/wasm-validator.cpp
We already validated function params, but were missing tags.
Without this the fuzzer can get confused if a type is only used in a tag.
=> Validate tag param types

src/passes/ConstantFieldPropagation.cpp, test/lit/passes/cfp.wast
The logic ignored copied values, which was fine for `struct.get` operations but
not for `struct.new`. See the example in the comment and the testcase.
=> ConstantFieldPropagation: Track copied values properly

src/ir/lubs.cpp, test/lit/passes/dae_all-features.wast
More generally, the LUB computation that code relies on did not handle
bottom types properly.
=> DeadArgumentElimination: Do not error on bottom types in result refining

src/binaryen-c.cpp, src/passes/Asyncify.cpp, src/passes/RoundTrip.cpp, src/wasm-binary.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-io.cpp, src/wasm/wasm-s-parser.cpp
We have `WasmBinaryBuilder` that read binary into Binaryen IR and `WasmBinaryWriter` that writes Binaryen IR to binary. To me `WasmBinaryBuilder` sounds similar to `WasmBinaryWriter`, which builds binary. How about renaming it to `WasmBinaryReader`?
=> Rename WasmBinaryBuilder to WasmBinaryReader (NFC)

src/wasm/wasm-type.cpp
Now that we support only isorecursive typing, which canonicalizes heap types by
the rec group rather than individually, we no longer need a canonicalizing store
for heap types. Simplify the `Store` implementation, which was previously
generic over both `HeapType`s and `Type`s, to instead work only for `Type`s.
Replace `globalHeapTypeStore` with a simple vector to keep canonicalized
`HeapTypeInfo`s alive. Also simplify global canonicalization to not replace heap
type uses, since that is already done separately as part of isorecursive rec
group canonicalization.
This simplification does require adding new information to
`CanonicalizationState`, but further work will simplify that away as well.
=> [NFC] Simplify the HeapTypeStore

src/wasm-type.h, src/wasm/wasm-type.cpp
Rewrite the type canonicalization algorithm to fully canonicalize a single rec
group at a time rather than canonicalizing multiple rec groups at once in
multiple stages. The previous code was useful when it had to be shared with
equirecursive and nominal canonicalization, but was much more complicated than
necessary for just isorecursive canonicalization, which is all we support today.
=> [NFC] Rewrite isorecursive canonicalization

src/ir/type-updating.cpp, src/passes/Print.cpp, src/passes/TypeMerging.cpp, src/wasm-type.h, src/wasm/wasm-type.cpp, src/wasm/wasm-validator.cpp, test/example/typeinfo.cpp
Rather than wrap a `TypeList`, make `Tuple` an alias of `TypeList`. This means
removing `Tuple::toString`, but that had no callers and was of limited use for
debugging anyway. In return, the use of tuples becomes much less verbose.
In the future, it may make sense to remove one of `Tuple` and `TypeList`.
=> [NFC] Simplify `Tuple` by making it an alias of `TypeList`

src/wasm/literal.cpp
Without this, a massive GC array for example can end up being printed as a huge
amount of output, which is a problem in the fuzzer. I noticed this because a testcase
was taking minutes to run.
Perhaps we should add an option (`BINARYEN_PRINT_FULL=1`?) to disable this limit,
but let's see if we ever need that.
=> Limit literal printing to a reasonable limit

scripts/fuzz_opt.py
Just look for export names as "" with some non-" in the middle.
That should handle everything but escaping of " in an export name (which I don't know
if we can handle in a regex?).
Missing from the old regex: spaces, parens, and probably more. Spaces and parens
are used in the test suite, which is how this was noticed by the fuzzer.
=> CtorEval Fuzzer: Generalize export regex

test/gtest/cfg.cpp, test/gtest/print-test.h
Such tests all have to handle disabling and re-enabling color output for printed
wast and have to handle parsing input wast, so add a test fixture that makes
these tasks easier.
=> Add a gtest fixture for tests checking printed output

src/analysis/lattice.h, src/analysis/monotone-analyzer-impl.h, src/analysis/monotone-analyzer.h, src/analysis/powerset-lattice-impl.h, src/analysis/sign-lattice.cpp, test/gtest/cfg.cpp
This change introduces a finite-height powerset lattice `FinitePowersetLattice` where each element's height is determined when constructed in runtime. This is implemented using a vector of `bool`'s. The previous finite-height powerset lattice implementation had used a `bitset`, which forced the size of each lattice element to be determined statically at compile time, which is a significant drawback, as most powerset lattice sizes are determined by the input program.
This change also modifies `BlockState` and `MonotoneCFGAnalyzer` to be templated on a generic lattice type instead of using a hardcoded lattice. It also fixes an iterator bug in `MonotoneCFGAnalyzer::fromCFG` which assigned a temporary iterator object as predecessor and successor pointers to `BlockState`'s instead of pointers …
=> Dynamic Sized Bitvector Powerset Lattice for Static Analysis

src/tools/wasm-metadce.cpp, test/metadce/ref-func.wast, test/metadce/ref-func.wast.dced, test/metadce/ref-func.wast.dced.stdout, test/metadce/ref-func.wast.graph.txt, test/metadce/segments.wast, test/metadce/segments.wast.dced, test/metadce/segments.wast.dced.stdout, test/metadce/segments.wast.graph.txt
`wasm-metadce` could wrongly consider some functions as unused since it did not take `ref.func` into consideration.
=> [wasm-metadce] Consider ref.func as introducing a dependency + fix rooting of segment offsets

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-gc.wast
This parallels the code in RefCast. Previously we only looked at the type reaching us, but
intermediate fallthrough values can let us optimize too. In particular, we were not
optimizing `(ref.test (local.tee ..))` if the tee was to a less-refined type.
=> OptimizeInstructions: Loop on fallthrough values in RefTest

src/ir/struct-utils.h, src/ir/subtypes.h, src/passes/AbstractTypeRefining.cpp, src/passes/RemoveUnusedModuleElements.cpp, src/passes/SignaturePruning.cpp, src/passes/SignatureRefining.cpp, src/passes/TypeRefining.cpp, src/tools/fuzzing/fuzzing.cpp, src/wasm/wasm-binary.cpp, test/gtest/type-builder.cpp
Previously we incorrectly used "strict" to mean the immediate subtypes of a
type, when in fact a strict subtype of a type is any subtype excluding the type
itself. Rename the incorrect `getStrictSubTypes` to `getImmediateSubTypes`,
rename the redundant `getAllStrictSubTypes` to `getStrictSubTypes`, and rename
the redundant `getAllSubTypes` to `getSubTypes`. Fixing the capitalization of
"SubType" to "Subtype" is left as future work.
=> [NFC] Fix the use of "strict" in subtypes.h

src/analysis/cfg.h, src/analysis/liveness-transfer-function.h, src/analysis/monotone-analyzer-impl.h, src/analysis/monotone-analyzer.h, test/gtest/cfg.cpp
This change makes the transfer function an object separate from the monotone analyzer. The transfer function class type is a generic template of the monotone analyzer, and an instance of the transfer function is instantiated and then passed into the monotone analyzer via its constructor.
This change introduces `LivenessTransferFunction` as a transfer function for liveness analysis as an example.
=> Make the Transfer Function a Generic, Interchangeable Type for the Monotone Analyzer

src/analysis/lattice.h, src/analysis/liveness-transfer-function.h, src/analysis/powerset-lattice-impl.h, test/gtest/cfg.cpp
This change enables the `FinitePowersetLattice` to be directly used to represent powerset lattices constructed from a set of arbitrary type members. The `FinitePowersetLattice` is made to map members to bitvector indices. During construction, an ordered vector of members of some templated type `Type` is passed in, and this ordering is used to determine the mapping of `Type` members to bitvector indices. Instead of having users directly manipulate the bitvector for each lattice element, methods `add` and `remove` are introduced to add or remove a lattice element member of `Type`.
=> Generalize Finite Powerset Lattice to Any Given Type

src/passes/GUFA.cpp, src/passes/Heap2Local.cpp, test/lit/passes/gufa-refs.wast, test/lit/passes/gufa-vs-cfp.wast
If we see `(ref.cast $A)` but we have inferred that a more refined type will
be present there at runtime `$B` then we can refine the cast to `(ref.cast $B)`.
We could do the same even when a cast is not present, but that would
increase code size. This optimization keeps code size constant.
This affects a couple of casts on the j2wasm binary.
=> GUFA: Refine casts

src/tools/fuzzing/fuzzing.cpp, test/passes/fuzz_metrics_noprint.bin.txt, test/passes/translate-to-fuzz_all-features_metrics_noprint.txt
Before we always created if-elses. Now we also create an If with one arm some of
the time, when we can.
Also, sometimes make one if arm unreachable, if we have two arms.
=> Fuzzer: Emit more variations of If

src/analysis/liveness-transfer-function.h, src/analysis/monotone-analyzer.h
Updates comments. Moves `wasm-traversal.h` dependency to transfer function classes.
=> Small fixes to Lattice and Monotone Analyzer

src/support/CMakeLists.txt, src/support/suffix_tree.cpp, src/support/suffix_tree.h, src/support/suffix_tree_node.cpp, src/support/suffix_tree_node.h, test/gtest/CMakeLists.txt, test/gtest/suffix_tree.cpp
This PR adds LLVM's suffix tree data structure to Binaryen. This suffix tree is implemented using Ukkonen's algorithm for linear-time suffix tree construction, and is intended for fast substring queries.
Note: All of the .h and .cpp files included are from LLVM. These files were copied directly instead of imported into our existing LLVM integration (in third_party/) to avoid bumping the commit hash and avoid the potential for complications with upstream changes.
=> [Outlining] LLVM Suffix Tree

src/analysis/cfg-impl.h, src/analysis/cfg.h, src/analysis/lattice.h, src/analysis/liveness-transfer-function.h, src/analysis/monotone-analyzer-impl.h, src/analysis/monotone-analyzer.h, src/analysis/reaching-definitions-transfer-function.h, src/analysis/visitor-transfer-function.h, test/gtest/cfg.cpp
This change creates a reaching definitions analysis, and makes some modifications in the `MonotoneCFGAnalyzer` class to facilitate these changes. In particular, this analysis is intended to eventually perform the same work that `LocalGraph` is currently doing.
I have reverted the changes to `LocalGraph` for the purpose of this pull request, but will restore them in the branch `local-graph-static-analysis` for fuzzing.
=> Substitute LocalGraph initial calculations with Reaching Definitions Analysis

src/analysis/cfg.cpp, src/analysis/cfg.h, test/gtest/cfg.cpp
I'd like to use this in the reverse-direction analysis for TrapsNeverHappen: I need to know
which expressions are in the same basic block.
=> Static Analysis: Add an API to get the block index of an expression

src/cfg/cfg-traversal.h
ControlFlowWalker builds a stack of control flow items and allows finding
the target of a branch using it. But the only use CFGWalker made of that was
to map a block or a loop to its branches. We can just use the name of the block
or loop in the map, and avoid the extra overhead.
`perf stat` confirms fewer instructions and branches with this change, but
the difference in runtime is too small to measure.
=> [NFC] Avoid using ControlFlowWalker in CFGWalker

CHANGELOG.md, src/binaryen-c.cpp, src/binaryen-c.h, test/example/c-api-kitchen-sink.c, test/example/c-api-kitchen-sink.txt
This is necessary for WasmGC producers using the C API, so that they can set the
heap type of functions. Otherwise the heap type is set structurally using params
and results in the old API.
The old API is kept for backwards compatibility and convenience (for the structural
case, which is all code before WasmGC basically).
Fixes #5826
=> C API: Add BinaryenAddFunction2 which takes a heap type

src/passes/SimplifyLocals.cpp, test/lit/passes/simplify-locals-gc.wast
A minor old bug that the fuzzer found just now. Removing a tee in the middle
can place a more refined type in a location, which requires updating parents.
=> SimplifyLocals: Refinalize after removing redundant tees

src/passes/hash-stringify-walker.cpp, src/passes/stringify-walker.h, test/gtest/stringify.cpp
The LLVM suffix tree expects to be provided with a vector of 32-bit unsigned integers. This PR makes it easier to integrate our wasm program string with the suffix tree.
Because the range of possible values is reduced from 2^64 to 2^32, a signed integer was added to manage the next separator value and ensure we're using every possible negative number.
=> [Outlining] Changing stringify values to 32-bit

src/tools/wasm-merge.cpp, test/lit/merge/start3.wat, test/lit/merge/start3.wat.second, test/lit/merge/start3.wat.third
Start functions can have locals, which we previously ignored as we just
concatenated the bodies together. This makes us copy the second start
and call that, keeping them separate (the optimizer can then inline, if that
makes sense).
fixes #5835
=> wasm-merge: Fix locals in merged start

src/analysis/reaching-definitions-transfer-function.h
Small change to change instances where the term "setses" was used incorrectly. References [the following comment](https://github.com/WebAssembly/binaryen/pull/5817#discussion_r1268779682).
=> Remove erroneous usages of "setses" in Reaching Definitions Analysis

src/cfg/cfg-traversal.h, src/ir/LocalGraph.cpp, src/ir/local-graph.h, src/ir/possible-contents.cpp, src/passes/Heap2Local.cpp, src/passes/LocalSubtyping.cpp, src/passes/LoopInvariantCodeMotion.cpp, src/passes/MergeLocals.cpp, src/passes/OptimizeAddedConstants.cpp, src/passes/Precompute.cpp, src/passes/SSAify.cpp, test/gtest/cfg.cpp
Before this PR, if a call had no paths to a catch in the same function then we skipped
creating a new basic block right after it. As a result, we could have a call in the middle
of a basic block.
That is ok, but I think it might be good to have the property that basic blocks end in
possibly-control-flow-transferring instructions. That is, anything that might branch -
even if just out of the whole function - ends a basic block, which is what this PR changes. 
This change makes a future PR simpler, as it wants to depend on that assumption.
I added a test in the analysis CFG file as that seems simplest: we can print out the
CFG there to verify what we want.
=> End the current basic block on a Call

src/passes/TypeRefining.cpp, src/wasm-builder.h, test/lit/passes/type-refining.wast
See the example in the code and test for a situation that requires this for validation.
To fix validation we add a cast. That should practically always be removed by later
optimizations, and the fact it took the fuzzer this long to even find such a situation
also adds confidence that this won't be adding overhead (and in this situation, the
optimizer will definitely remove the cast).
=> TypeRefining: Add casts when we must

src/analysis/lattice.h, src/analysis/powerset-lattice-impl.h, src/tools/CMakeLists.txt, src/tools/wasm-fuzz-lattices.cpp, test/lit/fuzz-lattices.test
This change adds a fuzzer which checks the following properties:
- Transfer Function Monotonicity
- Lattice Element Reflexivity
- Lattice Element Transitivity
- Lattice Element Anti-Symmetry
This is accomplished by randomly generating a module and using its functions as transfer function inputs, along with randomly generated lattice element states. Lattice element properties are fuzzed from the randomly generated states also.
=> Add a Fuzzer for Lattice and Transfer Function Properties

src/passes/TypeRefining.cpp, test/lit/passes/type-refining.wast
This is what I get for not fuzzing #5840 enough beforehand.
=> Fix a crash in TypeRefining on bottom types

src/analysis/lattice.h, test/gtest/cfg.cpp
This changes the static asserts checking a lattice type to require a non-static `compare` function instead of a static one, since a lattice instance may have instance-specific data relevant to such a comparison. The change also changes the `compare` functions of existing lattices to be non-static.
=> Make lattice compare function non-static

src/ir/possible-contents.cpp, src/ir/possible-contents.h, test/gtest/possible-contents.cpp
This is necessary for a future PR that will infer more things than full cones, which
were the thing we supported until this PR in intersections.
=> PossibleContents: Support more intersection types

src/passes/Print.cpp, test/heap-types.wast.from-wast, test/heap-types.wast.fromBinary, test/heap-types.wast.fromBinary.noDebugInfo, test/lit/passes/abstract-type-refining.wast, test/lit/passes/coalesce-locals-gc.wast, test/lit/passes/code-pushing-gc.wast, test/lit/passes/merge-blocks.wast, test/lit/passes/optimize-instructions-gc.wast, test/lit/passes/vacuum-gc.wast, test/lit/passes/vacuum-tnh.wast
Stop printing `ref.as_i31`, `br_on_func`, etc. because they have been removed
from the spec and are no longer supported by V8. #5614 already made this change
for the binary format. Like that PR, leave reading unmodified in case someone is
still using these instructions (even though they are useless). They will be
fully removed in a future PR as we finalize things ahead of standardizing
WasmGC.
=> [Wasm GC] Stop printing deprecated cast etc. instructions

src/ir/type-updating.cpp, src/ir/type-updating.h, src/passes/TypeMerging.cpp, src/wasm-type.h, src/wasm/wasm-type.cpp, test/lit/passes/type-merging.wast
TypeMapper is a utility used to globally rewrite types, mapping some eliminated
source types into destination types they should be replaced with. This was
previously done by first rewriting all the types in the IR according to the
given mapping, then rewriting the type definitions and updating all the types in
the IR again. Not only was doing the rewriting twice inefficient, it also
introduced a subtle bug where the set of private types eligible to be rewritten
could be inconsistent because updating types in the IR could change the types of
control flow structures. The fuzzer found a case where this inconsistency caused
the type rebuilding to fail.
Fix the bug by first building the new types with the mapping applied and only
then rewriting the IR a single time.
Fixes #5845.
=> Fix a fuzz bug in TypeMapper

src/ir/lubs.cpp, src/ir/module-utils.cpp, src/ir/module-utils.h, src/ir/struct-utils.h, src/passes/Directize.cpp, src/passes/GlobalEffects.cpp, src/passes/GlobalStructInference.cpp, src/passes/Inlining.cpp, src/passes/MultiMemoryLowering.cpp, src/tools/wasm-merge.cpp, src/tools/wasm-split/instrumenter.cpp, test/gtest/type-builder.cpp
None of that code is speed-sensitive, or at least doesn't need to be inlined to be
fast. Move it to cpp for faster compile times.
This caused a cascade of necessary header fixes (i.e. after removing unneeded
header inclusions in `module-utils.h`, files that improperly depended on that
stopped working and needed an added include).
=> [NFC] Move ModuleUtils copying and renaming logic from header to cpp

src/support/suffix_tree.h, test/gtest/stringify.cpp
Adds an integration test that identifies the substrings of a stringified wasm module using the suffix_tree.
=> [Outlining] Integration test for suffix_tree and stringify

.github/workflows/ci.yml
Add a CI step to build with gcov instrumentation and run the lit test suite to
gather profiles, then upload those profiles to codecov.io to generate a code
coverage report for each PR. The goal is not necessarily to achieve 100% code
coverage, but rather to help find important missing test cases and dead code.
=> Add CodeCov to CI

src/ir/linear-execution.h, src/passes/SimplifyLocals.cpp, test/lit/passes/Oz.wast, test/lit/passes/inlining-optimizing_optimize-level=3.wast, test/lit/passes/simplify-locals-eh.wast, test/lit/passes/simplify-locals-gc.wast, test/lit/passes/type-ssa_and_merging.wast, test/wasm2js/i64-ctz.2asm.js, test/wasm2js/unary-ops.2asm.js
This addresses most of the minor regression from the correctness fix in #5857.
That PR makes us consider calls as branching, but in some cases it is ok to
ignore that branching (see the comment in the code), which this PR allows as
an option.
This undoes one test change from that PR (showing it undoes the regression).
More tests are added to cover this specifically as well.
=> LinearExecutionTraversal: Add an option to connect adjacent code, use in SimplifyLocals

src/wasm-binary.h
Depending on whether preprocessor macros USE_STANDARD_GC_ENCODINGS and
USE_LEGACY_GC_ENCODINGS are defined, use the standard or legacy encodings for GC
types and instructions. Default to the latter for now. When WasmGC reaches phase
4, we will switch the default to be the standard encodings instead. After users
have time to update, we will remove the legacy encodings entirely.
Tested manually by building with USE_STANDARD_GC_ENCODINGS locally and seeing
that all the tests pass except for some tests that depend on the specific binary
encoding.
=> Allow opting into standard GC encodings at compile time

.github/codecov.yml
While useful these annotations in the GitHub code review UI, are also extremely
intrusive and make reading code under review harder.
=> Disable inline CodeCov annotations

src/support/result.h, src/wasm/wat-parser.cpp, src/wat-parser.h
Allow them to be used for more than just the new text parser.
=> [NFC] Factor `Result` and `MaybeResult` into a utility header

src/ir/properties.h, src/passes/OptimizeInstructions.cpp, src/wasm-type.h, src/wasm/wasm-type.cpp, test/lit/passes/optimize-instructions-call_ref.wast, test/lit/passes/optimize-instructions-gc-iit.wast, test/lit/passes/optimize-instructions-gc-tnh.wast, test/lit/passes/optimize-instructions-gc.wast
Simplify the optimization of ref.cast and ref.test in OptimizeInstructions by
moving the loop that examines fallthrough values one at a time out to a shared
function in properties.h. Also simplify ref.cast optimization by analyzing the
cast result in just one place.
In addition to simplifying the code, also make the cast optimizations more
powerful by analyzing the nullability and heap type of the cast value
independently, resulting in a potentially more precise analysis of the cast
behavior. Also improve optimization power by considering fallthrough values when
optimizing the SuccessOnlyIfNonNull case.
=> Improve cast optimizations

src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, src/wasm/wasm-stack.cpp, src/wasm/wasm-validator.cpp, src/wasm/wasm.cpp, test/lit/cast-to-basic.wast, test/lit/passes/code-pushing-gc.wast, test/lit/passes/gufa-refs.wast, test/lit/passes/merge-blocks.wast, test/lit/passes/optimize-instructions-gc.wast, test/lit/passes/remove-unused-brs-gc.wast
The WasmGC spec will require that the target cast type of br_on_cast and
br_on_cast_fail be a subtype of the input type, but so far Binaryen has not
enforced this constraint, so it could produce invalid modules when optimizations
refined the input to a br_on_cast* such that it was no longer a supertype of the
cast target type.
Fix this problem by setting the cast target type to be the greatest lower bound
of the original cast target type and the current input type in
`BrOn::finalize()`. This maintains the invariant that the cast target type
should be a subtype of the input type and it also does not change cast behavior;
any value that could make the original cast succeed at runtime necessarily
inhabits both the original cast target type and the input type, so it also must
inhabit their …
=> Ensure br_on_cast* target type is subtype of input type

src/wasm/wasm.cpp, test/lit/passes/optimize-casts.wast, test/lit/passes/optimize-instructions-call_ref.wast, test/lit/passes/optimize-instructions-gc-iit.wast, test/lit/passes/optimize-instructions-gc.wast, test/lit/passes/precompute-gc.wast, test/lit/passes/signature-refining.wast
We previously improved the nullability and heap type of the ref.cast target type
in RefCast::finalize() based on what we knew about its input type. Simplify the
code and make this improvement more powerful by using the greatest lower bound
of the original cast target and input type.
=> Further improve ref.cast during finalization

src/passes/SSAify.cpp, test/lit/passes/ssa.wast
Similar to #5885 this was uncovered by #5881 #5882. Here we need to refinalize
when we replace a `local.get` with a null, since the null's type is more refined.
=> Fix SSA on null refinement

src/wasm.h, src/wasm/wasm-binary.cpp, src/wasm/wasm-s-parser.cpp, src/wasm/wasm.cpp, test/lit/passes/local-subtyping.wast
Previously CallRef::finalize() would never update the type of the CallRef, even
if the type of the call target had been refined to give a more precise result
type. Besides unnecessarily losing type information, this could also lead to
validation errors, since the validator checks that the type of CallRef matches
the result type of the target signature.
Fix the bug by updating CallRef's type based on its target signature in
CallRef::finalize() and add a test that depends on this refinalization.
=> Fix finalization of call_ref to handle refined target types

src/passes/RemoveUnusedBrs.cpp, test/lit/passes/remove-unused-brs-gc.wast, test/lit/passes/remove-unused-brs_all-features.wast
Optimize both the known-null and known-non-null cases for BrOnNull and
BrOnNonNull and optimize for more cast behaviors such as SuccessOnlyIfNonNull
and Unreachable for BrOnCast and BrOnCastFail. Leave optimizing
SuccessOnlyIfNull to future work, since that's more complicated. Use type
information from fallthrough values to inform all the optimizations.
=> Improve br_on* optimizations

src/mixed_arena.h, src/wasm-builder.h, src/wasm-ir-builder.h, src/wasm.h, src/wasm/CMakeLists.txt, src/wasm/wasm-ir-builder.cpp, src/wasm/wat-parser.cpp
Add an IRBuilder utility in a new wasm-ir-builder.h header. IRBuilder is
extremely similar to Builder, except that it manages building full trees of
Binaryen IR from a linear sequence of instructions, whereas Builder only builds
a single IR node at a time. To build full IR trees, IRBuilder maintains an
internal stack of expressions, popping children off the stack and pushing the
new node onto the stack whenever it builds a new node.
In addition to providing makeXYZ function to allocate, initialize, and finalize
new IR nodes, IRBuilder also provides a visit() method that can be used when the
user has already allocated the IR nodes and only needs to reconstruct the
connections between them. This will be useful in outlining both for constructing
outlined functions and for reconstructing …
=> Factor IRBuilder utility out of the new wat parser

src/passes/RemoveUnusedBrs.cpp, test/lit/passes/remove-unused-brs-gc.wast
The improvements to RemoveUnusedBrs in #5887 also introduced a regression where
the pass did not correctly handle unreachable fallthrough values and crashed
with an assertion failure. Fix the problem by returning early when a fallthrough
value is unreachable and add a regression test.
Fixes #5892.
=> Fix assertion failure in RemoveUnusedBrs

test/lit/passes/remove-unused-brs-gc.wast
Looks like https://github.com/WebAssembly/binaryen/pull/5894 raced with something else, as tests passed there but fail on `main`. Might be a new test was added since that PR was opened.
(this just applies an update to the existing tests)
=> Fix a merge conflict on main

src/passes/TypeMerging.cpp, test/lit/passes/type-merging.wast
Previously it was possible that the supertype merging phase would merge
unrelated types when DFA minimization would split a common supertype out of a
partition, leaving unrelated types behind in the same partition. Fix the problem
by post-processing the partitions in the supertype merging phase to split any
partitions that contain unrelated types.
Fixes #5877.
=> Fix merging of unrelated types in TypeMerging

src/wasm-ir-builder.h, src/wasm/wasm-ir-builder.cpp, src/wasm/wat-parser.cpp, test/lit/wat-kitchen-sink.wast
The initial PR introducing IRBuilder kept the interface the same as the previous
internal interface in the new wat parser. This PR updates that interface to
avoid exposing implementation details of the IRBuilder and to provide an API
that matches the binary format. For example, after calling `makeBlock` or
`visitBlock` at the beginning of a block, users now call `visitEnd()` at the end
of the block without having to manually install the block's contents.
Providing this improved interface requires refactoring some of the IRBuilder
internals. While we are refactoring things anyway, put in extra effort to avoid
unnecessarily splitting up and recombining tuples that could simply be returned
from a multivalue block.
=> Refactor IRBuilder to build blocks internally

src/passes/Print.cpp, test/fib-dbg.wasm.fromBinary
Split from https://github.com/WebAssembly/binaryen/pull/5547.
Focus on debug info print optimization.
=> fix: debug info print with depth

src/wasm-binary.h
This bug was found by fuzzing Binaryen and V8 together with the standard GC
encodings enabled.
=> Fix standard reference type encoding

scripts/fuzz_opt.py
Remove the prompt for user confirmation when using the --auto-initial-contents
option with the fuzzer. It is not actionable, and it prevents me from going off
and doing something else when I build and start the fuzzer in the same command.
=> Do not prompt user on fuzz_opt.py --auto-initial-contents

src/wasm/wasm-binary.cpp, test/lit/passes/roundtrip.wast
In the binary parser, when creating a scratch local to hold multivalue results
as tuples, we previously ensured that the scratch local did not contain any
non-nullable by modifying its type and inserting ref.as_non_null as necessary.
Now that we properly support non-nullable elements in tuple locals, however,
this parser behavior is no longer necessary. Remove it.
=> Parse non-nullable tuple elements without special handling

src/wasm-binary.h, src/wasm/wasm-binary.cpp
Almost entirely trivial, except for this part:
```diff
-  if (nextDebugLocation.availablePos == 0 &&
-      nextDebugLocation.previousPos <= pos) {
+  if (nextDebugLocation.availablePos == 0) {
return;
```
I believe removing the extra check has no effect. Removing it does not change
anything in the test suite, and logically, if we set `availablePos` to 0 then we
definitely want to return here - we set it to 0 to indicate there is nothing left
to read, which is what the code after it does.
As a result, we can remove the `previousPos` field entirely.
cc @JesseCodeBones - am I missing something about `previousPos`? Do you have
an example maybe that shows it is needed?
=> [NFC] Source maps: Simplify the code and add comments

src/passes/Print.cpp, test/lit/passes/signature-pruning.wast, test/lit/passes/signature-refining.wast, test/lit/wat-kitchen-sink.wast
Previously, the printer incorrectly reconstructed imported functions' types from
their signatures instead of printing their types directly. This could cause the
printer to print uses of types that were never defined and did not exist in the
module. Fix the bug by printing imported functions' heap types directly.
=> Fix printing of types for imported functions

src/support/small_vector.h
Fix #5928 , on FreeBSD `off_t` is not defined in the headers we include, apparently.
=> Avoid off_t in small_vector.h

CHANGELOG.md, CMakeLists.txt
The important included change is the switch to default GC opcodes.
=> Prepare to release Version 116

src/wasm-stack.h, src/wasm/wasm-stack.cpp, test/exception-handling.wast.fromBinary, test/exception-handling.wast.fromBinary.noDebugInfo, test/lit/multivalue.wast
In general, the binary lowering of tuple.extract expects that all the tuple
values are on top of the stack, so it inserts drops and possibly uses a scratch
local to ensure only the extracted value is left. However, when the extracted
tuple expression is a local.get, local.tee, or global.get, it's much more
efficient to change the lowering of the get or tee to ensure that only the
extracted value is on the stack to begin with. Implement that optimization in
the binary writer.
=> Optimize tuple.extract of gets in BinaryInstWriter

scripts/fuzz_opt.py, scripts/test/shared.py
This setting is useful enough that there is basically no reason not to use it.
Turn it on by default to save some typing when running the fuzzer.
=> Enable auto_initial_contents by default in fuzz_opt.py

src/wasm-stack.h, src/wasm/wasm-stack.cpp, test/exception-handling.wast.fromBinary, test/exception-handling.wast.fromBinary.noDebugInfo, test/lit/multivalue.wast
Reverts WebAssembly/binaryen#5941
The binary writer optimization is not always correct when stack IR optimizations have run. Revert the change until we can fix it.
=> Revert "Optimize tuple.extract of gets in BinaryInstWriter"

src/wasm/wasm-validator.cpp
table.fill requires bulk memory to be enabled, not reference types.
=> Fix validation error message for table.fill

src/wasm-ir-builder.h, src/wasm/wasm-ir-builder.cpp
Visiting a block should push it onto the stack just like visiting any other
expression, but we previously had a `visitBlock` that introduced a new scope
instead. Fix `visitBlock` to behave as expected and introduce a new
`visitBlockStart` method to introduce a new scope.
Unfortunately this cannot be fully tested yet because the wat parser uses the
`makeXYZ` API intead of the `visit` API, but at least I updated `makeBlock` to
call `visitBlockStart`, so that is tested.
=> Fix visitBlock and add visitBlockStart in IRBuilder

src/passes/StackIR.cpp, test/lit/passes/optimize-stack-ir.wast
This Stack IR optimization is not compatible with a much more powerful
optimization we plan to do for tuples in the binary writer.
=> Do not optimize tuple locals in StackIR local2stack

src/passes/RemoveUnusedModuleElements.cpp
NFC, but fixes a current fuzz bug on `table.fill` not having an entry in this file. After
this PR, there is no need for such entries.
=> [NFC] RemoveUnusedModuleElements: Use delegations

src/passes/Heap2Local.cpp, test/lit/passes/heap2local.wast
I currently generate boxing and unboxing code like the following:
```wat
(local $x (ref eq)
...
(local.set $x
(struct.new $float
...
)
)
(struct.get $float 0
(ref.cast (ref $float)
(local.get $x)
)
)
```
This PR allows them to cancel out.
The heap2local pass is performed before the optimize-casts pass [the local-subtyping pass, actually], which would have removed the cast. I first considered modifying the optimize-instruction pass, similarly to what is done for tuples in #5938, but this is more general.
It might make sense to handle tuples in a similar manner, by the way.
=> Make heap2local work through casts

scripts/gen-s-parser.py, src/gen-s-parser.inc, src/parser/contexts.h, src/parser/parsers.h, src/wasm-ir-builder.h, src/wasm/wasm-ir-builder.cpp, test/lit/wat-kitchen-sink.wast
Parse both the straight-line and folded versions of if, including the
abbreviations that allow omitting the else clause. In the IRBuilder, generalize
the scope stack to be able to track scopes other than blocks and add methods for
visiting the beginnings of ifs and elses.
=> [Parser] Parse if-else in the new wat parser and IRBuilder

scripts/gen-s-parser.py, src/gen-s-parser.inc, src/parser/context-decls.cpp, src/parser/context-defs.cpp, src/parser/contexts.h, src/parser/parsers.h
The new wat parser previously returned InstrT types when parsing individual
instructions and collected InstrsT types when parsing sequences of instructions.
However, instructions were always actually tracked in the internal state of the
parsing context, so these types never held any interesting or necessary data.
Simplify the parser by removing these types and leaning into the pattern that
the parser context will keep track of parsed instructions.
This allows for a much cleaner separation between the `instrs` and
`foldedinstrs` parser functions.
=> [NFC][Parser] Simplify instruction handling

src/parser/input-impl.h, src/parser/input.h, src/parser/parsers.h, test/lit/wat-kitchen-sink.wast
Somewhat counterintuitively, the text syntax for a folded `if` allows any number
of folded instructions in the condition position, not just one. Update the
corresponding `foldedinsts` parsing function to parse arbitrary sequences of
folded instructions and add a test.
=> [Parser] Allow any number of foldedinsts in `foldedinsts`

src/parser/context-defs.cpp, src/parser/contexts.h, src/parser/wat-parser.cpp, src/wasm-ir-builder.h, src/wasm/wasm-ir-builder.cpp, test/lit/wat-kitchen-sink.wast
Add a `visitFunctionStart` function to IRBuilder and make it responsible for
setting the function's body when the context is closed. This will simplify
outlining, will be necessary to support branches to function scope properly, and
removes an extra block around function bodies in the new wat parser.
=> Support function contexts in IRBuilder

src/passes/NameTypes.cpp, src/passes/TypeSSA.cpp, test/lit/passes/name-types.wast, test/lit/passes/type-ssa.wast, test/lit/passes/type-ssa_and_merging.wast, test/lit/recursive-types.wast
Apparently `$N` (e.g. `FooClass$5`) is a convention in Java for anonymous classes, so our
`$N` that we use to disambiguate could be confusing. As the way we disambiguate does
not matter, switch to using `_N`. This PR does that in both `TypeSSA` and `NameTypes`.
Also make `NameTypes` "lint" names as it goes. That pass tries to give types nice names,
leaving existing ones that seem ok, and renaming long or unnamed ones. This PR makes
it aware of the `_N` notation and it tries to remove it, if removing it does not cause a
collision. An example of how that helps is if TypeSSA creates a subtype `$Foo_0` and then
we manage to remove `$Foo`, then we can use the shorter name for the subtype.
=> NameTypes and TypeSSA : Prefer _ over $ in names, and lint away _N suffixes

src/ir/struct-utils.h, src/passes/ConstantFieldPropagation.cpp, test/lit/passes/cfp.wast
If we see `A->f0 = A->f0` then we might be copying fields not only between
instances of `A` but also of any subtypes of `A`, and so if some subtype has
value `x` then that `x` might now have reached any other subtype of `A`
(even in a sibling type, so long as `A` is their parent).
We already thought we were handling that, but the mechanism we used to
do so (copying New info to Set info, and letting Set info propagate) was not
enough.
Also add a small constructor to save the work of computing subTypes again.
Add TODOs for some cases that we could optimize regarding copies but
do not, yet.
=> ConstantFieldPropagation: Fully handle copies

src/ir/type-updating.cpp, src/passes/TypeMerging.cpp, src/wasm-type-ordering.h
Move the topological sort from the constructor to a separate method. This CRTP
utility calls into its subclass to query supertype relationships, but doing so
in the base class constructor means that the subclass has not been fully
initialized yet, which can cause problems.
=> [NFC] Refactor SupertypesFirst utility

src/wasm-s-parser.h, src/wasm/wasm-s-parser.cpp, test/lit/parse-bad-nominal-types.wast, test/lit/parse-bad-tuple-extract-index.wast
Instead of just reporting the reason and line + column, also log out the element
the error occurred at.
Supercedes #5980
=> wasm-s-parser: Add context in validation errors

src/wasm/wasm-validator.cpp, src/wasm/wasm.cpp, test/lit/cast-to-basic.wast, test/lit/heap-types.wast, test/lit/passes/remove-unused-brs-gc.wast
Just like we do with other casts, refine the cast type to be the greatest lower
bound of its previous cast type and its input type. The difference is that the
output type of ref.test remains i32, but it's still useful to retain more
precise type information.
=> Refine ref.test's castType during refinalization

src/parser/contexts.h, src/parser/parsers.h, src/wasm-ir-builder.h, src/wasm/wasm-ir-builder.cpp, src/wasm/wasm-validator.cpp, test/lit/wat-kitchen-sink.wast
The parser previously parsed labels and could attach them to control flow
structures, but did not maintain the context necessary to correctly parse
branches. Support parsing labels as both names and indices in IRBuilder,
handling shadowing correctly, and use that support to implement parsing of br.
=> [Parser] Parse labels and br

src/emscripten-optimizer/simple_ast.h
C++20 will automatically generate an operator== with reversed operand order, which is ambiguous with the written operator== when one argument is marked const and the other isn't.
Even outside the context of C++20, I believe this is semantically correct.
=> mark operator== as const

src/passes/Asyncify.cpp, test/lit/passes/asyncify-wasm64.wast, test/lit/passes/asyncify-wasm64_pass-arg=in-secondary-memory.wast, test/lit/passes/asyncify.wast, test/lit/passes/asyncify_enable-multivalue.wast, test/lit/passes/asyncify_mod-asyncify-always-and-only-unwind.wast, test/lit/passes/asyncify_mod-asyncify-always-and-only-unwind_O.wast, test/lit/passes/asyncify_mod-asyncify-never-unwind.wast, test/lit/passes/asyncify_mod-asyncify-never-unwind_O.wast, test/lit/passes/asyncify_optimize-level=1.wast, test/lit/passes/asyncify_pass-arg=asyncify-addlist@foo_pass-arg=asyncify-ignore-indirect.wast, test/lit/passes/asyncify_pass-arg=asyncify-blacklist@foo,bar.wast, test/lit/passes/asyncify_pass-arg=asyncify-ignore-imports.wast, test/lit/passes/asyncify_pass-arg=asyncify-ignore-indirect.wast, test/lit/passes/asyncify_pass-arg=asyncify-imports@env.import,env.import2.wast, test/lit/passes/asyncify_pass-arg=asyncify-onlylist@foo,bar.wast, test/lit/passes/asyncify_pass-arg=asyncify-verbose.wast, test/lit/passes/asyncify_pass-arg=in-secondary-memory.wast
```wast
(if (result i32)
(expr0)
(i32.const 1)
(expr1)
)
```
can be written as
```wast
(i32.or
(expr0)
(expr1)
)
```
Also this removes some unused variables and methods.
This also adds an optimization for
```wast
(i32.eqz                                                                   
(global.get $__asyncify_state)                                            
)
```
in `--mod-asyncify-always-and-only-unwind` to fix an unexpected regression caused by this.
=> Asyncify: Simpify if into i32.or

src/passes/Asyncify.cpp, src/passes/SimplifyGlobals.cpp, src/tools/wasm-reduce.cpp, test/lit/help/wasm-reduce.test
This fixes some outdated comments and typos in Asyncify and improves some other comments. This tries to make code comments more readable by making them more accurate and also by using the three state (normal, unwinding, and rewinding) consistently.
Drive-by fix: Typo fixes in SimplifyGlobals and wasm-reduce option.
=> Asyncify: Improve comments

src/passes/CMakeLists.txt, src/passes/hash-stringify-walker.cpp, src/passes/stringify-walker.h, test/gtest/stringify.cpp
This PR adds a StringProcessor struct intended to hold functions that filter vectors of SuffixTree::RepeatedSubstring, and a test of its first functionality, removing overlapping repeated substrings.
=> [Outlining] Adds SuffixTree::RepeatSubstring dedupe test

src/passes/hash-stringify-walker.cpp, src/passes/stringify-walker-impl.h, src/passes/stringify-walker.h, test/gtest/stringify.cpp
Adds a std::variant to represent the context of why a unique symbol was inserted in the stringified module. This allows us to pass necessary contextual data to subclasses of StringifyWalker in a structured manner.
=> [Outlining] Adds separator context

src/passes/Print.cpp, src/wasm/wasm-validator.cpp, test/exception-handling.wast.from-wast, test/exception-handling.wast.fromBinary, test/exception-handling.wast.fromBinary.noDebugInfo, test/lit/merge/fusing.wat, test/lit/passes/coalesce-locals-eh.wast, test/lit/passes/dce-eh.wast, test/lit/passes/global-effects.wast, test/lit/passes/gufa-refs.wast, test/lit/passes/rse-eh.wast, test/lit/passes/type-refining.wast, test/metadce/tag.wast.dced, test/spec/exception-handling.wast, test/spec/tags.wast, test/tags.wast.from-wast, test/tags.wast.fromBinary, test/tags.wast.fromBinary.noDebugInfo, test/try-delegate.wasm.fromBinary, test/unit/test_features.py
This PR is part of a series that adds basic support for the [typed continuations proposal](https://github.com/wasmfx/specfx).
This PR relaxes the restriction that tags must not have `result`s , only `param`s. Tags with results must not be used for exception handling and are only allowed if the typed continuations feature is enabled.
As a minor point, this PR also changes the printing of tags without `param`s: To make the presentation consistent, `(param)` is omitted when printing a tag.
=> Typed Continuations: Allow result types on tags

README.md
The `first` module's `(import "second" "bar"...` gets satisfied by the `second` module's `(export "bar" (func $func))` and goes away.
=> README.md: eliminate spurious import in wasm-merge sample output

scripts/fuzz_opt.py
The number of ignored functions is logged out, so this can help us avoid getting
into a situation where many testcases just trap most of the time rather than
doing anything useful.
50% seems a reasonable cutoff. Even if 50% of functions trap, at least we are
getting 50% that don't, so lots of useful work.
We don't seem to have a problem with this atm, e.g.
```
ITERATION: 32278 [..] 91 ignored
```
So less than 100 ignored out of 32 K there. Still, this could regress with any
fuzzer change in theory.
=> Fuzzer: Mark runs where over 50% of functions trap as ignored

src/passes/hash-stringify-walker.cpp, src/passes/stringify-walker.h, src/support/suffix_tree.h, test/gtest/stringify.cpp
Adds a general purpose walker named FilterStringifyWalker, intended to walk control flow and take note of whether any of the expressions satisfy the `condition`.
Also includes an `<<` overload for SuffixTree::RepeatedSubstring to make debugging easier.
=> [Outlining] Filter Local Set

src/analysis/CMakeLists.txt, src/analysis/lattice.h, src/analysis/lattices/powerset-impl.h, src/analysis/lattices/powerset.h, src/analysis/liveness-transfer-function.h
Move the powerset lattices out of lattice.h, which now only contains the Lattice
concept, to their own dedicated header in a new analysis/lattices directory.
=> [analysis][NFC] Move powerset lattices to their own header

src/analysis/cfg-impl.h, src/analysis/lattice.h, src/analysis/monotone-analyzer-impl.h, src/analysis/monotone-analyzer.h, src/analysis/transfer-function.h, src/analysis/visitor-transfer-function.h, src/tools/wasm-fuzz-lattices.cpp
Factor the static assertions for transfer functions out into a new
transfer-function.h header. The concept requires the `getDependents` method to
return an input range of basic blocks, and to satisfy that requirement, fix up
_indirect_ptr_iterator in cfg-impl.h so that it is a proper iterator. Remove
part of the lattice fuzzer that was using a placeholder transfer function in a
way that does not satisfy the new type constraints; most of that code will be
overhauled in the future anyway.
=> [analysis][NFC] Create a TransferFunction concept

src/wasm/wasm-validator.cpp, test/gtest/CMakeLists.txt, test/gtest/validator.cpp
While working on testing some new [binaryen.ml](https://github.com/grain-lang/binaryen.ml) bindings for Grain, I came across a segmentation fault in the Binaryen WASM validator. The problem is that, if you construct a `try` expression which references a nonexistent tag in one of its `catch` blocks, the validation code successfully identifies the `null` pointer but then proceeds to try to read from it. I have updated the validation code to mitigate this problem and added in a unit test. I verified that backing out the change to `wasm-validator.cpp` causes the unit test file to segfault.
Note that this is not an issue that can be reproduced with the Python `check.py` test suite, since the s-expression parser will reject the malformed `try` block.
Apologies in advance for any faux pas in the …
=> fix: Avoid segfault in catch validator

src/ir/LocalGraph.cpp
`allGets` was declared in a scope that kept it alive for all blocks, and at
the end of the loop we clear the gets for a particular block. That's clumsy,
and makes a followup harder, so this PR moves it to the natural place for it.
(That is, it moves it to the scope that handles a particular block, and removes
the manual clearing-out of the get at the end of the loop iteration.) Optimizing
compilers are smart enough to be efficient about stack allocations
of objects inside loops anyhow (which I measured).
Helps #6042.
=> [NFC] LocalGraph: Move definition to logical place

src/ir/LocalGraph.cpp, test/lit/passes/precompute-gc.wast
If a local index has no sets, then all gets of that index read from the entry block
(a param, or a zero for a local). This is actually a common case, where a param
has no other set, and so it is worth optimizing, which this PR does by avoiding
any flowing operation at all for that index: we just skip and write the entry block
as the source of information for such gets.
#6042 on `precompute-propagate` goes from 3 minutes to 2 seconds with this (!).
But that testcase is rather special in that it is a huge function with many, many
gets in it, so the overhead we remove here is very noticeable.
=> [NFC] LocalGraph: Optimize params with no sets

src/ir/LocalGraph.cpp, src/ir/local-graph.h, src/passes/Precompute.cpp, test/lit/passes/precompute-gc.wast
Followup to #6046 - the fuzzer found we missed handling the case of the entry itself
being unreachable and there being a loop after it, see code and testcase.
Also add a "dump" impl in that file which helps debugging.
=> Fix the case of an unreachable entry in LocalGraph

src/analysis/liveness-transfer-function.h, src/analysis/reaching-definitions-transfer-function.h
This missing include was not a problem in our standard build configuration, but
was breaking other build configurations.
=> Add a missing include

src/analysis/lattice.h, src/analysis/lattices/powerset-impl.h, src/analysis/lattices/powerset.h, src/analysis/lattices/stack.h, src/analysis/monotone-analyzer-impl.h, test/gtest/cfg.cpp
In general, the operation of taking the least upper bound of two lattice
elements may depend on some state stored in the lattice object rather than in
the elements themselves. To avoid forcing the elements to be larger and more
complicated in that case (by storing a parent pointer back to the lattice), move
the least upper bound operation to make it a method of the lattice rather than
the lattice element. This is also more consistent with where we put e.g. the
`compare` method.
While we are at it, rename `makeLeastUpperBound` to `join`, which is much
shorter and nicer. Usually we avoid using esoteric mathematical jargon like
this, but "join" as a normal verb actually describes the operation nicely, so I
think it is ok in this case.
=> [analysis][NFC] Rename `makeLeastUpperBound` to `join` and move it to lattice

src/analysis/lattices/bool.h, test/gtest/CMakeLists.txt, test/gtest/lattices.cpp
This is a lattice with two elements: `false` is bottom and `true` is top.
Add a new gtest file for testing lattices.
=> [analysis] Implement a Bool lattice

src/analysis/lattices/int.h, test/gtest/lattices.cpp
Implement a generic lattice template for integral types ordered by `<`.
=> [analysis] Implement an Int lattice

src/analysis/lattices/flat.h, test/gtest/lattices.cpp
Given a type `T`, `Flat<T>` is the lattice where none of the values of `T` are
comparable except with themselves, but they are all greater than a common bottom
element not in `T` and less than a common top element also not in `T`.
=> [analysis] Implement Flat lattice

src/passes/Precompute.cpp, test/lit/passes/precompute-gc.wast
Followup to #6048, we did not handle nondefaultable tuples because of this.
=> Precompute: Check defaultability, not nullability

src/analysis/lattices/flat.h, src/analysis/lattices/inverted.h, src/analysis/lattices/lift.h, test/gtest/lattices.cpp
This lattice "lifts" another lattice by inserting a new bottom element
underneath it.
=> [analysis] Implement a Lift lattice

test/lit/wasm-split/profile-guided.wast
Apparently the version of node on the Alpine runner was updated and no longer
recognizes the --experimental-wasm-threads option. Delete this option out of the
test that was using it.
=> Fix Alpine CI by removing old node flag

src/analysis/lattices/inverted.h, src/analysis/lattices/lift.h, src/tools/wasm-fuzz-lattices.cpp
Implement new `RandomLattice` and `RandomFullLattice` utilities that are
lattices randomly created from other lattices. By recursively using themselves
as the parameter lattices for lattices like `Inverted` and `Lift`, these random
lattices can become arbitrarily nested.
Decouple the checking of lattice properties from the checking of transfer
function properties by creating a new, standalone `checkLatticeProperties`
function.
=> [analysis] Improve lattice fuzzer

src/analysis/lattices/bool.h, src/analysis/lattices/flat.h, src/analysis/lattices/int.h, src/analysis/lattices/inverted.h, src/analysis/lattices/lift.h, src/analysis/lattices/powerset-impl.h, src/analysis/lattices/powerset.h, src/analysis/lattices/stack.h
Since these methods, which operate on lattice elements, moved to the lattice
types, it no longer makes much sense for their parameters to be called `self`
and `other`. Rename them to `joinee` and `joiner` for joins and `meetee` and
`meeter` for meets.
=> [analysis][NFC] Rename parameters to join and meet methods

src/analysis/lattices/array.h, src/tools/wasm-fuzz-lattices.cpp, test/gtest/lattices.cpp
The elements of `Array<L, N>` lattice are arrays of length `N` of elements of
`L`, compared pairwise with each other. This lattice is a concrete
implementation of what would be written L^N with pen and paper.
=> [analysis] Implement an array lattice

src/analysis/lattices/vector.h, src/tools/wasm-fuzz-lattices.cpp, test/gtest/lattices.cpp
The vector lattice is nearly identical to the array lattice, except that the
size of the elements is specified at runtime when the lattice object is created
rather than at compile time. The code and tests are largely copy-pasted and
fixed up from the array implementation, but there are a couple differences.
First, initializing vector elements does not need the template magic used to
initialize array elements. Second, the obvious implementations of join and meet
do not work for vectors of bools because they might be specialized to be bit
vectors, so we need workarounds for that particular case.
=> [analysis] Implement a vector lattice

src/analysis/lattices/tuple.h, src/tools/wasm-fuzz-lattices.cpp, test/gtest/lattices.cpp
This lattice combines any number of other lattices into a single lattice whose
elements are tuples of elements of the other lattices. This will be one of the
most important lattices in the analysis framework because it will be used to
combine information about different parts of the program, e.g. locals and the
value stack, into a single lattice.
=> [analysis] Add a tuple lattice

src/passes/OnceReduction.cpp, test/lit/passes/once-reduction.wast
In particular, if the body just calls another "once" function, then we can
skip the early-exit logic (see details in the comment in the new code).
Followup/replacement of #6055 
cc @gkdn
=> OnceReduction: Optimize bodies of trivial "once" functions

src/passes/OnceReduction.cpp, test/lit/passes/once-reduction.wast
Followup to #6061 in which we only optimized the case of a "once" function immediately
calling another and doing nothing else. It is ok to do more things afterwards, so long as
we do nothing else before, by the same logic as already mentioned in the pass (but
clarified as to the meaning of "called" - all we need is for the function to have been
"entered" in the proof there, IIANM).
@gkdn am I missing something?
=> [NFC] Improve OnceReduction comment

src/analysis/lattices/valtype.h, src/tools/wasm-fuzz-lattices.cpp, test/gtest/lattices.cpp
Add a lattice that is a thin wrapper around `wasm::Type` giving it the interface
of a lattice. As usual, `Type::unreachable` is the bottom element, but unlike in
the underlying API, we uniformly treat `Type::none` as the top type so that we
have a proper lattice.
=> [analysis] Add a lattice for value types

src/analysis/lattices/flat.h, test/gtest/lattices.cpp
Many of the lattice tests were essentially copy-pasted from one lattice to the
next because they all tested isomorphic subsets of the various lattices,
specifically in the shape of a diamond. Refactor the code so that all lattices
that have tests of this shape use the same utility test functions.
=> [analysis][NFC] Refactor lattice unit tests

src/passes/SimplifyLocals.cpp, test/lit/passes/simplify-locals-gc-nn.wast
We handled references but not tuples in one place.
=> NonNullable => !Defaultable in SimplifyLocals

scripts/update_lit_checks.py
After merging #6051 update_lit_checks.py was broken, because I used placholder '%S' in lit test. This PR add support for this placeholder also in update_lit_checks.py
=> Support '%S' placeholder in update_lit_checks.py

src/analysis/lattices/shared.h, src/tools/wasm-fuzz-lattices.cpp, test/gtest/lattices.cpp
The analysis framework stores a separate lattice element for each basic block
being analyzed to represent the program state at the beginning of the block.
However, in many analyses a significant portion of program state is not
flow-sensitive, so does not benefit from having a separate copy per block. For
example, an analysis might track constraints on the types of locals that do not
vary across blocks, so it really only needs a single copy of the constrains for
each local. It would be correct to simply duplicate the state across blocks
anyway, but it would not be efficient.
To make it possible to share a single copy of a lattice element across basic
blocks, introduce a `Shared<L>` lattice. Mathematically, this lattice represents
a single ascending chain in the underlying lattice and its …
=> [analysis] Add a "Shared" lattice to represent shared state

src/analysis/lattices/inverted.h, src/analysis/lattices/shared.h, src/analysis/lattices/vector.h, test/gtest/lattices.cpp
Previously, modifying a single vector element of a `Shared<Vector>` element
required materializing a full vector to do the join. When there is just a single
element to update, materializing all the other elements with bottom value is
useless work. Add a `Vector<L>::SingletonElement` utility that represents but
does not materialize a vector with a single non-bottom element and allow it to
be passed to `Vector<L>::join`. Also update `Shared` and `Inverted` so that
`SingletonElement` joins still work on vectors wrapped in those other lattices.
=> [analysis] Allow joining a single vector element efficiently

src/analysis/cfg.cpp, src/analysis/cfg.h, src/cfg/cfg-traversal.h, test/gtest/cfg.cpp
Previously CFGWalker designated a particular block as the "exit" block, but it
was just the block that happened to appear at the end of the function that
returned values by implicitly flowing them out. That exit block was not tied in
any way to other blocks that might end in returns, so analyses that needed to
perform some action at the end of the function would have had to perform that
action at the end of the designated exit block but also separately at any return
instruction.
Update CFGWalker to make the exit block a synthetic empty block that is a
successor of all other blocks that implicitly or explicitly return from the
function in case there are multiple such blocks, or to make the exit block the
single returning block if there is only one. This means that analyses will only …
=> Update CFGWalker to generate consolidated exit blocks

.github/workflows/ci.yml, src/tools/wasm-fuzz-lattices.cpp
Update the C++20 builder to use Ubuntu 20.04 to catch problems building with its system compiler. Also fix such a problem in wasm-fuzz-lattices.cpp.
=> Fix build failure on older Ubuntu

src/parser/contexts.h, src/parser/parsers.h, src/wasm-ir-builder.h, src/wasm/wasm-ir-builder.cpp, test/lit/wat-kitchen-sink.wast
To support parsing calls, add support for parsing function indices and building
calls with IRBuilder.
=> [Parser] Parse `call` and `return_call`

src/passes/LocalCSE.cpp, test/lit/passes/inlining-optimizing_optimize-level=3.wast, test/lit/passes/local-cse.wast
LocalCSE is nice for large expressions, but for small things it has always been of
unclear benefit since VMs also do GVN/CSE anyhow. So we are likely not speeding
anything up, but hopefully we are reducing code size at least. Doing LocalCSE on
something small like a `global.get` is very possibly going to increase code size,
however (since we add a tee, and since the local gets are of similar size to global
gets - depends on LUB sizes). On real-world Java code that overhead is noticeable,
so this PR makes us more careful, and we skip things of size 1 (no children).
=> LocalCSE: Do not optimize small things like global.get

src/passes/CMakeLists.txt, src/passes/SeparateDataSegments.cpp, src/passes/pass.cpp, src/passes/passes.h, src/tools/wasm-emscripten-finalize.cpp, src/wasm-emscripten.h, src/wasm/wasm-emscripten.cpp, test/lit/help/wasm-opt.test, test/lit/help/wasm2js.test, test/lit/passes/separate-data-segments.wast
Because we currently strip some data segments (i.e. EM_JS strings) during `--post-emscripten` this is too late `--separate-data-segments` always runs in `wasm-emscripten-finalize`.
Once emscripten switches over to using the pass directly we can remove the support from `wasm-emscripten-finalize`
=> Move --separate-data-segments into a pass so it can be run from wasm-opt

src/passes/Heap2Local.cpp, test/lit/passes/heap2local.wast
We had a simple rule that if we reach an expression twice then we give up, which makes
sense for say a block: if one allocation flows out of it, then another can't - it would get
mixed in with the other one, which is a case we don't optimize. However, there are
cases where a parent has multiple children and different interactions with them, like
a struct.set: the reference child does not escape, but the value child does. Before this
PR if we reached the value child first, we'd mark the parent as seen, and then the reference
child would see it isn't the first to get here, and not optimize.
To fix this, reorder the code to handle this case. The manner of interaction between the
child and the parent decides whether we mark the parent as seen and to be further
avoided.
Noticed by the …
=> Heap2Local: Fix an ordering issue with children having different interactions with a parent

src/passes/StackIR.cpp, test/lit/passes/stack-ir-non-nullable.wast
Also add testcases to be comprehensive and notice changes if we ever decide to
modify that behavior.
Seen while auditing all uses of `isNonNullable` in the codebase.
=> [NFC] StackIR: Add comments on local2stack handling of tuples

src/ir/literal-utils.h
Seen while auditing all uses of isNonNullable in the codebase.
=> [NFC] Simplify LiteralUtils::canMakeZero

scripts/gen-s-parser.py, src/gen-s-parser.inc, src/parser/parsers.h
The new wat parser parses block, if, loop, then, and else keywords directly
rather than depending on code generated from gen-s-parser.py. Filter these
keywords out in gen-s-parser.py when generating the new wat parser and delete
the stub functions that the removed generated code used to depend on.
=> [Parser][NFC] Filter out unused instructions in gen-s-parser.py

CMakeLists.txt, src/analysis/lattices/inverted.h, src/analysis/lattices/lift.h, src/analysis/lattices/shared.h, src/analysis/lattices/stack.h, src/analysis/lattices/vector.h, src/analysis/monotone-analyzer.h, src/wasm-type-printing.h
Class template argument deduction (CTAD) is a C++17 feature that allows
variables to be declared with class template types without specifying the
template parameters. Deduction guides are a mechanism by which template authors
can control how the template parameters are inferred when CTAD is used. The
Google style guide prohibits the use of CTAD except where template authors opt
in to supporting it by providing explicit deduction guides. For compatibility
with users adhering to Google style, set the compiler flag to check this
condition and add the necessary deduction guides to make the compiler happy
again.
=> [NFC] Add explicit deduction guides for CTAD

src/passes/OptimizeInstructions.cpp, test/lit/passes/optimize-instructions-mvp.wast
We had an assert there that was wrong. In fact the assert is just in one of two code paths,
and an optional one: the end situation is we have an expression and a constant to add to it,
and the assert was in the case that the expression is a Const so we can do the add at
compile time (the other code path does the add at runtime). This code path is optional as
Precompute would do such compile-time addition anyhow, but it is nice to fix and leave that
path so that this pass emits fully optimal code.
=> OptimizeAddedConstants: Handle a final added constant properly

src/ir/possible-contents.cpp, src/ir/possible-contents.h
This is not needed in GUFA as it tracks local values precisely (each set is connected to
the gets that actually read from it), but in a future PR it will be useful to track local
values per index (each set is connected to all gets for that index, i.e., each local index
is a single "location").
=> [NFC] Add LocalLocation for future use

src/parser/contexts.h, src/parser/parsers.h, src/wasm-ir-builder.h, src/wasm/wasm-ir-builder.cpp, test/lit/wat-kitchen-sink.wast
Also mark array.new_elem as unimplemented as a drive-by; it previously had an
incorrect implementation.
=> [Parser] Parse call_ref

src/passes/SignatureRefining.cpp, test/lit/passes/signature-refining.wast
`call.without.effects` implies a call to the function reference in the last parameter,
so the values sent in the other parameters must be taken into account when
computing LUBs for refining arguments, otherwise we might refine so much that
the intrinsic call no longer validates.
=> SignatureRefining: Notice LUB requirements of intrinsic calls

src/passes/TypeGeneralizing.cpp, src/wasm/wasm-validator.cpp, test/lit/passes/type-generalizing.wast
Finish the transfer functions for all expressions except for string
instructions, exception handling instructions, tuple instructions, and branch
instructions that carry values. The latter require more work in the CFG builder
because dropping the extra stack values happens after the branch but before the
target block.
=> Implement more TypeGeneralizing transfer functions

src/passes/Outlining.cpp, src/wasm-ir-builder.h, src/wasm/wasm-ir-builder.cpp, test/lit/passes/outlining.wast
Besides `If`, no control flow structure consumes values from the stack. Fix a
bug in IRBuilder that was causing it to pop control flow children. Also fix a
follow on bug in outlining where it did not make the If condition available on
the stack when starting to visit an If. This required making `push()` part of
the public API of IRBuilder.
As a drive-by, also add helpful debug logging to IRBuilder.
=> Update IRBuilder to visit control flow correctly

test/lit/passes/outlining.wast
Adds tests that ensure outlining is skipping repeat sequences that include local.get, local.set, br, and return instructions.
=> [Outlining] Adds filter tests

src/wasm-ir-builder.h, src/wasm/wasm-ir-builder.cpp, test/lit/passes/outlining.wast
Adds support for call_indirect to wasm-ir-builder. Tests this works by outlining a sequence including call_indirect.
=> [IRBuilder] Add visitCallIndirect and makeCallIndirect

src/wasm-ir-builder.h, src/wasm/wasm-ir-builder.cpp, test/lit/wat-kitchen-sink.wast
When branches target control flow structures other than blocks or loops, the
IRBuilder wraps those control flow structures with an extra block for the
branches to target in Binaryen IR. Usually that block has the same type as the
control flow structure it wraps, but when the control flow structure is
unreachable because all its bodies are unreachable, the wrapper block may still
need to have a non-unreachable type if it is targeted by branches.
Previously the wrapper block would also be unreachable in that case. Fix the bug
by tracking whether the wrapper block will be targeted by any branches and use
the control flow structure's original, non-unreachable type if so.
=> Fix a bug with unreachable control flow in IRBuilder

src/passes/Asyncify.cpp, src/passes/opt-utils.h, src/passes/pass-utils.h
Asyncify gained a way to wrap a pass so that it only runs on a given set of
functions, rather than on all functions, so the wrapper "filters" what the pass
operates on. That was useful in Asyncify as we wanted to only do work on
functions that Asyncify actually instrumented.
There is another place in the code that needs such functionality,
`optimizeAfterInlining`, which runs optimizations after we inline; again, we
only want to optimize on the functions we know are relevant because they
changed. To do that, move that logic out to a general place so it can be
reused. This makes the code there a lot less hackish.
While doing so make the logic only work on function-parallel passes. It
never did anyhow, but now it asserts on that. (It can't run on a general
pass because a general one does not …
=> [NFC] Move InstrumentedPass logic out and use it in another place

src/binaryen-c.cpp, src/binaryen-c.h, test/example/c-api-multiple-tables.c
issue #6136 points out that Binaryen C API currently does not support getting and setting the element type of table, this pull request is intended to fix that.
=> C API: Add BinaryenTableGetType and BinaryenTableSetType

scripts/gen-s-parser.py, src/gen-s-parser.inc, src/parser/contexts.h, src/parser/parsers.h, src/wasm-ir-builder.h, src/wasm/wasm-ir-builder.cpp, test/lit/wat-kitchen-sink.wast
Parse the legacy v3 syntax for try/catch/catch_all/delegate in both its folded
and unfolded forms.
The first source of significant complexity is the optional IDs after `catch`
and `catch_all` in the unfolded form, which can be confused for tag indices and
require backtracking to parse correctly.
The second source of complexity is the handling of delegate labels, which are
relative to the try's parent scope despite being parsed after the try's scope
has already started. Handling this correctly requires punching a hole big
enough to drive a truck through through both the parser and IRBuilder
abstractions.
=> [Parser] Parse try/catch/catch_all/delegate

src/pass.h, src/passes/Inlining.cpp, test/lit/passes/inlining-optimizing_optimize-level=3.wast, test/lit/passes/inlining_optimize-level=3.wast
A trivial call is something like a function that just calls another immediately,
```js
function foo(x, y) {
return bar(y, 15);
}
```
We can inline those and expect to benefit in most cases, though we might
increase code size slightly. Hence it makes sense to inline such cases, even
though in general we are careful and do not inline functions with calls in
them; a "trampoline" like that likely has most of the work in the call itself,
which we can avoid by inlining.
Suggested by @gkdn based on findings in Java.
I ran this on the emscripten code size tests and saw nothing that looked
negative or concerning. In fact, this ends up reducing code size slightly
more often than it increases (and all the changes I inspected look like
they should improve speed).
=> Inlining: Inline trivial calls
