src/parser/context-decls.cpp
src/parser/context-defs.cpp
src/parser/contexts.h
src/parser/parsers.h
src/parser/wat-parser.cpp
src/support/result.h
test/lit/wat-kitchen-sink.wast

These module fields are especially complex to parse because they contain both
nontrivial types and instructions, so their parsing logic needs to be spread out
across the ParseDecls, ParseModuleTypes, and ParseDefs phases of parsing. This
applies to in-line elements in table definitions as well, which means we need to
be able to match a table to its in-line element segment across multiple phases.

[Parser] Parse tables and element segments

---

scripts/test/shared.py
scripts/test/wasm2js.py

Currently `get_tests` returns files and directories, especially when the extension is not given. This makes `get_tests` return a directory like `test/wasm2js/` as a test.
`wasm2js.py`'s `check_for_stale_files` errors out when there are files within `test/wasm2js/` whose basenames don't match any files within any of `test/`, `test/spec/`, `test/wasm2js/`.
https://github.com/WebAssembly/binaryen/blob/1d615b38dd4152494d2f4d3520c8b1d917624a30/scripts/test/wasm2js.py#L33-L46
`wasm2js.wast.asserts` is apparently a special case for asserts test: https://github.com/WebAssembly/binaryen/blob/1d615b38dd4152494d2f4d3520c8b1d917624a30/scripts/test/wasm2js.py#L28 and this doesn't seem to have the matching `wast` tests in the three test directories. But it just happened to not error out because …

[test] Make get_tests return only files

---

scripts/test/shared.py
scripts/test/wasm_opt.py
test/lit/passes/inlining-optimizing_optimize-level=3.wast

We don't have `*.fromasm` files anymore. Also `BIN_DIR` and `WATERFALL_BUILD_DIR` variables don't seem to be used as well.

[test] Remove asm2wasm tests from scripts

---

scripts/test/wasm2js.py

I tried to exclude wasm2js asserts tests from `check_for_stale_files` in #6164, but ended up doing it incorrectly. The file I checked for was `wasm2js.wast.asserts`, while the output I should have excluded was `wasm2js.asserts.js`. This fixes the code so we now check the prefix and not the filename.
This is currently breaking the main branch, which was caused by me landing multiple PRs at once. Sorry for the breakage. Landing this will fix it.

[test] Fix wasm2js stale check failure

---

scripts/gen-s-parser.py
src/gen-s-parser.inc
src/parser/parsers.h
src/passes/Print.cpp
src/wasm-s-parser.h
src/wasm/wasm-s-parser.cpp
test/binaryen.js/kitchen-sink.js.txt
test/example/c-api-kitchen-sink.txt
test/lit/basic/types-function-references.wast
test/lit/multivalue.wast
test/lit/passes/coalesce-locals-gc.wast
test/lit/passes/gufa-refs.wast
test/lit/passes/poppify.wast
test/lit/passes/remove-unused-brs.wast
test/lit/passes/roundtrip.wast
test/lit/passes/simplify-locals-gc-nn.wast
test/lit/passes/vacuum_all-features.wast
test/lit/validation/bad-non-nullable-locals.wast
test/lit/wat-kitchen-sink.wast
test/passes/precompute_all-features.wast
test/passes/rse_all-features.txt
test/unit/test_features.py

We previously overloaded `drop` to mean both normal drops of single values and
also drops of tuple values. That works fine in the legacy text parser since it
can infer parent-child relationships directly from the s-expression structure of
the input, so it knows that a drop should drop an entire tuple if the
tuple-producing instruction is a child of the drop. The new text parser,
however, is much more like the binary parser in that it uses instruction types
to create parent-child instructions. The new parser always assumes that `drop`
is meant to drop just a single value because that's what it does in WebAssembly.
Since we want to continue to let `Drop` IR expressions consume tuples, and since
we will need a way to write tests for that IR pattern that work with the new
parser, introduce a …

Add a `tuple.drop` text pseudoinstruction

---

src/passes/J2CLOpts.cpp
test/lit/passes/j2cl-inline.wast
test/lit/passes/j2cl.wast

The patch puts a new guardrail that will only hoist the field if it is initialized with the owner class.
The constant hoisting optimization in J2CL pass relies on the assumption that clinit that will initialize the field will be executed before the read of the field. That means the field that is optiized is within the same class:
class Foo {
public static final Object field = new Object();
}
Although it is possible to observe the initial value, that is not intention of the developer (which the point of the optimization).
However can also see a similar pattern in following:
class Foo {
public static Object field;
}
class Zoo {
static {
Foo.field = new Object();
}
}
Currently the pass also optimizes it as well since the field is only initialized once and by a clinit. However Zoo clinit is …

Put extra guardrails for J2CLOpts.

---

src/parser/contexts.h
src/parser/parsers.h
src/wasm-ir-builder.h
src/wasm.h
src/wasm/wasm-ir-builder.cpp
test/lit/wat-kitchen-sink.wast

Including table.get, table.set, table.size, table.grow, table.fill, and
table.copy.

[Parser] Parse table operations

---

src/parser/contexts.h
src/parser/parsers.h
src/wasm-ir-builder.h
src/wasm/wasm-ir-builder.cpp
test/lit/wat-kitchen-sink.wast

Like `delegate`, rethrow takes a `Try` label. Refactor the delegate handling so
that `Try` can share its logic.

[Parser] Parse rethrow

---

src/parser/contexts.h
src/parser/input-impl.h
src/parser/input.h
src/parser/parsers.h
src/wasm-ir-builder.h
src/wasm.h
src/wasm/wasm-ir-builder.cpp
test/lit/wat-kitchen-sink.wast

Parse `array.new_elem`, `array.init_data`, and `array.init_elem`.

[Parser] Parse the remaining array operations

---

test/lit/basic/exception-handling.wast

We ported basic tests to `test/lit/basic/` in #6160, but comparing `CHECK` lines with the test code for long functions is not easy, even though it wouldn't necessarily be worse than the the separate files we used to have in `test/`. This slices `exception-handling.wast` into functions so that the `CHECK` lines are easy to check.

[EH][test] Slice test code into different functions

---

src/wasm-ir-builder.h
src/wasm/wasm-ir-builder.cpp
test/lit/passes/outlining.wast

In Binaryen IR, we allow single `Drop` expressions to drop multiple values
packaged up as a tuple. When using IRBuilder to rebuild IR containing such a
drop, it previously treated the drop as a normal WebAssembly drop that dropped
only a single value, producing invalid IR that had extra, undropped values. Fix
the problem by preserving the arity of `Drop` inputs in IRBuilder. To avoid
bloating the IR, thread the size of the desired value through IRBuilder's pop
implementation so that tuple values do not need to be split up and recombined.

Preserve multivalue drops in IRBuilder

---

src/parser/contexts.h
src/parser/parsers.h
src/wasm-ir-builder.h
src/wasm.h
src/wasm/wasm-ir-builder.cpp
test/lit/passes/outlining.wast
test/lit/wat-kitchen-sink.wast

Parse `tuple.make`, `tuple.extract`, and `tuple.drop`. Also slightly improve the
way we break up tuples into individual elements in IRBuilder by using a
`local.tee` instead of a block containing a `local.set` and `local.get`.

[Parser] Parse tuple operations

---

src/ir/branch-utils.h
src/ir/iteration.h
src/ir/memory-utils.cpp
src/ir/properties.h
src/ir/type-updating.cpp
src/passes/MemoryPacking.cpp
src/passes/RemoveUnusedModuleElements.cpp
src/tools/wasm-merge.cpp
src/tools/wasm-metadce.cpp
src/wasm-traversal.h
src/wasm/wasm-ir-builder.cpp

`_VECTOR` or `_ARRAY` defines in `wasm-delegations-fields.def` are supposed to be defined in terms of their non-vector/array counterparts when undefined. This removes empty `_VECTOR`/`_ARRAY` defines when including `wasm-delegations-fields.def`, while adding definitions for `DELEGATE_GET_FIELD` in case it is missing.

Remove empty _ARRAY/_VECTOR defines (NFC)

---

src/wasm/wasm-validator.cpp

Without this fuzzer testcases fail if the initial content has a `tuple.drop` but multivalue
is disabled (then the initial content validates erroneously, and that content is remixed
into more content using multivalue which fails to validate).

Add tuple.drop validation

---

src/wasm/wasm-validator.cpp
test/spec/exception-handling.wast

This adds validation for the new EH instructions (`try_table` and `throw_ref`):
https://github.com/WebAssembly/exception-handling/blob/main/proposals/exception-handling/Exceptions.md
This also adds a spec test for checking invalid modules. We cannot check the executions yet because we don't have the interpreter implementation. The new test file also contains tests for the existing `throw`, because this is meant to replace the old spec test someday.

[EH] Add validation for new instructions

---

test/lit/basic/exception-handling.wast

This adds tests that test all four kinds of `catch` clauses for an empty tag and a multivalue tag. (Previously we had this test only for an `i32` tag.)

[EH][test] Add a few more tests

---

src/parser/contexts.h
src/parser/parsers.h
src/parser/wat-parser.cpp
test/lit/wat-kitchen-sink.wast

We previously support the in-line import abbreviation, but now add support for
explicit, non-abbreviated imports as well.

[Parser] Support standalone import definitions

---

src/tools/wasm-reduce.cpp

Avoid replacing with the exact same thing in the case of RefNull and a default
tuple.
Also be more careful with handling of numbers. Before we exited immediately
if we saw a number, but we can try to replace a number with a 0 or a 1, even
if it was a number before. That is, we consider 1 simpler than 12345678, and
0 simpler than 1.

wasm-reduce: Improve tryToReduceCurrentToConst()

---

src/passes/Print.cpp
src/wasm-builder.h
src/wasm-traversal.h
test/lit/basic/exception-handling.wast

- Deletes a stray whitespace after `throw_ref`
- Adds missing `makeThrowRef` to `wasm-builder.h`
- Adds a case for `TryTable` in `ControlFlowWalker`

[EH] Misc. fixes for EH

---

src/parser/contexts.h
src/parser/parsers.h
test/lit/wat-kitchen-sink.wast

To parse folded instructions in the right order, we need to defer parsing each
instruction until we have parsed each of its children and found its closing
parenthesis. Previously we naively looked for parentheses to determine where
instructions began and ended before we parsed them, but that scheme did not
correctly handle instructions that can contain parentheses in their immediates,
such as call_indirect.
Fix the problem by using the actual instruction parser functions with a
placeholder context to find the end of the instructions, including any kind of
immediates they might have.

[Parser] Parse folded instructions that contain parentheses

---

src/wasm/wasm-s-parser.cpp
test/lit/arrays.wast
test/lit/passes/gufa-refs.wast
test/lit/passes/gufa-tnh.wast
test/lit/passes/optimize-instructions-gc.wast
test/passes/Oz_fuzz-exec_all-features.wast
test/spec/array.wast

These type annotations were removed during the development of the GC proposal,
but we maintained support for parsing them to ease the transition. Now that GC
is shipped, remove support for the non-standard annotation and update our tests
accordingly.

Drop support for type annotations on array.len

---

src/parser/contexts.h
src/parser/parsers.h
src/wasm-ir-builder.h
src/wasm/wasm-ir-builder.cpp
test/lit/wat-kitchen-sink.wast

And validate in IRBuilder both that the input annotation is valid and that the
input matches it.

[Parser] Parse br_on_cast{_fail} input annotations

---

src/parser/parsers.h
test/lit/wat-kitchen-sink.wast

The planned spec change to use "sub open" never came together, so the standard
format remains "sub final".

[Parser] Go back to "sub final" intead of "sub open"

---

src/literal.h
src/wasm-interpreter.h

(These will help with a future PR.)

[NFC] Add some const annotations

---

src/passes/CMakeLists.txt
src/passes/WasmIntrinsics.cpp.in

The intrinsics file changed in #6201 and somehow CMake doesn't automatically
update itself, and needs a manual step for people with existing checkouts (a new
fresh checkout always works). To avoid annoyance for existing checkouts, rename
the vars, which forces CMake to recompute the contents.

Rename CMake vars for modified intrinsics file

---

src/wasm/wasm-ir-builder.cpp
test/lit/wat-kitchen-sink.wast

Since branches to loops go to the beginnings of the loops, they should send
values matching the input types for the loops (which are always none because we
don't support loop input types). IRBuilder was previously using the output types
of loops to determine what values the branches should carry, which was
incorrect. Fix it.

Fix branches to loops in IRBuilder

---

src/passes/CMakeLists.txt
src/passes/WasmIntrinsics.cpp.in

I think this is a nicer/better way to do #6204.

Fix cmake dependency on wasm-intrinsics.wat

---

src/ir/possible-constant.h
src/ir/subtypes.h

[NFC] Add more const annotations + a trivial ==

---

test/example/c-api-kitchen-sink.c

See relevant discussion in #6215

Testing: Write out and read back in the big binary in c-api-kitchen-sink.c

---

src/parser/contexts.h
src/parser/parsers.h
test/lit/wat-kitchen-sink.wast

Parse types like `exnref` and `nofunc` that we did not previously support.

[Parser] Parse remaining heap and reference types

---

src/wasm-builder.h

- This passes `name` to `makeBlock` call, because `makeBlock` uses `BranchSeeker` when finalizing only when the block has a `name`.
- This also refinalizes the block when an optional `type` is given.
This was spun off from #6210, but I'm not sure how to add a standalone test for this.

Make blockifyWithName correctly use name and type

---

src/binaryen-c.cpp
src/binaryen-c.h
test/example/c-api-kitchen-sink.c
test/example/c-api-kitchen-sink.txt

Refer to issue #6214, this pull request is trying to allow Binaryen C API to append new local variables to the function (in cases that there does not exist such C API yet).

C API: Add BinaryenFunctionAppendVar

---

src/wasm/wasm-validator.cpp
test/lit/ctor-eval/flatten_too_big.wast

This should be a runtime error, not a validator error. It caused a fuzzer failure on
wasm-ctor-eval.

Remove incorrect validation of segment sizes

---

src/cfg/cfg-traversal.h

This renames `***Stack` variables in `CFGWalker` to be consistent, as a preparation for adding another stack for the new EH. Currently `ifStack` and `loopStack` contains `BasicBlock*`s but `tryStack` contains `Expression*`, and `Try` expressions are rather contained in `unwindExprStack`, which to me is confusing.

Rename stack variables in CFGWalker (NFC)

---

src/passes/MemoryPacking.cpp
test/lit/passes/memory-packing_all-features.wast

They might trap. Leave that for RemoveUnusedModuleElements.
Fixes #6230

MemoryPacking: Ignore empty segments

---

src/parser/contexts.h
src/parser/parsers.h
test/lit/wat-kitchen-sink.wast

Use the new `(tuple ...)` syntax. Enforce that tuples have a valid number of
elements and are not nested to avoid assertion failures when parsing invalid
input.

[Parser] Parse tuple types

---

src/wasm-ir-builder.h
src/wasm/wasm-ir-builder.cpp
test/lit/wat-kitchen-sink.wast

These instructions always pop a single value, except when tuples are involved,
in which case they need special handling to know how many values to pop.

[Parser] Parse local.set and global.set of tuple values correctly

---

src/passes/Print.cpp
src/wasm/wasm-s-parser.cpp
test/example/c-api-kitchen-sink.txt
test/lit/basic/exception-handling-old.wast
test/lit/passes/catch-pop-fixup-eh-old.wast
test/lit/passes/gufa-refs.wast
test/lit/passes/poppify.wast
test/lit/passes/translate-eh-old-to-new.wast
test/lit/wat-kitchen-sink.wast
test/spec/exception-handling-old.wast

Rather than `(pop valtype*)`, use `(pop valtype)`, where `valtype` is now
allowed to be a tuple. This will make it possible to parse un-folded multivalue
pops in the new text parser. The alternative would have been to put an arity in
the syntax like we have for other tuple instructions, but that's much uglier.

Update pop text syntax

---

src/parser/contexts.h
src/parser/parsers.h
src/wasm-ir-builder.h
src/wasm/wasm-ir-builder.cpp
test/lit/wat-kitchen-sink.wast

Parse pop expressions and check that they have the expected types, but do not
actually create new Pop expressions or push anything onto the stack because we
already create Pop expressions as necessary when visiting the beginning of catch
blocks.
Unlike the legacy text parser, the new text parser is not capable of parsing
pops in invalid locations in the IR. This means that the new text parser will
never be able to parse test/lit/catch-pop-fixup-eh-old.wast, which deliberately
parses invalid IR to check that the pops can be fixed up and moved to the
correct locations. It should be acceptable to delete that test when we turn on
the new parser by default, though, so that won't be a problem.

[Parser] Parse pops (by doing nothing)

---

src/ir/table-utils.h
test/lit/passes/directize_all-features.wast

Directize: Handle overflows and out of bounds

---

src/ir/type-updating.cpp

This was perhaps an optimization? This change is needed for an upcoming
PR that lowers away strings, as it will replace the `string` HeapType with
`extern`.

Allow updating basic HeapTypes in GlobalTypeRewriter::mapTypes

---

src/support/CMakeLists.txt
src/support/json.cpp
src/support/json.h
test/gtest/CMakeLists.txt
test/gtest/json.cpp

Our barebones JSON impl will be used more in a future PR. This adds some
simple functionality to it.
It will be tested in the upcoming PR, which I can combine this into if that
would be preferable?

JSON: Add simple printing and creation

---

src/parser/input-impl.h
src/parser/input.h
src/parser/lexer.cpp
src/parser/lexer.h
test/gtest/wat-lexer.cpp

Have a single implementation for lexing each of unsigned, signed, and
uninterpreted integers, each generic over the bit width of the integer. This
reduces duplication in the existing code and it will make it much easier to
support lexing more 8- and 16-bit integers.

[Parser] Templatize lexing of integers

---

src/tools/wasm-ctor-eval.cpp
test/lit/ctor-eval/string.wast

#6244 tried to do this but was not quite right. It treated a string like an array
or a struct, which means create a global for it. But just creating a global isn't
enough, as it needs to also be sorted in the right place etc. which requires
changes in other places. But there is a much simpler solution here: string
constants are just constants, which we can emit in-line, so do that.

wasm-ctor-eval: Properly eval strings

---

src/parser/lexer.cpp
src/parser/lexer.h
test/gtest/wat-lexer.cpp
test/lit/wat-kitchen-sink.wast

In addition to normal identifiers, support parsing identifiers of the format
`$"..."`. This format is not yet allowed by the standard, but it is a popular
proposed extension (see https://github.com/WebAssembly/spec/issues/617 and
https://github.com/WebAssembly/annotations/issues/21).
Binaryen has historically allowed a similar format and has supported arbitrary
non-standard identifier characters, so it's much easier to support this extended
syntax than to fix everything to use the restricted standard syntax.

[Parser] Support string-style identifiers

---

src/support/string.cpp
src/support/string.h

Now that we have a .cpp file, none of the code that was in string.h needs to be
in a header any more.

[NFC] Move code to string.cpp

---

src/parser/context-defs.cpp
src/parser/contexts.h
src/parser/wat-parser.cpp
src/wasm/wasm-ir-builder.cpp
test/lit/wat-kitchen-sink.wast

We previously had a bug where we would begin and end an IRBuilder context for
imported functions even though they don't have bodies. For functions that return
results, ending this empty scope should have produced an error except that we
had another bug where we only produced that error for multivalue functions. We
did not previously have imported multivalue functions in wat-kitchen-sink.wast,
so both of these bugs went undetected. Fix both bugs and update the test to
include an imported multivalue function so that it would have failed without
this fix.

[Parser] Do not involve IRBuilder for imported functions

---

src/passes/StringLowering.cpp
test/lit/passes/string-gathering.wast
test/lit/passes/string-lowering-instructions.wast

All those in the list from https://github.com/WebAssembly/binaryen/pull/6271#issuecomment-1928514138

StringLowering: Lower all remaining important string operations

---

src/wasm/wasm-s-parser.cpp
test/lit/strings.wast

Removing support for the legacy syntax will allow us to avoid implementing
support for it in the new text parser.

Remove support for legacy stringref text syntax

---

src/parser/contexts.h
src/parser/wat-parser.cpp
test/lit/wat-kitchen-sink.wast

Construct a mapping from heap type and field name to field index, then use it while parsing instructions.

[Parser] Support references to struct fields by name

---

scripts/fuzz_shell.js

With this, the fuzz shell can run a hello world Java file compiled by j2wasm.

Fuzz shell: Add a j2wasm import

---

fuzz/readme.txt
scripts/fuzz_opt.py

This removes the manual list inside the fuzzer with a simple directory that we
scan. The manual list was not well-maintained and nothing there really
mattered enough to keep. Instead, users can place files in `/test/fuzz/` that they
consider important.

Fuzzer: Use a directory for important fuzz testcases

---

src/ir/type-updating.cpp
src/ir/type-updating.h
src/passes/StringLowering.cpp
test/lit/passes/string-lowering-instructions.wast

We want to actually remove all stringref appearances, in both public and
private types.

StringLowering: Modify string=>extern also in public types

---

src/passes/StringLowering.cpp
test/lit/passes/string-lowering-instructions.wast

Replacing the string heap type with extern is dangerous as they do not share top/bottom
types. In practice this works out almost everywhere except for a few ifs, which we can fix
up as a hack for now.

StringLowering: Hack around if issue with bottom types

---

src/passes/StringLowering.cpp
test/lit/passes/string-lowering-instructions.wast

The input module might use an array of 16-bit elements type that is somewhere in a
giant rec group, but that is not valid for imported strings: that array type is now on an
import and must match the expected ABI, which is to be in its own personal rec group.
The old array16 type remains in the module after this transformation, but all uses of it
are replaced with uses of the new array16 type.
Also move makeImports to after updateTypes: there are no types to update in the new
imports. That does not matter but it can make debugging less pleasant, so improve it.

StringLowering: Use an array16 type in its own rec group

---

src/wasm-interpreter.h
src/wasm/wasm-type.cpp
test/lit/exec/strings.wast

This adds just enough support to be able to `--fuzz-exec` a small but realistic fuzz
testcase from Java.
To that end, just implement the minimal ops we need, which are all related to
JS-style strings. Full Strings support does not make sense to spend time on atm,
but this small PR unblocks fuzzing so it seems worth it.

Strings: Add some interpreter support

---

src/passes/StringLowering.cpp
test/lit/passes/string-lowering-instructions.wast

StringAs's output must be non-nullable, so add a cast.

StringLowering: Properly handle nullable inputs to StringAs

---

scripts/fuzz_opt.py
scripts/fuzz_shell.js

Fuzzing Asyncify has a significant cost both in terms of the complexity in
the fuzzer and the slowness of the fuzzing. In practice it was useful years ago
when Asyncify was written but hasn't found anything for a while, and Asyncify
is really deprecated given JSPI. For all those reasons, remove it from the fuzzer.
We do still have lots of normal coverage of asyncify in lit tests, unit tests, and
the Emscripten test suite.
Removing this will also make future improvements to the fuzzer simpler.

Fuzzer: Remove Asyncify integration

---

src/passes/SetGlobals.cpp

For now if global isn't found, the warning is issued and then the pass segfaults on "if (glob->type == Type::i32)" line because glob is null here (also it is an UB).
This patch replaces warning with Fatal(), preventing segfault and raising an error if global is not found.
I think that the fatal error when the specified global is not found is the preferred (and the current, via segfault) behavior for this pass because it is much safer to break the build than skip SetGlobals without actually setting the variable.

[SetGlobals] fix segfault

---

src/passes/StringLowering.cpp
src/support/json.cpp
src/support/string.cpp
src/support/string.h
test/lit/passes/string-lowering-instructions.wast
test/lit/passes/string-lowering.js
test/lit/passes/string-lowering.wast

Also add an end-to-end test using node to verify we can parse the escaped
content properly using TextDecoder+JSON.parse.

StringLowering: Escape the JSON in the custom section

---

src/ir/subtype-exprs.h

This pulls out the `subtype-exprs.h` parts of https://github.com/WebAssembly/binaryen/pull/6108
These are NFC in the current codebase, but are fixes for that unlanded PR. I suggest we
land those because they can help other unrelated work even if we never land that PR.

subtype-exprs.h additions [NFC]

---

src/wasm/wasm-validator.cpp
test/lit/validation/imports.wast

We validate functions in parallel, but function-parallel passes do not run on imports,
so we did not issue a validation error on an import using a disallowed type, for example.
All the changes in `visitFunction` are just to group all the parts using `body` to the
end, and putting them behind a check for `body`.
(diff without whitespace is smaller)
Found using #6310 #6312

Validate function imports

---

src/wasm-binary.h

We had a temporary value 0xff there, but now it is added: https://github.com/WebAssembly/exception-handling/pull/298

[EH] Add noexn's opcode

---

src/support/string.cpp
test/lit/passes/string-lowering.wast

Catch and report all kinds of WTF-8 encoding errors in the source strings,
including invalid leading bytes, invalid trailing bytes, unexpected ends of
strings, and invalid surrogate sequences. Insert replacement characters into the
output as necessary. Add a TODO about minimizing size by escaping only those
code points mandated to be escaped by the JSON spec. Generally improve
readability of the code.

Improve JSON string encoding

---

src/support/small_vector.h

Ref: https://github.com/WebAssembly/binaryen/issues/6311
Building on aarch64 currently fails with:
```
ninja: job failed: /usr/bin/c++  -I/root/binaryen/src -I/root/binaryen/third_party/llvm-project/include -I/root/binaryen -static -DBUILD_LLVM_DWARF -Wall -Werror -Wextra -Wno-unused-parameter -Wno-dangling-pointer -fno-omit-frame-pointer -fno-rtti -Wno-implicit-int-float-conversion -Wno-unknown-warning-option -Wswitch-Wimplicit-fallthrough -Wnon-virtual-dtor -fPIC -fdiagnostics-color=always -O3 -DNDEBUG -UNDEBUG -std=c++17 -MD -MT src/passes/CMakeFiles/passes.dir/Precompute.cpp.o -MF src/passes/CMakeFiles/passes.dir/Precompute.cpp.o.d -o src/passes/CMakeFiles/passes.dir/Precompute.cpp.o -c /root/binaryen/src/passes/Precompute.cpp
In file included from …
```

Fix build error on aarch64

---

src/wasm/wasm-validator.cpp
test/lit/validation/array-init-data.wast
test/lit/validation/array-new-data.wast

Those instructions refer to a data segment, which mean the DataCount section
must be emitted before them (so that, per the [spec](https://github.com/WebAssembly/bulk-memory-operations/blob/master/proposals/bulk-memory-operations/Overview.md#datacount-section), they can be validated by
looking only at previous sections), which implies bulk-memory is needed.
Indeed V8 errors without it, as found by the fuzzer.

Validator: ArrayNew|InitData require Bulk Memory

---

src/parser/lexer.h
src/parser/parsers.h

Replace the general `peek` method that returned a `Token` with specific peek
methods that look for (but do not consume) specific kinds of tokens. This change
is a prerequisite for simplifying the lexer implementation by removing `Token`
entirely.

[Parser][NFC] Remove `Token` from lexer interface

---

scripts/fuzz_opt.py
src/tools/execution-results.h
test/lit/exec/i31.wast

JS engines print i31ref as just a number, so we need a small regex to
standardize the representation (similar to what we do for funcrefs on
the code above).
On the C++ side, make it actually print the i31ref rather than treat it
like a generic reference (for whom we only print `"object"`). To do that
we must unwrap an externalized i31 as necessary, and add a case for
i31 in the printing logic.
Also move that printing logic to its own function, as it was starting to
get quite long.

Fuzzer: Match the logging of i31ref between JS and C++

---

scripts/fuzz_opt.py

See #5665 #5599, this is an existing issue and we have a workaround for it
using `--dce`, but it does not always work. I seem to be seeing this in higher
frequency since landing recent fuzzer improvements, so ignore it.
There is some risk of us missing real bugs here (that we validate and V8
does not), but this is a validation error which is not as serious as a difference
in behavior. And this is a long-standing issue that hasn't bitten us yet.

Fuzzer: Ignore V8 errors on uninitialized non-defaultable locals

---

src/wasm/wasm-ir-builder.cpp

A bit of clean-up, changes getBranchValue to use pop().

[Parser] Condense redundant pop values

---

scripts/fuzz_opt.py

Somehow I forgot that they can be negative... but the fuzzer did not.

Fuzzer: Handle negative i31s

---

src/wasm-interpreter.h
test/lit/exec/array.wast

Also rename the existing `droppedSegments` to `droppedDataSegments` for clarity.

Implement dropping of active Element Segments

---

CMakeLists.txt

Add a flag to enable pthreads.
Use `SINGLE_FILE` on `binaryen.js/.wasm` as before, which is nice for library users
as they want just a single file to distribute for Binaryen support. For other builds
like `wasm-opt.js` etc. no longer set `SINGLE_FILE`, as that type of build wants to be
a replacement for a normal `wasm-opt` build as much as possible, so avoid the
overhead of `SINGLE_FILE`.
(Previously we disabled `SINGLE_FILE` also in the case of `BUILD_FOR_BROWSER`
but I don't think we need to special-case that any more.)
This is a step towards adding a `wasm-opt.js` build in our releases: We need
pthreads there, and we don't want `SINGLE_FILE`.

[Emscripten port] Improve emcc flags

---

scripts/fuzz_shell.js

Before this we only printed the type of a BigInt and not the value.

Fuzzer: Improve BigInt printing

---

src/support/threads.cpp

Before this all Emscripten builds would use 1 core.

[Emscripten port] Fix core count logic for Emscripten+pthreads

---

scripts/gen-s-parser.py
src/gen-s-parser.inc
src/parser/contexts.h
src/parser/lexer.cpp
src/parser/lexer.h
src/parser/parsers.h
src/wasm-ir-builder.h
src/wasm/wasm-ir-builder.cpp
test/lit/wat-kitchen-sink.wast

Parse annotations using the standards-track `(@annotation ...)` format as well
as the `;;@ source-map:0:1` format. Have the lexer implicitly collect
annotations while it skips whitespace and add lexer APIs to access the
annotations since the last token was parsed. Collect annotations before parsing
each instruction and pass the annotations explicitly to the parser and parser
context functions for instructions. Add an API to `IRBuilder` to set a debug
location to be attached to the next visited or created instruction and use it
from the parser.

[Parser] Parse annotations, including source map comments

---

src/passes/StringLowering.cpp
test/lit/passes/string-gathering.wast
test/lit/passes/string-lowering-instructions.wast

Previously we lowered this to `getCodePointAt`, which has different semantics
around surrogate pairs.

[StringLowering] Lower `stringview_wtf16.get_codeunit` to `charCodeAt`

---

.github/workflows/create_release.yml
README.md
src/support/threads.cpp

Simply build `wasm-opt` with Emscripten and bundle that up.
Example build:
https://github.com/kripken/binaryen/releases/tag/wasm-build-1
Specifically
[binaryen-wasm-build-1-wasm.tar.gz](https://github.com/kripken/binaryen/releases/download/wasm-build-1/binaryen-wasm-build-1-wasm.tar.gz.sha256)
Only 1.72 MB, as it's just `wasm-opt` and not any other tool, so it is
much smaller than our other targets. Perhaps we will add more of the
tools later as needed (`wasm-metadce`, `wasm-split`, etc.).
Also update the readme regarding which toolchains use us as a library, that I
noticed while editing it to add the release platforms.

Add a WebAssembly build to release

---

src/support/threads.cpp

This ensures in a better way that we don't have unneeded code.

[NFC] Use ifdef-else in threads.cpp

---

CHANGELOG.md

Also, any thoughts on the timing of a release? I was thinking of doing one before the
end of the week.

Update changlog before release [NFC]

---

src/ir/subtype-exprs.h
src/passes/StringLowering.cpp
src/passes/Unsubtyping.cpp
test/lit/passes/unsubtyping-casts.wast

When we do a `local.set` of a value into a local then we have both a subtyping constraint - for
the value to be valid to put in that local - and also a flow of a value, which can then reach
more places. Such flow then interacts with casts in Unsubtyping, since it needs to know
what can flow where in order to know how casts force us to keep subtyping relations.
That regressed in the not-actually-NFC #6323 in which I added the innocuous lines
to add subtyping constraints in `ref.eq`. It seems fine to require that the arms of a
RefEq must be of type eqref, but Unsubtyping then assuming those arms flowed into
a location of type eqref... which means casts might force us to not optimize some
things.
To fix this, differentiate the rare case of non-flowing subtyping constraints, which is …

SubtypingDiscoverer: Differentiate non-flow subtyping constraints

---

scripts/fuzz_opt.py
scripts/fuzz_shell.js

Before `FUZZ_OPTS` was used both when doing `--translate-to-fuzz/-ttf` to generate the
wasm from the random bytes and also when later running optimizations to generate
a second wasm file for comparison. That is, we ended up doing this, if the opts were `-O3`:
```
wasm-opt random.input -ttf -o a.wasm -O3
wasm-opt a.wasm -O3 -o b.wasm
```
Now we have a pair `a.wasm,b.wasm` which we can test. However, we have run `-O3`
on both which is a little silly - the second `-O3` might not actually have anything left
to do, which would mean we compare the same wasm to itself.
Worse, this is incorrect, as there are things we need to do *only* during the
generation phase, like `--denan`. We need that in order to generate a valid wasm to
test on, but it is "destructive" in itself: when removing NaNs (to …

Fuzzer: Separate arguments used to make the fuzz wasm from the opts we run on it

---

src/passes/Outlining.cpp
src/wasm-ir-builder.h
src/wasm/wasm-ir-builder.cpp
test/lit/passes/outlining.wast

Adds new visitBreakWithType and visitSwitchWithType functions to the IRBuilder API. These functions work around an assumption in IRBuilder that the module is being traversed in the fully nested format, i.e., that the destination scope of a break or switch has been visited before visiting the break or switch. Instead, the type of the destination scope is passed to IRBuilder.

[Outlining] Fixes break reconstruction

---

src/ir/subtype-exprs.h
src/passes/Unsubtyping.cpp

I audited all of SubtypingDiscoverer for flow/non-flow constraints and added
some comments to clarify things for our future selves if we ever need to
generalize it.

[NFC] Add some comments about flow in SubtypingDiscoverer and Unsubtyping

---

src/binaryen-c.cpp
src/binaryen-c.h
test/example/c-api-kitchen-sink.c
test/example/c-api-kitchen-sink.txt

C API: Support adding data segment individually

---

scripts/fuzz_opt.py

This new backend in V8 can now be used for wasm, so we should fuzz it.

Fuzz V8 Turboshaft

---

scripts/test/shared.py

Those flags were removed in V8 as the features are no longer experimental. This
PR removes this noise from our logs:
```
Warning: unknown flag --experimental-wasm-gc.                                                                                                                                                 
Try --help for options                                                                                                                                                                        
Warning: unknown flag --experimental-wasm-typed-funcref.                                                                                                                                      
Try --help for options                                                                         
Warning: …
```

Tests/Fuzzing: Remove some obsolete experimental V8 flags

---

src/passes/Print.cpp
test/lit/passes/cfp.wast
test/lit/passes/dae-gc-refine-return.wast
test/lit/passes/dae_all-features.wast
test/lit/passes/gsi.wast
test/lit/passes/gto-removals.wast
test/lit/passes/gufa-extern.wast
test/lit/passes/gufa-refs.wast
test/lit/passes/gufa-tnh-closed.wast
test/lit/passes/gufa-vs-cfp.wast
test/lit/passes/heap2local.wast
test/lit/passes/inlining-optimizing.wast
test/lit/passes/inlining_vacuum_optimize-instructions.wast
test/lit/passes/local-subtyping.wast
test/lit/passes/optimize-instructions-call_ref.wast
test/lit/passes/optimize-instructions-gc-heap.wast
test/lit/passes/optimize-instructions-gc-iit.wast
test/lit/passes/optimize-instructions-gc-tnh.wast
test/lit/passes/optimize-instructions-gc.wast
test/lit/passes/precompute-gc-immutable.wast
test/lit/passes/precompute-gc.wast
test/lit/passes/remove-unused-brs-gc.wast
test/lit/passes/remove-unused-module-elements-refs.wast
test/lit/passes/signature-pruning.wast
test/lit/passes/signature-refining.wast
test/lit/passes/simplify-locals-gc.wast
test/lit/passes/type-generalizing.wast
test/lit/passes/type-refining.wast
test/lit/passes/type-ssa.wast
test/lit/passes/unsubtyping.wast

In some cases we don't print an Expression in full if it is unreachable, so
we print something instead as a placeholder. This happens in unreachable
code when the children don't provide enough info to print the parent (e.g.
a StructGet with an unreachable reference doesn't know what struct type
to use).
This PR prints out the name of the Expression type of such things, which
can help debugging sometimes. See updated test text for examples.

[NFC] Add the type of the Expression when eliding it

---

src/passes/RoundTrip.cpp

It doesn't literally add them, but roundtripping a file can rename functions
which means our internal map of function name to effects can get out of
date, which has the effect of "adding" effects to passes when they get the
wrong ones.
This pass is just a fuzzer helper, so this hack seems good enough.

Fuzzer: Mark Roundtrip pass as adding effects

---

src/passes/OptimizeAddedConstants.cpp

OptimizeAddedConstants: Replace an assert with a proper error

---

CHANGELOG.md
src/parser/context-decls.cpp
src/parser/contexts.h
src/parser/parsers.h
src/parser/wat-parser.cpp
src/wasm/wasm-ir-builder.cpp
test/lit/source-map.wast

and fix a bug with sourcemap annotations on folded `if` conditions. Update
IRBuilder to apply prologue and epilogue source locations when beginning and ending
a function scope. Add basic support in the parser for explicitly tracking
annotations on module fields, although only do anything with them in the case of
prologue source location annotations.

[Parser] Support prologue and epilogue sourcemap annotations

---

scripts/fuzz_opt.py

When the stack runs out is observable and optimizations can change it, so
we must ignore such testcases.
Also add some logic to help debug stuff like this, as suggested by @tlively 
in the past, to add some metrics on the reasons we ignored a testcase. That
emits something like this:
```
(ignored 2 iters, for reasons {'too many errors vs calls': 2})
```
As a drive by make the metrics print wasm bytes/iter rather than by second
(the former is easy to compute from the latter anyhow, and the latter is more
interesting I think).

Fuzzer: Ignore fuzz testcases that make VMs run out of stack

---

src/parser/wat-parser.cpp
test/lit/wat-kitchen-sink.wast

Add a pass that propagates debug locations to unannotated child and sibling
expressions after parsing. The new parser on its own only attaches debug
locations to directly annotated instructions, but this pass, which we run
unconditionally, emulates the behavior of the previous parser for compatibility
with existing programs. It does unintuitive things to programs using the
non-nested format because it runs on nested Binaryen IR, so we may want to
rethink this at some point.

[Parser] Propagate debug locations like the old parser

---

scripts/fuzz_opt.py
scripts/fuzz_shell.js

We had `exception:` in one and `exception thrown:` in another. Making those
consistent allows `fuzz_shell.js` to print the exception after that prefix, which
makes debugging easier sometimes.
Also canonicalize tag names. Like funcref names, JS VMs print out the internal
name, which can change after opts, so canonicalize it.

Fuzzer: Standardize notation for exception prefixes

---

src/wasm/wasm-ir-builder.cpp
test/lit/wat-kitchen-sink.wast

Rather than reassembling a tuple from multiple pops, let the pop implementation
assemble the tuple. This produces less code in cases where there is already a
tuple of the proper size on top of the stack. It also simplifies the code.

[Parser] Improve parsed IR for multivalue returns

---

check.py
scripts/test/shared.py

As part of our running of spec tests, we split out each module in a test script
into a separate text file for processing with wasm-opt. We previously included
the test assertions corresponding to the module into that text file, where they
were ignored by the legacy text parser. The new parser errors out due to the
extra tokens after the module, though, so to avoid problems once we switch to
the new parser, stop including the assertions in those text files.
Also remove a nearby unused argument as a drive-by cleanup.

Do not write assertions to split.wast for spec tests

---

CHANGELOG.md
src/binaryen-c.cpp
src/binaryen-c.h
test/example/c-api-kitchen-sink.c

I am currently in need of setting features from the C API, so I figured I’d take a stab at fixing the TODO.
Not sure if this is the way you’d wanna go about it, though. Happy to adjust!

Expose features option in C API

---

src/passes/Print.cpp
test/lit/passes/gufa-refs.wast
test/lit/passes/type-generalizing.wast
test/lit/passes/unsubtyping.wast

When the bulk array ops had unreachable or null array types, they were replaced
with blocks, but not using the correct code that also prints all their children
as dropped followed by an unreachable. This meant that the text output in those
cases did not parse as a valid module.
Fix the bug. A follow-up PR will simplify the code to prevent similar bugs from
occurring in the future.

Fix printing of bulk array ops

---

src/passes/Print.cpp

When instructions cannot be printed because the children from which they are
supposed to get their type immediates are unreachable or null, we print blocks
of their dropped children followed by unreachables. But the logic for making
this happen was more complicated than necessary and in fact included dead code.
Clean it up.

[NFC] Clean up the unreachable replacement code in Print.cpp

---

src/wasm/wasm.cpp

Previously selects finalized with explicit types would never be marked
unreachable, even when they should have been.

Check for unreachable in `Select::finalize(Type)`

---

scripts/fuzz_opt.py

This is fallout from #6310 where we moved to use `fuzz_shell.js` for all fuzzing
purposes. That script doesn't know wasm types, all it has on the JS side is the
number of arguments to a function, and it passes in `null` for them all
regardless of their type. That normally works fine - `null` is cast to the right
type upon use - but in wasm2js optimized builds we can remove casts,
which can make that noticeable. Luckily the fixup is very simple.

Fuzzer: Fix up null outputs in wasm2js optimized builds

---

CMakeLists.txt

Emscripten had started complaining about the repeated NODERAWFS arguments in the
link command, but they would be nontrivial to deduplicate.

Fix Emscripten build with -Wno-unused-command-line-argument

---

src/tools/fuzzing/fuzzing.cpp

Add `[[maybe_unused]]` to variables that are only used in assertions. In builds
without assertions enabled, these were causing compiler errors about unused
variables.

Fix a build error when assertions are disabled

---

src/passes/DeadCodeElimination.cpp
test/lit/passes/dce-eh-old.wast

This is a very long-standing issue I believe, though very unlikely. It was
found now thanks to some new testcases in recent PRs that were used
as initial content.

DCE: Fix old EH on a pop that gets moved in a catch body

---

src/ir/localize.h
src/passes/GlobalTypeOptimization.cpp
test/lit/passes/gto-removals.wast

This is NFC in the current users, but is necessary functionality for a later
PR.
ChildLocalizer moves children into locals as needed. It used to stop when it
saw the first unreachable. After this change we move such unreachable
children out of the parent as well, making this more uniform: all interacting
effects are moved out, and all that is left nested in the parent can be
moved around and removed as desired.
Also add a `getReplacement` helper that makes using this easier.
This cannot be tested comprehensively with the current user as that user
will not call this code path on an unreachable parent at all, so this just
adds what can be tested. The later PR will have tests for all corner cases
:crossed_fingers:

[NFC] Refactor ChildLocalizer to handle unreachable code better

---

src/wasm-interpreter.h
test/lit/exec/strings.wast

This is necessary to execute fuzz testcases from Java.

[Strings] Implement string.encode_wtf16_array

---

src/support/small_vector.h

Similar issue as: https://github.com/WebAssembly/binaryen/pull/6330
```
FAILED: src/passes/CMakeFiles/passes.dir/Precompute.cpp.o 
/usr/bin/c++  -I/build/binaryen/src/binaryen-version_117/src -I/build/binaryen/src/binaryen-version_117/third_party/llvm-project/include -I/build/binaryen/src/binaryen-version_117/build -march=rv64gc -mabi=lp64d -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/binaryen/src=/usr/src/debug/binaryen -DBUILD_LLVM_DWARF -Wall -Werror -Wextra -Wno-unused-parameter -Wno-dangling-pointer -fno-omit-frame-pointer -fno-rtti -Wno-implicit-int-float-conversion -Wno-unknown-warning-option -Wswitch -Wimplicit-fallthrough -Wnon-virtual-dtor …
```

Fix build error on riscv64

---

src/passes/Precompute.cpp
test/lit/passes/precompute-gc.wast
test/lit/passes/precompute-strings.wast

Our UTF implementation is still not fully stable it seems as we have reports of
issues. Disable it for now.

Strings: Disable precomputing for now

---

src/passes/Precompute.cpp
test/lit/passes/precompute-gc.wast
test/lit/passes/precompute-strings.wast

Reverts WebAssembly/binaryen#6412
On second thought we found a way to make fixing this less urgent, and the
code size downsides of this are worrying, so let's revert it.

Revert "Strings: Disable precomputing for now"

---

src/wasm-interpreter.h
test/lit/exec/strings.wast

The [spec](https://github.com/WebAssembly/stringref/blob/main/proposals/stringref/Overview.md#stringview_wtf16) says
```
If pos is greater than the number of WTF-16 code units in view, it is as if it were instead given as the code unit length. This transformation is the "WTF-16 position treatment".
(stringview_wtf16.slice view:stringview_wtf16 start:i32 end:i32)
-> str:stringref
Return a substring of view, for the WTF-16 code units starting at offset start and continuing to but not including end. start and end receive the "WTF-16 position treatment", as for stringview_wtf16.encode.
```
My understanding is that that means if the end is larger than the size, it is shrunk to the size. That is,
```
end = min(end, actual size)
```
That appears to match what V8 does, thereby fixing a fuzz bug, …

[Strings] Fix StringSlice end computation

---

src/wasm/wasm-stack.cpp

See https://github.com/WebAssembly/stringref/issues/66

[Strings] Emit unreachable when a string instruction cannot be emitted properly

---

src/wasm/wasm-type.cpp
test/lit/validation/open-types-no-gc.wast

This omission was able to cause a problem with text round-tripping.

Mark non-closed types as requiring GC

---

src/passes/CodeFolding.cpp
test/lit/passes/code-folding-eh-old.wast

Context: The pass does (among other things) this:
```wat
(if
condition
X
X
)
=>
(block
(drop
condition
)
X ;; deduplicated
)
```
After that the condition is now nested in a block, so we may need EH fixups
if it contains a pop.

CodeFolding: Fix up old EH when we fold away an If

---

scripts/fuzz_opt.py

The test file was renamed, but the fuzzer still used the old name in
INITIAL_CONTENTS_IGNORE.

Update file name in INITIAL_CONTENTS_IGNORE

---

test/lit/passes/precompute-strings.wast

`string.encode_wtf16_array` operates on stringref, not on wtf16 string views, so
this conversion was causing validation errors when passed to V8 by the fuzzer.

Remove extra conversion in string test

---

CHANGELOG.md
scripts/fuzz_opt.py
src/binaryen-c.cpp
src/literal.h
src/parser/contexts.h
src/parser/lexer.cpp
src/passes/Print.cpp
src/passes/StringLowering.cpp
src/support/json.cpp
src/support/string.cpp
src/support/string.h
src/tools/fuzzing/fuzzing.cpp
src/wasm-builder.h
src/wasm-interpreter.h
src/wasm/literal.cpp
src/wasm/wasm-binary.cpp
src/wasm/wasm-s-parser.cpp
test/lit/passes/precompute-strings.wast
test/lit/passes/string-lowering.wast
test/lit/strings.wast

WTF-16, i.e. arbitrary sequences of 16-bit values, is the encoding of Java and
JavaScript strings, and using the same encoding makes the interpretation of
string operations trivial, even when accounting for non-ascii characters.
Specifically, use little-endian WTF-16.
Re-encode string constants from WTF-8 to WTF-16 in the parsers, then back to
WTF-8 in the writers. Update the constructor for string `Literal`s to interpret
the string as WTF-16 and store a sequence of WTF-16 code units, i.e. 16-bit
integers. Update `Builder::makeConstantExpression` accordingly to convert from
the new `Literal` string representation back to a WTF-16 string.
Update the interpreter to remove the logic for detecting non-ascii characters
and bailing out. The naive implementations of all the string operations are …

[Strings] Represent string values as WTF-16 internally

---

src/tools/fuzzing/fuzzing.cpp

Instead of generating exclusively ascii strings, generate empty strings and
strings containing various unicode characters and unpaired surrogates as well.

Generate interesting strings in fuzzer

---

src/wasm-interpreter.h
test/lit/exec/strings.wast

StringNew: Trap on OOB start index

---

scripts/fuzz_shell.js
src/wasm/literal.cpp
test/lit/exec/strings.wast

Previously we printed strings as WTF-8 in the output of fuzz-exec, but this
could produce invalid unicode output and did not make unprintable characters
visible. Fix both these problems by escaping the output, using the JSON string
escape procedure since the string to be escaped is WTF-16. Reimplement the same
escaping procedure in fuzz_shell.js so that the way we print strings when
running on a real JS engine matches the way we print them in our own fuzz-exec
interpreter.
Fixes #6435.

[Strings] Escape strings printed by fuzz-exec

---

src/ir/localize.h
src/tools/fuzzing/fuzzing.cpp
test/passes/fuzz_metrics_noprint.bin.txt
test/passes/translate-to-fuzz_all-features_metrics_noprint.txt

Before this PR we only mutated by replacing an expression with another, which
replaced all the children. With this PR we also do these two patterns:
```
(A
(B)
(C)
)
=> ;; keep children, replace A
(block
(drop (B))
(drop (C))
(NEW)
)
,
(D
(A
(B)
(C)
)
)
=> ;; keep A, replace it in the parent
(D
(block
(drop
(A
(B)
(C)
)
)
(NEW)
)
)
```
Even better would be to reuse the children by the new (`(NEW)`) expression,
but that would take significantly more work.

Add "interposition" to the fuzzer's mutate() method

---

src/wasm/wasm-s-parser.cpp
test/lit/basic/table-import.wast

The types was ignored and `funcref` was always used instead.

Fix parsing of table imports

---

CHANGELOG.md
src/binaryen-c.cpp
src/binaryen-c.h
src/js/binaryen.js-post.js
src/wasm-interpreter.h
test/binaryen.js/expressionrunner.js
test/binaryen.js/expressionrunner.js.txt

The implementation of calls with this option was incorrect because it cleared
the locals before evaluating the call arguments. The likely explanation for why
this was never noticed is that there are no users of this option, especially
since it is exposed in the C and JS APIs but not used internally.
Rather than try to fix the implementation, just remove the option.

Remove the TRAVERSE_CALLS option in the ConstantExpressionRunner

---

src/wasm-interpreter.h
test/lit/exec/atomic.wast

To avoid slow-running fuzz cases, we report a host limit when interpreting
atomic.wait with any non-zero timeout. However, in the allowed case where the
timeout is zero, we were incorrectly interpreting the wait as returning 0,
meaning that it was woken up, instead of 2, meaning that the timeout expired.
Fix it to return 2.

Report timeout in interpretation of AtomicWait

---

src/ir/possible-contents.cpp

Found by the fuzzer. We already processed the work queue in a deterministic
order, but the roots were unordered. The work queue's initial state is filled by
the roots, so we must process the roots deterministically as well.

GUFA: Fix nondeterminism in roots

---

src/ir/possible-contents.cpp
src/ir/possible-contents.h

See lines 69-70 in that header: For a global we store the name and a type,
and the type may be more precise than the global's type in the wasm. As
a result, when hashing, it is not enough to hash only the name, so hash
the type as well.
Not sure if this caused any significant issues due to more hash collisions,
but I noticed it while reading the code.
Also add a random TODO as a comment.

GUFA: Fix hashing of GlobalInfo's type

---

src/wasm-interpreter.h
test/lit/exec/strings.wast

That is, this should trap, but we did not:
```wat
(string.new_wtf16_array
(array.new_default $array16
(i32.const 1)
)
(i32.const 1)
(i32.const 0) ;; end is less than the start
)
```

[Strings] string.new_wtf16_array should trap if the end index is less than the start

---

src/ir/ExpressionAnalyzer.cpp
src/ir/branch-utils.h
src/wasm-delegations-fields.def

This removes the hard-coded generation of a switch and cases, and allows the user
to define the boilerplate at the start and end of the main output, and of what is
generated for each expression. By default we still emit a switch and cases.
Also standardize the output by never emitting `;` unnecessarily, which we were
inconsistent about.
This serves two goals: First, it will make using embind on Binaryen simpler as
embind needs to generate C++ template logic for each expression, and not a
switch (and we cannot have extra `;` in embind notation). Second, this makes
the format much simple to parse, which is a stepping stone for #6460, e.g.
before we had
```cpp
case Expression::Id::LoopId: {
DELEGATE_START(Loop);
DELEGATE_FIELD_CHILD(Loop, body);
DELEGATE_FIELD_SCOPE_NAME_DEF(Loop, name); …
```

[NFC] Generalize and simplify wasm-delegations-fields.h

---

test/lit/passes/global-effects.wast

Since there was no difference between the WITHOUT and DISCARD check prefixes, we
can just use WITHOUT for both and reduce the number of check lines by a third.

[NFC] Reduce verbosity of test/lit/passes/global-effects.wast

---

src/ir/branch-utils.h

These were causing build failures on the Emscripten builder.

[NFC] Remove unused variables

---

src/ir/branch-utils.h
src/ir/parents.h
src/passes/Heap2Local.cpp
test/lit/passes/heap2local.wast

Separate the escape analysis portion from the part that does the optimization.
We do still record information during the analysis phase, but at least this makes
the separation clearer, and will also allow analysis without necessarily optimizing.

[NFC] Refactor Heap2Local logic

---

src/ir/effects.h
src/pass.h
test/lit/passes/global-effects.wast
test/lit/passes/simplify-locals-eh-old.wast
test/lit/passes/vacuum-eh-old.wast

As far as their surrounding code is concerned return calls are no different from
normal returns. It's only from a caller's perspective that a function containing
a return call also has the effects of the return-callee. To model this more
precisely in EffectAnalyzer, stash the effects of return-callees on the side and
only merge them in at the end when analyzing the effects of a full function
body.

Update effects.h to handle return calls correctly

---

src/passes/CodeFolding.cpp
test/lit/passes/code-folding-eh-old.wast

Treat them the same as returns and test that they can be folded out of try-catch
blocks because they do not have throws effects.

Handle return calls in CodeFolding

---

scripts/fuzz_opt.py

The VM limitation might be an OOM (which can change due to opts) or an
atomic wait (which can hang on proper VMs with support). We already
avoided running VMs on the optimized wasm in this case, but we still
ran them on the original wasm, which this changes, mainly to avoid that
atomic wait situation.

Fuzzer: Do not run other VMs if the Binaryen interpreter hits a VM limitation

---

test/lit/merge/types.wat

The new parser, not yet enabled, requires that imports precede declared module
items except for types.

Fix import order in test/lit/merge/types.wat

---

src/passes/Print.cpp
test/lit/passes/optimize-instructions-multivalue.wast
test/lit/passes/tuple-optimization.wast

We previously printed the size of the tuple operand as the arity, but that
printed `1` when the operand is unreachable. We don't allow our text input to
use `1` as the arity, so don't print it, either. Instead, print the smallest
valid arity, `2`, in this case.

Ensure printed tuple.extract arity is valid

---

src/wasm/wasm-ir-builder.cpp
test/lit/wat-kitchen-sink.wast

When we need to pop a tuple and the top value on the stack is unreachable, just
pop the unreachable rather than producing a tuple.make. This always produces
valid IR since an unreachable is always valid where a tuple would otherwise be
expected. It also avoids bloating the parsed IR, since we would previously parse
a `tuple.make` where all the children were unreachable in this case.

[Parser] Use unreachables to fulfill tuple requirements

---

src/ir/bits.h
src/passes/ConstantFieldPropagation.cpp
src/passes/Heap2Local.cpp
test/lit/passes/cfp.wast
test/lit/passes/heap2local.wast

CFP already had logic for truncating but not for sign-extending, which this
fixes.
Use the new helper function in Heap2Local as well. This changes the model
there from "truncate on set, sign-extend on get" to "truncate or sign-extend
on get". That is both simpler by reusing the same logic as CFP but also more
optimal: the idea to truncate on sets made sense since sets are rarer, but if
we must then sign-extend on gets then we can end up doing more work
overall (as the truncations on sets are not needed if all gets are signed).
Found by #6486

Fix ConstantFieldPropagation signed packed field handling and improve Heap2Local's

---

src/ir/possible-contents.cpp
src/ir/possible-contents.h
test/lit/passes/gufa-refs.wast

GUFA already truncated packed fields on write, which is enough for unsigned gets,
but for signed gets we also need to sign them on reads.
Similar to https://github.com/WebAssembly/binaryen/pull/6493 but for GUFA. Also found by https://github.com/WebAssembly/binaryen/pull/6486

GUFA: Fix signed reads of packed GC data

---

src/tools/fuzzing.h
src/tools/fuzzing/fuzzing.cpp
test/passes/translate-to-fuzz_all-features_metrics_noprint.txt

This would have found the bug in #6480 fairly easily (confirmed as finding it
within a few minutes).

Fuzzer: Emit signed Struct/ArrayGet operations

---

src/ir/properties.cpp
src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-mvp.wast

"Generative" is what we call something like a `struct.new` that may be syntactically
identical to another `struct.new`, but each time a new value is generated. The same
is true for calls, which can do anything, including return a different value for
syntactically identical calls.
This was not a bug because the main user of `isGenerative`,
`areConsecutiveInputsEqual()`, was too weak to notice, that is, it gave up sooner,
for other reasons. This PR improves that function to do a much better check,
which makes the fix necessary to prevent regressions.
This is not terribly important for itself, but will help a later PR that will add code
that depends more heavily on `areConsecutiveInputsEqual()`.

Fix isGenerative on calls and test via improving OptimizeInstructions::areConsecutiveInputsEqual()

---

src/passes/GenerateDynCalls.cpp
src/passes/LegalizeJSInterface.cpp

This is temporary workaround for the current test failures on the emscripten waterfall.  The real fix I believe will be to make `hasExplicitName` the default in these kinds of cases.
See: #6466

When creating `dynCall` and `legalstub` function mark them as hasExplicitName. NFC

---

src/tools/fuzzing/fuzzing.cpp
test/passes/translate-to-fuzz_all-features_metrics_noprint.txt

Previously we chose the first with a proper type, and now we start to scan from
a random index, giving later functions a chance too, so we should be emitting a
greater variety of `ref.func` targets.
Also remove some obsolete fuzzer TODOs.

Fuzzer: Randomly pick which functions to use in RefFunc

---

src/passes/CoalesceLocals.cpp
test/lit/passes/coalesce-locals-eh-old.wast
test/lit/passes/coalesce-locals-gc.wast

The code had a different workaround, namely to add a block with an explicit
type to avoid changing the type at all (i.e. the block declared the original
type of the thing we replaced, not the refined type). But by adding a block we
can end up with an invalid pop, as the fuzzer found, see the EH testcase here.
To fix this, use the usual workaround of just running ReFinalize. That is simpler
and also improves the code while we do it. It does add more work, but this is
likely a very rare situation anyhow.

CoalesceLocals: ReFinalize when we refine a type

---

src/ir/child-typer.h
src/wasm-ir-builder.h
src/wasm/wasm-ir-builder.cpp
src/wasm/wasm-type.cpp
test/lit/wat-kitchen-sink.wast

We previously would eagerly drop all concretely typed expressions on the stack
when pushing an unreachable instruction. This was semantically correct and
closely modeled the semantics of unreachable instructions, which implicitly drop
the entire stack and start a new polymorphic stack. However, it also meant that
the structure of the parsed IR did not match the structure of the folded input,
which meant that tests involving unreachable children would not parse as
intended, preventing the test from testing the intended behavior.
For example, this wat:
```wasm
(i32.add
(i32.const 0)
(unreachable)
)
```
Would previously parse into this IR:
```wasm
(drop
(i32.const 0)
)
(i32.add
(unreachable)
(unreachable)
)
```
To fix this problem, we need to stop eagerly dropping stack values when …

[Parser] Pop past unreachables where possible

---

src/ir/names.h
src/wasm-ir-builder.h
src/wasm/wasm-ir-builder.cpp
test/lit/wat-kitchen-sink.wast

To reduce the size of the test output diff when switching to the new text
parser, update it to generate the same block names as the legacy parser.

[Parser] Match legacy parser block naming

---

src/wasm-ir-builder.h
src/wasm/wasm-ir-builder.cpp
test/lit/wat-kitchen-sink.wast

In the standard text format, try scopes can be targeted by both normal branches
and delegates, but in Binaryen IR we only allow them to be targeted by
delegates, so we have to translate branches to try scopes into branches to
wrapper blocks instead. These wrapper blocks must have different names than the
try expressions they wrap, so we actually need to track two label names for try
expressions: one for delegates and another for normal branches.
We previously tried to avoid this complexity by tracking only the branch label
and computing the delegate label from the branch label as necessary, but that
produced unnecessary wrapper blocks and ugly label names that did not appear in
the source.
To produce better IR and minimize the diff when switching to the new text
parser, bit the bullet and …

[Parser] Preserve try labels

---

src/tools/wasm-shell.cpp
test/lit/help/wasm-shell.test

None of our tests exercised the --entry or --skip options in wasm-shell, and
since wasm-shell is probably not used for anything outside our testing, there's
no reason to keep them. Remove them.

Remove unused options from wasm-shell

---

src/passes/OptimizeCasts.cpp
test/lit/passes/optimize-casts.wast

Converts the following:
```wasm
(some.operation
(ref.cast .. (local.tee $ref ..))
(local.get $ref)
)
```
into:
```wasm
(some.operation
(local.tee $temp
(ref.cast .. (local.tee $ref ..))
)
(local.get $temp)
)
```
This removes close to 10% of the casts in a test program (from 38113 casts down to 36119).
I also tried to improve the optimization that moves more refined casts earlier, but this does not seem very effective (it only eliminated 9 further casts), so I'm not sure it is worth it.

Cast optimization improvement: also handle local.tee

---

src/wasm/wasm.cpp
test/lit/passes/dce_all-features.wast

We added two fields to StringNew at some point but forgot to update the finalize method.

[Strings] Fix finalize() of StringNew on arrays

---

src/parser/parsers.h

Creating an error in the parser is an extremely expensive operation for very
large files because it has to traverse the input buffer and count newlines to
compute the error message. Despite that, there are a few places were we create
errors just to discard them and continue parsing. The most notable of these
places was where we parsed the list of label index immediates for the br_table
instruction. The parser determined the end of the list by intercepting the error
produced when trying to parse one more label index.
Fix this significant performance problem causing parsing to be quadratic by
introducing and using `maybeLabelidx`, which tries to parse a label index but
does not produce an error if it fails.

[Parser][NFC] Solve performance issue by adding maybeLabelidx

---

src/parser/lexer.cpp

The parsing of idchars was hot enough to show up while profiling the parsing of
a very large module. Optimize it to speed up the overall parse by about 16% in a
very unscientific measurement.

[Parser][NFC] Improve performance of idchar lexing

---

src/parser/contexts.h
src/parser/parsers.h

After the initial parsing pass to find the locations of all the module elements
and after the type definitions have been parsed, the next phase of parsing is to
visit all of the module elements and parse their types. This phase does not
require parsing function bodies, but it previously parsed entire functions
anyway for simplicity. To improve performance, skip that useless work.

[Parser][NFC] Do less work when parsing function types

---

src/passes/TranslateEH.cpp
test/lit/passes/translate-to-new-eh.wast

hen the function return type is concrete, the translation result of a `try`-`delegate` that targets the caller includes a `return` that returns the whole function body:
https://github.com/WebAssembly/binaryen/blob/219e668e87b012c0634043ed702534b8be31231f/src/passes/TranslateEH.cpp#L751-L763
We should do that based on the function's return type, not the function body's return type. The previous code didn't handle the case where the function's return type is concrete but the function body's return type is unreachable.

[EH] Fix delegating to caller when func result is concrete

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-gc-heap.wast

Before we preferred not to add default values, as that increases code size. But since
#6495 we turn more things into `struct.new_with default`, so it is important to handle
this. It seems likely that in most cases the code size downside of adding default
values is offset by avoiding a `local.set` later, so always do this (rather than add some
kind of heuristic).

OptimizeInstructions: Optimize subsequent struct.sets after struct.new_with_default

---

src/passes/Precompute.cpp
test/lit/passes/precompute-strings.wast

All Struct/Array operations must ignore mutable fields in Precompute atm, which we
did, but StringNew has an array variant that does an effective ArrayGet operation,
which we didn't handle.
Ideally Precompute would do a flow analysis to see if mutability is an issue or not,
at which point we could remove that limitation.

Precompute: Ignore mutable arrays in StringNew

---

src/passes/TranslateEH.cpp
test/lit/passes/translate-to-new-eh.wast

`shouldBeRef` incorrectly assumed that all `throw_ref`s within a `catch` body had been generated from `rethrow`s, which was not true, because `throw_ref`s are also created when translating `try`-`delegate`s: https://github.com/WebAssembly/binaryen/blob/219e668e87b012c0634043ed702534b8be31231f/src/passes/TranslateEH.cpp#L304
This fixes the assumption and changes `cast` to `dynCast`.

[EH] Fix assumption that all throw_refs are created from rethrows

---

.clang-format
src/tools/fuzzing.h
src/tools/fuzzing/fuzzing.cpp
src/wasm-interpreter.h
test/lit/exec/strings.wast

This adds fuzzing for `string.new_wtf16_array` and `string.from_code_point`. The
latter was also missing interpreter support, which this adds.
@tlively I seem to get the wrong results for unicode here - am I using the wrong
API or using it incorrectly? The last testcase here traps in V8 on being an invalid
codePoint but `String::convertUTF16ToUTF8` returns that it is valid.
For comparison, related V8 code: https://chromium.googlesource.com/v8/v8/+/a19a2ff2be5b60f6df6c7c7160860ede2cb85e27%5E%21/#F3

[Strings] Fuzz and interpret all relevant StringNew methods

---

src/wasm-stack.h
test/lit/source-map.wast

No debug information was emitted when a block was right at the start of another block.

Fix some missing debug location information

---

.github/workflows/ci.yml

This will hopefully get setup-python to install Python for the correct
architecture now that the macos runners have switched to ARM.

Upgrade setup-python and checkout actions in CI

---

src/tools/fuzzing.h
src/tools/fuzzing/fuzzing.cpp

Rather than compute the map of type to locals of that type once, at the
start, also update it when relevant, as we can add more locals in some
cases. This allows us to `local.get` from those late-added locals too.

Fuzzer: Update the typeLocals data structure before mutation

---

src/support/file.cpp
src/tools/wasm-ctor-eval.cpp
src/tools/wasm-metadce.cpp
src/tools/wasm2js.cpp
src/wasm/wasm-io.cpp

The new wat parser currently considers itself to be at the end of the file
whenever it cannot lex another token. This is not quite right, but fixing it
causes parser errors because of the extra null character we were appending to
files when we read them. This null character is not useful since we can already
read files as `std::string`, which always has an implicit null character, so
remove it. Clean up some users of `read_file` while we're at it.

Do not add an extra null character when reading files

---

src/ir/possible-contents.cpp
test/lit/passes/gufa-refs.wast

Normally a bottom type cannot reach there, as we ignore unreachable GC
operations early on. However, we can infer a bottom type later during the
flow, so we need to handle that (just not error on it, and for clarity during
debugging we also clear the contents).

GUFA: Handle bottom types in filterDataContents()

---

src/parser/lexer.cpp
src/parser/lexer.h
src/wasm/wasm-io.cpp
test/gtest/wat-lexer.cpp

The lexer currently lexes tokens eagerly and stores them in a `Token` variant
ahead of when they are actually requested by the parser. It is wasteful,
however, to classify tokens before they are requested by the parser because it
is likely that the next token will be precisely the kind the parser requests.
The work of checking and rejecting other possible classifications ahead of time
is not useful.
To make incremental progress toward removing `Token` completely, lex parentheses
on demand instead of eagerly.

[Parser] Do not eagerly lex parens

---

src/parser/lexer.cpp
src/parser/lexer.h

Lex them on demand instead to avoid wasted work.

[Parser] Do not eagerly lex keywords

---

src/parser/lexer.cpp
src/parser/lexer.h

Lex them on demand instead to avoid wasted work.

[Parser] Do not eagerly lex IDs

---

src/parser/lexer.cpp
src/parser/lexer.h

Lex them on demand instead to avoid wasted work.

[Parser] Do not eagerly lex strings

---

src/parser/lexer.cpp
src/parser/lexer.h

Lex integers and floats on demand to avoid wasted work. Remove `Token`
completely now that all kinds of tokens are lexed on demand.

[Parser] Do not eagerly lex numbers

---

src/wasm/wasm-validator.cpp
test/gtest/validator.cpp

Disallow returns from having any children, even unreachable children, in
function that do not return any values.

Improve return validation

---

src/parser/lexer.cpp
src/parser/lexer.h
src/parser/parsers.h

The lexer previously had both `getPos` and `getIndex` APIs that did different
things, but after a recent refactoring there is no difference between the index
and the position. Deduplicate the API surface.

[Parser][NFC] Clean up the lexer index/pos API

---

README.md
src/tools/fuzzing.h
src/tools/fuzzing/fuzzing.cpp
src/wasm/wasm-stack.cpp
test/lit/passes/roundtrip.wast
test/passes/translate-to-fuzz_all-features_metrics_noprint.txt

As suggested in https://github.com/WebAssembly/binaryen/pull/6434#issuecomment-2021399770 , lower `ref.cast` of string views
to `ref.as_non_null` in binary writing. It is a simple hack that avoids the
problem of V8 not allowing them to be cast.
Add fuzzing support for the last three core string operations, after which
that problem becomes very frequent.
Also add yet another `makeTrappingRefUse` that was missing in that
fuzzer code.

[Strings] Work around ref.cast not working on string views, and add fuzzing

---

scripts/fuzz_opt.py

The bug that had been preventing this fuzzing no longer reproduces.

Re-enable fuzzing of text round trips

---

src/wasm/wasm-ir-builder.cpp
test/lit/passes/type-merging-tnh.wast
test/lit/passes/type-merging.wast
test/lit/wat-kitchen-sink.wast

When the input has branches to block scope, IR builder generally has to add a
wrapper block with a label name for the branch to target. To reduce the parsed
IR size, add a special case for when the wrapped expression is already an
unnamed block. In that case we can simply add the label to the existing block
instead of creating a new wrapper block.

[Parser] Re-use blocks instead of wrapping where possible

---

test/example/module-splitting.cpp
test/gtest/cfg.cpp
test/gtest/possible-contents.cpp
test/gtest/print-test.h
test/gtest/stringify.cpp

Some of the example and gtest tests parse wat. Update them to use the new wat
parser, fixing problems with their text input. In one case, comment out an
outlining test entirely for now because the new parser produces different IR
that changes the test output, but it is not obvious how to understand and fix
the test.

Use the new wat parser in tests

---

src/passes/DebugLocationPropagation.cpp
src/passes/Print.cpp
src/wasm-binary.h
src/wasm-stack.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-stack.cpp
test/binaryen.js/sourcemap.js.txt
test/fib-dbg.wasm.fromBinary
test/lit/debug/source-map-smearing.wast
test/lit/debug/source-map-stop.wast

Some debug locations could be dropped at the beginning and end of functions:
- if a source map segment starts before the beginning of the code, it was not taken into account except for the function prologue;
- the last segment of the source map was ignored after one instruction;
- for coherence with the text printer, the text parser should propagate the debug location of the function prologue to its first instruction.
- the text printer should always print the debug location of the function epilogue if there is one (for coherence, since one repeats a debug location at the same indentation level for readability, and for round-tripping since the test parser does not propagate debug locations to the function epilogue).
Also, the binary writer was smearing the debug location of the last …

Source map fixes

---

scripts/fuzz_opt.py
src/ir/type-updating.cpp
src/tools/fuzzing/fuzzing.cpp

As of
https://chromium-review.googlesource.com/c/v8/v8/+/5471674
V8 requires stringviews to be non-nullable. It might be possible to make that
change in our IR, or to remove views entirely, but for now this PR makes the
fuzzer stop emitting nullable stringviews as a workaround to allow us to fuzz
current V8.
Without this the fuzzer errors after just a few dozen, and after it I've gone
several thousand without issue (though in theory this PR might miss some
path that can emit a nullable stringview).

Fuzzer: Stop emitting nullable stringviews

---

src/cfg/cfg-traversal.h

CFGWalker with single-thread fixes

---

src/wasm/wasm-validator.cpp

It seems like that each of the callsites already has looked up the `Memory` object so this helper is not doing anything useful.

[validator] Remove indexType helper function

---

scripts/fuzz_opt.py
src/tools/fuzzing/heap-types.cpp

Original text:
V8 errors on this, e.g. this was created:
```wat
(rec
(type $0 (sub (func (param nullref i32) (result (ref null $3)))))
(type $1 (sub final $0 (func (param stringview_iter i32) (result (ref null $3)))))
)
```
V8 says that subtyping is invalid.
Later PR focuses on ignoring a related message.

Fuzzer: Add another stringview subtyping error message to ignore

---

src/parser/context-decls.cpp
src/parser/contexts.h
src/parser/parsers.h
src/passes/Print.cpp
src/tools/wasm-shell.cpp
src/wasm-binary.h
src/wasm-builder.h
src/wasm-interpreter.h
src/wasm.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-validator.cpp
test/spec/table.wast
test/spec/table_fill.wast
test/spec/table_get.wast
test/spec/table_set.wast
test/spec/table_size.wast

See https://github.com/WebAssembly/memory64/issues/51

[memory64] Add table64 to existing memory64 support

---

src/wasm-stack.h
src/wasm/wasm-stack.cpp
test/lit/binary/dwarf-multivalue.test
test/lit/multivalue.wast

Change `countScratchLocals` to return the count and type of necessary scratch
locals. It used to encode them as keys in the global map from scratch local
types to local indices, which could not handle having more than one scratch
local of a given type and was generally harder to reason about due to its use of
global state. Take the opportunity to avoid emitting unnecessary scratch locals
for `TupleExtract` expressions that will be optimized to not use them.
Also simplify and better document the calculation of the mapping from IR indices
to binary indices for all locals, scratch and non-scratch.

Simplify scratch local calculation

---

src/ir/properties.cpp
src/ir/properties.h
src/passes/LocalCSE.cpp
src/passes/OptimizeInstructions.cpp
test/lit/passes/local-cse.wast

Previously we checked late, and as a result might end up failing to optimize when
a sub-pattern could have worked. E.g.
```wat
(call
(A)
)
(call
(A)
)
```
The `call` cannot be optimized, but the `A` pattern repeats. Before this PR we'd
greedily focus on the entire `call` and then fail. After this PR we skip the call
before we commit to which patterns to try to optimize, so we succeed.
Add a `isShallowlyGenerative` helper here as we compute this step by step as
we go. Also remove a parameter to the generativity code (it did not use the
features it was passed).

LocalCSE: Check effects/generativity early

---

src/passes/LocalCSE.cpp
test/lit/passes/local-cse_all-features.wast

```wat
(ORIGINAL)
(in between)
(COPY)
```
We want to change that to
```wat
(local.tee $temp (ORIGINAL))
(in between)
(local.get $temp)
```
It is fine if "in between" traps: then we never reach the new `local.get`. This is a safer
situation than most optimizations because we are not reordering anything, only
replacing known-equivalent code.

LocalCSE: Ignore traps of code in between

---

src/ir/CMakeLists.txt
src/ir/effects.cpp
src/ir/effects.h

With this you can do `std::cout << effects` and get something like
```
EffectAnalyzer{
writesMemory
hasSideEffects
}
```

[NFC] Add printing for EffectAnalyzer

---

README.md
src/ir/module-utils.cpp
src/parser/contexts.h
src/passes/Print.cpp
src/wasm-ir-builder.h
src/wasm.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-ir-builder.cpp
src/wasm/wasm-s-parser.cpp
test/example/debug-location-propagation.cpp
test/lit/debug/source-map-stop.wast

The comment `;;@` with nothing else can be used to specify that the following expression does not have any debug info associated to it. This can be used to stop the automatic propagation of debug info in the text parsers.
The text printer has also been updated to output this comment when needed.

Source maps: allow to specify that an expression has no debug info in text parsers

---

src/passes/LocalCSE.cpp
test/lit/passes/local-cse.wast
test/lit/passes/local-cse_all-features.wast

#6587 was incorrect: It checked generativity early in an incremental manner, but
it did not accumulate that information as we do with hashes. As a result we
could end up optimizing something with a generative child, and sadly we lacked
testing for that case.
This adds incremental generativity computation alongside hashes. It also splits
out this check from isRelevant.
Also add a test for nested effects (as opposed to generativity), but that already
worked before this PR (as we compute effects and invalidation as we go, already).

LocalCSE: Fix regression from #6587 by accumulating generativity

---

src/parser/contexts.h
test/lit/source-map.wast

The whole annotation was parsed as a keyword, which prevented file paths with non-ascii characters or paths starting with `/` or `.`.
Also, there was a typo: one was comparing `fileSize` rather than `lineSize` to `contents->npos`.

Debug location parser: accept arbitrary paths

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/j2cl-inline.wast
test/lit/passes/optimize-instructions-gc.wast

This existed before #6495 but became noticeable there. We only looked at
the fallthrough values in the later part of `areConsecutiveInputsEqual`, but
there can be invalidation due to the non-fallthrough part:
```wat
(i32.add
(local.get $x)
(block
(local.set $x ..)
(local.get $x)
)
)
```
The set can cause the `local.get` to differ the second time. To fix this,
check if the non-fallthrough part invalidates the fallthrough (but only
on the right hand side).
Fixes #6593

OptimizeInstructions: Add missing invalidation check in consecutive equality test

---

src/passes/Memory64Lowering.cpp
src/passes/Table64Lowering.cpp
src/wasm-traversal.h
test/lit/passes/table64-lowering.wast

This allows modules to contains both 32-bit and 64-bit segment.
In order to check the table/memory state when visiting segments we need to ensure that memories/tables are visited only after their segments.
The comments in visitTable/visitMemory already assumed this but its wasn't actually true in practice.

[Table64Lowering] Don't assume that all segments are from 64-bit tables

---

CMakeLists.txt

This list is identical to `binaryen_SOURCES` above.

[cmake] Remove redundant `binaryen_emscripten_SOURCES`

---

src/passes/GlobalRefining.cpp
src/wasm/wasm-validator.cpp
test/example/c-api-kitchen-sink.c
test/lit/passes/global-refining.wast

GlobalRefining did not traverse module code, so it did not update `global.get`s
in other globals.
Add missing validation that actually errors on that: We did not check `global.get`
types.
These could be separate PRs but it would be difficult to test them separately.

Fix GlobalRefining's handling of gets in module code and add missing validation

---

src/passes/SimplifyGlobals.cpp
test/lit/passes/simplify-globals-gc.wast

If we wanted to switch types in such cases we'd need to refinalize (which is likely
worth doing, though other passes should refine globals anyhow).
(I am adding more fuzzing for globals, which is finding these bugs.)

SimplifyGlobals: Do not switch a get to use a global of another type

---

src/tools/fuzzing/fuzzing.cpp
src/wasm/wasm-validator.cpp

The DataSegment was manually added to `.dataSegments`, but we need to add it
using `addDataSegment` so the maps are updated and `getDataSegment(name)`
works.
Ideally `.dataSegments` would be private, but a lot of code finds it useful to
iterate on it, so we've left it accessible.
Also add validation that would have caught this earlier: check that each item in
the item lists can be fetched by name.
The reason this was noticed is that #6620 happened to run into it by pure luck.

Fix fuzzer generation of a DataSegment + add validation that would have caught it

---

scripts/fuzz_opt.py

Turboshaft, the replacement, is rolling out, so we no longer need the coverage.
This makes us significantly faster as TurboFan was much slower than Turboshaft
on random fuzzer binaries.

Fuzzer: Stop testing with TurboFan

---

.clang-format
src/ir/type-updating.cpp
src/ir/type-updating.h
src/passes/SignaturePruning.cpp
test/lit/passes/signature-pruning.wast

The SignaturePruning pass optimizes away parameters that it proves are safe to
remove. It turns out that that does not always match the definition of private
types, which is more restrictive. Specifically, if say all the types are in one big
rec group and one of them is used on an exported function then all of them are
considered public (as the rec group is). However, in closed world, it would be ok
to leave that rec group unchanged but to create a pruned version of that type
and use it, in cases where we see it is safe to remove a parameter. (See the
testcase in the PR for a concrete example.)
To put it another way, SignaturePruning already proves that a parameter is
safe to remove in all the ways that matter. Before this PR, however, the testcase
in this PR would error - so this PR is …

SignaturePruning: Properly handle public types

---

CMakeLists.txt

This makes several changes to make the Emscripten build more configurable and convenient for testing:
1) Remove ERROR_ON_WASM_CHANGES_AFTER_LINK from ENABLE_BIGINT: this makes the setting composable with optimized builds
2) Add EMSCRIPTEN_ENABLE_MEMORY64 to build with the memory64 option
3) Add EMSCRIPTEN_ENABLE_SINGLE_FILE to allow disabling the single-file build (to make it easier to analyze binary output)

Make Emscripten CMake build more configurable

---

src/passes/Precompute.cpp

This PR addresses #6639, moving `ChildIterator(stack[index - 1])` into a local variable to avoid use after free.
Tested manually on Windows and Linux, same result as expected.

fix(#6639): fix stack-use-after-scope on windows

---

src/asmjs/asm_v_wasm.cpp
src/emscripten-optimizer/optimizer-shared.cpp
src/emscripten-optimizer/optimizer.h
src/emscripten-optimizer/simple_ast.h
src/wasm2js.h
test/wasm2js/refs.2asm.js
test/wasm2js/refs.2asm.js.opt
test/wasm2js/refs.wast

This adds `ref.eq, ref.null, ref.is_null, ref.func`.
I am not aware of a use case for these in production, but they should be helpful for
fuzzing in some ways.

wasm2js: Add basic reference operations

---

src/parser/CMakeLists.txt
src/parser/parse-1-decls.cpp
src/parser/parse-2-typedefs.cpp
src/parser/parse-3-implicit-types.cpp
src/parser/parse-4-module-types.cpp
src/parser/parse-5-defs.cpp
src/parser/parsers.h
src/parser/wat-parser-internal.h
src/parser/wat-parser.cpp

Because the parser has five stages, it requires instantiating all of the templates in parsers.h with up to five different contexts. Instantiating all those templates in a single compilation unit takes a long time. On my machine, a release build of wat-parser.cpp.o took 32 seconds. To reduce the time of incremental rebuilds on machines with many cores, split the code across several compilation units so that the templates need to be instantiated for just a single context in each unit. On my machine the longest compilation time after this splitting is 17 seconds. The time for a full release build also drops from 42 seconds to 33 seconds. On machines with fewer cores, the benefit may be smaller or even negative, though.

[Parser][NFC] Split parser into multiple compilation units

---

src/wasm2js.h
test/wasm2js/refs.2asm.js
test/wasm2js/refs.2asm.js.opt
test/wasm2js/refs.wast

This avoids special-casing particular global init forms. After this we should
support everything in global inits that we support anywhere else.

wasm2js: Generalize global initializer code to use the main codegen logic

---

src/tools/tool-options.h
src/wasm-binary.h
src/wasm-features.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-type.cpp
src/wasm/wasm-validator.cpp
src/wasm/wasm.cpp
test/binaryen.js/kitchen-sink.js.txt
test/example/c-api-kitchen-sink.txt
test/lit/help/wasm-as.test
test/lit/help/wasm-ctor-eval.test
test/lit/help/wasm-dis.test
test/lit/help/wasm-emscripten-finalize.test
test/lit/help/wasm-merge.test
test/lit/help/wasm-metadce.test
test/lit/help/wasm-opt.test
test/lit/help/wasm-reduce.test
test/lit/help/wasm-split.test
test/lit/help/wasm2js.test
test/lit/validation/shared-struct.wast
test/passes/strip-target-features_roundtrip_print-features_all-features.txt
test/unit/test_features.py

Add the feature and flags to enable and disable it. Require the new feature to
be enabled for shared heap types to validate. To make the test work, update the
validator to actually check features for global types.

[threads] Add a "shared-everything" feature

---

src/wasm-type.h
test/example/typeinfo.cpp
test/gtest/type-builder.cpp

Since the BasicHeapTypes are in an enum, calling HeapType methods on them
requires something like `HeapType(HeapType::func).someMethod()`. This is
unnecessarily verbose, so add a new `HeapTypes` namespace that contains
constexpr HeapType globals that can be used instead, shorting this to
`HeapTypes::func.someMethod()`.

[NFC] Add constexpr HeapTypes for basic heap types

---

src/parser/contexts.h
test/lit/passes/optimize-instructions-gc.wast
test/lit/passes/type-generalizing.wast
test/lit/wat-kitchen-sink.wast

As an abbreviation, a `typeuse` can be given as just a list of parameters and
results, in which case it corresponds to the index of the first function type
with the same parameters and results. That function type must also be an MVP
function type, i.e. it cannot have a nontrivial rec group, be non-final, or have
a declared supertype. The parser did not previously implement all of these rules.

[Parser] Update requirements for implicit type uses

---

src/parser/contexts.h
src/parser/parsers.h
test/lit/passes/optimize-instructions-gc.wast
test/lit/passes/type-generalizing.wast
test/lit/wat-kitchen-sink.wast
test/spec/ref_cast.wast

Not all uses of the `reftype` parser handled the fact that it returned a
`MaybeResult`. Change its name to `maybeReftype`, add a new `reftype` parser
that returns an error if there is no reftype, and update all the use sites.
Fixes #6655.

[Parser] Fix error message on required reftype

---

check.py
scripts/test/shared.py
scripts/test/support.py
test/spec/stack.wast

Re-triage all the disabled spec tests and re-enable many of them. Improve the module splitting logic to correctly handle (by skipping) quoted modules and their associated assertions.

Enable more spec tests

---

src/passes/GlobalStructInference.cpp
test/lit/passes/gsi.wast

This is achieved by simply replacing the Literal with PossibleConstantValues,
which supports both Literals and Globals.

GlobalStructInference: Optimize globals too

---

scripts/test/shared.py
src/wasm-binary.h
src/wasm/wasm-binary.cpp

Rather than treating them as custom sections. Also fix UB where invalid
`Section` enum values could be used as keys in a map. Use the raw `uint8_t`
section IDs as keys instead. Re-enable a disabled spec test that was failing
because of this bug and UB.

Reject invalid section IDs

---

scripts/test/shared.py
src/wasm/wasm-ir-builder.cpp
test/lit/wat-kitchen-sink.wast

When popping past an unreachable instruction would lead to popping from an empty
stack or popping an incorrect type, we need to avoid popping and produce new
`Unreachable` instructions instead to ensure we parse valid IR. The logic for
this was flawed and made the synthetic `Unreachable` come before the popped
unreachable child, which was not correct in the case that that popped
unreachable was a branch or other non-trapping instruction. Fix and simplify the
logic and re-enable the spec test that uncovered the bug.

[Parser] Fix bug in unreachable fallback logic

---

scripts/test/shared.py
src/wasm-binary.h

The unused bits must be a sign extension of the significant value, but we were
previously only validating that unsigned LEBs had their unused bytes set to
zero. Re-enable the spec test that checks for proper validation.

Fix validation of unused LEB128 bits

---

scripts/test/shared.py
src/parser/lexer.h
src/support/string.cpp
src/support/string.h
src/wasm-binary.h
src/wasm/wasm-binary.cpp

Add an `isUTF8` utility and use it in both the text and binary parsers. Add missing checks for overlong encodings and overlarge code points in our WTF8 reader, which the new utility uses. Re-enable the spec tests that test UTF-8 validation.

Validate that names are valid UTF-8

---

src/support/string.cpp

This will hopefully fix the build on the coverage builder.

[NFC] Add pragma to ignore maybe-uninitialized in strings.cpp

---

scripts/test/shared.py
src/support/string.cpp
src/wasm/wasm-validator.cpp
test/spec/address.wast

For 32-bit memories, the offset value must be in the u32 range. Update
the address.wast spec test to assert that a module with an overlarge
offset value is invalid rather than malformed.

Validate memarg offsets

---

scripts/test/shared.py
src/support/string.cpp
src/wasm/wasm-validator.cpp
test/spec/address.wast
test/spec/func.wast
test/spec/type.wast

And delete tests that no longer pass now that multivalue is standard.

Re-enable spec tests requiring multivalue

---

.clang-format
src/passes/GlobalStructInference.cpp
test/lit/passes/gsi.wast

If we have
```wat
(global $g (struct.new $S
(i32.const 1)
(struct.new $T ..)
(ref.func $f)
))
```
then before this PR if we wanted to read the middle field we'd stop, as it is non-constant.
However, we can un-nest it, making it constant:
```wat
(global $g.unnested (struct.new $T ..))
(global $g (struct.new $S
(i32.const 1)
(global.get $g.unnested)
(ref.func $f)
))
```
Now the field is a `global.get` of an immutable global, which is constant. Using this
technique we can handle anything in a struct field, constant or not. The cost of adding
a global is likely offset by the benefit of being able to refer to it directly, as that opens
up more opportunities later.
Concretely, this replaces the constant values we look for in GSI with a variant over
constants or expressions (we do still want to …

GlobalStructInference: Un-nest struct.news in globals when that is helpful

---

src/wasm2js.h
test/wasm2js/refs.2asm.js
test/wasm2js/refs.2asm.js.opt
test/wasm2js/refs.wast

We were missing code to mangle such names for JS. Without that, the name
of a temp var for the type `(ref $foo)` would end up with `(`, `)` in the name, which
is not valid in JS.
(See last commit for the effect of the one-line change.)

wasm2js: Fix the names of temp vars with named reference types

---

src/wasm/wasm-binary.cpp

The result cannot be `none` or `unreachable` etc.
Fixes #6694

Add a proper error for bad select results

---

src/passes/Heap2Local.cpp

We tracked which expressions we saw an allocated struct/array reach, and then
quickly exited when another one did (as when two allocations mix, we can
optimize neither). It turns out that this helps very little in actual measurements
(looks like within noise - likely we are ruling out the un-optimizable cases early
otherwise anyhow). Also the complexity it adds is a problem for an improvement
I want to make to the pass, so remove it.

[NFC] Remove a minor compile-time optimization in Heap2Local

---

src/wasm/wasm-binary.cpp

That child must be a reference, as `finalize()` assumes so. To avoid an
assertion, error early.
Fixes #6696

Add a missing binary reading check for BrOn's reference child's type

---

src/wasm/wasm-binary.cpp

Add missing struct/array type checks in binary reader

---

src/wasm-type.h
src/wasm/wasm-type.cpp
test/lit/passes/type-merging-shared.wast
test/spec/shared-array.wast
test/spec/shared-struct.wast

Add spec tests checking validation for structs and arrays.

[threads] Validate shared-to-unshared edges in heap types

---

scripts/fuzz_opt.py
src/wasm/wasm-binary.cpp
src/wasm/wasm-validator.cpp
test/spec/shared-array.wast
test/spec/shared-polymorphism.wast
test/spec/shared-struct.wast

Such as `ref.eq`, `i31.get_{s,u}`, and `array.len`. Also validate that
struct and array operations work on shared structs and arrays.

[threads] Validate shared-polymorphic instructions

---

test/lit/wasm-split/mismatched-hashes.wast

The `filecheck` command used for tests does not support `CHECK-SAME`, so use should be avoided.

[tests] Remove use of CHECK-SAME

---

src/binaryen-c.cpp
src/binaryen-c.h
test/example/c-api-kitchen-sink.c
test/example/c-api-kitchen-sink.txt

[C API] Add APIs for getting/setting function types, and a CallRef example

---

src/passes/Heap2Local.cpp
test/lit/passes/heap2local.wast

This is a tiny bit more code but it is more consistent with other operations, and
it saves work later.
As suggested in https://github.com/WebAssembly/binaryen/pull/6705/files#r1655368073

Heap2Local: Drop RefEq's two arms

---

src/wasm/wasm-validator.cpp
src/wasm/wasm.cpp
test/spec/shared-polymorphism.wast

`any.convert_extern` and `extern.convert_any` return references to
shared heap types iff their operands are references to shared heap
types.

[threads] Shared polymorphism for extern conversions

---

src/passes/Monomorphize.cpp
test/lit/passes/monomorphize-consts.wast
test/lit/passes/monomorphize-types.wast

Eventually I'll need to do some tuning of compile time speed, but for now it is
going to be simpler to do all the opts, in particular because it makes writing
tests simpler.

Monomorphize: Use -O3 over -O1 + tweaks

---

src/passes/Memory64Lowering.cpp
test/lit/passes/memory64-lowering.wast

This edge case make the lowering a little more tricky.

Memory64Lowering: Handle -1 return value from memory.grow

---

src/passes/Print.cpp
test/lit/basic/multi-table.wast
test/lit/passes/optimize-instructions-call_ref-roundtrip.wast
test/lit/passes/optimize-instructions-call_ref.wast
test/lit/passes/table64-lowering.wast
test/lit/passes/unsubtyping.wast
test/lit/wat-kitchen-sink.wast

The full syntax for an expression in an element syntax looks like
`(item (ref.null none))`, but we have been printing the abbreviated
version, which omits the `(item ...)`. This abbreviation is only valid
when the item has only a single instruction, so it is not always correct
to use it. Rather than determining whether or not to use the
abbreviation on a case-by-case basis, always print the full syntax.

Do not abbreviate items in element segments

---

src/passes/SafeHeap.cpp
test/passes/safe-heap_disable-simd.txt
test/passes/safe-heap_enable-threads_enable-simd.txt
test/passes/safe-heap_enable-threads_enable-simd64.txt
test/passes/safe-heap_low-memory-unused_enable-threads_enable-simd.txt
test/passes/safe-heap_start-function.txt

E.g. loading `4` bytes from `2^32 - 2` should error: `2` bytes are past the maximum
address. Before this PR we added `2^32 - 2 + 4` and overflowed to `2`, which we
saw as a low and safe address. This PR adds an extra check for an overflow in
that add.
Fixes https://github.com/emscripten-core/emscripten/issues/21557

SafeHeap: Handle overflows when adding the pointer and the size

---

CHANGELOG.md

We made a release since it was written, which this is not included in.

Fix changelog order after #6687

---

src/tools/fuzzing/fuzzing.cpp
test/passes/translate-to-fuzz_all-features_metrics_noprint.txt

When creating a reference to `func`, fix the probability of choosing to
continue on to choose some function other than the last one rather than
making it depend on the number of functions. Then, do not eagerly pick
from the rest of the candidate functions. Instead, fall through to the
more general logic that will already pick a random candidate function.
Also move the logic for coming up with a concrete signature down to
where it is needed.
These simplifications will make it easier to update the code to handle
shared types.

Simplify fuzzer generation of function references

---

src/ir/ExpressionManipulator.cpp
src/ir/manipulation.h

`flexibleCopy` always visited parents before children, but it visited
vector children in reverse order:
```wat
(call        ;; 1
(call $a)  ;; 3
(call $b)  ;; 2
)
```
The order of children happened to not matter in any user of this code,
and that's just what you get when you iterate over children in a vector
and push them to a stack before visiting them, so this odd ordering
was not noticed.
For a new user I will introduce soon, however, it would be nice to have
the normal pre-order:
```wat
(call        ;; 1
(call $a)  ;; 2
(call $b)  ;; 3
)
```
(2 & 3 swapped).
This cannot be tested in the current code as it is NFC, but the later PR
will depend on it and test it heavily.

[NFC] Clarify and standardize order in flexibleCopy

---

src/wasm/literal.cpp
test/spec/shared-polymorphism.wast

Normally, values of different types can never compare equal to each
other, but since i31refs are not actually allocations, `ref.eq` has no
way to differentiate a shared i31ref and an unshared i31ref with the
same value, so it will report them as equal. Update the implementation
of value equality to reflect this correctly.

[threads] Allow i31refs of mixed shareability to compare equal

---

src/binaryen-c.cpp
src/binaryen-c.h
src/js/binaryen.js-post.js
test/binaryen.js/closed-world.js
test/binaryen.js/closed-world.js.txt
test/binaryen.js/generate-stack-ir.js
test/binaryen.js/generate-stack-ir.js.txt
test/binaryen.js/optimize-stack-ir.js
test/binaryen.js/optimize-stack-ir.js.txt
test/binaryen.js/passes-to-skip.js
test/binaryen.js/traps-never-happen.js
test/binaryen.js/traps-never-happen.js.txt

Add functions to:
- set and get the `trapsNeverHappen`, `closedWorld`, `generateStackIR` and `optimizeStackIR` flags
- manage the list of passes to skip

Add C and JS APIs to control more pass options

---

src/wasm/wasm-type.cpp
test/lit/validation/shared-absheaptype.wast

The logic for adding the shared-everything feature was not previously
executed for shared basic heap types.

[threads] Fix feature detection for shared basic heap types

---

scripts/fuzz_opt.py
src/wasm/wasm-validator.cpp
test/lit/validation/shared-absheaptype.wast
test/lit/validation/shared-null.wast

`ref.null` of shared types should only be allowed when shared-everything
is enabled, but we were previously checking only that reference types
were enabled when validating `ref.null`. Update the code to check all
features required by the null type and factor out shared logic for
printing lists of missing feature options in error messages.

[threads] Validate all features required by ref.null

---

src/wasm/literal.cpp
test/spec/shared-polymorphism.wast

Allowing Literals with different types to compare equal causes problems
for passes that want equality to mean real equality, e.g. because they
are using literals as map keys or because they otherwise need to use
them interchangeably.
At a minimum, we would need to differentiate a `refEq` operation where
mixed-shareability i31refs can compare equal from physical equality on
Literals, but there is also appetite to disallow mixed-shareability
ref.eq at the spec level. See
https://github.com/WebAssembly/shared-everything-threads/issues/76.

Revert "[threads] Allow i31refs of mixed shareability to compare equal (#6752)"

---

scripts/fuzz_opt.py
src/wasm/literal.cpp
src/wasm/wasm-validator.cpp
test/spec/shared-polymorphism.wast
test/spec/shared-ref_eq.wast

Update the validator to reject mixed-shareability ref.eq, although this
is still under discussion in
https://github.com/WebAssembly/shared-everything-threads/issues/76. Fix
the implementation of `Literal::operator==` to work properly with shared
i31ref.

[threads] Fix shared ref.eq and disallow mixed-shareability

---

CMakeLists.txt

Fixes https://github.com/emscripten-core/emscripten/issues/17228
This seems the right default in binaryen.js which is used as a library through
npm mostly. We aren't a main program that wants to control node exclusively.
I verified manually that this does not interfere with our binaryen.js tests here,
just to be safe (that is, I added an error in a test and I saw the test then failed).

binaryen.js: Avoid catching exit/rejection which confuses Node error reporting

---

scripts/fuzz_opt.py
src/wasm/wasm-validator.cpp
test/lit/validation/table-type.wast

We previously special-cased things like GC types, but switch to a more
general solution of detecting what features a table's type requires.

Validate features for types used in tables

---

scripts/fuzz_opt.py
src/tools/fuzzing/fuzzing.cpp
src/tools/fuzzing/heap-types.cpp
test/passes/translate-to-fuzz_all-features_metrics_noprint.txt

Update the fuzzer to both handle shared types in initial contents and
create and use new shared types without crashing or producing invalid
modules. Since V8 does not have a complete implementation of
shared-everything-threads yet, disable fuzzing V8 when shared-everything
is enabled. To avoid losing too much coverage of V8, disable
shared-everything in the fuzzer more frequently than other features.

[threads] Update the fuzzer for shared types

---

src/literal.h
src/tools/fuzzing/heap-types.cpp
src/wasm-builder.h
src/wasm-type.h
src/wasm/literal.cpp
src/wasm/wasm-binary.cpp
src/wasm/wasm-validator.cpp
src/wasm/wasm.cpp

This abbreviates a common pattern where we first had to check whether a
heap type was basic, then if it was, get its unshared version and
compare it to some expected BasicHeapType.
Suggested in
https://github.com/WebAssembly/binaryen/pull/6771#discussion_r1683005495.

[NFC] Add HeapType::isMaybeShared(BasicHeapType) utility

---

src/passes/Heap2Local.cpp
test/lit/passes/heap2local.wast

Followup to #6727 which added support for failing casts in Struct2Local, but it
turns out that it required Array2Struct changes as well. Specifically, when we
turn an array into a struct then casts can look like they behave differently
(what used to be an array input, becomes a struct), so like with RefTest that we
already handled, check if the cast succeeds in the original form and handle
that.

Heap2Local: Properly handle failing array casts

---

src/passes/Inlining.cpp

Aside from the fact that there's no need for this to be non-const and this is the usual way to write an assignment operator, this is also needed because of a recent change to std::pair (https://github.com/llvm/llvm-project/pull/89652). This seems to be forcing pair to want the const version of the assignment operator of its members.

Make FunctionInfo's assignment operator argument const

---

src/ir/subtypes.h
test/gtest/type-builder.cpp
test/lit/passes/gufa-tnh.wast

[threads] Calculate shared heap type depths in subtypes.h

---

src/wasm/wasm-validator.cpp
src/wasm/wasm.cpp
test/lit/validation/non-ref.wast

Validate RefAsNonNull

---

src/passes/TupleOptimization.cpp
test/lit/passes/tuple-optimization.wast

We used the target's type for the read from the source, but due to subtyping those
might be different.

TupleOptimization: Properly handle subtyping in copies

---

src/wasm/literal.cpp
test/lit/ctor-eval/shared-i31.wast
test/lit/exec/strings.wast

Is it worth testing shareability here? (is the fuzzer ready?)

Generalize Literal::externalize/internalize for strings and shareability

---

src/support/strongly_connected_components.h
test/gtest/CMakeLists.txt
test/gtest/scc.cpp

Implement a non-recursive version of Tarjan's Strongly Connected
Component algorithm that consumes and produces iterators for maximum
flexibility.
This will be used in an optimization that transforms the heap type graph
to use minimal recursion groups, which correspond to the strongly
connected components of the type graph.

Add a Tarjan's Strongly Connected Component utilty

---

CHANGELOG.md
src/passes/Metrics.cpp
src/passes/pass.cpp
test/lit/help/wasm-metadce.test
test/lit/help/wasm-opt.test
test/lit/help/wasm2js.test
test/lit/passes/metrics.wast
test/passes/O3_low-memory-unused_metrics.txt
test/passes/converge_O3_metrics.bin.txt
test/passes/func-metrics.txt
test/passes/fuzz_metrics_noprint.bin.txt
test/passes/metrics_all-features.txt
test/passes/metrics_strip-debug_metrics.bin.txt
test/passes/metrics_strip-producers_metrics.bin.txt
test/passes/print_g_metrics.bin.txt
test/passes/sparse_matrix_liveness.bin.txt
test/passes/translate-to-fuzz_all-features_metrics_noprint.txt

Before the PR:
```wat
$ bin/wasm-opt test/hello_world.wat --metrics
total
[exports]      : 1       
[funcs]        : 1       
[globals]      : 0       
[imports]      : 0       
[memories]     : 1       
[memory-data]  : 0       
[tables]       : 0       
[tags]         : 0       
[total]        : 3       
[vars]         : 0       
Binary         : 1       
LocalGet       : 2       
```
After the PR:
```wat
$ bin/wasm-opt test/hello_world.wat --metrics
Metrics
total
[exports]      : 1       
[funcs]        : 1       
...
```
Note the "Metrics" addition at the top. And the title can be customized:
```wat
$ bin/wasm-opt test/hello_world.wat --metrics=text
Metrics: text
total
[exports]      : 1       
[funcs]        : 1       
```
The custom title can be helpful when multiple invocations of …

Add a customizable title to Metrics reporting

---

src/wasm/literal.cpp

The local was only used once, so it didn't really add much. And, it was causing some
compilers to error on "unused variable" (when building without assertions, the use
was removed).

[NFC] Avoid a temp local

---

src/support/disjoint_sets.h
test/gtest/CMakeLists.txt
test/gtest/disjoint_sets.cpp

This will be used in an upcoming type optimization pass and may be
generally useful.

Add a disjoint sets (union-find) utility

---

src/passes/TypeSSA.cpp
test/lit/passes/type-ssa-shared.wast

@tlively This makes me wonder if we should consider adding a "copy" method on
TypeBuilder, to avoid needing to remember to do both setOpen/setShared in each
such place?

Fix shareability handling in TypeSSA collision logic

---

src/support/CMakeLists.txt
src/support/strongly_connected_components.h
src/support/topological_orders.cpp
src/support/topological_orders.h
test/gtest/CMakeLists.txt
test/gtest/topological-orders.cpp

Use an extension of Kahn's algorithm for finding topological orders that
iteratively makes every possible choice at every step to find all the
topological orders. The order being constructed and the set of possible
choices are managed in-place in the same buffer, so the algorithm takes
linear time and space plus amortized constant time per generated order.
This will be used in an upcoming type optimization.

Add a utility for iterating over all topological orders

---

src/wasm/wasm-binary.cpp

As a followup we could probably make these more consistent.  For example, we could use a single char prefix for defined functions/tables/globals (e.g. f0/t0/g0)

WasmBinaryReader: Use helper function to create names for items. NFC

---

src/literal.h
src/passes/Precompute.cpp
src/tools/execution-results.h
src/tools/fuzzing/fuzzing.cpp
src/tools/wasm-ctor-eval.cpp
src/wasm-builder.h
src/wasm-type.h
src/wasm/literal.cpp
src/wasm/wasm-type.cpp

The HeapType API has functions like `isBasic()`, `isStruct()`,
`isSignature()`, etc. to test the classification of a heap type. Many
users have to call these functions in sequence and handle all or most of
the possible classifications. When we add a new kind of heap type,
finding and updating all these sites is a manual and error-prone
process.
To make adding new heap type kinds easier, introduce a new API that
returns an enum classifying the heap type. The enum can be used in
switch statements and the compiler's exhaustiveness checker will flag
use sites that need to be updated when we add a new kind of heap type.
This commit uses the new enum internally in the type system, but
follow-on commits will add new uses and convert uses of the existing
APIs to use `getKind` instead.

[NFC] Add HeapType::getKind returning a new HeapTypeKind enum

---

src/literal.h
src/passes/Precompute.cpp
src/tools/execution-results.h
src/tools/fuzzing/fuzzing.cpp
src/tools/fuzzing/heap-types.cpp
src/tools/wasm-ctor-eval.cpp
src/wasm-builder.h
src/wasm-type.h
src/wasm/literal.cpp
src/wasm/wasm-type.cpp

The code for collecting inhabitable types incorrectly considered shared,
non-nullable externrefs to be inhabitable, which disagreed with the code
for rewriting types to be inhabitable, which was correct, causing the
type fuzzer to report an error.

Fix sharedness bug in inhabitable type fuzzer

---

src/wasm/wasm-binary.cpp
test/gtest/CMakeLists.txt
test/gtest/binary-reader.cpp

Single-segment mappings were already handled in `readNextDebugLocation`, but not in `readSourceMapHeader`.
Update `readSourceMapHeader` to handle single-segment mappings.
The code to handle single segments is copied from `readNextDebugLocation`.

Handle single-segment source mapping in source map header decoder

---

src/literal.h
src/passes/Precompute.cpp
src/tools/execution-results.h
src/tools/fuzzing/fuzzing.cpp
src/tools/wasm-ctor-eval.cpp
src/wasm-builder.h
src/wasm-type.h
src/wasm/literal.cpp
src/wasm/wasm-type.cpp

PR ##6803 proposed removing Type::isString and HeapType::isString in
favor of more explicit, verbose callsites. There was no consensus to
make this change, but it was accidentally committed as part of #6804.
Revert the accidental change, except for the useful, noncontroversial
parts, such as fixing the `isString` implementation and a few other
locations to correctly handle shared types.

Restore isString type methods

---

src/parser/parse-2-typedefs.cpp
test/lit/parse-bad-supertype-8616.wast

The type index from the TypeBuilder error was mapped to a file location
incorrectly, resulting in an assertion failure.
Fixes #6816.

[parser] Fix bug when printing type builder errors

---

src/parser/contexts.h
src/parser/parse-2-typedefs.cpp
src/parser/parsers.h
src/parser/wat-parser.cpp

Match the current spec and clarify terminology by renaming the old `deftype` to
`rectype` and renaming the old `subtype` to `typedef`. Also split the parser for
actual `subtype` out of the parser for the newly named `typedef`.

[NFC][parser] Rename deftype and subtype

---

src/passes/GlobalTypeOptimization.cpp
test/lit/passes/gto-removals.wast

The optimization is to only use ChildLocalizer, which moves children to
locals, if we actually have a reason to use it. It is simple enough to see if
we are removing fields with side effects here, and only call ChildLocalizer
if we are not. However, this will become much more complicated in a
subsequent PR which will *reorder* fields, which allows removing yet more
of them (without reordering, we can only remove fields at the end, if any
subtype needs the field).
This is a pretty minor optimization, as it avoids adding a few locals in the rare
case of `struct.new` operands having side effects. We run `--gto` at the
start of the pipeline, so later opts will clean that up anyhow. (Though, this
might make us a little less efficient, but the following PR will justify this
regression.)

GTO: Remove minor optimization of avoiding ChildLocalizer sometimes

---

src/tools/wasm-fuzz-types.cpp
src/wasm-type-shape.h
src/wasm-type.h
src/wasm/CMakeLists.txt
src/wasm/wasm-type-shape.cpp

This is very similar to the internal utilities for canonicalizing rec
groups in the type system implementation, except that the new utility
also supports ordered comparison of rec groups, and of course the new
utility only uses the public type API.
A follow-up PR will replace the internal implementation of rec group
comparison and hashing in the type system with this one.
Another follow-up PR will use this new utility in a type optimization.

Add a utility for comparing and hashing rec group shapes

---

src/support/topological_orders.cpp
src/support/topological_orders.h
src/tools/wasm-fuzz-types.cpp
src/wasm-type-shape.h
src/wasm-type.h
src/wasm/CMakeLists.txt
src/wasm/wasm-type-shape.cpp

Make `TopologicalOrders` its own iterator rather than having a separate
iterator class that wraps a pointer to `TopologicalOrders`. This
simplifies usage in cases where an iterator needs to be persistently
stored. Notably, all of the tests continue working as they are.

Simplify TopologicalOrders

---

src/parser/parsers.h
src/passes/Print.cpp
test/lit/basic/typed_continuations_resume.wast
test/lit/wat-kitchen-sink.wast

The syntax for handler clauses in `resume` instructions has recently changed, using `on` instead of `tag` now.
Instead of 
```
(resume $ct (tag $tag0 $block0) ...  (tag $tagn $blockn))
```
we now have
```
(resume $ct (on $tag0 $block0) ...  (on $tagn $blockn))
```
This PR adapts parsing, printing, and some tests accordingly.
(Note that this PR deliberately makes none of the other changes that will arise from implementing the new, combined stack switching proposal, yet.)

Typed continuations: update syntax of handler clauses

---

src/passes/FuncCastEmulation.cpp

Without this all the newly created thunks lack names in the name section.

Set hasExplicitName for thunks generated in FuncCastEmulation. NFC

---

src/ir/type-updating.cpp
src/passes/TypeSSA.cpp
src/wasm-type.h
src/wasm/wasm-type.cpp

Given a function that maps the old child heap types to new child heap
types, the new API takes care of copying the rest of the structure of a
given heap type into a TypeBuilder slot.
Use the new API in GlobalTypeRewriter::rebuildTypes. It will also be
used in an upcoming type optimization. This refactoring also required
adding the ability to clear the supertype of a TypeBuilder slot, which
was previously not possible.

Add a TypeBuilder API for copying a heap type

---

src/ir/type-updating.cpp
src/ir/type-updating.h
src/passes/TypeSSA.cpp
src/wasm-type.h
src/wasm/wasm-type.cpp

Previously a module's type names were updated in
`GlobalTypeRewriter::rebuildTypes`, which builds new versions of the
existing types, rather than `GlobalTypeRewriter::mapTypes`, which
otherwise handles replacing old types with new types everywhere in a
module, but should not necessarily replace names. So that users of
`mapTypes` who are building their own versions of existing types can
also easily update type names, split type name mapping logic out into a
new method `GlobalTypeRewriter::mapTypeNames`.

[NFC] Separate out GlobalTypeRewriter::mapTypeNames

---

src/parser/parsers.h

This PR fixes the out-of-bounds read bug noted in [issue 6833](https://github.com/WebAssembly/binaryen/issues/6833) by performing error checking on a pointer before it is used.
**Post fix output:**
```
./wasm-opt ./wasm-oob-read.wasm
Fatal: 1:184: error: expected elem index or identifier
```

Fix OOB read bug - issue 6833

---

src/passes/Heap2Local.cpp
test/lit/passes/heap2local.wast

Previously we tracked only whether an expression was relevant to analysis, that is,
whether it interacted with the allocation we were tracing the behavior of. That is
not enough for all cases, though, so also track the form of the interaction, namely
whether the allocation flows through or is fully consumed. An example where that
matters:
```wat
(ref.eq
(struct.get $A 0
(local.tee $x
(struct.new_default $A)
)
)
(local.get $x)
)
```
Here the `local.get` flows out the allocation, but the `struct.get` only fully consumes
it. Before this PR we thought the `struct.get` flowed the allocation, and we misoptimized
this to `1`.
To make this possible, do a bunch of minor refactoring:
* Move ParentChildInteraction out of the class.
* Add a "None" interaction there.
* Replace the set of reached …

Heap2Local: Track interactions in detail

---

src/ir/module-utils.cpp
test/lit/passes/cfp.wast

Previously we included supertypes, but did not increase their count.
This was done so that the output for the nominal type system, which
introduced explicitly supertypes, would more closely match the output
with the old equirecursive types system. Neither type system exists
anymore and we only support the single, standard isorecursive type
system, so we can now properly count supertypes. It turns out it doesn't
make much of a difference in the test outputs anyway.

Count supertypes when collecting module types

---

src/wasm/wasm-type.cpp
test/lit/binary/strings-nogc.test
test/lit/validation/nullref-no-gc.wast
test/lit/validation/shared-null.wast

Since reference types only introduced function and extern references,
all of the types in the `any` hierarchy require GC, including `none`.
Fixes #6839.

Heap type `none` requires GC

---

src/wasm/literal.cpp

* `HeapType::ext` was handled in two places. The second place was [wrong, but not reached](https://github.com/WebAssembly/binaryen/pull/6814#discussion_r1717531032).
* Near the end all we have left are refs, so no need to check `isRef` etc.
* Simplify the code to get the heap type once.

[NFC] Clean up Literal copy constructor

---

src/wasm/wasm-validator.cpp

The previous rules for stale types were complicated and hard to
remember: in general it was ok for result types to be further refinable
as long as they were not refinable all the way to `unreachable`, but
control flow structures had a carve-out and it was ok for them to be
refinable all the way to unreachable.
Simplify the rules so that further refinable result types are always ok,
no matter what they can be refined to and no matter what kind of
instruction is being validated. This will be much easier to remember and
reason about.
This relaxation of the rules strictly increases the set of valid IR, so
no passes or tests need to be updated. It does make it possible for us
to miss type refinement opportunities that previously would have been
validation errors, but only in cases where …

Simplify validation of stale types

---

test/lit/passes/gto-removals.wast

We don't properly validate that yet. E.g.:
```wat
(module
(rec
(type $func (func))
(type $unused (sub (struct (field v128))))
)
(func $func (type $func))
)
```
That v128 is not used, but it ends up in the output because it is in a rec group that is used.
Atm we do not require that SIMD be enabled in such a case, which can trip up the fuzzer.
Context: https://github.com/WebAssembly/binaryen/pull/6820#discussion_r1719085970 For now, modify the test that uncovered this.

[NFC] Avoid v128 in rec groups with no other v128 uses

---

scripts/test/shared.py

Also we had a mix of `os.environ.get` and `os.getenv`. Prefer the former, as the default
value does actual work, so it's a little more efficient to not run it unnecessarily. That is,
`os.getenv('X', work())` is less efficient than `os.environ.get('X') or work()`.

Testing: Add an env var to pick the V8 binary

---

src/ir/gc-type-utils.h
src/ir/subtypes.h
src/passes/TypeMerging.cpp
src/passes/TypeSSA.cpp
src/passes/Unsubtyping.cpp
src/tools/fuzzing/fuzzing.cpp
src/tools/fuzzing/heap-types.cpp
src/tools/wasm-fuzz-types.cpp
src/wasm/wasm-binary.cpp
src/wasm/wasm-type.cpp

Replace code that checked `isStruct()`, `isArray()`, etc. in sequence
with uses of `HeapType::getKind()` and switch statements. This will make
it easier to find the code that needs updating if/when we add new heap
type kinds in the future. It also makes it much easier to find code that
already needs updating to handle continuation types by grepping for
"TODO: cont".

[NFC] Use HeapType::getKind more broadly

---

src/wasm/wasm-ir-builder.cpp
test/spec/shared-array.wast

IRBuilder is responsible for validation involving type annotations on GC
instructions because those type annotations may not be preserved in the
built IR to be used by the main validator. For `array.init_elem`, we
were not using the type annotation to validate the element segment,
which allowed us to parse invalid modules when the reference operand was
a nullref. Add the missing validation in IRBuilder and fix a relevant
spec test.

Validate array.init_elem segment in IRBuilder

---

src/ir/possible-contents.h

possible-contents.h hashes the location for caught exnrefs by hashing an
arbitrary string, "caught-exnref-location". It previously used
`std::hash<const char*>` for this, but some standard library
implementations report an error when this template instantiation is used
because hashing the location of a string is almost never correct. In
this case it is fine, so switch to using `std::hash<const void*>`.

[NFC] hash constant string as void*

---

src/passes/StringLowering.cpp
src/passes/pass.cpp
src/passes/passes.h
test/lit/help/wasm-metadce.test
test/lit/help/wasm-opt.test
test/lit/help/wasm2js.test
test/lit/passes/string-lowering.wast

The best way to lower strings is via the "magic imports" API that uses
the names of imported string globals as their values. This approach only
works for valid UTF-8 strings, though. The existing
string-lowering-magic-imports pass falls back to putting non-UTF-8
strings in a JSON custom section, but this requires the runtime to
support that custom section for correctness. To help catch errors early
when runtimes do not support the strings custom section, add a new pass
that uses magic imports and raises an error if there are any invalid
strings.

Add a string lowering mode disallowing non-UTF-8 strings

---

src/wasm/wasm-stack-opts.cpp

This is in quite ancient code, so it's a long-standing issue, but it got worse
when we enabled StackIR in more situations (#6568), which made it more
noticeable, I think.
For example, testing on `test_biggerswitch` in Emscripten, the LLVM part
is pretty slow too so the Binaryen slowdown didn't stand out hugely, but
just doing
`wasm-opt --optimize-level=2 input.wasm -o output.wasm`
(that is, do no work, but set the optimize level to 2 so that StackIR opts
are run) used to take 28 seconds (!). With this PR that goes down to less
than 1.

[NFC] Avoid quadratic time in StackIROptimizer::removeUnneededBlocks()

---

scripts/fuzz_opt.py
src/passes/Precompute.cpp

When precomputing fails on a child block of a parent block, there is no point
to precompute the parent, as that will fail as well.
At least, I can't think of any instruction sequence in wasm that could cause that
(see detailed comment in the code). I also fuzzed this (see second commit,
which is later reverted), and failed to find anything after a few thousand
iterations. But in theory this is not NFC if there is something that could be
optimized.
This makes `--precompute` on Emscripten's `test_biggerswitch` go from 1.44
seconds to 0.02 seconds (not a typo, that is 72x faster). The absolute number
is not that big, but we do run this pass more than once, so it saves a noticeable
chunk of time.

[NFC] Avoid quadratic time when precomputing blocks

---

scripts/test/shared.py
src/literal.h
src/parser/wast-parser.cpp
src/wasm-interpreter.h
src/wasm/literal.cpp

Spec tests use constants like `ref.array` and `ref.eq` to assert that
exported function return references of the correct types. Support more
such constants in the wast parser.
Also fix a bug where the interpretation of `array.new_data` for arrays
of packed fields was not properly truncating the packed data. Move the
function for reading fields from memory from literal.cpp to
wasm-interpreter.h, where the function for truncating packed data lives.
Other bugs prevent us from enabling any more spec tests as a result of
this change, but we can get farther through several of them before
failing. Update the comments about the failures accordingly.

Support more reference constants in wast scripts

---

src/wasm/wasm-validator.cpp
test/lit/validation/function-missing.wast

fix null dereference in FunctionValidator::visitBlock validateCallParamsAndResult

---

src/parser/wast-parser.cpp
test/lit/parse-bad-assertion.wast

The parser function for `action` returned a `MaybeResult`, but we were
treating it as returning a normal `Result` and not checking that it had
contents in several places. Replace the current `action()` with
`maybeAction()` and add a new `action()` that requires the action to be
present.
Fixes #6872.

Check for required actions when parsing wast

---

src/analysis/reaching-definitions-transfer-function.h
src/ir/LocalGraph.cpp
src/ir/local-graph.h
src/ir/possible-contents.cpp
src/passes/AvoidReinterprets.cpp
src/passes/Heap2Local.cpp
src/passes/LoopInvariantCodeMotion.cpp
src/passes/MergeLocals.cpp
src/passes/OptimizeAddedConstants.cpp
src/passes/Precompute.cpp
src/passes/SSAify.cpp
src/tools/wasm-fuzz-lattices.cpp
src/wasm/wasm-stack-opts.cpp
test/gtest/cfg.cpp

Before we just had a map that people would access with `localGraph.getSetses[get]`,
while now it is a call `localGraph.getSets(get)`, which more nicely hides the internal
implementation details.
Also rename `getSetses` => `getSetsMap`.
This will allow a later PR to optimize the internals of this API.
This is performance-neutral as far as I can measure. (We do replace a direct read
from a data structure with a call, but the call is in a header and should always get
inlined.)

[NFC] Refactor LocalGraph's core getSets API

---

scripts/fuzz_opt.py
scripts/test/shared.py

I had fp16 disabled locally using a hack. I removed it and now I need this to fix the fuzzer.
@brendandahl Should the fuzzer be working without this atm? Maybe I'm doing something wrong.

Add fp16 feature flag in V8 invocations

---

test/lit/lit.cfg.py

Previously for in-tree builds, they were put directly into test/, which
unnecessarily pollutes the tree.

Move lit test temporary files to out/test/

---

src/support/topological_orders.cpp
src/support/topological_orders.h
test/gtest/topological-orders.cpp

Reuse the code implementing Kahn's topological sort algorithm with a new
configuration that uses a min-heap to always choose the best available
element.
Also add wrapper utilities that can find topological sorts of graphs
with arbitrary element types, not just indices.

Add a utility for finding minimal topological sorts

---

src/passes/ReorderGlobals.cpp
src/support/topological_orders.cpp
src/support/topological_orders.h
test/gtest/topological-orders.cpp

Use the new TopologicalSort and MinTopologicalSortOf utilities instead
of the old CRTP topological sort utility and a bespoke heap-based
topological sort in ReorderGlobals. Since there is no longer a heap to
pop from, the direction of the custom comparator is now much more
intuitive.
Further simplify the code by switching from tracking the new order of
globals using a sequence of new indices to tracking the order using a
sequence of old indices.
This change also makes the pass about 20% faster on a large real-world
module.

Simplify ReorderGlobals using new topological sort utils

---

src/passes/ReorderGlobals.cpp
src/support/topological_orders.cpp
src/support/topological_orders.h
test/gtest/topological-orders.cpp

Previously they were structs and their results were accessed with
`operator*()`, but that was unnecessarily complicated and could lead to
problems with temporary lifetimes being too short. Simplify the
utilities by making them functions. This also allows the wrapper
templates to infer the proper element types automatically.

[NFC] Change topological sort utilities to functions

---

scripts/gen-s-parser.py
src/gen-s-parser.inc
src/ir/cost.h
src/literal.h
src/passes/Print.cpp
src/wasm-binary.h
src/wasm-interpreter.h
src/wasm.h
src/wasm/literal.cpp
src/wasm/wasm-binary.cpp
src/wasm/wasm-stack.cpp
test/lit/basic/f16.wast
test/spec/f16.wast

Specified at https://github.com/WebAssembly/half-precision/blob/main/proposals/half-precision/Overview.md
A few notes:
- The F32x4 and F64x2 versions of madd and nmadd are missing spect tests.
- For madd, the implementation was incorrectly doing `(b*c)+a` where it should be `(a*b)+c`.
- For nmadd, the implementation was incorrectly doing `(-b*c)+a` where it should be `-(a*b)+c`.
- There doesn't appear to be a great way to actually implement a fused nmadd, but the spec allows the double rounded version I added.

[FP16] Implement madd and nmadd.

---

src/passes/TranslateEH.cpp

This renames "delegate_br_target" to "delegate_trampoline". So how we translate `try`-`delegate` is:
- Before:
```wast
(try $delegate_target
...
(try
(do
...
)
(delegate $delegate_target)
)
...
)
```
- After:
```wast
(try_table $delegate_target
(throw_ref
(block $delegate_br_target
...
(try_table (catch_all $delegate_br_target)
...
)
...
)
)
)
```
So `delegate_br_target` is the destination we branch (via `try_table`) to, in order to rethrow the exnref using `throw_ref`.
But given that the translated code does not actually have a `br`, I think this name can be confusing.
This renames `br_target` to `trampoline`, given that the block is upon which we bounce the exnref off to reach the real delegate target.
This is to be consistent with the variable names in the LLVM implementation (which …

[EH] Rename BrTarget to Trampoline (NFC)

---

src/ir/local-graph.h
src/passes/Heap2Local.cpp
src/passes/MergeLocals.cpp
src/passes/OptimizeAddedConstants.cpp
src/passes/Precompute.cpp
src/passes/SSAify.cpp
src/passes/Souperify.cpp
src/wasm/wasm-stack-opts.cpp

This replaces direct access of the data structure `graph.*influences[foo]` with a call
`graph.get*influences(foo)`. This will allow a later PR to make those calls optionally
lazy.

[NFC] Convert LocalGraph influences accesses to function calls

---

src/wasm-binary.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-stack.cpp

This renames `Catch(All)_P3` enum to denote the old Phase 3 `catch(_all)` instructions to `Catch(All)_Legacy`, which sounds clearer.
This is also to be consistent with
https://github.com/llvm/llvm-project/pull/107187.

[EH] Rename Catch(All)_P3 to Catch(All)_Legacy (NFC)

---

src/passes/MinimizeRecGroups.cpp
src/passes/ReorderGlobals.cpp
src/support/topological_orders.h
test/gtest/topological-orders.cpp

This saves memory and could in principle improve performance, although a
quick experiment with 30 samples on ReorderGlobals did not yield a
statistically significant improvement. At any rate, using Index is more
consistent with other parts of the code base.

[NFC] Use Index instead of size_t in topological sort util

---

src/ir/module-utils.cpp
src/ir/module-utils.h

Many passes need to know both the set of all used types and also the
sets of private or public types. Previously there was no API to get both
at once, so getting both required two API calls that internally
collected all the types twice.
Furthermore, there are many reasons to collect heap types, and they have
different requirements about precisely which types need to be collected.
For example, in some edge cases the IR can reference heap types that do
not need to be emitted into a binary; passes that replace all types
would need to collect these types, but the binary writer would not. The
existing APIs for collecting types did not distinguish between these use
cases, so the code conservatively collected extra types that were not
always needed.
Refactor the type collecting code to expose a …

[NFC] Add a more powerful API for collecting heap types

---

src/ir/module-utils.cpp
test/example/c-api-kitchen-sink.txt
test/lit/basic/subtypes.wast
test/lit/isorecursive-good.wast
test/lit/passes/dae-gc-refine-return.wast
test/lit/passes/gufa-tnh.wast
test/lit/passes/gufa-vs-cfp.wast
test/lit/passes/optimize-instructions-gc.wast
test/lit/passes/precompute-partial.wast
test/lit/passes/simplify-locals-gc.wast

We previous incremented the use count for a declared supertype only if
it was also a type we had never seen before. Fix the count by treating
the supertype the same as any other type used in a type definition.
Update tests accordingly, including by manually moving input types
around to better match the output.

Fix supertype counts when collecting heap types

---

src/passes/MinimizeRecGroups.cpp
test/lit/passes/minimize-rec-groups.wast

As with all type optimizations, MinimizeRecGroups only changes private types,
which are the only types that are safe to modify. However, it is important for
correctness that MinimimizeRecGroups maintain separate type identities for all
types, whether public or private, to ensure that casts that should differentiate
two types cannot change behavior.
Previously the pass worked exclusively on private types, so there was nothing
preventing it from constructing a minimial rec group that happened to have the
same shape, and therefore type identity, as a public rec group. #6886 exhibits a
fuzzer test case where this happens and changes the behavior of the program.
Fix the bug by recording all public rec group shapes and resolve conflicts with
these shapes by updating the shape of the conflicting …

Avoid conflicts with public rec groups in MinimizeRecGroups

---

src/wasm/literal.cpp
test/spec/f16.wast

Before this change, replace lane was converting all the F16 lanes to F32 and then replacing one lane with the F16 (I32 representation) value, but it did not then convert all the other lanes back to F16 (I32). To fix this we can just leave the lanes as I32 and replace the one lane.
Note: Previous replace lane tests didn't catch this since they started with vectors with all zeros so the F32->I32 didn't matter. Also, other operations don't run into this issue since they iterate over all lanes and convert the F32's back to F16 (I32).

[FP16] Fix replace lane for F16x8.

---

src/ir/subtypes.h
src/ir/type-updating.cpp
src/support/old_topological_sort.h
src/tools/wasm-ctor-eval.cpp
src/wasm-type-ordering.h

This will allow both the old and new topological sort utilities to be included
into the same .cpp file while we phase out the old utility.

[NFC] Rename the old topological sort utility

---

src/ir/module-utils.cpp
src/passes/MinimizeRecGroups.cpp
src/passes/ReorderGlobals.cpp
src/support/topological_sort.h
test/gtest/CMakeLists.txt
test/gtest/topological-sort.cpp

Now that the header includes topological sort utilities in addition to the
utility that iterates over all topological orders, it makes more sense for it to
be named topological_sort.h

[NFC] Rename topological_orders.h to topological_sort.h

---

src/parser/wat-parser.h

This probably isn't the ideal solution but it did allow me to get binaryen building with gcc 14.2.
Fixes: https://github.com/WebAssembly/binaryen/issues/6779

Fix compilation under gcc 14.

---

src/ir/LocalGraph.cpp
src/ir/local-graph.h

Do not even construct the Flower helper class until we actually need it.
This avoids even scanning the function and building the internal CFG if
we never get any API call that needs it.
This speeds up LICM by 50% (as now we never construct the CFG if we
don't find a loop), and Stack IR-enabled binary writing by 10% (as many
functions do not have locals in positions that can be optimized using
LocalGraph).
This moves |locations| from the base class to LocalGraph. It is not
needed in the lazy version, so that makes sense for now (we can't keep
it in the base, as then it would need to be mutable, which only makes
sense for laziness).

[NFC] Make LazyLocalGraph even lazier

---

src/passes/LocalSubtyping.cpp
test/lit/passes/local-subtyping.wast

The LocalGraph there was used for two purposes:
1. Get the list of gets and sets.
2. Get only the reachable gets and sets.
It is trivial to get all the gets and sets in a much faster way, by just walking the
code as this PR does. The downside is that we also consider unreachable gets
and sets, so unreachable code can prevent us from optimizing, but that seems
worthwhile as many passes make that assumption (and they all become
maximally effective after --dce).
Removing LocalGraph + the fixup code for unreachability makes this
significantly shorter, and also 2-3x faster.

[NFC-ish] Remove LocalGraph from LocalSubtyping

---

src/pass.h
src/passes/CoalesceLocals.cpp
src/passes/CodeFolding.cpp
src/passes/DeadCodeElimination.cpp
src/passes/LogExecution.cpp
src/passes/LoopInvariantCodeMotion.cpp
src/passes/Memory64Lowering.cpp
src/passes/MemoryPacking.cpp
src/passes/MergeLocals.cpp
src/passes/MultiMemoryLowering.cpp
src/passes/OptimizeAddedConstants.cpp
src/passes/OptimizeInstructions.cpp
src/passes/Precompute.cpp
src/passes/RemoveUnusedBrs.cpp
src/passes/SignExtLowering.cpp
src/passes/SimplifyGlobals.cpp
src/passes/SpillPointers.cpp
src/passes/Table64Lowering.cpp
src/passes/TranslateEH.cpp
src/passes/TrapMode.cpp
src/passes/TupleOptimization.cpp
src/passes/TypeGeneralizing.cpp

As the name of a class, uppercase seems better here.
Context: https://github.com/WebAssembly/binaryen/pull/6897#discussion_r1744065962

[NFC] Standardize Super:: over super::

---

src/passes/Precompute.cpp

That is the slowest part of `--precompute-propagate`, which is one of our slowest
passes. This makes that pass 25% faster.
The main change is to make the maps consider missing elements as non-constant,
rather than storing a None element in them. That saves allocating entries for the
common case of a non-constant set/get.
Also switch to a simple vector for the work queue, which is possible if we only
add work when a get/set becomes constant (which can only happen once). Another
benefit to adding work in that manner is that we don't start by adding every single
get/set as "work" at the start.

[NFC] Optimize propagateLocals()

---

README.md

`wasm_of_ocaml` uses Binaryen's `wasm_as`, `wasm_merge` and `wasm_opt` as a part of its toolchain.

Add OCaml toolchain to binaryen readme

---

src/ir/type-updating.cpp
src/wasm/wasm-type.cpp
test/lit/passes/unsubtyping.wast

There are a few heap types that are hard-coded to be considered public
and therefore allowed on module boundaries even in --closed-world mode,
specifically to support js-string-builtins. We previously considered
both open and closed (i.e. final) mutable i8 arrays to be public in this
manner, but js-string-builtins only uses the closed versions, so remove
the open versions.
This fixes a particular bug in which Unsubtyping optimized a private
array type to be equivalent to an ignorable public array type,
incorrectly changing the behavior of a cast, but it does not address the
larger problem of optimizations producing types that are equivalent to
public types. Add a TODO about that problem for now.
Fixes #6935.

Remove open "ignorable public" array types

---

src/wasm-type.h
src/wasm/wasm-type.cpp

This just moves code around. As a result, `isRef()` vanishes entirely from the
profiling traces in #6931, since now the core `isRef/Tuple/etc.` methods are
all inlineable.
This also required some reordering of `wasm-type.h`, namely to move HeapType
up front. No changes to that class otherwise.
`TypeInfo` is now in the header. `getTypeInfo` is now a static method on `Type`.
This has the downside of moving internal details into the header, but it
doesn't seem that dangerous to me. Another downside is that it will add to
compile times of Binaryen itself. But this makes the `--precompute` benchmark
from #6931 significantly faster, 33%, so I think it is worth it.

[NFC] Move enough of wasm-type.cpp into wasm-type.h to inline core is*() methods

---

src/passes/GlobalStructInference.cpp
test/lit/passes/gsi.wast

We emit a select between two objects when only two objects exist of a particular
type. However, if the field is packed, we did not handle truncating the written
values.

Fix selects of packed fields in GlobalStructOptimization

---

src/ir/module-splitting.cpp
test/lit/wasm-split/minimized-exports.wast
test/lit/wasm-split/multi-split.wast

The module splitting utility has a configuration option for minimizing
new export names, but it was previously applied only to newly exported
functions. Using the new multi-split mode can produce lots of exported
tables and splitting WasmGC programs can produce lots of exported
globals, so minimizing these export names can have a big impact on code
size.

[wasm-split] Minimize non-function export names

---

src/literal.h
src/support/small_vector.h
src/wasm-interpreter.h
src/wasm/literal.cpp

This avoids creating a large Literals (SmallVector of Literal) and then copying it. All the places
that construct GCData do not need the Literals afterwards.
Also add a few other constructor type things, all as a result of C++ compiler errors after
the GCData constructor change.
This gives a 7% speedup on the `--precompute` benchmark from #6931

[NFC] Make the GCData constructor a move constructor

---

src/ir/module-utils.cpp
src/wasm/wasm.cpp
test/lit/passes/local-subtyping.wast

When a struct.get or array.get is optimized to have a null reference
operand, its return type loses meaning since the operation will always
trap. Previously when refinalizing such expressions, we just left their
return type unchanged since there was no longer an associated struct or
array type to calculate it from. However, this could lead to a strange
setup where the stale return type was the last remaining use of some
heap type in the module. That heap type would never be emitted in the
binary, but it was still used in the IR, so type optimizations would
have to keep updating it. Our type collecting logic went out of its way
to include the return types of struct.get and array.get expressions to
account for this strange possibility, even though it otherwise collected
only types that …

Improve types for null accesses and remove hacks

---

src/ir/possible-contents.cpp
src/ir/possible-contents.h

Before, a `br` would send its value to a `BreakTargetLocation`. That would then be
linked to the target:
```
{ br's value } => BreakTargetLocation(target name) => { location of target }
```
This PR skips the middle:
```
{ br's value } => { location of target }
```
It just connects breaks directly to the targets. We can do that if we keep a
map of the targets as we go.
This is 2% faster as well as simplifies the code, as an NFC refactoring. But it
also fixes a bug: we have handling on ExpressionLocation that filters values as they
come in (they must accord with the expression's type). We were not doing
that on BreakTargetLocation, leading to an assert. Removing
BreakTargetLocation entirely is easier and better than adding filtering logic
for it.
Fixes …

[NFC + bugfix] Remove BreakTargetLocation from GUFA

---

src/passes/OptimizeAddedConstants.cpp

This makes the pass 20% faster.

[NFC] Avoid collecting unnecessary parents in OptimizeAddedConstants

---

src/ir/module-utils.cpp
src/passes/Print.cpp
src/wasm-binary.h
src/wasm/wasm-binary.cpp
test/lit/binary/debug-bad-binary.test

In preparation for using IRBuilder in the binary parser, eagerly create
Functions when parsing the function section so that they are already
created once we parse the code section. IRBuilder will require the
functions to exist when parsing calls so it can figure out what type
each call should have, even when there is a call to a function whose
body has not been parsed yet.
NFC except that some error messages change to include the new empty
functions.

[NFC-ish] Eagerly create Functions in binary parser

---

src/passes/Inlining.cpp
src/passes/opt-utils.h

We already parallelized collecting info about functions and finding
inlining opportunities, but the actual inlining - copying the code into
the target function - was done sequentially. It turns out that a lot of
work happens there: this PR makes the pass over 2x faster.
Details:
* Move nameHint to InliningAction, so it is there when we apply the actions.
* Add a DoInlining internal pass which calls doInlining().
* Refactor OptUtils a little to make it easy to run DoInlining before opts.
* Also remove the return value of doInlining which was not used.

[NFC] Parallelize the actual inlining part of the Inlining pass

---

src/passes/Inlining.cpp
src/passes/opt-utils.h
test/lit/passes/inlining-optimizing_optimize-level=3.wast
test/lit/passes/inlining_optimize-level=3.wast

We may inline multiple times into a single function. Previously, if we did so, we
did the "fixups" such as ReFinalize and non-nullable local fixes once per such
inlining. But that is wasteful as each ReFinalize etc. scans the whole function,
and could be done after we copy all the code from all the inlinings, which is
what this PR does: it splits `doInlining()` into one function that inlines code and
one that does the updates after, and the update is done after all inlinings.
This turns out to be very important, a 5x speedup on a large real-world wasm
file I am looking at. The reason is that we actually inline more than once in
half the cases, and sometimes far more - in one case we inline over 1,000
times into a function! It is helpful to replaces 1,000 ReFinalizes with a single one... …

[NFC-ish] Avoid repeated ReFinalize etc. when inlining

---

src/ir/parents.h

This makes it slightly faster.
Followup to https://github.com/WebAssembly/binaryen/pull/6953#discussion_r1765313401

[NFC] Use an unordered map in Parents

---

src/passes/PickLoadSigns.cpp

In WasmGC modules there is often no memory at all, and we can skip
walking the code in this pass in such cases.

[NFC] Early-exit PickLoadSigns if there are no memories

---

src/passes/Inlining.cpp
test/lit/passes/inlining-eh-legacy.wast
test/lit/passes/inlining-unreachable.wast
test/lit/passes/inlining_all-features.wast
test/lit/passes/inlining_enable-tail-call.wast
test/lit/passes/inlining_optimize-level=3.wast
test/lit/passes/inlining_splitting.wast
test/lit/passes/inlining_splitting_basics.wast
test/lit/passes/no-inline-monomorphize-inlining.wast
test/lit/passes/no-inline.wast

Inlining was careful about nested calls like this:
```wat
(call $a
(call $b)
)
```
If we inlined the outer call first, we'd have
```wat
(block $inlined-code-from-a
..code..
(call $b)
)
```
After that, the inner call is a child of a block, not of a call. That is,
we've moved the inner call to another parent. To replace that
inner call when we inline, we'd need to update the new parent,
which would require work. To avoid that work, the pass simply
created a block in the middle:
```wat
(call $a
(block
(call $b)
)
)
```
Now the inner call's immediate parent will not change when we
inline the outer call.
However, it turns out that this was entirely unnecessary. We find
the calls using a post-order traversal, and we store the actions in
a vector that we traverse in order, so we only ever …

[NFC-ish] Stop creating unneeded blocks around calls when inlining

---

scripts/gen-s-parser.py
src/gen-s-parser.inc
src/ir/child-typer.h
src/ir/cost.h
src/literal.h
src/passes/Print.cpp
src/support/safe_integer.cpp
src/support/safe_integer.h
src/tools/fuzzing/fuzzing.cpp
src/wasm-binary.h
src/wasm-interpreter.h
src/wasm.h
src/wasm/literal.cpp
src/wasm/wasm-binary.cpp
src/wasm/wasm-stack.cpp
src/wasm/wasm-validator.cpp
src/wasm/wasm.cpp
test/lit/basic/f16.wast
test/spec/f16.wast

Note: FP16 is a little different from F32/F64 since it can't represent the full 2^16 integer range. 65504 is the max whole integer. This leads to some slightly strange behavior when converting integers greater than 65504 since they become infinity.
Specified at https://github.com/WebAssembly/half-precision/blob/main/proposals/half-precision/Overview.md

[FP16] Implement conversion operations.

---

src/passes/Print.cpp
src/wasm-interpreter.h
src/wasm.h

I found this useful in local debugging just now.

[NFC] Print type names in more places when logging

---

src/passes/Precompute.cpp
test/lit/passes/precompute-ref-func.wast

When we precompute something, we try to avoid allocating a new copy. That's important to
avoid many allocations each time we run Precompute - otherwise, each time we see a `br`
we'd allocate a fresh one, and for its values. But we had a bug where we reused a RefFunc
as the value of a `br` without updating the type. It's actually tricky to reach a situation where
we find a RefFunc to reuse and it is different from the actual one we want, but the fuzzer
found one.
Fixes the fuzz bug reported here: https://github.com/WebAssembly/binaryen/pull/6845#issuecomment-2377800299

Fix the type of reused RefFunc in Precompute

---

src/wasm/wasm-binary.cpp
test/unit/test_web_limitations.py

This raises the number of locals accepted by the binary parser to the absolute limit in the spec. A warning is now printed when writing a binary file if the Web limit of 50,000 locals is exceeded. This fixes #6968.

Binary parser: lift the limit on the number of locals

---

src/wasm-type.h
src/wasm/wasm-type.cpp

Some versions of libcxx or clang error without this, apparently due to Type
being a forward declaration.

[NFC] Move a TypeInfo constructor out of a header

---

scripts/fuzz_opt.py

The blocking bug https://issues.chromium.org/issues/332931390 has been fixed.
I fuzzed this for several hours now without seeing any issue.

Fuzz Wasm Exceptions in V8

---

src/passes/MergeBlocks.cpp
test/lit/passes/merge-blocks.wast

This just moves the code out into a function. A later PR will use it in another place.
Add a test that shows the motivation for that later PR: we fail to optimize away
a block return value at the top level of a function. Fixing that will involve calling
the new function here from another place.

[NFC] Refactor out the dropped-block optimization code in MergeBlocks

---

test/spec/f16.wast

0x7800 as FP16 is 32,768 not 32,767 as I had in the comment.
I also added another comment to explain the somewhat confusing behavior.

[FP16] Fix comment on f16x8.convert_i16x8_s test.

---

src/passes/RemoveUnusedBrs.cpp
test/lit/passes/remove-unused-brs-eh.wast

We ignored legacy Trys in #6980, but they can also catch.
Noticed by fuzzing with https://github.com/WebAssembly/binaryen/pull/6987

Fix a misoptimization with mixed Try/TryTable in RemoveUnusedBrs

---

src/passes/Flatten.cpp

This error makes #6989 less confusing.

Add explicit errors on unhandled instructions in Flatten

---

src/tools/fuzzing.h
src/tools/fuzzing/fuzzing.cpp
test/passes/translate-to-fuzz_all-features_metrics_noprint.txt

Also make Try/TryTables with type none, and not just concrete types as before.

Fuzzer: Generate TryTables

---

src/passes/RemoveUnusedBrs.cpp
test/lit/passes/remove-unused-brs-eh.wast

#6980 was missing the logic to reset flows after replacing a throw. The process
of replacing the throw introduces new code and in particular a drop, which
blocks branches from flowing to their targets.
In the testcase here, the `br` was turned into `nop` before this fix.

Fix a fuzz error due to throw => break opts in RemoveUnusedBrs

---

src/ir/branch-utils.h
test/lit/passes/gufa-refs.wast

BrOn does not always send a value. This is an odd asymmetry in the wasm
spec, where `br_on_null` does not send the null on the branch (which makes sense,
but the asymmetry does mean we need to special-case it).
Found by fuzzing with some BrOn additions that I will open a PR for later.

Fix BranchUtils::operateOnScopeNameUsesAndSentValues() on BrOn

---

src/passes/MergeBlocks.cpp
test/lit/passes/merge-blocks.wast
test/lit/passes/monomorphize-drop.wast
test/passes/Oz_fuzz-exec_all-features.txt
test/passes/merge-blocks.txt
test/passes/remove-unused-names_merge-blocks_all-features.txt

In #6984 we optimized dropped blocks even if they had unreachable code. In #6988
that part was reverted, and blocks with unreachable code were ignored once more.
However, I realized that the check was not actually for unreachable code, but for
having an unreachable child, so it would miss things like this:
```wat
(block
(block
..
(br $somewhere) ;; unreachable type, but no unreachable code
)
)
```
But it is useful to merge such blocks: we don't need the inner block here.
To fix this, just run ReFinalize if we change anything, which will propagate
unreachability as needed. I think MergeBlocks was written before we had
that utility, so it didn't use it...
This is not only useful for itself but will unblock an EH optimization in a
later PR, that has code in this form. It also simplifies the …

ReFinalize in MergeBlocks so we can optimize unreachable instructions too

---

src/passes/RemoveUnusedBrs.cpp
test/lit/passes/remove-unused-brs-eh.wast

This allows
```wat
(block $out (result i32)
(try_table (catch..)
..
(br $out
(i32.const 42)
)
)
)
=>
(block $out (result i32)
(try_table (result i32) (catch..)  ;; add a result
..
(i32.const 42)  ;; remove the br around the value
)
)
```

[Wasm EH] Optimize values flowing out of TryTable

---

src/wasm/wasm.cpp

Passing a constant string to functions requires memory allocation, and allocation is inherently slow. Since we are using C++17, we can use `string_view` and remove this unnecessary allocation.
Although the code seems simple enough for the optimizer to remove this allocation after inlining, tests on Clang 18 show that this is not the case (on Apple Silicon at least).
<details>
<summary>Assembly</summary>
Before:
```asm
wasm::Module::getFunction(wasm::Name):
sub	sp, sp, #64
stp	x20, x19, [sp, #32]
stp	x29, x30, [sp, #48]
add	x29, sp, #48
mov	w8, #11
strb	w8, [sp, #31]
mov	w8, #26996
movk	w8, #28271, lsl #16
stur	w8, [sp, #15]
Lloh143:
adrp	x8, l_.str.246@PAGE
Lloh144:
add	x8, x8, l_.str.246@PAGEOFF
Lloh145:
ldr	x8, [x8]
add	x0, x0, #480
str	x8, [sp, #8]
strb	wzr, [sp, #19]
add	x3, sp, #8
bl …
```

Optimize `Module::get_*` family of functions with `std::string_view` in `Module::getModuleElement`

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-gc-extern.wast

```wat
(any.convert_extern/extern.convert_any (ref.as_non_null ..))
=>
(ref.as_non_null (any.convert_extern/extern.convert_any ..))
```
This then allows the RefAsNonNull to be combined with parents in some cases
(whereas the reverse allows nothing).

[WasmGC] OptimizeInstructions: Reorder externalize/internalize operations with ref.as_non_null

---

src/passes/GlobalRefining.cpp
test/lit/passes/global-refining.wast

A mutable exported global might be shared with another module which
writes to it using the current type, which is unsafe and the type system does
not allow, so do not refine there.
Noticed while fuzzing wasm-split.

GlobalRefining: Do not refine mutable exported globals

---

src/passes/opt-utils.h

This can help find errors in the middle of passes like Inlining, that do
multiple cycles and include optimizations in the middle.

[NFC] Add validation checks in OptUtils::optimizeAfterInlining

---

src/ir/subtype-exprs.h
test/lit/passes/unsubtyping.wast

Similar to Break, BrOn, etc., we must apply subtyping constraints of the
types we send to blocks, so that Unsubtyping will not remove subtypings
that are actually needed.

[EH][GC] Add missing subtyping constraints from TryTable

---

src/passes/GlobalTypeOptimization.cpp
test/lit/passes/gto-removals.wast

TypeUpdater which it uses internally already does so, but we must also ignore
such types earlier, and make no other modifications to them.
Helps #7015

[GC] Ignore public types in GlobalTypeOptimization

---

src/passes/SignatureRefining.cpp
test/lit/passes/signature-refining.wast

Similar to https://github.com/WebAssembly/binaryen/pull/7017 and #7018

[GC] Ignore public types in SignatureRefining

---

scripts/fuzz_opt.py
scripts/fuzz_shell.js

The support is added but not enabled as this is still finding bugs, but I'd
like to land it now as it will conflict with other work I am doing.
The first part here is to add Split testcase handler to the fuzzer,
which runs a wasm, then runs it again after splitting it and then
linking it at runtime, and checking for different results.
The second part is support for linking two modules at runtime
in the fuzzer's JS code, that works in tandem with the first part.
New options are added to load and link a second wasm, and to
pick which exports to run.

wasm-split: Add fuzzer support

---

src/passes/GlobalTypeOptimization.cpp
test/lit/passes/gto-removals.wast

We only checked for the case of the immediate super being public while we
are private, but it might be a grandsuper instead. That is, any ancestor that
is public will prevent GTO from removing a field (since we can only add
fields on top of our ancestors).

[GC] Fix assertion in GlobalTypeOptimization about public super

---

src/passes/TypeMerging.cpp
test/lit/passes/type-merging.wast

TypeMerging works by representing the type definition graph as a partitioned DFA
and then refining the partitions to find mergeable types. #7023 was due to a bug
where the DFA included edges from public types to their children, but did not
necessarily include corresponding states for those children.
One way to fix the bug would have been to traverse the type graph, finding all
reachable public types and creating DFA states for them, but that might be
expensive in cases where there are large graphs of public types.
Instead, fix the problem by removing the edges from public types to their
children entirely. Types reachable from public types are also public and
therefore are not eligible to be merged, so these edges were never necessary for
correctness.
Fixes #7023.

Fix TypeMerging bug with indirectly reachable public types

---

src/passes/RemoveUnusedBrs.cpp
test/lit/passes/remove-unused-brs-gc.wast

Paradoxically, when a BrOn's castType is refined, its own type (the type it flows out)
can get *un*-refined: making the castType non-nullable means nulls no longer
flow on the branch, so they may flow out directly, making the BrOn nullable.

[GC] RemoveUnusedBrs: Ensure refining of BrOnCast's castType does not unrefine the output

---

src/ir/find_all.h
src/wasm.h

Make the ID enum an `int8_t`, and make the Specific ID a `constexpr`
of that type.
This seems more idiomatic and makes some code simpler, see the
change to `find_all.h` which no longer needs a cast to compile. It
will also simplify a future PR.
This seems to have no performance impact.
Is there maybe an even better C++ way to do this?

[NFC] Use more precise types for Expression IDs

---

src/tools/wasm-emscripten-finalize.cpp
test/lld/em_asm_pthread.wasm.out

This makes the behavior consistent with emcc builds where we don't run
finalization, and potentially makes testing and debugging easier.
Emscripten still strips the target features section when optimizing.

Don't strip target features in wasm-emscripten-finalize

---

src/wasm/wasm-validator.cpp

I believe that `table.fill` was introduced by the `reference-types` proposal and not by `bulk-memory`.
See [the proposal](https://github.com/WebAssembly/reference-types/blob/c7a3558bb5cbacb9c8879a91e08d0ac7276b740c/proposals/reference-types/Overview.md#:~:text=The%20new%20instruction%20table.fill%20fills,size%20%28analoguous%20to%20memory.fill%29).

Require reference-types instead of bulk-memory for `table.fill`

---

scripts/fuzz_opt.py
scripts/fuzz_shell.js
src/tools/execution-results.h
src/tools/fuzzing.h
src/tools/fuzzing/fuzzing.cpp
test/lit/exec/fuzzing-api.wast
test/passes/translate-to-fuzz_all-features_metrics_noprint.txt

Continues the work from #7027 which added throwing from JS, this adds
table get/set operations from JS, to further increase our coverage of
Wasm/JS interactions (the table can be used from both sides).

Fuzz the Table from JS

---

src/shell-interface.h
src/tools/wasm-ctor-eval.cpp
src/wasm-interpreter.h

The old code manually managed it for no good reason that I can see.
After this, there is no difference between `callFunction` and `callFunctionInternal`,
so fold them together.

[NFC] Use RAII to manage call depth tracking in the interpreter

---

src/ir/module-splitting.cpp
src/wasm/wasm.cpp

Emscripten's JS loader code for wasm-split isn't prepared for handling multiple tables that binaryen automatically creates when reference types are enabled (especially in conjunction with dynamic loading). For now, disable creation of multiple tables when using Emscripten's table ABI (distinguished by importing or exporting a table named "__indirect_function_table".

Module splitting: don't create new tables when splitting with Emscripten

---

src/passes/TypeSSA.cpp
src/support/hash.h

This is NFC on 64-bit systems but noticeable on 32.
Also remove the 32-bit path in `hash_combine`. That isn't necessary for this fix,
but it makes the code simpler and also makes debugging between systems
simpler. It might also avoid problems in future cases, if we are lucky. The only
cost is perhaps a slight slowdown on 32-bit systems, which seems worth it.
Fixes #7046

Make 32-bit hashing identical to 64-bit in TypeSSA

---

src/passes/GlobalTypeOptimization.cpp
test/lit/passes/gto-mutability.wast

This fixes a regression from #7019. That PR fixed an error on situations with
mixed public and private types, but it made us stop optimizing in valid cases,
including cases with entirely private types.
The specific regression was that we checked if we had an entry in the
map of "can become immutable", and we thought that was enough. But
we may have a private child type with a public parent, and still be able to
optimize in the child if the field is not present in the parent. We also did
not have exhaustive checking of all the states `canBecomeImmutable` can be,
so add those + testing.

[GC] Fix GlobalTypeOptimization logic for public types handling

---

src/wasm-binary.h
src/wasm/wasm-binary.cpp

This has not been emitted in LLVM since
https://github.com/llvm/llvm-project/commit/3f34e1b883351c7d98426b084386a7aa762aa366.
The corresponding proposed tool-conventions change:
https://github.com/WebAssembly/tool-conventions/pull/236

Remove FeaturePrefix::FeatureRequired (NFC)

---

scripts/j2cl.sh

J2CL runs a [long pipeline](https://github.com/google/j2cl/blob/e0dee1c7a726952c93d6ace95ddc39c7a6bcc74a/build_defs/internal_do_not_use/j2wasm_application.bzl#L4) of binaryen opts, including multiple invocations. This adds a
tool that simulates the same process manually, which can be easier to debug with
than running a full J2CL toolchain, which requires Bazel, etc. - this is just a few lines of
bash that does the same thing (at least in simple cases).

Add a J2CL compiler script

---

src/passes/ConstantFieldPropagation.cpp
test/lit/passes/cfp.wast

CFP is less precise than GUFA, in particular, when it flows around types then
it does not consider what field it is flowing them to, and its core data
structure is "if a `struct.get` is done on this type's field, what can be read?".
To see the issue this PR fixes, assume we have
```
A
/ \
B   C
```
Then if we see `struct.set $C`, we know that can be read by a `struct.get $A`
(we can store a reference to a `C` in such a local/param/etc.), so we propagate
the value of that set to `A`. And, in general, anything in `A` can appear in `B`
(say, if we see a copy, a `struct.set` of `struct.get` that operates on types `A`,
then one of the sides might be a `B`), so we propagate from `A` to `B`. But
now we have propagated something from `C` to `B`, which might be of an
incompatible type.
This cannot …

[GC] Fix ConstantFieldPropagation on incompatible types

---

scripts/fuzz_shell.js

The old code assumed the index was a JS number, but if the table has
64-bit indexes it must be a BigInt. Detect that and cast as needed.

[wasm64] Fuzzer: Fix table import operations on table64

---

src/shell-interface.h
src/tools/execution-results.h
src/tools/wasm-ctor-eval.cpp
src/wasm-interpreter.h
test/lit/exec/table64.wast

This allows 64-bit bounds checking to work properly.

[wasm64] Make interpreter table methods operate on Address, not Index

---

src/tools/fuzzing/fuzzing.cpp

When the fuzzer sees an imported segment, it makes it non-imported
(because imported ones would trap when we tried to run them: we don't
have the normal runtime they expect). We had hardcoded i32 offets there,
which need to be generalized.

[wasm64] Fuzzer: Fix type of unimported offsets

---

src/wasm-binary.h
src/wasm/wasm-binary.cpp

Instead of setting the local names at the end of binary reading, eagerly
set them before parsing function bodies. This is NFC now, but will fix a
future bug once the binary reader uses IRBuilder. IRBuilder can
introduce new scratch locals, and it gives them the names `$scratch`,
`$scratch_1`, etc. If the name section includes locals with the same
names and we set those local names after parsing function bodies, then
we can end up with multiple locals with the same names. Setting the
names before parsing the function bodies ensures that IRBuilder will
generate different names for the scratch locals.
The alternative fix would be to generate fresh names when setting names
from the name section, but it is better to respect the names in the name
section and use fresh names for the newly …

[NFC] Eagerly set local names in binary reader

---

src/wasm/wasm-binary.cpp
test/lit/passes/heap-store-optimization.wast
test/passes/dwarf-local-order.bin.txt
test/passes/fannkuch0_dwarf.bin.txt
test/passes/fannkuch3_dwarf.bin.txt
test/passes/fannkuch3_manyopts_dwarf.bin.txt
test/passes/reverse_dwarf_abbrevs.bin.txt

The binary reader has special handling for blocks immediately nested
inside other blocks to eliminate recursion while parsing very deep
stacks of blocks. This special handling did not record binary locations
for the nested blocks, though.
Add logic to record binary locations for nested blocks. This binary
reading code is about to be replaced with completely different code that
uses IRBuilder instead, but this change will eliminate some test
differences that we would otherwise see when we make that change.

Record binary locations for nested blocks

---

src/parser/parsers.h
src/support/result.h
test/gtest/local-graph.cpp

Since these types may be carrying errors that need to be handled or
propagated, it is always an error not to use them in some way. Adding
the [[nodiscard]] attribute caused the compiler to find a few instances
where we were incorrectly ignoring results. Fix these places.

Mark Result and MaybeResult [[nodiscard]]

---

src/wasm-ir-builder.h
src/wasm/wasm-ir-builder.cpp

Now that Result and MaybeResult are annotated [[nodiscard]] at the type
level, individual functions and methods that return these types do not
need to be annotated [[nodiscard]] themselves. Remove the newly
redundant annotations.

[NFC] Remove redundant [[nodiscard]] attributes

---

scripts/fuzz_opt.py

It is ok to use this pass to shape the wasm, but not to test for changes using
fuzz-exec, as the pass is destructive: it can alter observable behavior.

Fuzzer: Remove --enclose-world from list of fuzz-exec passes

---

scripts/fuzz_shell.js
test/lit/node/fuzz_shell.wast

This just moves the code around and avoids some duplication. It will make
later PRs simpler.
Also add a first test of running `fuzz_shell.js` in node.
edit: This does make `build()` append the exports, which was done before
on the main module but not the second one. That only affects the wasm-split
fuzzer, which is not active yet, so this is still NFC.

[NFC] Refactor nice methods in fuzz_shell.js

---

src/passes/Print.cpp
test/lit/wat-kitchen-sink.wast

br_on_cast and br_on_cast_fail have two type annotations: one for their
input type and one for their cast type. In cases where their operands
were unreachable, we were previously printing "unreachable" for the
input type annotation. This is not valid wat because "unreachable" is
not a reference type.
To fix the problem, print the bottom type of the cast type's hierarchy
as the input type for br_on_cast and br_on_cast_fail when the operand is
unreachable. This ensures that the instructions have the most precise
possible output type according to Wasm typing rules, so it maximizes the
number of contexts in which the printed instructions are valid.

Fix printing of unreachable br_on_cast{_fail}

---

src/ir/module-utils.cpp
test/lit/passes/type-refining.wast

Previously the classification of public types propagated public
visibility only through types that had previously been collected by
`collectHeapTypes`. Since there are settings that cause
`collectHeapTypes` to collect fewer types, it was possible for public
types to be missed if they were only public because they were reached by
an uncollected types.
Ensure that all public heap types are properly classified by propagating
public visibility even through types that are not part of the collected
output.
Fixes #7103.

Propagate public visibility through all types

---

src/passes/Print.cpp
test/lit/wat-kitchen-sink.wast

Since Load expressions use their `type` field to encode the type of the
loaded value, unreachable loads need to come up with some other valid
type to print. Previously we always chose i32 as that type, but that's
not valid when the load was originally a v128 load with an alignment of
8, since 8 is greater than the maximum valid alignment of 4 for an i32.
Fix the problem by taking alignment into account when choosing a type
for the unreachable load.

Print unreachable loads with valid types

---

src/passes/Print.cpp
test/lit/wat-kitchen-sink.wast

I forgot that there is a validation rule that the output type for
br_on_cast and br_on_cast_fail must be a subtype of the input type. We
were previously printing bottom input types in cases where the cast
operand was unreachable, but that's only valid if the cast type is the
same bottom type. Instead print the most precise valid input type, which
is the cast type itself.

Print castType for unreachable br_on_cast{_fail}

---

scripts/test/wasm2js.py

--emscripten is added to the command line if the filename contains the string
'emscripten', but the current logic includes the cwd, so it fails if the tests
are run from a directory with 'emscripten' in the name. Fix it so the test only
includes the basename.

[tests] Fix wasm2js test command line generation

---

src/mixed_arena.h
test/gtest/CMakeLists.txt
test/gtest/arena.cpp

This was never right for over a decade, and just never used I suppose... it should
have been called "take" since it grabbed data from the other item and then set
that other item to empty. Fix it so it swaps properly.

Fix ArenaVector::swap

---

.github/workflows/ci.yml
src/wasm-interpreter.h
test/lit/exec/array.wast

Even if the size is 0, if the offset is > 0 then we should trap.
@tlively Is it expected there are no spec tests for this combination of GC+bulk memory?

[GC] Fix trapping on array.new_data of dropped segments of offset > 0

---

src/ir/module-utils.cpp
src/parsing.h
src/passes/DebugLocationPropagation.cpp
src/passes/Print.cpp
src/source-map.h
src/tools/wasm-dis.cpp
src/wasm-binary.h
src/wasm-stack.h
src/wasm.h
src/wasm/CMakeLists.txt
src/wasm/parsing.cpp
src/wasm/source-map.cpp
src/wasm/wasm-binary.cpp
src/wasm/wasm-io.cpp
src/wasm/wasm-ir-builder.cpp
src/wasm/wasm-stack.cpp
src/wasm/wasm.cpp
test/gtest/CMakeLists.txt
test/gtest/source-map.cpp

Move all state relevant to reading source maps out of WasmBinaryReader
and into a new utility, SourceMapReader. This is a prerequisite for
parallelizing the parsing of function bodies, since the source map
reader state is different at the beginning of each function.
Also take the opportunity to simplify the way we read source maps, for
example by deferring the reading of anything but the position of a debug
location until it will be used and by using `std::optional` instead of
singleton `std::set`s to store function prologue and epilogue debug
locations.

[NFC] Encapsulate source map reader state

---

scripts/fuzz_opt.py
src/tools/fuzzing.h
src/tools/fuzzing/fuzzing.cpp
src/tools/wasm-opt.cpp

This sends `--closed-world` to `wasm-opt` from the fuzzer, when we use that
flag (before we just used it on optimizations, but not fuzz generation). And
TranslateToFuzzReader now stores a boolean about whether we are in closed-
world mode or not.
This has no effect so far, but will be needed in a later PR, where we must
generate code differently based on whether we are in closed-world mode
or not.

[NFC] Send the closed-world flag to TranslateToFuzzReader

---

src/wasm/wasm-binary.cpp

When we refactored how the name section is read, we accidentally left an
old warning about invalid field name indices in place. The old warning
code compares the type index from the names section to the size of the
parsed type vector to determine if the index is out-of-bounds. Now that
we parse the name section before the type section, this is no longer
correct. Delete the old warning; we already have a new, correct warning
for out-of-bound indices when we parse the type section.

Remove incorrect warning when reading name section

---

src/passes/TypeRefining.cpp
test/lit/passes/gto_and_cfp_in_O.wast
test/lit/passes/type-refining.wast

If we see a StructGet with no content (the type it reads from has no writes)
then we can make it unreachable. The old code literally just changed the type
to unreachable, which would later work out with refinalization - but only if
the StructGet's ref was unreachable. But it is possible for this situation to
occur without that, and if so, this hit the validation error "can't have an
unreachable node without an unreachable child".
To fix this, merge all code paths that handle "impossible" situations, which
simplifies things, and add this situation.

[GC] Fix TypeRefining on StructGets without content but with a reachable ref

---

src/wasm/wasm-type.cpp

Co-locate the declaration and implementation of TypeGraphWalkerBase and
its subtypes in wasm-type.cpp and simplify the implementation. Remove
the preVisit and postVisit tasks for both Types and HeapTypes since
overriding scanType and scanHeapType is sufficient for all users. Stop
scanning the HeapTypes in reference types because a follow-on change
(#7142) will make that much more complicated, and it turns out that it
is not necessary.

[NFC] Simplify TypeGraphWalker in wasm-type.cpp

---

scripts/fuzz_opt.py

The new `Two` fuzz testcase handler generates two wasm files and
then runs them in V8, linking them using JS. It then optimizes at least one of
the two and runs it again, and checks for differences.
This is similar to the `Split` fuzzer for `wasm-split`, but the two wasm files
are arbitrary and not the result of splitting.
Also lower CtorEval priority a little. It is not very important.

Fuzz combinations of two modules

---

src/tools/execution-results.h
test/lit/exec/fuzzing-api.wast

Execution results: JS traps on exnref on the boundary

---

src/tools/wasm-reduce.cpp
test/lit/help/wasm-reduce.test

With this option, each time we reduce we save a file `w.wasm.17` or such,
incrementing that counter. This is useful when debugging the reducer, but
might have more uses.

[wasm-reduce] Add an option to save all interim working files as we reduce

---

src/passes/RemoveUnusedBrs.cpp
test/lit/passes/remove-unused-brs.wast

We normally like to move brs after ifs into the if, when in a loop:
```wat
(loop $loop
(if
..
(unreachable)
(code)
)
(br $loop)
)
=>
(loop $loop
(if
..
(unreachable)
(block
(code)
(br $loop) ;; moved in
)
)
)
```
However this may be invalid to do if the if condition is unreachable, as
then one arm may be concrete (`code` in the example could be an `i32`,
for example). As this is dead code anyhow, leave it for DCE.

RemoveUnusedBrs: Avoid an error on loops with unreachable ifs

---

src/passes/Heap2Local.cpp
test/lit/passes/heap2local.wast

Heap2Local replaces gets and sets of non-escaping heap allocations with
gets and sets of locals. Since the accessed data does not escape, it
cannot be used to directly synchronize with other threads, so this
optimization is generally safe even in the presence of shared structs
and atomic struct accesses. The only caveat is that sequentially
consistent accesses additionally participate in the global ordering of
sequentially consistent operations, and that effect on the global
ordering cannot be removed. Insert seqcst fences to maintain this global
synchronization when removing sequentially consistent gets and sets.

Handle atomic accesses in Heap2Local

---

scripts/fuzz_opt.py
test/unit/test_cluster_fuzz.py

1. Error on retrying due to a `wasm-opt` issue, locally (in production, we
don't want to error on ClusterFuzz).
3. Move some asserts from `test_run_py` to the helper `generate_testcases`
(so that the asserts happen in all callers).

[NFC] Improve ClusterFuzz testing

---

CMakeLists.txt

This handles the case where WASM_BIGINT is enabled by default by emcc.
Binaryen's JS bindings do not currently work with bigint (see #7163)

Explicitly disable WASM_BIGINT in emcc build when the CMake flag is off

---

scripts/fuzz_opt.py
scripts/test/fuzzing.py
scripts/test/shared.py

The list of tests, and which tests cannot be fuzzed, will be useful in
a future PR that uses it for ClusterFuzz as well. This just moves things
out so they are reusable.

[NFC] Move code from fuzz_opt.py to a shared place

---

src/ir/properties.h
src/passes/GUFA.cpp
test/lit/passes/gufa-refs.wast

Conservatively avoid introducing synchronization bugs by not optimizing
atomic struct.gets at all in GUFA. It is possible that we could be more
precise in the future.
Also remove obsolete logic dealing with the types of null values as a
drive-by. All null values now have bottom types, so the type mismatch
this code checked for is impossible.

Do not optimize atomic gets in GUFA

---

src/passes/GlobalStructInference.cpp
test/lit/passes/gsi.wast

GlobalStructInference optimizes gets of immutable fields of structs that
are only ever instantiated to initialize immutable globals. Due to all
the immutability, it's not possible for the optimized reads to
synchronize with any writes via the accessed memory, so we just need to
be careful to replace removed seqcst gets with seqcst fences.
As a drive-by, fix some stale comments in gsi.wast.

Update GlobalStructInference to handle atomics

---

src/support/string.cpp

The coverage CI builder was failing because of a spurious error about a
variable being possibly used uninitialized. Fix the warning by
initializing the variable to 0.

[NFC] Fix spurious uninitialized variable warning

---

src/wasm-io.h

We always use the new WAT parser now.

[NFC] Remove unused `useNewWATParser` bool

---

src/passes/CoalesceLocals.cpp

This may have been used in the past somehow, but no longer is.

[NFC] Remove some unused code

---

src/tools/fuzzing/fuzzing.cpp

Emitting that in e.g. a global init is not going to validate, so avoid doing so,
and continue to the code below, which may manage to emit something in
this case.

Fuzzing: Do not emit RefAsNonNull in non-function contexts

---

CHANGELOG.md
src/wasm/wasm-validator.cpp
test/lit/validation/gc-atomics.wast

Without this, it is invalid to lower them to simpler atomic operations like
`atomic.fence` (as some passes do) or linear memory atomics (as a future
lowering pass might do).
Fixes #7184

[GC][Threads] Atomic GC operations require --enable-threads

---

scripts/fuzz_opt.py
scripts/fuzz_shell.js

If the module has an invalid segment offset, for example, it will error. We
should not error in the fuzzer on such rare cases.
Also add logging of the actual error, which matches what we do for
errors elsewhere, and makes debugging easier:
https://github.com/WebAssembly/binaryen/blob/dcec348ded6d7ab7bf4b758bdb92107e4262dbf4/scripts/fuzz_shell.js#L397
As a result another place needs to look for the prefix now, and not the
entire string (since we append the error contents).

Fuzzing: Handle instantiation errors in ClusterFuzz

---

src/passes/CMakeLists.txt
src/passes/RemoveMemoryInit.cpp
src/passes/pass.cpp
src/passes/passes.h
src/tools/wasm-reduce.cpp
test/lit/help/wasm-metadce.test
test/lit/help/wasm-opt.test
test/lit/help/wasm2js.test
test/lit/passes/remove-memory-init.wast
test/passes/remove-memory.txt
test/passes/remove-memory.wast

Also rename it to RemoveMemoryInit to make it more clear what it's for.
For now, keep the legacy pass name, to be deleted after rolling into Emscripten.

Make RemoveMemory pass also remove the start function

---

src/wasm/wasm-validator.cpp
test/unit/test_features.py

We previously checked only for the multivalue feature when used by
blocks, but now check for all used features. This will fix a current
fuzzer error where the new unreachable-string-new.wast test validates
with shared-everything disabled even though it uses shared heap types,
allowing the fuzzer to use those shared types in other places that are
checked by the validator.

Validate features used by block return types

---

scripts/fuzz_opt.py

wasm2js renames exports to js-valid names. That difference can be noticeable
when we compare it to the original names, so fix that up.
This must land before #7198: that PR adds more invokes, including invokes of
imports, whose names can be modified by wasm2js.

Fuzzing: Ignore differences in names that wasm2js fixes up

---

src/wasm2js.h

This code wrote to `export_name` but it was never used. I guess we forgot
to remove it when we updated the name mangling there.

[NFC] Remove some dead code in wasm2js

---

src/tools/fuzzing/fuzzing.cpp
test/passes/fuzz_metrics_noprint.bin.txt
test/passes/fuzz_metrics_passes_noprint.bin.txt
test/passes/translate-to-fuzz_all-features_metrics_noprint.txt

This adds more of a chance to call code from initial content. This includes
invokes of function imports, which we didn't do before.

Fuzzer: Add invokes for initial functions

---

scripts/fuzz_opt.py

This is needed for the same reasons as log-*. I believe no other import needs
fixing, as they require features not supported in wasm2js (like reference types
for table operations).

wasm2js fuzzing: Fix up call-* import names

---

scripts/fuzz_shell.js
scripts/wasm2js.js
test/lit/node/fuzz_shell_numeric_export.wast

JS sorts such indexes to the start of `wasm.exports`, but we want the order in
the wasm, so get the proper ordering using `WebAssembly.Module.exports`.

Fuzzing: Fix fuzz_shell.js on exports whose name is an integer

---

scripts/test/fuzzing.py

The interpreter does not yet support the struct RMW ops, so this test
file cannot be fuzzed.

Do not fuzz gc-atomics.wast

---

src/tools/fuzzing/fuzzing.cpp

We may move a rethrow into an invalid position when we `mutate()` etc. This finds
such invalid rethrows and replaces them with something trivial so that we validate.

Fuzzer: Fix up rethrows after changes

---

scripts/test/shared.py
src/wasm/wasm-ir-builder.cpp
test/lit/basic/extra-branch-values.wast

Now that we support sending additional values on these branches, we can
run their spec tests, so enable them. Also fix a bug with block naming
that the spec tests exposed.
We still cannot run the br_on_cast and br_on_cast fail spec tests, but
update the relevant comments to describe the new reason they fail.

Enable br_on_null and br_on_non_null spec tests

---

scripts/test/fuzzing.py

We warn on that, saying we don't support it, which is both an error in the
fuzzer but also means it isn't useful to fuzz.
Fixes https://github.com/WebAssembly/binaryen/pull/7212#issuecomment-2590839205

Fuzzer: Ignore tests with the linking section

---

scripts/fuzz_opt.py

Apparently we have some exports that need escaping in their names, and
we should not escape them twice.

Fuzzer: Fix escaping of wasm-ctor-eval names

---

src/passes/SignatureRefining.cpp
test/lit/passes/signature-refining.wast

Now that we preserve tag heap types in the IR, it was possible for
SignatureRefining to refine heap types used by tags in such a way that
the tag uses would no longer be valid. An ideal fix would be to have
SignatureRefining analyze and optimize tag usage as well as calls, but
for now just skip optimizing any heap type used in a tag.

Do not optimize tag types in SignatureRefining

---

README.md

The next level `*` should have two spaces indentation from the previous level. Currently the sentences under `Reference Types` have only one, making them appear in the same level in the markdown format.

Fix indentations in README.md

---

src/passes/GlobalTypeOptimization.cpp
test/lit/passes/gto-removals.wast

#6950 would have fixed this but we decided it was too risky/complex for
now. Meanwhile I see this on the fuzzer now and then, so let's fix this
directly.

[EH] Fix nested pops when GTO removes a GC operation

---

CMakeLists.txt

For some reason CMake is now using the clang-style version of the flag (i.e. `-MD`
instead of `/MD`) to choose the runtime so this manual flag scrubbing no longer
works. Now that we are depending on CMake newer than version 3.15 we can use
its builtin support for choosing the MSVC runtime.

Use CMAKE_MSVC_RUNTIME_LIBRARY to choose MSVC CRT

---

scripts/fuzz_shell.js
test/lit/d8/fuzz_shell_sleep.wast

Rather than return a promise, it returns an integer immediately.
@brendandahl I believe this implements the idea you mentioned recently?

JSPI: Add a chance for sleep() to not actually sleep

---

.flake8
.github/workflows/ci.yml
.gitignore
.gitmodules
CMakeLists.txt
check.py
test/gtest/CMakeLists.txt
test/gtest/type-builder.cpp
test/gtest/type-domains.cpp
test/gtest/type-domains.h
test/gtest/type-test.h
third_party/CMakeLists.txt

FuzzTest is a state-of-the-art fuzzing framework. It supports writing
property-based fuzz targets very similar to googletest unit tests, where
the framework provides the arguments to the test function drawn from a
given domain. These fuzz tests are run continuously for one second each
when running the normal googletest unit tests, but FuzzTest also
supports building in "fuzzing mode" where the tests can be run
continuously with coverage-guided mutations until they find a bug.
Add FuzzTest as a third_party dependency that is not built by default.
To build FuzzTest and the fuzz tests that use it, set the CMake variable
`BUILD_FUZZTEST=ON`. To build in fuzzing mode, additionally set the
CMake variable `FUZZTEST_FUZZING_MODE=ON`.
One of FuzzTest's key features is its support for domain …

Add FuzzTest and use it to fuzz types

---

src/parser/parsers.h
test/lit/parse-bad-optional-memidx.wast

We previously asserted that the end of a nested expression is the same
when we parse it with a null context just to find its children and when
we parse it for real. It turns out that it is possible for the two end
positions to be different when the instruction is invalid in a way that
only the real parse catches. Return a normal error instead of asserting
because it is possible for invalid input to trigger this condition.
Fixes #7251.

Fix a text parser assertion on bad immediates

---

src/wasm/wasm-ir-builder.cpp
test/lit/parse-error-return-nofunc.wast

Without this we get an assertion later on,
```
child-typer.h:720:  Assertion `func' failed.
```
Returns use the function to find the return values, so like local
get and set, we must error early on lacking a function.

Properly error on a return in a non-function scope

---

src/interpreter/interpreter.cpp
test/gtest/interpreter.cpp

Building on top of #7227, i32.sub is implemented and tested.

[Interpreter] i32.sub

---

.github/workflows/create_release.yml

This was supposed to be part of #7258

[ci] Attempt to fix create_release for arm64 linux

---

.github/workflows/create_release.yml

Hopefully this will fix the current failure:
```
Run actions/setup-python@v1
with:
python-version: 3.x
architecture: x64
Error: Version 3.x with arch x64 not found
```

[ci] Bump setup_python version in create_release.yml

---

src/parser/contexts.h
test/lit/parse-bad-tuple-in-sig.wast

Without this, we reach an assertion when we construct the Type for the
params or results, as Types accept lists with single values only.

Parser: Error on tuples in signatures

---

.github/workflows/ci.yml

This should really be the default shouldn't it?

[ci] Cancel CI jobs when new commits are added to a PR

---

src/tools/fuzzing.h
src/tools/fuzzing/fuzzing.cpp

We generate a `throw_ref` by generating an exnref for it to throw. To avoid that
causing lots of traps due to not having an exnref, add some logic to generate
an exnref (by making a try that throws and catches).

Fuzzer: Generate ThrowRef, and avoid unneeded traps with it

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-struct-rmw.wast

We previously reasoned that RMWs that do not change in-memory values
could be optimized to just atomic gets because they did not necessarily
synchronize with subsequent atomic reads of the same location. This is
not correct for seqcst RMWs, though, since subsequent seqcst reads in
the total order of seqcst operations are _required_ to read from and
synchronize with these RMWs, even though they do not change the
in-memory values. Fix the optimization to only work on acquire-release
RMWs and RMWs to unshared memory.

Fix optimization of seqcst RMWs in OptimizeInstructions

---

src/ir/possible-contents.cpp
test/lit/passes/gufa-cast-all.wast

When a tag is imported or exported, it might be written to (an exception thrown
with a value in the tag) from the outside, so we should not assume it is
unreachable.

GUFA: Fix handling of public tags

---

src/passes/LegalizeJSInterface.cpp
test/lit/passes/legalize-and-prune-js-interface.wast

Like v128, JS VMs will trap on an exnref on the boundary between JS and wasm,
so the fuzzer must prune such exports (we run that pruning when we intend
to compare d8 to the binaryen interpreter; after the pruning, all exports should
behave the same between those VMs).

[EH] Prune exnref-returning/receiving exports

---

src/tools/fuzzing/fuzzing.cpp
src/tools/fuzzing/heap-types.cpp
test/lit/fuzz-types.test
test/passes/translate-to-fuzz_all-features_metrics_noprint.txt

Most of the work here is avoiding shared and non-nullable exnref in
various places, as we cannot support those in the fuzzer (I don't see
a way to generate shared exnrefs, and non-nullable ones can be
created but not in global places, as the way to create them needs a
block and a try).
Some example output:
```wat
(type $0 (struct (field (mut exnref)) (field (mut i64)) (field (mut v128))))
(type $1 (sub (struct (field (ref null $1)) (field (mut i16)) (field (mut exnref)) (field (ref struct)))))
(type $3 (sub final $1 (struct (field (ref null $3)) (field (mut i16)) (field (mut exnref)) (field (ref $2)))))
```

[GC][EH] Fuzz exnref in GC structs

---

src/tools/fuzzing/fuzzing.cpp
test/passes/fuzz_metrics_noprint.bin.txt
test/passes/fuzz_metrics_passes_noprint.bin.txt
test/passes/translate-to-fuzz_all-features_metrics_noprint.txt

In the earlier days of the fuzzer we would call `makeUnary` with unreachable
sometimes, and then emit an unreachable `i32.eqz` for example. Later we
added `mutate()` which randomly emits unreachable into places, which gives
even better coverage - no need to manually handle unreachability in every
single instruction. This PR removes the old form.
Also remove the "Important" label from `makeUnreachable`. The
unreachable instruction is now one of many that have that type, and we
have no reason to prefer it to others.
These changes have the effect of improving the chance to emit interesting
instructions with unreachable type, like `throw, throw_ref`.

Fuzzer: Simplify and improve emitting of unreachable code

---

src/tools/fuzzing.h
src/tools/fuzzing/fuzzing.cpp

When we need an exnref value we may create a try-catch with a throw (so
when we catch it, we get an exnref). But if the exception tag contains an
exnref, then we will try to create another exnref in the throw, leading to
recursion (possibly infinite). To avoid this, just create a trivial tag with no
values when we just want a trivial value.

[EH] Fuzzer: Fix infinite loop with nested exnrefs

---

scripts/fuzz_opt.py
scripts/test/shared.py

Recent v8 prints "warning: unrecognized flag" about it.
This warning broke a test. Add some logging to the test as well, to make it
easier to debug in the future.

[NFC] Remove no longer needed v8 flag to avoid warnings

---

scripts/fuzz_shell.js
test/lit/d8/fuzz_shell_exceptions.wast

We have a test
```js
try {
..
} catch (e) {
e.a; // must be valid
}
```
That test will catch various wasm exception issues, but it turns out that it
also fails on one specific JS exception: null. It is ok to do `e.a` on numbers,
objects, anything really, all except for null. This PR adds a guard for that.

Fuzzer: Fix handling of JS null exceptions

---

src/ir/memory-utils.h
src/passes/LimitSegments.cpp
test/lit/passes/custom-max-data-segments.wast

Related to #7229.
The custom limit can be passed by doing `--pass-arg=limit-segments@1024 `.
I didn't commit a unit test because I don't think it's necessary to add one, but I wrote one to test everything works:
```diff --git a/test/unit/test_memory_packing.py b/test/unit/test_memory_packing.py
index e2468e689..42e696421 100644
--- a/test/unit/test_memory_packing.py
+++ b/test/unit/test_memory_packing.py
@@ -40,3 +40,19 @@ class MemoryPackingTest(utils.BinaryenTestCase):
self.assertEqual(p.returncode, 0)
self.assertIn('Some VMs may not accept this binary', p.stderr)
self.assertIn('Run the limit-segments pass to merge segments.', p.stderr)
+
+    def test_limit_segments_arg(self):
+        max_data_segments = 1024
+        data = '\n'.join('(data (i32.const %i) "A")' % i for i in …
```

Customize the limit of MaxDataSegments

---

scripts/fuzz_opt.py

This avoids the annoying experience of seeing ClusterFuzz block for
many seconds as you watch the fuzzer begin to run.

[NFC] Run ClusterFuzz only after some time has passed

---

src/ir/cost.h
test/lit/passes/monomorphize-benefit.wast
test/lit/passes/remove-unused-brs-gc.wast

VM feedback suggests that `struct.new` etc. should be avoided when we
selectify, as the cost is high even in generational GC implementations.

Adjust the cost of allocations to a much higher value

---

src/passes/ConstantFieldPropagation.cpp
test/lit/passes/cfp-rmw.wast
test/lit/passes/cfp.wast

ConstantFieldPropagation previously reasoned that if a field has a
constant value, then it is not possible for release-acquire operations
to use it for synchronization, since the read can be assumed to be from
a previous write. This logic was incorrect because reads must read the
value written by the last write in the global modification order for the
accessed location.
In principle it would be possible for CFP to detect fields that have
both constant values and also either no acquire reads or no release
writes. Such fields cannot possibly be part of synchronization edges and
their gets could be optimized normally. For now though, simply do not
optimize any gets with acquire or seqcst ordering. Similarly, stop
optimizing RMW operations because they can also form synchronization
edges.

Fix CFP to avoid removing synchronization

---

src/parser/lexer.h
src/parser/wat-parser.cpp
src/parser/wat-parser.h
src/wasm/wasm-io.cpp
test/lit/parse-bad-optional-memidx.wast
test/lit/parse-bad-supertype-8616.wast
test/lit/parse-bad-supertype.wast
test/lit/parse-bad-tuple-extract-index.wast
test/lit/parse-bad-tuple-in-sig.wast
test/lit/parse-error-func-param-type.wast
test/lit/parse-error-return-nofunc.wast
test/lit/parse-error.wast

This is especially useful with `wasm-merge` which takes several file as inputs.

WAT parser: include file name in error messages

---

src/tools/fuzzing.h
src/tools/fuzzing/fuzzing.cpp
test/passes/fuzz_metrics_noprint.bin.txt
test/passes/fuzz_metrics_passes_noprint.bin.txt
test/passes/translate-to-fuzz_all-features_metrics_noprint.txt

Previously we would create a function and then immediately modify it in
interesting ways (replace code, move code around, etc.). We also modified any
initial functions (in the content we are given to build on top of) at the very
start. That was simple, by modifying later we can get some benefits. This PR
makes us work in a loop:
```python
while more:
if random:
add function
else
modify some random function previously added
```
This lets us unify the modification code to one place (rather than have it
separate for initial functions and for created functions). Also, by modifying
late, we can end up with calls from early functions to late ones, as we may
create A and B before modifying A, and end up mutating something into a call to
B. Previously we never had such forward calls.
For such …

Fuzzer: Modify functions late

---

.github/workflows/create_release.yml

This may be a case of if its not broke, don't fix it, but the checkout action used in the release workflow is very old (and I'm slightly surprised it works). This PR updates to the latest version of the action, making it consistent with the main ci workflow here https://github.com/WebAssembly/binaryen/blob/83c82e56172506572098cbc590e7b0b0d6edcd1f/.github/workflows/ci.yml#L29 .

[ci] Update checkout action in create_release.yml to v4

---

src/tools/fuzzing/fuzzing.cpp

If the initial wasm we are fuzzing with had an export, then some of
the time add more code in that export, interposing before the
usual code:
```wat
(func $foo (export "bar") (result i32)
(..code..)
)
=>
(func $foo (export "bar") (result i32)
(call $something) ;; new code
(..code..)
)
```
We interpose by inserting a call to another function.
We already got something like this from modifying functions
from initial content, but adding such calls gives a much better
chance to execute an interesting amount of new code (calling
one of the new functions we generated ourselves, which could
contain anything).

Fuzzer: Interpose on existing exports

---

scripts/clusterfuzz/embed_wasms.py
test/lit/scripts/embed_wasms.lit

This is the inverse of `extract_wasms.py`: the previous script
extracted wasm files from JS, and this one can re-embed them
back in.
This can be useful when working with ClusterFuzz and Fuzzilli
testcases.

[Fuzzing] Add a script to embed wasm files into JS testcases

---

src/interpreter/interpreter.cpp
test/gtest/interpreter.cpp

Building on top of #7227, the following are implemented and tested:
- f32.add
- f32.sub
- f32.mul
- f32.div
- f32.sqrt
- f32.ceil
- f32.floor
- f32.trunc
- f32.nearbyint

[Interpreter] Float32

---

.github/workflows/ci.yml

If you pick a recent workflow run (here is the latest run on main https://github.com/WebAssembly/binaryen/actions/runs/13530775040 as of writing this PR) you'll see following at the bottom 
If you click of the link for this warning you'll be taken here https://github.com/actions/runner-images/issues/11101 . It states that the Ubuntu 20.04 runner was deprecated at the start of this month, and will be fully unsupported by the 1st April . Therefore in my opinion is worth removing the Ubuntu 20.04 job from the ci rather than risk trying to run on an unsupported runner. If you need to keep supporting this version of Ubuntu then a job could be created in a separate PR, which builds inside a Docker container with a Ubuntu 20.04 base image.

[ci] Update Ubuntu 20.04 ci job to Ubuntu 22.04

---

src/wasm-type.h
src/wasm/wasm-type.cpp
test/gtest/type-builder.cpp

Introduced in the Custom RTTs proposal, exact reference types are
referencdes to a particular heap type and not any of its subtypes. The
exception is that exact references to the bottom type of each heap type
hierarchy are subtypes of exact references to any other type in the
hierarchy. This maintains the property that each hierarchy of reference
types is a lattice.
Implement, construction, equality, hashing, subtyping, LUB, and GLB
operations for exact reference types, but do not yet use them in the IR
or implement parsing for them.

Implement exact reference types

---

src/interpreter/interpreter.cpp
test/gtest/interpreter.cpp

Building on top of #7227, the following are implemented and tested:
- i64.add
- i64.sub
- i64.mul
- i64.eq
- i64.ltS
- i64.ltU
- i64.gtS
- i64.gtU
While here, I added in relevant cases that leveraged the code added for the above instructions.
- i32.eq
- f32.eq
- f64.eq
- i32.ltS
- i32.ltU
- i32.gtS
- i32.ltU

[Interpreter] I64

---

src/interpreter/interpreter.cpp
test/gtest/interpreter.cpp

Building on #7227, implemented and tested the following:
- i32/i64.and
- i32/i64.or
- i32/i64.xor
- i32/i64.shl
- i32/i64.shrU
- i32/i64.shrS
- i32/i64.rotL
- i32/i64.rotR

[Interpreter] i32/i64 Bitwise Operators

---

.github/workflows/create_release.yml

If you look here https://github.com/WebAssembly/binaryen/actions/runs/13124901726 , you'll see that when the create_release.yml workflow you runs you get a warning that "The `set-output` command is deprecated and will be disabled soon". I believe this is the modern version of set-output. I got the suggestion from here https://stackoverflow.com/questions/75892082/warning-for-set-output-command-is-deprecated-and-will-be-disabled-soon-wont .

[ci] set-output changed to echoing to GITHUB_OUTPUT create_release.yml

---

src/tools/tool-options.h
src/wasm-binary.h
src/wasm-features.h
src/wasm/wasm-binary.cpp
src/wasm/wasm.cpp
test/binaryen.js/kitchen-sink.js.txt
test/example/c-api-kitchen-sink.txt
test/lit/help/wasm-as.test
test/lit/help/wasm-ctor-eval.test
test/lit/help/wasm-dis.test
test/lit/help/wasm-emscripten-finalize.test
test/lit/help/wasm-merge.test
test/lit/help/wasm-metadce.test
test/lit/help/wasm-opt.test
test/lit/help/wasm-reduce.test
test/lit/help/wasm-split.test
test/lit/help/wasm2js.test
test/passes/strip-target-features_roundtrip_print-features_all-features.txt

Although the proposal is called "Custom RTTs," the more precise term for
its main feature is "custom descriptors." To decrease long-term
confusion at the expense of some possible short-term confusion, name the
corresponding new feature "custom descriptors." This feature will guard
the use of both descriptor/describes clauses and exact reference types.

Add a custom descriptors feature

---

src/wasm/wasm-ir-builder.cpp
test/lit/parse-bad-gc-br_on-novalue.wast
test/lit/parse-bad-gc-cmpxchg-orders.wast

Internally we subtract 1 from the number of values while
processing such things, but if we start with 0 we'd overflow
and hit a confusing error later.
Fixes the last part of #7337

[Parser] Error properly on br_on* going to a target without a value

---

src/wasm/wasm-validator.cpp

For `struct.new`, `array.new`, `ref.func`, `ref.i31`, `cont.new`, and
`cont.bind`, check in the validator that the result type is a
non-nullable reference. This ensures that we have the most precise
possible type information for these instructions. The generic stale type
checker does not check this because finalizing these expressions does
not change their types.

Validate that allocations produce non-nullable references

---

src/passes/MergeSimilarFunctions.cpp
test/lit/passes/merge-similar-functions_all-features.wast
test/lit/passes/merge-similar-functions_types.wast

This patch makes MergeSimilarFunctions do a return_call when the module has tail-call enabled. This is not merely an optimization, but is crucial for correctness when optimizing wasm modules produced by GHC that relies on tail-call to do control flow transfers. Previously, -Oz would break tail-call enabled modules by making the control stack grow where it shouldn't.

MergeSimilarFunctions: do a return_call when possible

---

src/wasm-binary.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-stack.cpp
test/lit/basic/exact-references.wast

The binary format for casts needs to be extended to support exact
references. In particular, add new opcodes for `ref.test` and `ref.cast`
that take reference type immediates instead of heap type immediates. Use
two more bits in the flags immediate of `br_on_cast` and
`br_on_cast_fail` to encode the source and destination exactness.

Binary encoding and decoding of exact casts

---

scripts/bundle_clusterfuzz.py
scripts/clusterfuzz/run.py
scripts/fuzz_opt.py

V8 does not yet support custom descriptors, so update all fuzz handlers
that use it to avoid running when the feature is enabled. Since running
V8 is important, though, disable the feature most of the time, just like
we do for shared-everything.

Do not fuzz on V8 with custom descriptors enabled

---

CMakeLists.txt

Make it default to ON when using emscripten

Gate LTO in the Emscripten build behind the BYN_ENABLE_LTO CMake flag

---

src/wasm/wasm.cpp
test/lit/basic/exact-references.wast

Update the finalization of all instructions whose types (or sent types)
depend on their operand reference types to handle exact references
correctly. Specifically, update `ref.as_non_null`, `br_on_null`,
`br_on_non_null`, `br_on_cast`, and `br_on_cast_fail`. Also add TODOs on
all instructions that allocate new heap objects to remind us to make
their types exact in the future.

Update finalization for exact references

---

src/binaryen-c.cpp
src/binaryen-c.h
src/js/binaryen.js-post.js

This PR adds all current features to the C API. I reordered `BulkMemory` and `SignExt` to match the order defined in `wasm-features.h`.
Fixes #7361

Add all features to C API

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-exact.wast

The logic for optimizing ref.casts that are known to succeed did not
account for possible casts to exact null types, leading to it producing
invalid IR. Fix it and add a test.

Fix optimization of casts to exact null types

---

src/ir/possible-contents.cpp
test/lit/passes/gufa-tnh.wast

GUFA in TNH mode will infer that this will trap:
```wat
(func $foo (param $x)
(ref.cast $T (local.get $x))
)
(func $bar
(call $foo (X))
)
```
If X's type will cause a trap when cast to T, then we infer that the call
will trap, and optimize. However, we were missing a check for the
param being trampled,
```wat
(func $foo (param $x)
(local.set $x (Y))     ;; !!!!!!!!!!
(ref.cast $T (local.get $x))
)
```
Then if Y can be cast, we should not actually trap.
Fix this by just tracking which params are written to. We only look
in the first basic block anyhow, and traverse it in order, so that is
enough.
Fixes #7366

[Wasm GC] Fix GUFA on trampled params in TrapsNeverHappens mode

---

test/gtest/type-domains.cpp

First is an unused variable, second is an unneeded move.

Fix fuzztest compiler warnings [NFC]

---

.gitignore
CMakeLists.txt
third_party/CMakeLists.txt

and some minor drive-by fixes: gitignore Ninja in-tree build file, update mimalloc to latest stable release.
This gets rid of warnings in the mimalloc cmake/make step. See https://github.com/microsoft/mimalloc/issues/1031#issuecomment-2740351301 and https://github.com/microsoft/mimalloc/issues/1038.

Do not pass C++-only flag to C compiler

---

check.py

These means that the intermediate files don't conflict with each other and you can inspect them by name after the test run.

[test] Use test-specific filename when running spec tests

---

CMakeLists.txt
third_party/CMakeLists.txt

Since mimalloc is linked statically into the Binaryen tools, none of its
files need to be installed with Binaryen.
Also use CMAKE_SYSTEM_NAME instead of LINUX, as the latter was introduced in CMake 3.25

Exclude the mimalloc files from the Binaryen install

---

src/passes/I64ToI32Lowering.cpp
test/lit/passes/flatten_i64-to-i32-lowering.wast

We recently started updating RefFunc types in I64ToI32Lowering to ensure
that their types matched the updated types of their functions. But the
way we updated the types of RefFunc expressions and Functions were not
the same. When updating Functions that return i64, we replace the result
type with i32 and use a global to propagate the remaining bits to the
caller. Previously when updating RefFunc result types, we would instead
split i64s into pairs of i32s, depending on multivalue to lower the
type. Update the logic for updating RefFunc results to match the
existing logic for updating Functions.

Fix RefFunc type updating in I64ToI32Lowering

---

src/wasm-type.h
src/wasm/wasm-type.cpp
test/spec/descriptors.wast

To ensure soundness, there are very particular rules about how described
and descriptor type declarations must relate to one another and their
supertypes. Implement and test these rules.

Validate descriptor declarations

---

test/gtest/type-builder.cpp

The length macro used in a type test in type-builder.cpp was causing
extremely long compile times in some compilers. Use a lambda instead to
fix it. This makes the error messages less useful when a test fails, but
under normal circumstances the test should not be failing, so this is a
good trade off.
Fixes #7383.

[NFC] Use a lambda instead of a macro in gtest

---

src/tools/wasm-as.cpp
src/tools/wasm-ctor-eval.cpp
src/tools/wasm-merge.cpp
src/tools/wasm-metadce.cpp
src/tools/wasm-opt.cpp
test/lit/help/wasm-as.test
test/lit/help/wasm-ctor-eval.test
test/lit/help/wasm-merge.test
test/lit/help/wasm-metadce.test
test/lit/help/wasm-opt.test

Our tools all stated that if `-o` is not provided, we write to stdout by default.
But that is not true - we do nothing in that case. I believe the rationale is
that we write text to stdout by default in say wasm2js, but for wasm-opt etc.
we don't want to write binary to stdout (as that is dangerous).
It might be worth rethinking this in theory, but this has been the behavior
for many many years, so seems safest to update the help text.

[NFC] Fix help text for tools that emit binary

---

CHANGELOG.md
CMakeLists.txt

Given the big speedup in our official release binaries for Linux, this seems
useful to get to users quickly.

Release version 123

---

src/passes/Outlining.cpp
src/passes/hash-stringify-walker.cpp
src/passes/stringify-walker.h
src/support/CMakeLists.txt
src/support/intervals.cpp
src/support/intervals.h
test/gtest/CMakeLists.txt
test/gtest/intervals.cpp
test/lit/passes/outlining.wast

While determining whether repeat sequences of instructions are candidates for outlining, remove sequences that overlap, giving weight to sequences that are longer and appear more frequently.

[Outlining] Remove overlapping sequences

---

test/gtest/stringify.cpp

In the interest of improved test readability, moved the return part of the FilterBranches test into its own test. Also condensed the test to remove the unnecessary consts.

[Outlining] Separating Filter Branch & Return Tests

---

src/passes/RemoveUnusedModuleElements.cpp

Globals that refer to globals lead to more work. This work cannot be
infinite, as globals only refer to previous ones, but  this can end up as
exponential time, so this is actually important to optimize here.
For exponential time, it is enough to have a chain of these:
```wat
(global $global$N+1 (ref $A) (struct.new $A
(global.get $global$N)
(global.get $global$N)
))
```
That is, two references from each global to its predecessor, causing
us to double the work each time we scan back.
Fixes #7405 (where the above pattern appears)

Avoid repeated work in RemoveUnusedModuleElements::addReferences() [NFC]

---

src/passes/Outlining.cpp
src/passes/stringify-walker.h
test/lit/passes/outlining.wast

When the last instruction of the outlined sequence is unreachable, we need to insert an unreachable instruction immediately after the call to the outlined function. This maintains the unreachable type in the original scope of the outlined sequence.

[Outlining] Insert Unreachable

---

src/passes/hash-stringify-walker.cpp
src/passes/stringify-walker-impl.h
src/passes/stringify-walker.h
test/lit/passes/outlining.wast

Fixes a bug where stringify walker was not removing outlining candidates with restricted expressions because they were in nested control flow.

[Outlining] Filter in nested control flow

---

src/binaryen-c.cpp
src/binaryen-c.h
src/js/binaryen.js-post.js
test/binaryen.js/kitchen-sink.js
test/example/c-api-kitchen-sink.c

This PR adds `BinaryenGetStart` to the C api and the corresponding `module.getStart` JS wrapper.

Allow JS and C to read the start function of a module

---

src/passes/Print.cpp

Rename the function in anticipation of exact heap types appearing in the
IR. When an expression like `StructNew` has an exact heap type, the
`exact` does not appear in `struct.new $foo`. In this case `$foo` is not
the full heap type, but rather than name of the heap type definition.

[NFC] printHeapType => printHeapTypeName in Print.cpp

---

src/passes/Print.cpp
src/tools/wasm-fuzz-types.cpp
src/wasm-type-printing.h
src/wasm-type.h
src/wasm.h
src/wasm/wasm-type.cpp

Now that we have exact heap types, non-abstract heap types no longer
correspond 1:1 with heap type definitions. We previously used a single
type, `HeapType`, to represent both heap types and heap type
definitions. Now that `HeapType` can represent multiple heap types
corresponding to the same definition, there is a new class of potential
bugs in which code that expects `HeapType` values to map 1:1 with heap
type definitions observes both an exact and inexact heap type for the
same definition.
To eliminate this class of bugs, introduce a new type, `HeapTypeDef`,
whose values do correspond 1:1 with heap type definitions. `HeapTypeDef`
is a subclass of `HeapType`, so it supports all the same functionality,
but it cannot represent exact heap types because its constructor clears
the exact bit. …

[NFC] Introduce HeapTypeDef and use it for printing

---

src/passes/Print.cpp
test/lit/passes/gsi-debug.wast

`printTypeOrName`, used to print types for BINARYEN_PRINT_FULL and a few
other niche use cases, previously had bespoke printing for references
that did not follow the standard format. To improve the output and
reduce the number of ways we print types, change it to use the standard
printing utility.

Use standard type printing for BINARYEN_PRINT_FULL

---

src/ir/module-utils.cpp
src/ir/module-utils.h
src/ir/subtypes.h
src/parser/contexts.h
src/parser/parse-2-typedefs.cpp
src/parser/parse-3-implicit-types.cpp
src/parser/parse-4-module-types.cpp
src/parser/parse-5-defs.cpp
src/parser/wat-parser-internal.h
src/parser/wat-parser.cpp
src/passes/NameTypes.cpp
src/passes/Print.cpp
src/passes/TypeMerging.cpp
src/passes/TypeSSA.cpp
src/tools/fuzzing.h
src/tools/fuzzing/fuzzing.cpp
src/tools/fuzzing/heap-types.cpp
src/tools/fuzzing/heap-types.h
src/tools/wasm-fuzz-types.cpp
src/wasm-binary.h
src/wasm-type-ordering.h
src/wasm-type.h
src/wasm/wasm-type.cpp
test/gtest/possible-contents.cpp
test/gtest/type-builder.cpp
test/gtest/type-domains.cpp
test/gtest/type-domains.h

Update `TypeBuilder::build` to return a vector of `HeapTypeDef`.
Although `HeapTypeDef` is implicitly convertible to `HeapType`,
containers of `HeapTypeDef` are not implicitly convertible to containers
of `HeapType`, so this change requires several other utilities and
passes to start using `HeapTypeDef` directly and transitively.

[NFC] Use HeapTypeDef more widely

---

src/tools/fuzzing/random.h

The random number generator adds into `xorFactor` in various places.
This variable was previously signed, so overflows from these adds were
UB. Make it unsigned to avoid UB.

Avoid overflow UB in random.cpp

---

src/passes/TypeRefining.cpp
test/lit/passes/type-refining-gufa.wast

TypeRefiningGUFA refines struct types based on the types that flow into fields,
and looks past the immediate types in the IR. As a result, it can require
casts when we end up storing something that appears not-sufficiently-
refined to wasm validation rules, in ways that cannot occur with normal
TypeRefining.
The specific problem that can happen is that casts are disallowed in
globals, so we must be careful to not refine too much there.

[GC] Fix global handling in TypeRefiningGUFA

---

scripts/bundle_clusterfuzz.py

The emsdk's linux builds now include mimalloc, so we must bundle
them for ClusterFuzz, same as we already do for libc++.

ClusterFuzz: Bundle mimalloc

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-mvp.wast

Current peephole optimization for unsigned(x) <= -1 => i32(1) is restrictive—actually we could replace the condition with const (1 here), while preserving any necessary side effects from the original expression or its children(by getDroppedChildrenAndAppend).
Fixes #7434

OptimizeInstructions: Optimize (unsigned)x <= -1  ==>   i32(1) even with side effects

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-mvp.wast

Current peephole optimization for `(unsigned)x > -1   ==>   i32(0)` is restrictive—actually we could replace the condition with const (1 here), while preserving any necessary side effects from the original expression or its children(by getDroppedChildrenAndAppend).
Fixes: #7435

OptimizeInstructions: Optimize (unsigned)x > -1   ==>   i32(0) even with side effects

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-mvp.wast

Current peephole optimization for  `x | -1   ==>   -1` is restrictive—actually we could replace the condition with const (1 here), while preserving any necessary side effects from the original expression or its children(by getDroppedChildrenAndAppend).
Fixes: #7438

OptimizeInstructions: Optimize  x | -1   ==>   -1 even with side effects

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-mvp.wast

Current peephole optimization for unsigned(x) >= 0 => i32(1) is restrictive—actually we could replace the condition with const (1 here), while preserving any necessary side effects from the original expression or its children(by getDroppedChildrenAndAppend).
Fixes #7425

OptimizeInstructions: Optimize `unsigned(x) >= 0 => i32(1)` even with side effects

---

src/passes/TypeRefining.cpp
test/lit/passes/type-refining-gufa.wast

We must first find global restrictions, then propagate, so that the
restrictions propagate.

[GC] Fix order of operations in TypeRefiningGUFA: Restrictions must propagate

---

src/binaryen-c.cpp
src/tools/execution-results.h
src/tools/wasm-ctor-eval.cpp
src/tools/wasm-shell.cpp
src/wasm-interpreter.h

Previously the constructor ran the start method and other initialization. Doing
that in an explicit function that the user calls makes it possible to do things in
the middle. The specific thing I would like to do in the middle is have a function
to change the interpreter instance's mode to "reject as nonconstant relaxed SIMD",
but I've wanted this in the past too, and worked around it - seems best to just
fix it.
Adding more flags to the constructor is another option, but there are already
several, and more in the parent classes, and several levels of inheritance through
which all such options must be forwarded, which is annoying.

[NFC] Add an explicit ModuleRunner.start()

---

scripts/fuzz_opt.py

That spec allows for differences between VMs, so we must disable
most comparisons (e.g. V8 and Binaryen can disagree, and also V8
can disagree with itself on an optimized version of a wasm, if
Binaryen precomputed something there).

[SIMD] Avoid comparing V8 to other VMs when relaxed SIMD is enabled

---

test/binaryen.js/sideffects.js

The equality operator (`==`) has higher operator precedence than bitwise OR (`|`), meaning that `a == b | c` is interpreted like `(a == b) | c` and not `a == (b | c)`, how it was intended.

Fix operator precedence in Binaryen.js tests

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-mvp.wast
test/wasm2js/bulk-memory.2asm.js.opt

Current peephole optimization for `unsigned(x) < 0 => i32(0)` is restrictive—actually we could replace the condition with const (zero here), while preserving any necessary side effects from the original expression or its children(by `getDroppedChildrenAndAppend`).
Fixes #7418

OptimizeInstructions: Optimize unsigned(x) < 0 => i32(0) even with side effects

---

src/source-map.h
src/wasm-binary.h
src/wasm.h
src/wasm/source-map.cpp
src/wasm/wasm-binary.cpp
test/gtest/source-map.cpp

This is in preparation for fixing #6805.
Aside from cleaning up and reusing more code, it allows optional fields in the
source map and random access to those fields, rather than walking through
the whole JSON file just once. (It does keep the current behavior of
walking through the actual mappings in a single pass synchronized with reading
the binary). It also adds some unit tests.

Switch source map parsing to use the JSON parser

---

scripts/fuzz_opt.py

Relaxed SIMD prevents comparisons between VMs, but v8-liftoff can be
compared to v8-turboshaft for example, as it is the same VM in another
mode.
To do this, replace the `can_compare_to_others` with a function that
considers a specific other VM.

[Fuzzer] Compare V8 variants

---

src/passes/Outlining.cpp
src/passes/stringify-walker.h

Improve the quality of debug logs during outlining by:
- reorder logs to occur before corresponding asserts
- rename the debug logging macro used in Outlining.cpp so its not defined twice
- add a parameter to function outline to thread the data needed for logging
- add a parameters to struct OutliningSequence to connect the sequence back to its location in the stringified binary

[Outlining] Improve logging

---

scripts/clang-tidy-diff.sh
src/tools/fuzzing/random.h

Setting error-on-exit just makes it exit with error 1 after writing to `/dev/null`
(see line 31). After removing that, it properly continues and shows the
error.
See the last 3 commits in https://github.com/WebAssembly/binaryen/pull/7475  for an example. Without this fix, no diff is shown.

Fix clang-tidy

---

scripts/fuzz_opt.py

`--liftoff/--no-liftoff` are enough to control which tier we get. Removing the
extra flags avoids a warning.
Test with `--no-wasm-generic-wrapper` sometimes, which was suggested.

Fuzzer: Improve V8 flags

---

src/passes/OptimizeInstructions.cpp

Just to simplify code a little. We have similar helpers for `effects()` etc.

[NFC] Add getFallthrough* helpers in OptimizeInstructions

---

scripts/clusterfuzz/run.py
scripts/fuzz_opt.py
test/unit/test_cluster_fuzz.py

This is necessary with latest V8, since
https://github.com/v8/v8/commit/af887e07511cce2831b96edf7e3d9a13bc8c9df8
This is not ideal, see comment in the source, but also seems hard to
improve on.

[EH] Use V8 flag to allow mixed old and new EH [NFC]

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-mvp.wast

Current peephole optimization for `bool(x) | 1   ==>   1` is restrictive—actually we could replace the condition with const (1 here), while preserving any necessary side effects from the original expression or its children(by `getDroppedChildrenAndAppend`).
Fixes: #7477

OptimizeInstructions: Optimize bool(x) | 1 ==> 1 even with side effects

---

scripts/clusterfuzz/run.py
scripts/fuzz_opt.py
test/unit/test_cluster_fuzz.py

ClusterFuzz already applies this flag, and it implies the EH flag, so we might
as well do it the way V8 does it. This is simpler, though it does mean we are
testing something even more different than production - but in the way V8
believes is best for fuzzing, at least.

[Fuzzing] Simplify V8 fuzzing flags: use --fuzzing over specific EH flag

---

scripts/emcc-tests.sh

This makes it easier to run the tests while keeping the source tree clean.

Allow emcc-tests.sh to be invoked from outside the Binaryen source directory

---

scripts/test/binaryenjs.py

Instead create `<filename>.mjs` named after each test.
Test output now looks like this:
```
$ ./check.py --binaryen-bin=emcc-build/bin binaryenjs_wasm
warning: Binaryen not found (or has not been successfully built to bin/ ?
executing:  /usr/bin/node -e process.stdout.write(typeof WebAssembly)
[ checking binaryen.js testcases (/usr/local/google/home/sbc/dev/wasm/binaryen/emcc-build/bin/binaryen_wasm.js)... ]
executing:  /usr/bin/node atomics.mjs
executing:  /usr/bin/node closed-world.mjs
executing:  /usr/bin/node copy-expression.mjs
executing:  /usr/bin/node custom-section.mjs
...
```
Previously:
```
$ ./check.py --binaryen-bin=emcc-build/bin binaryenjs_wasm
warning: Binaryen not found (or has not been successfully built to bin/ ?
executing:  /usr/bin/node -e process.stdout.write(typeof …
```

[test] Avoid reusing a.mjs for all js tests.

---

src/ir/possible-contents.cpp
test/lit/passes/gufa-cast-all-exact.wast

The logic for joining nullability into a PossibleContents cone value did
not previously preserve the exactness of the type in the cone value,
causing assertion failures.

Propagate exactness when combining GUFA possible contents

---

src/ir/bits.h
test/lit/passes/optimize-instructions-mvp.wast

The result of integer division cannot have more bits than the dividend. However, currently rule for `div` doesn't cover the `0 / 0`. It returns `1` for `0 / 0` binary operation (line 198 below).
https://github.com/WebAssembly/binaryen/blob/e6f1c53a2052d7c1e9e06ace64c7c2833aa82a7d/src/ir/bits.h#L194-L201
Fixes bug, and missed optimization in #7471

Fix incorrect result in getMaxBits for 0 / 0

---

src/passes/StringLifting.cpp
test/lit/passes/string-lifting-section-erase.wast

After we lift the strings section into stringref, we don't need the section any
more, and leaving it around could cause problems with repeated lifting/
lowering operations (which would be very much possible with #7540). In
particular, without erasing it, we'd accumulate such sections over time.

[Strings] Erase the strings section after StringLifting

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-mvp.wast

Currently, `wasm-opt` cannot optimize the code as expected: `(unsigned)x < 0 ==> i32(0)`.
```webassembly
(i32.lt_u
(i32.load $0 (i32.const 0) )
(block (result i32)
(i32.store $0
(i32.const 0)
(i32.const 0)
)
(i32.const 0)
)
)
```
It should have been optimized after `merge-blocks`, as the `store` could have been hoisted. However, the load and store cannot be reordered, preventing `wasm-opt` from doing so. 
This can be addressed in `optimizeInstructions` by using `fallthrough` to hoist the constant zero, enabling further optimizations.
Fixes: #7455

Use fallthrough in optimizeInstructions to further optimize (unsigned)x < 0 ==> i32(0)

---

src/wasm-interpreter.h

The interpreter previously inspected subtyping for nullability and heap
types separately when executing casts. Simplify this to just check
subtyping on the combined type. This is NFC for now, but will have the
happy side effect of handling exactness correctly once we type
allocations as exact and interpret exact casts.

[NFC] Simplify interpretation of casts

---

src/ir/possible-contents.cpp
test/lit/passes/gufa-cast-all-exact.wast
test/lit/passes/gufa-refs.wast

Use the standard utility rather than reimplementing type intersection.
The new code is simpler, shorter, and properly supports exactness,
avoiding an assertion failure in the added test case. The other
functional change is that when one of the intersected heap types is
bottom and the type GLB is a non-nullable reference to bottom, the
result of the intersection is `None` where it was previously a `Cone`.

Use GLB in PossibleContents::intersect

---

src/ir/module-utils.cpp

Previously public type collection worked by collecting all types in the
module, classifying their visibility, then picking out all the public
types to return. However, visibility classification requires directly
finding the public types from the imports and exports in the first
place, so the initial step of collecting all the types was unnecessary.
Refactor the code so `getPublicHeapTypes` calculates the public types
directly from the imports and exports and `classifyTypes` uses those
results to classify visibility only when collecting all types from the
module anyway.

[NFC] Make public type collection more efficient

---

scripts/test/fuzzing.py

Fix ignored test names so the tests are properly ignored.

Fix typos in fuzzing.py

---

src/passes/MinimizeRecGroups.cpp
src/wasm-type.h
src/wasm/wasm-type.cpp

This was one of @danleh 's top findings in the [mimalloc investigation](https://github.com/WebAssembly/binaryen/issues/5561#issuecomment-2714778022),
where this method accounted for 25% (!) of all allocations.
I measured various sizes of SmallVectors and indeed it is possible to
get noticeably faster here: this PR is a 5% speedup for `-O3` as a whole,
tested on a large Java testcase and a large Kotlin testcase.
The change to MinimizeRecGroups is NFC (the order is reversed, but I don't
think it matters?). This is needed to compile, as our current SmallVector
doesn't have reverse iteration support (I looked into that for a few minutes
but it was not trivial to add; anyhow, the new code is idiomatic in the
codebase, I think).
cc #4165

[NFC] Use a SmallVector for HeapType children

---

src/passes/RemoveUnusedBrs.cpp
test/lit/passes/remove-unused-brs.wast

If a block ends with a `br_if` followed by a value that is the same as the `br_if`'s value (and has no side effects), the value of `br_if` and `br_if` itself are redundant and can be removed. For example:
``` webassembly
(block $block (result i32)
..
(drop
(br_if $block
(value)
(condition)
)
)
(value)
)
=>
(block $block (result i32)
..
(drop
(condition)
)
(value)
)
```
Fixes: #7489

Optimize block tails where a dropped br_if's value is redundant

---

src/wasm-binary.h
src/wasm-stack.h
src/wasm/wasm-binary.cpp
src/wasm/wasm-stack.cpp

We track debug info in two ways: for source maps, and for DWARF. DWARF needs
more information, not just the start of each expression's location but also the end
and delimiters (else for an if) as well. The existing code slightly mixed the two
together, which is annoying because code annotations require the same tracking
DWARF does. To improve that, this PR refactors the code to cleanly separate the
two forms of tracking:
* writeSourceMapLocation is now the only method that source maps use
* trackExpressionStart|End|Delimiter is now used by DWARF (and soon code
annotations).
As a result,
* BinaryInstWriter no longer needs a sourceMap param. It was using !sourceMap
in the sense of "maybe DWARF", but given custom annotations we'll need more
anyhow. Simplify the code by letting the parent …

[NFC] Cleanly separate expression tracking from source maps

---

src/analysis/monotone-analyzer-impl.h
src/analysis/monotone-analyzer.h

For backward analyzer, it is helpful to have a function to init state in the "entry point" (exit block).

add `evaluateFunctionExit` for backward analyzer in `monotone-analyzer`

---

src/wasm-binary.h
src/wasm/wasm-binary.cpp

This allows generating sections in side buffers, rather than just on the
main output buffer ("o"). This will help code annotations, where it is
useful to emit them to a side buffer, then copy them into the right
place (which is before the code section, but we must emit the code
first, to know the offsets for the annotations, so reordering is
unavoidable).

[NFC] Move optimal-LEB emitting logic to a shared place

---

src/wasm-binary.h
src/wasm/wasm-binary.cpp

This will allow 95% of the code to be shared for binary writing, between
branch hints and inline hints for example. They have almost identical
formats in structure, differing only in the hint itself and section name.
Also prepare for multiple code annotations sections.

[NFC] Refactor a generic function for binary writing of a code annotations section

---

README.md

Mention that ref.func and allocation instructions are always typed as
exact internally. Clarify that binary writing will generalize types as
necessary. Remove some other outdated information about the supported
text format and strings as well.

Update README for exact types

---

src/passes/Print.cpp
test/lit/branch-hinting-printing.wast

The code saved and restored `std::cout`, not the current stream... and the
current stream is `std::cout` in most tests, so this went unnoticed. Printing
from `wasm-dis` works otherwise apparently, and the bug showed up there.

Fix Branch Hinting iostream printing

---

src/wasm/wasm-ir-builder.cpp
test/lit/validation/array-new-fixed.wast

Fix parsing error on array.new_fixed on non-array

---

src/passes/StringLowering.cpp

Now that `string` is a subtype of `extern`, the null type for strings
and externrefs is the same, so we no longer need to fix up nulls in
StringLowering.
Unblocks #7601.

[NFC] Remove StringLowering::replaceNulls

---

src/ir/public-type-validator.cpp

this fixes an unused variable warning in opt mode.

add missing maybe_unused annotation

---

.github/workflows/ci.yml
src/tools/wasm-reduce.cpp
src/wasm/wasm-binary.cpp

All our testing has asserts enabled, to catch issues. This adds a build mode
for no-asserts, just to catch compile errors like #7610

[CI] Add a no-asserts build

---

src/ir/possible-contents.cpp
test/lit/passes/type-refining-gufa.wast

`filterPackedDataReads` had an assertion that the read field existed,
but it was possible for this to not be the case when the reference being
read from was null. Avoid the assertion failure by checking for this
case and filtering the read results to `none` because a read from null
will never return.

Fix assertion failure in type-refining-gufa

---

src/passes/StringLowering.cpp
test/lit/passes/string-lowering_types.wast

We manually update the types of functions that have size 1 rec groups,
because we need to update imports and exports, even though that
changes the ABI - something TypeMapper does not do, but StringLowering
wants. See the existing comment for details.
That code updated those types, but did just themselves - it did not go
through the code to find RefFuncs of them, which left them with the old
type, causing errors. To fix this, tell TypeUpdater to map those types (it
doesn't know it needs to automatically, since we manually handled them).

[Strings] Fix StringLowering of reference-taken functions

---

src/wasm/wasm-ir-builder.cpp
test/lit/branch-hinting.wast

The old code forgot the If scope when it started the Else, so any if-else would get
a binary location span that started in the else (and ends in the right place).
To fix this, note the if start location when we have it, and don't trample.
Fixes branch hints on if-elses.

Fix IRBuilder location tracking of If starts

---

src/passes/TypeMerging.cpp
test/lit/passes/type-merging-exact.wast
test/lit/passes/type-merging.wast

If we merge siblings to their parent, they may end up equal:
```wat
(select (result A))
(B1)
(B2)
)
=>
(select (result (exact A))) ;; result is now exact
(A) ;; both are
(A) ;; now A
)
```
In such cases we must refinalize, as the LUB is now exact.

Fix missing Exact type ReFinalization in TypeMerging

---

.github/workflows/ci.yml
.github/workflows/create_release.yml

According to https://github.blog/changelog/2025-04-14-windows-arm64-hosted-runners-now-available-in-public-preview/ Windows arm Github runners are now available for free for public repositories. Therefore I have added them to binaryen ci.

Add Windows 11 arm to ci

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-mvp.wast

There are so many rules for `and`, but we still cannot optimize the following one:
```
(i32.and
(i32.eqz
(i32.load $0
(i32.const 0)
)
)
(i32.const 4)
)
```
to zero.
Adding rule for `add`: `any boolean & (No overlap with boolean's LSB)  ==> 0`
Fixes: #7481

OptimizeInstruction: Optimize any boolean & (No overlap with boolean's LSB)  ==> 0

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-mvp.wast

Previously we set such locals to 64 bits, even if they were i32. This
interacted with #7505 which compared the bits to the true bits of
the type, which led to 64 != 32, which suggested we knew something
nontrivial about the bits.

OptimizeInstructions: Fix max bits of a local with an unreachable set

---

src/tools/wasm-reduce.cpp

Rather than executing the reduction command twice for every candidate,
once to get the return code and once to capture stdout, just run it once
and capture both.

[wasm-reduce] Get the return code from pclose

---

src/tools/wasm-reduce.cpp

Now that we only run the reduction command once per candidate rather
than twice, we don't need to divide the measured execution time in half.

[wasm-reduce] Fix time calculation

---

src/passes/TupleOptimization.cpp
test/lit/passes/tuple-optimization.wast

We previously counted a local use for all `local.tee` operands to
`tuple.extract`, even if the `local.tee` was unreachable and had a
non-tuple local. This led to an assertion failure later. Fix the issue
by disregarding `local.tee` operands of `tuple.extract` if they don't
have tuple locals.

Fix assertion failure in TupleOptimization

---

src/ir/possible-contents.h
src/support/utilities.h

This allows building without asserts, with -Wunused-but-set-variable

Mark a variable only used in an assert

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-exact.wast

We must not forget exactness there.

OptimizeInstructions: Fix merging of exact cast + ref.as_non_null

---

third_party/setup.py

On Linux we use "ubuntu" as the platform string when searching for a wabt release tarball and search for a file that ends with "-ubuntu.tar.gz".
However wabt release tarballs mention Ubuntu version as well, e.g. the current release name is "wabt-1.0.37-ubuntu-20.04.tar.gz". The current check with `endswith` does not match the current release tarball names.
Update the name matching to use the regex `^wabt-.*-ubuntu-.*.tar.gz$`, which matches version numbers after the "ubuntu" part.

Fix wabt setup script

---

src/wasm-interpreter.h

Don't drop the segment in the module as the module can be used again later.
Instead add the segment to the dropped segments set.
Fixes the fuzzing issue described in https://github.com/WebAssembly/binaryen/pull/7658#issuecomment-2985124026.

Fix elem.drop interpretation

---

.gitignore

This is a standard CMake file used to configure builds in IDEs.

Add CMakeUserPresets.json to .gitignore

---

src/literal.h
src/wasm-interpreter.h
src/wasm/wasm.cpp
test/spec/ref.get_desc.wast

Add a descriptor to the GCData stored in a reference value. The
descriptor itself is another literal representing either a null if there
is no descriptor or otherwise a reference to the descriptor. Update
the interpretation of struct.new to set the descriptor when allocating
types with descriptors and then retrieve the descriptor when
interpreting ref.get_desc.

[Custom Descriptors] Interpret ref.get_desc

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-gc.wast

When optimizing `add` operations, OptimizeInstructions calculates the
max bits of the operands and shifts that value to produce a bit mask.
When an operand is unreachable, it is arbitrarily considered to have a
max bits value of 64, even for 32-bit operations. This leads to UB in
the shift. Fix the problem by returning before the shift in this case.

Fix UB in OptimizeInstructions

---

src/passes/Heap2Local.cpp
test/lit/passes/heap2local-desc.wast

Insert a ref.as_non_null when optimizing struct.new with a nullable
descriptor to preserve the trap if the descriptor is null.

[Custom Descriptors] Preserve trap in Heap2Local

---

scripts/fuzz_opt.py
src/passes/RemoveUnusedModuleElements.cpp
test/lit/passes/remove-unused-module-elements-refs-descriptors.wast

Update RemoveUnusedModuleElements to preserve traps in global and
element segment initializers due to null or possibly-null descriptors
passed to struct.new. For every struct.new that appears with a
descriptor in an initializer, find the origin of the descrpitor value.
If it is a null literal or a nullable import, keep the global containing
the struct.new because it either will or will possibly trap.

[Custom Descriptors] Keep trapping initializers

---

src/passes/OptimizeInstructions.cpp
test/lit/passes/optimize-instructions-desc.wast

When all of the non-descriptor operands to struct.new have default
values, we can optimize the struct.new to struct.new_default in
OptimizeInstructions. When we do this, we drop all the children with
side effects. This previously included the descriptor operand, even
though we did not clear the descriptor operand from the StructNew parent
expression, causing the descriptor operand to appear twice in the IR.
This is invalid and could lead to assertion failures elsewhere.
To avoid the problem, clear the descriptor operand while we call the
utility to drop the StructNew children and restore it afterward. This is
somewhat ugly, but better than duplicating the functionality of the
utility, except ignoring the descriptor.

[Custom Descriptors] Fix bug optimizing struct.new

---

scripts/fuzz_opt.py

Normally we want to fix it up (remove NaNs etc., as we do normally), but the
changes in each fuzzing iteration can make things hard to debug. Add an
env var to simply trust the given wasm file and use it without changes.
Diff without whitespace is a little smaller.

[Fuzzing] Add an env var to avoid modifying the given wasm file in fuzz_opt.py

---

src/passes/TypeMerging.cpp
src/wasm-type.h
test/lit/passes/type-merging-desc.wast

TypeMerging cannot merge one type in a descriptor chain into another
type without merging the type's full descriptor chain into the other
type's full descriptor chain. Because of this, each descriptor chain
acts as a single unit in the DFA minimization algorithm.
Update TypeMerging so that descriptor types do not get their own shapes,
but rather are included in the shapes of their base described types. To
make this simpler, add a new utility for easily iterating over a type's
descriptor chain.

[Custom Descriptors] Merge descriptors correctly

---

src/ir/metadata.cpp
test/lit/passes/duplicate-function-elimination_branch-hints.wast

Ignore debug info there, allowing e.g. DuplicateFunctionElimination to
merge functions identical in all ways but for debug info.

[Debug Info] Prioritize optimization over debug info in metadata comparisons

---

src/passes/Unsubtyping.cpp
test/lit/passes/unsubtyping.wast

Speed up Unsubtyping by over 2x via algorithmic and other improvements.
The most expensive part of the Unsubtyping analysis is the handling of
casts. For each cast source and destination pair, each type that remains
a subtype of the source and was originally a subtype of the destination
must remain a subtype of the destination for the cast to continue
succeeding.
Previously, Unsubtyping analyzed these cast relationships for all types
as a single unit of work whenever it reached a fixed point from
examining other sources of subtyping constraints. This led to duplicated
work because the subtype, cast source, and cast destination triples
analyzed once would be analyzed again the next time casts were
considered.
Avoid this duplicated cast analysis by incrementally analyzing casts
whenever a …

[NFC] Speed up Unsubtyping

---

src/ir/function-utils.h
test/lit/passes/duplicate-function-elimination_branch-hints.wast

Our comparisons are only used in optimization atm, and we decided not to
consider metadata when merging functions, as that is what LLVM does: it
will fold code together without carefully checking if profiling info matches,
and without even trying to fix up that profiling info later.
For more on LLVM, see
https://github.com/WebAssembly/binaryen/pull/7733#discussion_r2214579266
but basically it will just merge two instructions with different branch_weights
and keep the first of the two, no matter what.

Revert part of #7715: Ignore metadata in function comparisons

---

src/ir/ReFinalize.cpp
test/lit/passes/remove-unused-brs-desc.wast
test/lit/passes/vacuum_all-features.wast
test/passes/fuzz_metrics_noprint.bin.txt
test/passes/fuzz_metrics_passes_noprint.bin.txt
test/passes/precompute_all-features.txt
test/passes/remove-unused-brs_enable-multivalue.txt
test/passes/remove-unused-brs_generate-stack-ir_print-stack-ir.txt

ReFinalize replaces unreachable branches with unreachable blocks so that
it can possibly propagate the unreachability up to the former branch
target. It previously only did this for branches whose sent values (as
opposed to their conditions) were unreachable, except for BrOn, where it
could erroneously optimize when the sent value was reachable and the
descriptor was unreachable. This was incorrect because `replaceUntaken`
assumed that the sent value was unreachable.
Rather than fix the bug for BrOn, generalize `replaceUntaken` to work
no matter whether the sent value or the other child exists or is the
source of unreachability.

Improve ReFinalize::replaceUntaken

---

src/tools/wasm-metadce.cpp
test/lit/metadce/remove-unused-module-elements.wat
test/lit/metadce/remove-unused-module-elements.wat.json

wasm-metadce does a graph analysis to find unreached things, and then
cleans up using RemoveUnusedModuleElements. That pass become more
powerful in #7728, which led to a situation where an import was removed
from the wasm, but wasm-metadce did not report that it had removed it.
This led to unneeded code in the JS (it kept sending that import,
unnecessarily). This was a harmless minor waste of JS size, but it did cause
a test error on Emscripten (#7747), as it parses that JS to check some
things, and it found an import in JS without a use in wasm.
To fix that, check if that pass removed imports, and report them.

[Metadce] Report removed imports due to RemoveUnusedModuleElements

---

src/passes/Unsubtyping.cpp
test/lit/passes/unsubtyping-desc.wast

We already partially handled the interaction between descriptors and
subtyping by ensuring that B <: A implies B.desc <: A.desc if B.desc and
A.desc both exist. However, there was a subtler situation we did not
handle:
A -> A.desc
^      ^
|    B.desc
|      ^
C -> C.desc
This subtyping violates the constraint that the descriptor of C's
immediate supertype must be the immediate supertype of C's descriptor.
To fix this, find the described type B to insert between C and A before
establishing C.desc <: B.desc <: A.desc.

[Custom Descriptors] Ensure descriptor validity in Unsubtyping

---

src/passes/J2CLItableMerging.cpp
test/lit/passes/j2cl-merge-itables.wast

Update J2CLItableMerging to consider types whose vtables are custom descriptors

Update J2CLItableMerging to consider custom descriptors

---

src/passes/AbstractTypeRefining.cpp
test/lit/passes/abstract-type-refining-desc.wast

When AbstractTypeRefining optimized out descriptor casts targeting
uninstantiated types, it previously did not preserve traps on null
descriptors. Preserve the traps by inserting a ref.as_non_null on
nullable descriptor operands.

[Custom Descriptors] Preserve traps in AbstractTypeRefining

---

src/passes/Heap2Local.cpp
test/lit/passes/heap2local-desc.wast

When Heap2Local optimized an allocation that flowed into a ref.cast_desc
that admitted nulls as the cast descriptor, it reasoned that the only
way the original cast could have succeeded was if the cast reference was
null, so Heap2Local optimized the cast to a drop of the descriptor
operand followed by a cast to null of the reference operand.
This missed the edge case where the same allocation flows in as both the
reference and descriptor operands. In that case, the optimized
allocation passed the cast to null even though the original cast would
have failed. Fix the bug by only using the code path that produces the
null cast when the optimized allocation does not also flow into the cast
as the reference operand. Casts where the same allocations flows in as
both operands are now optimized …

[Custom Descriptors] Edge case in Heap2Local

---

src/tools/wasm-split/wasm-split.cpp
test/lit/wasm-split/multi-split.wast

For non-multi-split, we decide whether to minimize the export names based on the debug info flag:
https://github.com/WebAssembly/binaryen/blob/96362ebe5f3eedc9d9a53694a16e375670cd53b1/src/tools/wasm-split/wasm-split.cpp#L333
But in multi-split we always minimize them. This makes it also dependent on the debug flag as in the case of the two-way split.

[wasm-split] Don't always minimizee export names in multi-split

---

src/ir/features.h

This is needed to prevent fuzzer errors.

[Relaxed SIMD] Add missing relaxed entries in features.h

---

scripts/fuzz_opt.py

The first time the Clusterfuzz handler runs, it does a lot of setup work
that can be annoying when trying to run the fuzzer briefly to smoke out
very obvious problems. To avoid that annoyance, we do not run the
Clusterfuzz handler until we have already fuzzed for at least 30
seconds. However, we used to control this in the `can_run_on_wasm`
method, which caused reproducibility issues because the number of calls
to `random` functions would differ before and after that 30-second
cutoff. Specifically, `relevant_handlers` would have a different size
before and after that cutoff, so the number of `random` calls to compute
`filtered_handlers` would be different.
To avoid these reproducibility problems, simply return early from the
`handle` method of the Clusterfuzz handler if it has not yet …

Fix determinism of Clusterfuzz fuzz handler

---

src/wasm-interpreter.h
src/wasm/literal.cpp
test/lit/exec/cont_simple.wast
test/spec/cont.wast

In the simple case, all parameters are bound. This is common in the
spec test, and will unblock a bunch of stuff there.
To do this, add full support for resuming without a resume expression,
that is, without a Suspend that we need to unwind back to. Specifically,
when we resume a bound continuation, the only thing we need to do
when resuming is to apply the bound arguments, and then
continue execution normally.

[Stack Switching] Implement the simple case of cont.bind

---

src/wasm-interpreter.h
src/wasm/literal.cpp
test/spec/cont.wast

The key fix here is that we don't know what the continuation
function (the thing to call, to continue onwards) is, at the time of
suspending. Rather, that function is called from a resume, to
resume execution from there, so do so when we handle a
suspend in a Resume.
And, when we resume "through" a suspend (due to a nested
suspend), then we should just rewind the call stack.
With this, the next big spec testcase passes.
Also fix a minor issue with trying to put breaking values on
the value stack - only value stack values go there. The new
testcase enabled here trips on that.
Also improve some debug logging.

[Stack Switching] Handle nested continuations

---

src/passes/Precompute.cpp
test/lit/passes/precompute-gc.wast

Precompute has two modes, one where we ignore effects. We were
caching the effectless results for where the normal mode (which cares
about effects) would reuse them, leading to bugs.
Fixes a regression from #7763, another after #7766. We were not using the
cache fully, before, and caches are bug-prone, sadly. I have an idea for a
larger refactor to make this more robust, but I wanted to get this two-line
fix out first.

Precompute: Do not cache calculations that ignore effects

---

src/ir/child-typer.h
src/passes/Precompute.cpp
src/passes/StringLowering.cpp
src/tools/fuzzing/fuzzing.cpp
src/wasm-type.h
src/wasm/wasm-ir-builder.cpp
src/wasm/wasm-type.cpp
src/wasm/wasm-validator.cpp
test/lit/basic/unreachable-string-new.wast
test/lit/passes/precompute-strings.wast
test/lit/passes/simplify-locals-strings.wast
test/lit/passes/string-lowering-instructions.wast
test/lit/strings.wast
test/lit/wat-kitchen-sink.wast

The operations for creating strings from arrays and decoding strings
into arrays previously accepted any array types with i8 or i16 elements,
depending on the specific operation. This violates the principal types
properties of the WebAssembly type system and was a bug in the design of
the defunct stringref proposal.
In practice, these operations are only useful when lowered to calls to
the standard JS string builtins, which have strict requirements about
what array types they accept. Reflect those requirements by restricting
the array types we allow to be used with the string Expressions in our
IR. This allows us to remove the special casing for these operations in
ChildTyper.
Since Precompute only worked on string operations taking immutable
arrays, but those arrays are now invalid to …

Require specific array types for string ops

---

src/tools/fuzzing/fuzzing.cpp

The fuzzer tries to finish quickly by falling back to creating
local.gets or constants after it reaches the end of its random input.
The former option should only be used inside a funtion context, though.

[Fuzzer] Do not make local.get without function context

---

src/ir/child-typer.h
src/passes/TypeSSA.cpp
src/wasm/wasm-ir-builder.cpp

When ChildTyper does not have enough type information to generate type
constraints (for example, because a child whose type provides crucial
information is unreachable), it previously allowed the user to determine
whether to return early or not. But not returning early would then lead
to an assertion failure or other bad behavior, so it is never a
reasonable choice. The only real choice a user has is to return early
and ignore the situation (which is what TypeSSA wants) or to fail loudly
because this should never happen (which is what IRBuilder wants).
Simplify the callback to allow customizing this behavior but not whether
the early return ocurrs.

[NFC] Update ChildTyper callback for unknown constaints

---

test/unit/test_cluster_fuzz.py

Our statistics naturally drift over time. Update some of those values.
Also we now pass V8 an experimental pass. Filter that out to avoid noise in the
tests.

ClusterFuzz updates [NFC]

---

src/support/small_vector.h

SmallVector previously (partially) implemented its own random access
iterators using a pointer to the parent SmallVector and an index, but
ParentIndexIterator is a more complete implementation of the same
iterator design. Reduce duplication and fix missing iterator
functionality by using ParentIndexIterator.

[NFC] Use ParentIndexIterator in SmallVector

---

src/tools/fuzzing/fuzzing.cpp
src/tools/fuzzing/random.cpp
test/passes/fuzz_metrics_noprint.bin.txt
test/passes/fuzz_metrics_passes_noprint.bin.txt
test/passes/translate-to-fuzz_all-features_metrics_noprint.txt

Add a new env var to control the fuzzer input size,
```
BINARYEN_FUZZER_MAX_BYTES
```
When set, we will truncate the random bytes we receive as
input in translate-to-fuzz. This makes it simple to bisect on the
input, for example.
Also make the fuzzer notice that the input has run out in more
cases, and stop emitting things. This makes small inputs to
the fuzzer smaller in output.

Fuzzer: Improve handling of small inputs and their debugging

---

src/passes/TypeMerging.cpp
test/lit/passes/type-merging-desc.wast

When merging sibling types, we must first partition the types by their
supertypes and shapes. With custom descriptors, we consider full
descriptor chains as single units to be merged. We had updated the shape
partitioning to account for this, but not the supertype partitioning. As
a result, we were incorrectly merging chains with different descriptor
supertypes as long as the base described types had no supertype.
Fix the bug by partitioning not just on the base described type's
supertype, but the sequence of all supertypes in the chain.

[Custom Descriptors] Fix TypeMerging sibling criteria

---

src/passes/Print.cpp

Rather than always printing the table like in #7839, this prints the table only when either reference types is enabled or the table index is not 0 (even if the features section or `--enable-reference-types` is not provided)
This addresses the concern in #7802, while not printing table when it is not necessary.
There is no test changes because
- At the moment wasm-dis enables all features so wasm-dis always prints tables in `call_indirect`s. This will change in #7840.
- wasm-opt results didn't print table so far when reference-types is not enabled, and all `call_indirect`s in those tests have table index 0.

Print tables for call_indirects for nonzero table index

---

src/passes/TypeMerging.cpp
test/lit/passes/type-merging-desc.wast

Due to an accidental use of the wrong variable, we were not properly
checking for casts to descriptor types that should have blocked merging.

[Custom Descriptors] Fix TypeMerging cast check

---

src/ir/struct-utils.h
src/passes/ConstantFieldPropagation.cpp
src/passes/GlobalTypeOptimization.cpp

This mostly just avoids code duplication, but the CFP version was
actually also inefficient (combine returned true more than it
should, possibly leading to wasted work).

[NFC] Share the "simple combinable bool" logic among StructValues users

---

src/tools/wasm-ctor-eval.cpp
test/lit/ctor-eval/cont-noserial.wast

#7877 gave up when we couldn't serialize things, in various situations. But
one of the cases, when we can't serialize the results, we checked AFTER we
already "commit" the changes to the module. That is, we need to check for
errors and stop if we find any, and only then apply execution results to the
module, and we added a check that was after the application.
To fix this, we need to be careful and know that if we will care about the
serialization of the results then we cannot execute continuations, as they
may end up needing to be serialized. Doing anything more precise would
be significantly more complex.

[Stack Switching] wasm-ctor-eval: Properly handle continuation serialization errors in results

---

src/tools/fuzzing/fuzzing.cpp

When we create a global we properly do `value = makeConst()`. However, if
we have nested structs, we ended up possibly calling `make(field.type)`,
which could emit anything.
To fix that, check for a function context in the core `make()`.
Replaces #7817

Fuzzer: Fix root cause of emitting non-constant expressions in global positions

---

scripts/test/fuzzing.py

The subtype chains in that test exceed the limits on subtyping depth in real engines.

Add reorder-types-real.wast to fuzzer block list

---

src/ir/type-updating.cpp
src/passes/GlobalTypeOptimization.cpp
test/lit/passes/gto-desc-tnh.wast
test/lit/passes/gto-desc.wast

GTO tries to optimize out unused descriptor types, but sometimes cannot
because the descriptor type must remain a descriptor to be a valid
supertype of a subtype that will remain a descriptor. To optimize the
original described type to not have a descriptor while simultaneously
keeping the descriptor a valid supertype, insert a new, trivial
placeholder type for the descriptor to describe. Since this new type is
not otherwise used in the module, it should be able to be optimized out
after subsequent rounds of unsubtyping and other optimizations.

[Custom Descriptors] Use placeholder describees in GTO

---

.github/workflows/ci.yml
.github/workflows/create_release.yml
src/support/threads.cpp
test/lit/lit.cfg.py
test/lit/num_cores.wast

This reports that number of CPUs that are actually usable by the current process.
This means that I can do something like `taskset -c 0 emcc hello.c -O2` and the internal call to `wasm-opt` within emcc will only use a single core.
Ideally this would work on macOS and windows too, but I'm not even sure how easy it is to control affinity on those OSes.

Honor CPU affinity in ThreadPool::getNumCores

---

scripts/fuzz_opt.py
src/passes/pass.cpp

This pass has been used by j2wasm for a while, and is useful there, so
enable it for general use.
This pass can grow code size in some cases, if it emits a `ref.test` that is not
later optimized out. For that reason only enable it in `-O3+`, that is, when
optimizing aggressively for size.
Also fuzz this pass more.

[GC] Use cfp-reftest pass

---

src/passes/GlobalTypeOptimization.cpp
test/lit/passes/gto-desc.wast

When we optimize a descriptor to describe a placeholder type because the
original described type no longer needs a descriptor, we were not
previously ensuring that the sharedness of the placeholder matched the
sharedness of the descriptor type. Make sure the shareness matches to
avoid validation errors when rebuilding the types.

[Custom Descriptors] Fix shared GTO placeholders

---

test/lit/exec/runtime-nonexact.wast

The test verifies that even if validation accepts something, the interpreter
checks subtyping at runtime, allowing us to detect (in principle) bugs in
validation (or missing/incorrect validation rules).

[NFC] Test we error at runtime on subtyping errors

---

third_party/llvm-project/dwarf2yaml.cpp

Hello,
I'm getting a segfault while running wasm-opt on my wasm (it started with version 123)
```bash
$> wasm-opt --enable-threads -g -O4 -ol 100 -s 0 -all -o out.wasm in.wasm
fish: Job 1, 'wasm-opt --enable-threads -g -O…' terminated by signal SIGSEGV (Address boundary error)
```
After a little sesion with gdb, found out in `third_party/llvm-project/dwarf2yaml.cpp:122` **the `CU` variables equals the end of the iterator**.
WASM analysis:
```bash
$> wasm-objdump -h in.wasm
[...]
Custom start=0x037bac4b end=0x0508e814 (size=0x018d3bc9) "name"
Custom start=0x0508e816 end=0x0508e822 (size=0x0000000c) ".debug_info"
Custom start=0x0508e824 end=0x0508e82f (size=0x0000000b) ".debug_loc"
Custom start=0x0508e831 end=0x0508e83f (size=0x0000000e) ".debug_ranges"
[...]
$>  wasm-objdump -j .debug_loc …
```

fix: segf with empty dwarf .debug_loc

---

src/tools/fuzzing.h
src/tools/fuzzing/fuzzing.cpp

Leaving a small chance to only modify existing functions, rather than
always add lots of new ones, opens opportunities for very precise
small testcases to not get overly-modified. E.g., if a small testcase
checks for turning a field immutable, adding many functions will
likely add sets to all fields, changing the global picture substantially.

Fuzzer: Do not always add functions

---

src/tools/fuzzing/fuzzing.cpp

Before, we always made a new, simple (closed, and not a subtype of
anything) type. Now we pick an interesting one sometimes.
In particular, sometimes we'll get an open type here, allowing #7935
to do more (as it can only optimize DAE results on an open type).

Fuzzer: Pick an interesting function type for our functions

---

src/passes/GlobalTypeOptimization.cpp
test/lit/passes/gto-desc.wast

Do not leave unreachable ref.cast_desc instructions with descriptors
arguments that have been optimized to no longer be descriptors. This was
intended to be inluded in #7937.

[Custom Descriptors] Fix GTO after #7937

---

src/passes/SimplifyGlobals.cpp
test/lit/passes/simplify-globals-gc.wast

An exported global can have extra uses, which prevent folding its value
into others.

SimplifyGlobals: Fix folding of exports

---

src/wasm-interpreter.h

std::function can already be empty, so wrapping it in std::optional is
redundant.

[NFC] Remove unnecessary std::optional in FuncData

---

src/ir/module-splitting.cpp

This reorders the numbered list in the beginning of the file that describes the process so that the order matches the actual process.
Also removes a few outdated lines of comments and an unnecessarily include.

[wasm-split] Reorder comments

---

scripts/test/shared.py

Bring in the latest upstream testsuite to include Wasm 3.0 tests,
including for multi-memory, memory64, and GC proposals. Update the list
of skipped tests to remove some tests that newly pass, add new failing
tests, and generally update given failure reasons. Also add logic to
skip all tests for proposals we do not yet support, including custom
page sizes and wide arithmetic.

Update spec test suite for Wasm 3.0
